### ISSUE TITLE
--show-diff-on-failure does not respect --color

### ISSUE THREAD

**Issue by chadrik** [pre-commit/pre-commit#1007]
I'm running `pre-commit` on gitlab, and I noticed that the diffs produced when `--show-diff-on-failure` is enabled do not respect `--color=always`.  

It looks like a pretty easy fix:   we just need to pass the `--color` setting to `git diff`.  It supports the same "auto", "always", "never" settings as `pre-commit`.  

`git diff --color` [documentation](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---colorltwhengt).

code in question: https://github.com/pre-commit/pre-commit/blob/master/pre_commit/commands/run.py#L227

**Comment by asottile** [comment]
want to submit a PR?

**Comment by chadrik** [comment]
Sure!

**Comment by asottile** [comment]
@chadrik ping!

**Comment by mandarvaze** [comment]
@chadrik If you are busy/not working on this, can I give it a try ? 
I came here looking for "good-first-issue"

**Comment by asottile** [comment]
@mandarvaze I say go for it 👍  -- let me know if you want some more directed pointers about where this code is and what to pass through :)

**Comment by chadrik** [comment]
Hi, sorry I’ve been busy.  Please feel free to go for it!

**Comment by asottile** [comment]
this has been released as part of [v1.17.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.17.0) -- thanks again for the issue!

**Comment by chadrik** [comment]
Thanks for the solution!
