### ISSUE TITLE
Question: what command should I run after updating .pre-commit-config.yaml?

### ISSUE THREAD

**Issue by goerz** [pre-commit/pre-commit#1008]
I can't tell from the documentation what I should do after modifying `.pre-commit-config.yaml`. Is it `pre-commit install`, `pre-commit install -f`, `pre-commit install-hooks`, or `pre-commit autoupdate`?

**Comment by asottile** [comment]
~technically you don't have to run anything, on the next operation that `pre-commit` gets invoked it'll install hooks to match your configuration (note: this assumes you've run `pre-commit install` at some point already, or are going to use `pre-commit run ...` to run the hooks manually)

You could run `pre-commit install-hooks` if you want to eagerly install the hooks, but it's technically not necessary

**Comment by goerz** [comment]
Ah! That wasn't clear to me at all, but that's very nice! Thanks!

**Comment by asottile** [comment]
cheers -- if there's something that could be improved here I'd happily accept a PR!  https://github.com/pre-commit/pre-commit.github.io
