### ISSUE TITLE
ability to define hooks disabled by default

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1009]
There are tools that are very expensive to run each time (`yapf` being one such example) and this does not play well with the current pre-commit behavior of running all checks by default.

Someone recommented adding extra pre-commit hook configuration file for the heavy tests and running it while mentioning the custom configuration file.

Still this approach does not make the tool easy to run, it would be much easier if we could trigger optional checks based on existence of an environment variable or an extra parameter, without having to deal with two configuration files.

Another approach would be if pre-commit would allow to run some checks only on modified files. Now the `--all` option applies to all hooks which makes impossible to run all files for some hooks and only modified ones for the heavy ones.

**Comment by asottile** [comment]
`stages: [manual] ` is what you're looking for i believe

**Comment by asottile** [comment]
if not comment back and I'll reopen -- thanks!
