### ISSUE TITLE
Unable to download latest node version

### ISSUE THREAD

**Issue by GeordieR** [pre-commit/pre-commit#1017]
When trying to execute a pre-commit that requires node I get an `[SSL: CERTIFICATE_VERIFY_FAILED]` error. Sorry If I'm missing something straight forward, any help is appreciated.

## Error
```
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/geordier/.cache/pre-commit/repobvSbe4/node_env-default')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nodeenv.py", line 1480, in <module>
        main()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nodeenv.py", line 1067, in main
        opt.node = get_last_stable_node_version()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nodeenv.py", line 997, in get_last_stable_node_version
        response = urlopen('https://%s/dist/latest/' % src_domain)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nodeenv.py", line 564, in urlopen
        return urllib2.urlopen(req)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
        context=self._context)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
```

## YAML
```yaml
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    name: Python Linting
- repo: https://github.com/prettier/prettier
  rev: "1.17.0"
  hooks:
  - id: prettier
    name: Javascript Linting
```

## Versions
pre-commit: `1.15.2`
git: `2.20.1`
python: `2.7.16` / `3.7.2`
OSX: `10.14.4`

**Comment by asottile** [comment]
hmm, I've seen this ssl issue on macos before (not during pre-commit though), something about the certs never being updated 

if I recall correctly, the fix is this?

```bash
/Applications/Python\ 2.7/Install\ Certificates.command
```

(basin 2.7 on the version above, you might need `sudo` I don't remember)

**Comment by GeordieR** [comment]
That worked! Thank for your help.

**Comment by asottile** [comment]
Awesome! Good to hear! macos python dumpster fire strikes again!

**Comment by jackton1** [comment]
For any one that encounters this issue.

Replace lines below using your python version i.e 2.6 ,3.5+

```bash
$ pip install certifi
$ python3.6 -m certifi
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/certifi/cacert.pem
$ cd /Library/Frameworks/Python.framework/Versions/3.6/etc/openssl/
$ ln -s /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.7/site-packages/certifi/cacert.pem cert.pem
```

**Comment by asottile** [comment]
oh, did this not work for you? https://github.com/pre-commit/pre-commit/issues/1017#issuecomment-488214828

**Comment by jackton1** [comment]
Not really. Unable to locate Cerificates.command.

**Comment by asottile** [comment]
hmmm the standard distribution should include that -- what happens if you `ls -al '/Applications/Python 3.6/'`

**Comment by jackton1** [comment]
Python installed at `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`

**Comment by asottile** [comment]
Right, the python installer has two parts, a "Framework" and an "Application" -- the application usually contains that little `.command` script -- if you Cmd+Space you should be able to find it by searching for "Install Certificates"

**Comment by kvalkhof75** [comment]
While it is most likely not a pre-commit issue, I just got stuck on this error while trying to make a Windows docker image with pre-commit. (The Linux image of course works just fine of course.)

`mcr.microsoft.com/windows/servercore:ltsc2019`
... (install python3, git and pre-commit)
```
pip install certifi
py -m certifi
git init
pre-commit install-hooks
```

- The `.pre-commit-config.yaml` has prettier.
- Not using certifi also gets the error.
- Google does not help me, or I am not using the correct search terms...

Any ideas?

**Comment by asottile** [comment]
@kvalkhof75 this issue is about macos, please make a **new issue** with complete details (you've not given enough to even start trying to reproduce the problem, put yourselves in my shoes and give enough details about how one could go about coming to the same problems you're having)

**Comment by prd-anh-ho-trung** [comment]
this run !!!
