### ISSUE TITLE
Compute rule of file exclusion

### ISSUE THREAD

**Issue by jcoux** [pre-commit/pre-commit#1035]
Hi,

I need a way to compute the rule of file exclusion.
Depending on files content, we need to exclude (or not) folders from pre-commit checks.

Example:
```
- folder1
  - file1
    - contains "text_to_search"
- folder2
  - file2
    - not contains "text_to_search"
```
In this example, we need to exclude folder1 to pre-commit.
But if tomorrow, the file1 will not contain my "text_to_search", we want to automatically have the check played on folder1.

Do we have a way to do that with current code of `pre-commit`?
If not, do you accept a future pull request which will add a global `exclude_script` configuration which will returns the list of files/folders to exclude?

Thanks in advance,
Julien.

**Comment by asottile** [comment]
We don't have such a thing, and it would be prohibitively expensive to implement and maintain (and very very niche, I don't really see anyone but you using this).

What I'd suggest is you encode this logic into your hook such that it handles this itself

**Comment by asottile** [comment]
An example of a hook which does this already if you want some prior art: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_added_large_files.py

It filters the list of input files to just those that were added in the commit

**Comment by jcoux** [comment]
Thanks for your answers and informations, we will try to do it into a hook.
