### ISSUE TITLE
FileNotFoundError when config installed on a different path

### ISSUE THREAD

**Issue by mitzkia** [pre-commit/pre-commit#1037]
Update:
While I wrote this issue I have found that `pre-commit autoupdate` has also a `--config` option.
My question is could `autoupdate` find my previously configured (in a proper way) config file?
Or Could `autoupdate` display a better error message: 
"please use with --config=[path to config]"?

Original Issue:
Reproduction:
1, pre-commit install
```
$ pre-commit install --config=dir/subdir/.pre-commit-config.yaml
```

2, run autoupdate
```
$ pre-commit autoupdate
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '.pre-commit-config.yaml'
```

pre-commit version: `pre-commit 1.16.1`

**Comment by asottile** [comment]
this is expected, you want `pre-commit autoupdate --config=dir/subdir/.pre-commit-config.yaml`

the `--config` argument to `install` just writes that configuration into `.git/hooks/pre-commit` -- it doesn't set any state other than that

**Comment by asottile** [comment]
to your point, one thing that could be improved here is to make it an argument parsing error if `--config` doesn't exist, instead of falling through to when the config gets loaded for the first time

that would be a custom `type=...` here that does the right thing: https://github.com/pre-commit/pre-commit/blob/77947f212e7b88a479dbe6feebc60a9f773e8c13/pre_commit/main.py#L49

**Comment by mitzkia** [comment]
Hi, thank you for the answer and a possible solution.
I think this argument parsing solution could help here.

Thanks

**Comment by asottile** [comment]
I think for now I'm going to close this and the associated PR :( -- the case is rare enough and the change potentially breaks some legitimate workflows.  thank you again for the issue and I'm sorry it didn't work out in the end <3
