### ISSUE TITLE
Run pre-commit after a git cherry-pick

### ISSUE THREAD

**Issue by mitzkia** [pre-commit/pre-commit#1038]
My question is it possible to set pre-commit to triggered by `git cherry-pick`?

My use-case is:
- While cherry-picking git commits from other branch/repo (where pre-commit is not configured) I would like to ensure that the cherry-picked code is passed on my local .pre-commit-config.yaml configuration.

**Comment by asottile** [comment]
`git` for whatever reason don't run hooks on cherry-pick / rebase.  You can manually `pre-commit run --all-files` or `pre-commit run --source HEAD^ --origin HEAD` (if you just want the lastest commit)

**Comment by asottile** [comment]
You can also `git cherry-pick --no-commit` and then `git commit` (no arguments) to trigger the hooks as well on a cherry-pick

**Comment by mitzkia** [comment]
Hi, thank you for the answer and the possible solutions.
I think for me the `git cherry-pick --no-commit` and then `git commit` will work. 
Thanks.
