### ISSUE TITLE
Cannot install via Puppet

### ISSUE THREAD

**Issue by pillarsdotnet** [pre-commit/pre-commit#1039]
Using the [`puppet-python`](https://github.com/voxpupuli/puppet-python) moodule to install the `pre-commit` pip results in the following command and output:

```
pip --log /tmp/pip.log install --upgrade --no-binary :all: pre-commit
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pre-commit
  Using cached https://files.pythonhosted.org/packages/58/ab/ce9c21f70238d150c3efb14fc6230017b24729cb482815ba65feba8a2ceb/pre_commit-1.16.1.tar.gz
  WARNING: Generating metadata for package pre-commit produced metadata for project name unknown. Fix your #egg=pre-commit fragments.
Installing collected packages: unknown
  Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
  Running setup.py install for unknown ... done
Successfully installed unknown-0.0.0
```

Is this normal and expected behavior?

**Comment by pillarsdotnet** [comment]
Cross-posted: https://github.com/voxpupuli/puppet-python/issues/481

**Comment by asottile** [comment]
your setuptools version is too old, either upgrade that or remove `--no-binary :all:`

**Comment by pillarsdotnet** [comment]
@asottile  -- Sure enough, installing the latest `setuptools` pip fixed the problem.

Is there a way to encode that dependency into the `pip` information so that the relationship is more clear to the installer?

Or is `pip` unable to resolve version dependencies?

**Comment by pillarsdotnet** [comment]
Hmm... apparently it's a [work-in-progress](https://github.com/pypa/pip/issues/988).

**Comment by asottile** [comment]
it's too early to really have any control there

it also looks like puppet-python is doing the wrong thing here -- it's assuming that if `wheel` isn't installed that pip can't install from wheels, which is completely wrong :S

**Comment by asottile** [comment]
this fixes the puppet module: https://github.com/voxpupuli/puppet-python/pull/483

**Comment by pillarsdotnet** [comment]
Thanks!

**Comment by asottile** [comment]
If you could review and/or approve that PR that would be great (even if you don't have merge, every bit of support helps!)
