### ISSUE TITLE
Not possible to install python3 from EPEL with this module.

### ISSUE THREAD

**Issue by pillarsdotnet** [pre-commit/pre-commit#1040]
It does not appear to be possible, using this module, to install Python3 on Centos-7.

The EPEL package name is [`python36`](https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python36-3.6.8-1.el7.x86_64.rpm)

I've tried setting `python::version` to each of the following values, to no avail:

* `3`
* `'3'`
* `'36'`
* `'3.6'`
* `'python36'`
* `'python3.6'`
* `'rh-python36'`
* `'rh-python3.6'`

**Comment by pillarsdotnet** [comment]
Sorry; wrong project.

**Comment by asottile** [comment]
ah cheers -- I was very confused 😆
