### ISSUE TITLE
make hook as optional

### ISSUE THREAD

**Issue by lokesh1729** [pre-commit/pre-commit#1057]
hey,

first of all thanks for the great framework, it's awesome. I have a config where I have `pylint`, `flake8`, `black` and `isort`. I want to mark `black` and `isort` as optional hooks because when I run, both `black` and `isort` make changes to the files. I want them to run but the failure/success of the commit shouldn't depend upon them... a few months back I only had `black` in my config and it used to work fine... I don't know but recently, if the files were changed during the commit, then the hook is failing.... is there a way to stop if the files were changed don't mark it fail or make a hook as optional ????

**Comment by lokesh1729** [comment]
I will explain the scenario, I have `black` and `isort` both configured... what's happening is `black` doesn't do import optimization so it formats the code first and it make changes to the code, then `isort` runs and optimize imports... so, no matter how many times I run, there is no way that the commit will get succeed because every time both will make changes and the commits will fail...

**Comment by asottile** [comment]
I think what you want instead is to change how `isort` is configured so it is compatible with `black`

**Comment by asottile** [comment]
perhaps you're looking for https://github.com/python/black/issues/127

something like this?

```ini
[settings]
multi_line_output=3
line_length=88
include_trailing_comma=true
```

**Comment by spaceone** [comment]
Another use case for optional hooks would be, to allow "compilerla/conventional-pre-commit" to be added for those who already use conventional-commit-messages but don't block others, who don't do it yet.
