### ISSUE TITLE
Error: cannot lock ref/Unable to create file

### ISSUE THREAD

**Issue by x249wang** [pre-commit/pre-commit#1058]
I keep getting the following error when trying to use `pre-commit run --all-files` on my repository (I was able to use it successfully a few weeks ago). I've tried reinstalling pre-commit, as well as cloning my repository again.

```
[INFO] Initializing environment for https://github.com/codespell-project/codespell.
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Program Files\\Git\\mingw64\\bin\\git.exe', 'fetch', 'origin', '--tags')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    From https://github.com/codespell-project/codespell
     * [new branch]      dict              -> origin/dict
     * [new branch]      master            -> origin/master
     * [new branch]      peternewman-aspell-dict-check -> origin/peternewman-aspell-dict-check
     * [new branch]      peternewman-bodgy -> origin/peternewman-bodgy
     * [new branch]      pr-skip           -> origin/pr-skip
    error: cannot lock ref 'refs/remotes/origin/pr/aux': Unable to create 'C:/Users/<user>/.cache/pre-commit/repo5tf14_g0/.git/refs/remotes/origin/pr/aux.lock': No such file or directory
     ! [new branch]      pr/aux            -> origin/pr/aux  (unable to update local ref)
     * [new branch]      pr/fix-install    -> origin/pr/fix-install
     * [new branch]      v1.0.x            -> origin/v1.0.x
     * [new branch]      v1.1.x            -> origin/v1.1.x
     * [new branch]      v1.2.x            -> origin/v1.2.x
     * [new tag]         1.10.0            -> 1.10.0
     * [new tag]         log               -> log
     * [new tag]         v0.9              -> v0.9
     * [new tag]         v1.0              -> v1.0
     * [new tag]         v1.0-rc1          -> v1.0-rc1
     * [new tag]         v1.0-rc2          -> v1.0-rc2
     * [new tag]         v1.0-rc3          -> v1.0-rc3
     * [new tag]         v1.0.1            -> v1.0.1
     * [new tag]         v1.0.2            -> v1.0.2
     * [new tag]         v1.0.3            -> v1.0.3
     * [new tag]         v1.1              -> v1.1
     * [new tag]         v1.1-rc1          -> v1.1-rc1
     * [new tag]         v1.1-rc2          -> v1.1-rc2
     * [new tag]         v1.1.1            -> v1.1.1
     * [new tag]         v1.10.0           -> v1.10.0
     * [new tag]         v1.11.0           -> v1.11.0
     * [new tag]         v1.12.0           -> v1.12.0
     * [new tag]         v1.13.0           -> v1.13.0
     * [new tag]         v1.14.0           -> v1.14.0
     * [new tag]         v1.15.0           -> v1.15.0
     * [new tag]         v1.2              -> v1.2
     * [new tag]         v1.3              -> v1.3
     * [new tag]         v1.4              -> v1.4
     * [new tag]         v1.5              -> v1.5
     * [new tag]         v1.6              -> v1.6
     * [new tag]         v1.7              -> v1.7
     * [new tag]         v1.8              -> v1.8
     * [new tag]         v1.9.0            -> v1.9.0
     * [new tag]         v1.9.1            -> v1.9.1
     * [new tag]         v1.9.2            -> v1.9.2
```

**Comment by asottile** [comment]
weird, what happens if you run the following commands outside of pre-commit?

```bash
git --version
git init x
cd x
git remote add origin https://github.com/codespell-project/codespell
git fetch origin --tags
```

You may also want to try upgrading `git` since that looks like a bug in `git` itself

**Comment by x249wang** [comment]
> weird, what happens if you run the following commands outside of pre-commit?
> 
> ```shell
> git --version
> git init x
> cd x
> git remote add origin https://github.com/codespell-project/codespell
> git fetch origin --tags
> ```
> 
> You may also want to try upgrading `git` since that looks like a bug in `git` itself

Hi @asottile , I upgraded `git`, so now I'm using `git version 2.22.0.windows.1`. 

Running the code you suggested gives the same error. I'm able to run with the other hooks if I skip this particular one. Perhaps it has to do with the repo?...

**Comment by asottile** [comment]
yeah if those branches got deleted in that repo it would probably clone fine, it looks like those are from old PRs and probably a quick issue on their github tracker would solve this problem :+1:

**Comment by larsoner** [comment]
I have removed the `codespell` branches with `/` in the name

**Comment by asottile** [comment]
Awesome, thanks @larsoner! :tada:

**Comment by asottile** [comment]
I mailed the git mailing list, the helpfully pointed out that it's not the directory but the name "aux":

> AUX is a [reserved] filename on Windows. Quoting from that source:
>
>     Do not use the following reserved names for the name of a file:
>     CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7,
>     COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and
>     LPT9. Also avoid these names followed immediately by an
>     extension...
>
> The default Git "ref store" is filesystem-based, so a branch named
> "aux" is problematic. Other ref store implementations would not be
> subject to this limitation (though I'm not sure what the state of the
> others is -- someone with more knowledge can probably answer that).
>
> [reserved]: https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#naming-conventions

**Comment by larsoner** [comment]
Good thing I removed aggressively, `aux` was already part of the cull :)

**Comment by x249wang** [comment]
It all works now. Thank you!
