### ISSUE TITLE
Pre-commit hangs waiting for GPG signature

### ISSUE THREAD

**Issue by wmayner** [pre-commit/pre-commit#1063]
It seems that the ncurses pinentry program that usually appears when GPG asks me to enter my key isn't running properly, and so it hangs waiting for input.

Looks like someone else ran into this on SO: https://stackoverflow.com/questions/55107243/pre-commit-does-not-allow-gpg-code-signing

**Comment by asottile** [comment]
Do you have a reproduction? I don't have much to go off of from this report

**Comment by wmayner** [comment]
Sorry, this was a problem with gpg-agent, not pre-commit.
