### ISSUE TITLE
--hook-type installation option is a confusing name

### ISSUE THREAD

**Issue by esciara** [pre-commit/pre-commit#1065]
Hi,

Following up on https://github.com/jorisroovers/gitlint/issues/86#issuecomment-503273121 , there is some confusion around the naming of the `--hook-type` option.

Indeed, when reading the `pre-commit` doc, there is less a type of hook than a stage on which a hook is installed. Hence, using `hook-type` as seems odd and does not convey the behavior that is set through the `default_stages` top-level property and the `stages` hook property.

What do you think ?

**Comment by asottile** [comment]
yeah `--stage` might be a better name -- `stages` was added after `--hook-type` and it was never updated

would you like to add an alias for that?

**Comment by esciara** [comment]
Actually, thinking about it... it is more the property names `default_stages` and `stages` that are confusing... and some of their possible values (`commit`, `push`) are different to the ones used in `--hook-type` (`pre-commit`, `pre-push`), where as other stay the same `prepare-commit-msg`, `commit-msg`)

Would it not be less confusing to have a `default_hook_types` and `hook_types` properties with the same `pre-commit`, `pre-push`, `prepare-commit-msg` and `commit-msg` as `--hook-type`?

**Comment by esciara** [comment]
> yeah `--stage` might be a better name -- `stages` was added after `--hook-type` and it was never updated
> 
> would you like to add an alias for that?

Hmm... not sure which way would be the best... What does your experience say? Are people talking more about hook-types or stages?

**Comment by esciara** [comment]
And would not add an alias when options are different (`pre-commit` <-> `commit`, etc.) that would confuse the hell out of people...

**Comment by asottile** [comment]
to be honest, I'm not exactly sure :laughing:  -- personally I really only use the `.git/hooks/pre-commit` features and don't use `commit-msg` / `pre-push` / `prepare-commit-msg` myself

**Comment by asottile** [comment]
we didn't really come to any conclusion here, I'm going to close this since I don't think it's actionable.  the names are at least documented and have a schema
