### ISSUE TITLE
How to cache pre-commit hooks on travis

### ISSUE THREAD

**Issue by talha131** [pre-commit/pre-commit#1066]
Running pre-commit takes almost 1 minute in my [repo](https://github.com/Pelican-Elegant/elegant). Travis logs are available [here](https://travis-ci.org/Pelican-Elegant/elegant/jobs/549343328).

I tried to fix this issue by adding `/home/.cache/pre-commit/` to the [`cache`](https://github.com/Pelican-Elegant/elegant/blob/master/.travis.yml#L18-L22).

```yaml
cache:
- pip
- directories:
  - /home/.cache/pre-commit/
```

But it had no effect. I still get the following output

```log
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/prettier/prettier.
[INFO] Initializing environment for https://github.com/python/black.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/python/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

How do I cache pre-commit hooks so that on subsequent builds, it won't take a whole minute.

**Comment by asottile** [comment]
this is what I used with success before switching to azure pipelines: https://github.com/pre-commit/pre-commit/blob/c577ed92e7482094614a64c8b692daebea3a1a15/.travis.yml#L32

**Comment by talha131** [comment]
Thank you @asottile for the prompt response. This fixed the issue.

`pre-commit run --all-files` now takes mere 4 seconds.

**Comment by asottile** [comment]
dope.

thanks for the issue 🎉

**Comment by sadikkuzu** [comment]
For the ones coming from "pre-commit cache bitbucket pipeline" google search,
(by the help of [this comment](https://github.com/pre-commit/pre-commit/issues/1066#issuecomment-504757189))
sample [bitbucket-pipelines.yml](https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/) file is here:

```yaml
image: python:3.7

definitions:
  caches:
    pre-commit: $HOME/.cache/pre-commit
  steps:
    - step: &all-files
        name: Run pre-commit for all files
        caches:
          - pre-commit
        script:
          - pip install pre-commit
          - pre-commit run --all-files
    - step: &only-changed-files
        name: Run pre-commit for all files
        caches:
          - pre-commit
        script:
          - pip install pre-commit
          - pre-commit run --from-ref origin/HEAD --to-ref HEAD

pipelines:
  pull-requests:
    '**':
      - step: *all-files
```

**Comment by asottile** [comment]
better would be to send a PR to the docs: https://pre-commit.com/#managing-ci-caches
