### ISSUE TITLE
Shareable/Reusable configuration?

### ISSUE THREAD

**Issue by sloria** [pre-commit/pre-commit#1069]
Is there a recommended pattern for re-using configuration across many repos? I am looking for something similar to eslint's [`extend`](https://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package) functionality.

**Comment by asottile** [comment]
there is not and I have no plans to add such a thing

I've seen people use submodules and symlinks to accomplish this 🤷‍♂ 

you can also run [pre-commit-in-pre-commit](https://github.com/pre-commit/pre-commit/issues/731#issuecomment-376945745) -- there's a few other linked resources there for similar ideas

**Comment by sloria** [comment]
Thanks! The pre-commit-in-pre-commit approach may suffice for my org's use case. Thanks for pointing me to it.
