### ISSUE TITLE
Pre-commit plugin "files" pattern is matching txt extension, but not others

### ISSUE THREAD

**Issue by homebysix** [pre-commit/pre-commit#1070]
I've got a pre-commit plugin that is intended to check a basic list file in one of several formats. I'm trying to use the `files` pattern below, but I keep getting `(no files to check) Skipped`.

```
- id: check-autopkg-recipe-list
  name: Check AutoPkg Recipe List
  description: This hook checks AutoPkg recipe lists (in txt, plist, yaml, or json format) for common issues.
  entry: check-autopkg-recipe-list
  language: python
  files: 'recipe.?list\.(yaml|txt|yml|json|plist)'
  types: [text]
```

My plugin successfully locates a file called **recipe_list.txt** but fails to locate and check files called **recipe_list.yaml**, **recipe_list.yml**, **recipe_list.json**, or **recipe_list.plist**.

I thought maybe I was making a dumb regex mistake with the pattern, but I ran it through an app that confirms the pattern should be correct:

![image](https://user-images.githubusercontent.com/7801391/60550499-0bbaae80-9cdd-11e9-9b3c-d04cff331acd.png)

I've also tried without the `types: [text]` option, but the behavior persists.

What am I doing wrong?

**Comment by homebysix** [comment]
After playing around a bit more with the pattern, it looks like `files: 'recipe_list\.txt'` successfully runs tests on a file called recipe_list.txt, but `files: 'recipe_list\.yaml'` does NOT run tests on a file called recipe_list.yaml, even when specifying `--all-files`.

**Comment by asottile** [comment]
seems to work fine for me? is it possible those other files are not text files?  what happens if you drop `types: [text]`?

```console
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   .pre-commit-config.yaml
	new file:   recipeYlist.json
	new file:   recipeYlist.plist
	new file:   recipeYlist.txt
	new file:   recipeYlist.yaml
	new file:   recipeYlist.yml
	new file:   recipe_list.json
	new file:   recipe_list.plist
	new file:   recipe_list.txt
	new file:   recipe_list.yaml
	new file:   recipe_list.yml
	new file:   recipelist.json
	new file:   recipelist.plist
	new file:   recipelist.txt
	new file:   recipelist.yaml
	new file:   recipelist.yml
	new file:   recipenope.yaml

$ pre-commit run identity --all-files
identity.................................................................Passed
hookid: identity

recipe_list.json
recipeYlist.txt
recipe_list.plist
recipelist.txt
recipelist.yaml
recipe_list.txt
recipe_list.yaml
recipeYlist.plist
recipeYlist.yml
recipelist.plist
recipe_list.yml
recipelist.json
recipeYlist.yaml
recipeYlist.json
recipelist.yml

$ cat .pre-commit-config,yaml
repos:
-   repo: meta
    hooks:
    -   id: identity
        files: 'recipe.?list\.(yaml|txt|yml|json|plist)'
        types: [text]
```

**Comment by asottile** [comment]
you can also use `identify-cli filename` to see what `identify` (and therefore `pre-commit`) thinks about a specific file

**Comment by homebysix** [comment]
Your `git status` output jogged my memory — I had forgotten to `git add .` after previously renaming the file. I forgotten that `--all-files` only covers files after they've been added to the stage.

After staging the file, the original pattern is working as expected. Thanks!

**Comment by asottile** [comment]
ahah!
