### ISSUE TITLE
Globally disable color?

### ISSUE THREAD

**Issue by saper** [pre-commit/pre-commit#1073]
I cannot find the way to globally disable color in the pre-commit output. Setting only the background color to green and not changing the foreground color does not work for my terminal with the following settings in the Xt resources (as set in the `${HOME}/.Xresources` file):

````properties
Rxvt.background: black
Rxvt.foreground: deepSkyBlue
````

Is there a way? It would be great to respect https://no-color.org/ environment variable. And, while we are here, maybe understand the following git config setting:

````ini
[color]
        ui = never
````

**Comment by asottile** [comment]
There's [`--color`](https://pre-commit.com/#cli)

**Comment by saper** [comment]
Thanks, how do i do this from the git pre-commit hook?

**Comment by asottile** [comment]
currently not an option afaik

**Comment by asottile** [comment]
@saper would you like to implement `$NO_COLOR` or some such? shouldn't be too difficult to plug in [here](https://github.com/pre-commit/pre-commit/blob/95afd642f52b4d2a12ad605683c8f752e63530d0/pre_commit/color.py#L42-L54)

**Comment by geieredgar** [comment]
I submitted two PRs to disable color output via NO_COLOR environment variable (#1092) and deducing the right --color option from color.ui config value when run as git hook (#1091)

**Comment by saper** [comment]
This is fantastic @geieredgar ! Thank you very very much!

**Comment by asottile** [comment]
I've had more thought about this and I think `NO_COLOR` is kind of a [bad standard](https://github.com/jcs/no_color/issues/57) and inflexible for `pre-commit`

@geieredgar would you mind reimplementing this as reading `PRE_COMMIT_COLOR` and having that be the default of the `--color` argparse option -- that would allow also forcing color on as well as off

**Comment by geieredgar** [comment]
@asottile Ok, I will submit a new PR soon.

**Comment by asottile** [comment]
I'm also going to have TERM=dumb disable colors as well -- see #1103

**Comment by asottile** [comment]
@geieredgar and @saper -- thanks again for the issue and implementation!

In the next minor release, pre-commit will have two ways to force color:

```bash
PRE_COMMIT_COLOR=...  # always, never, auto
TERM=dumb  # disables color
```
