### ISSUE TITLE
pre-commit and pyenv

### ISSUE THREAD

**Issue by adithyabsk** [pre-commit/pre-commit#1074]
It seems that pre-commit and pyenv don't seem to play well with each other and I think it comes down to the fact that pre-commit's vendorized version ships with python, pip, etc... in its bin which when added to the path cause issues. I was wondering if this was an area of the documentation that could be expanded upon to figure out best practices when using this package.

**Comment by adithyabsk** [comment]
As of right now I am only adding the pre-commit command inside the bin to my path but want to see what the consensus seems to be around this type of use case.

**Comment by asottile** [comment]
you're going to have to provide a reproduction -- we don't vendorize anything

**Comment by adithyabsk** [comment]
Sure, I guess this might be two separate issues.
```bash
brew install pre-commit
brew install pyenv
```
Close terminal and open terminal and pre-commit cannot be found as a command. This is I assume because of the below.

My workaround as of right now is to install the "vendorized version", or as per your documentation "Non-administrative installation." and only add the `pre-commit` utility to my path rather than everything in bin.

```
cat ~/.bash_profile
...
export PATH="$HOME/.pre-commit-venv/bin/pre-commit:$PATH"
...
```

Just trying to understand the rationale for bundling all these other dependencies in bin as I'm not familiar with the best practice here. From my understanding, only the installed tool should be in bin which might be why the brew installations might be conflicting, but I could be completely off base here.

```
$ ls ~/.pre-commit-venv/bin/
activate                      nodeenv*                      python*
activate.csh                  pip*                          python-config*
activate.fish                 pip2*                         python2@
activate_this.py              pip2.7*                       python2.7@
easy_install*                 pre-commit*                   virtualenv*
easy_install-2.7*             pre-commit-validate-config*   wheel*
identify-cli*                 pre-commit-validate-manifest*
```

**Comment by asottile** [comment]
oh boy, ok so you have two ways of pre-commit currently installed -- if you're on macos there isn't a reason to use `install-local.py` -- that's intended for users which don't have package management installation or aren't python developers (and don't have access to `pip`) -- no idea what `pyenv` has to do with any of this, seems completely unrelated

Let's start from just having the `brew` installed one -- that should create `/usr/local/bin/pre-commit` -- if it hasn't then your brew installation is broken and you should `brew link pre-commit` or `brew doctor` until that works.

Even if that were the case, the "local install" isn't intended for you to know about `~/.pre-commit-venv` -- it makes a symlink of `~/.pre-commit-venv/bin/pre-commit` into ` ~/bin/pre-commit` (and prints this!) https://github.com/pre-commit/pre-commit.github.io/blob/f7166ef4345ae7e026531cb368f4f422f450640e/install-local.py#L84 -- so if you were to add anything to your PATH it should just be `~/bin` (which on many systems is already part of the `PATH` so you don't need to do this, however iirc macos doesn't do this)

The other stuff in that `bin` dir is the standard things that come with a virtual environment, it doesn't hurt that they're there if you follow the directions it prints -- but you've gone and done something else ;)

Also extending your `PATH` in the way you've listed above doesn't work, `PATH` is intended to be a list of directories and not files.

**Comment by adithyabsk** [comment]
Ah, that makes gimme a sec to fix a few things and I'll let you know if the bug goes away. AFAIK I don't have two versions of pre-commit installed, but I can double check.

**Comment by asottile** [comment]
If you installed it with both `brew` and `install-local.py` then yes you have two versions installed

**Comment by adithyabsk** [comment]
I uninstalled the brew version as for some reason terminal wasn't able to find pre-commit even though it showed up in `/usr/local/bin`. But either way, I removed the other install and re-installed pre-commit through brew and everything works. No clue why brew was unable to find the command before. Thanks for all you help.

**Comment by asottile** [comment]
cheers!
