### ISSUE TITLE
Local hooks support for Docker

### ISSUE THREAD

**Issue by adarnimrod** [pre-commit/pre-commit#1081]
it'd be useful to have local hooks that use a Docker image built from a Dockerfile in the repo.

**Comment by asottile** [comment]
This won't happen, sorry.

None of the install artifacts can come from the local repo because they can't be cached. 

I'd suggest pushing the image somewhere and using `docker_image`

**Comment by adarnimrod** [comment]
Docker has caching of its own. If the `Dockerfile` or any of the files copied didn't change then the build process will finish in a few seconds.

**Comment by asottile** [comment]
I completely understand how docker works, I'm referring to how pre-commit works

The hooks each have a backing repository where installation happens. These backing repos contain things like `setup.py` / `Dockerfile` / etc. to build the hook executable.

`local` repos do not have a backing repository and must be functional from only the pre-commit configuration.

If you must, you can use a `language: script` type hook which implements the docker build for you:


(untested, typed on phone) 

```bash
#!/usr/bin/env bash
docker build -t hook-img . 
exec docker run -v "$PWD:/code" -w /code --user "$(id -u):$(id -g)" --rm hook-img "$@"
```

```
-   repo: local 
    hooks:
    -   id: docker-thing
        name: docker-thing
        entry: ./bin/docker-hook
        language: script
```

**Comment by adarnimrod** [comment]
I see.
Thank you for your very quick answers.
