### ISSUE TITLE
pre-commit doesn't work when called from magit

### ISSUE THREAD

**Issue by edran** [pre-commit/pre-commit#1082]
Sadly this afternoon I got bitten by magit/magit#3419, and by the look of it it seems like the issue might not be fixable easily by `magit`.

Is there any way that `GIT_LITERAL_PATHSPECS` could be unset by pre-commit directly?

**Comment by asottile** [comment]
Is there a particular crash?

**Comment by edran** [comment]
No crashes, but magit doesn't seem to be running - say - `black` when committing through its interface (while the hook runs if the commit is created from git's CLI).

**Comment by asottile** [comment]
Can you provide a reproduction and an expected output?  `pre-commit` itself shouldn't care about that setting (it doesn't use globs or patterns anywhere when consulting `git`) -- I suspect that there's a bug in some hook and that setting that in `pre-commit` would actually be a _disservice_ since it would hide bugs in underlying tools.

**Comment by asottile** [comment]
@edran ping!

**Comment by asottile** [comment]
@edran could you help with a full reproduction?

**Comment by asottile** [comment]
@edran if you have a reproduction I'd be interested in seeing it -- I tried the same operations that I did for https://github.com/asottile/seed-isort-config/issues/5 but this time I used `black` with `pre-commit` and it seems to work fine 🤷‍♂ 

please comment back with instructions / a reproduction and I can reopen -- thanks again for the issue!

**Comment by createyourpersonalaccount** [comment]
@edran this works for me, i.e. your `.git/hooks/pre-commit` can be:

```sh
#!/bin/sh

if ! command -v black > /dev/null 2>&1; then
    printf "black is not installed. See <%s>." \
           "https://black.readthedocs.io/en/stable/" 2>&1
    exit 1
fi

# Makes it work for magit <https://magit.vc/>.
unset -v GIT_LITERAL_PATHSPECS

staged=$(git diff -z --name-only --staged -- '*.py' | base64)

printf "%s" "$staged" | base64 -d | xargs -0 black -q

modified=$(git diff -z --name-only --diff-filter=M -- '*.py' | base64)

printf "%s" "$staged" | base64 -d \
    | (printf "%s" "$modified" | base64 -d && cat) \
    | sort -z | uniq -z -d \
    | xargs -0 git add -u
```
