### ISSUE TITLE
stash/restore of unstaged files overwrites mtime, etc.

### ISSUE THREAD

**Issue by gimbo** [pre-commit/pre-commit#1083]
When I `git commit` and that triggers pre-commit to run, it stashes any unstaged files, and restores them after it completes; that's all fine.

However, I've noticed that on restoration, the files' mtimes (and other timestamps) are overwritten with the time the stash was popped. I understand that this is the usual and expected git behaviour, and that there are in general good reasons for git doing it this way, but as it's happening automatically it feels to me like pre-commit has a "heavier footprint" than I expected.

I noticed because it's introducing a slight annoyance into my workflow: if I'm working on a jupyter notebook and it gets stashed/restored in this way, then jupyter sees the mtime update and prompts me, asking if I want to load the "new" version - even though nothing has actually changed. Presumably there are other cases where such false positives get triggered. (And maybe it's unavoidable, after all there were a few seconds there where the file disappeared _entirely_...)

I wonder if pre-commit ought to be less intrusive, by restoring the mtimes (and maybe all the timestamps?) to their pre-stash values after git has done its work.

* MacOS Mojave version 10.14.5
* python version 3.7.3
* pre-commit version 1.17.0
* git version 2.20.1

**Comment by asottile** [comment]
I don't think this is possible -- sorry

It would also create a more surprising experience elsewhere. why not stage the notebook?

**Comment by gimbo** [comment]
Fair enough; it was just a thought/suggestion. The reason for not staging the notebook is that I'm committing changes to that separately (and less frequently) than to the core code that it utilises.

Thanks again for some awesome software anyway. :-)

**Comment by asottile** [comment]
yeah I feel your pain :(

I'd have to reimplement `git apply` to make this work, and it's still unclear what should happen if hooks were to modify the files as well (and if they were to modify and then they were to conflict) -- a whole load of edgecases that I don't know if they'd even be the right decisions :S

**Comment by gimbo** [comment]
I was thinking to let `git` do it's thing and then overwrite the mtimes, which had been cunningly stored somewhere in the meantime. It would definitely add moving parts though. No worries!

**Comment by upsj** [comment]
Adding my two cents here: Touching files can trigger costly rebuilds in compiled languages (changing a header file can lead to 20 min build times in one of my projects). Before moving to `pre-commit`, our custom scripts used [`git show`](https://github.com/ginkgo-project/git-cmake-format/blob/26465c1669f3f64bf6709170fb98dcf63561b29e/git-cmake-format.py#L57) to get a stable view of the work-tree. If it was possible to run everything inside `pre-commit` in such a virtual view of the worktree, it would be much less intrusive. But I understand that this may require significant changes and may not be feasible in the current design.
