### ISSUE TITLE
Option for auto-commiting hook-made changes

### ISSUE THREAD

**Issue by ArturGajowy** [pre-commit/pre-commit#1086]
The docs say:
`The hook must exit nonzero on failure or modify files in the working directory (since 0.6.3).`

That is also the observed behavior. In case of a formatter hook though, that means most commits need to be attempted twice: once to re-format them, twice to commit them successfully.

For a sufficiently mature formatter tool, it should be OK to just set sth like `auto_commit_changes: true` in its hook config. This issue is about adding such an option to pre-commit. WDYT?

**Comment by asottile** [comment]
pre-commit will never ever ever modify the staging area, that's not a safe operation and one of the worst anti-features of related tools

See also #879 #806 #999 #747 (please search the issue tracker next time!)

**Comment by ArturGajowy** [comment]
Thanks, I found your remark in one of those issues helpful: I can always make my hook do `run_formatter && git add -u`.

(I did search the tracker)
