### ISSUE TITLE
Plugins should not require a .pre-commit-hooks.yaml file

### ISSUE THREAD

**Issue by anentropic** [pre-commit/pre-commit#1095]
Docs say:

> python ¶
The hook repository must have a setup.py. It will be installed via pip install .. The installed package will provide an executable that will match the entry – usually through console_scripts or scripts in setup.py.
>
> Support: python hooks work without any system-level dependencies. It has been tested on linux, macOS, windows, and cygwin.

But this is not entirely true.  You cannot install arbitrary tools and use them with pre-commit.

The tool you install currently has to provide a `.pre-commit-hooks.yaml`, otherwise you get the error:
```
/.cache/pre-commit/repohzjhAS/.pre-commit-hooks.yaml does not exist
```

This seems like a design flaw.

As a user I should be able to provide the necessary configuration to use the target package as a pre-commit hook from within my own project's `.pre-commit-config.yaml` file, without needing any cooperation from the tool itself.

If the `.pre-commit-hooks.yaml` file has a role at all it can be for plugin authors to provide useful defaults. But it should not be required in order to use a particular tool.

**Comment by asottile** [comment]
You're looking for [`local`](https://pre-commit.com/#repository-local-hooks) if you need a way to provide metadata

**Comment by anentropic** [comment]
`local` is not as good as a `repo` since it doesn't auto install

I don't understand why the `.pre-commit-hooks.yaml` file is required

**Comment by asottile** [comment]
it absolutely does, you're just not reading the right part -- here's an example: https://github.com/pytest-dev/pytest/blob/52ad5a1591e96b27b0128f6468e84ebcae40864f/.pre-commit-config.yaml#L57-L62

the `.pre-commit-hooks.yaml` is so it is trivial to add a "good default setup" and have the ability to share that.  It makes it simple for someone to add an existing tool with good defaults.

A user can go "I want to use black" and not have to think about "hmm what `language`, `files`, `types`, etc. should this apply to" -- they can just add the reference to the remote repository and they're done

It's a similar reason to why you'd add a line to your requirements.txt and not vendor the `setup.py` into your repository

**Comment by anentropic** [comment]
> it absolutely does, you're just not reading the right part -- here's another example: https://github.com/pytest-dev/pytest/blob/52ad5a1591e96b27b0128f6468e84ebcae40864f/.pre-commit-config.yaml#L57-L62

sorry I'm not sure what this part is an answer to?

> A user can go "I want to use black" and not have to think about "hmm what language, files, types, etc. should this apply to" -- they can just add the reference to the remote repository and they're done

But having the ability to provide good defaults via a `.pre-commit-hooks.yaml` file does not mean that it should be required.

It's great that black are able to specify those defaults, but if I want to use a tool that is not aware of pre-commit I should be able to supply the necessary values myself as a user instead of getting an error.

**Comment by asottile** [comment]
> sorry I'm not sure what this part is an answer to?

it was an answer to this:

> local is not as good as a repo since it doesn't auto install

**Comment by anentropic** [comment]
are you saying that local hook will `pip install rst` ?

that was not clear from the docs

**Comment by anentropic** [comment]
oh I see, it will `pip install pygments, restructuredtext_lint`

my apologies, I will try this out

**Comment by asottile** [comment]
The docs have one example of the three main types: system, script, and things that get installed (in this case `ruby`) -- they also mention "local hooks can use any language which supports `additional_dependencies` ..."

if you think there's more that can be added there please [submit a PR](https://github.com/pre-commit/pre-commit.github.io)

**Comment by anentropic** [comment]
thanks very much for your help 👍

**Comment by asottile** [comment]
no problem, happy to help :) glad we got there in the end!
