### ISSUE TITLE
--config arg not working on pre-config install?

### ISSUE THREAD

**Issue by ChrisWeiss** [pre-commit/pre-commit#1097]
From the docs (https://pre-commit.com/#cli):

```
All pre-commit commands take the following options:

--color {auto,always,never}: whether to use color in output. Defaults to auto.
-c CONFIG, --config CONFIG: path to alternate config file
-h, --help: show help and available options.
```

From the command line:
```
$pre-commit -c /Users/cweiss/.pre-commit-config.yaml install
usage: pre-commit [-h] [-V]
                {install,install-hooks,uninstall,clean,gc,autoupdate,migrate-config,run,sample-config,try-repo,help}
                ...
pre-commit: error: argument command: invalid choice: '/Users/cweiss/.pre-commit-config.yaml' (choose from 'install', 'install-hooks', 'uninstall', 'clean', 'gc', 'autoupdate', 'migrate-config', 'run', 'sample-config', 'try-repo', 'help')
```

I'd like to be able to refer to a central `.pre-commit-config.yaml` file when setting up new repos.

`pre-commit` version 1.17.0 installed via Homebrew

**Comment by geieredgar** [comment]
Did you try putting install before the -c option, like this:
`pre-commit install -c /Users/cweiss/.pre-commit-config.yaml`?

**Comment by ChrisWeiss** [comment]
That worked. I was thrown because I was validating with `pre-commit run` which (I discovered) expects a config file and doesn't look in `.git/hooks`. Thanks!
