### ISSUE TITLE
functionality to add files to commit

### ISSUE THREAD

**Issue by lamourj** [pre-commit/pre-commit#1099]
It would be a nice feature to have the option to automatically stage new files at the end of the precommit hook.
Use case: I use a hook to generate documentation at commit time. It would be nice to have the option to add these files to the current commit, if modified. 
Is there any way to do that currently ? I guess a workaround would be to add a hook at the end which would add these files... any nicer way ?
Thanks

**Comment by asottile** [comment]
pre-commit will never ever ever modify the staging area, that's not a safe operation and one of the worst anti-features of related tools

See also #1086 #879 #806 #999 #747 (please search the issue tracker next time!)
