### ISSUE TITLE
pre-commit has suppressed colors in the output of the hook tool

### ISSUE THREAD

**Issue by anentropic** [pre-commit/pre-commit#1100]
I'm running a linting tool as a pre-commit hook, the colored output from the tool is useful.

pre-commit seems to strip the colors from the tool output though

I tried `pre-commit run <tool> --color=always` but it had no effect, it seems this flag only toggles the color from pre-commit's own output strings ("Failed" etc).

Is there a way to preserve color in the output from the tool being run by pre-commit?

**Comment by asottile** [comment]
pre-commit does not supply a tty to the tool which is probably triggering the underlying tool's behaviour to turn off colors

You'd probably need to pass some argument to the actual tool to control its colors

**Comment by anentropic** [comment]
ah ok, thanks... I made the tool so hopefully I can fix it  😄

**Comment by asottile** [comment]
it might make sense for pre-commit to export an environment variable such that underlying tools could know what's up? -- we added some precedence for `PRE_COMMIT_COLOR` in #1098

and there's precedence for pre-commit passing some extra information in #550 (PRE_COMMIT_SOURCE / PRE_COMMIT_ORIGIN)

**Comment by anentropic** [comment]
I'm using this library https://github.com/chalk/chalk#chalksupportscolor and can see it must be what you said, it detected that terminal colors were not supported even though presumably they are

so I'm thinking to add a `--force-color` flag to my tool

I guess there is no way that will 'just work' across all tools unless you can fool the auto-detection somehow

**Comment by anentropic** [comment]
would `PRE_COMMIT_COLOR` env var pass down the "supports color" status of the parent terminal?

**Comment by asottile** [comment]
yes

**Comment by asottile** [comment]
however it would need someone to implement it ~o/

**Comment by anentropic** [comment]
got my tool working with a `--force-color` flag which can be applied via pre-commit hook `args`

**Comment by asottile** [comment]
also -- try out pre-commit 1.20 -- it has improved pty support

**Comment by ssbarnea** [comment]
I recently started to encounter (MacOS) an issue where `pre-commit` and `mypy` started to run without colors but I was not able to narrow down what is causing this. Using `PRE_COMMIT_COLOR=always` worked but is far from convenient, especially as this impacts any project and that tox for example is likely to not passenv this.

Funny story is that when I run inside tox pre-commit seems to run colored but outside it runs without. This makes me believe that maybe there is another environment variable that affects it. I am stil trying to bisect them to narrow it down.

I am not sure what is real source of the bug but this seems interesting:
```
python
Python 3.8.2 (default, May  3 2020, 15:47:33)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.isatty()
True
sys.stderr.isatty()
False
>>> sys.stdout.isatty()
True
```

On Linux all 3 do report True for isatty() but not here.
