### ISSUE TITLE
Run hook once (not for every file) if a matched file is detected

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1102]
After I could not find an answer on [StackOverflow](https://stackoverflow.com/questions/57199833/run-pre-commit-com-hook-once-not-for-every-file-if-a-matched-file-is-detected), I dare to ask here: 

I have a hook that generates documentation files from source files, built with the [pre-commit.com framework](https://pre-commit.com). The function that is invoked in that hook does not have a file argument, so it simply creates documentation for all source files in the directory. The hook is a `system` hook, i.e. just a bash script where I call that function to create the documentation. However, in the pre-commit.com framework, files are passed to the hook and the logic is to execute a hook on every file, which makes sense in most cases (e.g. to lint every file separately), but not in my case. So my question is: How can I ensure that the documentation hook is run just *once* if there is any source file changed, as opposed to it being run in multiple times (in parallel or sequentially), on the individual files? In concrete terms, my hook is generating R docuementation with `roxygen2::roxygenize()` and can be found [here](https://github.com/lorenzwalthert/pre-commit-hooks/blob/master/bin/roxygenize). 

If that is not currently supported, would you consider adding support for that? For example, in `.pre-commit-hooks.yaml`, hooks could gain an argument `once_for_all`, for example with a description as the following: 

> "`once_for_all` (defaults to false) Whether or not to execute the hook just once if any file or file type is matched. The file argument to the hook is ignored. This can be useful for more complicated hooks that don't take file arguments but only work for whole directories because of the interdependencies between files such as generating documentation with inheritance of parameters between files.

This would make the framework more general and suitable for complex interactions in my opinion. Thanks for this amazing tool.

**Comment by asottile** [comment]
`pass_filenames: false` I believe is what you want

**Comment by lorenzwalthert** [comment]
Perfect, works like a charm. Thanks for your support.
