### ISSUE TITLE
pre-commit shoud use on urls with .git suffix

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1109]
Few weeks back we found a bug where older versions of git would fail to clone repositories mentioned `.pre-commit-config.yaml` files. After investigation this proved to be caused by the lack of `.git` in the urls. Newer versions of git are able to adapt and succeed cloning it but older ones would choke.

This was observed especially with flake8 from gitlab, probably has also something to do on how the web server is handling HTTP redirects.

Action items:
* add `.git` to all urls, especially samples and examples
* add a warning that detects lack of .git and tells user to add it

**Comment by asottile** [comment]
nah you're wrong about this and it won't / shouldn't happen -- only specific hosts require `.git` in urls and otherwise it's just cargo cult and noise

**Comment by ssbarnea** [comment]
@asottile Please read https://bugs.launchpad.net/tripleo/+bug/1836761 too see what happened and how it was addresed.

People tried to revert that change that added pre-commit but luckly I was able to identify that this error was present only on repos where .git was not at the end. The other worked. Even adding it fixed the issue. 

Based on reports from http://logstash.openstack.org/#/dashboard/file/logstash.json?query=message:%5C%22error:%20RPC%20failed%3B%20result%3D22,%20HTTP%20code%20%3D%20404%5C%22 I would say that it involved at least 8 builds. Maybe it was only a glitch on the gitlab server redirector?

Also more interestingly, there is this https://stackoverflow.com/questions/32533379/git-error-rpc-failed-result-22-http-code-404 

The number of votes on that ticket tells me that there are at least 40 engineers that do think that confirm that adding `.git` can fix the problem.

**Comment by asottile** [comment]
sounds like gitlab had a bad deploy that they fixed to me and that adding `.git` didn't fix anything it just was a coincidence

**Comment by asottile** [comment]
I'm not saying that all servers don't require `.git` -- because I know bitbucket does -- just there's no reason to cargo cult it everywhere

**Comment by ssbarnea** [comment]
I am ok having this ticket closed. At least we will findout if someone gets into the same kind of problem and we could corellate more factors.

For me it was clear because I was able to reproduce the same failure on centos-7, when it was working from macos. Centos git was older (1.8.3.1), while local was (2.22.0). Adding suffix fixed it. i tried to reproduce today and failed so maybe it was just a rare coincidence that affected only redirection on gitlab, so no real reason to worry.
