### ISSUE TITLE
Possibility to skip a hook from inside the hook script

### ISSUE THREAD

**Issue by bilke** [pre-commit/pre-commit#1115]
It would be nice if a hook script could set the hook as skipped (similar to `Check Xml.....(no files to check)Skipped`). This could be useful, e.g. when a hook requires a tool which is not installed on the machine. Is this already possible?

**Comment by asottile** [comment]
I believe you're looking for [`SKIP=...`](https://pre-commit.com/#temporarily-disabling-hooks)

**Comment by bilke** [comment]
No, I am talking about setting the skipped flag from inside the hook itself. This could maybe implemented by checking for a certain return value of the hook, e.g.:

```bash
#!/usr/bin/env bash

EXE=$(command -v required_tool_x)
if [ -z "$EXE" ]; then
    echo "required_tool_x not found; skipping check."
    exit 9999
fi
...
```

And then `pre-commit` could check for that magic return value (`9999`) and set the hook to skipped.

**Comment by asottile** [comment]
yep that's already supported, use the special exit code `0`

**Comment by bilke** [comment]
yes but `0` means success. I would like to indicate that it was skipped.

**Comment by asottile** [comment]
Scripts can only exit 0-255, any of those will collide with some other convention

Sorry, have to say no on this one, please understand
