### ISSUE TITLE
Feature Request: Add 'exclude-hook' when running.

### ISSUE THREAD

**Issue by mmphego** [pre-commit/pre-commit#1121]
I find myself wanting to run all my hooks except specific ones. 

For example, I might have `hook1`, `hook2`, `hook3` and `hook4` but only want to run all except `hook3`

It would be nice to have that option under: `pre-commit run`

**Comment by asottile** [comment]
you're looking for [`SKIP=`](https://pre-commit.com/#temporarily-disabling-hooks)

**Comment by mmphego** [comment]
Memo to myself: **READ THE DOCS**
