### ISSUE TITLE
Unable to use language_version to require a minimal python version

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1128]
Some time ago I encountered a problem which seems not to be sorted yet: you cannot require a minimal version of python. For example black requires minimum python3.6

This means that: it will work fine with python3.6 or python3.7 -- whatever user have installed but that it will clearly not work with python3.5.

If used happens to have multiple versions installed, there is a real chance that python3.5 will be picked.

The only way to avoid this is to change pre-commit to either support minimal version or to allow a list of interpreters to pick from, so we can put there both and in near feature maybe even python3.8

Here is a practical example which blocked adoption of Black via pre-commit, where even CI is not passing: https://review.opendev.org/#/c/678221/

Please note that is not reasonable to force users to install a specific version of python in order to perform the linting, different distros could have different python versions.

**Comment by asottile** [comment]
Until virtualenv does something about this the answer here is the same as the last time you asked -- there's nothing really that can be done

black currently sets `language_version: python3` to do as best as we can with the current facilities provided by `virtualenv` and such

**Comment by ssbarnea** [comment]
Not sure why picking the first executable found from a list would not be considered an acceptable solution? `which python3.7 python3.6 | head` works fine.

**Comment by benjaoming** [comment]
> black currently sets language_version: python3 to do as best as we can with the current facilities provided by virtualenv and such

Does this guarantee the highest-possible Python 3 version?

Also, additional note: Black unfortunately [suggests/recommeds](https://github.com/psf/black/#version-control-integration) `language_version: python3.6`, that would break on systems that only have Python 3.7?

**Comment by asottile** [comment]
> Does this guarantee the highest-possible Python 3 version?

`virtualenv` resolves that to whatever `python3 --version` gives you

> Also, additional note: Black unfortunately suggests/recommeds language_version: python3.6, that would break on systems that only have Python 3.7?

yes, it would break

an aside, I think it would be cool if `virtualenv` supported something like `virtualenv -p '>=python3.6'` -- though that would require changes to support that (I think the recent rewrite might make this easier?)

**Comment by bristea** [comment]
So if we need to require any minimal version of python 3 with pre-commit there is no way of doing it. The only workaround is to hardcode a specific version of python that is within the range we need.

So those that have py37 or py38 into python_requires have no option other than picking one and sticking inside pre-commit config, forcing everyone that tries to use pre-commit locally to have this particular version. That is not very cool.

**Comment by asottile** [comment]
like I said above, and in the other thread -- if you want to move this forward I'd recommend you suggest a feature to `virtualenv` to support the feature you're asking for

taking out your frustration on this issue tracker is not useful
