### ISSUE TITLE
Add option to add project root to PYTHONPATH

### ISSUE THREAD

**Issue by ulope** [pre-commit/pre-commit#1129]
Background:
`pylint` plugins need to be specified via an import path. If project specific plugins are to be used this means they are not accessible from within the pre-commit hook virtualenv.

Therefore it would be useful if there was an option to add the project root to the hook's PYTHONPATH.

The recommendation so far has been to use a `local` hook of type `system`. Unfortunately this is pretty fragile since it requires `pre-commit` to be invoked from within the activated virtualenv of the current project. This is (what feels like) increasingly not the case with tools like poetry, pipenv and also some git GUI clients.

**Comment by asottile** [comment]
Not supported or portable but:

```yaml
        entry: env PYTHONPATH=. pylint
```

Note that this explicitly goes against the design, hooks are intentionally isolated (this will not become a first class or supported feature)

Here's the previous and linked discussions about pylint: https://github.com/pre-commit/pre-commit-hooks/issues/157#issuecomment-265516255

**Comment by ulope** [comment]
Unfortunately none of the suggested solutions in that issue work under the constraints I mentioned above (i.e. project venv not activated / managed by tools, etc.)

I understand that isolated hook venvs are an important design goal but in this case it seems to stand in the way of solving the (IMO) primary goal of allowing users to run checks on their code.

Also on the topic of pylint performing dynamic checks, the [documentation explicitly states the opposite](https://pylint.readthedocs.io/en/latest/user_guide/run.html):

> You should give Pylint the name of a python package or module, or some number of packages or modules. **Pylint will not import this package or module**, though uses Python internals to locate them and as such is subject to the same rules and configuration.

(emphasis mine)

**Comment by ulope** [comment]
Anyway I've now created the worlds simplest pylint wrapper that adds the the working dir to the PYTHONPATH:
https://github.com/ulope/pre-commit-pylint-wrapper-pythonpath

This solves the issue for me.

**Comment by asottile** [comment]
pylint doesn't invoke the import machinery, but it does follow imports which is ~roughly the same.  did the `env` trick above not work? that should do essentially the same as your wrapper

**Comment by ulope** [comment]
> did the env trick above not work?

Indeed it does!

I wasn't aware that it's possible to override `entry` on an 'imported' hook. I though that only worked for local ones.

Thanks for clarifying, that is indeed much easier.

**Comment by asottile** [comment]
~technically the only thing that isn't overridable is `id`, though there's `alias` for that 👍

**Comment by ulope** [comment]
For posterity in case someone else has a similar problem:

Overriding the entry unfortunately wasn't enough. Since both pylint and mypy need access to third party library code in order to fully function we'll be using a wrapper that installs the project dependencies into the pre-commit generated venvs.

This exact implementation is project specific (e.g. paths and tool choice), but should be easy enough to adap: thttps://github.com/raiden-network/raiden/pull/4784/files#diff-383eb76d31fde5ed79970c3dfbc8c8e1
