### ISSUE TITLE
Insert variables in pre-commit configuration

### ISSUE THREAD

**Issue by ttwister** [pre-commit/pre-commit#1131]
Hello,

I could not find a title that reflect my idea.

I would like to know if you a have a way to configure the usage of a proxy server for this environment:
  - we work behind our company HTTPS proxy server
  - the pre-commit hooks repositories we use are a mix of public Github repositories (requiring a proxy setting) and internal hosted git repositories (no proxy required)
  - it looks like we will have no issue for the additional_dependencies (npm, pypi) because we use a solution that allows configuring repositories behind a proxy. Moreover we can pass options to the package managers to change the proxy configuration.
  - teammates that only have a python installation with pre-commit package already installed

We would like to avoid using user/system environment variables configured outside of the pre-commit configuration as it requires switching it regularly to be able to work with public or private repositories. This is the option I use for now.
git http.proxy configuration does not work properly for us and suffers the same requirement.
I understand you propose something similar to use your tox tool (https://pre-commit.com/#usage-with-tox). Do you have any suggestion?

**Comment by asottile** [comment]
why can't you request public things with `http_proxy` / `https_proxy` environment variables set?

(another idea) at a previous company, we mirrored public repos internally such that everything was requested in a uniform manner

**Comment by ttwister** [comment]
> why can't you request public things with http_proxy / https_proxy environment variables set?
We can, it is more a choice. To me, it is convenient but we would prefer a project configuration instead of a user configuration.

Your mirror repos is a really good idea I did not think to. Thank you.

**Comment by asottile** [comment]
cool, glad you came to a solution!
