### ISSUE TITLE
An error has occurred: InvalidManifestError

### ISSUE THREAD

**Issue by kobeTianSilk** [pre-commit/pre-commit#1134]
when i change the repo 
i got same error

- per-commit install
- pre-commit run --all-files
pre-commit --version : 1.18.3
`
[INFO] Initializing environment for https://github.com/kobeTianSilk/py3-bundleb2b.git.
An error has occurred: InvalidManifestError: 
=====> /Users/kobetian/.cache/pre-commit/repo6iaxh9oh/.pre-commit-hooks.yaml does not exist
Check the log at /Users/kobetian/.cache/pre-commit/pre-commit.log
`

here is my code

`
default_language_version:
    python: python3.7
default_stages: [commit, push]
repos:
-   repo: https://github.com/kobeTianSilk/py3-bundleb2b.git
    rev: 896b92dcdbf567c5c0197fc6575e0c8bf6d2b5b3
    hooks:
    -   id: python-pylint
    -   id: python-isort
    -   id: autopep8
    -   id: black
        language_version: python3.7
`

**Comment by asottile** [comment]
please continue discussion in #1133
