### ISSUE TITLE
pre-commit tool should have its own stackoverflow tag

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1137]
Currently on StackOverflow the `pre-commit` tag points to the generic SCM action with the same name and it would be totally inappropriate to reuse it as users may get confused.

I propose using `pre-commit.com` tag as is apparently already used https://stackoverflow.com/questions/tagged/pre-commit.com

**Comment by asottile** [comment]
I recently did a sweep and retagged to `[pre-commit.com]`

we should document this somewhere, would you like to help with that?

**Comment by ssbarnea** [comment]
I even did more than this, I added the tag to my rss2irc bot which will announce new questions on #pylib channel from now on (every ~30mins).
