### ISSUE TITLE
Locking pre-commit directory per repository

### ISSUE THREAD

**Issue by MaxymVlasov** [pre-commit/pre-commit#1138]
In some cases I'd like to run `pre-commit install-hooks` / `pre-commit install --install-hooks` in many folders at the same time, but pre-commit locks it own directory fully, not per repo.

**Comment by asottile** [comment]
this is intentional, the individual language installers (outside pre-commit's control, for example python) are themselves not parallel safe. additionally the backing store (sqlite) does not support concurrent writes

**Comment by MaxymVlasov** [comment]
Okay, thanks for expanation
