### ISSUE TITLE
Install many hooks types by one command

### ISSUE THREAD

**Issue by MaxymVlasov** [pre-commit/pre-commit#1139]
Now I should run next in every new repo:
```console
$ pre-commit install-hooks
$ pre-commit install --install-hooks --hook-type commit-msg
```

Maybe can be more pretty have something like 
```console
$ pre-commit install --install-hooks --all
# OR
$ pre-commit install --install-hooks --hook-type pre-commit,commit-msg
```

**Comment by asottile** [comment]
you don't need to run install-hooks fwiw, it happens on demand

also I think `&&`  probably works fine and then I don't need to maintain the complexity

have you seen the new `init-templatedir` feature?

**Comment by MaxymVlasov** [comment]
No, in my case I should run pre-commit install --install-hooks in every repo, because now I have task to update couple of things in many repos, and most of it I cloned first time. I just want prepare hooks before I start commit changes in ~50 repos.

Of cource I use `&&` - but it looks like crutch for this case.

About `init-templatedir` - it's cool stuff which I start use in nearest future. 
Before I use it my own hooks next:
```bash
# Run pre-commit
pre-commit
exitcode=$?

if [ ${exitcode} -ne 0 ] ; then
    exit 1
fi
```
But `init-templatedir` not about this case.

**Comment by asottile** [comment]
fwiw you could also use

```bash
set -e
pre-commit
```

or

```bash
if pre-commit; then
    exit 1
fi
```

pre-commit shares hook installations across repositories so usually you'll only incur the startup cost a few times. the `install-hooks` commands aren't really designed so much for human use as they are for scripting or building docker images

**Comment by asottile** [comment]
#1145 enables specifying `--hook-type` multiple times for `install`, `uninstall`, and `init-templatedir` -- let me know how that looks!

**Comment by MaxymVlasov** [comment]
Cool, thanks!

Commands like below looks pretty well
```bash
pre-commit install --install-hooks -t pre-commit -t commit-msg
```

**Comment by janosh** [comment]
What's the rationale for not making `pre-commit install` behave like `pre-commit install --all`, i.e. install whatever hook types `.pre-commit-config.yaml` specifies? I expect a Twitter pole would say `pre-commit install --all` is the majority expected behavior.
