### ISSUE TITLE
Support monorepos

### ISSUE THREAD

**Issue by dpinol** [pre-commit/pre-commit#1140]
Hi,
several people have asked about monorepos, which is a very popular trend:
https://github.com/pre-commit/pre-commit/issues?utf8=%E2%9C%93&q=is%3Aissue+monorepo+

Without explicit support, I need to specify the project path 3 times for pylint:
```
    -   id: pylint
        name: pylint
        entry: env PYTHONPATH=hubtype_babel/deploy_app python -m pylint.__main__ --rcfile=hubtype_babel/deploy_app/pylintrc
        language: system
        types: [python]
        files: hubtype_babel/deploy_app/.*/.*py
```
Maybe adding a new "working_folder" hook field which just performs a "cd" before running the hook could be a quick win?

thanks!

**Comment by asottile** [comment]
please continue discussion in an existing issue, thanks
