### ISSUE TITLE
InvalidManifestError. Pre-commit tries wrong user.

### ISSUE THREAD

**Issue by bushmaks** [pre-commit/pre-commit#1149]
Hi, I'm trying to run `pre-commit run --all` and pre-commit trying to take cache from wrong user, how can I change this path? Thanks

My user folder is called `bushmaks` and I'm using macOS Mojave 10.14.6

Here's full output:
```An error has occurred: InvalidManifestError: 
=====> /Users/ai/.cache/pre-commit/repojeiak4da/.pre-commit-hooks.yaml does not exist
Check the log at /Users/bushmaks/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
That seems very weird, like you copied your home directory from somewhere else maybe?

Before you blow away the data can you run this for me?

```bash
sqlite3 ~/.cache/pre-commit/db.db 'select * from repos;'
```

and ~likely the solution after that is `pre-commit clean` -- still weird though

**Comment by bushmaks** [comment]
Yes, recently I migrated from my old mac.

**Comment by bushmaks** [comment]
Thanks, cleaning worked for me.

**Comment by asottile** [comment]
cool, makes sense then
