### ISSUE TITLE
way to install 3rd party requirements

### ISSUE THREAD

**Issue by fantapop** [pre-commit/pre-commit#1150]
It would be great to have a more generic way to install 3rd party dependencies.  I'm trying to use the terraform hooks (https://github.com/antonbabenko/pre-commit-terraform) which is a collection of tools many of which are required to be manually installed.  I don't see a way to accomplish this with currently functionality.

https://github.com/antonbabenko/pre-commit-terraform/issues/69

**Comment by asottile** [comment]
you're looking for [`additional_dependencies`](https://pre-commit.com/#pre-commit-configyaml---hooks)

**Comment by asottile** [comment]
ah no this is separate entirely, pre-commit-terraform depends on things being system installed (`system` / `script` type hook) which is the escape hatch

if it is using one of the [supported languages](https://pre-commit.com/#supported-languages) pre-commit will manage the entire installation and `additional_dependencies` installation as well

adding a language is pretty straightforward, but needs someone to do it: https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#adding-support-for-a-new-hook-language

**Comment by asottile** [comment]
and actually, since terraform is `go` it should already work fine in the normal way of having pre-commit manage the installation
