### ISSUE TITLE
Preinstall hooks without git repo

### ISSUE THREAD

**Issue by hoefling** [pre-commit/pre-commit#1152]
First of all, thank you for this great project. Found `pre-commit` while poking around the `pytest` source code and become a `pre-commit` junkie in no time :smile:

This is rather a question than an issue - I'm looking for ways to speed up the CI pipeline execution and found out the installation of hooks swallows a noticeable amount of time. Is there a way to preinstall the hooks e.g. in a docker image without having the Git repo available in the image? Something like
```
FROM python:3.7
RUN pip install pre-commit
COPY .pre-commit-config.yaml .
RUN pre-commit install --install-hooks --config .pre-commit-config.yaml && rm .pre-commit-config.yaml  # this will fail b/c no git repo around
```
I have considered caching the `~/.cache/pre-commit` directory between CI runs, but this has the consequence of uploading/downloading a ~100MiB archive for each job as we have a remove server configured for storing CI caches, therefore caching doesn't make CI jobs any faster.

**Comment by asottile** [comment]
you're looking for [`pre-commit install-hooks`](https://pre-commit.com/#pre-commit-install-hooks) which was built for this purpose -- you'll still need a git repo, but it can be an empty `git init` (just so `pre-commit` can find the repo-root)

we do something like this at lyft:

```bash
cp /tmp/src/.pre-commit-config.yaml .
git init .
pre-commit install-hooks
```

you can do a similar thing in a dockerfile (though, you'd still have the upload and download presumably to get your image on the box)

you can also adjust the directory where the hooks get installed using `PRE_COMMIT_HOME` (though usually it's not necessary, and currently intentionally undocumented)

**Comment by hoefling** [comment]
Awesome, thank you so much for the prompt answer! The missing part was the init of an empty repository, worked like a charm once I added this. Here's an enhanced example, just for the reference's sake:
```
FROM python:3.7
RUN pip install pre-commit
COPY .pre-commit-config.yaml .
RUN git init . && pre-commit install-hooks --config .pre-commit-config.yaml && rm -rf .git/ && rm .pre-commit-config.yaml
```

**Comment by Downchuck** [comment]
@asottile Is this a wontfix situation? Seems like a flag would be appropriate here, as this workaround adds a bit of noise to the Dockerfile. A flag would be helpful as well for run when targeting specific files as opposed to checking for staging status.

**Comment by asottile** [comment]
no, I'm not going to maintain a hack solution that could confuse / be abused in other ways when `git init .` works just fine.  it's hardly noise

**Comment by Downchuck** [comment]
```
RUN cd /app && git init . && pre-commit install-hooks && rm -rf .git
```
vs.
```
RUN pre-commit install-hooks --my-eyes-are-burning-and-everything-is-drama
```
