### ISSUE TITLE
pip fail because SSL_CERT_FILE is not passed

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1154]
When pip is configured to use a SSL proxy, it also needs to load the custom CA mentioned in `SSL_CERT_FILE` variable. Apparently pre-commit hides it thus later failing to install dependencies due to SSL errors.

I do mention that pip works fine from cli, also from tox, because they can load SSL_CERT_FILE variable.

**Comment by asottile** [comment]
`pre-commit` doesn't clear this variable -- I assume based on the closed state of this issue you were mistaken?

**Comment by ssbarnea** [comment]
Yep, sorry I was a PEBKAC.
