### ISSUE TITLE
use standard parsable spelling instead of parseable

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1156]
Time for pre-commit to correct its spelling in config `parseable` -> `parsable`.

Reasoning: https://en.wiktionary.org/wiki/parsable -- time to add pre-commit to the list? ;)

**Comment by asottile** [comment]
don't make an issue for typos, just fix it -- also not sure what you mean:

```console
$ git -C pre-commit grep parseable
$ git -C pre-commit.github.io grep parseable
$
```

**Comment by asottile** [comment]
also your link shows `parseable` as an alternative form 🤷‍♂
