### ISSUE TITLE
Support other return codes

### ISSUE THREAD

**Issue by michaelquinn32** [pre-commit/pre-commit#1167]
It would be nice to report issues in the code without blocking the commit. This would involve accepting other status codes here:

https://github.com/pre-commit/pre-commit/blob/bb108bf00e8a19bfb41a32afae7c4a9a58a56866/pre_commit/commands/run.py#L132

Even better if we could allow warnings to always behave as if the `--verbose` flag was passed.

**Comment by asottile** [comment]
```
        entry: bash -c 'exe "$@" || true' --
```

**Comment by asottile** [comment]
this is a dupe but I'm on my phone so there's the copy paste answer

**Comment by michaelquinn32** [comment]
Thanks!
