### ISSUE TITLE
run hook concurrent?

### ISSUE THREAD

**Issue by FelixSeptem** [pre-commit/pre-commit#1174]
I saw it run hooks by id serialized. Is is possible to run it concurrent by use `async/await` or `subprocess` to cut down running time?

**Comment by asottile** [comment]
yes that's the default (and called out in the changelog and docs)

if you're asking about intermixing, no that's not safe due to fixers

**Comment by zachvalenta** [comment]
[This](https://github.com/pre-commit/pre-commit/issues) is the mention in the docs.

I think it'd be worth adding greater emphasis by putting this in the [introduction section of the docs](https://pre-commit.com/#intro).

**Comment by asottile** [comment]
I'm locking this issue as all comments since resolution have been off topic -- if you have a new issue please create a new issue
