### ISSUE TITLE
pre-commit fails to read git config

### ISSUE THREAD

**Issue by thiras** [pre-commit/pre-commit#1178]
Hello,

I've followed the official documentation to install pre-commit. I don't have any `.pre-commit-config.yam` yet. When I tried to create commit I get this error;

```
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```

Here is my `git config -l`;

```
user.email=antsomers@example.com
user.name=Ant Somers
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@gitlab.com:thiras/testrepo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

I've both tried with VSCode and manual on terminal. Both throw the same error.

**Comment by asottile** [comment]
what commands are you running and what do you expect and what are they doing?

pre-commit does not utilize git configuration

**Comment by thiras** [comment]
Just trying to commit with; `git commit -m "Blabla"` after staging some changes. My git works perfect (for years) until I installed pre-commit.

**Comment by asottile** [comment]
have you tried the suggestions that are printed?

**Comment by thiras** [comment]
@asottile Why would I do that? Instead I would like to fix missing configuration if it's there any. Pre-commit is the git enhancer in the first place. What's the point if I bypass my git config to use it?

**Comment by thiras** [comment]
I'll uninstall than create `.pre-commit-config.yaml` and commit it than will try to reinstall to solve the issue. Let's see

**Comment by thiras** [comment]
Yes it worked. Thanks.

**Comment by asottile** [comment]
cheers! thanks for the issue 🎉
