### ISSUE TITLE
Offline test invocation

### ISSUE THREAD

**Issue by jayvdb** [pre-commit/pre-commit#1183]
A lot of the tests depend on online functionality.

For testing in rpmbuild workers, etc, it would be helpful if a pytest marker was put on all tests which require network, so they can be disabled when run from VMs not attached to the internet.

**Comment by jayvdb** [comment]
This is what I need to run to avoid the online tests.  I assume some of these might be fixed by adding build dependencies.
```console
%pytest -k 'not (test_run_a_node_hook or test_run_a_ruby_hook or test_run_versioned_node_hook or test_run_versioned_ruby_hook or test_run_ruby_hook_with_disable_shared_gems or test_golang_hook or test_golang_hook_still_works_when_gobin_is_set or test_installed_from_venv or test_environment_not_sourced or test_warning_on_tags_only or test_main or test_local_rust_additional_dependencies or test_local_golang_additional_dependencies or test_additional_golang_dependencies_installed or test_additional_golang_dependencies_installed or test_additional_golang_dependencies_installed or test_additional_ruby_dependencies_installed or test_additional_node_dependencies_installed or test_additional_rust_cli_dependencies_installed or test_additional_rust_lib_dependencies_installed or test_additional_dependencies_roll_forward)'
```

**Comment by asottile** [comment]
I'm not sure this is actionable, I don't plan to keep the list up to date and there's no way for me to test it.  `-k` already works (though your list contains some that are suspect, like `test_main`)

**Comment by jayvdb** [comment]
I suspect some of the tests are failing because of missing dependencies, e.g. go/node/ruby/rust tools.

My notes to self in my rpm .spec are currently

```console
# test_switch_language_versions_doesnt_clobber fails on python3-only due to needing python2
# test_run_a_node_hook, test_run_a_X_hook might only need some pre-installed bits
# test_warning_on_tags_only use autoupdate which requires internet
# test_installed_from_venv and test_environment_not_sourced shouldnt fail; need investigating
```

**Comment by asottile** [comment]
the autoupdate tests should pass, they usually use local repos

the repository tests intentionally exercise the network, demonstrating it actually works.  for instance, nodeenv downloads the interpreter, the other tests done that the package manager works

**Comment by jayvdb** [comment]
You are right; `test_warning_on_tags_only` now passes.

And node and other lang tests failed due to internet.

`tests/make_archives_test.py::test_main` is trying to fetch the repos in `pre_commit/make_archives.py::REPOS` - definitely looks like an internet test.

My `-k` is down to `-k 'not (test_installed_from_venv or test_environment_not_sourced or test_run_a_ruby_hook or test_run_versioned_ruby_hook or test_run_ruby_hook_with_disable_shared_gems or test_golang_hook or test_golang_hook_still_works_when_gobin_is_set or test_local_rust_additional_dependencies or test_local_golang_additional_dependencies or test_additional_golang_dependencies_installed or test_additional_golang_dependencies_installed or test_additional_golang_dependencies_installed or test_additional_ruby_dependencies_installed or test_additional_rust_cli_dependencies_installed or test_additional_rust_lib_dependencies_installed or test_run_versioned_node_hook or test_additional_node_dependencies_installed or test_main or test_additional_dependencies_roll_forward or test_switch_language_versions_doesnt_clobber)'`

I have `test_installed_from_venv` and `test_environment_not_sourced` mostly figured out, as being due to PYTHONPATH not being carried through.  rpmbuild VMs need to use PYTHONPATH as the install prefix is different from the read-only site-packages were build dependency packages are located.

Ideally, I'd like to propose a patch like https://github.com/ofek/hatch/pull/59 , which uses a little helper to check network

https://github.com/ofek/hatch/blob/666fc1a1b383cf9c882720bbb90a5cdf4d7b8110/tests/utils.py#L50

Even if the decorator is sometimes missed, it will be easy for packagers to add extra markers if the infrastructure is already in place.
