### ISSUE TITLE
Tests assume invocation from a git directory

### ISSUE THREAD

**Issue by jayvdb** [pre-commit/pre-commit#1184]
Running the tests from a tarball results in lots of errors.
A simple `git init` does the trick.
However https://pypi.org/project/pytest-git/ could be used to create and destroy a temporary repo.

**Comment by asottile** [comment]
doesn't feel like a bug, all of our testing scenarios run from `git` and it is developed from `git`

**Comment by asottile** [comment]
patches welcome of course :)
