### ISSUE TITLE
feature: make travis lint work as a pre-commit hook

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1189]
More recently Travis team managed to [revive their linter](https://blog.travis-ci.com/2019-10-24-build-config-validation) and it would be very useful if we can help them make it run as a pre-commit hook as I suppose they don't know.

**Comment by asottile** [comment]
I don't think there's anything actionable from the pre-commit framework -- the directions for setting up a hook are [here](https://pre-commit.com/#new-hooks) and once it's ready it can be added to the docs [here](https://github.com/pre-commit/pre-commit.github.io/blob/real_master/all-repos.yaml)
