### ISSUE TITLE
Docker language seems broken

### ISSUE THREAD

**Issue by NielsZeilemaker** [pre-commit/pre-commit#1190]
I trying to use the docker language to run some unit-tests in a docker container. In my repo I have a Dockerfile in the root, but somehow it doesn't get copied into the pre-commit cache folder. And hence the docker build fails. If I manually copy the Dockerfile into the cache folder it works.

Am I doing something wrong?

This is my .pre-commit-config.yaml file:
```
repos:
- repo: local
  hooks:
    - id: tests
      name: Run tests
      entry: python setup.py test
      language: docker
```
And this is the output:
```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for local.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/docker', 'build', '--tag', 'pre-commit-d696ec7745d71dd1bd4c68fe1d1f551f', '--label', 'PRE_COMMIT', '--pull', '.')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/vsts/.cache/pre-commit/repo114zeupo/Dockerfile: no such file or directory
```

**Comment by asottile** [comment]
the `docker` language [does not have `local` support](https://pre-commit.com/#docker). the only languages with `local` support are `script` + `system` and those which support `additional_dependencies`

(this is because pre-commit does not install anything from the repository being linted -- for any language)

**Comment by NielsZeilemaker** [comment]
Thanks Anthony, I will go that route.
