### ISSUE TITLE
this is not a troll, please revert #1179 before making a new release

### ISSUE THREAD

**Issue by haiden77** [pre-commit/pre-commit#1191]
please revert #1179, it broke all of my hooks at work and my boss said he'll fire me if I don't fix them ASAP. I don't know how to fork and fix it so it depends you pre-commit team.

**Comment by haiden77** [comment]
we use master version of pre-commit because we like new fancy features

**Comment by asottile** [comment]
do you have an example of breakage?  this change hasn't even been released yet

**Comment by haiden77** [comment]
you are thinking I am a troll, but I am not

**Comment by haiden77** [comment]
```py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
ValueError: Hooks failed, reason: 's replaced with /
```

**Comment by haiden77** [comment]
a short note, I am not @haydennyyy

**Comment by asottile** [comment]
that's on line 1 my dude, you definitely just wrote

```python
raise ValueError('...')
```

**Comment by haiden77** [comment]
i have some hooks that rewrites my code for me and puts everything to one line

**Comment by haydennyyy** [comment]
@haiden77 Nice cover-up. Our plan to overthrow Anthony's reign of terror over the pre-commit codebase is coming along swimmingly! Muahahahahaha!

**Comment by haiden77** [comment]
i think i can call them meta-hooks because they generate my hooks. like classes that generates classes are metaclasses and grammars that generates grammars are metagrammars

**Comment by haiden77** [comment]
generator throw

**Comment by haiden77** [comment]
putting everything in one-line optimizes my code

**Comment by haiden77** [comment]
i dont use that project

**Comment by asottile** [comment]
very funny :P

**Comment by haiden77** [comment]
my boss wrote onelinerizer but it is for python3.10
