### ISSUE TITLE
ruby-build  tar is out of date so you can't use ruby versions later than 2016

### ISSUE THREAD

**Issue by choffee** [pre-commit/pre-commit#1193]
Can the ruby-build.tar in resources be updated?

**Comment by asottile** [comment]
They absolutely can, would you like to?

Note that prebuilt versions are not limited by the `ruby-build` bits so you can usually get newer ones as long as you [pick one that exists](https://rvm.io/binaries/)

**Comment by choffee** [comment]
Fair play :) I've added in the latest build from their github.

RVM stopped building debian binaries a few years ago so I always have to compile.

**Comment by asottile** [comment]
via #1195

**Comment by asottile** [comment]
this has been released as part of 1.20 -- thanks again for the issue and patch!
