### ISSUE TITLE
allow pre-commit verbosity to be passed to the hook

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1199]
Calling pre-commit with verbosity does not have any effect on the verbosity of the called hook, which is likely needing its own `-v` added.

This means that hook creators should be able to pass verbosity to the called hook script when pre-commit is called with `-v`.

I remember that I was able to implement [something similar with tox](https://github.com/tox-dev/tox/issues/947), so what we need is an expansion that expands to nothing when -v is not used and expands to a user text when present.

Mainly if we would have something like `{verbose:-v}` that expands to empty string when not in verbose mode or to `-v` when verbose it called we can allow users to control verbosity without having to change the hook configuration files.

**Comment by asottile** [comment]
I am not going to implement expansion

I'd accept a PR to pass along `PRE_COMMIT_VERBOSE` as an environment variable -- there's precedent already: https://github.com/pre-commit/pre-commit/blob/0bc40bc4ea081802dd41ac92068104dfde468f6d/pre_commit/commands/run.py#L271-L272

what do you think?

**Comment by asottile** [comment]
alternatively, you could configure your hook to always be verbose -- pre-commit will hide it unless shown -- does that not work?

**Comment by ssbarnea** [comment]
Yeah, passing envar seems like a smart approach, especially as it would not be the first. I will make a PR when the need strikes again, now I am busy with more broken stuff on ansible-lint.

**Comment by asottile** [comment]
looking forward to the PR :+1:
