### ISSUE TITLE
29 tests failing ... what do I do wrong?

### ISSUE THREAD

**Issue by mcepl** [pre-commit/pre-commit#1202]
Hi,

trying to package pre-commit for openSUSE package, and I have a terrible time with trying to make the testsuite pass.

With the package installed in the specific directory I run

```sh
export GIT_AUTHOR_NAME=test GIT_COMMITTER_NAME=test \
GIT_AUTHOR_EMAIL=test@example.com GIT_COMMITTER_EMAIL=test@example.com \
VIRTUALENV_NO_DOWNLOAD=1 PRE_COMMIT_NO_CONCURRENCY=1
PYTHONPATH=:/home/abuild/rpmbuild/BUILDROOT/python-pre-commit-1.20.0-0.x86_64/usr/lib/python3.7/site-packages \
py.test-3.7 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v
```

but the results are rather tragic. I have two suspicions and I am not sure how to overcome either of these:

1. There is still something missing from my test environment,

2. SUSE build environment doesn’t allow access to the network (for obvious reasons), and it seems that some (cargo, go) tests require it. Is there a way how en masse skip all tests requiring network access?

Could you help me please how to overcome these issues?

[Full build log](https://github.com/pre-commit/pre-commit/files/3798841/_log.txt)

**Comment by asottile** [comment]
sorry I'm not really a debugging service -- here's my first guess at these:

- `test_all_cmds[*]`, `test_try_repo`, `test_warnings_on_tags_only`: the testsuite assumes you're running from a git checkout -- you can probably `git init .` before running
- `test_main` (the `make_archives` version of this test): this requires network
- `test_switch_language_versions_doesnt_clobber` - looks like your installation of `python2` is broken?
- `test_run_a_node_hook`, `test_run_versioned_node_hook`, `test_additional_node_dependencies_installed`: requires network for `nodeenv`
- `test_run_a_ruby_hook`, `test_additional_ruby_dependencies_installed`: you need to have `gem` installed
- `test_run_versioned_ruby_hook`, `test_run_ruby_hook_with_disable_shared_gems`: this requires network for `rbenv`
- `test_golang_hook`, `test_golang_hook_still_works_when_gobin_is_set`, `test_additional_golang_dependencies_installed`, `test_local_golang_additional_dependencies`: you need to have `go` installed
- `test_rust_hook`, `test_additional_rust_lib_dependencies_installed`, `test_local_rust_additional_dependencies`: you need to have `cargo` installed
- `test_additional_dependencies_roll_forward`: network is required
- `test_installed_from_venv` I suspect you have some `PYTHONPATH` shenanigans going on? hard to tell
- `test_healthy_types_py_in_cwd`: no idea, probably a problem with your environment

you can exclude tests using `-k`

**Comment by mcepl** [comment]
Thank you very much.
