### ISSUE TITLE
RFE: multiple config files or include feature

### ISSUE THREAD

**Issue by scop** [pre-commit/pre-commit#1203]
Being able to specify an alternate config files is nice for example for setups where certain hooks should not be enabled by default. But it comes with a maintenance burden; if all setups should run hooks A and B, and C is optional e.g. at user discretion, we need to create two configs; one with A and B, and another with A, B, and C.

I can think of at least two options for improving on this:
1. Make it possible to specify multiple config files, at least for `install`. Configs from different files would be merged. (For `run` it's not that crucial, as one can just `run` several times with different configs.)
2. Make it possible to include other configs from a config file.

**Comment by asottile** [comment]
multiple configs / inclusion is not going to be implemented, sorry -- you can read some related discussion in #731
