### ISSUE TITLE
fatal: reference is not a tree <commit> with older git versions

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1211]
On CentOS-7 with all updates included, current git version is `git version 1.8.3.1` which reproduces this pre-commit bug:

```
[INFO] Initializing environment for https://github.com/ansible/ansible-lint.git.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'checkout', 'ad721b6cde91a65e28d1f4fa4052bb721b17ae11')
Return code: 128
Errors:
    fatal: reference is not a tree: ad721b6cde91a65e28d1f4fa4052bb721b17ae11
```

Hook config:
```
---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: ad721b6cde91a65e28d1f4fa4052bb721b17ae11
    hooks:
      - id: ansible-lint
```

As one of my colleagues described this happens due to pre-commit internals as git itself is perfectly able to clone the repo and get this commit.

## Background

> [11:39:17]  <jpena>	zbr: ok, I got the reason for the error, and it's in pre_commit
> [11:40:06]  <jpena>	The sequence of commands it runs is: https://softwarefactory-project.io/paste/show/1648/
> [11:40:27]  <jpena>	since you're specifying a commit and not a tag or branch, it fails because it didn't do a full clone
> [11:40:35]  <jpena>	I have reproduced it locally
> [11:41:35]  <jpena>	it starts in https://github.com/pre-commit/pre-commit/blob/master/pre_commit/store.py#L157-L172, which then calls https://github.com/pre-commit/pre-commit/blob/master/pre_commit/git.py#L152-L158, and finally tries the checkout at https://github.com/pre-commit/pre-commit/blob/master/pre_commit/store.py#L139-L144
> [11:49:40]  <zbr>	jpena: interesting because I used commit in the past and i did not encounter the bug
> [11:50:19]  <zbr>	also this does not explain why it works locally for me, i rememeber that I cleaned the cache directory
> [11:50:39]  <zbr>	behavior seems to to vary, maybe depends on git version?
> [11:51:30]  <zbr>	jpena: what git version do you have where you reproduced it?
> [11:58:27]  <jpena>	zbr: 1.8.3.1
> [11:58:31]  <jpena>	let me try it in fedora
> [11:59:05]  <zbr>	at least we could raise a valid bug once we narrow it down
> [11:59:30]  <jpena>	zbr: in fedora (git version 2.21.0) it does not fail

**Comment by javierpena** [comment]
I can confirm Sorin's observations. With git 1.8, it looks like it is not enough to do the git init/git remote add/git fetch origin process to get a commit reference.

**Comment by asottile** [comment]
I can't reproduce, please provide a reproduction:

```console
(venv) [root@b21a1ee7374d demo]# pre-commit install-hooks
[INFO] Initializing environment for https://github.com/ansible/ansible-lint.git.
[INFO] Installing environment for https://github.com/ansible/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
(venv) [root@b21a1ee7374d demo]# cat .pre-commit-config.yaml 
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: ad721b6cde91a65e28d1f4fa4052bb721b17ae11
    hooks:
      - id: ansible-lint
(venv) [root@b21a1ee7374d demo]# git --version
git version 1.8.3.1
```

Or if you just want git commands that do what pre-commit does:

```console
(venv) [root@b21a1ee7374d tmp]# mkdir y
(venv) [root@b21a1ee7374d tmp]# cd !$
cd y
(venv) [root@b21a1ee7374d y]# git init .
Initialized empty Git repository in /tmp/y/.git/
(venv) [root@b21a1ee7374d y]# git remote add origin https://github.com/ansible/ansible-lint.git
(venv) [root@b21a1ee7374d y]# git fetch origin --tags
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 3867 (delta 4), reused 8 (delta 2), pack-reused 3849
Receiving objects: 100% (3867/3867), 3.50 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2035/2035), done.
From https://github.com/ansible/ansible-lint
 * [new tag]         v3.1.1     -> v3.1.1
 * [new tag]         v3.1.2     -> v3.1.2
 * [new tag]         v3.1.3     -> v3.1.3
 * [new tag]         v3.2.0     -> v3.2.0
 * [new tag]         v3.2.1     -> v3.2.1
 * [new tag]         v3.2.4     -> v3.2.4
 * [new tag]         v3.2.5     -> v3.2.5
 * [new tag]         v3.3.0     -> v3.3.0
 * [new tag]         v3.3.1     -> v3.3.1
 * [new tag]         v3.3.2     -> v3.3.2
 * [new tag]         v3.3.3     -> v3.3.3
 * [new tag]         v3.4.0     -> v3.4.0
 * [new tag]         v3.4.0rc1  -> v3.4.0rc1
 * [new tag]         v3.4.0rc4  -> v3.4.0rc4
 * [new tag]         v3.4.1     -> v3.4.1
 * [new tag]         v3.4.10    -> v3.4.10
 * [new tag]         v3.4.11    -> v3.4.11
 * [new tag]         v3.4.12    -> v3.4.12
 * [new tag]         v3.4.13    -> v3.4.13
 * [new tag]         v3.4.14    -> v3.4.14
 * [new tag]         v3.4.15    -> v3.4.15
 * [new tag]         v3.4.16    -> v3.4.16
 * [new tag]         v3.4.17    -> v3.4.17
 * [new tag]         v3.4.18    -> v3.4.18
 * [new tag]         v3.4.19    -> v3.4.19
 * [new tag]         v3.4.2     -> v3.4.2
 * [new tag]         v3.4.20    -> v3.4.20
 * [new tag]         v3.4.21    -> v3.4.21
 * [new tag]         v3.4.22    -> v3.4.22
 * [new tag]         v3.4.23    -> v3.4.23
 * [new tag]         v3.4.3     -> v3.4.3
 * [new tag]         v3.4.4     -> v3.4.4
 * [new tag]         v3.4.5     -> v3.4.5
 * [new tag]         v3.4.6     -> v3.4.6
 * [new tag]         v3.4.7     -> v3.4.7
 * [new tag]         v3.4.8     -> v3.4.8
 * [new tag]         v3.4.9     -> v3.4.9
 * [new tag]         v3.5.0     -> v3.5.0
 * [new tag]         v3.5.0rc1  -> v3.5.0rc1
 * [new tag]         v3.5.1     -> v3.5.1
 * [new tag]         v4.0.0     -> v4.0.0
 * [new tag]         v4.0.0a0   -> v4.0.0a0
 * [new tag]         v4.0.0a1   -> v4.0.0a1
 * [new tag]         v4.0.0a2   -> v4.0.0a2
 * [new tag]         v4.0.1     -> v4.0.1
 * [new tag]         v4.1.0     -> v4.1.0
 * [new tag]         v4.1.0a0   -> v4.1.0a0
 * [new tag]         v4.1.1a0   -> v4.1.1a0
 * [new tag]         v4.1.1a1   -> v4.1.1a1
 * [new tag]         v4.1.1a2   -> v4.1.1a2
 * [new tag]         v4.1.1a3   -> v4.1.1a3
 * [new tag]         v4.1.1a4   -> v4.1.1a4
(venv) [root@b21a1ee7374d y]# git checkout ad721b6cde91a65e28d1f4fa4052bb721b17ae11
Note: checking out 'ad721b6cde91a65e28d1f4fa4052bb721b17ae11'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ad721b6... Enable ansible-lint to auto-detect roles/playbooks
```

**Comment by asottile** [comment]
do you have a MITM proxy that's maybe caching an old version of this git clone?

**Comment by ssbarnea** [comment]
The resan why you are not able reproduce the bug is because few minutes ago they added the `v4.1.1a4 ` tag which points to this commit. I asked them to do this in order to be able to workaround this bug.

As long you put a commit that is newer than the tags being pulled, you will reproduce the bug.

And it even makes sense because pre-commit does not really clone the repository, it does only pull *some* tags. This does not imply getting all the commits.

I guess something changed internally with newer versions of git and it started to pull more than the tags. Still, that relies on git internals which can change. I think that only a clone/pull would be safe.

**Comment by asottile** [comment]
the split out commands are ~roughly equivalent to what `clone` does -- I'm not going to officially support a version of `git` from 2012 but if you'd like to submit a patch feel free

**Comment by ssbarnea** [comment]
Any reason for not performing a clone? I am going to look into a way to avoid this bug with minimal changes.

**Comment by asottile** [comment]
it's slower

**Comment by asottile** [comment]
if I had to guess it's just the `fetch` command you need to change

**Comment by ssbarnea** [comment]
I am forced to find a solution on pre-commit itself as I just found another bug which will be fixed by https://github.com/ansible/ansible-lint/pull/628 but I cannot ask for new tag. Expect a PR tomorrow as now I am too tired.

**Comment by asottile** [comment]
:man_shrugging: you're not really _forced_ to do anything ;)

**Comment by ssbarnea** [comment]
I had a [good progress](https://github.com/ssbarnea/pre-commit/commit/01d598760bbdfaa2806bf3952fa0a01bb1f1c676/checks?check_suite_id=301747814) but because pre-commit is currently not CI tested on multiple platforms, I find new bugs.

**Comment by asottile** [comment]
you've got a too old version of setuptools to build from source

**Comment by asottile** [comment]
@ssbarnea any updates on this?

**Comment by ssbarnea** [comment]
@asottile My interests to contribute went down when my proposal to add cross-platform testing was refused at https://github.com/pre-commit/pre-commit/issues/1213 -- mainly I do find the pre-commit support matrix very-vague ("linux" is not a platform, it needs to specify exactly which platforms are tested/supported). Using containers to test cross-platform can be done very easy even with a single travis job that tests all (linux) platforms. 

Still, without testing, why should I bother?

To not be misleading, pre-commit should state exactly what platforms is tested on (name and version) and which ones are not supported. I can fully understand that what is not mentioned is more of a best-effort (like accepting bugfixes).

It worth documenting the fact that you do not want to add extra platform testing to pre-commit.

All this issue started because pre-commit does not check git version and relies on some behaviors which were introduced in 2.x. pre-commit only partially works with older git, until you try to use some advanced features. Ideally pre-commit should have job that runs with oldest supported git version and prevents regressions. I am sure that cloning was removed at some point as part of an optimization, an optimization what introduced that issue. Without CI testing, stuff like this would happen.

The fact that you also refused to correct known GitLab bug on https://gitlab.com/pycqa/flake8/merge_requests/381 also makes me wonder if it worth the struggle.

I also seen that the recent adoption of azure pipelines moved the CI code to your personal repository which makes it much harder to identify on which platforms is the code tests or to extend 
the support matrix.

Don't get me wrong, **I do really appreciate the huge amount of effort you put on these tools** and especially on pre-commit. I love it, still I am more inclined to contribute back to projects where decisions are made maybe a little bit more democratic.

**Comment by asottile** [comment]
seems petty but ok

**Comment by garborg** [comment]
This is affecting me on targets with old git and shas newer than the latest tag. The issue as titled and described seems as relevant as ever even if the resolution outlined in a couple of the comments has stalled out -- re-open?

**Comment by asottile** [comment]
If you'd like to submit a patch, by all means

If you want, the line to fix is this one, probably just needs another arg or something: https://github.com/pre-commit/pre-commit/blob/0fd4a2ea38df4f276e43397e21ecb3fcbc96d122/pre_commit/store.py#L142
