### ISSUE TITLE
Untracked files should be stashed

### ISSUE THREAD

**Issue by dzamlo** [pre-commit/pre-commit#1212]
Currently, untracked files are not stashed when pre-commit run. For hooks that takes a list of files as arguments, this is not an issue. 
But for hooks that check the working directory (`pass_filenames: false`) this is problematic.
For example, I have a local hook that run `./gradlew check`. But when I have untracked files, the hook often fail if I try to commit only some of the modified files. The files that are modified but not staged are stashed but not the untracked files. This make the working directory incoherent

I believe that it would make sense to stash the untracked files like the not staged changes. This would ensure that the the working directory match what is committed.

**Comment by asottile** [comment]
this is a dupe but I'm on my phone, pre-commit can't do this as it would potentially blow away pre-commit itself (say, in `./venv`)

pass_filenames is an escape hatch already from the supported normal way and so you're kind of on your own to manage that

**Comment by nameer** [comment]
Hey @asottile, I know this is years old issue but I didn't want to create a new one.

Files and folders such as `.venv` are usually git-ignored. Instead of staging all files, can we stage only untracked, non-ignored files?

**Comment by asottile** [comment]
no thanks
