### ISSUE TITLE
feature: add ci testing on centos-7 platform

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1213]
As I recently faced two bugs related to the older git version that comes with centos-7, I would like to propose to add a CI test that runs pre-commit on centos-7, so we can avoid future regressions.

This testing can be implemented using a container, maybe even using tox-docker and should include at least two tests that we already know to fail:
* cloning a gitlab repo without .git at the end of url - flake8
* cloning a repo that use a commit revision instead of a tag/branch name

Is this ok? If so, what path would you recommend? I can easily make a PR to enable that.

**Comment by asottile** [comment]
no thanks, centos 7 is very old
