### ISSUE TITLE
 Name 'json' already defined (by an import)

### ISSUE THREAD

**Issue by chunji08** [pre-commit/pre-commit#1217]
This is my code in python 3.7
```
    54  try:
    55      import json
    56  except ImportError:
    57      import simplejson as json
```
And when I run pre-commit in such cmd: 

`pre-commit run --all-files`, 

I am getting such result: 
`xxx.py py:57: error: Name 'json' already defined (by an import)
`

Any way I may by-pass such failure ?  

my pre-commit is of version 1.2.0 on Ubuntu 16.0.4. 

Thanks, 

Jack

**Comment by asottile** [comment]
pre-commit is just a framework and doesn't implement any lint checks itself -- you probably want to check with whatever hook you're using

Also note that pre-commit 1.2.0 is very very old (2017-10-03)

**Comment by chunji08** [comment]
Thanks you for the tips.
