### ISSUE TITLE
consider activating sponsorship option

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1223]
As I like pre-commit tool and I would like to be able to donate some $/month to show my support for python projects I use a lot.

Recently GitHub made it very easy to do this and even activating a sponsor profile seems to take only few days, check [mine](https://github.com/sponsors/ssbarnea).  I don't see this as being a revenue stream but a more visible way to say thank you. I am personally curious how many users would end-up giving a dime for it.

I think their program has great networking potential as they also list on your own provide to which projects you are donating, look at mine to see tox maintainer listed.

I would have asked the same for flake8 but it is hosted on gitlab and I am not sure if it is possible to activate sponsorshipt on its github mirror, maybe it works.

PS. Apparently GitHub is also matching donation during the first year.

**Comment by asottile** [comment]
sounds good!  seems the organization-level sponsors bit is still in waitlist-beta :thinking:

**Comment by asottile** [comment]
I've [enabled this for my personal account](https://github.com/sponsors/asottile) but the organization level requires some more work (centralized non-personal bank account, etc.) and a beta signup.

thanks for the issue!   when it comes out of beta I'll see how much work it is to set up for the org itself (I hear Open Collective is also working on something which makes this signup more streamlined)
