### ISSUE TITLE
Display durations for hooks

### ISSUE THREAD

**Issue by blueyed** [pre-commit/pre-commit#1227]
Using pre-commit often takes 5+s, which is kind of a bummer for `gcma` (`"git commit --amend" "$@" `).

Therefore I'd like to be aware/notified about the slowest hooks, to potentially improve/remove them then.

It would be nice if pre-commit would display durations by default already - given that each hook takes a line of terminal output already it should be ok to add it there.

For reference: I am dispaying total durations already with 77aab5e ("quiet by default").

**Comment by asottile** [comment]
Dupe #1144
