### ISSUE TITLE
Make `bash` hooks work under Windows through WSL or MSys64

### ISSUE THREAD

**Issue by kvalkhof75** [pre-commit/pre-commit#1229]
I work in a mixed environment (Linux and Windows) and I would really like it if `bash` hooks work under Windows through WSL, `MSys64` or even `cygwin`.

Now the hook just seems to fail because paths are not converted to the format accepted by the 'bash` 'container'.

So if we can just correct the path for each file passed as argument then we would be fine again.

Attention points:
  - Fix the drive prefix. Usually something like `C:\` -> `/mnt/c`. The tail then just needs its slashes fixed.
  - Fix incorrect cased paths, because Windows paths are case preserving and POSIX paths are case sensitive. (`MYNICEFILE.txt` is accepted on Windows, but on POSIX it really is `MyNiceFile.TXT`)
  - UNC paths.
  - Take care of absolute paths, relative paths and semi-relative paths like `D:MyPath\MyFile.txt` while `C:` is the active drive.
  - Find the correct insertion point in the existing code. (`normalize_cmd` in `parse_shebang.py` ?)
  - Only change path parameters, not actual parameters.
  - Make it work for Python 2.7 + (instead of just 3.6).

If you like it then I will do the work.

Note that I accidentally made a pull request earlier. I did expect the request to end up just on my fork. Guess how experienced I am in contributing...

<https://github.com/kvalkhof75/pre-commit/tree/bash-on-windows>
This has a minimum viable product.
It demonstrates that `shfmt` installed in `WSL` through `apt` will succeed with the development `pre-commit` activated with `venv\Scripts\activate.bat` and then executed as `pre-commit run shfmt --file bash_script.sh`.
This will fail without the changes.

**Comment by asottile** [comment]
Ah, this is because their script is buggy: https://github.com/syntaqx/git-hooks/blob/master/hooks/shfmt.sh

in particular this line: https://github.com/syntaqx/git-hooks/blob/f16f18866390cba642e8af6073ed59504aeada5c/hooks/shfmt.sh#L16

Here's a small example demonstrating their bash bug:

```bash
#!/usr/bin/env bash
set -euxo pipefail

cmd="echo $*"
${cmd}
```

```console
$ bash t.sh  'hello\ world'
+ cmd='echo hello\ world'
+ echo 'hello\' world
hello\ world
```

It is splatting the arguments (breaking spaces, special characters, etc.)

Here's the "correct" way to do this (using arrays):

```bash
#!/usr/bin/env bash
set -euxo pipefail

cmd=(echo "$@")
"${cmd[@]}"
```

```console
$ bash t.sh  'hello\ world'
+ cmd=(echo "$@")
+ echo 'hello\ world'
hello\ world
```

(notice how it preserves the single argument as a single argument)

A general rule of thumb when working with `bash` is to **never use `$*`**

**Comment by asottile** [comment]
@kvalkhof75 could you verify the fix I made in https://github.com/syntaqx/git-hooks/pull/3 and comment / follow up there?  thanks again for the issue!

**Comment by tik9** [comment]
@kvalkhof75 I also work on WSL and use VSCode in WSL remote. 
I face an issue: how can I tell vscode the paths to Git and Python (in /mnt/c/programm..)?

**Comment by kvalkhof75** [comment]
@tik9 I do not use VSCode, so I do not know how to configure its settings.

You may want to describe your issue in more detail. For example, do you have an issue with pre-commit or with VSCode?
