### ISSUE TITLE
Can't specify hook args with `pre-commit run`

### ISSUE THREAD

**Issue by bhrutledge** [pre-commit/pre-commit#1233]
I'm trying to synchronize hooks in pre-commit config with my development virtual environment and my editor (Visual Studio Code). I was intrigued by the solution proposed in https://github.com/pre-commit/pre-commit-hooks/issues/311#issuecomment-562183852, so I set up my VS Code configuration like:

```json
{
  "python.linting.flake8Path": "venv/bin/pre-commit",
  "python.linting.flake8Args": [
    "run",
    "flake8",
    "--files",
  ],
}
```

That results in VS Code running:

```
pre-commit run flake8 --files --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/Code/pytest-quarantine/src/plugin.py
```

The first problem is that the `--format` argument becomes the `--files` value. TBH, I'm not sure if/how that could be fixed in my VS Code configuration, so that might be a deal-breaker.

But, assuming I *could* get VS Code to run a command something like:

```
pre-commit run flake8 --files ~/Code/pytest-quarantine/src/plugin.py --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s
```

The `--format` arg isn't recognized by pre-commit. I was hoping I could add `-- ` before `--format` (similar to [`posargs` in tox](https://tox.readthedocs.io/en/latest/example/general.html#interactively-passing-positional-arguments)), but that didn't work either.

I will probably try [repository local hooks](https://pre-commit.com/#repository-local-hooks) as described in #945, which I'm hoping will leave my VS Code config unchanged. So, feel free to close this. I mostly just wanted to document the attempt, and see if anybody chimed in with ideas.

Thanks again for making this awesome tool.

**Comment by asottile** [comment]
yep `pre-commit run` / `pre-commit try-repo` don't support reconfiguring the underlying hook -- they're designed to replicate exactly what's configured

one way you could do this is to use a `stages: [manual]` hook (such that it doesn't run normally, but can be triggered with `pre-commit run`)

something like:

```yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
    -   id: flake8
        alias: flake8-vscode
        args: ['--format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s']
        stages: [manual]
```

```console
$ pre-commit run --hook-stage manual flake8-vscode --files all_repos/grep.py
flake8...................................................................Failed
hookid: flake8

2,1,F,F401:'wat' imported but unused

```

**Comment by bhrutledge** [comment]
Thanks, @asottile. I'm glad to know about `alias` and `[manual]`. Unfortunately, the `--format` argument is appended by VS Code to whatever is in the `python.linting.flake8Args` setting, followed by the file argument. That means `--format` will still be used as the value of pre-commit's `--files`.

No big deal. This was an exercise in single-sourcing my linters & formatters from `extras_require` in setup.cfg. I got it working via `repo: local`, but then opted to let it go and removed them from setup.cfg in favor of a standard pre-commit config.

**Comment by asottile** [comment]
cheers -- thanks for the issue!
