### ISSUE TITLE
Using a Git repo in `additional_dependencies`

### ISSUE THREAD

**Issue by bhrutledge** [pre-commit/pre-commit#1238]
I'm guessing this is a `question`, with an easy resolution.

The released version of flake8 flags errors for the new `:=` operator in Python 3.8, because the released versions of pycodestyle and pyflakes don't support it. However, both projects have merged fixes into their `master` branches. I can workaround this in a virtual environment by installing pyflakes and pycodestyle from their Git repos:

```
python3.8 -m venv venv
source venv/bin/activate
pip install flake8 git+https://github.com/PyCQA/pyflakes git+https://gitlab.com/PyCQA/pycodestyle
flake8 test_walrus.py
```

In tox, this is possible by specifying `deps` for a `testenv`. However, the same approach doesn't seem to be working with pre-commit's `additional_dependencies`.

I put up an example repository with a test file, configurations for tox and pre-commit, and example output at https://github.com/bhrutledge/pre-commit-git-deps.

**Comment by bhrutledge** [comment]
As demonstrated in https://github.com/bhrutledge/pre-commit-git-deps/pull/1, apparently this can be solved by adding `#egg={package}`, e.g.:

```
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [
          "git+https://github.com/PyCQA/pyflakes#egg=pyflakes",
          "git+https://gitlab.com/PyCQA/pycodestyle#egg=pycodestyle",
        ]
```

Leaving this open in case there's some sort of follow-up to be done, but feel free to close.

**Comment by asottile** [comment]
yep! you got to it before I could, that is the correct answer
