### ISSUE TITLE
Blacklist string hook?

### ISSUE THREAD

**Issue by ahonnecke** [pre-commit/pre-commit#1242]
I'm looking for a hook that disallows arbitrary strings ("NOCOMMIT" or "TODO") for instance, where if a file has that string in it, the hook fails and does not allow for a commit.

**Comment by asottile** [comment]
pre-commit has a "language" which makes it easy to configure hooks like this: [`language: fail`](https://pre-commit.com/#fail)

**Comment by asottile** [comment]
errr actually you're looking for [`language: pygrep`](https://pre-commit.com/#pygrep) -- here's some examples: https://github.com/pre-commit/pygrep-hooks
