### ISSUE TITLE
How to run a local python file 

### ISSUE THREAD

**Issue by drummerboy2543** [pre-commit/pre-commit#1245]
Hi,

I am sorry if this is obvious but I am trying to run a simple python file for our project using pre-commit.
Essentially I want a git prehook to create a csv file every time it gets committed.

So this prehook has nothing to do with the code itself. I just want to generate a csv file based on the current code in the repo. I am also not trying to tap into different repos right now I just want to execute a python file that can look at our code and generate the csv.
 
I have been looking in the documentation and obviously I am missing something.

What exactly is a repo in this case? Is this just a git project? Does that mean my python scripts have to be in a repo to run? Or can they be anywhere on the computer?

How do these files run, obviously you are running linters and testing some files when running tools like black. Is there a common scheme my python functions have to adhere to in order for pre-commit to run said file? 

Also, I am not trying to test my code with pre-commit currently. I just want to make hooks that can be used by other people on my team. So we have the same development flow.

How does one execute a simple python file in the .pre-commit-config.yaml file?

The current directory setup I have is:
```
.git (Directory)
some_code (Directory)
.pre-commit-config.yaml
README.md
script_I_want_to_run.py
```

The yaml file I have is currently this. 
```
repos:
-   repo: local
    hooks:
    -   id: some_test
        name: script_I_want_to_run
        entry: python script_I_want_to_run
        language: system
        types: [python]
 ```       

That is the main question I have. I appreciate you taking the time to read this.
If this is not the place to ask questions. Please let me know where to go.
Also if you need more information from me please let me know.

Also thank you for making this awesome library, I can't wait to incorporate some of the plugins to linters you made in my workflow.

**Comment by asottile** [comment]
that looks correct (looks like you found the [repository local hooks](https://pre-commit.com/#repository-local-hooks) section of the docs), though I think you want either:

```
    entry: python -m script_I_want_to_run
```

or

```
    entry: python script_I_want_to_run.py
```

if you want it to always run you can use:

```
    always_run: true
```

and for that you probably want to remove `types` / `files` and you can also prevent it from forwarding arguments wiht

```
    pass_filenames: false
```

what's the current output you're getting and what do you expect to get -- maybe I can help in a more guided way with that info

**Comment by drummerboy2543** [comment]
Hey Asottile,

Thank you for getting back to me quickly!

The script is super simple it is literally

`print("Hello pre-commit activated this function.")` 

The reason I created a trivial script is I just wanted to get a basic setup and then go from there.
So I figured a print statement is the easiest way to check if it ran or not.

The output I ran before any changes made was:
 `script_I_want_to_run ............................................(no files to check)Skipped`

However, getting rid of types and adding a .py at the end of the entry point switched it to this.
`script_I_want_to_run ................................................................Passed`

Which means it ran successfully!

However, there is no output. (No "Hello pre-commit activated this function.")  Which makes sense because that is what verbose is for.

So that worked, I am confused however, because in the repository local hook section from
[ pre-commit.com](https://pre-commit.com/#repository-local-hooks) says:
`"A local hook must define id, name, language, entry, and **files / types** as specified under Creating new hooks"`

It says that I must specify a type.  However, the script ran correctly when I got rid of types. 

What am I missing here?

I know that in the [creating new hook section](https://pre-commit.com/#new-hooks) it says types are optional but it says it is required for[ local hooks section](https://pre-commit.com/#repository-local-hooks).

So, in summary, what am I missing here and what are types exactly? It seems to me, that 'type' is the type of file you want your hooks to run. 
But isn't that language? 







On another note, I was trying other configurations as well, and one of the configurations that I was surprised by that worked was: 

```
    -   id: some_test
        name: script_I_want_to_run
        entry: python script_I_want_to_run.py
        language: python
        verbose: true
```

What is weird about this configuration is that I am using python as my language choice. 

However, in the [python section of pre-commit .com](https://pre-commit.com/#python) it says.
"The hook repository must have a setup.py"

However, my script does not have a setup.py considering the python script is simply.
`print("Hello pre-commit activated this function.")` 

Also, it is not a package so there is no need for pip. Which it says it will use to install

Can you please clarify what that means? 

Finally, it looks like the [website says](https://pre-commit.com/#creating-new-hooks): 
` the language of the hook - tells pre-commit how to install the hook.`
I am assuming the "-" means and? 

If it is then my interpretation of  it means it is the language of the hook and it tells pre-commit how to install the hook based on the language. 

If that is the case I did not know "-" means and so it might be helpful to make that explicit (Maybe say and). 

Thanks again for taking the time to read this and helping a new guy like me out.

**Comment by asottile** [comment]
> "A local hook must define id, name, language, entry, and **files / types** as specified under Creating new hooks"

oops -- files / types isn't truly required, but otherwise it matches every file in the repository -- it _used_ to be required before `pass_filenames` / `always_run` were options

> What is weird about this configuration is that I am using python as my language choice.
>
> However, in the python section of pre-commit .com it says.
> "The hook repository must have a setup.py"

ah yeah for `repo: local` repositories none of the restrictions on remote repositories apply (a dummy `setup.py` / etc. is provided by `pre-commit` itself).  `repo: local` repositories are basically "configuration only" meaning you basically can only give them deps via `additional_dependencies` and such

> Finally, it looks like the website says:
> the language of the hook - tells pre-commit how to install the hook.
> I am assuming the "-" means and?

it's meant to be an emdash, just a separator -- you can interpret it as `and` and it reads the same :)

**Comment by asottile** [comment]
hope this answered your questions -- if you have any more feel free to comment here!

**Comment by Mandera** [comment]
This page is the first google result for `pre-commit run python file` so I'd like to (shamelessly) share a simple example without using this package.

Edit this file in your repo: `.git/hooks/pre-commit`

```
#!/usr/bin/env python

from package_in_your_venv import your_pre_commit_check

assert your_pre_commit_check()
```

It will use your active Venv and if it raises an Exception then the commit will be halted.

<hr>

This is a nice package but in this scenario, I think it's unnecessary.
Google understandably cannot distinguish between pre-commit the python package or pre-commit the git hook
