### ISSUE TITLE
Disabling color output should also do so for `FAIL` messages

### ISSUE THREAD

**Issue by eyalzek** [pre-commit/pre-commit#1247]
Running pre-commit with `--color never` doesn't disable color output for `FAIL` messages:

![image](https://user-images.githubusercontent.com/6243438/71250227-6f827380-231f-11ea-897d-032ab5b1f1b1.png)

**Comment by asottile** [comment]
can you provide more information? that `FAIL` message isn't coming from `pre-commit` and I don't believe we pass along a `pty` when `--color never` is specified (meaning `terraform` is just wrong here)

**Comment by asottile** [comment]
yep, `pre-commit` is doing the right thing here, whatever terraform hook you're using is either forcing color or doesn't properly detect a tty

![Capture7](https://user-images.githubusercontent.com/1810591/71263818-8b721f00-22f7-11ea-9e72-48bde51d9afb.png)

**Comment by eyalzek** [comment]
You're totally right - not a pre-commit issue.
