### ISSUE TITLE
Slightly broken links in output

### ISSUE THREAD

**Issue by yhoiseth** [pre-commit/pre-commit#1261]
`pre-commit autoupdate` outputs repository links:

```
Updating https://github.com/psf/black...already up to date.
Updating https://github.com/prettier/prettier...already up to date.
```

In iTerm2 on a Mac using Fish Shell—and probably lots of other setups as well—you can click the repository links (by holding down the _Command_ key):

<img width="668" alt="Screenshot 2020-01-01 at 15 21 32" src="https://user-images.githubusercontent.com/8469540/71642362-6fcd2800-2caa-11ea-9e00-d463dcdf9682.png">

But the link is slightly broken because there is no space after it—we're getting https://github.com/asottile/seed-isort-config...already instead of https://github.com/asottile/seed-isort-config.

This is a tiny issue, but it would be nice if we could fix it. I'll try to make a pull request to show what I mean.

**Comment by asottile** [comment]
This has been released as part of [v1.21.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.21.0) -- thanks again for the issue and PR 🎉!
