### ISSUE TITLE
Way to include hook that is skipped by default

### ISSUE THREAD

**Issue by commentator8** [pre-commit/pre-commit#1264]
I couldn't find this on the pre-commit site, but is there a way to include a hook that is skipped by default?

Use case is if i want to include e.g. pylint that is a little rough on a legacy code base but i want the ability to include it so that i can choose to run it manually from pre-commit (with the exclude etc honored) easily without having to install it manually. Or alternatively if phasing in a hook to have it off by default until the code base is ready then enable it with a single change.

**Comment by lsorber** [comment]
I think you can achieve that by adding the `stages: [manual]` property to the hook so that it only runs on manual invocations.

**Comment by commentator8** [comment]
Perfect - looks exactly like what i wanted. Thanks!

**Comment by asottile** [comment]
yep!  [`stages: [manual]`](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) is exactly what you're looking for -- thanks @lsorber for the assist :)
