### ISSUE TITLE
`default_stages` should probably not include `prepare-commit-msg` and `commit-msg`

### ISSUE THREAD

**Issue by lsorber** [pre-commit/pre-commit#1267]
If you install the `prepare-commit-msg` hook type with `pre-commit install --hook-type prepare-commit-msg`, then all installed hooks that don't define a `stages` property will run twice on commit: once for the `pre-commit` hook and once for the `prepare-commit-msg` hook.

Many of the provided [pre-commit hooks](https://github.com/pre-commit/pre-commit-hooks) don't set  the `stages` property and therefore run twice unintentionally in that scenario.

One solution could be to explicitly set the ([undocumented](https://github.com/pre-commit/pre-commit/issues/1265)) `stages` property in the hook definition in `.pre-commit-hooks.yaml`, but a more reasonable (though potentially breaking) default to me would be to limit the `default_stages` to `[commit, manual, push]`.

**Comment by asottile** [comment]
it includes all of the supported stages today, this is as far as I'm concerned the only reasonable default -- don't want to box people into particular setups

fortunately, the hooks in the other stages are incredibly unlikely to run against the `commit-msg` / `prepare-commit-msg` stage as the only file included for that stage is `.git/COMMIT_MSG` which doesn't match any of the common `files` / `types` that would be used for a linter (so they'll always be `Skipped`) -- for `pre-commit/pre-commit-hooks`, none of them without `stages` match `.git/COMMIT_MSG`

thanks for the issue nonetheless! but I'm not going to change this
