### ISSUE TITLE
Question: is it possible to run hooks from CLI?

### ISSUE THREAD

**Issue by a1tus** [pre-commit/pre-commit#1270]
In our project we already use some watchers that do their job on file save (isort for python, for example). Is it possible to use some bunch of hooks like that but without git - pass file name as argument and read from stdout.

I've installed pre-commit via pip and trying to run smth like:
`pre-commit run string_fixer --files test.py`

There's always error "An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?".

Thank you.

**Comment by asottile** [comment]
as the error message states (*it's not wrong!*), the pwd must be inside a git repository (this is necessary to locate the configuration file, and set a consistent working directory when running hooks)

though the `--files` option currently doesn't care if that file is managed by git (it can even be unrelated to the current repository) -- this behaviour was unintentional, but I see no reason to change it since it's kinda convenient 🤷‍♂ 

```console
$ git rev-parse --show-toplevel
/home/asottile/workspace/babi
$ pwd
/home/asottile/workspace/babi
$ pre-commit  run flake8 --files ../pre-commit/setup.py 
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

../pre-commit/setup.py:1:1: F401 'os' imported but unused

```

**Comment by a1tus** [comment]
Thanks! I've initiated git repo and created sample `.pre-commit-config.yaml` with one hook `double-quote-string-fixer`. After that my command `pre-commit run --files test.py` executed successfully.

This workaround will work for me, but still there's a question - could this be done in a better way?

I mean, we have some useful utils, for example `string_fixer.py`. It's useful by itself - without git or config or other stuff. At the moment we can't do that?

**Comment by asottile** [comment]
sure you can install any of the things separately -- but then you're kinda missing the point of `pre-commit` -- it's goal is to manage all of the installations, versions, knowing what files to run things on, knowing which things are version controlled and not.

but yeah any of the things are installable separately, for instance the official hooks can be installed using `pip install pre-commit-hooks`

**Comment by a1tus** [comment]
I understand the goal of pre-commit and we're already using it. Just waanted to clarify the _right way_ for this non-direct purpose (may be it will help someone later too). Thanks again.
