### ISSUE TITLE
pre-commit generates wrong python shebang when already inside a virtualenv

### ISSUE THREAD

**Issue by ansiblejunky** [pre-commit/pre-commit#1271]
Currently inside a custom virtualenv that is activated. I run `pre-commit install-hooks` and it downloads the hooks into the environment (in my case `ansible-review`).  When running the hook it fails with stack trace error: 
```
ImportError: No module named ruamel.yaml
```
This is because the shebang that was generated for the hook command is using the python executable inside the pre-commit environment! And not the virtualenv that is currently active!

`/home/myuser/.cache/pre-commit/repoErsWY5/py_env-python2.7/bin/ansible-review` has the following shebang info:
```
#!/home/myuser/.cache/pre-commit/repoErsWY5/py_env-python2.7/bin/python
```
And you can test the command using:
```
$ /home/myuser/.cache/pre-commit/repoErsWY5/py_env-python2.7/bin/python -c 'import ruamel.yaml'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ruamel.yaml
```

How to fix this or correct this?

**Comment by ansiblejunky** [comment]
Nevermind, it appears the problem was that I had set the `PYTHONPATH` env variable before running the `pre-commit install-hooks` command. That seems to have done it. The PYTHONPATH was pointing to the site-packages for the venv.

**Comment by asottile** [comment]
that shebang is correct fwiw
