### ISSUE TITLE
Node/npm post-install script failure when running as root

### ISSUE THREAD

**Issue by eyalzek** [pre-commit/pre-commit#1272]
when using `node` as the language for a pre-commit hook, it seems like it is expected to be running as user `1000`. This proves to be a problem when additional dependencies are installed and their post-install hooks are ran, for example this script: https://github.com/zloirock/core-js/blob/master/packages/core-js-pure/package.json#L55 will fail with:
```
    sh: 1: node: Permission denied
    npm ERR! code ELIFECYCLE
    npm ERR! syscall spawn
    npm ERR! file sh
    npm ERR! errno ENOENT
    npm ERR! core-js-pure@3.6.2 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
    npm ERR! spawn ENOENT
    npm ERR!
    npm ERR! Failed at the core-js-pure@3.6.2 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

according to this [stackoverflow thread](https://stackoverflow.com/a/53270214), it has to do with the [npm configuration option for user](https://docs.npmjs.com/misc/config#user). And indeed, running this as user 1000 works whereas running as root fails.

I created a minimal repo to reproduce this issue: https://github.com/eyalzek/pre-commit-node-root-user

Solutions to this issue at the moment are to either:
- run as user `1000`
- add `--ignore-scripts` to the list of `additional_dependencies` which will cause npm install to ignore scripts (https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/node.py#L77) - this is hacky and might have unexpected side effects

You might have more insight as to why this happens and how to properly fix it, but one way might be to allow passing npm configuration somehow?

**Comment by asottile** [comment]
as far as I know this has nothing to do with `pre-commit` and is an inherent issue with `npm` and some _bad choices_ they made around the root user

I assume this is docker?  I think you can set `ENV NPM_USER=root` to work around this iirc

**Comment by eyalzek** [comment]
@asottile I wasn't aware I can override npm config with env variables - the correct form is `npm_config_user=root`. This solves my problem, thanks!

**Comment by asottile** [comment]
perfect!  cheers and thanks for the issue 🎉

**Comment by playpauseandstop** [comment]
Thanks for pointing this. 

I have similar issue with GitHub Actions & running eslint pre-commit hook.

To fix just need to put,

```yaml
  env:
    npm_config_user: "root"
```

to job config.
