### ISSUE TITLE
Pre-push hook checks only when pushing to certain remote

### ISSUE THREAD

**Issue by dmbarreiro** [pre-commit/pre-commit#1274]
I have two remotes configured in my repository (`origin` and `upstream`) and I want my pre-push hook to fire and do the configured checks only when we push to `upstream`, bypassing all checks when we push to remote `origin`. Is this possible without using git `--no-verify` option?
I was checking for ways to obtain the remote from `pre-commit`as a parameter and pass it to my local hook to bypass the checks in case remote doesn't match `upstream` but I haven't been very successful. Any ideas on how to do this?

Thank you so much for all the great work you are doing with this project.

**Comment by asottile** [comment]
(moved to the proper project, `pre-commit/pre-commit-hooks` is for the builtin hook executables)

**Comment by asottile** [comment]
pre-commit currently doesn't expose that information (but it could!)

I think the only way it would be able to do so would be as an environment variable, here's roughly what you'd have to change to make this work:

1. in [`hook-tmpl`](https://github.com/pre-commit/pre-commit/blob/ef583d2fde05e631c59d6637e433bf86dd0e6331/pre_commit/resources/hook-tmpl#L125-L159) capture the values of `sys.argv[1]` (remote name) and `sys.argv[2]` (remote url) -- add these to `opts` in some way
2. in [`pre_commit/main.py`](https://github.com/pre-commit/pre-commit/blob/ef583d2fde05e631c59d6637e433bf86dd0e6331/pre_commit/main.py#L82-L113) add options for these two values (probably `--push-remote-name` and `--push-remote-url` or some such -- probably add these near the other hook-specific options like `--commit-msg-filename`)
3. in [`pre_commit/commands/run.py`](https://github.com/pre-commit/pre-commit/blob/ef583d2fde05e631c59d6637e433bf86dd0e6331/pre_commit/commands/run.py#L257-L260) expose those new environment variables when the values are set
4. in [`tests/commands/install_uninstall_test.py`](https://github.com/pre-commit/pre-commit/blob/ef583d2fde05e631c59d6637e433bf86dd0e6331/tests/commands/install_uninstall_test.py#L550-L561) write a test which exercises this (I've linked a related `pre-push` test)

let me know if you think this feature would be helpful or not and if you'd want to work on it

**Comment by dmbarreiro** [comment]
That's great! Yes, I'd like to work on it if that's OK for you.

**Comment by asottile** [comment]
sure!

**Comment by dmbarreiro** [comment]
After checking your proposed changes and the code a bit better I think this solution does not work for my case since the env vars will only be available (or so it seems looking at the code) through `pre-commit run --push-remote-name` and this is not so interesting for me since I do not trigger the pre-push hook with run, I just use pre-commit to install my hooks.

I would need a way to either inform my local hook about the remote we are pushing to (to be able act accordingly in the hook) or a way to skip the pre-push hook when pushing to a certain remotes (or the opossite, run it only when pushing to certain remote, both would work).

Again thank you so much for the quick replies and all the support.

**Comment by asottile** [comment]
so `hook-tmpl` is the thing that gets templated into `.git/hooks/pre-push` -- so it would be available

**Comment by asottile** [comment]
(basically the way `pre-commit` works is it templates that script into the `.git/hooks` directory, which eventually calls `pre-commit run ...` with the proper arguments)

**Comment by dmbarreiro** [comment]
Yest, it does! I think I have the code ready, I am figuring out how could I test it, I want to check the variable is available in the hook. I was trying to find similar test cases for other env vars like `--origin` and `--source` but couldn't find any. I will continue looking when I have some more time but testing is the only part missing I think.

**Comment by asottile** [comment]
oops looks like `--origin` and `--source` are untested

you can probably write a little shell hook and `echo` the variables and then run the hook using `verbose: true` or `--verbose` (probably can even get away with a `local` hook if you don't want to set up a full repository in `testing/resources`)

**Comment by asottile** [comment]
let me know if you need help writing a test, happy to supply that (you could start a WIP PR probably and I can give some pointers / code)

**Comment by asottile** [comment]
thanks again for the issue and patch!  this should land in pre-commit 2.0 when released

**Comment by jsamoocha** [comment]
I have a shell script I'd like to run pre-push, in which I need to know to which remote we're pushing. When using it as a "plain" pre-push script, it looked like:

```
#!/bin/sh

remote="$1"

echo "remote = $remote"

if [[ $remote == MY_SPECIAL_REMOTE ]]
then
# do something special
```
and the remote is passed to the script as a command line argument.

I'm trying to integrate it into my pre-commit flow as follows:

```
-   repo: local
    hooks:
    -   id: my_pre_push
        name: foobar
        entry: ./my_pre_push_script.sh
        language: script
        stages: [pre-push]
        pass_filenames: false
        always_run: true
        verbose: true
```

How can I use the above approach to gain access to the remote? Is it available as an env var to the script? Or am I missing something about passing the remote as an argument (which doesn't seem to happen out of the box)?

**Comment by asottile** [comment]
please don't ask new off topic questions on 3 year old issues
