### ISSUE TITLE
Question: Shell variables using language:docker_image

### ISSUE THREAD

**Issue by nmoreau-ocl** [pre-commit/pre-commit#1286]
Is the best/only way to populate shell/env variables like $PWD something like this?
```
...
language: system
entry: bash -c "docker run -v $PWD:/mnt image"
...
```

When I try to use language:docker_image pre-commit passes '$PWD' to docker which of course doesn't work.  Seems like a common use case and I couldn't find examples of how docker_image should be used in the supported hooks

**Comment by asottile** [comment]
you shouldn't need to add an additional mount, pre-commit automatically [adds a mount of the current code to `/src`](https://github.com/pre-commit/pre-commit/blob/5a625013071877a5b5dc8eba5b25c791c9c9c6ec/pre_commit/languages/docker.py#L97)

variable interpolation is not supported (somewhat intentionally, it's pretty complicated and very hard to get right)

**Comment by asottile** [comment]
seems this was missing from the docs so I'm adding it here: https://github.com/pre-commit/pre-commit.github.io/pull/289

**Comment by nmoreau-ocl** [comment]
Makes sense and thank you for the precise answer

**Comment by asottile** [comment]
no problem -- and thanks for the issue :tada:
