### ISSUE TITLE
[Question] compare two branches / commits hooks are skipped.

### ISSUE THREAD

**Issue by keivanzavari** [pre-commit/pre-commit#1290]
I am not sure if this is an issue or intended behavior.
I have branch `feature` that is being compared to `master`.
If I get a list of changed files like this:
```bash
export changed_files_list="$(git diff --name-only feature $(git merge-base feature master))"
echo $changed_files_list
```
There are files where I have defined certain hooks to be applied. They are working fine and well tested. But when I run pre-commit to the diff of two branches, the result of
```bash
pre-commit run --source feature --origin master
```
is not very clear. Those hooks that should be applied are skipped in the report.

**Comment by keivanzavari** [comment]
![Screenshot from 2020-01-17 16-13-57](https://user-images.githubusercontent.com/3716940/72623223-048b8300-3945-11ea-91be-a9b04fb36ec2.png)
I thought of sending a screenshot to show what I mean. My apologies if it's not very readable. Had to redact...

**Comment by keivanzavari** [comment]
![Screenshot from 2020-01-17 16-13-57](https://user-images.githubusercontent.com/3716940/72623391-53391d00-3945-11ea-963c-17fbcfdc7a29.png)
I thought of sending a screenshot to show what I mean. My apologies if it's not very readable. Had to redact...

**Comment by asottile** [comment]
looks like you have [the options backwards] (https://pre-commit.com/#pre-commit-run)

this is important because it does a directional diff and the opposite direction already contains the merge base (so no diff)

**Comment by keivanzavari** [comment]
Oh cool. Yes indeed. It's working now. Thanks.

**Comment by asottile** [comment]
cheers, the options have kind of bad names -- they were never really intended to be exposed but they are convenient so now they are documented. the names are that way as they're relative to `git push`
