### ISSUE TITLE
add action for adding new linters 

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1291]
To ease adding new linters, it would be very useful if users could do:

```bash
>pre-commit add flake8
flake8 added to your config file.

>pre-commit add
Please specify a known linter from list below or a git url:
flake8
doc8
bashate
ansible-lint
```

**Comment by asottile** [comment]
how would it work?

**Comment by ssbarnea** [comment]
Mainly we would store a catalog of `yaml` stubs that would be appended to the config file. We can even rely on github to download them in order to avoid the need to update pre-commit when they are changed.

For example SchemaStore project uses https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json to link schema names to their definitions.

If this catalog would be part of pre-commit itself or not is up to you, but at least it could be used to document official locations of the most popular tools. I doubt the number of tools would explode.

I would probably try to implement it myself if we agree about where to store the catalog.

**Comment by asottile** [comment]
this seems like it would quickly become a maintenance nightmare (lots of PRs to add / modify yaml snippets, constantly having to re-audit all of them / bump versions etc.) -- do you think this is accurate?

**Comment by ssbarnea** [comment]
I agree that bumping versions would be problem. I need to think about that aspect because we do not want to have to update these. Another option would be to rely on tool creators to expose the template in their repositories and our catalog would only look like:
```
- tools
  flake8: git://
  doc8: git://
```
We would only have to add or remove entries from this dictionary. To avoid being spammed with requests like "please add john-doe-cool-hooks to the catalog" we can document are rule of adding only popular mature projects (>100 stars and green CI).

As you probably observed my goal is to only make those proved good tools easier to activate, not to be a bazar of junk ;)

**Comment by asottile** [comment]
I think this is not all that different from https://pre-commit.com/hooks.html but I don't think we really need any sort of centralized list to power this or even a template (since we know the list of hooks that are in the repository just given a git url) -- this is how `try-repo` works for instance.

I'm not sure the value-add is there over grabbing a config from a `README` or such for this particular feature (you're probably going to want to figure out how a tool works / etc. anyway)

I'm inclined to defer this feature request

**Comment by ssbarnea** [comment]
Or we can let it rest for a while to see if there are others asking about the same thing. When I started using pre-commit myself, I was bit confused about how to add existing tools (not custom hooks).

To be honest I was even thinking about doctor mode where it could suggest you tools that you may want, based on existence of different file extensions or filenames on your repository.

**Comment by asottile** [comment]
yeah just sounds like a bunch of complexity that the tool can't really do a good job of anyway

going to defer this for now, if someone is interested in something like this please comment here with how this would benefit you and I can reopen
