### ISSUE TITLE
unversioned requirement importlib-meta prohibits using pip with --require-hashes mode

### ISSUE THREAD

**Issue by mpasternak** [pre-commit/pre-commit#1314]
Hi, 

I'm using pip-tools, esp. pip-compile. After adding your package (with require-hashes) mode, here's what I get when I try installing my resources.txt file

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-resources; python_version < "3.7" from https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl#sha256=6e2783b2538bd5a14678284a3962b0660c715e5a0f10243fd5e00a4b5974f50b (from pre-commit==2.0.1->-r requirements_dev.txt (line 196))
```

I suppose those two requirements (importlib-resources and importlib-meta) could be versioned.

**Comment by asottile** [comment]
this means you should list those with == in your file, it has nothing to do with this project

**Comment by asottile** [comment]
or this is a bug with pip-tools, either way the metadata here is correct as is

**Comment by atugushev** [comment]
@mpasternak could you [raise](https://github.com/jazzband/pip-tools/issues/new?template=bug-report.md) an issue in pip-tools' issue tracker we'll try to figure out what's wrong? BTW, I've tried to reproduce it locally with py36 but had no luck.

**Comment by atugushev** [comment]
@mpasternak got it, it seems you've compiled requirements on py37, but trying to install requirements on py36.

**Comment by mpasternak** [comment]
Hi @atugushev , thanks for analysing this small glitch. 

The deal is, that your package does not pin versions for importlib-resources and importlib-meta. After building a requirements.txt file with hashes from requirements.in by pip-compile, installation failed with the message I provided in my initial report. 

After giving it some thought, I think @asottile is right. pip-compile should somehow pin those two packages that pre-commit requires after building requirements.txt file. So this is pip-compile bug, if any. 

Thanks.
