### ISSUE TITLE
Add support for global index urls in pip config

### ISSUE THREAD

**Issue by collin-miller** [pre-commit/pre-commit#1316]
I have index for private indexes in my pip config; however, it doesn't appear that pre-commit uses those while trying to install dependencies. It would be best if these indexes were also searched while trying to setup the environment.

**Comment by asottile** [comment]
The suggestion is to use:

```yaml
    -   id: your-hook-id
        additional_dependencies: [--index-url=...]
```

that way your installation is consistent independent of your environment

**Comment by twmht** [comment]
@asottile 

how can i specifiy if i have multiple index-url?

**Comment by asottile** [comment]
imagine you are a pip install command, what would you do?
