### ISSUE TITLE
Support JSON with comments

### ISSUE THREAD

**Issue by TheButlah** [pre-commit/pre-commit#1320]
Although the JSON specification does not allow comments, people ubiquitously tend to put them in their json files anyway. This type of JSON file is often referred to as [JSONC](https://komkom.github.io/). It would be awesome if `check-json` supported jsonc as an opt-in flag, such as `--with-comments` or `--jsonc`. Alternatively, if it was deemed more in line with the goals of `pre-commit`, an additional hook called `check-jsonc` could be provided.

Would this be a feature that could be added? I think its a common enough use case to merit support via the main `pre-commit` repository.

**Comment by asottile** [comment]
this repository (pre-commit/pre-commit) is just the framework -- anyone is free to add a hook which supports and/or checks json with comments

**Comment by maresb** [comment]
@TheButlah, I just published a [check-json5 hook](https://gitlab.com/bmares/check-json5) which should do what you want. It's a drop-in replacement for `check-json`.
