### ISSUE TITLE
Supply official Docker/OCI image

### ISSUE THREAD

**Issue by Yajo** [pre-commit/pre-commit#1323]
I think that including a `pre-commit run -a` job is becoming a common pattern in almost any CI pipeline for projects that leverage pre-commit.

It'd be a big help to have a slim pre-commit image to run that.

A simple dockerfile like this should do the job, and it could be published to [Github package registry](https://github.com/features/packages) as a docker image [using github actions](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem):

```dockerfile
FROM python:3-alpine
COPY . /usr/local/src/pre-commit
RUN apk add --no-cache git
RUN pip install --no-cache-dir /usr/local/src/pre-commit
ENTRYPOINT ["pre-commit"]
```

**Comment by asottile** [comment]
I'm not sure what value this provides over someone just doing this in their own pipeline, also `alpine` is generally a poor choice when you need to install things (it also, for example, doesn't work for `nodeenv` currently)

what you probably want to do to end up with the most efficient CI is to do something like:

```dockerfile
...
ADD .pre-commit-config.yaml
RUN pre-commit install-hooks
...
```

which at that point a base image isn't really that useful

-- curious to hear your thoughts

**Comment by Yajo** [comment]
Well forget alpine then, that's not the most important part.

As the almost de facto standard way to run ci these days are containers, having one where to mount your code and run your linters seems more comfortable than going over the loop of pip installing dependencies.

To do pip efficiently you need to care about caches and run a hunk of commands that would be simplified by using an image with all the needed runtimes included.

**Comment by asottile** [comment]
I just don't see the value, it's simple enough to use `image: python:3.7` or whatever and then `pip install pre-commit && pre-commit run --all-files`

or even better, use something like tox: https://gitlab.com/pycqa/flake8/-/blob/8f9b4931b9a28896fb43edccb23016a7540f5b82/.gitlab-ci.yml#L61-64

I just don't see the value in providing an image that just has `pip install pre-commit` inside of it

and even if there is value there, how do you prevent the complexity from exploding? people will ask for different python versions, different tools installed, different programming languages installed, different base operating systems, different versions of pre-commit, different versions of `git`, etc. and maintaining a cross product of that _does not sound fun or productive_.

**Comment by ssbarnea** [comment]
I am happy to see that others see the a real use-case for having pre-baked images. At the same time I think that @asottile has valid reasons to worry regarding maintenance.

My plan was to build such an image on top of pre-commit when I would have found time. Maybe it would make sense to to have two different projects working in tandem, so pre-commit itself would not be poluted by the very-ambicious baking goal, but at the same time being aware of the other, and trying not to make break it.

Another thing that prevented me from going this path (other than time), was that at this time, there is no way to decouple hook version from its configuration. Configuration clearly needs to be in-repo, as you cannot bake it, but to pre-build it you need hook definitions (url+deps).

**Comment by asottile** [comment]
closing this out:
- this doesn't add much value over the current options
- doing this would involve a very very large maintenance project to support the combinatoric explosion of software / image choices
- even if we provided an image it doesn't help consumers much with efficiently caching the installed hooks -- you need more of a "recipe" than a base image for that

thanks again for the issue though!
