### ISSUE TITLE
Is there a way to force pre-commit on everything (not just what's been touched)?

### ISSUE THREAD

**Issue by jeking3** [pre-commit/pre-commit#1326]
I'd like to apply all the pre-commit checks to everything in a repository even if files haven't changed, but I haven't seen a way to force it to run on everything.  Hopefully this is already possible and I missed it in the documentation?  This would allow for a one-time alignment of everything when introducing pre-commit to an existing project, as opposed to doing it piecemeal as files are touched.

**Comment by asottile** [comment]
[`pre-commit run --all-files`](https://pre-commit.com/#4-optional-run-against-all-the-files)
