### ISSUE TITLE
Accidentally deleted .cache/pre-commit/repo... folders

### ISSUE THREAD

**Issue by HWiese1980** [pre-commit/pre-commit#1328]
Hi, I accidentally deleted the cache folders of pre-commit and now I'm facing the error message 

    .cache/pre-commit/repoxxxxxxxx/.pre-commit-hooks.yaml does not exist

Is there an easy way, a command or something, to rebuild the cache? 

Thank you!

**Comment by HWiese1980** [comment]
... and I figured it out myself. To document it for others who run into the same issue: 

    pre-commit clean

Seems to fix it. Afterwards, running pre-commit rebuilds the cache. Thanks anyway!

**Comment by flying-sheep** [comment]
I think it’s a reasonable assumption that the tool can cope with deleting an individual cache folder.

Maybe pre-commit should just rebuild a project’s cache when the whole folder is missing.

**Comment by asottile** [comment]
no means no
