### ISSUE TITLE
Output failures to a structured-data file for displaying nicely inside CI

### ISSUE THREAD

**Issue by petemounce** [pre-commit/pre-commit#1332]
I just discovered pre-commit and have now adopted it within a couple of days. It's great; thank you!

I (happen to) use BuildKite CI, which has quite a nice way of displaying result-summaries (https://github.com/bugcrowd/test-summary-buildkite-plugin#test-summary-buildkite-plugin). I run pre-commit inside CI with the same configuration as I'm getting people to, locally, so that we get the workstation runs but also require CI to pass.

This formatter works by accepting files in either 
* JUnit
* Checkstyle
* [Test Anything Protocol (TAP)](http://testanything.org/)
* plain-text-file-with-one-failure-per-line

... and then turns that into a pretty markdown/HTML report for rendering at the top of my CI pipelines. The point of this is to surface failures to people so they don't need to trawl through the usually-more-verbose build logs, saving them time.

Would it be a reasonable thing to ask for pre-commit to produce some test-output in one of those formats, for this and similar integrations?

I've seen the `log_file` option - I'm hoping that what I'm asking for can be a thing that pre-commit owns, since I think it's in the best position to make something consistent.

For example, the sort of data I'd want to see in the result breakdown would include:
* which hook
* which file
  * optionally, which line / column
* what the hook's executable decided to output, split by stdout and stderr
  * with the option to strip ANSI

I'm not so familiar with python, but I did find https://pypi.org/project/junit-xml/ and https://tappy.readthedocs.io/en/latest/ which sound like they might serve?

**Comment by asottile** [comment]
I kinda don't want to do this -- the output is already very slim (only containing the things you'd need and whatever the underlying tool presents) and it's easy to build whatever output you'd need from it via `log_file`

there's a duplicate somewhere that I closed with a similar sentiment but I can't find it anywhere :thinking: 

my main concern is the complexity of implementing something like this, as well as the slippery slope (as you've pointed out there's a bunch of different potential formats for this and surely if we add one someone will want another one)

I especially do not want to add a dependency just for this

**Comment by petemounce** [comment]
That's fair enough; I especially understand not wanting to take a dependency.

My perspective is that of a developer experience /engineering velocity person in a large team; taking on the feature and adding a single file-output option to your software's contract to complement the `log_file` option allows the avoidance of the greatest amount of work on the part of each of the plugin authors, I think.

As in, of there's an existing format out there that suitably captures the semantics of linting/formatting/testing I hope you might reconsider? In a world where that's supported it then becomes an easier proposition to transform that structure to another for an integrator, compared to the current landscape where it's a plugin by plugin proposition. That now becomes "merge the structured output (for which there's probably a library in your language) together and use it".

The semantics I'd been thinking of included
* Success with no problem / tests run and passed
* Success but problem found (no autofix)
* Success but problem found and fixed
* Failed to run
* Tests run successfully but some
  * Skipped
  * Warned (conftest can for example be set to warn instead of fail on a policy)
  * Failed
* Tests failed to all run
* Capture the detail output to the output

(I think that rules out TAP for example since that had no concept of "warn"; its spec allows directives for "skip" and "todo".)

**Comment by asottile** [comment]
if any solution involves parsing the output of individual tools that's not going to happen -- there's absolutely zero agreeance on the output structure of individual tools.  pre-commit simply runs the tools and produces their output and is none the wiser (it really can't differentiate between any of the bullet points you've posted above beyond "did it change files" and "did it exit nonzero")

the underlying tools are also extremely diverse, some being autofixers, some being test frameworks themselves, some being linting tools, I've even seen some that do none of these things and fire to slack or whatever -- I really don't think this mishmash fits well into any of the formats you've suggested above?

**Comment by petemounce** [comment]
I definitely hadn't intended that this be done by making a parser per-tool; sorry if I came across sounding like that. That sounds like it would be a maintenance nightmare because as you say, the tools vary widely and outside of `pre-commit`'s control.

I meant to suggest that if `pre-commit` advertised to plugin authors that "if you make file(s) contain output complying with xyz format, `pre-commit` understands that and can present it in a consistent way to the user and to CI".

I'd thought it to be completely up to plugin authors whether they wanted to implement their end of the contract.

**Comment by petemounce** [comment]
(Also - I see you work at Lyft; @DoomGerbil has been in touch I think around how we're doing macOS/iOS code-signing in buildkite CI. If that hasn't got through, check out https://github.com/improbable-eng/mac-codesign-buildkite-plugin.)

**Comment by asottile** [comment]
yeah I don't want to get into the business of parsing outputs at all -- that adds a whole level of complexity and error cases (what if a tool advertises incorrectly? what if the encoding of the tool output is unreliable? etc.) -- right now pre-commit doesn't even decode the output of tools, it just treats it as an opaque blob of bytes

**Comment by asottile** [comment]
unless there's something else to do here I'm going to close this out -- please comment back otherwise!  thanks again for the issue

**Comment by petemounce** [comment]
Say - a thing occurred to me.

Would it be acceptable for pre-commit to write a structured file containing just the information about the hooks that ran and their outcome? That would still be really valuable to me, since I could take that and place it in the buildkite annotation, making it more prominent.

Here, I'd been thinking `outcome` in terms of
* skipped
* passed
* failed - exit code non-zero
* failed - changed path(s)
* error running hook

if it's possible to slurp the changed path(s) into the output, that'd be great, since that's mainly what a person will be interested in

**Comment by asottile** [comment]
> Here, I'd been thinking outcome in terms of ...

you can get all this from the current output except changed paths

> if it's possible to slurp the changed path(s) into the output, that'd be great, since that's mainly what a person will be interested in

it's not possible to get changed paths, pre-commit doesn't even know that on a per-hook basis (diffs are treated opaquely)
