### ISSUE TITLE
Have lint-staged fail commit instead of "reverting to original state"

### ISSUE THREAD

**Issue by andersjr1984** [pre-commit/pre-commit#1335]
Working with lint-staged and husky, if the files I am attempting to commit have lint errors, it "reverts to original state" for these files, removing my changes. I would prefer it just fail my commit. Is there any option to stop the commit?

**Comment by asottile** [comment]
this isn't lint-staged, this is [`pre-commit`](https://pre-commit.com) -- fwiw `pre-commit` works the way you describe

**Comment by sibelius** [comment]
how to make this work well with husky?

**Comment by asottile** [comment]
this isn't husky, this is [pre-commit](https://pre-commit.com)
