### ISSUE TITLE
How to run pre-commit in a microservice-pattern application?

### ISSUE THREAD

**Issue by richardnguyen99** [pre-commit/pre-commit#1348]
I have an application structured like below:
```bash
docker-compose.yml
.pre-commit-config.yaml 
  └─ services/
    └─ backend/        # written in python
      └─.style.yapf
      └─.flake8
    └─ client/        # written in javascript
      └─.eslintrc
      └─.prettierrc
```

How can I setup `.pre-commit-config.yaml` to run all these formatter and linter with their configurations files correctly? Thank you.

**Comment by asottile** [comment]
I believe you mean "monorepo" -- there's a few duplicate issues which discuss some approaches: #1110 #1061 #466
