### ISSUE TITLE
cache + virtualenv>=20 / python_venv + moving executables -> File not found: ... python

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#1353]
failure mode looks something like this:

```
Check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

Executable `/Users/runner/.cache/pre-commit/repo14qw_y0i/py_env-python3.8/bin/python` not found
```

currently this is a common failure for github actions caches, there's ~2 ways to work around this:

1. [add `$(which python)`](https://github.com/pre-commit/action/commit/ee269b64a608de770696d23079f46238c2f7ab5a) to the pre-commit cache key
2. [manually bump](https://github.com/pypa/pip/pull/7750/files) the pre-commit cache key

but pre-commit should more gracefully detect this in the [`healthy()`](https://github.com/pre-commit/pre-commit/blob/0a8ba31b9b6656d90f94fc368b47acb502cea44d/pre_commit/languages/python.py#L160-L168) function (which is designed to catch these sorts of system breakages)

**Comment by duckinator** [comment]
@asottile for now, does it make sense for pip to just manually bump the pre-commit cache key again?

**Comment by asottile** [comment]
I would do (1) above

**Comment by pradyunsg** [comment]
@duckinator we'd likely want to do it in a separate PR.

**Comment by asottile** [comment]
pre-commit 2.2.0 contains a fix for this 🎉
