### ISSUE TITLE
`pre-commit autoupdate` should not change `rev` fields like `master` or `stable`

### ISSUE THREAD

**Issue by lucatrv** [pre-commit/pre-commit#1354]
I set most of my hooks' `rev` fields to `master`, or `stable` for `black`, see [instructions](https://github.com/psf/black#version-control-integration). If I run `pre-commit autoupdate`, all `rev` fields are set explicitly to the latest version number, and I need to revert all them back manually. `pre-commit autoupdate` should update only those `rev` fields that are set to an explicit version number.

**Comment by asottile** [comment]
[you should not do that -- it does not do what you expect](https://pre-commit.com/#using-the-latest-version-for-a-repository) -- [and will eventually produce an appropriate warning](https://github.com/pre-commit/pre-commit/issues/974)

**Comment by asottile** [comment]
black's directions are wrong and will be changed eventually: https://github.com/psf/black/issues/420

**Comment by lucatrv** [comment]
I'm ashamed I didn't notice that documentation section... But now my issue becomes that every time a hook is updated to a new version, the `.pre-commit-config.yaml` file is changed, and since I use [conventional commits](https://www.conventionalcommits.org/), every time I would need to create a new "build: [...]" commit.
What is the suggested solution to this?

**Comment by asottile** [comment]
what is the problem?

**Comment by lucatrv** [comment]
Well... to pollute my git history. Do you suggest to ignore the `.pre-commit-config.yaml` file or to check it in?

**Comment by asottile** [comment]
wait, what are you polluting?

**Comment by lucatrv** [comment]
I mean, I configured several hooks. Maybe every other day there could be an update, after a year I would have hundreds of "build: [...]" commit just for `.pre-commit-config.yaml`. I wanted to avoid that.

**Comment by asottile** [comment]
if you read the docs above, the goals are for _reproducibility_ and _repeatability_.  without checking in the file and picking consistent versions you really have no idea what versions you're running and no way to validate

in other words, the world you're describing your repository will (not can) break without changes to the code in the repository

updating the versions of linters is a conscious decision and has a commit associated with it (instead of mysteriously broken builds due to some upstream changing)

you don't have to do it every day unless you want to (but then that would be your decision) -- the stability without updating is very good

I'd encourage you to read up on why repeatability is a desirable quality in software :)

**Comment by lucatrv** [comment]
I agree that _reproducibility_ and _repeatability_ is a very important concept when considering dependencies and build tools configuration, but (at least in my case) I'm using `pre-commit` for linting code, in case a linter is updated maybe I would get some new or different lint message, or even an error when committing, but my code would not really _break_. Or am I mistaken?

**Comment by asottile** [comment]
presumably your build is broken if your linters aren't passing

but also code formatters

**Comment by lucatrv** [comment]
OK, I found this solution: I installed all required packages locally, and configured all hook `repo`s as `local`, using the specific hook configuration for each package. For instance for `black` now I have:

```yaml
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]
```

Now all packages are managed outside `pre-commit`, so the `.pre-commit-config.yaml` does not change anymore.

Are there any drawbacks with this solution?

**Comment by asottile** [comment]
yes that has exactly the same problems, except now you're using the less supported escape hatch

**Comment by asottile** [comment]
plus your contributors need to install things manually instead of having it automatically managed

**Comment by lucatrv** [comment]
I also added all required packages to my `setup.py` file:

```python
setup({
    extras_require={
        'dev': [
            'pip-commit-hooks',
            'isort',
            'black',
            'flake8',
            'pylint',
            ...
        ]
    }
})
```

**Comment by asottile** [comment]
yeah, kind of the whole point of pre-commit is that it manages the installs for you so you don't have some bespoke setup for contributors to try and learn

**Comment by lucatrv** [comment]
OK, you convinced me, thanks.
