### ISSUE TITLE
changing hooks working dir

### ISSUE THREAD

**Issue by lewisacidic** [pre-commit/pre-commit#1356]
Is there a way to change the working directory hooks run in? 

My use case is I have a multilanguage monorepo project like:

```
.
├── README.md
├── .precommit-config.yaml
├── r
    └── ...
├── js
    └── ...
└── py
    ├── mypy.ini
    ├── pyproject.toml
    ├── pytest.ini
    ├── setup.cfg
    ├── setup.py
    └── src
        └── proj
            ├── __init__.py
            └── mod.py
```

Mypy, black and flake8 don't pick up the config as they are being executed below the config files.  I could move the mypy.ini and setup.cfg files to the project base, but that's not ideal. any ideas?

**Comment by asottile** [comment]
there's a few other issues which discuss this with workarounds: https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+monorepo+is%3Aclosed
