### ISSUE TITLE
Add option to exclude the .pre-commit-config.yaml file from git locally only

### ISSUE THREAD

**Issue by it-praktyk** [pre-commit/pre-commit#1357]
I would like to see an option (an argument) in the pre-commit to easily exclude the file `.pre-commit-config.yaml` from being included to the git repository but not including it the `.gitignore` file.

It can be done by
- add the `.pre-commit-config.yaml` to the `.git/info/exclude` file
- set the `core.excludesFile` for the local copy of a repository

Does it corresponds to https://github.com/pre-commit/pre-commit/issues/157 ?

**Comment by asottile** [comment]
it's designed to be checked in but pre-commit also doesn't care if you don't check it in -- no such option is necessary this is already how it is
