### ISSUE TITLE
Rename the `.cache` folder on Windows 

### ISSUE THREAD

**Issue by lucatrv** [pre-commit/pre-commit#1360]
On Linux the `~/.cache` folder is is part of the [Freedesktop Basedir specifications](https://www.freedesktop.org/wiki/Specifications/basedir-spec/), and therefore it is normally present and known. On Windows this is not the case, and normally there is no `.cache` under `%USERPROFILE%`. As a consequence, normally there is only the `pre-commit` folder within `%USERPROFILE%\.cache`.

To make it more recognizable, I suggest to save the `pre-commit` cache directly in a folder named `%USERPROFILE%\.pre-commit` (notice the leading dot). Most Python packages follow this convention, so under `%USERPROFILE%` there are folders like `.ipython`, `.jupyter`, `.matplotlib`, etc.

**Comment by asottile** [comment]
is something actually broken or is this a vanity request?  if nothings broken I'm not adding complexity for this

**Comment by lucatrv** [comment]
I made it clear from the title

**Comment by asottile** [comment]
just for your information the actual convention on windows is `%USERPROFILE%\AppData\Local\{author}\{application_name}\Cache\...` -- ipython / matplotlib / jupyter don't follow it (and don't follow XDG on linux platforms either)

**Comment by lucatrv** [comment]
I agree, however having a `.cache` folder on Windows under `%USERPROFILE%` where there should not be does not tell anything to the user, while `.pre-commit` would be recognizable, also considering that it can easily reach hundreds of MB.
The added complexity should be about a couple of lines, I could issue a PR if useful.
This is just a suggestion though.

**Comment by asottile** [comment]
not happening, and especially not to an equally-wrong thing -- sorry

**Comment by lucatrv** [comment]
OK, that was just a suggestion, thanks anyway.
