### ISSUE TITLE
Feature request: add parameter to delete cached repos unused in the last X days

### ISSUE THREAD

**Issue by lucatrv** [pre-commit/pre-commit#1361]
At present the `pre-commit` cache can grow indefinitely unless the user remembers to issue now and then the `pre-commit gc` or `pre-commit clean` commands. This can be a problem in particular for contributors to projects who do not run themselves the `pre-commit autoupdate` command, but nevertheless receive updates from the upstream `.pre-commit-config.yaml` file.
I suggest to add a [`.pre-commit-config.yaml` top level paramenter](https://pre-commit.com/#pre-commit-configyaml---top-level) to specify that, at each run, cached repos that have not been used in the last X days should be cleaned. This parameter could be named for instance `clean_unused_cached_repos`.

**Comment by asottile** [comment]
you're looking for [`pre-commit gc`](https://pre-commit.com/#pre-commit-gc)

**Comment by lucatrv** [comment]
If I am not mistaken, `pre-commit gc` cleans all older repos which are not used by the current project. If I work on two projects which require two different versions of the same hook, it would keep deleting the older repo every time the new one is installed, when switching from one project to the other one. This request is for a command to delete repos which have not been accessed in the last X days.
Moreover there should be a way to run this automatically at each `pre-commit` run.

**Comment by asottile** [comment]
nah try it -- it only deletes non-referenced repositories on your system

**Comment by asottile** [comment]
deleting cache is incredibly slow and requires a global write lock, you absolutely do not want to run this on every run

**Comment by asottile** [comment]
please trust me on this one, I've put a lot of thought into `pre-commit gc` and it is _the way_ and I'm not making another way to do the same thing but worse :)

**Comment by lucatrv** [comment]
OK, I tried it and in fact it does not clean repos unnecessarily. I guess it works verifying that the projects that once required a certain version still exist, and still require that version. Smart!

Sorry for my wrong assumption.

However I still think that there should be a way to run it automatically, what would you think about a parameter to specify every how many days it should be run? I see the problem of the cache folder growing indefinitely for users that do not know about `pre-commit gc` but just contribute to my projects.

**Comment by asottile** [comment]
it's 2020, disk is cheap, and `cron` exists if you really need it

**Comment by lucatrv** [comment]
So why you added `pre-commit clean`? I can use `rm`.

**Comment by asottile** [comment]
the cache is private implementation detail, the command allows me to change how it works and where it lives without retraining (for example, it has gone through several complete rehauls and moved once)

**Comment by lucatrv** [comment]
I still think that an option to run `pre-commit gc` every X days would be very useful, in particular for contributors to other projects who just follow the instructions to run `pre-commit install` without actually managing it. However the decision is yours of course.

**Comment by asottile** [comment]
stop please
