### ISSUE TITLE
Provide guidance or helper function to recover stashed code after user interruption of git commit

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1362]
I ran git commit and did not stage all files that were modified in the repo, so pre-commit stashed them to my systems pre-commit cache in `$HOME/pre-commit` for later restore. I then interrupted (my bad) the process and now I wonder how I can `git stash apply ...` and / or where I have to put the file `patch49209` that is now in the cache back in `.git/` without breaking my git repo. I know it's more a git than a pre-commit issue but I think it would be appropriate to provide guidance in the documentation and / or a helper function in pre-commit to get out of such a situation smoothly (if possible) because it is much more likely to occur when using pre-commit and there are checks that are non-instantaneous (because the user then has more time to make a mistake :smile:).

I quickly googled and [it does not seem very straight-forward](https://stackoverflow.com/questions/40653560/where-are-git-stashes-stored). I think this can really cause a big headache otherwise, especially for non-git experts.

**Comment by asottile** [comment]
it's supposed to auto-restore the patch -- can you provide a reproduction where it doesn't?

worst case you can `git apply path/to/the/patch` (that's why it prints it)

**Comment by asottile** [comment]
for example:

```console
$ git commit -m "test"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.cache/pre-commit/patch1584026177.
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check docstring is first.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
Fix double quoted strings................................................Passed
flake8...................................................................^C
[INFO] Restored changes from /home/asottile/.cache/pre-commit/patch1584026177.
Interrupted (^C): KeyboardInterrupt: 
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```

see the

```
[INFO] Restored changes from /home/asottile/.cache/pre-commit/patch1584026177.
```

**Comment by lorenzwalthert** [comment]
Thanks @asottile. Well I used RStudio which has a git GUI and then I hit abort, so the window with the log closed and I did not see
```
^C
[INFO] Restored changes from /home/asottile/.cache/pre-commit/patch1584026177.
Interrupted (^C): KeyboardInterrupt: 
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```

The fact that I did not use git from the command line might be also the reason why the patch was not auto restored. I think it would be nice if we could make RStudio applying the patch anyways, but I think that's more on their side and I have no idea how to approach this problem. I could open up an issue there if you don't know a quick fix. Just seems hitting abort in the git tab of RStudio is not equivalent to hit ^C on the command line. Did people using other git GUIs report similar problems in the past?

**Comment by asottile** [comment]
nope! this is the first I've heard of such -- I wonder if they're sending a more powerful signal like KILL?

**Comment by lorenzwalthert** [comment]
> "it does not seem very straight-forward"
`git apply path/to/the/patch`

Ups, thanks for that one.😄 

KILL instead of INT: Possibly, I don't know. I guess I had to open an issue in rstudio/rstudio.

**Comment by lorenzwalthert** [comment]
I tried to describe the problem and our suspicion in https://github.com/rstudio/rstudio/issues/6471.

**Comment by asottile** [comment]
sounds good 👍 let me know if there's anything I can help with!  the description in that issue sounds good

**Comment by kumarappan-arumugam** [comment]
@asottile Is there a way to configure pre-comnmit to use a different cache folder for stashing? For ex if you run pre-commit from docker the stashed code is lost.

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /root/.cache/pre-commit/patch1639811512-8.
Check docstring is first.............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Detect AWS Credentials...................................................Passed
Trim Trailing Whitespace.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Fix python encoding pragma...........................(no files to check)Skipped
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check for merge conflicts................................................Passed
Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

.pre-commit-config.yaml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x .pre-commit-config.yaml
  If it is supposed to be executable, double-check its shebang.
docker/pre-commit/Dockerfile: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x docker/pre-commit/Dockerfile
  If it is supposed to be executable, double-check its shebang.

[INFO] Restored changes from /root/.cache/pre-commit/patch1639811512-8.
```
