### ISSUE TITLE
Excluding a template directory does not work

### ISSUE THREAD

**Issue by tumblago** [pre-commit/pre-commit#1365]
Hello!

  I have a seemingly stupid problem. We have a cookiecutter templates directory which we'd like to skip the pre-commit hooks for (since from the POV of the linters we use, cookiecutter syntax is malformed).
  
   For instance, we'd like to format all terraform files, but exclude those in the `templates` directory. If I add in `files: \.tf$ exclude: '^templates/'` everything seems to work fine when I modify a template, but as soon as any other `.tf` file is modified, the pre-commit hook seems to execute against the `templates` directory as well. I've tried so many things at this point - (negative) look aheads, behinds, but nothing seems to be able to change this behavior. Is this a bug or am I doing something very wrong?

**Comment by asottile** [comment]
that looks correct -- what is the rest of your configuration?

or is this closed because you figured it out?

**Comment by tumblago** [comment]
The problem wasn't with pre-commit, I'm sorry for prematurely posting here. The problem was that `terraform fmt` does its own searching for files independently of what `pre-commit` identifies as the scope.
