### ISSUE TITLE
Is it possible to run outside a GIT repo

### ISSUE THREAD

**Issue by tolomea** [pre-commit/pre-commit#1366]
I'm using AWS codebuild, I want to run `pre-commit run --all-files` in the build stage to run my precommit tests, however when I do I get:
```
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```
Which I presume is because codebuild is only checking out the files, not cloning the git repo.

Is there a way to run pre-commit without the .git directory.

**Comment by asottile** [comment]
like the error message says, you need a git repository

you can always make one and add all the files `git init . && git add .`
