### ISSUE TITLE
2.2.0: tests missing in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [pre-commit/pre-commit#1367]
Hi! I'm packaging python-pre-commit for Arch Linux.
We're usually using the pypi sdist tarballs as they provide more unique naming schemes.
However, the tests directory is missing from the sdist tarball. For people building from source it's always good to be able to run tests against their environment to ensure compatibility.

It would be great if the tests directory could be added in the upcoming release!

As a side note: Somehow the tarballs on pypi are named [pre_commit](https://pypi.org/project/pre-commit/#files), but the project is called [pre-commit](https://pypi.org/project/pre-commit/). It would be nice to have a more consistent naming scheme.

**Comment by asottile** [comment]
yeah, intentionally not included -- if you need a tgz with the tests use the github tgz

**Comment by dvzrv** [comment]
Hm, okay. What is the purpose of providing sdist tarballs then though?

**Comment by asottile** [comment]
if one is using `pip install --no-binary :all:` there will be source packages -- there are also some sites which do not trust the wheel packages and would rather build them from source inside their infrastructure

in reality, almost nobody uses the source distributions on pypi and that's fine

**Comment by dvzrv** [comment]
I guess distributions are in that situation though.

And I can't agree with:

> in reality, almost nobody uses the source distributions on pypi and that's fine

On Arch it's [at least around 600 packages](https://pkgbuild.vdwaa.nl/?q=files.pythonhosted.org&i=nope&files=&repos=) using pypi.org. By proxy every Arch user installing that package uses the source distribution and entrusts us to run tests and fix potential integrational issues.
I don't have numbers for Debian or Red Hat based distros, but they also mainly use pypi.org to my knowledge.
