### ISSUE TITLE
Unable to enforce default_language_version to enforce python_venv

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1370]
I tried to use the documented `default_language_version` override feature in order to enforce use of `python3 + venv` for creation of all virtualenvs but apparently this does not work as one would expect.
```
default_language_version:
  # avoid use of virtualenv which recently become unstable
  python: python_venv
```
https://github.com/pre-commit/pre-commit/search?q=python_venv&unscoped_q=python_venv

Is there a way to enforce this without having to touch each hook? In some repositories there lots of hooks defined.

**Comment by asottile** [comment]
`default_language_version` is for overriding `language_version`, not `language` so I'm not sure why you expected that :)

if you're worried about the stability of virtualenv 20.x I'd suggest `virtualenv<20` in your requirements -- that said, virtualenv 20.x has a setting to *use venv*, so that's probably a better option

**Comment by asottile** [comment]
note also, `language: python_venv` will be going away soon/eventually as virtualenv is now making venv-style environments

**Comment by ssbarnea** [comment]
So basically, by capping virtualenv version when I install, pre-commit I avoid being affected by this issue. Thanks, lucky me I am using tox, so very easy.

**Comment by asottile** [comment]
the other way, use of `virtualenv` would return to the only way now that it creates environments identical to `venv`

**Comment by gaborbernat** [comment]
That error makes no sense if you're actually using virtualenv 20.0.10 🤔
