### ISSUE TITLE
Option to separate hook arguments from hook file list with '--'

### ISSUE THREAD

**Issue by davidpfarrell** [pre-commit/pre-commit#1372]
## Situation

[My Hooks](https://github.com/TekWizely/pre-commit-golang) are scripts that wrap various golang lint commands, invoking commands for each input file, individually.

My challenge was that I wanted to enable the user to pass options into the golang tool, but I didn't want my wrapper script to have to be aware of all the tool's options.

## Attempted Solution # 1

My first incarnation was simple enough, I simply *required* the user to terminate their arguments list with a `'--'`, ie:
```
args: [arg1, arg2, ..., '--']
```

This always felt clunky and I was concerned users would either forget to add it or simply not read the instructions.  Indeed one of the very first users of my hooks contacted me with an issue passing arguments (doh!)

I was able to quickly inform them on how to get past their issue, and they were happy.

But it got me wondering if I might be able to add some intelligence to minimize the cases where the `'--'` was required.

## Attempted Solution # 2
I came up with a semi-interesting pattern:  

* Any Argument That Doesn't Reference a Filesystem File Is Likely An Option
```
OPTIONS=()
# If arg doesn't pass [ -f ] check, then it is assumed to be an option
#
while [ $# -gt 0 ] && [ "$1" != "-" ] && [ "$1" != "--" ] && [ ! -f "$1" ]; do
	OPTIONS+=("$1")
	shift
done

FILES=()
# Assume start of file list (may still be options)
#
while [ $# -gt 0 ] && [ "$1" != "-" ] && [ "$1" != "--" ]; do
	FILES+=("$1")
	shift
done

# If '--' next, then files = options
#
if [ $# -gt 0 ]; then
	if [ "$1" == "-" ] || [ "$1" == "--" ]; then
		shift
		# Append to previous options
		#
		OPTIONS=("${OPTIONS[@]}" "${FILES[@]}")
		FILES=()
	fi
fi

# Any remaining arguments are assumed to be files
#
while [ $# -gt 0 ]; do
	FILES+=("$1")
	shift

# From this point on, OPTIONS = the tool options, and FILES = pre-commit file list
```

With this, the `'--'` is only required if your options contain a reference to an existing file on the file system.

This all-but-completely eliminates the need for the user to add `'--'`, but it is a bit of a hack.

## Feature Request

I'd like to discuss the possibility of adding a configuration flag that would have pre-commit add a `'--'` between the user-provided arguments and the file list, making it easier for hooks to process hook options.

This would be a configuration in hook's`.pre-commit-hooks.yaml` telling pre-commit how to communicate to the configured hook.

## Why '--'

According to [The Open Group Utility Syntax Guidelines](https://pubs.opengroup.org/onlinepubs/7908799/xbd/utilconv.html):

> Guideline 10:
> The argument -- should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the "-" character.
> ...

## Why I'm Asking Now

I recently had the idea to make a blog post on my current technique in case others might find it useful.

It then occurred to me that it might be *even more* useful to spend some of that energy discussing the issue here and see if we could avoid the work-around altogether.

## Conclusion

Thank you for time, I look forward to discussing the matter further.

-DF

**Comment by davidpfarrell** [comment]
@asottile  Apologies for creating the ticket in wrong repo and thanks for moving it !

> but I don't think a feature is necessary -- options should always start with - or -- (or / if you're using windows conventions). the options should have known number of arguments afterwards (0 for flags, 1 for key-value options). and then everything that is not an option is a file

Remember in my post I say that my hook script invokes another command and I don't want to have to encode ALL of that commands' arguments in my script ... So the script is blind as to `"known number of arguments afterward"`

> plus, option 1 already works (and this case is very far from the normal case)

Related to the first comment, this doesn't work in the case where the option takes an argument in the form of `--option option-value` (i.e space-separation between the option and the option value)

So I am specifically asking for this feature so I can support space-separated options and option-values in a script that cannot otherwise be aware of when options stop and files begin.

Thanks again for the assist and for getting the conversation started.  I look forward to further discussion on the matter.

-DF

**Comment by asottile** [comment]
why can't you do something like (it's python but you could easily port the same logic to some other language):

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--flag-type', action='store_true')
parser.add_argument('--option-type')
args, rest = parser.parse_known_arguments()

# args is now *our* arguments, and rest is the things that we don't know about
```

**Comment by davidpfarrell** [comment]
Thanks for the follow up, but I think I'm failing to communicate my use case.
In my case there are NO `"our"` arguments - Any user-provided arguments will be passed into the command that the hook script is proxying, and I wont' know (don't want to know) *what* options are available to the user when invoking the proxied command.

Here's another take at it showing it.

_.pre-commit-config.yaml_
```
hooks:
    -   id: myhook
        args: ['--config-file',  '/etc/my_config_file.cfg']
```

User modifies 3 files on the system and needs the hook to run against them:
* `path1/file1`
* `path2/file2`
* `path3/file3`

Pre-commit will invoke my hook:
```
myhook.sh --config-file /etc/my_config_file.cfg path1/file1 path2/file2 path3/file3
```

_myhook.sh_
```
#!/usr/bin/env bash
# My hook is a proxy for /usr/bin/some_cool_tool
#
# some_cool_tool accepts 25+ options to configure its behavior
# I do not want to have to duplicate those options in this hook script
#
# I need to invoke some_cool_tool for each modified file, individually
# Passing the user-provided options to each invocation
#
# Instead of using the exact filename as the argument to some_cool_tool
# I will be using some derived value that is computed by this hook script
#
# For this example:
# I will use the file's parent folder as the argument to some_cool_tool
...
```

So when myhook runs, it will need to execute the following commands:
* `/usr/bin/some_cool_tool --config-file /etc/my_config_file.cfg path1`
* `/usr/bin/some_cool_tool --config-file /etc/my_config_file.cfg path2`
* `/usr/bin/some_cool_tool --config-file /etc/my_config_file.cfg path3`

My issue is, with the current way that arguments and files are passed, my hook script can't know where the input arguments stop and the pre-commit file list starts.

And remember, I'm not asking to change the default behavior, just for a hook configuration option that will include `'--'` as a separator between the args and files, and that doing so is actually a rather standard unix convention.

Hopefully this example communicates my use case more clearly - Please let know you still have any questions that I can try to clarify.

Thank you,
-DF

**Comment by asottile** [comment]
imo `some_cool_tool` is broken in this case, it should be able to accept `/usr/bin/some_cool_tool --config-file /etc/my_config_file.cfg path1 path2 path3`

**Comment by davidpfarrell** [comment]
> imo some_cool_tool is broken in this case, it should be able to accept /usr/bin/some_cool_tool --config-file /etc/my_config_file.cfg path1 path2 path3

But *how* would my script compute `path1 path2 path3` ? Again my script needs to know where the files start so I can munge them into tool arguments .... And I'd rather not have to code ALL of cool_tool's arguments into my script ...

**Comment by asottile** [comment]
why can't it just pass them along, what sort of munging are you doing?

**Comment by davidpfarrell** [comment]
> why can't it just pass them along, what sort of munging are you doing?

Per the example, pre-commit passes files into the hook and the hook passes parent folders into the tool.

So for this example, the "munging" is computing the parent folder of each input file.

**Comment by asottile** [comment]
ok I understand now -- you're wrapping a tool which has super non-standard calling conventions (arguably a design flaw in that tool, but I assume you can't fix that thing)

I think your current working solution of `args: [--]` is what you should go with and I don't think there's a need to grow such an option in pre-commit itself.  it's exceedingly rare to need such a thing (I haven't heard of a use case similar to this).  I'd suggest documenting this oddity in your specific hook and making the error message loud when that `--` argument is missing such that you can't accidentally have an incorrect configuration.  it should be straightforward for you to look for `--` in argv and produce an error if it is missing (as well as setting a default `args: [--]`).

pre-commit will always pass `args` and then files so you can depend on that being ordered properly

**Comment by davidpfarrell** [comment]
> a tool which has super non-standard calling conventions

Just to be clear, the tool *does not* have non-standard calling conventions.  I just want to munge the file list into arguments for the tool and also would like to exert control over how often the tool is invoked (ie. maybe multiple files with the same parent folder are on the file list so I only want to invoke the tool once for that parent folder since its an expensive call or would produce duplicate error messages)

I don't see a request for an *explicit* separation between options and files as too much of an ask.

Just the same, I won't push the argument any further.  

Thank you for your time,

-DF

**Comment by asottile** [comment]
currently pre-commit does _no_ processing of arguments and I don't really want to change that unless there's a very strong use case for it -- in open source "no" is temporary but "yes" is forever

thanks for understanding
