### ISSUE TITLE
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'

### ISSUE THREAD

**Issue by benjeffery** [pre-commit/pre-commit#1375]
Over at https://github.com/tskit-dev/tskit/issues/498 a user has reported this error:

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/peter/.cache/pre-commit/repoeh3i9c_u/py_env-python3.6', '-p', 'python3.6')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
```
Is this related to https://github.com/pypa/virtualenv/issues/1515 ?

**Comment by benjeffery** [comment]
Config at https://github.com/tskit-dev/tskit/blob/master/.pre-commit-config.yaml
Version 2.2.0

Seems adding `language_version: python3.7` to the black config fixed this, as they didn't have python 3.6 on their system, but might that break people who have 3.6 only?

**Comment by asottile** [comment]
this probably means they don't have python3.6 -- probably best to do `language_version: python3` and then that should work for most that have a modern-enough python

**Comment by benjeffery** [comment]
Brill - thanks for that!

**Comment by asottile** [comment]
@gaborbernat -- just a data point, I think the old error message was easier to understand here:

```
$ virtualenv -p python3.6 vvv
The path python3.6 (from --python=python3.6) does not exist
```

vs

```
$ virtualenv -p python3.6 vvv
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
```

**Comment by gaborbernat** [comment]
Well, in theory it's more accurate to say could not be found opposed to does not exists; because the executable might still be available on the machine, we could just not discover it because e.g. it's no on the PATH.

**Comment by asottile** [comment]
yeah, perhaps just some wording can be rearranged, maybe something like this?

```
`python3.6` (from --python=python3.6) was not found while attempting Builtin discovery.
```

**Comment by guilleijo** [comment]
For anyone having this problem I fixed it by adding the following in the `pre-commit-config.yml`:
```
default_language_version:
    python: python3
```
You can use a more specific version, in my case im using `python: python3.7`.

**Comment by khoulouda1996** [comment]
hello, I'm using Windows and I've used virtualenv -p $env:python3 env
However, I got this error ```RuntimeError: failed to find interpreter for Builtin discover of python_spec='$env:python3'```

**Comment by asottile** [comment]
@khoulouda1996 sorry, that has nothing to do with this project -- you want [pypa/virtualenv](https://github.com/pypa/virtualenv)
