### ISSUE TITLE
No colors when hooks are run by a git commit

### ISSUE THREAD

**Issue by Cielquan** [pre-commit/pre-commit#1381]
Hi,
I use pre-commit at home on linux which works perfect. But at work I have a windows pc. Here I have problems with the colorfull output. 

When the hooks are run by `tox` calling `pre-commit run` there are colors as usual. When the hooks are run by a `git commit` the colors are missing.

Concrete I mean the green for 'Passed', red for 'Failed ' and yellow/brown for 'Skipped' in the overview.

There is no difference if I run it via git-bash, cmd or powershell. Also there is no difference if I use the pycharm buildin terminal or others.

**Comment by asottile** [comment]
colors on windows are a bit fiddly and unfortunately there isn't much we can do to change them when run from `git` -- we try and call `SetConsoleMode` [here](https://github.com/pre-commit/pre-commit/blob/34e9d117861ba758b3fd2d0b33eb70de9f05238d/pre_commit/color.py#L45) but if that fails you don't get colors

**Comment by Cielquan** [comment]
Ok thanks for the fast answer. 
Then I have to live with it :(

**Comment by asottile** [comment]
actually hmm, on windows `sys.stdout.isatty()` is false, but `sys.stderr.isatty()` is true -- which is different than linux, maybe if we use stderr instead of stdout?

**Comment by Cielquan** [comment]
When I run `sys.std---.isatty()` on my windows maschine both are `false` when run from pycharm python console. But both are `true` when run from the terminal regardless if via invoking a python console first or by running `python -c`.

**Comment by asottile** [comment]
can you try the patch in #1382?

**Comment by Cielquan** [comment]
Sure let me try .. may take a bit.

**Comment by Cielquan** [comment]
It does work 👍
