### ISSUE TITLE
language_version with non-strict values

### ISSUE THREAD

**Issue by chrishna1** [pre-commit/pre-commit#1384]
Hi, thanks for this awesome framework. This is not an issue exactly. I want to ask if there is some ways to use `language_version` as

`language_version: 2.1.5+`

that would mean that allow version higher than 2.1.5+. If this feature sounds useful then I can contribute on this.

**Comment by asottile** [comment]
it unfortunately depends on the underlying tool supporting it (there isn't really anything `pre-commit` can do to help this) and I don't think any of the underlying `language_version`-supporting tools currently handle that (python: virtualenv, node: nodeenv, ruby: rbenv/ruby-build/ruby-download)
