### ISSUE TITLE
Bug: Cannot use pre-commit with language "node"

### ISSUE THREAD

**Issue by daniel-wtd** [pre-commit/pre-commit#1385]
Hi,

thank you a lot for maintaining and developing pre-commit.

Recently I was using more hooks during my work and am running into issues with the following setup.

```
python3 -m venv .venv_python
source .venv_python/bin/activate
pip install pre-commit
cd /my/work/dir/
pre-commit install
```

the pre-commit-config.yaml looks like:
```
repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v2.3.0"
  hooks:
    - id: "check-yaml"
    - id: "end-of-file-fixer"
    - id: "trailing-whitespace"

- repo: "https://github.com/pre-commit/mirrors-csslint"
  rev: "v1.0.5"
  hooks:
    - id: "csslint"
```

The official hooks are working fine (check-yaml, eof, etc.).
Hooks, which are using `language: node` are failing during `pre-commit install` with the error below:

```
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-csslint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-csslint:csslint@1.0.5.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-csslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...




An unexpected error has occurred: CalledProcessError: command: ('/home/dschier/.venv-python3/bin/python3', '-mnodeenv', '--prebuilt', '--clean-src', '/home/dschier/.cache/pre-commit/repok0rsxt76/node_env-default')
return code: 1
expected return code: 0
stdout: (none)
stderr:
     * Install prebuilt node (13.12.0) .
    Traceback (most recent call last):
      File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/dschier/.venv-python3/lib64/python3.7/site-packages/nodeenv.py", line 1517, in <module>
        main()
      File "/home/dschier/.venv-python3/lib64/python3.7/site-packages/nodeenv.py", line 1113, in main
        create_environment(env_dir, opt)
      File "/home/dschier/.venv-python3/lib64/python3.7/site-packages/nodeenv.py", line 936, in create_environment
        install_node(env_dir, src_dir, opt)
      File "/home/dschier/.venv-python3/lib64/python3.7/site-packages/nodeenv.py", line 700, in install_node
        install_node_wrapped(env_dir, src_dir, opt)
      File "/home/dschier/.venv-python3/lib64/python3.7/site-packages/nodeenv.py", line 723, in install_node_wrapped
        download_node_src(node_url, src_dir, opt, prefix)
      File "/home/dschier/.venv-python3/lib64/python3.7/site-packages/nodeenv.py", line 552, in download_node_src
        dl_contents = io.BytesIO(urlopen(node_url).read())
      File "/usr/lib64/python3.7/http/client.py", line 470, in read
        s = self._safe_read(self.length)
      File "/usr/lib64/python3.7/http/client.py", line 622, in _safe_read
        raise IncompleteRead(b''.join(s), amt)
    http.client.IncompleteRead: IncompleteRead(27623177 bytes read, 5720155 more expected)
    
Check the log at /home/dschier/.cache/pre-commit/pre-commit.log
```

nodeenv is installed in the venv:
```
nodeenv (1.3.5)  - Node.js virtual environment builder
  INSTALLED: 1.3.5 (latest)
```

Would be awesome, if you can suggest whats going wrong here. The issue appears in Ubuntu 18.04 and Fedora31.

Best regards,
Daniel

**Comment by asottile** [comment]
IncompleteRead means your network connection cut out while downloading -- perhaps try again?

**Comment by RazerM** [comment]
See https://github.com/ekalinin/nodeenv/issues/253

**Comment by asottile** [comment]
This happens when nodejs.org has a blip or the local network has a blip -- I don't think there's anything fixable here

I also can no longer reproduce the error above, I was able to successfully install csslint and run it

let's continue the discussion in `nodeenv` (if at all)

**Comment by asottile** [comment]
you _may_ be able to work around the downloading by using `language_version: system` (assuming you have `node` installed on your system already)

**Comment by yhoiseth** [comment]
> This happens when nodejs.org has a blip or the local network has a blip -- I don't think there's anything fixable here

Could it be an alternative to show an error message with the URL of the service that doesn't work? I think that would make the error easier to troubleshoot.

**Comment by asottile** [comment]
> > This happens when nodejs.org has a blip or the local network has a blip -- I don't think there's anything fixable here
> 
> Could it be an alternative to show an error message with the URL of the service that doesn't work? I think that would make the error easier to troubleshoot.

that would be an improvement request for `nodeenv` and not pre-commit -- pre-commit knows nothing about the internals of `nodeenv` and simply calls it as an executable:

```
An unexpected error has occurred: CalledProcessError: command: ('/home/dschier/.venv-python3/bin/python3', '-mnodeenv', '--prebuilt', '--clean-src', '/home/dschier/.cache/pre-commit/repok0rsxt76/node_env-default')
```

(the inner stacktrace comes from `nodeenv` itself)

**Comment by daniel-wtd** [comment]
Thanks a lot everybody. I will check this and open an issue for nodeenv, if reproducible.

**Comment by asottile** [comment]
@daniel-wtd there is one here: https://github.com/pre-commit/pre-commit/issues/1385#issuecomment-609916331

it's flakey for me fwiw -- but yeah due to networking on nodejs.org afaict
