### ISSUE TITLE
Pipe filenames to "entry" instead of passing as args

### ISSUE THREAD

**Issue by olirice** [pre-commit/pre-commit#1389]
I'm attempting to create a pre-commit hook for a cli that expects its inputs to be piped in rather than accepting a list of files.

Here's the setup:
```
# https://github.com/olirice/flupy/blob/master/.pre-commit-hooks.yaml
-   id: flupy
    name: flupy
    entry: flu
    language: python
    'types': [python]
    args: []
    require_serial: false
    additional_dependencies: []
```

As expected, that results in the command executing as:
```shell
flu file1.py file2.py
```
Which raises an error with that cli.

Is there a way to manipulate the `entry` hook such that `flu` would be invoked as
```shell
echo "file1.py file2.py" | flu
```
while any user specified args would still follow the `flu` command? 

Thanks for this project, I use it everywhere!

**Comment by asottile** [comment]
most of that configuration is unnecessary for what it's worth, you can unquote `types` and remove args / requires_serial / additional_dependencies

pre-commit only supports calling as positional arguments as that's how it can best parallelize

you can use a less-portable workaround using bash:

```yaml
    entry: bash -c 'echo "$@" | ...' --
```
