### ISSUE TITLE
pre-commit hangs in Centos 8

### ISSUE THREAD

**Issue by innerout** [pre-commit/pre-commit#1390]
Hello I have been using pre-commit for some time now and worked flawlessly in Centos 7.
One of the servers I am working was upgraded recently to Centos 8 and while pre-commit installs successfully and `pre-commit --version` runs. 
When I try to run pre-commit install in a repo it hangs forever. I have tried deleting
`~/.cache/pre-commit` but it does not seem to have any difference.

**Comment by asottile** [comment]
you'll need to show more information like:

- what version you're using
- what your configuration is
- what command you're running
- what your output is

**Comment by innerout** [comment]
`pre-commit --version` 2.2.0
`python3 --version`  3.6.8
The command I am running is `pre-commit install` and the output is blank.

**Comment by asottile** [comment]
what about your `git` version, and could you `ls -al .git/hooks`

maybe also `strace pre-commit install` would be helpful (probably long output, can attach it as a file)

**Comment by innerout** [comment]
`git --version` 2.18.2
[hooks.txt](https://github.com/pre-commit/pre-commit/files/4458347/hooks.txt)
[strace.txt](https://github.com/pre-commit/pre-commit/files/4458369/strace.txt)

**Comment by innerout** [comment]
Sorry this is the correct `ls -al` output.
[hooks.txt](https://github.com/pre-commit/pre-commit/files/4458379/hooks.txt)

**Comment by asottile** [comment]
interesting, the last bit of this seems to be an access to the sqlite database:

```
lstat("/home1/public/gxanth/.cache/pre-commit/db.db", {st_mode=S_IFREG|0600, st_size=5120, ...}) = 0
getpid()                                = 640
getpid()                                = 640
openat(AT_FDCWD, "/home1/public/gxanth/.cache/pre-commit/db.db", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=5120, ...}) = 0
fstat(3, {st_mode=S_IFREG|0600, st_size=5120, ...}) = 0
stat("/home1/public/gxanth/.cache/pre-commit/db.db", {st_mode=S_IFREG|0600, st_size=5120, ...}) = 0
pread64(3, "SQLite format 3\0\4\0\1\1\0@  \0\0\0\3\0\0\0\5"..., 100, 0) = 100
brk(NULL)                               = 0x55edcd2cf000
brk(0x55edcd2fa000)                     = 0x55edcd2fa000
fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}%
```

can you try the following small script for me?

```python
import contextlib
import os.path
import sqlite3


with contextlib.closing(sqlite3.connect('db.db')) as db:
    db.execute('CREATE TABLE IF NOT EXISTS d (k)')

print(os.path.exists('db.db'))
```

though the output indicates that some process is holding a read lock on that file already -- perhaps `lsof | grep db.db` could give a clone to that?

**Comment by innerout** [comment]
The output of `lsof | grep db.db` is empty your script hangs in the same way as pre-commit.

**Comment by asottile** [comment]
sounds like your `sqlite` module is broken then! -- is this maybe from a `virtualenv` hanging around from before upgrading the host machine?  is the `python` you're using custom built or part of the base os?

**Comment by innerout** [comment]
About the `virtualenv` I don't know, is there a way to verify it? The python is installed using the os package manager.

**Comment by asottile** [comment]
(for what it's worth, using a blank `centos:8` docker container that script succeeds)

**Comment by asottile** [comment]
try `/usr/bin/python3 thatscript.py` maybe? should help figure out whether a virtualenv is interfering

**Comment by innerout** [comment]
I ran it but it still does not show anything.

**Comment by asottile** [comment]
hmmm, maybe check the version of sqlite? here's what I've got:

```
[root@f44c73f4fd52 /]# yum list | grep sqlite
Failed to set locale, defaulting to C.UTF-8
sqlite-libs.x86_64                                   3.26.0-3.el8                                      @System   
apr-util-sqlite.x86_64                               1.6.1-6.el8                                       AppStream 
freeradius-sqlite.x86_64                             3.0.17-6.module_el8.1.0+198+858eb655              AppStream 
sqlite.i686                                          3.26.0-4.el8_1                                    BaseOS    
sqlite.x86_64                                        3.26.0-4.el8_1                                    BaseOS    
sqlite-devel.i686                                    3.26.0-4.el8_1                                    BaseOS    
sqlite-devel.x86_64                                  3.26.0-4.el8_1                                    BaseOS    
sqlite-doc.noarch                                    3.26.0-4.el8_1                                    BaseOS    
sqlite-libs.i686                                     3.26.0-4.el8_1                                    BaseOS    
sqlite-libs.x86_64                                   3.26.0-4.el8_1                                    BaseOS    
```

**Comment by innerout** [comment]
I got the same.

**Comment by asottile** [comment]
what happens if you move that test file to a temporary directory and try running it there? (maybe something has a lock on your homedir?)

**Comment by innerout** [comment]
I moved it in /tmp and printed true.

**Comment by asottile** [comment]
interesting!  ok I think (?) that means something has an exclusive lock on your whole home directory -- which is strange and suspicious

I'm a bit out of my depth in `lsof` commands but does this show anything useful?

```
lsof "$HOME" | grep -v '\scwd\s'
```

**Comment by innerout** [comment]
The output is empty. It is weird because my home directory is on NFS. If I login in a Centos 7 machine pre-commit installs hooks fine, if I connec to a Centos 8 machine it freezes. Shouldn't both deadlock?

**Comment by asottile** [comment]
I would expect neither to deadlock tbh -- what happens if you reboot the centos8 machine?

**Comment by asottile** [comment]
the docs do mention that locking is shady-at-best on nfs: https://www.sqlite.org/lockingv3.html#how_to_corrupt

it's possible the nfs implementation or sqlite implementation differs between the two

**Comment by asottile** [comment]
one other solution might be for you to set `$XDG_CACHE_HOME` or `$PRE_COMMIT_HOME` to somewhere that isn't on nfs

**Comment by innerout** [comment]
I set both variables to `/tmp` and it worked perfectly!

**Comment by asottile** [comment]
sweet, nfs takes another victim!  thanks for the report and the back and forth to debug 👍
