### ISSUE TITLE
API to expose the common functions required to run hooks

### ISSUE THREAD

**Issue by justin39** [pre-commit/pre-commit#1397]
In our codebase, we unfortunately can't use the package management functionality of pre-commit and so plan to run our own framework for configuring git hooks. However, there's a lot of functionality in pre-commit for writing and running git hooks that's already battle-tested and would be great to reuse!

To this end, it would be great if we could expose a documented API to avoid relying on any pre-commit internals that could lead to breaks when upgrading. This API would help handle various stumbling blocks when writing git hooks, like stashing/restoring unstaged changes around a hook to only operate on staged files.

**Comment by asottile** [comment]
can you use `language: system` and/or `repo: local` to accomplish what you need?  could you elaborate on what's not provided for you?

the internals are intentionally internal, I would not recommend depending on them and in no way is using them in the way you're describing supported.  It's enough to support the configurable surface area.  the only supported interface in pre-commit is the subprocess interface.

**Comment by justin39** [comment]
Don't think so - `language: system` + `repo: local` avoids the installation and virtual environment portion of pre-commit, but I understood it to mean that the hook executable needs to be globally available via PATH. We'd like to be able to refer to hooks that are built locally via a codebase name and have that resolve to a location for built artifacts on disk. 

Maybe we could pass in a script that handles finding the hook and returns a path to the executable that gets called by pre-commit?  That sounds more maintainable, at least.

**Comment by asottile** [comment]
sounds like you might be able to make a "remote" repository that has stub executables that exec the well-known locations on disk.  not quite the same example but we do a similar thing to use `shellcheck` via a stub python package [here](https://github.com/shellcheck-py/shellcheck-py)

**Comment by justin39** [comment]
Hm, that's pretty clever. I don't think it works for us unfortunately because we're working in a monorepo (though I need to confess to not having a great handle on our monorepo structure yet).
But since the behavior seems to be based around passing the repo to `git clone`, I'm fairly confident that workaround doesn't hack it for us.

`repo: local` is a must-have for any workarounds within the existing framework of pre-commit, I think, to avoid the clone step.

**Comment by guykisel** [comment]
maybe this helps? here's my approach to running pre-commit in a monorepo: note that this repo has python binaries + all the relevant dependencies vendored.

in a library, we have this function (apologies if the formatting is wonky, ive deleted some extra stuff thats not relevant):
```
from identify import identify
from pre_commit.xargs import xargs
from pre_commit.languages import helpers

...

def run_pre_commit_tool(
    cmd,
    file_types=None
):
    run_cmd = cmd
        if not file_types:
            file_types = {"text"}
        elif isinstance(file_types, str):
            file_types_str = file_types
            file_types = set()
            file_types.add(file_types_str)
        else:
            file_types = set(file_types)
        staged_files = []
            staged_files = set(
                relative_normalized_path(path)
                for path in staged_paths
                if os.path.exists(path)
                and identify.tags_from_path(path) & file_types
            )
            if not staged_files:
                return 0
            staged_files = helpers._shuffled(staged_files)
        run_cmd = [relative_normalized_path(sys.executable), "-m"]
        run_cmd.extend(cmd)
        run_cmd = tuple(run_cmd)
        env = dict(os.environ)
        target_concurrency = 1
        try:
            target_concurrency = multiprocessing.cpu_count()
        except NotImplementedError:
            pass
        ret, stdout = xargs(run_cmd, staged_files, env=env, target_concurrency=target_concurrency)
        return ret
```
and then you can call it like this:
```
git_helpers.run_pre_commit_tool(cmd="pre_commit_hooks.check_json", file_types="json")
```
though i'm actually using concurrent.futures.ThreadPoolExecutor to parallelize a bunch of hooks to run em at the same time (which is only safe if you are not running anything that actually modifies files)

and anyway that's called in a python script that's called by a bash precommit script.

note this depends on some pre-commit internals like xargs, but since we've vendored our deps it's safe to rely on these as long as we're careful about updates.

**Comment by asottile** [comment]
even `repo: local` can install a virtualenv and use it, you'd specify dependencies in `additional_dependencies`

**Comment by justin39** [comment]
@guykisel didn't realize how much the funky indentation would trip me up at first but the snippet is great 👍 

looks like it circumvents a lot of pre-commit's functionality when it comes to git edge cases (like `--intent-to-add` weirdness, not that I've ever used it) or small QoL touches (like fail-fast flags or diff coloring). But then again I can't see the python script that actually calls your helper function, and you could probably handle all the config file parsing and setup work in there! Though that brings up the same problems of needing to reimplementing pre-commit's functionality or directly calling internal methods again.

**Comment by asottile** [comment]
anyway, I'm not going to be exposing internals but I can help you utilize `repo: local` to accomplish the same thing (since you have access to arbitrary code there and can do ~essentially anything)

**Comment by lordmauve** [comment]
To be clear, we're proposing that we would do the work to define, expose, and document an API; would you be willing to accept PRs on that basis?

(We're merely assessing feasibility at this point though.)

I don't think we can use `repo: local`; we have dynamic path configuration. We might be able to do something like `repo: our-plugin`, if that was a thing.

**Comment by asottile** [comment]
> To be clear, we're proposing that we would do the work to define, expose, and document an API; would you be willing to accept PRs on that basis?

nope, sorry -- it's not about defining and exposing it, it's maintaining it and the gear-grind it would cause when refactoring / improving the framework.

> I don't think we can use repo: local; we have dynamic path configuration.

it's definitely possible, we do this at lyft -- here's an example which uses a special tool installed at a special location (paths and tools are of course made up but you can substitute whatever logic you may need) with python dependencies

```yaml
-   repo: local
    hooks:
    -   id: my-pylint
        name: pylint
        language: python
        entry: hooks/path-munge custompylint
        additional_dependencies: [pylint, pyyaml]
        types: [python]
```

```python
#!/usr/bin/env python3
import os
import sys

def main():
    # example munging `PATH`
    os.environ['PATH'] = f'{os.getcwd()}/vendor/bin{os.pathsep}{os.environ["PATH"]}'
    os.environ['PYTHONPATH'] = 'vendor/lib'
    # example execing some other tool (should use `subprocess.call` if you care about windows, etc.)
    cmd = (sys.executable, '-m', sys.argv[1], *sys.argv[2:])
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    exit(main())
```

**Comment by justin39** [comment]
to clarify, `path-munge` is located in the same repo where the staged files are? not a different repo?

**Comment by asottile** [comment]
yes, `local`ly at `hooks/path-munge` from the root of the repository

**Comment by justin39** [comment]
thanks - that means we would need to have this `hooks/path-munge` executable in every repo that wants to use it though, right? since the entry path will always be local to the repo that's executing pre-commit.

Can we pass pre-commit absolute paths with `language: system`? ex:
```yaml
-   repo: local
    hooks:
    -   id: my-hook
        name: custom-hook
        language: system
        entry: /home/$USER/foo/bar
```
If that's allowed, can we get the hook name as an argument in the hook executable? would be nicer than having to duplicate that value, and that way maybe we could just declare a wrapper script that handles resolving the hook and calling it before returning back to pre-commit.

**Comment by asottile** [comment]
oh I thought you had a monorepo setup

if you want to share it I'd suggest the classic setup (a repository you include in each of your repositories -- it can be a private repo) -- then you can define your one shim executable 

you can use absolute paths, but there is no environment or variable substitution (and it's very unlikely to be implemented due to the mountain of complexity there) -- but pre-commit doesn't really need to support that because a script can do any of that

**Comment by justin39** [comment]
Right, I keep saying "repo" - they're submodules, whoops! Well, submodules with some magic, I'm told. They behave awfully similar to separate repos a lot of the time until stitching everything together.

I like the idea of a script here, not sure how to work it into the pre-commit workflow though. We want to avoid needing to commit a separate script for every ~~repo~~ submodule, but we also can't just refer to the hooks via a remote `repo` to clone as they're not actually repos (and we don't want to clone/install the hooks anyways, as they're already built).

**Comment by asottile** [comment]
if they're submodules then surely they're clonable and you can follow the normal `repo: ...` approach?

**Comment by asottile** [comment]
(even if the repo isn't "remote" and even if you don't need to install something from it, you can use that to "distribute" your path munging script)

**Comment by justin39** [comment]
from what I can see, pre-commit performs a fetch into a `git submodule update --init --recursive --depth 1`. Haven't worked very closely with submodules, but doesn't that process still require pulling down the entire monorepo? unless I'm misreading the dark git incantations.

**Comment by asottile** [comment]
so what you would do is set up another of your "submodules" as a remote, and select that with

`repo: your/submodule`

**Comment by asottile** [comment]
or, you make an exception to the monorepo rule, and set up a separate repo that just houses that script

**Comment by justin39** [comment]
oh looks like fetch/checkout on a `repo/submodule` is constrained to just the submodule, neat - thanks!

that does still mean we're cloning something that's already on disk though, right? isn't that redundant? especially if we already have everything built somewhere - `repo: local` still seems like the best way to avoid that, but I'm not sure how to point pre-commit to that location.

**Comment by asottile** [comment]
I mean, if you're trying to micro-optimize a few KB idk what to tell you 😆 pre-commit is at least going to share all of them and not make N copies

note that even a `repo: local` causes an environment setup (so basically the same disk usage)
