### ISSUE TITLE
Slowly adopt pre-commit on a big project

### ISSUE THREAD

**Issue by felippemr** [pre-commit/pre-commit#1405]
Hey folks, thanks for maintaining this amazing project, it helps me get a lot done!

**Situation**
I was wondering how I could slowly adopt pre-commit hooks on a large project. A project that folks are hesitant of running black and isort all at once so, in order to mitigate that I was thinking about a way that I could "elect" a few files and have pre-commit only running on them. 

**Problem**
In theory, I could use the exclude pattern on the plugin to achieve what I want but the `.yml` config file would soon become a behemoth very hard to change and understand.

**Comment by asottile** [comment]
There's [top level `files` and `exclude`](https://pre-commit.com/#pre-commit-configyaml---top-level) for this purpose

for example if you wanted to opt in just `src/foo` but not the rest of `src` you could use:

```yaml
files: ^src/foo
hooks:
    ...
```

**Comment by felippemr** [comment]
hmmm, got it. Would it be able to have a file containing all the files I want to "whitelist" and pass it to `files:`?

Something like:
```
files: -r file_that_should_have_pre-commit.txt
hook:
  ...
```

**Comment by asottile** [comment]
no, all of pre-commit's configuration is specified directly in the config file without inclusion.  you may find [verbose regexes](https://pre-commit.com/#regular-expressions) useful if you plan to have a list of files

**Comment by felippemr** [comment]
thanks!

**Comment by felippemr** [comment]
Do you think the project could benefit from this? I am willing to create this feature if you think this makes sense.

**Comment by asottile** [comment]
no, it is an explicit design decision that there is no inclusion.  that way you can easily know whether to invalidate things just based on a simple hash of the config file.

**Comment by asottile** [comment]
plus they're regexes, not file lists
