### ISSUE TITLE
Improving pre-commit time execution performances with docker-compose usage

### ISSUE THREAD

**Issue by lemaadi** [pre-commit/pre-commit#1408]
Hi @asottile thank you for this great tools.
Right now, after creating an image by running `docker-compose up -d` and each time we execute this command : `docker-compose run --rm app pre-commit run --all-files` it initialize and install environment for all hooks which is a time-consuming, for example we have this output : 

```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Check for merge conflicts................................................Passed
Check for added large files..............................................Passed
Check python ast.........................................................Passed
Check for broken symlinks................................................Passed
Check JSON...........................................(no files to check)Skipped
Check Yaml...............................................................Passed
Trim Trailing Whitespace.................................................Passed
Debug Statements (Python)................................................Passed
Detect AWS Credentials...................................................Passed
Check JSON...............................................................Passed
Debug Statements (Python)................................................Passed
Pretty format JSON...................................(no files to check)Skipped
black....................................................................Passed
```

So, to avoid this, there are any ways to cache pre-commit installation in docker-compose context using _.pre-commit-config.yaml_ file
We already tried this solution https://github.com/pre-commit/action but it's working only in github actions context

**Comment by asottile** [comment]
this has nothing to do with the action so I moved this issue

without seeing your docker compose setup or dockerfile(s) I can't really help

**Comment by asottile** [comment]
@lemaadi ^^ could you provide more information?

**Comment by lemaadi** [comment]
Hi @asottile 
Thank's for reopening this issue.
Here is the topic : 
Having this _docker-compose.yml_
`version: '3.3'

services:
  app:
    build: .
    env_file:
      - docker-compose.env

    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8888"`

And _Dockerfile_
`FROM python:3.7.3

COPY requirements.txt /opt/pip/requirements.txt
RUN pip install -r /opt/pip/requirements.txt

ADD . /opt/app
WORKDIR /opt/app

ENTRYPOINT ["sh", "/opt/app/docker-entrypoint.sh"]`

And _.pre-commit-config.yaml_
`-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: master
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-symlinks
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: debug-statements
        args:
        - --allow-missing-credentials

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-json
    -   id: debug-statements
    -   id: pretty-format-json
        args:
        - --autofix

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        args: ['--target-version', 'py37']`

Steps to reproduce the "issue" locally: 
**1.** Run `docker-compose up -d` to build and run services
**2.** Run `docker-compose run --rm app pre-commit run --all-files` to reformat the code
So, **each time we run the second command, it initializes and installs environments for all hooks** 
The question is, if it's possible, how can we implement a cache mechanism for the pre-commit hooks to avoid the re-installation every time we run that command ?

Thank's again.

**Comment by asottile** [comment]
If you add a line similar to this in your `Dockerfile` it should cache the installations inside your image:

```dockerfile
WORKDIR /opt/app
COPY .pre-commit-config.yaml .
RUN : git init . && pre-commit install-hooks
```

you'd probably add this after your step which caches your requirements installation

**Comment by asottile** [comment]
note also, the way you make multi-line fixed-width text in markdown is by using code fences:

```markdown

    ```yaml
    yaml: code
    here: true
    ```
```

**Comment by lemaadi** [comment]
It is working as expected.
Now, the `docker-compose run --rm app pre-commit run --all-files` command takes 3 seconds to check the code format instead of more than 1 minute.
Well done +1
Thank you.

**Comment by asottile** [comment]
cheers
