### ISSUE TITLE
Commit message format hook for semantic versioning

### ISSUE THREAD

**Issue by Angeluz-07** [pre-commit/pre-commit#1409]
Is there any standard hook available to check the commit messages format?. I ask specifically for the [angular commit message style](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits) which is commonly used for semantic versioning and releases. 

This library looks nice, but I couldn't find a hook for it in https://github.com/pre-commit/pre-commit-hooks . I had to make my own script with regex and configure `.pre-commit-config.yaml` to look for the script locally, but I think you may have already a hook for it.

Thanks in advance.

**Comment by asottile** [comment]
you may find something like this in https://pre-commit.com/hooks.html -- there's likely something similar to what you need there -- `gitlint` for example lints commit messages and might have options for this?
