### ISSUE TITLE
Pre-push local and remote ref (branch name) are unavailable.

### ISSUE THREAD

**Issue by MaicoTimmerman** [pre-commit/pre-commit#1410]
The grammar for a pre-push hook is:
```
<local ref> SP <local sha1> SP <remote ref> SP <remote sha1> LF
```

I'd like to use the `<local ref>` and `<remote ref>` to add extra conditions for pushing to those branches, like which credentials are active. Current only the sha's are exposed as `PRE_COMMIT_FROM_REF` and `PRE_COMMIT_TO_REF`.

Can the refs be exposed as well?

**Comment by asottile** [comment]
if you'd like to work on this, here's the code hints:
- [hook-impl](https://github.com/pre-commit/pre-commit/blob/bcff73c9cc76f614d41933974b8f4b4d52e19251/pre_commit/commands/hook_impl.py#L109)
- [run](https://github.com/pre-commit/pre-commit/blob/bcff73c9cc76f614d41933974b8f4b4d52e19251/pre_commit/commands/run.py#L328-L338)
- [main](https://github.com/pre-commit/pre-commit/blob/bcff73c9cc76f614d41933974b8f4b4d52e19251/pre_commit/main.py#L135-L138)

**Comment by microcat49** [comment]
Hey @asottile, 

Could I work on this one? I know how to solve it.

**Comment by asottile** [comment]
sure! go for it
