### ISSUE TITLE
allow post-commit hook

### ISSUE THREAD

**Issue by ModischFabrications** [pre-commit/pre-commit#1411]
I would like to tag git versions whenever specific conditions are true. 

I can't use pre-commit because I don't have a commit yet, pre-push would lead to the new tag not being pushed together with the rest. Did I miss something or is this hook simply not added yet?

**Comment by asottile** [comment]
there has been no interest so far so it has not been implemented

you may find the work for [post-checkout](https://github.com/pre-commit/pre-commit/issues/1120) similar if you'd like to implement this

**Comment by ModischFabrications** [comment]
Can't promise anything yet, but if everything else is working I might take a stab at it.
