### ISSUE TITLE
Encountered migration mode

### ISSUE THREAD

**Issue by xiaotianq** [pre-commit/pre-commit#1419]
bug: pre-commit's script is installed in migration mode
run `pre-commit install -f --hook-type pre-commit` to fix this

How can we nee to fix this?
git ccmmit does not work but hooks are still running

**Comment by asottile** [comment]
can you show steps on how you ended up in this situation?

**Comment by xiaotianq** [comment]
We deleted the legacy file pre-commit.legacy in .git/hooks/pre-commit, the it fixed

**Comment by asottile** [comment]
right, but how did it get there? can you provide more information, versions, etc.?

**Comment by xiaotianq** [comment]
@asottile Not sure how we get the pre-commit.legacy file inside .git/hooks/pre-commit

**Comment by xiaotianq** [comment]
Now runs `git commit` or `pre-commit run`, there are no legacy files generated.

**Comment by asottile** [comment]
they patch pre-commit in an unsupported way so I can't help unfortunately
