### ISSUE TITLE
Specifying hooks to be configured from a config file

### ISSUE THREAD

**Issue by onlinejudge95** [pre-commit/pre-commit#1423]
I have started using black as a pre-commit hook, earlier I had it integrated black with my IDE, what I want now is to specify the path to config file i.e `pyproject.toml`. I **DO NOT** want to keep my config file at root dir so that I can keep all config related stuff at one place, is there any option to specify the config file path.

**Comment by asottile** [comment]
you're looking for [`--config`](https://pre-commit.com/#command-line-interface)

**Comment by onlinejudge95** [comment]
Sorry for checking in late, but thanks for the info, I don't know how I skipped it even after going through the above link 🤦‍♂️
