### ISSUE TITLE
Any scalar quotes around rev are lost during autoupdate

### ISSUE THREAD

**Issue by marcjay** [pre-commit/pre-commit#1434]
#### Steps to reproduce

Example `.pre-commit-config.yaml`:
```
repos:
-   repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v2.4.0'
    hooks:
    -   id: 'trailing-whitespace'
    -   id: 'end-of-file-fixer'
    -   id: 'check-yaml'
    -   id: 'check-added-large-files'
```

Run 
```
$ pre-commit autoupdate
Updating https://github.com/pre-commit/pre-commit-hooks ... updating v2.4.0 -> v2.5.0.
```

`.pre-commit-config.yaml` after:
```
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.5.0
    hooks:
      - id: 'trailing-whitespace'
      - id: 'end-of-file-fixer'
      - id: 'check-yaml'
      - id: 'check-added-large-files'
```
Any wrapping quotes (single or double) around the `rev` value are lost during the update

I noticed this when I turned on the `quoted-strings` [yamllint rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings) and set it to `required` to be consistent with our internal YAML coding conventions

**Comment by asottile** [comment]
Hmmm, I considered it a feature that it fixed to bare strings if they were unnecessarily quoted, this kinda goes against that.  personally I'm not sure I agree with `quoted-strings: required` but I don't want that to interfere with this.  I'll review the patch but I'm not sure this is an improvement 🤔

**Comment by asottile** [comment]
also seems that the rule is inconsistently applied, since your keys should get quoted too (they're strings!)

**Comment by marcjay** [comment]
> Hmmm, I considered it a feature that it fixed to bare strings if they were unnecessarily quoted, this kinda goes against that. personally I'm not sure I agree with `quoted-strings: required` but I don't want that to interfere with this. I'll review the patch but I'm not sure this is an improvement 🤔

Understood, didn't realise that, I guess I thought it seemed to be verging on being beyond the scope of pre-commit to apply YAML style changes - but please don't #TodayInOpenSource me! 😳. I won't be offended if the PR is rejected.

> also seems that the rule is inconsistently applied, since your keys should get quoted too (they're strings!)

That's a good point -  It seems to be a conscious decision - but I don't know the background: https://github.com/adrienverge/yamllint/issues/176#issuecomment-486663998
From our perspective a good majority of our YAML is Ansible, where the keys are well-known and safe from being parsed as non-strings, but the values are where bugs can creep in. Given that revs are always strings (unless I'm mistaken) quoting them for safety seemed sensible

**Comment by asottile** [comment]
lol, no you're fine <3

**Comment by asottile** [comment]
yeah it's just weird because like:
```yaml
provinces:
  BC: Victoria
  ON: Toronto
  # ...
```

but yeah off topic I'll shush :)

**Comment by asottile** [comment]
but yeah, I'm fine taking this change 👍
