### ISSUE TITLE
Add option to retry cloning of the repos

### ISSUE THREAD

**Issue by okainov** [pre-commit/pre-commit#1441]
Today we got quite some of the errors with flake8 hook:

```
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: unable to access 'https://gitlab.com/pycqa/flake8/': Operation timed out after 300004 milliseconds with 0 out of 0 bytes received
    
Check the log at /tmp/pre-commit/pre-commit.log
```

While when I check the repo manually, it seems to be there, up and healthy. Probably it would make sense to have a top-level configuration option for `pre-commit` to specify amount of retries to clone the repo it does before failing.

**Comment by asottile** [comment]
we don't really have much control over the underlying protocol where a retry would be appropriate (and given the message above at 300,000ms timeout I don't think a retry would even be desirable -- at n=2 you're looking at 10 minutes to first failure!!!)

I notice you're using an older version of git which has some limitation sin the fetch protocol, in newer versions I believe the protocol has changed to handle this better

there's been previous discussion of this as well, I think it's probably best for the user to retry in these situations and probably not to handle it in the tool

**Comment by okainov** [comment]
As a user I cannot "retry" as it's part of my CI job. I can only retrigger the whole job which is very undesirable since it introduces yet another reason for annoying developers ("CI is stable").

I'm not sure how "old" is my git, it's coming from Docker image similar to this:

```
FROM docker:19

# Install required packages
RUN apk add --no-cache git && pip3 install pre-commit

```

So I assume it's not so old.

>(and given the message above at 300,000ms timeout I don't think a retry would even be desirable -- at n=2 you're looking at 10 minutes to first failure!!!)

Is the timeout configurable? I'd say typically 30s is good enough for one try, so the tool can try several times and fail after 3-5 failures.

**Comment by asottile** [comment]
your git is falling into the slow full-fetch path so I suspect it's pretty old 🤔 

I don't know about changing `git`'s timeouts internally, all pre-commit does is call `git`.

I'd suggest you set up caching and retries in your CI layer, you'll probably have happier devs either way -- https://pre-commit.com/#managing-ci-caches (also it's very easy for you to write `pre-commit install-hooks || pre-commit install-hooks` I imagine)

note that 300,000ms is 5 minutes not 30 seconds

**Comment by okainov** [comment]
```
/ # git --version
git version 2.24.2
```

From two months ago. It's for sure not "old".

I do know that 300k ms is 5 minutes, I know math :)

Also we will take a look at caching the hooks, but it's not related to the subj feature request.

**Comment by asottile** [comment]
I mean, it kind of is related :) -- if you're cached you don't need to request most times and retries are essentially unnecessary

**Comment by asottile** [comment]
this was also due to a gitlab outage, which a retry would not help you with

**Comment by okainov** [comment]
> this was also due to a gitlab outage, which a retry would not help you with

Not really

>While when I check the repo manually, it seems to be there, up and healthy.

**Comment by asottile** [comment]
there was a brief outage right before you posted the issue so it's likely when you looked manually the website was back up again
