### ISSUE TITLE
Using repo local disable ability to install python package

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1445]
The `language: python` documentation states that it does automatically install the current package using `pip install .` but apparently this does not happen with local repositories, as seen on https://github.com/ansible/ansible-lint/pull/779/files

Example:
```
  - id: docs-rebuild
    name: Checks that generated docs are in-sync with commit
    entry: python -m ansiblelint.generate_docs
    language: python
    pass_filenames: false
```

That hook definition is inside ansiblelint repository, which has a `setup.py` which should be installed but what happens looks like:
```
Checks that generated docs are in-sync with commit.......................Failed
- hook id: docs-rebuild
- exit code: 1

/Users/ssbarnea/.cache/pre-commit/repoxu2n7dg2/py_env-python3.7/bin/python: Error while finding module specification for 'ansiblelint.generate_docs' (ModuleNotFoundError: No module named 'ansiblelint')
```

Because the normal hook works without problems I suspect that is a bug related to use of local. I tried to run with multiple `-vvv` flags but it did not produce more output.

**Comment by asottile** [comment]
`repo: local` is "I install only from the .pre-commit-config.yaml" -- it is an escape from the normal repository-based installation which indeed does `pip install .` (implementation detail: it still runs `pip install .`, but it's on the empty template)

this is intentional, installing from things outside of `.pre-commit-config.yaml` leads to intractable caching problems (which have been brought up in many issues in the past, can probably search for `requirements.txt` or `pylint` for other related issues)

**Comment by asottile** [comment]
(you can however use `additional_dependencies` to pull in dependencies from pypi there)

**Comment by ssbarnea** [comment]
I do not understand why this was closed as it seem to be a real bug which prevents dog-fooding for python libraries.

If I have a python projects which is a linter that supports being used as a pre-commit, this limitation makes impossible to test a change using its own code. Clearly the linters needs to be installed in order to be run. When this happens the code is never tested.

I am not saying that the current behavior needs to be changed but I am trying to find a workaround that allows linter developers test pre-commit integration. What would you recommend?

I faced this issue while working on https://github.com/ansible/ansible-lint/pull/779/files 

Once I know the workaround I would be happy to make PR to improve the documentation around use of `local` feature.

**Comment by asottile** [comment]
you can look at any of the many duplicates for the technical reasons why: #1406  https://github.com/pre-commit/mirrors-mypy/issues/3 #730 #880 https://github.com/pre-commit/pre-commit-hooks/issues/157 https://github.com/pre-commit/pre-commit/issues/362 https://github.com/pre-commit/pre-commit/issues/266 https://github.com/pre-commit/pre-commit/issues/178

the supported way to try a repo in this case is to use `pre-commit try-repo`
