### ISSUE TITLE
The script to install golang env requires golang

### ISSUE THREAD

**Issue by priyasiddharth** [pre-commit/pre-commit#1449]
https://github.com/pre-commit/pre-commit/blob/b3c0eab7dc47b95125744ec560aa3f204874b013/pre_commit/languages/golang.py#L81

The introduction mentions...

_If one of your developers doesn’t have node installed but modifies a JavaScript file, pre-commit automatically handles downloading and building node to run eslint without root._

I would assume golang would be installed automatically in a similar manner. 

Is this reasonable?

thank you
Siddharth

**Comment by asottile** [comment]
So pre-commit has various levels of language support currently.  This is roughly outlined in the [contributing guidelines](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#adding-support-for-a-new-hook-language).

the example language there (`node`) is a "first class" language which pre-commit will bootstrap if it doesn't exist.

`go` is unfortunately currently in the "second class" language type which means that the user needs to have a go toolchain set up already.

a patch to improve this would be appreciated, but it's understandable that some of the languages won't be bootstrappable from scratch.

**Comment by xenowits** [comment]
> So pre-commit has various levels of language support currently. This is roughly outlined in the [contributing guidelines](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#adding-support-for-a-new-hook-language).
> 
> the example language there (`node`) is a "first class" language which pre-commit will bootstrap if it doesn't exist.
> 
> `go` is unfortunately currently in the "second class" language type which means that the user needs to have a go toolchain set up already.
> 
> a patch to improve this would be appreciated, but it's understandable that some of the languages won't be bootstrappable from scratch.

Hi @asottile . I'hv go toolchain already setup but I'm unable to go repo hooks (https://github.com/corverroos/fiximports). My local `.pre-commit-config.yaml` has:
```
repos:
  -   repo: https://github.com/corverroos/fiximports
      rev: 258e9de8481700360dd4b65a9183c1ba4874c66c
      hooks:
        -   id: go-fiximports
```
Says `AssertionError: For now, pre-commit requires system-installed golang`. Can you help?

**Comment by asottile** [comment]
don't comment on old issues, especially when they are **not** your problem

make a new issue and fill out the issue template
