### ISSUE TITLE
Run project command

### ISSUE THREAD

**Issue by countravioli** [pre-commit/pre-commit#1456]
I already have a lint command setup in tox. I don't see a way to use pre-commit to just run that.

Ideally I'd be able to run X hooks from the ecosystem and my own that are part of my repo. It looks like I could make a separate repo to do this but that seems like quite the overhead.

Is there a way to just run a custom command at project root? Thanks!

**Comment by asottile** [comment]
I believe you're looking for [repository local hooks](https://pre-commit.com/#repository-local-hooks)

**Comment by countravioli** [comment]
Thanks! Guess i didn't make it to advanced or didn't expect it in there. GoogleFu was weak today. Appreciate it!
