### ISSUE TITLE
Add possibility to have disabled hook

### ISSUE THREAD

**Issue by okainov** [pre-commit/pre-commit#1457]
We'd like to have the possibility to add some hooks which can be run only manually

Something like:
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
        enabled: False
```

So the hook is not being run by default with `pre-commit run` however it might be run manually `pre-commit run trailing-whitespace`

**Comment by asottile** [comment]
I believe you're looking for [`stages: [manual]`](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages)
