### ISSUE TITLE
How to deal with `git commit --all`?

### ISSUE THREAD

**Issue by kulti** [pre-commit/pre-commit#1461]
I love how to pre-commit deal with fixer-hooks. They not change staged diffs.

If I have unstaged diffs I often do stage and commit in one operation: `git commit -a`.

Is that possible to stage current diffs and keep fix is unstaged? Or maybe you have other good approach to how to deal with `git commit -a`?

**Comment by asottile** [comment]
I'm not sure what you mean, I believe `git commit -a` works the same way normal commits work (during commit the files appear as "staged" and so pre-commit won't stash them)?

**Comment by kulti** [comment]
Sorry. I try to explain it in another way.

I have a file 1.py with double quoted python string that should be fixed by double-quote-string-fixer.

pre-commit works great when diff staged before commit. Loot at [this paste](https://pastebin.com/M6xVz261). After failed commit diffs are separated.

But when diff is not staged hook change my files unrevertable. Loot at [this paste](https://pastebin.com/1sV2DQXr). After `git commit -a` my changes was mixed with from double-quote-string-fixer. I want to have the state from the first scenario.

I'm not sure that is a job for pre-commit. If it has any solution, it will be cool to illustrate that in pre-commit documentation.

**Comment by asottile** [comment]
yeah I don't think that's possible to separate -- to pre-commit both of those scenarios appear the same given what `git` tells us
