### ISSUE TITLE
exclude and files filters

### ISSUE THREAD

**Issue by k4ch0** [pre-commit/pre-commit#1470]
Hello, 

I have this project layout:

```
.
├── data
├── defaults
├── docs
├── etc
├── inventories
├── output
├── playbooks
├── plugins
├── roles
├── scripts
├── templates
├── terraform
├── tests
└── vars
```

I want to configure `exclude` and `files` as:

```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black

files: |
  ^defaults/
  ^docs/
  ^etc/
  ^inventories/
  ^roles/
  ^scripts/
  ^templates/
  ^terraform/
  ^tests/
  ^vars/
   * #For all the files on root directory

exclude: |
  ^data/
  ^output/
  ^plugins/
```

But filter it is not working that way.

What is the correct way to perform that filtering?

**Comment by asottile** [comment]
`files` and `exclude` are [regular expressions](https://pre-commit.com/#regular-expressions)

you actually don't need `files` here and just `exclude` and can do `exclude: `^(data/|output/|plugins/)` or if you want to use multi line regexes:

```yaml
exclude: |
    (?x)(
        ^data/|
        ^output/|
        ^plugins
    )
```

**Comment by k4ch0** [comment]
I'm configuring the exclude as you mentioned.
But when I'm running `pre-commit run --all-files` it is not excluding those folders.
I'm trying to run it on all the files just as first step using pre-commit.

What do you suggest?

**Comment by asottile** [comment]
can you share your configuration and the full output so I can see what you are seeing

**Comment by k4ch0** [comment]
It is working now, it was a yaml isssue.
Thank you for your support!

**Comment by jakubziebin** [comment]
Hello, I have the same problem...
My configuration is as follows:
```
files: |
    (?x)(
            ^python/my_project/.*$|
            ^python/tests/.*$
    )
exclude: |
    (?x)(
            ^python/my_project/cpp_python_bridge.pyi|
            ^python/my_project/project_result.py|
            ^python/my_project/project_visitor.py|
            ^python/my_project/project_proto/.*$
    )
```
When I run `pre-commit run --all-files` pre-commit (mypy especially) also checks files with exclude, is this the expected behaviour?

**Comment by asottile** [comment]
your question is off topic but:

mypy follows imports even if pre-commit does not pass it the filename
