### ISSUE TITLE
Use appdirs to determine OS specific cache dir

### ISSUE THREAD

**Issue by hoefling** [pre-commit/pre-commit#1475]
I have noticed that `pre-commit` stores its cache into `~/.cache` and not into `~/Library/Caches` on MacOS due to how `_get_default_directory()` is implemented:

https://github.com/pre-commit/pre-commit/blob/d71699d7cdd02d54568209711934ad35c8e89dd7/pre_commit/store.py#L33-L36

I don't consider this to be a real issue, it's only something to keep in mind when freeing disk space. However, maybe it would be more elegant to use something like [`appdirs`](https://pypi.org/project/appdirs/) to find the OS specific cache dir. The above snippet could then become
```python
ret = os.environ.get('PRE_COMMIT_HOME') or appdirs.user_cache_dir('pre-commit')
```

**Comment by asottile** [comment]
I've decided to intentionally reject the per-os cache dirs and use XDG everywhere

I know it's slightly wrong, but the consistency is worth it
