### ISSUE TITLE
Running pre-commit fails when using a conda virtual environment

### ISSUE THREAD

**Issue by ahmedkrmn** [pre-commit/pre-commit#1477]
Running `pre-commit run --all-files` fails when running on a conda environemnt.
Below is the detailed output:
```
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('c:\\users\\ahmedkaraman\\anaconda3\\envs\\test\\python.exe', '-mvirtualenv', 'C:\\Users\\AhmedKaraman\\.cache\\pre-commit\\repor5uf9mc5\\py_env-python3.6', '-p', 'C:\\python36\\python.exe')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\python36\\python.exe'

stderr: (none)
Check the log at C:\Users\AhmedKaraman\.cache\pre-commit\pre-commit.log
```

It appears that the library expects Python to be installed in `C:\\python36\\python.exe`, but this isn't the case when using Anaconda.

**Comment by asottile** [comment]
this means that pre-commit was unable to find  any python3 installation on your computer that was compatible.

It tries the following on windows:
- the current executable
- `py -3.6`
- `C:\python36\python.exe`

if you don't have any of those you'll see the message above, and there's nothing that can be done about that, sorry.

**Comment by ahmedkrmn** [comment]
@asottile thanks for the clarification. I think it would be nice if the user can manually specify the Python path if Anaconda is used.

**Comment by asottile** [comment]
do you have python3.6 installed?

**Comment by ahmedkrmn** [comment]
No it's not installed globally on the system. I'm using separate conda environments.

**Comment by asottile** [comment]
ok then this is invalid, that's not how `language: python` works
