### ISSUE TITLE
random.shuffle's random= argument got deprecated

### ISSUE THREAD

**Issue by isidentical** [pre-commit/pre-commit#1479]
Related issue: [bpo-40465](https://bugs.python.org/issue40465).
```
black..................................................................../home/isidentical/.venv/lib/python3.10/site-packages/pre_commit/languages/helpers.py:95: DeprecationWarning: The *random* parameter to shuffle() has been deprecated
since Python 3.9 and will be removed in a subsequent version.
  random.shuffle(seq, random=fixed_random.random)
Passed
```

**Comment by asottile** [comment]
well that's annoying.

**Comment by serhiy-storchaka** [comment]
Why not to use just
```python
fixed_random.shuffle(seq)
```
?

**Comment by asottile** [comment]
is that documented? I don't see it on https://docs.python.org/3/library/random.html

**Comment by serhiy-storchaka** [comment]
https://docs.python.org/3.9/library/random.html#random.shuffle

**Comment by asottile** [comment]
yeah that's what the current code is using?

**Comment by isidentical** [comment]
> yeah that's what the current code is using?

I think what @serhiy-storchaka is suggesting that, since you set a custom seed you can use directly `fixed_random`'s shuffle method.
```py
def _shuffled(seq: Sequence[str]) -> List[str]:
    """Deterministically shuffle"""
    fixed_random = random.Random()
    fixed_random.seed(FIXED_RANDOM_SEED, version=1)

    seq = list(seq)
    fixed_random.shuffle(seq)
    return seq
```

**Comment by asottile** [comment]
I get that, but where in the documentation does it say that `Random` has a `shuffle` method -- the link above is to the module's function

**Comment by serhiy-storchaka** [comment]
> The functions supplied by this module are actually bound methods of a hidden instance of the random.Random class. You can instantiate your own instances of Random to get generators that don’t share state.

**Comment by asottile** [comment]
🤦 and here I was expecting it to be documented under https://docs.python.org/3/library/random.html#random.Random
