### ISSUE TITLE
Using pre-commit through intellij/pycharm commits

### ISSUE THREAD

**Issue by symonk** [pre-commit/pre-commit#1487]
Hi Anthony, great tool thanks! - I've always used the command line for git in which case everything works nicely, however trying to roll this out in work has caused some headaches / confusion for those who rely on intellij/pycharm for doing day to day git tasks.  Heres an example of when things go bad below:

- Modify a simple file in the repo that black will rewrite, change a "hello world" to 'hello world':

```python
 def last_failed_show(config, session) -> int:
     terminal_writer = TerminalWriter()
-    var = "hello world"
+    var = 'hello world'
     print(var)
```

- Add/commit such file using pycharm which automatically runs git hooks to apply black (which will rewrite the file and abort the commit (rightly so):

```bash
0 file committed, 1 file failed to commit: test2
black....................................................................Failed
- hook id: black
- files were modified by this hook
```

When committing through intellij, the following commands are issued here:

```bash
22:54:21.066: [pytest] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- src/_pytest/cacheprovider.py
22:54:21.115: [pytest] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F C:\Users\sy\AppData\Local\Temp\git-commit-msg-.txt --
black....................................................................Failed
- hook id: black
- files were modified by this hook
```

As far as this file within Intellij/pycharm goes, it is now impossible to add it via the GUI, the add/commit options are no longer available, from the cli we see the following:

```bash
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   src/_pytest/cacheprovider.py

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/_pytest/cacheprovider.py
```

Has anyone came across this before and has a potential work around to make it work? maybe its an intellij issue as they don't seem to run `traditional` git commands as you would via the CLI.

![image](https://user-images.githubusercontent.com/17887843/83817231-1daa8b80-a6bc-11ea-9c5d-5aabef7eda50.png)

^ intellij only git user is now in somewhat of a 'limbo' situation.

Appreciate your time, thanks :)

**Comment by asottile** [comment]
sounds like a bug/regression in pycharm -- this used to work

**Comment by asottile** [comment]
this might be windows specific as well, I've never tried intellij / pycharm on windows

**Comment by symonk** [comment]
@asottile thanks for the quick replies, I an recreate this issue on work (mac) and at home (windows).  Same here, ive always been running on the CLI but trying to roll it out is a little more difficult as some folks prefer the comforts of the IDE so I need to support both

**Comment by asottile** [comment]
I'd suggest opening an issue on intellij, the git commands it runs aren't anything special but the bug is that it's not noticing the modifications correctly

**Comment by symonk** [comment]
not sure if relatable but: https://youtrack.jetbrains.com/issue/IDEA-63391?_ga=2.13035775.978496579.1591306893-23816267.1581023896

**Comment by asottile** [comment]
doesn't seem related -- their bug is that the IDE is not noticing that the files are modified
