### ISSUE TITLE
Is there any interest in putting nodeenv behind extras_require?

### ISSUE THREAD

**Issue by joshuarli** [pre-commit/pre-commit#1488]
Recently was surprised to find out about `nodeenv` in my virtualenv. I don't use pre-commit for any node-related things, so it would be nice to put `nodeenv` behind an extras_require.

Or, it might be more preferable to somehow tell pip to not install nodeenv... I'm not sure if an inverse extras_require is possible in setuptools metadata?

If there's any interest in this, I can submit a PR for this as well as update any related documentation.

**Comment by asottile** [comment]
extras is a major pain in the ass, so no.  the same can be said for toml or virtualenv too

part of the design of pre-commit is you don't care what language things are implemented in

**Comment by joshuarli** [comment]
Gotcha, thanks for the quick reply.
