### ISSUE TITLE
Creation of files does not fail hook

### ISSUE THREAD

**Issue by hyperfekt** [pre-commit/pre-commit#1489]
When a hook creates files, the hook still passes.

This could be interpreted as ontradicting the documentation, which states:
`The hook must exit nonzero on failure or modify files in the working directory.`

The hook does modify the _set_ of files in the working directory, but does not modify any _individual_ file in the working directory.

The issue could be treated as either one of unclear documentation or one of implementation.

**Comment by asottile** [comment]
can you show a demo? given what I know about the implementation, the documentation is correct.  here's a small demo confirming that:

```console
$ touch foo bar
$ git add .
$ git status
On branch master

No commits yet

Changes to be committed:
	new file:   .pre-commit-config.yaml
	new file:   bar
	new file:   foo

$ git ls-files
.pre-commit-config.yaml
bar
foo
$ pre-commit  run --all-files
modifier.................................................................Failed
- hook id: modifier
- files were modified by this hook
$ git status
On branch master

No commits yet

Changes to be committed:
	new file:   .pre-commit-config.yaml
	new file:   bar
	new file:   foo

Changes not staged for commit:
	modified:   bar

$ cat .pre-commit-config.yaml 
repos:
-   repo: local
    hooks:
    -   id: modifier
        name: modifier
        entry: bash -c 'echo hi >> bar'
        language: system
        files: ^foo$
        pass_filenames: false
```

**Comment by asottile** [comment]
ah I see your edit now, creation of files also will make things modified, though the files need to be created as part of the index (usually via `git add --intent-to-add`)

newly created files are not part of the index by default so they are not tracked (it is impossible to know whether a file that's created should be tracked)

**Comment by hyperfekt** [comment]
Yes, sorry for the unclear statement of the issue at first. I only thought to investigate that part after I had already opened it, which goes to show how confusing this can be due to the vagueness of words like 'modify' et cetera.
In that case clarifying the documentation is probably most appropriate?

**Comment by asottile** [comment]
I'd maybe just drop "in the working directory"
