### ISSUE TITLE
Make pre-commit PEP 561 compatible package

### ISSUE THREAD

**Issue by playpauseandstop** [pre-commit/pre-commit#1493]
Hi!

I wonder are the any objections in making pre-commit [PEP 561](https://www.python.org/dev/peps/pep-0561/) compatible package by adding,

- `py.typed` file to `pre_commit` and all internal packages (`pre_commit.commands`, `pre_commit.languages`, etc)
- `Typing :: Typed` classifier to `setup.cfg`

As `pre_commit` already provide type annotations for all their code, adding `py.typed` will allow mypy (and other type checkers) to properly run type checking against the code, which imports `pre_commit` library.

If you're ok with given improvements, I'd will to provide them and, as well, provide basic tests, that `pre-commit` typed well.

Thanks!

**Comment by asottile** [comment]
pre-commit has no python api so no this will not happen

please do not import code from pre-commit
