### ISSUE TITLE
Wrong python version used by pre-commit

### ISSUE THREAD

**Issue by beverlybiwenlow** [pre-commit/pre-commit#1504]
Hi, 

I'm facing this issue where my default Python on my system is `3.6.9`, but pre-commit uses `3.6.0` in running the hooks.

```
➜   python --version
Python 3.6.9
➜  python3.6
Python 3.6.9 (default, Jun 12 2020, 10:30:48)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

In my config, I pinned `default_language_version` to `3.6`, and I expected pre-commit to use the latest release version that I have, ie. `3.6.9`
```
default_language_version:
    python: python3.6
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
```

However, pre-commit used `3.6.0` instead, and threw the error below:
```
➜  pre-commit run --all-files
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/blow/.cache/pre-commit/repo7_4ikr9y/py_env-python3.6/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/blow/.cache/pre-commit/repo7_4ikr9y

stderr:
    ERROR: Package 'pyupgrade' requires a different Python: 3.6.0 not in '>=3.6.1'

Check the log at /Users/blow/.cache/pre-commit/pre-commit.log
```

Pinning `python3.6.9` for `default_language_version` in the config solves this problem, but I want to be able to not pin release versions and just pin `python3.6`. 

Am I doing something wrong in my setup? Appreciate the help.

**Comment by asottile** [comment]
can you `cd / && python3.6 --version`

**Comment by beverlybiwenlow** [comment]
```
➜  cd / && python3.6 --version
Python 3.6.9
```

Appreciate the quick response :)

**Comment by asottile** [comment]
what does `which -a python3.6` give you

and what about `$(head -1 $(which pre-commit) | cut '-d!' -f2) --version`

(I think that command is correct, sorry typed on my phone

**Comment by beverlybiwenlow** [comment]
Here you go

```
➜  which -a python3.6
/Users/blow/.pyenv/shims/python3.6
➜  /Users/blow/.pyenv/shims/python3.6
Python 3.6.9 (default, Jun 12 2020, 10:30:48)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
➜  $(head -1 $(which pre-commit) | cut '-d!' -f2) --version
Python 3.7.7
```

**Comment by asottile** [comment]
hmmmm my guess is you've got pyenv 3.6.0 configured globally?  maybe try `pyenv global 3.6.9`?

I'm surprised that the `cd / && python3.6 --version` didn't show 3.6.0 in that case though, but then again it's been quite a while since I've debugged pyenv

**Comment by asottile** [comment]
@beverlybiwenlow any updates on this?  could you also `cd ~ && python3.6 --version`

**Comment by beverlybiwenlow** [comment]
I resolved this by removing 3.6.0 from my machine. Thanks for your help and will close this now

**Comment by icfly2** [comment]
I'm leaving this info here as the above is not super helpful

For me this issue was caused and resolved by looking at the python3 python call. Redefining what python3 maps to fixed it. This is best done by editing the symlink as described here: https://unix.stackexchange.com/a/521060

**Comment by asottile** [comment]
doing what that link suggests is a terrible idea -- your system depends on that being the system python and many parts of your OS use that and will break if you switch the version
