### ISSUE TITLE
Using git directly instead of a temporary file when stashing changes

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pre-commit/pre-commit#1505]
First, thank you for this great hook framework, I'm using it all the time.

After checking the code for removing the changes that are not stagged [here](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/staged_files_only.py#L42), it seems that pre-commit use a temporary file that will be deleted when we leave the context of pre-commit, because it's created with a `tempdir_factory.get()`
```python
        with open(patch_filename, 'wb') as patch_file:
            patch_file.write(diff_stdout_binary)
```
This means that if you halt pre-commit during its execution you can lose your unstaged changes because the temporary file disappears. I think it would be safer to stash inside git, so the changes can be recovered using git if pre-commit is halted with ctrl+C or for another problem.

This is not an hypothetical situation, by the way, we lost 3 hours of changes that way :)

Let me know if something is problematic with this approach. I could work on it.

**Comment by asottile** [comment]
the temporary file is never deleted so this isn't a problem

`git stash` *will lose your changes on conflict* so it is intentionally avoided

**Comment by asottile** [comment]
`tempdir_factory` is only a thing in the tests, I think you're misunderstanding how the code works in reality :)

**Comment by asottile** [comment]
> This is not an hypothetical situation, by the way, we lost 3 hours of changes that way :)

**Comment by Pierre-Sassoulas** [comment]
Hmm, ok, if someone see this the temporary file is stored in :
```
    ret = os.environ.get('PRE_COMMIT_HOME') or os.path.join(
        os.environ.get('XDG_CACHE_HOME') or os.path.expanduser('~/.cache'),
        'pre-commit', 
    )
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for the quick answer :)

**Comment by asottile** [comment]
pre-commit prints the location of the file as well so no need to go digging:

```console
$ git commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.cache/pre-commit/patch1591945458.
Check docstring is first.............................(no files to check)Skipped
...
```
