### ISSUE TITLE
Debug how pre-commit initializes its environment

### ISSUE THREAD

**Issue by atzannes** [pre-commit/pre-commit#1508]
I'm writing my first hook and I'm stumped because the hook fails because one of its python dependencies is not installed in the environment. My first thought was I have messed up and forgot to include that dependency somewhere such as in my `setup.py`. However, when I do `pip install -e .` in a fresh virtualenv and then run `pre-commit run` (with `repo:local` in my `.pre-commit-config.yaml`)  my hook succeeds. But when I run `pre-commit try-repo . <hook-name>` the hook fails with a `ModuleNotFound` error. The same happens if I replace `repo:loca`l with the remote and give it a `rev`.

I tried to increase the verbosity to see how `pre-commit` installs the hook environment but to no avail and I'm stumped. Is there a way to see what happens during that step (the one we are warned that "This may take a few minutes...").

Love pre-commit by the way, thanks!

**Comment by asottile** [comment]
your editable install is probably hiding your broken packaging -- try [`pip install .`](https://pre-commit.com/#python) as the docs indicate

**Comment by atzannes** [comment]
Apologies for the slow turnaround. My packaging was broken and I believe I've fixed it. Now the pre-commit hook works as expected (it succeeds to install my repo), but `pip install .` still doesn't work, even though I can successfully install from a github commit with `pip install git+https://github.com/user/repo@commit#egg`. This is a package with compiler C++ extensions and so its build and dependencies are tricky. That's why I wanted to know how exactly pre-commit is installing the package so I could get it to work. It looks like `pip install .` is not it, although for most packages it should be equivalent.

So, if `pip install .` doesn't work for you because your package is not straightforward, perhaps if you can get a clean install with `pip install git+https://github.com/<user>/<repo>.git@<commit-hash>#egg=<repo>`, that would be sufficient for pre-commit.

**Comment by asottile** [comment]
I promise you, it's [literally just `pip install .`](https://github.com/pre-commit/pre-commit/blob/e2fe94cbe75b79e48baf78660b3b26f4e19e2040/pre_commit/languages/python.py#L209)

**Comment by atzannes** [comment]
Interesting. Does the hook perhaps run in a different directory than the root directory of the package? It looks like that makes a difference in my case. In any case, thank you for the quick responses and for `pre-commit`. It's great!

**Comment by asottile** [comment]
hooks will run from the root of the repository you're committing to

basically you can simulate with:

```
git clone ... ../hook
cd ../hook
virtualenv venv
venv/bin/pip install .
cd -
../venv/bin/myexe path/to/files
```
