### ISSUE TITLE
"Executable ... is not executable" error

### ISSUE THREAD

**Issue by bdarcus** [pre-commit/pre-commit#1514]
I'm new to pre-commit, so apologies if I'm missing something obvious.

I have [this config file](https://github.com/citation-style-language/schema/blob/master/.pre-commit-config.yaml), which points to [this script](https://github.com/citation-style-language/schema/blob/master/hooks/rnc-format-validate.py).

Per the linked issue, I did `chmod +x` on the script, but when I try to commit, I get a `Executable 'hooks/rnc-format-validate.py is not executable` error.

I had previously tested this on some local test repos without ever seeing this error.

citation-style-language/schema#256

**Comment by asottile** [comment]
can you show the full output and command you ran?

**Comment by bdarcus** [comment]
Sure thing; here you go:

``` console
❯ git commit schemas/styles/csl.rnc   
Check for merge conflicts................................................Passed
prettier.............................................(no files to check)Skipped
Check rnc schema files...................................................Failed
- hook id: rnc-format-validate
- exit code: 1

Executable `hooks/rnc-format-validate.py` is not executable

```

**Comment by asottile** [comment]
can you `ls -al hooks` for me?

**Comment by bdarcus** [comment]
``` console
❯ ls -al hooks 
total 4
drwxr-xr-x. 1 bruce bruce  44 Jun 17 12:25 .
drwxr-xr-x. 1 bruce bruce 256 Jun 17 11:26 ..
-rw-r--r--. 1 bruce bruce 757 Jun 17 12:25 rnc-format-validate.py
```

**Comment by asottile** [comment]
so you haven't done `chmod +x` on that file?

**Comment by bdarcus** [comment]
I did, but I guess I needed to fix the permissions in the repo. 

This appears to have solved it:

``` console
git update-index --chmod=+x hooks/rnc-format-validate.py
```

Sorry for the noise.
