### ISSUE TITLE
special handling of source-container formats, esp. ipynb

### ISSUE THREAD

**Issue by graingert** [pre-commit/pre-commit#1520]
I'm working on a project with several .ipynb files and I'd like to be able to run things like add-trailing-comma and pyupgrade on the code inside the "code" cells. This works great with black_nbconvert, but black without add-trailing-comma is painful

it feels like something in the scope of pre-commit, eg files with files in them, eg ipynb files, rst files with embedded code, or even .zip and .tgz files
to open the container format into multiple files run pre-commit hooks on them and then re-construct them into the original file

**Comment by asottile** [comment]
(as discussed in discord) pre-commit as a framework only operates on executables and filenames and knows nothing about the underlying format, etc. (and though pre-commit is written in python, it is not a python-specific tool -- the suggestion here would require pre-commit to have significant knowledge of a particular format)

what I'd suggest is writing a tool which parses the container format and calls out to the individual tools and then writes back to the container (similar to how https://github.com/asottile/blacken-docs works), and then pre-commit can call that as normal
