### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by sassan72** [pre-commit/pre-commit#1523]
```
/opt/anaconda3/lib/python3.7/site-packages/jsonschema/__init__.py in <module>
     31     from importlib import metadata
     32 except ImportError: # for Python<3.8
---> 33     import importlib_metadata as metadata
     34 __version__ = metadata.version("jsonschema")

ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by asottile** [comment]
guessing: you compiled dependencies using pipenv with python3.8 and then installed in python3.7

**Comment by asottile** [comment]
oh actually, our module doesn't use `jsonschema` at all so this is off topic

**Comment by sassan72** [comment]
you mean I must upgrade python3.7 to python3.8. is that true?

**Comment by asottile** [comment]
no, I was just guessing sorry -- I'm not sure why you made the issue on my project in the first place though, we don't use `jsonschema`

**Comment by sann3** [comment]
I also faced the same issue, upgrading the python to 3.8 solved the issue.
