### ISSUE TITLE
Unable to use detect_private_key in the latest rev

### ISSUE THREAD

**Issue by akoul** [pre-commit/pre-commit#1524]
I am using the latest rev, however when I do a pre-commit run --all-files, I get the following error:
[pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[ERROR] `detect_private_key` is not present in repository https://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.](url)

Are all pre-commit hooks not imported in the latest rev, or is there a specific rev for _detect_private_key_?

**Comment by asottile** [comment]
I'm guessing you closed this because the first hint in the error was correct: typo ?
