### ISSUE TITLE
Installing pre-commit automatically activates virtualenv

### ISSUE THREAD

**Issue by brandones** [pre-commit/pre-commit#1527]
This is a very surprising side effect. Very strange behavior. I expect pre-commit to manage my git hooks; nothing more, nothing less.

**Comment by asottile** [comment]
it doesn't do that, do you have an example?

**Comment by asottile** [comment]
in fact, it's impossible for _any_ executable to modify your shell environment (only shell functions)

**Comment by brandones** [comment]
Yep, yeah, not sure what happened yesterday. Sorry about that.
