### ISSUE TITLE
VS Code error: pre-commit not found.  Did you forget to activate your virtualenv?

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#1537]
Having the [same problem](https://github.com/pre-commit/pre-commit/issues/359#issuecomment-646562402) as @UrszulaCzerwinska in #359.

Trying to use the VS Code source control UI to commit in a project with `pre-commit@2.6.0`, I get the error

> Git: `pre-commit` not found.  Did you forget to activate your virtualenv?

![screenshot](https://user-images.githubusercontent.com/30958850/87763460-1f1bb780-c815-11ea-865f-666e93efb040.png)

**Comment by janosh** [comment]
Committing from terminal in the same project works fine.

**Comment by asottile** [comment]
can you provide more information?

- how did you install `pre-commit`
- where did you run `pre-commit install`
- what is the output of `grep ^INSTALL .git/hooks/pre-commit`
- what is the output of `which pre-commit`
- what is the version you're using
- what is the output of `head -1 $(which pre-commit)`

**Comment by asottile** [comment]
my guess (you haven't provided enough information) is you're using conda on windows -- there's a known issue with conda's packaging there: https://github.com/conda-forge/pre-commit-feedstock/issues/9

**Comment by janosh** [comment]
Here's the additional information:

- **Installation method**: `pip install pre-commit`
- **Installation location**: VS Code integrated terminal (`zsh`)
- `grep ^INSTALL .git/hooks/pre-commit`: `INSTALL_PYTHON = '/usr/local/Caskroom/miniconda/base/envs/thermo/bin/python'`
- `which pre-commit`: `/usr/local/Caskroom/miniconda/base/envs/default/bin/pre-commit`
- **version**: 2.6.0 (I did mention that)
- `head -1 $(which pre-commit)`: `#!/usr/local/Caskroom/miniconda/base/envs/default/bin/python`
- OS: macOS 10.15.6

Does that help?

I'm not sure it's relevant because I suspect the problem lies with VS Code not running `git` inside the activate conda environment. [I did report the problem there as well](https://github.com/microsoft/vscode-python/issues/10165#issuecomment-634550639) but no changes from them yet. I suspect there's not much `pre-commit` can do about it either but I thought I'd at least check.

**Comment by asottile** [comment]
though from that output it appears you ran `pre-commit install` using the `thermo` environment (which may not exist any more?) could you try re-running `pre-commit install` and seeing if the issue persists?

if you're on macos, I'd generally suggest `brew install pre-commit` over using conda

**Comment by janosh** [comment]
Wonderful, `pip uninstall pre-commit && brew install pre-commit` solved the issue.

That was easy. Should have thought of it myself. 🤦

**Comment by stefanbschneider** [comment]
Did not solve the problem for me, now I just get `No module named pre_commit` both in the terminal and in VSCode. I'm going back to installing it with pip...

**Comment by asottile** [comment]
you will need to rerun `pre-commit install` if you change the location of the pre-commit executable you're using

please don't grave dig 2 year old closed issues with unrelated problems -- open a new issue next time
