### ISSUE TITLE
Question: Is it possible to specify `--all-files` in config yaml

### ISSUE THREAD

**Issue by stevetarver** [pre-commit/pre-commit#1538]
I am trying to convert a project to use pre-commit as our standard merge gate in CI.

I would like to configure pre-commit to always run against all files so each developer sees results that CI will see and avoid edge cases where they have merged in a change that breaks the build. Ideally, they would commit, pre-commit run against all files, and they don't have to manually run with `--all-files`.

It looks like the `files` config item is a filter on top of changed files and not seeing a way to install hooks to always run all files.

Is there a trick to this, or is that not a supported use case?

really nice project, btw

**Comment by asottile** [comment]
there is intentionally not, the pre-commit hook is intended to be fast and non-noisy and running against all files always defeats those goals
