### ISSUE TITLE
make supported hooks cli-discoverable

### ISSUE THREAD

**Issue by blaggacao** [pre-commit/pre-commit#1541]
`pre-commit` does not have a converging design around the two commands:

- `pre-commit install`
- `pre-commit uninstall` 

(they simply default to 'commit' stage)

_That means `pre-commit install` does not converge to the declared hooks (either `default_stages` or `stages`). Likewise, `pre-commit unsinstall` does **only** uninstall 'commit' stage, unless the user specifies `-t` flag._

Add to the mix that supported hooks are not programatically discoverable through a well known interface.

The first circumstance makes it so abstract tooling, that is tasked with construing reproducible and converging environments and designed to work with arbitrary version of `pre-commit` has to deal with the following situation:

- an additional stage should be installed
- an old stage is not cleared should be uninstalled

The second circumstance makes it so those stages are not discoverable by such tooling.

Hence such tooling currently cannot do things like:

```console
ok=
for hook in $(pre-commit -hooks); do
    if [ $1 == $hook]; then ok=true; fi
done
[ $ok != true ] && exit 1
```

```console
for hook in $(pre-commit -hooks); do
    pre-commit uninstall -t $hook
done
```

It _can_ do:
```console
hooks="pre-commit pre-merge-commit pre-push prepare-commit-msg commit-msg post-checkout post-commit"
for hook in $hooks; do
    if [ $1 == $hook]; then ok=true; fi
done
[ $ok != true ] && exit 1
```

**But** this latter work around does not "grow" along with future `pre-commit` versions once they introduce a new hook.

Please don't force me to parse this: :pray: 
```
-t {pre-commit,pre-merge-commit,pre-push,prepare-commit-msg,commit-msg,post-commit,post-checkout}, --hook-type {pre-commit,pre-merge-commit,pre-push,prepare-commit-msg,commit-msg,post-commit,post-checkout}
```

**Comment by asottile** [comment]
I'm sorry, I don't understand your english at all, what are you asking for?

**Comment by blaggacao** [comment]
Oops, is it so bad? :wink: 

I'm asking for a command line option similar to
`pre-commit --available-hooks`
->
to output either
```
pre-commit pre-merge-commit pre-push prepare-commit-msg commit-msg post-checkout post-commit
```
or to output
```
pre-commit
pre-merge-commit
pre-push
prepare-commit-msg
commit-msg
post-checkout
post-commit
```

---

There are alternative solutions, but I assume those are out of consideration.

<details>

- `pre-commit install` would install all stages from `default_stages` instead of defaulting to 'commit'
- `pre-commit uninstall` would uninstall all _currently_ pre-commit installed stages.

</details>

**Comment by blaggacao** [comment]
For clarification, Iwouldn't be able to avoid help message parsing for current version.

But at least for future versions, additional hooks get discoverable and I can write future-proof code.

**Comment by blaggacao** [comment]
Can you perceive the intention behind this request? Please ask if I should further clarify...

For additional context https://github.com/cachix/pre-commit-hooks.nix/pull/52 might be involved, but helpful.

**Comment by asottile** [comment]
I'm not sure why you need this to be discoverable, the documentation includes the values people would expect to be able to find and pre-commit produces a readable error message when an unsupported stage is attempted -- can you not use this?

**Comment by blaggacao** [comment]
> can you not use this?

Well, I certainly _can_ check the documentation regularly for updates, but then live gets into the way, and the reality is I won't. I'm not even the maintainer of the traget repository for which I'm asking for this facility.

I'd prefer to be able to write future proof code.
```console
for hook in $(pre-commit -hooks); do
    pre-commit uninstall -t $hook
done
```


That is, unless, you'd agree as an alternative to modify `pre-commit uninstall` so that:
- it uninstalls all known hooks for pre-commit (certainly only, if said hook is identified as a pre-commit hook, only)

The latter change would make this reuest obsolete in the light of your suggestion to use error codes for the install phase, since the installing hooks are externally provided by the configuration file, which in turn is maintained by the user Jon Doe, Jon Doe should be considered required to check the documentation, indeed.

**Comment by asottile** [comment]
why not just pass through the argument, pre-commit does not (intentionally) have a programmatic interface and I'm not comfortable with the tooling and user experience you're creating

**Comment by blaggacao** [comment]
> pre-commit does not (intentionally) have a programmatic interface

Ah ok, that wasn't obvious. Thanks.

Still, I feel a little left in the rain \*, as for my options ...

> why not just pass through the argument

... or at least I don't understand what that means.

\* meanwhile I'll fetch my :umbrella: .

**Comment by blaggacao** [comment]
For clarification purpose, what I'm trying to do is to uninstall all _available_, but _unkown_ hooks, so that I can create a reproducible environment which just installing the _intended_ hooks.

- _available_ cause any given pre-commit version makes them available
- _unkown_ because I have no knowledge about the version previously, thus the _available_ hooks. For past hooks the state of the world is clear, for future hooks, I have missing information.
- _intended_ because the maintainer of the configuration intents to use certain hooks.

**Comment by asottile** [comment]
my suggestion is to not diverge from the UX, if you need to wrap `pre-commit install`, just pass along `--hook-type` / `-t` without modification.  you don't need to read the value.  you can react to the return value of the command.

pre-commit intentionally makes opting in and out an explicit action

**Comment by blaggacao** [comment]
I appreciate your suggestion, and, as I said above it does _indeed_ go half the way.

My remaining issue is with `pre-commit uninstall`.

I have not found way of knowing in a future proof way what hook I can possibly pass to:
`pre-commit uninstall -t <hook>`.

Does this clarify the quid of this issue?

**Comment by blaggacao** [comment]
> pre-commit intentionally makes opting in and out an explicit action

https://github.com/cachix/pre-commit-hooks.nix/pull/52#issuecomment-662081856

**Comment by blaggacao** [comment]
`pre-commit uninstall --all` ? would that be something you could become comfortable with? It would solve my problem neatly.
