### ISSUE TITLE
Latest version not compatible with Volta

### ISSUE THREAD

**Issue by dcramer** [pre-commit/pre-commit#1542]
Tested with 2.6.0. Downgrading to 2.2.0 works, so guessing something changed with how node hooks work between then and now.

```
[INFO] Installing environment for git://github.com/getsentry/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/dcramer/.volta/bin/npm', 'install', '-g', '.')
return code: 126
expected return code: 0
stdout: (none)
stderr:
    Volta error: Global package installs are not supported.

    Use `volta install .` to add a package to your toolchain (see `volta help install` for more info).

Check the log at /Users/dcramer/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
this is from 2.3.0: https://github.com/pre-commit/pre-commit/blob/master/CHANGELOG.md#230---2020-04-22

> Use `language_version: system` by default for `node` hooks if `node` / `npm` are globally installed. (#1388)

arguably `volta` is buggy here, it's not actually performing a `-g` install but one with a `npm_config_prefix`.

that said, you can use `language_version: latest` for node hooks to override the default

or 

```yaml
default_language_version:
    node: latest
```

to do it globally for all hooks
