### ISSUE TITLE
Allow git submodules as repos

### ISSUE THREAD

**Issue by pchanial** [pre-commit/pre-commit#1545]
I'll give some context. I am currently developping on a VM without internet connection, only intranet. So, from a VM with access to internet, I tried to create a git repo "all-pre-commit-hooks" in the intranet BitBucket, adding pre-commit repos such as seed-isort-config, black, etc. as git submodules. But that didn't work, the submodules are not treated in the same way as the git repos.
Maybe there's a better solution ? (other than cloning all the hook repos and cluttering the number of repos in our project)

**Comment by asottile** [comment]
can you share what you've tried so far and your outputs and versions, etc.?  I don't have much to go off of other than your assertions so I can't see what you've tried.  It should work fine as this setup is very similar to how our test suite executes

**Comment by pchanial** [comment]
I created a repo in gihub https://github.com/pchanial/test_precommit in which I have added some hooks as git submodules.

When I set the repo fields to a local git submodules, it works (except for the black hook, which specifies a branch (stable) for 'rev' and not a commit)

I have also tried to use as a repo value, for example https://github.com/pchanial/test_precommit/seed-isort-config
but it is not recognized.

I also tried to point at https://raw.githubusercontent.com/pchanial/test_precommit/master/black
but that also fails. Anyways, I can use the local repo, but I would have preferred not to have to check it out.
So, that's probably more a github api issue. You can close this issue.

**Comment by asottile** [comment]
oh sure of course, the value of `repo` needs to be something you can clone, you can't clone a submodule that's part of a repo (it's not actually a real repository to the git protocol, just a special file in a repository)

if you add that repo as a submodule though you can access `repo: that-submodule/black` (but I don't see the point?).  are you trying to freeze the versions? you may want to look at `pre-commit autoupdate --freeze`?

**Comment by asottile** [comment]
@pchanial does that make sense?
