### ISSUE TITLE
Cannot use v2.6.0 - says no such tag

### ISSUE THREAD

**Issue by lanshark** [pre-commit/pre-commit#1548]
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', 'v2.5.1')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v2.5.1' did not match any file(s) known to git
    
Check the log at /home/ubuntu/.cache/pre-commit/pre-commit.log

**Comment by asottile** [comment]
can you share your configuration?  v2.5.1 of what exactly?

**Comment by lanshark** [comment]
Sorry, of pre-commit:  Config is:

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.6.0
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

Python 3.7 is 3.7.7 installed using pyenv, and it is working.  Running python3.7 from command line works.  I have tried both 2.5.1 and 2.6.0, same error.  2.5.0 works.

-Scott

**Comment by lanshark** [comment]
Also, I have 2.6.0 installed, and pre-commit sample-config creates a sample with 2.4.0 as the version, FYI

**Comment by asottile** [comment]
ah you're confusing the versions of `pre-commit` (the framework) and `pre-commit-hooks` (a set of hooks built for `pre-commit`) -- pre-commit-hooks is versioned separately and you can see the released versions here: https://github.com/pre-commit/pre-commit-hooks/releases

note that it's usually easier to just run `pre-commit autoupdate` and that will pick the proper versions for you

**Comment by lanshark** [comment]
AH - should have picked that up... never mind!

-Scott
