### ISSUE TITLE
install_requires should fix dependencies to specific versions

### ISSUE THREAD

**Issue by svisser** [pre-commit/pre-commit#155]
The `install_requires` value in `setup.py` does not specify the exact versions (`dependency==0.1.0`) and / or version bounds (`dependency<=0.2`). This means that someone could install this project a year from now and it may not work because a dependency could have introduced a backwards incompatible change. It's therefore better to specify the versions and upgrade them yourself when you've verified that a newer version of a dependency works fine with this project.

**Comment by asottile** [comment]
closing as wontfix, we haven't really had any problems with this and the packages we're depending on are pretty stable
