### ISSUE TITLE
Windows. UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by bamesserly** [pre-commit/pre-commit#1550]
Windows 10. python 3.7.3. Here are the exact powershell commands:
```
pip install pre-commit
pre-commit sample-config > .pre-commit-config.yaml
git commit -m "Test" README.md
```

which gives me the error + attached log
```
An unexpected error has occurred: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

[pre-commit.log](https://github.com/pre-commit/pre-commit/files/4983937/pre-commit.log)

**Comment by asottile** [comment]
looks like your terminal is not writing UTF-8 bytes, perhaps make sure that the configuration is encoded using UTF-8?

**Comment by bamesserly** [comment]
Yikes. That seems to have been the issue.

I replaced this:
```
pre-commit sample-config > .pre-commit-config.yaml
```
with this
```
pre-commit sample-config | out-file .pre-commit-config.yaml -encoding utf8
```

Chalk this one up to being new to powershell.

**Comment by asottile** [comment]
awesome! glad we got this one figured out!

**Comment by asottile** [comment]
I'm making this error more apparent here: https://github.com/asottile/cfgv/pull/30

**Comment by Greedquest** [comment]
Just tried this with latest version of this repo; I think the error messaging could be more clear:

```
> pre-commit.exe sample-config > .pre-commit-config.yaml
> pre-commit-validate-config
> pre-commit install
pre-commit installed at .git\hooks\pre-commit
> pre-commit autoupdate
An unexpected error has occurred: ReaderError: unacceptable character #x0000: control characters are not allowed
  in "<unicode string>", position 5
```
