### ISSUE TITLE
setup.cfg is not being read for pydocstyle

### ISSUE THREAD

**Issue by kidrahahjo** [pre-commit/pre-commit#1552]
The `setup.cfg` contains the below mentioned code but still the directories which were supposed to get skipped are being tested for style:
This works fine with `flake8` but it's failing for `pydocstyle`
```
[pydocstyle]
match-dir = ^((?!doc|tests).)*$
ignore = D105, D107, D203, D204, D213
```
This is the hook I used (I also tried using a look hook but it didn't work).
```
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
```

**Comment by asottile** [comment]
pre-commit just [passes through arguments](https://pre-commit.com/#arguments-pattern-in-hooks) to pycodestyle, so it's probably pycodestyle ignoring the `match-dir` setting

**Comment by asottile** [comment]
you're probably best to use `pre-commit`'s [`exclude`](https://pre-commit.com/#config-exclude) / [`files`](https://pre-commit.com/#config-files) settings to filter the arguments passed to the underlying tools

**Comment by kidrahahjo** [comment]
@asottile 
This is working as expected for me when I execute the command: `pydocstyle .`. 
I am not sure why it's failing here.
Isn't there a centralized way for passing the arguments?

**Comment by asottile** [comment]
@kidrahahjo please read the link above, pre-commit will not execute `pycodestyle .` but `pycodestyle file1.py file2.py file3.py`

**Comment by kidrahahjo** [comment]
Okay, got it.
Thanks @asottile for responding thus far.
