### ISSUE TITLE
autoupdate downgrades isort 5.3.2 to 5.3.0

### ISSUE THREAD

**Issue by hugovk** [pre-commit/pre-commit#1555]
isort 5.3.0 was released two days ago.

isort 5.3.1 and 5.3.2 were released an hour ago.

* https://github.com/timothycrosley/isort/releases

For some reason pre-commit is autoupdating 5.3.2 (and versions < 5.3.0) to 5.3.0 and ignoring the latest patch releases:

```console
$ python --version
Python 3.8.3
$ pre-commit --version
pre-commit 2.6.0
$ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.3.2
    hooks:
      - id: isort
$ pre-commit autoupdate
Updating https://github.com/timothycrosley/isort ... updating 5.3.2 -> 5.3.0.
$ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.3.0
    hooks:
      - id: isort
```

Similarly on CI:

* https://travis-ci.org/github/hugovk/test/jobs/715777034

I can manually edit the file, but not so easily for a file using hashes frozen by  `--freeze`.

**Comment by asottile** [comment]
yeah, isort doesn't tag their default branch or merge their tags into the default branch for some reason

`pre-commit autoupdate` picks the latest tag on the main branch

**Comment by hugovk** [comment]
Thanks, I'll open an issue at isort.
