### ISSUE TITLE
ModuleNotFoundError for pre_commit_hooks when setting PYTHONPATH to project root

### ISSUE THREAD

**Issue by woutervdbekerom** [pre-commit/pre-commit#1559]
I'm running pre-commit on Windows 10 and have set PYTHONPATH to the root of my project. I'm using conda and my pre-commit hooks are installed with python from the base env. When I try to run my hooks I get the following import errors for all `pre_commit_hooks` hooks:

```
(base) PS C:\Users\wouter\OBELIX\engineering-codebase> pre-commit run
Fix double quoted strings............................(no files to check)Skipped
Check for added large files..........................(no files to check)Skipped
Check python ast.....................................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\wouter\scoop\apps\miniconda3\current\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\wouter\scoop\apps\miniconda3\current\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wouter\.cache\pre-commit\repo6_ztvn4d\py_env-default\Scripts\no-commit-to-branch.EXE\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pre_commit_hooks.no_commit_to_branch'
```

When I unset my PYTHONPATH or set it to somewhere else all is fine. Checked this in both Powershell and Git-bash and behavior is the same. As far as I understand pre-commit is supposed to run in an isolated env and hence should not care about this PYTHONPATH since it should not be set in the virtualenv?

Note that my `autopep8` and `mypy` hooks run without an issue, the failing import only occur for `pre_commit_hooks` hooks. Also tried installing with my conda env activated but this does not change anything. Any thought on what is happening and how it can be tackled?

Some possibly useful info:
Python executable used by hooks: `C:\Users\wouter\scoop\apps\miniconda3\current\python.exe`

Versions used:
```powershell
python -V # Python 3.7.4
conda -V # conda 4.8.4
pre-commit -V # pre-commit 2.6.0
```

**Comment by asottile** [comment]
setting `PYTHONPATH` [is almost always the wrong thing to do](https://github.com/asottile/scratch/wiki/PythonPathSadness), but can you `ls -al` in your working directory?  I suspect you have a `pre_commit_hooks` directory hanging out there which is clobbering the namespace in the pre-commit virtual environment

we could unset `PYTHONPATH` in the `python` language, but I suspect people are (ab)using this to do plugin-y things

**Comment by woutervdbekerom** [comment]
Ashamed to say there was indeed a folder named `pre_commit_hooks` in the project root. Renamed that one and all is working fine again :)

Thanks @asottile for the fast support, much appreciated!
