### ISSUE TITLE
Use case for `require_serial: false` 

### ISSUE THREAD

**Issue by xinbinhuang** [pre-commit/pre-commit#1563]
Hi team,

I noticed that some of my frequently used hooks (e.g. flake8, black, mypy) set `require_serial: true`. In fact, when I tried to set `require_serial: false`, it seems to be slower and it actually blows up my CI environment when running `mypy`.

So I am curious about in what situation (what type of workloads?) should I actually set `require_serial: false` and it's beneficial.

Any suggestions would be much appreciated!

Thanks
Bin

**Comment by asottile** [comment]
some hooks implement their own multiprocessing internally and so it is best to `require_serial: false` for them
