### ISSUE TITLE
Add perforce support?

### ISSUE THREAD

**Issue by petemounce** [pre-commit/pre-commit#1579]
(I appreciate this is very likely to be a "no", but I thought I'd ask, in case it's a "yes", or a "yes, but please DIY in a PR").)

I work with a number of teams (games studios) that use perforce, rather than git, to source control their work. It would be really useful to be able to wire up pre-commit in a similar way for those teams as is possible for git-using teams.

One of the things we've done to enable them to have better workflows is integrated perforce with buildkite CI via https://github.com/improbable-eng/perforce-buildkite-plugin/ - an integration with pre-commit would allow us to shift-left some of those checks in the pipeline so they happen ahead of triggering CI. Since games CI tends toward the more time-consuming end of the scale, this would be a pretty big win for us in terms of static analysis preventing waste.

So, I was wondering whether this might be possible to add, or whether you would welcome a PR that adds it? 

I'd been thinking incrementally... The sorts of things we do with pre-commit are:

* in-CI incremental linting on branches as a pre-merge gate
    * so, `run --from-ref $(git ... fork-point) --to-ref HEAD`
* `run {linter} --all-files` when introducing a new hook, to fix as much as possible before making it a pre-merge gate
* on-workstation incremental-linting as a pre-push
    * understanding how to get a list of changed files
    * figure out the semantics between `git stash` and perforce's closest equivalent (files being added to a changelist / shelfset)
* ... the above, automatically
    * so, `install`, but the perforce equivalent if one exists for pre-commit/push

Later, things like `pre-commit` during commits/merges/commit-messages; we don't use those features today.

If a PR is welcome, any guidance that you might share to enable us would be very gratefully received.

Regarding testing - I'd been thinking in terms of a containerised p4d (https://github.com/ambakshi/docker-perforce exists and I'd have started there) and then making the assumption that the existing test-suite must pass against that...?

Regarding delivery - I haven't thought too much about this, but in the event it's a large change, I'd been hoping it might be possible to split up into smaller logical pieces that are easier to iterate on and review, that can sit behind some flag or env-var feature-flag until it's in a stable state.

What do you think?

**Comment by asottile** [comment]
pre-commit is pretty intimately tied to git, but you could already do this today using `git-p4` without needing pre-commit to have understanding of perforce internals (similar to how `git-remote-hg` repos are supported)

similar to https://github.com/pre-commit/pre-commit/issues/160, I don't have any interest in implementing or maintaining this but a well tested PR would be accepted.

**Comment by guykisel** [comment]
unfortunately the p4 server i'm currently working with dates back to 2018 and doesn't respond to `p4 help clientextensionintro` but i'm hoping to get a newer p4 server set up locally for some experimentation.

**Comment by guykisel** [comment]
ah here we go, a bit of docs:

    Introduction to Helix Core Client Extensions (Technical Preview)

        Client-side extensions are a means for customizing parts of
        Helix Core clients with user-supplied logic.

        Helix Core clients run Extensions natively without relying on
        external processes, providing a portable runtime and versioned
        programmatic API.  Extensions are written in the Lua language,
        version 5.3.  There are two types of client-side Extension:
        loose Extensions and packaged Extensions.  A loose Extension
        is a bare script source file, and a packaged Extension is a
        package of content - a manifest, source code, assets, etc all
        packaged up in a '.p4-extension' file.

        The P4EXTENSIONS environmental variable enables client-side
        Extensions.  The value of this variable specifies a file
        pattern the client program uses when searching the client
        filesystem for Extensions.  When executing a command, the
        client program load the P4EXTENSIONS variable, and like
        P4CONFIG, uses the current working directory as its starting
        point and moves its way to the root of the tree in search of
        file matches, keeping any that it encounters.  Unlike
        P4CONFIG, P4EXTENSIONS does not specify a literal file name.
        To leave room in the future for the existence of multiple
        scripting options, P4EXTENSIONS only specifies a filename
        prefix.  Of files that match the prefix, there must be a
        matching suffix in the form of '.version.language'.  E.g. if
        P4EXTENSIONS is set to 'p4script', a matching file would be
        named 'p4script-example.53.lua', where the '53' is the '5.3'
        of the bundled version of Lua.  Currently the only supported
        script type is 'lua' (case-sensitive) and the version is '53'.
        These two fields in the file name are to give the client a
        hint about what interpreter to load when running the loose
        Extension since they don't have a manifest file to declare
        those details.  P4EXTENSIONS may point to an absolute path, in
        which case the client does not search outside of the specified
        directory.

        Client-side Extensions can be disabled either by removing the
        P4EXTENSIONS variable from the environment, or by using the
        --no-script global flag.

        Client-side Extensions are run before and after command
        execution (pre/post hooks).

        Certain commands can not be handled with Extensions.  E.g. 'p4 trust'
        and 'p4 transmit'.

        The --script flag runs the named script file and exits.  The
        script is not an Extension here, but rather just a normal
        program being run for its side effects.

        Refer to the online documentation for instructions on creating
        Extensions.  Server-side Extensions are largely the same, but
        have additional APIs.  Note that for client-side Extensions,
        that the server-side help may not reflect client program
        capabilities if the versions don't match.
