### ISSUE TITLE
Ability to specify latest sha in config yaml

### ISSUE THREAD

**Issue by dfarr** [pre-commit/pre-commit#158]

**Comment by asottile** [comment]
The sentiment in the comment above is still true, however instead of using named directories / symlinks we're now keeping track of the installed hooks using sqlite.

**Comment by gretel** [comment]
have this in the `README` would certainly help. spend about an hour figuring - and yes, i've read the docs.

**Comment by asottile** [comment]
I've documented this [here](http://pre-commit.com/#using-the-latest-sha-for-a-repository).  Going to close this for now.
