### ISSUE TITLE
what is the solution to not being able to install setoolkit

### ISSUE THREAD

**Issue by rudixxjayescore** [pre-commit/pre-commit#1582]
abyzarhack@DESKTOP-NP96F6T:~$ git clone https://github.com/trustedsec/social-engineer-toolkit/ setoolkit/
Cloning into 'setoolkit'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by asottile** [comment]
sorry, this isn't a general support forum for git problems -- closing since this has nothing to do with `pre-commit`
