### ISSUE TITLE
Wrong shebang line generated for my setyp (Windows10 + pyenv-win + pre-commit installed in virtual env)

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [pre-commit/pre-commit#1583]
pre-commit generates the following shebang in the hook:
```
#!/usr/bin/env python.exe
```
It works when I have a virtual env activated, but not outside because I install python with [pyenv-win](https://github.com/pyenv-win/pyenv-win) that makes python accessible through a `python` shim installed in `%USERPROFILE%\.pyenv\pyenv-win\shims\python`.

Right now my workaround is to edit manually the hook and replace "python.exe" with "python". I don't want to change my PATH to have "python.exe" accessible from it because I may change the global python I use with pyenv and I would have to remember to update my PATH in that case.

Is there a command line argument to specify the command to use in the shebang ? (I don't see any  with `pre-commit --help` or `pre-commit install --help`). If not do you think it would be a good idea to offer such option ?

**Comment by asottile** [comment]
on windows the only reasonable choice is `os.path.basename(sys.executable)` (which, for your setup, happens to be `python.exe`)

I don't think there's really any improvement that can be done here without breaking the rest of the windows usecases (notably, `shims\python` isn't a valid windows executable, it would need an extension such as `.exe` or `.bat`, etc. so we can't use `python`, `pythonX.X`, etc. on windows).  an older version of pre-commit used to attempt to discover pythons in that way but broke spectacularly when (for instance) bundled executables named `python2.7` (which is a ".7" file and not executable on windows!) were on the `PATH`.

I can't remember why `.exe` was important (or maybe it isn't?) -- perhaps you could try a patch and see if removing the extension there still passes the testsuite?

**Comment by Celeborn2BeAlive** [comment]
Yes I agree with you, the default obtained with `os.path.basename(sys.executable)` is totally fine and I don't expect `pre-commit` trying too hard to guess what python command it should put in the shebang. As you mentionned it would be hard to support all usecases.

That's why I was wondering if you might consider adding a CLI argument so it can be overidden, for example:
```
pre-commit install --shebang-cmd="python"
```

**Comment by asottile** [comment]
I don't want an option, can you try and see whether it just works by dropping the extension?

**Comment by Celeborn2BeAlive** [comment]
Sure I'll try today to run the tests on a version where I drop the extension.

Another thing I just tried manually: replacing "python.exe" with the full path to the python, that would be obtained by `sys.executable`.  In my case the shebang becomes:
```
#!/usr/bin/env C:\\Users\\laure\\.pyenv\\pyenv-win\\versions\\3.7.9\\python.exe
```
With this my commits work (tried in git bash console and in cmd console). What do you think about this one ?

**Comment by asottile** [comment]
the problem with that is that executable often points at a virtualenv which can go missing (most of the git hook script is trying to re-discover a suitable pre-commit executable)

**Comment by asottile** [comment]
@Celeborn2BeAlive did you get a chance to try out the idea of stripping extension?

**Comment by Celeborn2BeAlive** [comment]
@asottile Yes, sorry for the delay, I was quite busy these last few days.

Here is what I did:

First I ran the test suite on master (f511afe40e3f0ea7474d37f19c69741d3e167876) by following the instructions of CONTRIBUTING.md (create the dev venv with tox, activate it, then ran `pytest tests`) to get a reference.

On my setup I have several tests that fail out of the box, but I guess it is normal, I did not inspect too much but these are tests like "tests_conda_hook", "test_golang_hook", ... I noticed from your Azure Pipeline that you install several tools first for these tests. Here is the detailed output of this first run: https://pastebin.com/3KA0D2GP

Then I changed `install_uninstall.py:58` to remove the extension of `SYS_EXE` (https://github.com/Celeborn2BeAlive/pre-commit/tree/1583-wrong-shebang-line-win10-pyenvwin) and ran the test suite again. I have one more test that fails which is `install_uninstall_test.py::test_shebang_windows`  and it seems normal since it explicitely test for `python.exe` being in the shebang line. I'm sending you a PR to run the test pipeline in the correct environment see if other tests are passing.

I've also made some manual testing: I've removed my pyenv-win shims from my PATH and added a path containing "python.exe" only. It seems to work with the pre-commit hook generated from my modified version.

**Comment by Celeborn2BeAlive** [comment]
Ok [the pipeline finished](https://asottile.visualstudio.com/asottile/_build/results?buildId=4378&view=logs&j=94d9d3b4-8e3d-5cdc-d6c7-40ce0e4fea69) and the only test that fail is `test_shebang_windows`. I'm updating the pull request with updated tests.
