### ISSUE TITLE
Cached environments never change even if the rev they point to changes

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [pre-commit/pre-commit#1587]
Consider the following YAML fragment:

```repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
```

Whatever version the stable tag was pointing to at creation will be cached and will be used thereafter even if the stable tag moves forward leading to some head scratching until the environment cache is cleaned.

**Comment by asottile** [comment]
https://pre-commit.com/#using-the-latest-version-for-a-repository

**Comment by asottile** [comment]
this is correct, intentional -- don't use mutable references
