### ISSUE TITLE
Hook installs an ancient version of black

### ISSUE THREAD

**Issue by joshtemple** [pre-commit/pre-commit#1593]
When I run `pre-commit run -v` for my `black` hook, I see the following output:

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/joshuat/.cache/pre-commit/patch1599590125.
black....................................................................Passed
- hook id: black
- duration: 0.22s

black, version 0.1.dev1+g2354126
```

Here's the config file.

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        args: [--version]
```

Why isn't pre-commit installing the correct version of Black? I've tried running `pre-commit clean` and reinstalling, but it still shows the old version.

**Comment by asottile** [comment]
the version is bogus, this is due to `setuptools-scm` not knowing what's up

**Comment by asottile** [comment]
(it's actually 20.8b1, you can verify using the `--help` and checking for the new options)

**Comment by asottile** [comment]
also that the `g` version matches the tag: https://github.com/psf/black/releases/tag/20.8b1
