### ISSUE TITLE
Running pre-commit from venv in a docker created by an user script

### ISSUE THREAD

**Issue by sar772004** [pre-commit/pre-commit#1594]
Hi,
This is more of a question i have not found an answer to yet.

Can anyone answer this use case ?
Use case:
Running pre-commit from venv in a docker created by an user script

Example, 
build_docker.py --docker-name xyz    # creates the docker name "xyz" with the git repo mounted
Then I would like to make a pre commit hook to call this script , exec the pre-commit yaml in the docker xyz under a given venv and return status on every 'git commit' operation.

Thanks
Srini

**Comment by asottile** [comment]
`PRE_COMMIT_HOME` is designed for this

generally you need to:

1. build a docker image with your base software
2. copy the `.pre-commit-config.yaml` into the image
3. `pre-commit install-hooks` (with the `PRE_COMMIT_HOME` set)

and then things will be reused without needing to rebuild


though generally, pre-commit works best on the host machine without needing to involve docker (docker is going to add a few seconds to every call anyway)
