### ISSUE TITLE
pre-commit run --all --show-diff-on-failure reverts changes

### ISSUE THREAD

**Issue by iwkse** [pre-commit/pre-commit#1596]
Hi,
possibly I'm missing something but I didn't find a better place to submit that.

When I run the pre-commit run and I fix some errors, than I try it again, the files changed are reverted to the original state.
How can I avoid that?

**Comment by asottile** [comment]
can you show your output? that isn't how pre-commit works

**Comment by iwkse** [comment]
So the issue was with black adding a space and flake8 removing it!
