### ISSUE TITLE
Mercurial support

### ISSUE THREAD

**Issue by hermanocabral** [pre-commit/pre-commit#160]
Howdy,

Do you have any plans to support mercurial (hg)? I'd be happy to send a PR for this.

Thanks

**Comment by asottile** [comment]
I believe hook repositories can already be supported by using `git-remote-hg` and repo urls that look like `'hg::...'`.

**Comment by bartekbrak** [comment]
I'd love this so much (as much as I don't like being made to work with hg). I guess there isn't much interest.

**Comment by asottile** [comment]
I think this would actually be pretty easy to implement (or at least get the minimal bits working to support at least running hooks).  I wish I knew slightly more about `hg` and I'd tackle it myself.

I think most of it can be isolated to version-control-specific modules that interact with the underlying VCS, detect which VCS at startup time and use it.   Then it'd be easy to add any VCS that supports hooks similar to git.

**Comment by asottile** [comment]
I don't have any plans to tackle this -- as such I'm going to close this issue for now.  A PR would be welcome for this feature.
