### ISSUE TITLE
installing with shiv: No module named pre_commit

### ISSUE THREAD

**Issue by diefans** [pre-commit/pre-commit#1602]
I want to keep my project venv clean from tools and helpers like pre-commit.

For that reason I tried installing pre-commit via. shiv:
```
shiv pre-commit virtualenv -E -o ~/.shiv/bin/pre-commit -c pre-commit -p "/home/olli/.pyenv/versions/3.8.5/bin/python"
```
When I run `git commit` I get the following error:
```
/home/olli/.pyenv/versions/3.8.5/bin/python: No module named pre_commit
```
which is due to the fact, that the installed hook is a python script generated by the shiv zipapp, which puts its executable into the `INSTALL_PYTHON` attribute and assumes that the `pre_commit` module is contained in its venv (which is not) and tries to execute "itself" via `python -mpre_commit`. 

IMHO the hook shoud execute `~/.shiv/bin/pre-commit` directly and not via `python -m<module>`

**Comment by asottile** [comment]
this is a bug with shiv, not pre-commit
