### ISSUE TITLE
Pass environment variable to hook, define in .pre-commit-config.yaml

### ISSUE THREAD

**Issue by christian-steinmeyer** [pre-commit/pre-commit#1609]
Given the following `.pre-commit-config.yaml`:

```yaml
-   repo: https://github.com/some/repo
    hooks:
    -   id: my-hook
        args: ["-t", "$ENVIRONMENT_VARIABLE"]
```
and assuming my hook expects an argument like "-t some_string" as well as I have an existing environment variable `ENVIRONMENT_VARIABLE`, how can I use that variable in my config? The above approach unfortunately does not work. I saw, that I could call the script manually instead (as hinted at in the [docs](https://pre-commit.com/#arguments-pattern-in-hooks)), however that kind of defeats the purpose?

#### To give you a little bit of background:

I have a gitlab-ci template repository consisting of many gitlab-ci yaml files, using (possibly nested) includes. Now I want to create a gitlab-ci file for that repository, checking all repository files for validity against the [gitlab included CI lint tool](https://docs.gitlab.com/ee/ci/lint.html) ([API](https://docs.gitlab.com/ee/api/lint.html)). I have a python script that does just that and created a pre-commit hook from that. 

However, as part of the linting, gitlab requires access to repos (when using the [include](https://docs.gitlab.com/ee/ci/yaml/includes.html) tag, which can be solved via an access token, passed as an argument to my script. Of course, I don't want to write it to the `.pre-commit-config.yaml` in plain text (which works fine, when run locally). Thus my idea with the environment variable.

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit/issues/758#issuecomment-404554291
