### ISSUE TITLE
Can't use ruby 2.7.1 on MacOS

### ISSUE THREAD

**Issue by tdeo** [pre-commit/pre-commit#1612]
Hi, 

Bumping my ruby hooks to version 2.7.1 worked fine for me on Ubuntu but doesn't work for my colleagues using MacOS, is there something to do about bumping rbenv archives ? 

Thanks

**Comment by asottile** [comment]
"doesn't work" isn't a bug report, show me commands, outputs, configuration, etc.

**Comment by tdeo** [comment]
Ping @gterral

**Comment by tdeo** [comment]
I was actually asking if there is a "process" for the introduction of new ruby versions since there are bundled `ruby-build`, `ruby-download` and `rbenv` tar archives versioned in this repo : https://github.com/pre-commit/pre-commit/tree/master/pre_commit/resources

**Comment by asottile** [comment]
for prebuilts it's usually just automatic as rvm.io adds them, for building-from-source the rbenv archive is updated using the scripts

note also that there's a third option now, `language_version: system` (the default if both `ruby` and `gem` exist) which'll reuse the system `gem` / `ruby` binaries but install in an isolated environment
