### ISSUE TITLE
Improve documentation on files/exclude pattern

### ISSUE THREAD

**Issue by touilleMan** [pre-commit/pre-commit#1619]
Current documentation doesn't explain against what the pattern is applied:

files | (optional: default '') global file include pattern.  new in 1.21.0.
-- | --
exclude | (optional: default ^$) global file exclude pattern.  new in 1.1.0.

The name `file pattern` in the explanation makes you think the check is done against a file name (i.e. `foo.txt` and not `spam/bar/foo.txt`)

Looking into the codebase, it seems `git ls-files` is used as input for the filter, so we end up with path relative to the root of the git repository. I think it would be much better to add this information to the documentation ;-)

**Comment by asottile** [comment]
feel free to send a patch if you think you can improve things but I don't think people are having the same misconception you are having (especially when there are [examples showing otherwise](https://pre-commit.com/#regular-expressions))

**Comment by ut-adamc** [comment]
The docs definitely need to be much more precise.
