### ISSUE TITLE
Running on new files and changed files

### ISSUE THREAD

**Issue by simonweil** [pre-commit/pre-commit#1620]
Hi
And thank you for a great and helpful project!

I'm trying to find how to run checks on files before staging or add them but can't seem to find how.
Is it possible? maybe some workaround to run on changed/new files?

Thanks!

**Comment by MarcoGorelli** [comment]
If you've installed pre-commit (`pre-commit install`), then when you do `git commit` it'll run on changed / new files

**Comment by simonweil** [comment]
True, I'm actually trying to run it also before I commit, just on the files I've changed or added without first adding the files.

I can run with `run - a` but it only applies to files staged or commited

**Comment by asottile** [comment]
See [`pre-commit run`](https://pre-commit.com/#pre-commit-run) in the docs:

> `pre-commit run`: this is what pre-commit runs by default when committing. This will run all hooks against currently staged files.
> `pre-commit run --all-files`: run all the hooks against all the files. This is a useful invocation if you are using pre-commit in CI.

**Comment by simonweil** [comment]
Then I understand correctly that it's not possible to run on files that are yet unknown to git or changes that are not yet staged.
Thanks for the answer and this great project!
