### ISSUE TITLE
Pre-commit on merge

### ISSUE THREAD

**Issue by sodrian** [pre-commit/pre-commit#1622]
Hey,

What is the best way to check merged files from another branch? I tried using this approach:

`git merge BRANCH --no-ff --no-commit`
`pre-commit run`

but had no luck, because pre-commit treats these files as merged, not committed ones.

**Comment by asottile** [comment]
you might be able to use `--files` to do what you want?  by default merged files are ignored (unless there's a non-trivial conflict resolution) [to avoid a bunch of unnecessary work on merge conflicts](https://pre-commit.com/#pre-commit-during-merges)

a *guess* would be `pre-commit run --files $(git diff --name-only HEAD)`

**Comment by sodrian** [comment]
Yeah, I believe your replied solved my issue, thanks. The final call for me is:

`pre-commit run --files $(git diff --name-only --staged)`
