### ISSUE TITLE
Q: Running precommit against added and deleted files only

### ISSUE THREAD

**Issue by ryan-dyer-sp** [pre-commit/pre-commit#1625]
I'd like to create a precommit hook for a workflow which for example purpose is just creating a manifest file of the files in the repo.  As such this really only needs to be ran when files are added and deleted from the repo, not when they experience content changes.  Is this something the framework supports or would the script need to handle the check?

Thanks

**Comment by asottile** [comment]
the script would need to handle that -- you can (for example) take a look at how [check-added-large-files](https://github.com/pre-commit/pre-commit-hooks/blob/5bd9e74adfb59d8e14c8a88c36511eb60c59b36e/pre_commit_hooks/util.py#L11-L13) works

note that `pre-commit` skips deleted files intentionally so you'll likely need to make your hook use [`always_run: true`](https://pre-commit.com/#hooks-always_run) and perhaps [`pass_filenames: false`](https://pre-commit.com/#hooks-pass_filenames)
