### ISSUE TITLE
Can't run pre-commit as a module.

### ISSUE THREAD

**Issue by hadialqattan** [pre-commit/pre-commit#1627]
Can't run `pre-commit` as a module.

pre-commit version: 2.7.1.
Python version: 3.8.
OS: Ubuntu 20.x.

```console
$ python3 -m pip install pre-commit
... already installed!
$ python3 -m pre-commit
/usr/bin/python3: No module named pre-commit
```

**Comment by hadialqattan** [comment]
I can solve this problem, if you want, assign it to me.

**Comment by asottile** [comment]
the module is named `pre_commit` as python modules are named

**Comment by Enprogames** [comment]
Well that was infuriating, but thanks.
