### ISSUE TITLE
 RuntimeError: no .dist-info has pip

### ISSUE THREAD

**Issue by nautatva** [pre-commit/pre-commit#1628]
Can someone help me with this error, trying to setup up pre-commit hooks

Using Python 3.8 (virtual environment), tried with pip 20.1.1 as well as pip 20.2.3. The error says .dist-info not found, I checked out the particular directory, that indeed is the case.
![image](https://user-images.githubusercontent.com/28155271/95292602-669f6600-088f-11eb-875c-0f2882a78379.png)

Any ups on what should I do now?
Additionally, I can use pip globally as well. Created venv using `python3 -m venv env`

```
(env) D:\Mac\Sites\project-reconnaissance>git commit -m "some message here"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\cool dude\.cache\pre-commit\patch1602049156.
[INFO] Installing environment for https://github.com/timothycrosley/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from C:\Users\cool dude\.cache\pre-commit\patch1602049156.
An unexpected error has occurred: CalledProcessError: command: ('d:\\mac\\sites\\project-reconnaissance\\env\\scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\cool dude\\.cache\\pre-commit\\repowq_8m7xu\\py_env-python3.8', '-p', 'd:\\mac\\sites\\project-reconnaissance\\env\\scripts\\python.exe')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image pip because:
    Traceback (most recent call last):
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 58, in 
_install
        installer.install(creator.interpreter.version_info)
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 46, in install
        for name, module in self._console_scripts.items():
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 116, in _console_scripts
        entry_points = self._dist_info / "entry_points.txt"
      File "d:\mac\sites\project-reconnaissance\env\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 103, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at C:\Users\cool dude\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any, has pip
```

**Comment by asottile** [comment]
this is a bug in virtualenv, I'd suggest reporting there: https://github.com/pypa/virtualenv/issues

**Comment by jdsalaro** [comment]
Leaving a comment here for reference as the conversation on the PyPa issue has been limited to collaborators https://github.com/pypa/virtualenv/issues/1971

This can also be due to an improperly initialized `/wheel` directory, allegedly by `virtualenv` or `pipenv`, as I've documented in https://jdsalaro.com/howto/fix-pipenv-runtimeerror-no-dist-info-has-pip 

It suffices to remove the wheel directory for that minor Python version and letting `virtualenv` or `pipenv` re-create it during the preparation of a new virtual environment for that minor version.

**Comment by asottile** [comment]
@jdsalaro this is off topic here -- please don't
