### ISSUE TITLE
[Request] Adding a python version option.

### ISSUE THREAD

**Issue by hadialqattan** [pre-commit/pre-commit#1629]
I think it would be great if we have an option to specify the Python version which runs pre-commit when `git commit`.

I know that we can run pre-commit with something like:
```bash
$ python3.8 -m pre_commit run --all-files
```
But when I do a `git commit` it runs on the default Python3.

**Comment by hadialqattan** [comment]
I know that we can change the default Python3.

**Comment by hadialqattan** [comment]
It would be great if we can customize the pre-commit installation with a Python version [python3 remains the default].

**Comment by asottile** [comment]
it uses whatever you've configured using [`language_version`](https://pre-commit.com/#config-language_version) or [`default_language_version`](https://pre-commit.com/#top_level-default_language_version) falling back to whatever executable you used when you ran `pre-commit install`

all the knobs are there -- use them!

**Comment by asottile** [comment]
also, you've got a classic case of [XY Problem](http://xyproblem.info/) -- describe your actual issue instead of a solution because I think you're misdiagnosing whatever actual issue you're having.
