### ISSUE TITLE
Force re-installation of commit hooks

### ISSUE THREAD

**Issue by archoversight** [pre-commit/pre-commit#1630]
It would be nice if there was a way to force re-creation of all of the environments, so that changes may be picked up when using a branch name as a revision rather than a tag/sha1.

**Comment by asottile** [comment]
branches are [not supported](https://pre-commit.com/#using-the-latest-version-for-a-repository) don't use them (their support is accidental and will likely be removed in the future)

there is [`pre-commit clean`](https://pre-commit.com/#pre-commit-clean) which already exists, but it's only intended as a debugging tool and should not be necessary for normal operation
