### ISSUE TITLE
Feature request: Install all configured hooks with one command

### ISSUE THREAD

**Issue by obukhov** [pre-commit/pre-commit#1635]
When I started using pre-commit I configured two types of hooks in my repository: a bunch of pre-commit hooks and one commit-msg. Later I figured out that `pre-commit install` do not install all configured hooks but only once that run on `pre-commit` stage. To install the other one I have to run `pre-commit install --hook-type commit-msg`

So to install hooks in a repository I have to read `.pre-commit-config.yaml` file, or document in `README.md` what hooks to install. This, in my humble opinion, defeats the purpose of the tool. My idea is that a user after checking out a repository by just seeing `.pre-commit-config.yaml` can run a single command having no additional knowledge to set up all required hooks to follow contribution guideline.

I think to maintain backward compatibility this should be a new command or new option, i.e.:
```
pre-commit install-all
```
or
```
pre-commit install --all-hooks
```

Sorry if this has already been discussed or even exists and I wasn't able to find it.

**Comment by asottile** [comment]
dupe #1139 #1186 #1338
