### ISSUE TITLE
filter remotes or cache results push type hook

### ISSUE THREAD

**Issue by jettero** [pre-commit/pre-commit#1641]
Semi-unrelated backstory: I prefer the workflow where I commit 10,000 dumb things "this is wrong", "oops", "fixed this thing", "blah"; then `git rebase -i` to fix up and squash my ramblings into a rational commit for a pull request… Because of this, I definitely prefer only running the pre-commit hooks on push. The main reason is that pylint and pytest can often take quite a while to run, and mostly I like to commit really often so I have undo steps and reflog entries ; it's less about communicating with the upstream repo.

I've been really happy using only push hooks for a while now, but I just added a second remote and started pushing each commit to both remotes and noticed it's running all my slow linting and testing twice. 

I can't seem to find any way to cache the result of the pre-commit run for a given commit id, but it seems like there should be some way to do this (even if a touch convoluted since my use case is likely rare).

**Comment by jettero** [comment]
This is already somewhat figured out on my end... I just use `--no-verify` on subsequent pushes; but I still wish there was a way to prevent re-running the exact same tests/linting if nothing has actually changed since the last time they ran.

**Comment by asottile** [comment]
yeah sorry not going to happen, you're basically asking for an extremely fragile cache for an extremely specific and rare workflow

thanks for the issue though!
