### ISSUE TITLE
Inconsistent behavior when using shared hooks

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1642]
While following instructions from https://stackoverflow.com/questions/59047996/how-can-i-configure-pre-commit-tool-to-rely-on-a-single-location-for-all-hook-co I created https://github.com/ansible-community/.github/blob/main/.pre-commit-hooks.yaml

Apparently I was able to call the meta `shared-hooks` hook defined in the repository above and local tests appeared to work to some extend.

I observed unexpected duplicated execution and behavior that diverged when running pre-commit directly or from inside tox (not clear why)

An WIP change can be seen at https://github.com/ansible-community/pytest-molecule/pull/81 which describes the duplication happening.

I do suspect this has something to do with the fact that we use to call pre-commit with ``pre-commit run -a`` in order to cover all files, not only the touched ones.

At a later stage I decided to add options below to enforce the execution of shared-hook once and for any run. Still this did not play well as hooks received no files so they skipped ruining.
```
        pass_filenames: false
        always_run: true
```

Is there a way to modify https://github.com/ansible-community/.github/blob/main/run-shared-hooks in such way that would work for both cases: when is called with changed files and with ``--all-files`` mode?

**Comment by asottile** [comment]
this workflow is unsupported, you're on your own
