### ISSUE TITLE
[BUG] - An unexpected error has occurred: CalledProcessError: command

### ISSUE THREAD

**Issue by noklam** [pre-commit/pre-commit#1651]
Is it a Window bug or something? I tried reinstall with a clean environment and get the thing, it seems looking for a python not from the anaconda env.
```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\CHANNO.OOCLDM\\AppData\\Local\\Continuum\\anaconda3\\python.exe', '-mvirtualenv', 'C:\\Users\\CHANNO.OOCLDM\\.cache\\pre-commit\\repooo6lzrgr\\py_env-default', '-p', 'C:\\Users\\C
HANNO.OOCLDM\\AppData\\Local\\Continuum\\anaconda3\\python.exe')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\CHANNO.OOCLDM\\AppData\\Local\\Continuum\\anaconda3\\Lib\\venv\\scripts\\nt\\python.exe'
```

**Comment by asottile** [comment]
please search the issue tracker: #1648 #1645

**Comment by zhangbc** [comment]
(env3.7) E:\projects\combat-chat-backend>pre-commit install --install-hooks
pre-commit installed at .git\hooks\pre-commit
[INFO] Installing environment for https://github.com/asottile/seed-isort-config.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Administrator\\.cache\\pre-commit\\repoxuz9tpin\\py_env-py
thon3.7\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\administrator\.cache\pre-commit\repoxuz9tpin

stderr:
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Ca
nnot connect to proxy.', OSError(0, 'Error'))': /simple/aspy-refactor-imports/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Ca
nnot connect to proxy.', OSError(0, 'Error'))': /simple/aspy-refactor-imports/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Ca
nnot connect to proxy.', OSError(0, 'Error'))': /simple/aspy-refactor-imports/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Ca
nnot connect to proxy.', OSError(0, 'Error'))': /simple/aspy-refactor-imports/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Ca
nnot connect to proxy.', OSError(0, 'Error'))': /simple/aspy-refactor-imports/
    ERROR: Could not find a version that satisfies the requirement aspy.refactor_imports (from seed-isort-config)
    ERROR: No matching distribution found for aspy.refactor_imports


python3.7+win10
