### ISSUE TITLE
install-hooks hangs indefinitely if the hook language can't be found

### ISSUE THREAD

**Issue by monfresh** [pre-commit/pre-commit#1653]
Hello. We ran into an issue where running `pre-commit install-hooks` was hanging seemingly indefinitely. For example:
```
$ pre-commit install-hooks
[INFO] Installing environment for git://github.com/igorshubovych/markdownlint-cli.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```
This was because we are using `nodenv` and didn't have node installed globally. After digging around, we came across the `language_version` and `default_language_version` config options, which solved the problem, but was not intuitive. It seems like a better user experience for the script to exit if it can't find the language that the hook needs, and display an appropriate message pointing to the language version options.

Thoughts?

**Comment by asottile** [comment]
it's not actually hanging forever, it's downloading an interpreter.  The `[INFO] This may take a few minutes...` is not wrong!

your suggestions are due to a misunderstanding so they're not applicable

**Comment by monfresh** [comment]
How long would you consider it acceptable to wait? We've seen this hang for over 10 minutes. If it's downloading something, would it make sense to display some kind of progress bar so the user knows something is happening? The same `[INFO] This may take a few minutes...` is displayed when we specify the `language_version`, and it takes less than a minute. Wouldn't it be reasonable to differentiate between the two scenarios?

**Comment by asottile** [comment]
> How long would you consider it acceptable to wait?

on the order of "minutes" -- 10 wouldn't be unsurprising if your network connection is slow

> If it's downloading something, would it make sense to display some kind of progress bar so the user knows something is happening?

`language_version` shouldn't make a considerable difference in download time -- when it's not specified it just defaults to `latest`, you might just be getting (un)lucky?

```console
$ time nodeenv nenvl -n latest  # this is the default for no `language_version` specified
 * Install prebuilt node (15.0.1) ..... done.

real	0m3.688s
user	0m2.483s
sys	0m0.513s
$ time nodeenv nenv15 -n 15.0.1   # this is how `language_version` works
 * Install prebuilt node (15.0.1) ..... done.

real	0m3.649s
user	0m2.358s
sys	0m0.650s
```

**Comment by monfresh** [comment]
Thanks for the details. That's helpful. I don't think it solves the mystery yet. Maybe if I provide more details about our dev environment it might help. I will try this tomorrow on a different machine to confirm, but I believe this is what is needed to reproduce the issue:
1. Remove node from your machine
2. `brew install nodenv`. Note this is the node version manager with a single `e`, not `nodeenv` with 2 `e`s
3. Run `nodenv init`, which will print out the line you need to add to your shell file
4. Add the line to your shell file, and restart the terminal
5. Within our project directory, we run `nodenv local 12.16.3`

With this setup, when we ran `pre-commit` without specifying the `language_version`, it hangs. Before we discovered the `language_version` option, we "fixed" this by setting node globally by running `nodenv global 12.16.3`.

After discovering the `language_version`, I removed node globally, and it stopped hanging and worked with the local node installation.

Here is our [.pre-commit-config.yaml](https://github.com/transcom/mymove/blob/master/.pre-commit-config.yaml).

**Comment by asottile** [comment]
could you try debugging this further? what command is hanging? poke around with `ps` / `pstree`

I don't have access to macos right now and I'm not going to install `nodenv` as it messes with dotfiles and my home directory

what's probably happening is their shim executable does not act like actual `node` / `npm` (probably prompting for interactive input or something dumb)

**Comment by asottile** [comment]
in the future, you would have gotten a lot better reception / attention if you would have led with debugging details instead of making assumptions.  This is commonly known as the XY problem

**Comment by monfresh** [comment]
That's a fair point. I made an educated guess based on the fact that the only difference between not hanging and hanging was node being installed globally versus not, or specifying the language version in the pre-commit config versus not.

Running `ps`, it looks it's hanging trying to run `npm install`:
```shell
96268 ttys002    0:01.25 /usr/local/Cellar/pre-commit/2.7.1/libexec/bin/python3.8 /usr/local/bin/pre-commit run
97150 ttys002    5:47.39 bash /usr/local/Cellar/nodenv/1.4.0/libexec/nodenv exec node /usr/local/bin/npm install
```

**Comment by asottile** [comment]
if you kill that npm process what does the output give you? is it prompting for something?

**Comment by sblask** [comment]
I am not sure this is the same problem I had, but it's what came up when I googled my problem, so I leave my solution for others. I was trying to run pre-commit hooks as part of Gitlab CI/CD on AWS ECS and had it "hanging" as well. After eliminating the hooks one by one as culprits I was left with one hook that uses node that caused the problem. So I looked into nodeenv and used `python -m trace` to find where it's hanging and found it's urllib2.urlopen. Then I could take the URL and try something else:

```
$ wget https://nodejs.org/download/release/index.json
Resolving nodejs.org (nodejs.org)... 2606:4700:10::6814:172e, 2606:4700:10::6814:162e, 104.20.22.46, ...
Connecting to nodejs.org (nodejs.org)|2606:4700:10::6814:172e|:443... failed: Connection timed out.
Connecting to nodejs.org (nodejs.org)|2606:4700:10::6814:162e|:443... failed: Connection timed out.
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 224195 (219K) [application/json]
Saving to: 'index.json'
     0K .......... .......... .......... .......... .......... 22% 26.7M 0s
    50K .......... .......... .......... .......... .......... 45% 65.0M 0s
   100K .......... .......... .......... .......... .......... 68% 37.7M 0s
   150K .......... .......... .......... .......... .......... 91% 25.6M 0s
   200K .......... ........                                   100% 74.9M=0.006s
```
So IPv6 requests timed out and IPv4 requests succeeded meaning I got delays but no errors and these delays accumulated. After a while I figured out that I was missing an IPv6 egress rule in my security groups, so they all got blocked. After fixing that pre-commit finished in seconds instead of "hanging" for more than one hour.
