### ISSUE TITLE
Have pre-commit call underlying hooks scripts one time only

### ISSUE THREAD

**Issue by nkazarian-spokeo** [pre-commit/pre-commit#1654]
This is our issue:

We use `jenkins-job-builder` to represent our Jenkins jobs as YAML files (see more on that [here](https://opendev.org/jjb/jenkins-job-builder)) and so we've written a shell script that essentially takes the list of modified files and checks their syntax and semantics by running the `test` subcommand in various directories. 

The problem comes in when `pre-commit` notices a large amount of files changed and calls our script multiple times with a certain set of files passed to each process that's now running the shell script. Jenkins job builder has an internal timeout for acquiring a lock file that is 60 seconds in length. Furthermore, jenkins job builder cannot be run in parallel so some `N` number of processes are now waiting to acquire a lock and this can result in a timeout, failing the entire pre-commit hook...

If instead `pre-commit` just called our script once with the exhaustive list of modified files, not only would the execution of the underlying script be a lot quicker, we'd have no chance of running into timeouts due to multiple processes being spun up and in a waiting state.

Any feedback would be appreciated, thanks!

**Comment by asottile** [comment]
[`require_serial`](https://pre-commit.com/#hooks-require_serial)

**Comment by nkazarian-spokeo** [comment]
> [`require_serial`](https://pre-commit.com/#hooks-require_serial)

Wow, I completed missed this. Sorry for the trouble, thanks for the speedy reply!!!
