### ISSUE TITLE
Is there a way to pin npm version?

### ISSUE THREAD

**Issue by Yajo** [pre-commit/pre-commit#1655]
Hello, I'm facing https://github.com/prettier/prettier/issues/9459 everywhere and it seems that prettier cannot be installed with npm 7, which is what pre-commit seems to be using.

Is there a way to pin the npm version, just like `language_version`?

cc @joao-p-marques

**Comment by asottile** [comment]
the npm version is tied to the `language_version` and not updated out of band (so presumably if you use `language_version: 14.something.something` you'll get npm 6 -- or if you have a functioning `node` + `npm` globally available it will use that
