### ISSUE TITLE
Question: Run pre-commit on staged and unstaged files.

### ISSUE THREAD

**Issue by adiroiban** [pre-commit/pre-commit#1656]
Hi,

Thanks  for the pre-commit project. It is great.

I am trying to use it in my dev workflow.

Would it be possible to run pre-commit without doing an actual commit for both staged and unstaged files?

I am trying to use it with SublimeText

The idea is that I want to edit a file and when SublimeText saves the file it will also triggers the while pre-commit stack (including black) to check that all is ok.

I am also using the Git pluggin for SublimeText.

The problem is that when I am staging a change, the changes are no longer visible in SublimeText.. this might be an issue with the SublimeText Git plugin .

But I think that it would be nice to be able to run pre-commit as some sort of precommit checkup without staging files.

Thanks.

**Comment by asottile** [comment]
on my phone, try `pre-commit run --all-files` or `pre-commit run --files ...` - both of these are listed in the docs on https://pre-commit.com

**Comment by adiroiban** [comment]
Thanks for the followup.

`pre-commit run --all-files` is slow.

My main goal is to check all the files from a branch that were changed since the main/default branch.

But I understand the name `pre-commit` and that pre-commit should not be used as a tool ouside of the pre-commit stage.

**Comment by asottile** [comment]
no you just didn't read the docs! there's two command there that do exactly what you're asking it's just very difficult to link on my phone

**Comment by adiroiban** [comment]
thanks. sorry for the noise. I willl read the docs. Much appreciated :)

**Comment by zackmccord** [comment]
For those who find this thread by Googling like I did: a simple script does the job.

```bash
#!/bin/bash -e
files="$(git diff --name-only HEAD)"
echo "$files"
echo "$files" | tr '\n' '\0' | xargs -0 pre-commit run --files 
```

**Comment by jnewbery** [comment]
This should do the trick:

```shell
pre-commit run --files $(git ls-files -m)
```

(`git ls-files -m` lists all files with unstaged modifications)

**Comment by asottile** [comment]
that is only supported on accident and may not work in the future so I would not rely on it
