### ISSUE TITLE
pre-commit for bare repos with separate working tree and git dir

### ISSUE THREAD

**Issue by adithyabsk** [pre-commit/pre-commit#1657]
Hi!

I'm using a setup similar to the [one described in this blog](https://harfangk.github.io/2016/09/18/manage-dotfiles-with-a-git-bare-repository.html) to manage my dotfiles. I manage this repo using an aliased version of git which specifies the working tree and the git directory. How would I go about setting up pre-commit to work with setup? (I tried looking through the issues but couldn't find a similar one)

```bash
# Setup Bare repo
$ git init --bare $HOME/.dotfiles.git
```

```bash
# .zshrc
alias dotfiles="/usr/local/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
```

**Comment by asottile** [comment]
could you give more details? what have you tried so far, what isn't working, what commands have you run?

pre-commit supports worktrees so it should just work ?

**Comment by adithyabsk** [comment]
Sure, maybe I'm just not clear on how to proceed. I looked through both the docs and the help to see if there was a command-line flag to pass the location of the git directory. When I run `pre-commit install` I get the following which makes sense.

```bash
$ pre-commit install  # In $HOME
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /Users/adithyabalaji/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
ah I see, you didn't actually set up a worktree, just kinda convinced git that it existed

here's how I got this working without needing any aliases (just a tiny bit more setup)

```bash
cd /tmp
rm -rf x
mkdir x  # pretend like this is your homedir
cd x
git clone --bare git@github.com:asottile/scratch
git -C scratch.git worktree add $PWD/tmp master
git --git-dir scratch.git --work-tree=$PWD checkout master
cp tmp/.git .
rm -rf tmp
# git commands work as normal from here on out
pre-commit install
pre-commit run --all-files
```

this sets up a temporary worktree, then reassigns your "homedir" to that worktree (for whatever reason, `git worktree add` errors if the directory already exists)

**Comment by asottile** [comment]
you can probably also convince git of the weird setup by using `GIT_DIR=... GIT_WORK_TREE=...` though I didn't try that approach

**Comment by adithyabsk** [comment]
This works great!

The only issue here seems to be that now my entire home directory is a "git repo" The alias approach was to avoid that issue IIUC. I'm going to give the environment variable approach a go with an alias of pre-commit with those env vars specified and report back.

**Comment by adithyabsk** [comment]
@asottile thanks for leading me down the path of using the environment variables. I was able to solve my issue by adding an alias as follows:

```bash
#.zshrc

# Configure dotfile management using git
# Usage:
#   dotfile git status
#   dotfile pre-commit run -a
alias dotfile="GIT_DIR=$HOME/.dotfiles.git/ GIT_WORK_TREE=$HOME"
```

**Comment by asottile** [comment]
cool! glad that works!

**Comment by JohnPaton** [comment]
Just popping in to say that this "weird setup" is a nice way of managing dotfiles as described [here](https://www.atlassian.com/git/tutorials/dotfiles), and many users of this prefer not to have a `.git` right there in their home directory but to keep it elsewhere, hence the `--git-dir ... --work-tree ...` args to `git` in OP's alias.

I would be curious about getting `pre-commit` working "properly" with this setup, but I've also made a note to just use the env vars before each call for now if I want to use it interactively.

**Comment by asottile** [comment]
yeah just because lots of people do a weird / bad idea doesn't make it a good idea

using a non existent work tree from a bare repo is asking for trouble
