### ISSUE TITLE
github deprecated used of set-env, affects caching guidelines

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1660]
The caching guidelines from https://pre-commit.com/#github-actions-example have very recently become outdated as github:
``
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Example: https://github.com/pycontribs/subprocess-tee/actions/runs/327311143 
```

I am currently testing the recommendations in order to build a newer variant of the guidelines.

**Comment by ssbarnea** [comment]
Apparently something like https://github.com/pycontribs/subprocess-tee/pull/9/files makes github happy.

**Comment by asottile** [comment]
I'm not sure what you're talking about, this repository doesn't use github actions at all

**Comment by ssbarnea** [comment]
I raised to the wrong project, as is a docs issue. Please transfer ticket to https://github.com/pre-commit/pre-commit.com project and I will raise a PR for it. Apparently my yesterday hack worked fine.
