### ISSUE TITLE
provide an example for `commit-msg` hook

### ISSUE THREAD

**Issue by ivica-k** [pre-commit/pre-commit#1664]
Hello and thank you for creating and maintaining this project.

I've started using it very recently and I am having issues with setting up a hook that would allow me and my colleagues to verify Git commit messages (with regex).

Reading the documentation at [pre-commit.com](https://pre-commit.com/#pre-commit-for-commit-messages) didn't really help; I was able to install the hook and it's contents is below:

```
#!/usr/bin/env python3.7
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
import os
import sys

# we try our best, but the shebang of this script is difficult to determine:
# - macos doesn't ship with python3
# - windows executables are almost always `python.exe`
# therefore we continue to support python2 for this small script
if sys.version_info < (3, 3):
    from distutils.spawn import find_executable as which
else:
    from shutil import which

# work around https://github.com/Homebrew/homebrew-core/issues/30445
os.environ.pop('__PYVENV_LAUNCHER__', None)

# start templated
INSTALL_PYTHON = '/Users/ivica/PATH_TO/venv/bin/python3.7'
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=commit-msg']
# end templated
ARGS.extend(('--hook-dir', os.path.realpath(os.path.dirname(__file__))))
ARGS.append('--')
ARGS.extend(sys.argv[1:])

DNE = '`pre-commit` not found.  Did you forget to activate your virtualenv?'
if os.access(INSTALL_PYTHON, os.X_OK):
    CMD = [INSTALL_PYTHON, '-mpre_commit']
elif which('pre-commit'):
    CMD = ['pre-commit']
else:
    raise SystemExit(DNE)

CMD.extend(ARGS)
if sys.platform == 'win32':  # https://bugs.python.org/issue19124
    import subprocess

    if sys.version_info < (3, 7):  # https://bugs.python.org/issue25942
        raise SystemExit(subprocess.Popen(CMD).wait())
    else:
        raise SystemExit(subprocess.call(CMD))
else:
    os.execvp(CMD[0], CMD)
```

What i'm missing from the docs is how to use this hook. As I said before, I'd like to verify that commit messages are in a correct format with some regex rules.

There is an existing hook for `black` configured like so

```
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
```

and it is working well.

I am probably missing or misunderstanding something - i'm just not sure what.

**Comment by asottile** [comment]
have you read the instructions on [creating new hooks](https://pre-commit.com/#pre-commit-for-commit-messages) and the specific parts for [commit-msg hooks](https://pre-commit.com/#pre-commit-for-commit-messages)?  probably in your case you also want to look at [repository local hooks](https://pre-commit.com/#pre-commit-for-commit-messages).

**Comment by ivica-k** [comment]
Hey @asottile and thank you. I have somehow miss-interpreted what was written there. This is what worked for me in the end (it may not be completely correct mind you)

1. Created a `bash` script that validates a commit message
```
#!/usr/bin/env bash
ARGS=$1

COMMIT_MSG=`head -n1 $ARGS`
PATTERN="^(CDD|CDTS)-[0-9]+[[:space:]]-[[:space:]]"
if ! [[ "$COMMIT_MSG" =~ $PATTERN ]]; then
  echo "Bad commit message '$COMMIT_MSG'. It must be in the format of 'CDD-1234 - message here' or 'CDTS-1234 - message here'"
  exit 1
fi
```

2. Added it to the `.pre-commit-config.yaml` like so
```
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        stages: [commit]
  - repo: local
    hooks:
      - id: validate-commit-msg
        name: validate-commit-msg
        entry: ./validate_commit_msg.sh
        language: script
        stages: [commit-msg]
```
(don't forget to make the script executable with `chmod +x ./validate_commit_msg.sh`

To see it in action:

1. Change a file and stage it with `git add CHANGED_FILE`
2. Try to commit with a wrong message; `git commit -m "wrong message"`.
  1. `black` hook gets triggered first and it does its thing. Stage the file again.
  2. Try to commit with a wrong message and now my hook is triggered, shows

```
git commit -m "wrong message"
black....................................................................Passed
validate-commit-msg......................................................Failed
- hook id: validate-commit-msg
- exit code: 1

Bad commit message 'wrong message'. It must be in the format of 'CDD-1234 - message here' or 'CDTS-1234 - message here'
```

Only when the commit message is in the correct format and `black` reformatted the file am I able to commit, which is what I wanted :) 🥳 

```
git commit -m "CDD-1234 - this is the correct format"
black....................................................................Passed
validate-commit-msg......................................................Passed
[CDD-2785-pre-commit-hooks e92501e] CDD-1234 - this is the correct format
 1 file changed, 56 insertions(+), 86 deletions(-)
```

**Comment by asottile** [comment]
cool, you can do it even easier with [pygrep](https://pre-commit.com/#pygrep) -- then you don't need a script at all!

**Comment by MarcoGorelli** [comment]
Good to see `--negate` come in handy :smile:

```
          - id: validate-commit-msg
            name: validate-commit-msg
            language: pygrep
            entry: ^(CDD|CDTS)-[0-9]+\s-\s
            stages: [commit-msg]
            args: [--negate]
```

**Comment by ivica-k** [comment]
Thank you both. The only downside I see is not being able to get that nice error message for the user-friendliness factor.

Could this be a potential feature? Instead of returning just the name of the file that failed it could return something to the effect of: `File '.git/COMMIT_EDITMSG' did not pass validation with '^(CDD|CDTS)-[0-9]+\s-\s'`?

**Comment by asottile** [comment]
shouldn't be necessary, that's what `name` is for (it can be any string)

**Comment by williamfzc** [comment]
https://commitizen-tools.github.io/commitizen/auto_check/
hope this helps

**Comment by pknameer** [comment]
> shouldn't be necessary, that's what `name` is for (it can be any string)

I agree with @ivica-k on this. I typically prefer keeping the `name` concise and wouldn’t want it to contain a list of 10 items just to indicate that a commit message should match one of them. Doing so detracts from the clean and brief display that pre-commit provides.

It would be fantastic if we could show the description in case of a failure instead. Since it's meant to be more detailed than the name, it would offer better clarity while keeping the overall output neat and readable.
