### ISSUE TITLE
Pre-commit doesn't parse python shebangs as expected on windows

### ISSUE THREAD

**Issue by andrewsavage1** [pre-commit/pre-commit#1665]
[Overriding Language Version](https://www.python.org/dev/peps/pep-0394/) indicates pre-commit will use the python launcher (`py`) to execute python files when a language version is specified. `py` is able to resolve version-specific python shebangs, but this seems to fail using pre-commit:

`.pre-commit-config.yaml`:
```
repos:
-   repo: local
    hooks:
    -   id: foo
        name: foo
        entry: ./foo.py
        language: python
        language_version: python3
        always_run: true
```

`foo.py`:
```
#!/usr/bin/env python3

import sys
print(sys.executable)
print(sys.version)
```

```
> py -3 foo.py
C:\Python38\python.exe
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

> git commit -m "Test"
foo......................................................................Failed
- hook id: foo
- exit code: 1

Executable `python3` not found
```

**Comment by MarcoGorelli** [comment]
does changing `entry` to
```
entry: python foo.py
```
work for you?

**Comment by asottile** [comment]
it will use the `py` launcher **to find pythons**, it does not use the py launcher to run scripts

you can write `entry: python foo.py` and `language_version: python3` -- that will use the py launcher to create a python environment using whatever suitable python3.x you have.  it will then activate that environment and `python` will match that version
