### ISSUE TITLE
bug: rbenv: no such command `install'

### ISSUE THREAD

**Issue by aerickson** [pre-commit/pre-commit#1671]
fails: https://travis-ci.com/github/mozilla-platform-ops/ronin_puppet/jobs/420816191
passes: https://travis-ci.com/github/mozilla-platform-ops/ronin_puppet/jobs/420881311

The difference in the failing job is pre-commit 2.8.1 (passing is using 2.7.1). It seems similar to https://stackoverflow.com/questions/17618113/the-command-rbenv-install-is-missing... perhaps Travis doesn't include that particular bit.

failure log snippet:
```
$ pre-commit run --all-files

[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.

[INFO] Once installed this environment will be reused.

[INFO] This may take a few minutes...

An unexpected error has occurred: CalledProcessError: command: ('/bin/bash', '/home/travis/.cache/pre-commit/repoz146d2mg/rbenv-default/bin/rbenv', 'install', 'default')

return code: 1

expected return code: 0

stdout: (none)

stderr:

    rbenv: no such command `install'

    

Check the log at /home/travis/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
this means there isn't a suitable `ruby` executable on the system

the logic changed a bit in 2.8.0: these two paths need to be available, not /shims/, and not in the home directory: `gem`, `ruby`

could you show `which ruby` and `which gem`?

**Comment by asottile** [comment]
you can work around this by setting `language_version` either to `system` or to a specific version

**Comment by asottile** [comment]
the error message from rbenv is just bad here by the way, ruby build is there but for some reason `rbenv install default` causes it to produce a strange error message

**Comment by asottile** [comment]
another thing you may want to try (if you're interested in early alpha) is https://results.pre-commit.ci (more information here: https://pre-commit.ci)

**Comment by aerickson** [comment]
```
$ which ruby; which gem

/home/travis/.rvm/rubies/ruby-2.6.6/bin/ruby

/home/travis/.rvm/rubies/ruby-2.6.6/bin/gem
```

**Comment by asottile** [comment]
yep that makes sense then, those will now be detected as "shim" executables and skipped since they're in the home directory -- that was #1658 / #1668

**Comment by aerickson** [comment]
I don't really want all users to use `language: system` (just Travis). It's painful to have to set it for each hook (we currently have 11). Is there a way of doing this globally?

What was the behavior in pre-2.8.0? Why the new requirement?

I'll check out the new service. Thanks :)

**Comment by asottile** [comment]
you can use

```yaml
default_language_version:
    ruby: system
```

- the behaviour prior to 2.7.0 I think was the same, I'd have to check exactly
- the behaviour in 2.7.x was to assume any `ruby` and any `gem` were valid system executables (caused #1658)
- the 2.8.x behaviour is as described above

I think I might partially revert such that `default` still attempts system since that has some chance of succeeding 🤔

**Comment by asottile** [comment]
oh I see, there is a subtle difference from #1509 

the code used to call `_install_ruby(...)` only if version was not `C.DEFAULT` -- now it calls it if it's not `system`

let me change that and see if it makes it better

**Comment by asottile** [comment]
would you like to try out the patch in #1672?
