### ISSUE TITLE
precommit error on windows + anaconda enviroment

### ISSUE THREAD

**Issue by vinura** [pre-commit/pre-commit#1675]
I get the following error after running the following commands
========================================================
1. Fresh Conda and GIT installation on Windows 
2. Run the following commands on anaconda prompt (on the project directory)
>conda create -n code_quality_demo python=3.7
>conda activate code_quality_demo
>pip install -r test_requirements.txt(includes pre-commit)
>git init
>pre-commit install
>git add .
>pre-commit run --all-files

Error 
==========================================================
> [INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\vinurap\\.conda\\envs\\code_quality_demo\\python.exe', '-mvirtualenv', 'C:\\Users\\vinurap\\.cache\\pre-commit\\repog4vviu07\\py_env-default')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vinurap\\.conda\\envs\\code_quality_demo\\Lib\\venv\\scripts\\nt\\python.exe'

>stderr: (none)
Check the log at C:\Users\vinurap\.cache\pre-commit\pre-commit.log

Hack i found to fix this
=================================================================
Copying python.exe and pythonw.exe to the 'C:\\Users\\vinurap\\.conda\\envs\\code_quality_demo\\Lib\\venv\\scripts\\nt\\'

Is there a better way than this ?

**Comment by MarcoGorelli** [comment]
It seems this is due to a bug in virtualenv https://github.com/pypa/virtualenv/issues/1986

> Is there a better way than this ?

Can you try downgrading `virtualenv` to version 20.0.33 ?

**Comment by vinura** [comment]
@MarcoGorelli  Thanks man it worked <3 ! You saved me from a lot of trouble
