### ISSUE TITLE
Allow to exclude files in LFS

### ISSUE THREAD

**Issue by wannesvanloock** [pre-commit/pre-commit#1676]
We run our hooks in CI but don't pull LFS objects to save bandwidth. We are now encountering the case where hooks are failing as they are run on unpulled lfs files (in our case a large json test file). It would be great if we would have a way to exclude such files. Perhaps adding `lfs` as a type for `identify`?

**Comment by asottile** [comment]
please show an example

**Comment by wannesvanloock** [comment]
Consider the following repo as example: https://github.com/wannesvanloock/pre-commit-lfs.

The `example.json` contains simply `{}` but is tracked by lfs.

After cloning the repo with 
```bash
GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/wannesvanloock/pre-commit-lfs.git
```
`pre-commit run --all-files` will fail as the lfs json file was skipped during the cloning and still points to the lfs object. The file contents is now
```
version https://git-lfs.github.com/spec/v1
oid sha256:d914176fd50bd7f565700006a31aa97b79d3ad17cee20c8e5ff2061d5cb74817
size 4
```
and is clearly not a valid json file. Therefore, being able to easily exclude lfs files in `pre-commit` would be a welcome addition.

Hope that clarifies things. Thanks!

**Comment by asottile** [comment]
thanks, that would have been useful to lead with!  A good rule of thumb when creating issues is to provide enough information such that someone else can understand exactly what you're seeing -- an improvement further would be to show a configuration and an output but you've provided enough for me to do that myself

can you not use `exclude:`?

**Comment by wannesvanloock** [comment]
We're using `exclude` as a workaround for now. But this may not be scalable as the number of locations to exclude will surely grow in our case + the reason for failure is not at all obvious leaving devs clueless. I was thinking along the lines of adding an `exclude_type: ['lfs']`. If that sounds reasonable to you, I'll propose a PR.

**Comment by asottile** [comment]
I don't think that would work because when lfs isn't installed we wouldn't be able to get the list of lfs files

I'm also hesitant to add a blocking call to the critical path which most users won't use for something that is a third party extension of git

**Comment by wannesvanloock** [comment]
An alternative to `git lfs ls-files`, would be to detect that we haven't pulled the file based on the file contents.

```
version https://git-lfs.github.com/spec/v1
oid sha256:d914176fd50bd7f565700006a31aa97b79d3ad17cee20c8e5ff2061d5cb74817
size 4
```
seems rather predictable and easy to detect.

Another, much more generic solution would be to allow the `exclude` to be scriptable.

In any case, if not in scope of the project, feel free to close the issue. Thanks!

**Comment by asottile** [comment]
those contents are implementation details of lfs, they are not a stardard part of `git`

**Comment by asottile** [comment]
`exclude` is scriptable, you just have to think outside the box :)

write a pre-commit hook which runs your lfs commands and modifies the configuration

**Comment by wannesvanloock** [comment]
Already had that in mind :grinning:
I guess we'll have to resort to that.

**Comment by simonLeary42** [comment]
Also having this issue
