### ISSUE TITLE
Execute pre-commit on file save

### ISSUE THREAD

**Issue by lioramilbaum** [pre-commit/pre-commit#1679]
It would be valuable to have the ability to execute the pre-commit hooks on file save.
IDEs like vscode has the ability to configure actions upon save, via plugins.

This is a shift left approach. Which is finding the issues as soon as possible, which is while we edit the files (way before we commit them).

**Comment by MarcoGorelli** [comment]
Hi @lioramilbaum 

If you have modified files but not staged them (i.e. you've not done `git add`), then my understanding is that `pre-commit run` will just skip all checks. You could set up the 'run on save' extension to execute `pre-commit run --all-files` on save, but then wouldn't that be a bit too disruptive?

For what it's worth, I'd advise to do frequent and atomic commits while developing (you can always fix them up before pushing)

**Comment by lioramilbaum** [comment]
Thank you for the suggestion. We already practice the advised process.
I was referring to a bit different experience.  Let me elaborate with an example.
I am using flake8 as a linter.  It is configured to run checks on the saved file and identify immediately (in the editor view) the lines that are not passing the rules.
Staging nor Commiting are not required to figure out what is wrong. The feedback loop is shorter.

**Comment by MarcoGorelli** [comment]
How would you propose that this be implemented, other than running `pre-commit run --all-files` on save?

Either way, from what I understand, you'd like a vscode extension, so this wouldn't live inside the pre-commit repo, right?

**Comment by lioramilbaum** [comment]
Implement a pre-commit run <file> can be one option. WDYT?
I work with vscode, than yes, it would be great to have a vscode plugin. Where the code is tracked is not something I can answer.

**Comment by MarcoGorelli** [comment]
> WDYT?

TBH I would find it disruptive to have `pre-commit run --all-files` run every time I save a file. Given that the project's author doesn't use vscode himself, I'm pretty sure this will be closed

Anyway, if that's what you want, you can just use the existing 'run on save' extension https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave and put the above command in there, as far as I can tell there's no need for a separate extension

**Comment by lioramilbaum** [comment]
It is distruptive to have `pre-commit run --all-files` run every time you save a file. What about to have `pre-commit run <single file>
'?

**Comment by MarcoGorelli** [comment]
OK, yes, I just tried enabling https://marketplace.visualstudio.com/items?itemName=wk-j.save-and-run and putting
```
		"saveAndRun": {
			"commands": [
				{
					"match": ".*",
					"cmd": "<path to pre-commit> run --files ${file}"
				}]
		}
```
in my vscode settings and it seems to work
