### ISSUE TITLE
pre-commit is working well with github workflows but don't working without it

### ISSUE THREAD

**Issue by bhuiyanmobasshir94** [pre-commit/pre-commit#1680]
I am working with two reposiitories where in one case I am using hithub workflows ci and it's working good but in other case I am not working without it and that case its not working with commit. Isn't it capable to work standalone. Thank you.

**Comment by asottile** [comment]
you've given me zero information to try and help you

put me in my shoes and what could I possibly tell you from what you've given me?

show me your repo, show me your configuration, show me the commands you ran, show me the output

"it doesn't work" is not a bug report

**Comment by bhuiyanmobasshir94** [comment]
@asottile the initial problem was with installation, I reinstalled it and it worked. Thanks for the help.
