### ISSUE TITLE
Installing npm packages with path deps on Windows fails under pre-commit due to symlink perms, works fine with npm outside of it

### ISSUE THREAD

**Issue by CAM-Gerlach** [pre-commit/pre-commit#1681]
I'm otherwise a very happy user of pre-commit, but I seem to have run into one significant issue that's blocking adoption across the projects I manage. I wasn't quite sure whether to report the issue here or to the upstream package, but since I cannot reproduce the error running the same npm command pre-commit is using and thus I'm not sure if they'd be able to help me, I figured I'd try here first, after searching for the error on both issue trackers and Google.

In summary, when I use the following minimal pre-commit config with the `markdownlint` npm-based hook as an example,

```yaml
repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.24.0
  hooks:
  - id: markdownlint
```

Installing the hook on Windows results in npm failing on a permissions error due to npm trying to symlink a locally installed development package, unless I run `pre-commit install-hooks` first in an elevated console, or in Windows 10 "development mode" which allows non-admins to create symlinks.  I can reproduce this on both pre-commit 2.7.1 and the latest 2.8.2 starting from a clean environment (`pre-commit clean`)

However (and the reason I'm reporting this here), I __cannot__ reproduce this running the same npm command as pre-commit did (`npm install --dev --prod --ignore-prepublish --no-progress --no-save`) both in cmd and git bash using the current LTS npm (6.14.8) in the root of my repo plus `markdown-cli`, nor if I clone the `markdown-cli` repo and run the same command there. 

Error message:

<details>

```
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Installing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\C. A. M. Gerlach\\.cache\\pre-commit\\repob8cym6bz\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 4294963248
expected return code: 0
stdout: (none)
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm ERR! code EPERM
    npm ERR! syscall symlink
    npm ERR! path ..\test\custom-rules\test-rule-package
    npm ERR! dest C:\Users\C. A. M. Gerlach\.cache\pre-commit\repob8cym6bz\node_modules\test-rule-package
    npm ERR! errno -4048
    npm ERR! Error: EPERM: operation not permitted, symlink '..\test\custom-rules\test-rule-package' -> 'C:\Users\C. A. M. Gerlach\.cache\pre-commit\repob8cym6bz\node_modules\test-rule-package'
    npm ERR!  [Error: EPERM: operation not permitted, symlink '..\test\custom-rules\test-rule-package' -> 'C:\Users\C. A. M. Gerlach\.cache\pre-commit\repob8cym6bz\node_modules\test-rule-package'] {
    npm ERR!   errno: -4048,
    npm ERR!   code: 'EPERM',
    npm ERR!   syscall: 'symlink',
    npm ERR!   path: '..\\test\\custom-rules\\test-rule-package',
    npm ERR!   dest: 'C:\\Users\\C. A. M. Gerlach\\.cache\\pre-commit\\repob8cym6bz\\node_modules\\test-rule-package'
    npm ERR! }
    npm ERR!
    npm ERR! The operation was rejected by your operating system.
    npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
    npm ERR! or that you lack permissions to access it.
    npm ERR!
    npm ERR! If you believe this might be a permissions issue, please double-check the
    npm ERR! permissions of the file and its containing directories, or try running
    npm ERR! the command again as root/Administrator.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_logs\2020-11-03T15_50_34_868Z-debug.log
```

</details>

It seems to be triggered by markdownlint-cli requiring [this test package](https://github.com/igorshubovych/markdownlint-cli/blob/b0fe91bb57e3872754d0c46323d859f413909d1e/package.json#L60) that's a local directory rather than a npm module name, and it seems likely given the circumstances it will be the case with any pre-commit installed package that has such a dependency.

Given not all our Windows devs and potential contributors have Windows 10 or development mode enabled, this is a non-trivial blocker to widespread adoption without being a barrier to new contributors, many of whom are blog writers, scientists, engineers or students rather than professional programmers (which is one reason pre-commit is such a great tool, as it avoids either us or them having to nitpick style and correctness issues).

Therefore, given I cannot reproduce the error running `npm` normally with the same command and package outside of pre-commit, and I'm not a npm whiz, I'm not sure how to proceed debugging this, or where else this should be reported. I'm happy to help test this further, submit a PR If the fix is straightforward, or report this elsewhere, as approprite—just let me know. Thanks!

**Comment by asottile** [comment]
not our problem it seems:

```
C:\Users\asott>cd %TEMP%

C:\Users\asott\AppData\Local\Temp>git clone https://github.com/igorshubovych/markdownlint-cli
Cloning into 'markdownlint-cli'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 778 (delta 14), reused 13 (delta 5), pack-reused 752Receiving objects:  99% (771/778)
Receiving objects: 100% (778/778), 477.19 KiB | 4.19 MiB/s, done.
Resolving deltas: 100% (500/500), done.

C:\Users\asott\AppData\Local\Temp>cd markdownlint-cli

C:\Users\asott\AppData\Local\Temp\markdownlint-cli>python -m venv venv

C:\Users\asott\AppData\Local\Temp\markdownlint-cli>venv\Scripts\pip install nodeenv
Collecting nodeenv
  Downloading https://files.pythonhosted.org/packages/ae/d0/efdf54539948315cc76e5a66b709212963101d002822c3b54369dbf9b5e0/nodeenv-1.5.0-py2.py3-none-any.whl
Installing collected packages: nodeenv
Successfully installed nodeenv-1.5.0
You are using pip version 18.1, however version 20.3b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\asott\AppData\Local\Temp\markdownlint-cli>venv\Scripts\nodeenv nenv
 * Install prebuilt node (15.0.1) ..... done.
You do not have sufficient privilege to perform this operation.
You do not have sufficient privilege to perform this operation.
Error: Failed to create nodejs.exe link

C:\Users\asott\AppData\Local\Temp\markdownlint-cli>nenv\Scripts\activate.bat
(nenv) C:\Users\asott\AppData\Local\Temp\markdownlint-cli>npm i
npm notice
npm notice New patch version of npm available! 7.0.3 -> 7.0.7
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.0.7
npm notice Run npm install -g npm@7.0.7 to update!
npm notice
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ..\test\custom-rules\test-rule-package
npm ERR! dest C:\Users\asott\AppData\Local\Temp\markdownlint-cli\node_modules\test-rule-package
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, symlink '..\test\custom-rules\test-rule-package' -> 'C:\Users\asott\AppData\Local\Temp\markdownlint-cli\node_modules\test-rule-package'
npm ERR!  [Error: EPERM: operation not permitted, symlink '..\test\custom-rules\test-rule-package' -> 'C:\Users\asott\AppData\Local\Temp\markdownlint-cli\node_modules\test-rule-package'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '..\\test\\custom-rules\\test-rule-package',
npm ERR!   dest: 'C:\\Users\\asott\\AppData\\Local\\Temp\\markdownlint-cli\\node_modules\\test-rule-package'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asott\AppData\Local\npm-cache\_logs\2020-11-03T17_00_25_583Z-debug.log
```

but, you can enable symbolic links on windows without development mode -- iirc both the `git` and `python` installers prompt to enable this

**Comment by asottile** [comment]
downgrading to npm 6 might be useful -- you can do that via `language_version` (and selecting a 14.x node) -- I'd suggest reporting to both npm and markdowncli-lint

**Comment by CAM-Gerlach** [comment]
Thanks @asottile , much appreciated! Pinning to node 14.15.0 (the latest LTS version, and it looks like reading the nenv docs you reference that there's no way to just pin to the latest minor or patch version of a major version?) does indeed prevent the issue; my fault for not testing the latest node rather than the LTS (I'd incorrectly thought pre-commit was using the former), and I can confirm I see the same error as you once I upgrade node to that version.

I'll report it to both places you mention, and hopefully it  can get resolved upstream before that old node version gets too long in the tooth. Again, thanks!

**Comment by CAM-Gerlach** [comment]
Looks like its been reported to npm as npm/cli#1923 and a PR npm/arborist#162 is in flight to fix it, so hopefully it should be resolved soon, in case any other users ask.

**Comment by asottile** [comment]
I think this would help for the nodeenv side, but yeah this is ultimately an npm issue: https://github.com/ekalinin/nodeenv/issues/274

**Comment by CAM-Gerlach** [comment]
Great, thanks!
