### ISSUE TITLE
Dynamic routing $id will be ignore by pre-commit

### ISSUE THREAD

**Issue by buzingar** [pre-commit/pre-commit#1692]
![image](https://user-images.githubusercontent.com/39228659/98643768-71f02080-236a-11eb-81bd-64ede7b898ba.png)
the path is changing to `weexProgram/hotBrand/index.jsx`, as the raw path is `weexProgram/hotBrand/$id/index.jsx`. I wonder which config could solve this problem.

**Comment by asottile** [comment]
you have the wrong project, this isn't `lint-staged` and files are passed along literally by pre-commit (there's no shell involved)

**Comment by buzingar** [comment]
@asottile thanks for your answer, but I don't quite understand what you mean.I know now that I came to the wrong place. This is not a lint-staged thing? so it must be a eslint thing. Check them all.

**Comment by asottile** [comment]
it's probably a problem with `lint-staged` if I had to guess, but that's an unrelated project (`pre-commit` and `lint-staged` are similar tools however)
