### ISSUE TITLE
Run pre-commit while running rebase --continue

### ISSUE THREAD

**Issue by Tadaboody** [pre-commit/pre-commit#1696]
Here's the use case I've recently encountered: 
- Your branch has gone stale, so you rebase off of the main branch
- Merge conflicts arise, so you solve them as they come and run `git rebase --continue` without creating new commits
- `pre-commit` doesn't run, leaving style violations and lint errors in the new commit history 😿

**Comment by asottile** [comment]
unfortunately, there's no `git` hook that fires on `git rebase --continue`

but, fortunately, as long as you've run `git add`, you can run `pre-commit` manually and it will act the same as if you had run a `git commit`

**Comment by Tadaboody** [comment]
Understandable, thanks for the quick answer!

**Comment by wagnerluis1982** [comment]
Adding to this thread, I am using a trick to deal with the git limitation:
```console
$ git rebase -x 'git reset --soft HEAD~1 && git commit -C HEAD@{1}' origin/master
Executing: git reset --soft HEAD~1 && git commit -C HEAD@{1}
black....................................................................Passed
flake8...................................................................Passed
[detached HEAD c972492] Add tests for the coolest feature
 Date: Tue Nov 17 22:31:44 2021 +0100
 11 files changed, 147 insertions(+), 15 deletions(-)
 create mode 100644 tests/test_coolest.py
Executing: git reset --soft HEAD~1 && git commit -C HEAD@{1}
black....................................................................Passed
flake8...................................................................Passed
[detached HEAD e3656a8] Complement with more tests
 Date: Sat Nov 20 07:33:50 2021 +0100
 5 files changed, 35 insertions(+), 16 deletions(-)
Successfully rebased and updated refs/heads/coolest-feature.
```

This is pretty useful when pre-commit rules were updated in `master` and you want to reapply to all commits in your working branch. Must also work well in `rebase --continue`.

To make it easier, I added a git alias :smile: 
```console
$ git config --global alias.pre-commit-rebase "rebase -x 'git reset --soft HEAD~1 && git commit -C HEAD@{1}'"
```

Source: https://asciinema.org/a/222023

**Comment by MRigal** [comment]
Thanks @adamchainz !

Once again a masterpiece of clarity, with outputs and how to behave 💯 ! I also prefer your command invocation than to use `git reset --soft`

**Comment by fleutot** [comment]
> I just [blogged about](https://adamj.eu/tech/2022/11/07/pre-commit-run-hooks-rebase/) a different use of `-x` to invoke pre-commit directly, rather than undoing and redoing the commit:
> 
> ```
> $ git rebase -x 'pre-commit run --from-ref HEAD~ --to-ref HEAD' main
> ```

@adamchainz , I must be missing something, but I don't know what. When you rebase a branch and want to apply your pre-commit hook on every new commit, the hook should be run _before_ creating the commit, right? But if I understand correctly, `git rebase -x` runs the command _after_ the commit creation. The command runs one commit too late. Where am I blind?
