### ISSUE TITLE
Rbenv default ruby issue on install

### ISSUE THREAD

**Issue by abuxton** [pre-commit/pre-commit#1699]
I am trying to install MDL v0.11.0

i get the following error during install 
```
pre-commit
[INFO] Installing environment for git://github.com/markdownlint/markdownlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/bash', '/Users/abuxton/.rbenv/shims/gem', 'build', 'mdl.gemspec')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    rbenv: version `default' is not installed (set by RBENV_VERSION environment variable)
```

seems to be the same issue as https://github.com/pre-commit/pre-commit/issues/369 on a previous version of pre-commit
pre-commit.log https://gist.github.com/abuxton/d29e6265f3230f838a746d7a5defd5e3 

i have tried, ensuring local rbenv, I have tried pre-commit clean/uninstall and reinstall to no success, mdl will `brew install mdl` successfully and works fine.

**Comment by asottile** [comment]
ah yeah, this has regressed because it's difficult to test!  pre-commit ~correctly identified that you're using shims globally so it shouldn't necessarily trust that ruby, but then used it anyway 😆 -- this `if` here needs to also apply to `'default'`:  https://github.com/pre-commit/pre-commit/blob/59acc7e48a58de3771d7552c64104add7e3dd1bf/pre_commit/languages/ruby.py#L43

**Comment by asottile** [comment]
actually hmm this seems really strange -- pre-commit should still be creating an rbenv shim in that case so my suggested patch above isn't quite correct

**Comment by asottile** [comment]
@abuxton can you try out the patch in #1700 -- it fixed the case I tried locally but I'm not 100% it solves your usecase

**Comment by georgealton** [comment]
I had _exactly_ the same issue today in AWS CodeBuild.

Tried the fix #1700 and it solves it for me.

**Comment by pbr0ck3r** [comment]
Now that this has been merged in, when is the next planned package release?

**Comment by asottile** [comment]
> 
> 
> Now that this has been merged in, when is the next planned package release?

if you look at the release history, nothing is "planned", I maintain this in my free time :) if you or your company depend on this package I'd recommend [sponsoring](https://github.com/pre-commit/pre-commit/pull/1703)
