### ISSUE TITLE
re-stage files changed by end-of-file-fixer hook

### ISSUE THREAD

**Issue by najisawas** [pre-commit/pre-commit#1706]
curious what the discussion around supporting an `--autofix` flag for the `end-of-file-fixer` is. It seems odd to me that although the hook fixes the issue, it won't re-stage the file and follow through with the commit if it is the only issue / adjustment to the file / commit. Currently a user's work flow is that they must restage and re-run `git commit` if this fails, which is slightly tedious and seems confusing

**Comment by asottile** [comment]
see [this SO answer](https://stackoverflow.com/a/64309843/812183)

or these duplicate issues:

- https://github.com/pre-commit/pre-commit/issues/532
- https://github.com/pre-commit/pre-commit/issues/747
- https://github.com/pre-commit/pre-commit/issues/806
- https://github.com/pre-commit/pre-commit/issues/879
- (there's more, but you get the idea)
