### ISSUE TITLE
How to run pre-commit at the CI if there is no git ?

### ISSUE THREAD

**Issue by elnygren** [pre-commit/pre-commit#1722]
Hey, I'm wondering what is the best way to run pre-commit checks at a CI like Google Cloud Build where there really isn't a git repo or git (you can obviously install git and init a repo).

What we are doing now is 

```yaml
  - name: "gcr.io/cloud-builders/docker"
    id: "Lint - Python"
    waitFor:
      - "Docker Build - Python"
    args:
      [
        "run",
        "--entrypoint",
        "/bin/bash",
        "eu.gcr.io/$PROJECT_ID/$IMAGE:$SHORT_SHA",
        "-c",
        "git init && git add . && pre-commit run --all-files isort && pre-commit run --all-files black && pre-commit run --all-files flake8",
      ]
```

and this has several downsides to it:
* our container has to include `git` which we really don't want to
* our container has to include pre-commit and it's deps too
* we need to `git init` even though we really don't want to do that

So it seems the options here are:
1. separate docker container that has git, pre-commit and the actual checks installed
2. `pre-commit just run the checks to all files directly without git`
3. ?

What's the recommended / standard way? Perhaps this ought to be documented as the industry is converging to these similar Docker based CIs (?)

**Comment by asottile** [comment]
`pre-commit` is entirely based around `git` so you need it one way or another

what you've got is what I'd recommend -- or maybe check out https://pre-commit.ci and see if it fits your needs

**Comment by kretes** [comment]
Facing the same issue now, when trying to run `pre-commit run <files>` on all project files in CI.

> `pre-commit` is entirely based around `git` so you need it one way or another

This isn't entirely true.
E.g. to invoke a manual check over some files (e.g. a list from `find` command) - no valid git repo is required, just a dummy one.
So - there are commands/command settings where git isn't really needed and maybe shouldn't be invoked.

a) Considering a selective requirement for git would be nice. 
b) Allowing for '--no-git-check' would be a bad compromise IMO - changes for users, and more changes in `pre-commit`

**Comment by asottile** [comment]
no
