### ISSUE TITLE
Use ~/.cache/pre-commit in docker container

### ISSUE THREAD

**Issue by varac** [pre-commit/pre-commit#1731]
I'd like to run pre-commit from a docker image (so our team can easily use the same version of pre-commit and don't need to install it on everybodies machines). 
Without mounting the persitant cache dir from the docker host, pre-commit would obviously install all hooks each time I run it.
So I try to mount the cache dir into the container like this:

    alias pre-commit='docker run --rm -it --mount type=bind,source=$(pwd),dst=/src --mount type=bind,source=/home/varac/.cache/pre-commit,dst=/home/user/.cache/pre-commit OUR_IMAGE pre-commit'

The problem is that the pre-commit cache dir config contains the hardcoded username/home dir so when I run it it will complain about a non-existing directory:

```
❯ pre-commit run --all-files
An error has occurred: InvalidManifestError: 
=====> /home/varac/.cache/pre-commit/repod1b33t67/.pre-commit-hooks.yaml does not exist
Check the log at /home/user/.cache/pre-commit/pre-commit.log
```

Because my docker host user is not present in the container.
Any ideas how to best approach this ?

**Comment by asottile** [comment]
the [docs answer this](https://pre-commit.com/#managing-ci-caches)

**Comment by gad26032** [comment]
@varac take a look this comment, maybe it can help you. We have similar flow.
https://github.com/pre-commit/pre-commit/issues/1734#issuecomment-746115929
