### ISSUE TITLE
Support config in setup.cfg files? Or config in a separate folder?

### ISSUE THREAD

**Issue by illume** [pre-commit/pre-commit#1733]
Hello,

if it's not already possible... 

would you consider allowing config to be read from `pre-commit-config` `pre-commit-hooks` sections in a setup.cfg file? 

Alternatively perhaps just a way to store a folder to search for config inside the setup.cfg file.

I like to minimize config files in the root of a repo, and want to use pre-commit. The repo has a `setup.cfg` and a `buildconfig` folder. Pretty much all python tools support setup.cfg for config.

cheers,

**Comment by asottile** [comment]
You can use `--config`, but no, it's not possible to represent the structure in `ini` and I have no interest in supporting alternative configuration formats even though yaml sucks

**Comment by asottile** [comment]
Note also that although pre-commit is written in python, it is not specifically a python tool -- it supports many different programming languages

**Comment by illume** [comment]
Is there a way to support config file soup haters?

Perhaps a wrapper script which just calls pre-commit with `--config`?

**Comment by illume** [comment]
Note also that although pre-commit is for multiple languages, python is a language it supports.
