### ISSUE TITLE
Running pre-commit in a submodule directory

### ISSUE THREAD

**Issue by gad26032** [pre-commit/pre-commit#1734]
When I try to run pre-commit inside a submodule it fails and I get the following report

### version information

```
pre-commit version: 2.9.3
sys.version:
    3.7.9 (default, Nov 25 2020, 03:17:55) 
    [GCC 8.3.0]
sys.executable: /usr/local/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pre_commit/git.py", line 56, in get_root
    cmd_output('git', 'rev-parse', '--show-cdup')[1].strip(),
  File "/usr/local/lib/python3.7/site-packages/pre_commit/util.py", line 160, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'rev-parse', '--show-cdup')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: not a git repository: /src/../.git/modules/amp
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.7/site-packages/pre_commit/main.py", line 330, in main
    _adjust_args_and_chdir(args)
  File "/usr/local/lib/python3.7/site-packages/pre_commit/main.py", line 147, in _adjust_args_and_chdir
    toplevel = git.get_root()
  File "/usr/local/lib/python3.7/site-packages/pre_commit/git.py", line 61, in get_root
    'git failed. Is it installed, and are you in a Git repository '
pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

Since Git use .git files instead of .git folders this check will always  raise an Exception

From the Git official documentation [GitBook->Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

> It’s important to note that submodules these days keep all their Git data in the top project’s .git directory, so unlike much older versions of Git, destroying a submodule directory won’t lose any commits or branches that you had.

Can we add some additional checks here to make it possible to run pre-commit in the submodule?

https://github.com/pre-commit/pre-commit/blob/2d54ea112aab5568c149bb81f428dce70010a151/pre_commit/git.py#L49-L69

**Comment by asottile** [comment]
hmmm this may have regressed -- can you try 2.9.2 -- we had a test for this as well I wonder what happened to it

**Comment by asottile** [comment]
hmmm I cannot reproduce, `--show-cdup` works fine for me in submodules -- can you share your `git` version?  I'm using 2.25.1

**Comment by asottile** [comment]
the `/src` directory is definitely suspect though, my guess without seeing your setup is you're using some sort of weird unsupported pre-commit docker wrapper which only mounts the current repository to `/src`

and then because you haven't mounted the rest of the git repository where the submodule git metadata is, `git` commands fail

so this isn't a bug in pre-commit but in whatever mounting docker thing you're doing

**Comment by gad26032** [comment]
@asottile You absolutely right, we are using pre-commit inside a docker. This is our way of distributing custom linters and code checks. We have an image with installed pre-commit and our library of linters, we mount various repos inside a container and run checks. Sometimes we run it for submodules.
At the moment to work around this problem we use this solution:

 ```bash
if [ $(git rev-parse --show-superproject-working-tree) ]; then
    SUBMODULE_NAME=$(basename "$(pwd)")
    echo "Running linter for '$SUBMODULE_NAME' submodule."
    WORK_DIR="/src/$SUBMODULE_NAME"
    REPO_ROOT=$(git rev-parse --show-superproject-working-tree)
  else
    echo "Running linter for the repository."
    WORK_DIR="/src"
    REPO_ROOT="$(pwd)"
fi
```
and then
```bash
docker run --rm -t \
    --env "PRE_COMMIT_HOME=$HOME/.cache/pre-commit" \
    -v "$HOME/.cache:$HOME/.cache:rw" \
    -v "$REPO_ROOT":/src \
    --workdir "$WORK_DIR" \
    custom_pre_commit_image:latest "$@"
```

From your response, I see that it going to be our long-term solution.
@asottile Thanks for the quick response. And for your work on such a useful tool!
