### ISSUE TITLE
exclude hook ids from running

### ISSUE THREAD

**Issue by nicoa** [pre-commit/pre-commit#1737]
Hey,

not sure If I oversee any issue or documentation on this, so asking here.

From our point of view it makes sense to have the option to exclude some hook IDs when running pre-commit (e.g. long running ones in a CI pipeline). Right now we have to either
a) run all the hooks separately or
b) run all hooks alltogether

What do you think of having the option to exclude some hook IDs when running `pre-commit run`? Would that makes sense? Am I overseeing some easy solution already?

Best
Nico

**Comment by MarcoGorelli** [comment]
You can use the `SKIP` environment variable

**Comment by nicoa** [comment]
okay, somehow didn't saw that, thx for the info!
