### ISSUE TITLE
conda support still ok? 

### ISSUE THREAD

**Issue by xhochy** [pre-commit/pre-commit#1740]
Hello @asottile, just wanted to give you a heads-up that we are still happily using the conda support in pre-commit that I contributed a while ago. We just only recently came up with an issue in #1738 / #1739 otherwise pre-commit + the contributed conda support work very smooth. I am not actively monitoring the issue tracker here but I'm happy to support if issues come up with the conda support come up, just mention me on an issue.

As I personally know quite well that supporting a feature one doesn't need themselves is quite a burden, I wanted to use this occasion to ask whether all is ok with the conda support or whether something should be cleaned up? 

Feel free to just close this issue if everything is ok! Thought I'd better ask before one day the support may be dropped to due "no users / no maintainers".

**Comment by asottile** [comment]
yep it's fine!
