### ISSUE TITLE
Autoupdate replacing a sha with 'older' release

### ISSUE THREAD

**Issue by AleksaC** [pre-commit/pre-commit#1744]
I use a pre-commit hook with a `rev` pointing to a sha. When I use `autoupdate` it changes the `rev` to latest release, but that release is older than the previous sha. I think it would make sense not to change the rev if it's pointing to a commit after the latest release. 

Of course, this can be circumvented by passing the other repos to autoupdate but it is a bit cumbersome. I can also update that specific hook using `--bleeding-edge` but I don't really want the latest commit, just the commit where a specific feature is introduced. This might also be useful for pre-commit.ci where AFAIK you cannot specify which repos should be updated.

Just to clarify by older I'm not thinking of dates instead I'm refering to the order they appear in history for the specific branch. I'm not sure if this notion can be generalized across branches.

If you think that it makes sense to implement this and that it can be tackled by someone without much familiarity with the codebase I can try to provide a PR for this.

**Comment by asottile** [comment]
I don't think this really makes sense for pre-commit, you're essentially asking for `autoupdate --no-autoupdate` which would just be "don't run autoupdate".

I think for pre-commit.ci, adding a special comment to freeze a version might make sense?  but preventing autoupdates actually makes the system less efficient and more expensive (when everything is on the latest versions there's much less cache data required for oddball versions) so I don't really want that feature to exist

Even better would be to convince the upstream to make a release with the new feature :)

**Comment by AleksaC** [comment]
Yeah, I also didn't take caching into account.  Using a special comment seems reasonable. Maybe it would also make sense to add a flag like `--exclude-repos` to `autoupdate`, not just for this particular use case but in general.

**Comment by asottile** [comment]
there's already `--repos` -- I think that probably works for what you want right?

**Comment by AleksaC** [comment]
Yes it does, it's just cumbersome to write 7 times

**Comment by asottile** [comment]
ah fair,

you could do something like this:

```console
$ ~/go/bin/uq .pre-commit-config.yaml | jq --raw-output .repos[].repo | grep -v pycqa/flake8 | xargs --replace pre-commit autoupdate --repo {}
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating https://github.com/pre-commit/mirrors-autopep8 ... already up to date.
Updating https://github.com/pre-commit/pre-commit ... already up to date.
Updating https://github.com/asottile/pyupgrade ... already up to date.
Updating https://github.com/asottile/reorder_python_imports ... already up to date.
Updating https://github.com/asottile/add-trailing-comma ... already up to date.
Updating https://github.com/asottile/setup-cfg-fmt ... already up to date.
Updating https://github.com/pre-commit/mirrors-mypy ... already up to date.
```

**Comment by AleksaC** [comment]
Nice, thanks! `uq` is [solarkennedy/uq](https://github.com/solarkennedy/uq)?

**Comment by asottile** [comment]
yep!
