### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by luksiv** [pre-commit/pre-commit#1747]
Hey,

There are some issues when running pre-commit on the M1 chip for apple.

Device: MacBook Pro (13-inch, M1, 2020)

```
➜  ~ brew install pre-commit
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 12 formulae.

Warning: pre-commit 2.9.3 is already installed and up-to-date
To reinstall 2.9.3, run `brew reinstall pre-commit`
➜  ~ pre-commit --version
[1]    33362 illegal hardware instruction  pre-commit --version
```

**Comment by asottile** [comment]
it's claimed to work here: https://github.com/Homebrew/brew/issues/7857 -- I'd suggest following up with homebrew specifically

**Comment by asottile** [comment]
note that we don't have any nonpure code so it couldn't be us :)

**Comment by luksiv** [comment]
Alright, will try to sort out with Homebrew. Thank you for your swift response 👍
