### ISSUE TITLE
Unable to specify Python editable dependency when using local hook due to change in working directory

### ISSUE THREAD

**Issue by wchill** [pre-commit/pre-commit#1752]
Hi,
I'm working on onboarding my team at work to use pre-commit and have been running into a few issues.

My team develops in a large monorepo shared with other teams. I would like to use mypy as one of the pre-commit hooks, but mirrors-mypy does not work for us as it causes errors when we try using it against files in multiple packages at once (this is not really a pre-commit issue, but one with mypy), so I have been looking into writing our own hook specifically for this repo.

I want to install all the packages in editable mode when the hook venv is initialized. However, because we operate in a large monorepo, I'm forced to use local hooks as we don't have a setup.py at the top level to install. This causes the working directory for the `pip install .` command to happen in some temporary directory and not at the top level of the git repo, as expected. Because of this, I'm unable to use relative paths when writing the yaml file, which makes the local hook pretty much useless unless my teammates clone the repo to a hardcoded path (which would be messy if we wanted to also use pre-commit in CI).

Wouldn't it make sense if, instead of [this](https://github.com/pre-commit/pre-commit/blob/ebd83171dfa8030a9767018b231b6fb1831b082b/pre_commit/languages/python.py#L199), pre-commit did something more like

```python
install_cmd = ('python', '-mpip', 'install', os.path.abspath(prefix.prefix_dir), *additional_dependencies)
```

and then either local hooks used the current working directory or provided a way for us to specify our own? I'm aware that I can use `system` to hack my way around this, but I feel like that honestly requires far more work than me just patching pre-commit due to devs/CI using multiple OSes (so we can't just script everything out in bash), venv management, etc.

**Comment by asottile** [comment]
This is intentional, pre-commit only installs from the configuration and never the repository under test

**Comment by asottile** [comment]
You can read more about this in #730 -- also check out all the duplicates linked there as well for more information

**Comment by wchill** [comment]
Figured out a workable solution based on this comment: https://github.com/pre-commit/pre-commit/issues/1406#issuecomment-617952446

**Comment by asottile** [comment]
note that mutating the installed things inside pre-commit's cache is not supported and is likely to break in the future.  you should treat those as immutable.  you'll probably do better to set up a separate environment

**Comment by wchill** [comment]
Yep, I moved virtualenv creation and activation to the wrapper script. So there should be no problems there
