### ISSUE TITLE
node: allow to specify a minimal language_version and check system-provided version against it

### ISSUE THREAD

**Issue by dev-zero** [pre-commit/pre-commit#1757]
We're currently using [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) which uses `language: node`. Some of our devs have a system-provided version of `node` installed which is automatically picked up (which would be a good thing), but that version is too old to run the hook (cp2k/cp2k#1296). Specifying `language_version: ...` with a specific version would force the installation of recent-enough node (see  igorshubovych/markdownlint-cli#157), but means that everyone gets another installation of it.
Hence, it would be helpful if hooks could specify the minimal version of the language required to still profit from a system-provided installation if version requirements are satisfied.

**Comment by asottile** [comment]
this would be a feature request for [nodeenv](https://github.com/ekalinin/nodeenv) -- we just proxy to that

**Comment by dev-zero** [comment]
I see why you first want support for that in nodeenv (ekalinin/nodeenv#152), but the decision whether to use the system-provided by default is done in pre-commit and not nodeenv (see also ekalinin/nodeenv#153):

https://github.com/pre-commit/pre-commit/blob/ebd83171dfa8030a9767018b231b6fb1831b082b/pre_commit/languages/node.py#L33-L34

**Comment by asottile** [comment]
@dev-zero you'll notice that that branch is only taken if you don't configure `language_version`
