### ISSUE TITLE
`pre-commit` not found.  Did you forget to activate your virtualenv?

### ISSUE THREAD

**Issue by macalada** [pre-commit/pre-commit#1758]
Hello,
I am new in web development. I am trying to get pre-commit works on our website, using django framework. I am using vagrant virtual machine in this project. i installed pip install pre-commit then add the requirement.txt as well the yaml file. But i want to use our custom script " npm run style-js-fix" which called in the .sh script would that possible in this pre-commit? i kept getting above error tho.

**Comment by asottile** [comment]
please show more information and a way to reproduce your problem (including the software versions you're using, any relevant configuration and scripts).  I can't see your screen
