### ISSUE TITLE
Trying to use pre-commit, getting "pre-commit_hooks.yaml" is missing

### ISSUE THREAD

**Issue by aronchick** [pre-commit/pre-commit#1759]
I have followed the quick start as near as I can (https://pre-commit.com/#quick-start).

Here's what I did:
- Install pre-commit (via pip inside poetry)
![image](https://user-images.githubusercontent.com/51317/104396811-3d324e00-5500-11eb-99a6-114ed886e71f.png)

- Added a pre-commit-config.yaml file:
```
repos:
-   repo: git@github.com:contoso/private-repo.git
    rev: main
    hooks:
    - id: go-fmt
```
- Executed `pre-commit install`
```
pre-commit installed at .git/hooks/pre-commit
```
- Executed pre-commit --run
```
❯ pre-commit run
An error has occurred: InvalidManifestError: 
=====> /home/my_user_name/.cache/pre-commit/repox37iai_z/.pre-commit-hooks.yaml does not exist
Check the log at /home/my_user_name/.cache/pre-commit/pre-commit.log
```

I'm not sure what I'm missing - first, it's not clear to me why the cache has a unique repo name(that could be an implementation detail. But further, in the quick start, there's nothing about creating a 'pre-commit-hooks' file.

Thanks!

**Comment by asottile** [comment]
your `contoso/private-repo` doesn't have a `.pre-commit-hooks.yaml` at whatever revision you tried to install

I notice you're using `rev: main` which is [not supported](https://pre-commit.com/#using-the-latest-version-for-a-repository) and probably the problem (in the next release this will produce a warning)

**Comment by aronchick** [comment]
Oh wow - this is totally my confusion because I had mistakenly assumed that the items in the documentation were the SAMPLEs. I'm not doing any pre-commit hooks, i'm actually just trying to consume them. 

I'm not sure how to get this across differently for idiots like myself, but there you go.
