### ISSUE TITLE
failed to find interpreter when running black via pre-commit

### ISSUE THREAD

**Issue by levinotik** [pre-commit/pre-commit#1761]
I am suddenly having issues running `black` via pre-commit. Other pre-commit hooks work just fine. I have the following in my pre-commit config:

```yaml
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
```

I am using Python version 3.7.6 with pyenv. This setup has worked just fine for a long time. 

Now, when committing my changes, I get the following error:

```
### version information


pre-commit version: 2.9.3
sys.version:
    3.9.1 (default, Jan  6 2021, 06:04:49) 
    [Clang 12.0.0 (clang-1200.0.32.28)]
sys.executable: /usr/local/Cellar/pre-commit/2.9.3/libexec/bin/python3
os.name: posix
sys.platform: darwin


### error information


An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/pre-commit/2.9.3/libexec/bin/python3', '-mvirtualenv', '/Users/levinotik/.cache/pre-commit/repoc_gsawtf/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)

Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/main.py", line 347, in main
    return hook_impl(
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/commands/hook_impl.py", line 217, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/commands/run.py", line 402, in run
    install_hook_envs(hooks, store)
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/repository.py", line 206, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/languages/python.py", line 202, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/usr/local/Cellar/pre-commit/2.9.3/libexec/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/Cellar/pre-commit/2.9.3/libexec/bin/python3', '-mvirtualenv', '/Users/levinotik/.cache/pre-commit/repoc_gsawtf/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
```

I'm not sure how to resolve this or whether this is actually an upstream issue in black. Any ideas? Thanks

**Comment by asottile** [comment]
what does `cd / && python3.7 --version` give you? additionally what does `virtualenv venv -ppython3.7` give you?

Also do you need to run `black` with `python3.7`? does `language_version: python3` work?

Note that the messaging there is coming from `virtualenv` so it isn't pre-commit's problem but I'm willing to try and help you anyway

**Comment by levinotik** [comment]
Thanks a lot, really appreciate it. Interesting, I had `language_version: python3.7` in my `black` settings in `pre-commit-config.yaml`. Changing that to `language_version: python3` does seem to resolve the issue!

Here's what I get for the things you asked about:

```
$ cd / && python3.7 --version
direnv: unloading
pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.6
  3.7.7

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

and 

```
$ virtualenv venv -ppython3.7
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
```

**Comment by asottile** [comment]
that indicates you've misconfigured pyenv

**Comment by asottile** [comment]
I'm no expert on pyenv, and I recommend against it because of issues like you're encountering, but you can probably fix it with something like `pyenv global 3.7.6`

**Comment by levinotik** [comment]
Ah ok, thank you. What do you recommend instead of pyenv or do you not use Python version management tools altogether?

**Comment by asottile** [comment]
I don't really work on macos all that much, but I used to use the python.org installers + brew for the latest(ish) version

my main environment is ubuntu where I use (and maintain) deadsnakes

**Comment by levinotik** [comment]
Gotcha. Makes sense. Thanks so much for helping even though this wasn't a `pre-commit` issue.

**Comment by ed-graham** [comment]
I have just had exactly the same issue as @levinotik - I am using Python 3.8 (rather than 3.7) and working under Windows 10 21H1.  Changing from `language_version: python3.8` to `language_version: python3` in the config.yaml file worked for me, too.
