### ISSUE TITLE
Support for other types of hooks

### ISSUE THREAD

**Issue by psacawa** [pre-commit/pre-commit#1762]
Is there are reason why only some types of hooks are supported? I am interested in the `post-merge` hook that checks whether any documentation source files have been changed, and rebuilds them to html and prints them if they have. I would like to run it as a `post-merge` hook so it runs on `git pull`. 

The documentation suggests this is not supported. Is there a workaround? Is there a technical obstruction to this use case?

**Comment by asottile** [comment]
nope! just needs someone to implement the other hooks.  They've been implemented as needed

if you want to try your hand at adding one, you might want to take a look at one of the others that's been implemented

for example, here's the commit which added `post-commit` support: 26adf1d560d24a4c5764c6cb42e66dc2c876b18f

**Comment by psacawa** [comment]
This seems not hard, especially since `post-merge` is simple, so I'll try this.

**Comment by asottile** [comment]
@psacawa did you have a change to take a look at this?

**Comment by psacawa** [comment]
Yes, however I didn't create any tests, so I didn't submit a pr: 317ac637979ca083d439d6523383fb1c73971bf7
This is unfortunately low on my list of priorities. What's there is the easy part.
