### ISSUE TITLE
Config discovery is wrong

### ISSUE THREAD

**Issue by skorokithakis** [pre-commit/pre-commit#1767]
I have a repository that looks like this:

```
.
├── .pre-commit-config.yaml
└── python
    ├── foo
    └── .pre-commit-config.yaml
```

If I `cd python/foo` and run `pre-commit run`, it will use the *top-level* pre-commit config, whereas I would have expected it to use the one immediately above (the config for Python files). Is this correct behaviour?

**Comment by asottile** [comment]
> If I cd python/foo and run pre-commit run, it will use the top-level pre-commit config

your assertion is incorrect, I'd recommend in the future actually showing output when you're making a claim

```console
$ tail -n999 .pre-commit-config.yaml  foo/.pre-commit-config.yaml 
==> .pre-commit-config.yaml <==
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

==> foo/.pre-commit-config.yaml <==
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
$ cd foo/
$ pre-commit run
Trim Trailing Whitespace.................................................Passed
$ cd ..
$ pre-commit  run
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
```

**Comment by skorokithakis** [comment]
```bash
stavros@talos:/t/test (master|…) 
19:41:31 $ tail -n999 .pre-commit-config.yaml  python/.pre-commit-config.yaml
==> .pre-commit-config.yaml <==
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

==> python/.pre-commit-config.yaml <==
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace

stavros@talos:/t/test (master|…) 
19:41:36 $ cd python/foo/

stavros@talos:/t/t/p/foo (master|✔) 
19:41:42 $ pre-commit run -a
Trim Trailing Whitespace.............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Check for added large files..........................(no files to check)Skipped
```

**Comment by asottile** [comment]
you must be on an old version then -- please do some debugging

**Comment by skorokithakis** [comment]
```
stavros@zeus:/t/t/p/foo (master|✔) 
20:05:22 $ pre-commit --v run
pre-commit 2.9.3

stavros@zeus:/t/t/p/foo (master|✔) 
20:05:33 $ pre-commit run -v
Trim Trailing Whitespace.............................(no files to check)Skipped
- hook id: trailing-whitespace
Fix End of Files.....................................(no files to check)Skipped
- hook id: end-of-file-fixer
Check Yaml...........................................(no files to check)Skipped
- hook id: check-yaml
Check for added large files..........................(no files to check)Skipped
- hook id: check-added-large-files
```

I did do some debugging; this is a bug, please reopen.

**Comment by asottile** [comment]
ah I see, you're misunderstanding then, let me explain

`pre-commit run` is the equivalent to `pre-commit run --config .pre-commit-config.yaml`

git hooks always run from the root of the repository, so the convention is to put the file there.  if you've put the file anywhere else you need to use `--config` to reference it.

some attempts are made when normalizing the working directory to retain an absolute reference to the pre-commit configuration passed on the commandline as `--config`.  if `./.pre-commit-config.yaml` exists (since it matches the `--config` option) that will be retained

otherwise the default is discarded (if it is the default) and the root of the repository is used

note that there can only be one set of git hooks for a repository, so setting up configurations in the manner you're suggesting does not make sense -- but you can still enable it by explicitly using `--config`

**Comment by skorokithakis** [comment]
> so setting up configurations in the manner you're suggesting does not make sense

I just want the config file discovery to follow standard git practice (where e.g. `.gitignore` files are searched upwards towards the root until one is found). I only ever want one set of git hooks for a repository, I'm not saying they should be inheritance.

I don't know if this behaviour is desired, but it was surprising to me and a colleague, so I thought I'd open an issue/feature request.

**Comment by asottile** [comment]
>  standard git practice

that's nonsense as a precedence.  there's no cascading and there's only one set of hooks per repository so a suggestion of the sorts is irrelevant.  git always executes git hooks from the root of your repository so it would have no way of knowing what subdirectory you are in.

that `--config` is supported at all is an escape hatch to allow you to do unsupported things and it will not be extended in the way you're suggesting as it gives the impression that cascading and alternate directories are a suggested or supported approach.  if you want a weird setup as you're suggesting, use `--config` explicitly
