### ISSUE TITLE
Setting PRE_COMMIT_HOME in an .env file

### ISSUE THREAD

**Issue by giuliogiaconi** [pre-commit/pre-commit#1774]
Hi, I have a question about using `pre-commit` with environment variables. I am sorry if this question was already addressed somewhere else, but I couldn't find this specific information anywhere. 

In my repository I manage environment variables through an `.env` file, which I load onto python scripts using the `python-dotenv` package. 

In particular, in the `.env` file I also set the `PRE_COMMIT_HOME`, which is used by `pre-commit` as described [here](https://pre-commit.com/#managing-ci-caches). My question is: How can I ensure `pre-commit` runs using the `PRE_COMMIT_HOME` environment variable defined in the `.env` file? I assume I should use a flag or option inside the `.pre-commit-config.yaml` file, but I couldn't find a way to do this. I am asking this as I'd like to avoid the need to set  `PRE_COMMIT_HOME` manually, and I'd like that variable to be set automatically while committing. 

Just wanted to note that I have defined various pre-commit plugins inside the `pre-commit-config.yaml`. OS is Windows (in case terminal commands are needed). Thanks.

**Comment by asottile** [comment]
why are you setting `PRE_COMMIT_HOME` at all?  it's not intended for normal use (only for static use in CI)

if your goal is a per-project pre-commit cache, you're missing the point of the cache and intentionally making your runs slower and take more disk.  pre-commit intentionally does not install from projects-under-test such that the cache can be shared

no such thing exists in pre-commit and I don't think teaching pre-commit about `.env` is a good idea -- this would really be up to your environment configuration (perhaps by using something like [`aactivator`](https://github.com/Yelp/aactivator)? or in your shell's startup rc files)

**Comment by giuliogiaconi** [comment]
Hi @asottile, thanks for your quick reply. I think I know what you mean, but, unfortunately, I need to set `PRE_COMMIT_HOME` as I don't have admin rights on the default location `~/.cache/pre-commit`. Because of this, if I don't modify this environment variable I run into an error related to the impossibility of running `python.exe`.

Setting `PRE_COMMIT_HOME` to be a specific path where I have admin rights solves the issue and enables me to run `pre-commit` correctly. However, at the moment I am doing that manually on Windows terminal, whereas I am looking for a way to achieve this via python, .e.g. via `python-dotenv` (as I am using this on my project). 

Do you have any thoughts on how to achieve this in a nice way? I thought I could somehow instruct `.pre-commit-config.yaml` about the presence of `PRE_COMMIT_HOME` being set as specified in `.env` - maybe using the Windows shell as a flag?

**Comment by asottile** [comment]
seems very odd that you wouldn't have rights on *your own home directory* ? are you sure that's the source of your error?

iirc windows terminal is a powershell variant so you could set it in your powershell startup scripts, from some googling those live in `%UserProfile%\Documents\Windows­PowerShell\profile.ps1`

**Comment by giuliogiaconi** [comment]
Yes, I am sure because that is not my personal computer.

Do you mean, setting the environment variable after pc startup? I was thinking about setting the variable up only when running `pre-commit`. Is there an equivalent of  `load_dotenv()` that can be used within the `pre-commit-config.yml` file for example? Or maybe I can run windows terminal, similar to [a previous suggestion of yours](https://github.com/pre-commit/pre-commit/issues/758#issuecomment-505935221). In the latter case, could you please help me out with the specific command?

**Comment by asottile** [comment]
there is not, nor will there be something like `load_dotenv` in pre-commit

my suggestion is as above, set `PRE_COMMIT_HOME` in your dotfiles
