### ISSUE TITLE
Batching calls to the hook?

### ISSUE THREAD

**Issue by talbright** [pre-commit/pre-commit#1775]
I'm working on developing a hook (written in go, but the behavior below is the same using bash), and noticed that the files get sequenced to the hook in batches. Is there anyway to control this behavior? I need to analyze all the changes before decides what actions to take.

For example: 

```
$ pre-commit try-repo ../builds-shared helmut --verbose --all-files
[WARNING] Creating temporary repo with uncommitted changes...
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /var/folders/hn/42vq29n96j5269vgnnzyg5z80000gp/T/tmp080d24hw/shadow-repo
    rev: b555db18f2c8aa74c75ab18873a13d35fb9f4140
    hooks:
    -   id: helmut
===============================================================================
[INFO] Initializing environment for /var/folders/hn/42vq29n96j5269vgnnzyg5z80000gp/T/tmp080d24hw/shadow-repo.
[INFO] Installing environment for /var/folders/hn/42vq29n96j5269vgnnzyg5z80000gp/T/tmp080d24hw/shadow-repo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
helmut...................................................................Passed
- hook id: helmut
- duration: 0.14s

root cmd with args: [make/include/spinnaker.mk .pre-commit-hooks.yaml go.mod pre-commit/cmd/helmut/commands/root.go]
root cmd with args: [make/include/helm-umbrella.mk make/include/artifacts.mk README.md pre-commit/hooks/hello.sh]
root cmd with args: [pre-commit/cmd/helmut/main.go make/include/factors.mk go.sum pre-commit/hooks/helmlint.sh]
root cmd with args: [make/include/helm.mk make/include/version.mk]
```

**Comment by asottile** [comment]
yes and no

the batching you're seeing is due to multiprocessing implemented for speed.  you can disable the multiprocessing with [`require_serial: true`](https://pre-commit.com/#hooks-require_serial) (looks like your computer has 4 processors!)

note that this does not guarantee that all filenames will be passed in a single invocation, however it may appear that way for small numbers of files.  this is because there is a limit to the command line length (and on some platforms, such as windows, it is especially small!)

pre-commit [implements a portable version of `xargs`](https://github.com/pre-commit/pre-commit/blob/7727f8777aeedafb567da063fc911414b46a6a3b/pre_commit/xargs.py) which ensures that command line invocations are not too long

**Comment by asottile** [comment]
> I need to analyze all the changes before decides what actions to take.

note that this isn't possible in the general case -- due to command line length limits (so you may want to adjust your tool's design to fix this problem)

**Comment by talbright** [comment]
Thanks for answering my question.

> > I need to analyze all the changes before decides what actions to take.
> 
> note that this isn't possible in the general case -- due to command line length limits (so you may want to adjust your tool's design to fix this problem)

That makes sense.

> the batching you're seeing is due to multiprocessing implemented for speed. you can disable the multiprocessing with require_serial: true (looks like your computer has 4 processors!)

Actually I did add this setting, and I was surprised it didn't change the behavior. 

```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: ../builds-shared/pre-commit
    rev: 26fa7ab4d3be22635470315d3e7ba6b50fabea766
    require_serial: true
    stages: [commit]
    hooks:
    -   id: hello
    -   id: helmut
```

Thanks again!

**Comment by asottile** [comment]
show your output, then read what it says :)
