### ISSUE TITLE
Excluding a filetype from a single directory

### ISSUE THREAD

**Issue by wwuck** [pre-commit/pre-commit#1780]
The docs at https://pre-commit.com/#filtering-files-with-types mention `types, types_or, and files are evaluated together with AND when filtering.`

I couldn't find whether a similar relation applies to `exclude` and `exclude_types`.

My use case is to exclude some autogenerated python code files in a specific directory while still including all other files in that directory and all other python files elsewhere, and I thought it would be easier to use a combination of `exclude: "^generated/` and `exclude_types: ["python"]` instead of a more complex regex with just `exclude`.

**Comment by asottile** [comment]
presumably you just need `exclude`?

could you elaborate on what files you have and intent to match / not match?

**Comment by wwuck** [comment]
I have a repository containing some Protocol Buffer .proto files, which then get transformed into generated .py files by the protoc compiler.  These will end up in multiple subdirectories of a top-level `proto` directory.
eg.
```
$ find .
.
./setup.py
./src
./src/project
./src/project/tests
./src/project/tests/project_test.py
./src/project/project.py
./src/project/__init__.py
./proto
./proto/main_pb2.pyi
./proto/main_pb2_grpc.py
./proto/main_pb2.py
./proto/main.proto
./proto/sub1
./proto/sub1/sub1_pb2.pyi
./proto/sub1/sub1_pb2_grpc.py
./proto/sub1/sub1_pb2.py
./proto/sub1/sub1.proto
./proto/sub1/sub2
./proto/sub1/sub2/sub2_pb2.pyi
./proto/sub1/sub2/sub2_pb2_grpc.py
./proto/sub1/sub2/sub2_pb2.py
./proto/sub1/sub2/sub2.proto
```

I am wanting to run pre-commit on every file here except for the `_pb2.py` and `_pb2_grpc.py` generated files in `./proto` as they won't match the other project files in regards to end-of-file-newlines, etc.

If nothing else is supported, I will try to write a regex to cover this (unknown number of subdirectories for excluding .py files).

**Comment by asottile** [comment]
yeah you want `exclude: ^proto/.*\.py$`

**Comment by luchaoqi** [comment]
Hi, is there any way we can set top-level `exclude_types` like `exclude_types: ['symlinks', 'directory']` if I want to exclude symlinks and submodules for all hooks?

**Comment by asottile** [comment]
you shouldn't need to, they are excluded by default
