### ISSUE TITLE
pre-push is executed several times during a single push

### ISSUE THREAD

**Issue by alessandro308** [pre-commit/pre-commit#1783]
I don't know if it is a bug or a desired behaviour. I have a pre-push installed that runs a script:

```
-   repo: local
      hooks:
        -   id: Karma Test
            name: Run Karma Test
            stages: [push]
            language: system
            files: '.*\.js$'
            entry: bash -c 'cd ionicApp && ./node_modules/karma/bin/karma start karma.conf.js --autoWatch=false' --
        -   id: Check Translations Strings
            name: Check Translations Strings
            stages: [push]
            language: system
            entry: bash -c 'cd ionicApp && yarn check_strings' --
```

The  `yarn check_strings` is only an execution of the python `scripts/check_strings.py` script that does several stuff but at the beginning it prints its pid:
```
import os
print('RUNNING', os.getpid())
```

Reading the output looks like the script is executed several times (some times 1, some other times 2 or 3 times):
```
11:24 $ git push origin HEAD
Check Translations Strings...............................................Failed
hookid: Check Translations Strings

yarn run v1.17.3
$ python3 scripts/check_strings.py src/
RUNNING 12264 <<<------------------------------------------------------------------------
Not found key CHAT.LEAVE.POPU1P.TITLE
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.17.3
$ python3 scripts/check_strings.py src/
RUNNING 12263 <<<------------------------------------------------------------------------
Not found key CHAT.LEAVE.POPU1P.TITLE
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
error Command failed with exit code 1.
```

Do you have any feedback on it? Is it a bug or I have to specify to run it only once?

**Comment by alessandro308** [comment]
I just found a solution in another thread. The script is executed one time for each file type in the push. In order to avoid it I added `pass_filenames: false` as option. My question is, in case the hooks specify the `files` like `files: '.*\.js$'`, is it still executed several times for each file type pushed?

**Comment by asottile** [comment]
pre-commit [passes files to hooks](https://pre-commit.com/#arguments-pattern-in-hooks).  it also uses multiprocessing to speed things up

you can disable file passing using [`pass_filenames: false`](https://pre-commit.com/#hooks-pass_filenames) 

> The script is executed one time for each file type in the push.

this isn't quite true, files are batched and split across processes

> My question is, in case the hooks specify the files like files: '.*\.js$', is it still executed several times for each file type pushed?

I mean, pretty easy for you to check in the same way you were checking.  but no if you use `pass_filenames: false` then it will obviously not pass filenames

**Comment by asottile** [comment]
by the way, to perform better I'd suggest moving your scripts to operate on filenames -- the framework is designed around that and it will speed up your (incremental) checks
