### ISSUE TITLE
Show delta to main branch

### ISSUE THREAD

**Issue by blackliner** [pre-commit/pre-commit#1791]
We are using a handwritten `prepare-commit-msg` script right now, which accumulates the changes of the current branch compared to the main branch, and spits out a nice summary for the dev. This way they get regular feedback how big their PR would be, as we want them to be small and focused. It looks like this:
```
# Branch size statistics
# Changed lines: 109/250 43%
```

Would something like this also be possible with `pre commit`

**Comment by asottile** [comment]
wrong repository, pre-commit/pre-commit-hooks is a set of tools -- not the framework

___

yes, [as of 1.16.0 pre-commit supports the `prepare-commit-msg` git hook](https://pre-commit.com/#pre-commit-for-commit-messages)
