### ISSUE TITLE
How to execute a bash/script command, after clone, and before setup install?

### ISSUE THREAD

**Issue by jfaleiro** [pre-commit/pre-commit#1796]
We need to run a bash script during `pre-commit install` of a `python` language hook. 

The script tags a numeric version in a file and should be executed after `git clone` and before `setup install`. Is there a direct way to do it now?

**Comment by asottile** [comment]
I'm not 100% sure what you're asking -- but maybe this answers it?

I think the only git hook that helps you with that is `post-checkout`  -- it looks like `pre-commit` already supports that hook: https://pre-commit.com/#pre-commit-for-switching-branches

as for directly after `git clone` -- the only way to hook into that is via git templating -- for instance usage with `init-templatedir`: https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

**Comment by jfaleiro** [comment]
Thanks for the quick reply. Yes it does answer. The best (simplest?) workaround is then to commit an invalid version file to the hook's git repository and skip the need for the bash/script command altogether at this point. Ugly, but works.
