### ISSUE TITLE
Provide guidance on a docker-in-docker CI image

### ISSUE THREAD

**Issue by mattyclarkson** [pre-commit/pre-commit#1798]
We would like to run Docker hooks in a our `pre-commit`  CI run. This requires using [docker-in-docker official image](https://hub.docker.com/_/docker/). These are based on Alpine Linux which forces handling the default `musl` library situation.

The following works but is non-obvious if you are not familiar with the requirements for various hooks to compile dependencies.

- `git`: required for `pre-commit` to be able to download the hooks
- `gcc`: required for compiling any `npm`/`pip` dependencies
- `libgcc`: required for `nodeenv`
- `libstdc++`: required for `nodeenv`
- `musl-dev`: required to provide `libc` headers for dependency compilation
- `py3-pip`: used to install a specific version of `pre-commit` so the `Dockerfile` is reproducible

```
FROM docker:20.10.3

# Install tools
RUN apk add --no-cache \
      git \
      gcc \
      libgcc \
      libstdc++ \
      python3-dev \
      musl-dev \
      py3-pip

# Create unprivileged user
RUN addgroup -S ci \
 && adduser -S -G ci -u 1000 ci
USER ci
WORKDIR /home/ci

# Add pip binaries to PATH
ENV PATH /home/ci/.local/bin:$PATH

# Add a specific version of pre-commit
RUN pip3 install --user --no-cache-dir pre-commit==2.10.1
```

I can't confirm that it will work with _every_ hook but it works with _our_ hooks `prettier`, `black`, `mypy`, `clang-tidy`, `clang-format` (the latter two using Docker images).

Just wondering if we want to document this somewhere, or collaborate on a common Docker hub image?

**Comment by paulhfischer** [comment]
you can have a look at the [pre-commit.ci runner image](https://github.com/pre-commit-ci/runner-image), which is used by [pre-commit.ci](https://pre-commit.ci/) to run pre-commit in a docker container.

(or, you could simply use pre-commit.ci which also has some nice features like automatically updating your hooks, autofixing and caching for [fast runs](https://github.com/pre-commit-ci-demo/demo#results))

**Comment by asottile** [comment]
you'll probably have better mileage by installing `node` instead of trying to get the whole nodeenv toolchain working (pre-commit will default to an existing `node` installation instead of bootstrapping one if available)

I don't have plans for an official image because it can't possibly satisfy everyone's needs without being extremely large -- the pre-commit.ci image is the closest to that currently and I plan to split it up into "components" to reduce its size
