### ISSUE TITLE
Ability to run subset of hooks, not just one

### ISSUE THREAD

**Issue by ehontoria** [pre-commit/pre-commit#1803]
Hi folks! Wondering if adding the ability to run a subset of checks rather than just one is possible.
For example, instead of only being able to run a `black` check: `pre-commit run black`. Be able to run something like `pre-commit run black,flake8` to run the `black` and `flake8` checks.

This would be especially useful for me since I am working on creating a shared pre-commit container/configuration for multiple repositories, but not all of them want to run every available check (only a subset).

I'm also aware there is a workaround for this, running something like `pre-commit run black && pre-commit run flake8` but figured another solution may be more elegant.

**Comment by asottile** [comment]
there's `&&` and there's `SKIP` -- both of which allow you to run multiple hooks

**Comment by ehontoria** [comment]
Ah I see so there is the negative case of skipping, but not the positive case of opting in for only certain hooks. I'm fine with using the existing workarounds. I think it would be cool to include the positive case still, but you're right that there is an existing way to get the functionality I'm interested in.

Thank you so much for the quick response.

**Comment by asottile** [comment]
note that shared configuration is kind of the opposite of the goals of pre-commit -- each repository has its own unique needs and should have its own configuration.  a shared configuration is impossible to upgrade / downgrade without breaking some subset of the repositories it is applied to (consider upgrading black for instance which changes the formatting -- you can't possibly upgrade a centrally managed thing without causing repositories to be in a broken state for some time)

this is why the pre-commit configuration is meant to be version controlled with the repository it self, such that any version of the repo you check out should pass the linting at that point in time

**Comment by christhekeele** [comment]
I'd really benefit from this. I have a great many hooks, organized into "suites" (auto-formatters, linters, typecheckers) I want to run together (as a little script).

### Current options

#### `&&`

```bash
# file: bin/format
pre-commit run json-formatter && pre-commit run python-formatter && ...
```

##### CON
This has to re-stash between every single hook, which is really adding up

#### `SKIP`

```bash
# file: bin/format
SKIP=enumerate,every,single,non-format,hook... pre-commit run
```

##### CON
This is much harder to understand and maintain

### Desired option

```bash
# file: bin/format
pre-commit run json-formatter python-formatter...
```

**Comment by brandon-leapyear** [comment]
Likewise, even support for globs, like
```bash
pre-commit run '*-formatter'
```
which would run all hooks matching the pattern
