### ISSUE TITLE
Allow to silence passed and/or skipped hooks

### ISSUE THREAD

**Issue by armcknight** [pre-commit/pre-commit#1805]
Hello, first issue! Thanks for making such a great tool, we love it at work.

We have a monorepo, and for various reasons I'll have a bunch of skipped hooks when committing because I'm only working on one of several languages in our codebase. I'd love a way to silence skipped hooks so I only see passing/failing hooks. I imagine I might want to also silence passing hooks to keep my scrollback clean.

It looks like just a few statements would need an additional condition passed down from a new argument or two for the main invocation of the command, [here](https://github.com/pre-commit/pre-commit/blob/d827e9aa7211456965bf7d16f06ac6a85b0f2984/pre_commit/commands/run.py#L156-L164), [here](https://github.com/pre-commit/pre-commit/blob/d827e9aa7211456965bf7d16f06ac6a85b0f2984/pre_commit/commands/run.py#L171-L180) and [here](https://github.com/pre-commit/pre-commit/blob/d827e9aa7211456965bf7d16f06ac6a85b0f2984/pre_commit/commands/run.py#L208).

I reread the docs and ran a few searches through your issues, so sorry if this is covered already!

**Comment by asottile** [comment]
dupe #823

**Comment by asottile** [comment]
you should consider proposing that your work sponsors the project :P
