### ISSUE TITLE
Extending the PATH of the original virtualenv into pre-commit's virtualenv

### ISSUE THREAD

**Issue by dinoshauer** [pre-commit/pre-commit#181]
Hey guys, currently I have an [open issue on the python-import-sorter pre-commit hook.](https://github.com/FalconSocial/pre-commit-python-sorter/issues/9)

I seem to have boiled the problem down to the fact that when the hook is running in pre-commit's virtualenv it doesn't have access to the PATH of the original virtualenv so it won't know which packages are third-/first-party - My troubleshooting is documented in the original issue above :)

Let me know if you need more info!

**Comment by asottile** [comment]
@Dinoshauer I've started working on it here: https://github.com/asottile/reorder_python_imports

From what I can tell it works pretty well? Mind poking around with it and see if it works for you?

**Comment by Dinoshauer** [comment]
@asottile I'll check it out and get back to you :)

**Comment by Dinoshauer** [comment]
Eureka, it works! :+1:
