### ISSUE TITLE
Executable not found with simple Python script hook

### ISSUE THREAD

**Issue by kokkonisd** [pre-commit/pre-commit#1810]
I'm relatively new to this framework so there are things I might not understand. I've read the doc carefully but I can't seem to get this to work.
So what I want to do is build a very simple Python-script-based hook. I basically just want the hook to run a Python script, nothing more. Thus, I don't define it as a _Python package_, but rather a system executable (it is guaranteed that, in the environment it will be run, a Python interpreter will always be available in the PATH).

Let's say I have the following directory structure:

```
my_hooks/
    my_python_script_hook/
        python_script_hook.py
    .pre-commit-hooks.yaml

my_project/
    ...
```

The `.pre-commit-hooks.yaml` file looks like this:

```
- id: my-python-script-hook
  name:  My Python script hook
  entry: my_python_script_hook/python_script_hook.py
  language: system
```

If I run `pre-commit try-repo . my-python-script-hook --all-files --verbose` in the `my_hooks/` directory it runs correctly, since it basically runs `./my_python_script_hook/python_script_hook.py`, and the file is an executable, has a correct shebang and so on.

However, if I run `pre-commit try-repo ../my_hooks my-python-script-hook --all-files --verbose` in the `my_project/` directory, as stated in the [doc](https://pre-commit.com/#developing-hooks-interactively), I get:

```
Executable `my_python_script_hook/python_script_hook.py` not found
```

My guess is that it's looking for it locally in the repo, but why would it do that? Aren't entry points obviously relative to the hook repo?

How are we supposed to handle this, without having to define a Python package to be installed via `setup.py` and so on? I just want to run an executable.

**Comment by asottile** [comment]
[`language: system`](https://pre-commit.com/#system) is "look it up on the `PATH`" -- you want [`language: script`](https://pre-commit.com/#script)
