### ISSUE TITLE
get_root incorrectly identifies root of workspace in git directory

### ISSUE THREAD

**Issue by admorgan** [pre-commit/pre-commit#1816]
[git subrepo](https://github.com/ingydotnet/git-subrepo) does work on worktrees in the .git/tmp/subrepo directory. git properly recognizes that this is a worktree; using git rev-parse --is-inside-git-dir returns false. get_root looks like it should resolve to an equivalent of git rev-parse --show-toplevel which in this directory returns the expected path, but the workaround for strange Windows behavior is causing this to fail.

I understand it is strange to have worktrees in the $GIT_DIR, but it works really well for what git subrepo does

**Comment by asottile** [comment]
please show what you're seeing and what you expect to see

**Comment by admorgan** [comment]
Shell output

```
git-subrepo: Command failed: 'git worktree add .git/tmp/subrepo/tools/waf-garmin-tools subrepo/tools/waf'.
Preparing worktree (checking out 'subrepo/tools/waf')
HEAD is now at 7d11c8bc1 Merge master into waf-2.0
An error has occurred: FatalError: git toplevel unexpectedly empty! make sure you are not inside the `.git` directory of your repository.
Check the log at C:\tools\.cache\pre-commit\pre-commit.log
```

pre-commit.log

>### version information
>
>```
>pre-commit version: 2.9.3
>sys.version:
>    3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
>sys.executable: c:\python36\python.exe
>os.name: nt
>sys.platform: win32
>```

>### error information

>```
>An error has occurred: FatalError: git toplevel unexpectedly empty! make sure you are not inside the `.git` directory of your repository.
>```

>```
>Traceback (most recent call last):
>  File "c:\python36\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
>    yield
>  File "c:\python36\lib\site-packages\pre_commit\main.py", line 330, in main
>    _adjust_args_and_chdir(args)
>  File "c:\python36\lib\site-packages\pre_commit\main.py", line 147, in _adjust_args_and_chdir
>    toplevel = git.get_root()
>  File "c:\python36\lib\site-packages\pre_commit\git.py", line 66, in get_root
>    'git toplevel unexpectedly empty! make sure you are not '
>pre_commit.errors.FatalError: git toplevel unexpectedly empty! make sure you are not inside the `.git` directory of your repository.
>```

I would expect the post-checkout hook to trigger on the worktree like normal. This happens if the worktree is located outside the $GIT_DIR.

**Comment by asottile** [comment]
thanks, next time please lead with that -- without it nobody can find your issue and I can't even start to triage -- it also prevents you from potentially rabbit holing on something irrelevant

do you have any suggestions on how to handle this? subtrees are already a little weird and if you're putting them inside the `.git` directory that seems strange as well -- but certainly doable if you can come up with a suggestion and/or patch

**Comment by asottile** [comment]
the error message at least is correct -- you are inside the `.git` repo, so this isn't a bug but a feature suggestion

**Comment by admorgan** [comment]
While trying to find a workaround I have discovered that this works fine on Linux, but not on Windows. It makes me concerned about finding a solution that works everywhere. I know that you have encountered the same issue, numerous times with other issues. Can you give me a feel for how much I can count on CI to determine compatability?

**Comment by asottile** [comment]
the CI has been improved a lot lately to try and capture these odd git corner cases (and probably would want for another test to handle your particular usecase as well) -- it should be a pretty good representation.  otherwise, there's free windows VMs from https://modern.ie if that's more your style

**Comment by admorgan** [comment]
I should have been more clear. The current implementation works correctly on Linux, but work forces me to use Windows, where I discovered this. I am mostly worried about things like MacOS which I don't have any systems I can try it.

**Comment by asottile** [comment]
ahhhhhh of course I was thinking about that backwards 🙃 -- yeah the CI should be pretty good about this particular feature (there's also many fewer edge cases for it on non-windows platforms)

**Comment by admorgan** [comment]
Fixed by f9fbe18abf44a55fb6a67b9601053fcee8979d12.

**Comment by asottile** [comment]
I think this is actually the commit that fixed it: https://github.com/pre-commit/pre-commit/commit/f75fc6b2a85a61e50a0270d24a3589a083f1c06c

we should probably add a test for the particular usecase you're describing just so it doesn't break in the future

**Comment by admorgan** [comment]
Isn't there already one? 

def test_get_root_bare_worktree(tmpdir):
    src = tmpdir.join('src').ensure_dir()
    cmd_output('git', 'init', str(src))
    git_commit(cwd=str(src))

    bare = tmpdir.join('bare.git').ensure_dir()
    cmd_output('git', 'clone', '--bare', str(src), str(bare))

    cmd_output('git', 'worktree', 'add', 'foo', 'HEAD', cwd=bare)

    with bare.join('foo').as_cwd():
        assert git.get_root() == os.path.abspath('.')

**Comment by admorgan** [comment]
BTW, I really want to compliment you on your excellent issue handling skills.

**Comment by asottile** [comment]
yeah that's for a bare repository, I think your usecase is a non-bare repo if I'm reading correctly? (should be the same, but will be ~slightly different)
