### ISSUE TITLE
Automatically apply changes and retry or only run if previous hooks succeeded

### ISSUE THREAD

**Issue by sondrelg** [pre-commit/pre-commit#1817]
Hi,

First of all thanks for the awesome framework. Pre-commit is great 👏  

I often find myself running pre-commit by adding my changes with `git add` and then committing. Then, typically it will "fail" because just one or two lines will be fixed by one of the hooks (typically `black`), and I will re-run the git commands once more to finish committing my changes.

This doesn't take much effort, but running everything twice it is a pattern I repeat almost every time I commit something: Would you ever consider adding an option to automatically re-committing the changes made by individual hooks? As in, say you could specify in the config that if `black` makes changes, pre-commit should simply add those changes to the staged diff, before running the hook once more, and then running the remaining hooks?

To prevent the [xy problem](https://en.wikipedia.org/wiki/XY_problem): the underlying reason why running pre-commit twice can sometimes be inconvenient in the first place, is because we have several static checkers like `flake8` and `mypy` which we don't really *want* to run until all code changes are out of the way. Our `mypy` hook in particular can take up to 10-15 seconds to run, and as a consequence I will usually interrupt pre-commit after the first few hooks have run (if one "failed") and re-run all commands.

Finally, I recognise that there might be good reasons why this doesn't make sense; that pre-commit could be built in a way where it's not worth a complete restructuring to implement such a feature; or that perhaps my workflow is just sub-optimal, so this is primarily a question over a feature request 🙂 

Thanks!

**Comment by MarcoGorelli** [comment]
Hi @sondrelg - have you seen #1782 #1706 #1342 #1246 #1188 #1099 #1086 #879 #806 #999 #747 ?

**Comment by sondrelg** [comment]
I tried search for relevant tickets, but couldn't find any. I'll read these, thanks!

**Comment by sondrelg** [comment]
@MarcoGorelli thanks again for the quick response. Definitely understand about not wanting to stage things automatically.

Just one final follow up question if you don't mind: What do you think about preventing hooks from running instead? If I could tell mypy, flake8, and other static checkers to skip running if a previous hook had failed, that would also be very nice.

Has this also been asked 100x? 😅  If so, apologies

**Comment by asottile** [comment]
yes that's the [`fail_fast`](https://pre-commit.com/#top_level-fail_fast) option

**Comment by sondrelg** [comment]
Thanks 👏👏👏👏
