### ISSUE TITLE
Run pre-commit.ci on branch push

### ISSUE THREAD

**Issue by ajhynes7** [pre-commit/pre-commit#1822]
Hello,

I have `pre-commit.ci` configured to run on a GitHub repository. I can see on the website that it's running `pre-commit` on PRs, and on the `master` branch when a PR is merged.

I see this on the website:

> pre-commit.ci will run on all pull request commits, but will not push for commits made by bots.

I'm wondering if there's a way to make it run on every push to a non-master branch? Or if this is a feature that could be added?

Thanks very much for this great tool.

**Comment by asottile** [comment]
I can't transfer issues but this is the wrong project -- you want [pre-commit-ci/issues](https://github.com/pre-commit-ci/issues)

pre-commit.ci will not push to non-PRs, you can open a draft PR for the branch in question if you want pre-commit.ci to run against it
