### ISSUE TITLE
Question: does pre-commit need to be available in the environment in which hooks are run?

### ISSUE THREAD

**Issue by sam-hoffman** [pre-commit/pre-commit#1823]
I have a project containing multiple different conda environments. I'd like to use pre-commit hooks in this project, but it's not clear to me whether pre-commit needs to be installed and available in all the environments. Apologies in advance if this is covered in the documentation, I didn't see it but wanted to be sure!

**Comment by asottile** [comment]
it does not, just somewhere on your system and available on the `PATH`

**Comment by asottile** [comment]
I'd encourage you to just try it and validate your assumptions -- going to be faster than asking :)
