### ISSUE TITLE
How to avoid downloading dependencies manually?

### ISSUE THREAD

**Issue by dudicoco** [pre-commit/pre-commit#1824]
Hi,

Some hooks require external dependencies to be installed, for example: `terraform`, `shellcheck`, `hadolint` etc.

In order to make it easier for individuals who use the repository to run pre-commit without manually installing all of the necessary binaries, I would like to know if one of these options is possible:
1. Automatically install the dependencies for the user.
2. Supply a docker image which includes all of the dependencies and have pre-commit run this image.

Any other solutions are welcomed!

Thanks

**Comment by asottile** [comment]
the best way is to add language support for the particular language the tool is written in, or write a wrapper a supported language (for example [shellcheck-py](https://github.com/shellcheck-py/shellcheck-py))

there's also the ability to leverage `docker` or `docker_image` languages, though the pure language support is preferable

**Comment by dudicoco** [comment]
@asottile thank you for the response.

Can you please elaborate on the possible options?
For example, if i'm using the following hook: https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L53-L59
How can I use it without downloading the `terraform` binary?

**Comment by asottile** [comment]
since terraform is written in `go`, you can probably hook it through using `additional_dependencies: [...]`, though I haven't tried that before

**Comment by dudicoco** [comment]
@asottile do you have a suggestion for a more generic solution? 
The hook which i've specified uses the `script` language so `go` `additional_dependencies` won't work here.
In addition, some dependencies cannot be fetched via `go get` or `pip install` etc.

**Comment by asottile** [comment]
`language: script` / `language: system` are "at your own support" (they are the unmanaged escape hatch) so no there isn't a suggestion other than if you want better installation experience don't use script/system.  If something can't be installed by its language's package manager then I don't know what to tell you

**Comment by dudicoco** [comment]
@asottile since the hooks repo maintainer chooses the language to use for writing the hooks it's not really up to me to decide on the language.

I'm asking this as the consumer of the hooks repo.

**Comment by asottile** [comment]
if you're using something which is using an unsupported thing, you are using an unsupported thing -- there's nothing I can really help you with there.  if you want to become the producer of something that does it the supported way then by all means.
