### ISSUE TITLE
Best way to handle a repo-local flake8 plugin?

### ISSUE THREAD

**Issue by sirosen** [pre-commit/pre-commit#1826]
I'm going to state my specific case because I'm not sure if it's simple to generalize to other languages, etc.

I just tried putting together a flake8 plugin as part of a project, and wanted to add it to `additional_dependencies` for the existing flake8 hook. i.e. `additional_dependencies: ["./myplugin"]`. However, providing a local path doesn't work for that. (I'm aware of the requirements.txt discussion and the caching consideration, which is somewhat related. But I was surprised that this doesn't work even so.)

I'm also looking at the nearest comment/discussion I've found to this case here: https://github.com/pre-commit/pre-commit/issues/758#issuecomment-505935221

And then the other thing I'm considering is writing a local script hook which handles setting up a virtualenv.
None of this seems like a perfect fit.

I'm not expecting necessarily to find a silver-bullet solution which requires zero effort from me, but I'm curious... aside from moving the plugin to a separate repository, is there a nice way to solve this? Is writing a bash script the best I can do?

**Comment by asottile** [comment]
I believe you're looking for [flake8 local plugins](https://flake8.pycqa.org/en/latest/user/configuration.html#using-local-plugins)

**Comment by sirosen** [comment]
Oy vey! I didn't see that anywhere when I looked for exactly that functionality. Thanks so much for the pointer!
