### ISSUE TITLE
Print out the time taken to run a hook without the verbose flag

### ISSUE THREAD

**Issue by idanov** [pre-commit/pre-commit#1829]
Running pre-commit hooks can sometimes be a bit slow and it would be very useful to know which hook is taking most of the time. I tried to find a way to see the runtime for each of the hooks without the verbose flag, but it seems that this feature is not available at the moment. Could you add runtimes for each hook in the summary report or at least enable such option?

<img width="735" alt="Screenshot 2021-03-08 at 09 47 12" src="https://user-images.githubusercontent.com/3482916/110304319-57197a00-7ff3-11eb-88de-0f9042fcc5c3.png">

From what it seems, this should involve a two line change here:
https://github.com/pre-commit/pre-commit/blob/54c49abbcb4b9fbf10865cc8e08f1628836a6088/pre_commit/commands/run.py#L208

To become:

```python
        colored_status = color.format_color(status, print_color, use_color)
        output.write_line(f'{colored_status} in {duration}s')
```

**Comment by asottile** [comment]
the output is branding at this point and will not change, if you want the timing use `--verbose`

**Comment by idanov** [comment]
@asottile Totally makes sense. Would adding an extra flag to print out the output from the screenshot be feasible instead? Adding the `--verbose` flag prints out too much stuff, where just seeing the time hook steps took is a very common use case (at least where we use `pre-commit` hooks).

I am happy to open a PR if you are ok with adding an extra flag.

**Comment by asottile** [comment]
no thanks, that's what `--verbose` is for
