### ISSUE TITLE
Fix package name on PyPI

### ISSUE THREAD

**Issue by henryiii** [pre-commit/pre-commit#1833]
Pre-commit does not support Python 2 anymore (`python_requires = >=3.6.1`), so it does not need universal wheels activated, which produce `py3.py2` in the wheel name instead of `py3`.

You can see the incorrect "Universal" naming here: https://pypi.org/project/pre-commit/#files 

`universal=True` does _not_ mean pure Python, it means support wheel naming for Python 2 and Python 3. If you don't have an Extension, it's pure Python, if you do, it's not. Universal was there just to activate Python 2 + Python 3 support, since setuptools/wheel couldn't tell that without help (it predates `python_requires`). You will notice that after setuptools 45 dropped Python 2 support all mention of the old universal setting was excised from the documentation.

 See https://github.com/pypa/setuptools/issues/1974 when [Setuptools 45.1](https://setuptools.readthedocs.io/en/latest/history.html#v45-1-0) dropped `universal=True` from setuptools itself https://github.com/pypa/setuptools/pull/1978 (45.0 had the same wheel naming bug that pre-commit currently has). Setuptools can tell if a project is pure Python; the universal=1 added `py2.py3` tag. Quoting @jaraco from that issue, the steps to drop Python 2 support are:

> * update python_requires
> * remove Python 2 from Trove classifiers
> * add Python 3 Only to Trove classifiers
> * drop universal wheel

This package is missing the final step. I originally opened a PR #1832, but apparently an issue was needed. This might be good to do in other projects or in automated tooling.

**Comment by asottile** [comment]
you are mistaken

`universal` means "contains no binary artifacts" -- it has been used in the past to signal that a distribution contains only pure code and is therefore the same across python major versions.  it likely will continue to have that same meaning when python 4 comes along

it has nothing to do with `python_requires` which indicates the minimum supported version
