### ISSUE TITLE
R hooks give misleading warning when {renv} package versions differ

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1835]
The implementation in #1799 relies on a globally installed version of the `{renv}` R package (with 0 dependencies). When the version of this installed package is different from what is provided in `renv.lock` (which is managed by the hook author), a warning like the following is displayed when hooks are ran:

```
renv 0.13.0 was loaded from project library, but this project is configured to use renv 0.12.5.
Use `renv::record("renv@0.13.0")` to record renv 0.13.0 in the lockfile.
Use `renv::restore(packages = "renv")` to install renv 0.12.5 into the project library. 
```
This is very misleading since these commands had to be ran in `env_dir` of the hook, not in the directory from which the hook is invoked and if the user were to run the above command, it would in the worst case change the virtual environment of the project from which the hooks are invoked - and in no case fix the warning.

The solution to this is IMO, as mentioned in https://github.com/pre-commit/pre-commit/pull/1799#issuecomment-792697793, to require the hook authors to provide the activation script `renv/activate.R` in the hook repo in addition to `renv.lock`, as [recommended for collaboration per the docs of `{renv}`](https://rstudio.github.io/renv/articles/collaborating.html#collaborating-with-renv-1) (`.Rprofile` can be omitted since all it contains is a call to `renv/activate.R`). This will boostrap the right version of `{renv}` installation into the virtual environment used for the hook. This approach fixes a few other problematic aspects of the current implementation in addition to the above:

* `{renv}` would no longer be installed into the global package library. We could go from a 99% insolation to 100% isolation from the global library.
* `{renv}` is not required in the global package library, i.e. the hooks still work if it was for some reason uninstalled or not available after a major R version update (where the user starts off with an empty library).
* https://github.com/pre-commit/pre-commit/pull/1799#discussion_r576345988 would not be an issue anymore, i.e. on linux, non-root users would no longer be required to have installed any package to make the hooks works.

If you agree, I can make a PR to try to implement this. For local hooks, we need to make sure to populate the directory `renv/` in `env_dir` with `activate.R` in analogy to what the hook author would provide in his repo. Currently, `pre_commit.store.Store.make_local()` can only put files in the root of `env_dir` so this would require making the function slightly more general and add `"renv/activate.R"` to  `pre_commit.store.Store.LOCAL_RESOURCES` as well as creating `empty_template_activate.R` in `pre_commit/resources`. I believe allowing to place files in sub directories of `env_dir` with `pre_commit.Store.make_local()` can be achieved with just a few tweaks to the function (https://github.com/lorenzwalthert/pre-commit/commit/4218765fe45a7b5c6b23d807cca212abd7092541).

Sorry for the hassle, I should have done more testing and indicated concerns in #1799 after I converted from draft and all checks were passing.

**Comment by asottile** [comment]
should we vendor a copy of renv?  would the `r` `install_hook` be able to write an `activate` file on its own?

**Comment by lorenzwalthert** [comment]
What exactly do you mean by vendoring? Including a copy of renv to generate the activation file at install time? `renv/activate.R` is a [static file](https://github.com/rstudio/renv/blob/master/inst/resources/activate.R), so we don't need any logic from `{renv}` to generate it. I.e. we can include a copy of `renv/activate.R` (and regularly update it here). We'd have to check the legal things but probably will be fine. Downloading the file at install time is a bit more brittle I think (e.g. file location can change).

The reason why I suggested to simply ask the hook author to include `renv/activate.R` was because:

* Principle of least astonishment: People who work with renv are used to commit the file along their code already, as this is [the recommended way of collaborating](https://rstudio.github.io/renv/articles/collaborating.html#collaborating-with-renv-1).
* Zero maintenance on our side: We don't have to manage the file, update it when `{renv}` gets updated and so on.
* Maximal control for hook authors: They choose the version of `{renv}` they want to use with their hooks. This simplifies testing the hooks on their side as they can test the hooks independently of pre-commit (just activate their virtual env and go).

**Comment by asottile** [comment]
the main problem is we can't mix managed and unmanaged files in the environment directory (currently set to `./renv`) -- otherwise it seems fine

**Comment by lorenzwalthert** [comment]
Ok. Why not? I am also not sure the file has to live under `renv/`, we can potentially copy it from the hook repo into`pre_commit.helpers.environment_dir(ENVIRONMENT_DIR, version)` instead of the sub directory `renv/` and things would still work. But there are also other files in the `renv/` directory that define the `{renv}` behaviour, such as `settings.dcf` (if one changes the defaults, they will be set there). In general, however, I think `{renv}` is not an experimental package anymore, and using a vendored `renv/activate.R` should also work. Another (hacky) option: Supressing the activation warning...

**Comment by asottile** [comment]
> Ok. Why not?

because it gets cleared on failure which would break the repository

whatever you think is best for your community makes sense though -- let me know what you think is the best way to do this 👍

**Comment by lorenzwalthert** [comment]
Sorry I can't follow. The directory structure I have looks like this;
```
|- ~/.cache
   |- pre-commit
      |- repobtu95rmu         (hook repo, prefix.path())
         |- renv.lock         (provided by user)
         |- renv              (will be here if we ask the user to provide it in hook repo)
           |- activate.R      
         |- renv-default      (env_dir)
            |- renv           (created during install_environment())
               |- activate.R  (The file I proposed to copy from repobtu95rmu/renv)
               |- [... ]
            |- renv.lock      (copied from repobtu95rmu)
```
What I don't understand is:

* why you refer to the environment directory as `./renv` in your comment above (because I believe it is `renv-default`). I don't see how pre-commit can know about `renv/` in `renv-default/`.
* we already have an unmanaged (= user provided) file in `env_dir`: `renv.lock`. I see that we remove `env_dir` with[`with clean_path_on_failure(env_dir)`](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/r.py#L89) when the installation fails, but I don't see how this is a problem, since these files will be copied into `env_dir` on a new installation attempt in my understanding.

Anyways, I opened a PR in #1841 where I implemented my initial propose, so we can see if tests pass and we have actual code to reason about, maybe it's easier.

**Comment by asottile** [comment]
@lorenzwalthert this is done / fixed right ?
