### ISSUE TITLE
Executing pre-commit gives 'CalledProcessError'

### ISSUE THREAD

**Issue by bellerophons-pegasus** [pre-commit/pre-commit#1838]
I'm very new to hooks and pre-commit and could not yet manage to get a successful run. Maybe someone can help?

What I did in a repository on ubuntu 18.04 (git version 2.17.1, pre-commit version 2.11.1):
* installed pre-commit with `pip install pre-commit`
* installed nbstripout with `pip install --upgrade nbstripout`
* saved the file `.pre-commit-config.yaml` with the required contents for [nbstripout](https://github.com/kynan/nbstripout) to the root of the repository
* executed `pre-commit install` which resulted in `pre-commit installed at .git/hooks/pre-commit`

Where the error occurs:
* execution of `pre-commit run --all-files` results in
```
[INFO] Installing environment for https://github.com/kynan/nbstripout.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/ich/Applications/anaconda3/bin/python', '-mvirtualenv', '/home/ich/.cache/pre-commit/repouwygl0sw/py_env-python3.7')
return code: 1
expected return code: 0
stdout:
    TypeError: entry_points() missing 1 required positional argument: 'name'
    
stderr: (none)
Check the log at /home/ich/.cache/pre-commit/pre-commit.log
```

The log is attached. [pre-commit.log](https://github.com/pre-commit/pre-commit/files/6136855/pre-commit.log)

It seems that pre-commit creates some sort of copy of the repository in `.home/ich/.cache/pre-commit` including a copy of the config file. But that file is different from the one in the repository and looks messed up:
```
-   id: nbstripout
    name: nbstripout
    description: 'nbstripout: strip output from Jupyter and IPython notebooks'
    entry: nbstripout
    language: python
    types: [jupyter]
```

Any ideas what is happening?

**Comment by asottile** [comment]
that looks like a bug in `virtualenv` -- please report that [here](https://github.com/pypa/virtualenv) (you should be able to reproduce by using `python -m virtualenv venv`)

**Comment by bellerophons-pegasus** [comment]
Thanks!
Indeed, it seems to be `virtualenv`

**Comment by bellerophons-pegasus** [comment]
Problem just was: very outdated `virtualenv`
