### ISSUE TITLE
Possibility to specify version for additional dependencies

### ISSUE THREAD

**Issue by rmestrum** [pre-commit/pre-commit#1840]
I want to use some additional ruby gem with a specific version

Is there any possibility to specify a version for the gems using the additional dependencies option?

**Comment by asottile** [comment]
yep!  using the same syntax you'd use if you were running `gem install` -- here's [an example](https://github.com/asottile/personal-puppet/blob/b74d0f3b93180bcbed7055c4b298f5cff7079d6e/.pre-commit-config.yaml#L55)
