### ISSUE TITLE
pre-commit breaks on centos-7 due to old git and problem with version 6.0.0 of setuptools_scm

### ISSUE THREAD

**Issue by PatrikHlobil** [pre-commit/pre-commit#1844]
On Centos-7 the default Git version ist pretty old (1.8.x). The new release 6.0.0 of setuptools_scm breaks the installation of e.g. black. The corresponding issue on setuptools_scm shows more details for this:

https://github.com/pypa/setuptools_scm/issues/537

A possible solution is to pin the version of setuptools_scm, however I couldn't resolve where this could be done in the repository.

Best Patrik

**Comment by asottile** [comment]
there's nothing we can do about black's use of setuptools-scm -- not sure why you think this is a pre-commit issue ?

**Comment by RonnyPfannschmidt** [comment]
@asottile my bug is bubbling up to you due to unhappy users, bugfix incoming
