### ISSUE TITLE
Bundled ruby-build version needs an update (for ruby 2.7.2 on macos)

### ISSUE THREAD

**Issue by sirosen** [pre-commit/pre-commit#1848]
I tried to noodle out how to do this, but I couldn't figure it out.
I saw the last update was #1614 

I think we're just due for another one?

I have a coworker who ran into issues running a hook specifying ruby 2.7.2 , and we tracked it down to the version of ruby-build being too old.

I also wonder if we could get the version of the bundled tool into the pre-commit.log somehow? Or at least the fact that pre-commit will be using its own ruby-build version. I lost time being confused about what pre-commit was doing (and thinking that my coworker's rbenv setup was somehow broken).

**Comment by asottile** [comment]
I'd rather not expose the version as I plan to remove `rbenv` `ruby-build` and `ruby-download` at some point
