### ISSUE TITLE
.git/hooks/pre-commit died of signal 6 aftre upgrading to macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by mkalimeri** [pre-commit/pre-commit#1850]
I try to commit to git with pre-commit installed and get the rerror ".git/hooks/pre-commit died of signal 6". This happened after I upgraded my OS to masOS Big Sur 11.2.3

**Comment by asottile** [comment]
you haven't shown any information to possibly reproduce, diagnose, or debug
