### ISSUE TITLE
Bad executor when using pipx to install pre-commit git hook

### ISSUE THREAD

**Issue by gtmanfred** [pre-commit/pre-commit#1852]
When I install the git hook with pre-commit using pipx, it still passes `/usr/bin/env <pythonver>` but i need the shebang to point to the python version in the virtualenv.

Would it be possible to just have this use `sys.executable` from the pre-commit command, instead of attempting to search the command path for a specific python version? This should allow whatever python executable is used to execute the `pre-commit install command` to be used when installing the git hook.  Currently i am just manually changing this once the hook is installed.

Thanks,
Daniel

**Comment by asottile** [comment]
please provide more information, outputs, etc.  you're describing a solution to a problem but have not actually showed the problem

**Comment by gtmanfred** [comment]
Hrm, it seems that i am unable to reproduce this error anymore.  I do not know what would have changed, I think it probably was fixed by removing unused commands from my pyenv installs.

oh well, thanks for the quick response. If it comes up again i will make sure to save what I did to cause it.

Thanks!
