### ISSUE TITLE
Running on machines not connected to the internet?

### ISSUE THREAD

**Issue by max-sixty** [pre-commit/pre-commit#1853]
Thanks for the awesome tool!

Is there a reasonable way to install hooks onto machines that aren't connected to the internet?

For example, would copying pre-commit's cache dir onto those machines be reliable?

Thanks!

**Comment by asottile** [comment]
yes, this is for instance how https://pre-commit.ci works

more information [in the docs](https://pre-commit.com/#managing-ci-caches)

**Comment by max-sixty** [comment]
Thanks @asottile . I had seen those docs — I'm taking from your response that copying the cache is reliable. Cheers!

**Comment by asottile** [comment]
as long as the machines are relatively identical, yes
