### ISSUE TITLE
Possible to change default hooks ~./cache/pre-commit install location via .pre-commit.config.yaml? 

### ISSUE THREAD

**Issue by kozarski** [pre-commit/pre-commit#1856]
Unless i'm overseeing this (very possible) - I don't see any way to set the default location for hooks from the `.pre-commit-config.yaml` file directly in the `.pre-commit.config.yaml` file? 

From what I've read from the docs, [PRE_COMMIT_HOME](https://pre-commit.com/#managing-ci-caches) is only available to be set via CI?

Alternatively if there's a way to set the default hooks location upon `pre-commit install --install-hooks`, that would be beneficial as well. 

Thanks!

**Comment by asottile** [comment]
there is not, and allowing that would be a potential security issue (as it would force writing directories in an arbitrary location)

you can configure this by setting the same environment variables that the docs you linked to mention -- for instance in your `.bashrc`

**Comment by kozarski** [comment]
Got it - i'll go this route then

I admittedly have a pretty unique edge case, thanks for the fast reply :)

**Comment by asottile** [comment]
just for the future, you'd be better off _stating_ your actual use case when asking questions / making issues
