### ISSUE TITLE
Interactive hooks

### ISSUE THREAD

**Issue by MIJOTHY** [pre-commit/pre-commit#1857]
Hey, enjoying the project a lot (via [pre-commit-hooks.nix](https://github.com/cachix/pre-commit-hooks.nix)). I'm interested in integrating commitizen (cz-cli) [prepare-commit-message](https://github.com/commitizen/cz-cli#optional-running-commitizen-on-git-commit) interactivity into the pre-commit framework - I'm wondering if there's a blessed way to do this? I can't see documentation for introducing interactivity into commit hooks via the pre-commit framework?

**Comment by asottile** [comment]
the framework intentionally does not enable interactivity (and git discourages this as well by not providing a tty to git hooks)

duplicate issues: #1127 #871 #872

**Comment by MIJOTHY** [comment]
Alright thanks. Will investigate another approach. It might be worth documenting this non-goal of the project somewhere in the docs.

**Comment by asottile** [comment]
there are infinite non-goals, it's difficult to be exhaustive in documenting them :)

**Comment by MIJOTHY** [comment]
> there are infinite non-goals, it's difficult to be exhaustive in documenting them :)

Of course, though there is an obvious heirarchy of relevance of non-goals induced by the frequency of being asked about them, and in some cases the absence of documentation of a deliberate non-feature isn't enough to inform users that it is an intentional omission.
