### ISSUE TITLE
detect-aws-credentials false positive

### ISSUE THREAD

**Issue by nmarchini** [pre-commit/pre-commit#1860]
I get the following error when using this detect-aws-credentials. The are 100% no credentials in the makefile. 

Detect AWS Credentials...................................................Failed
- hook id: detect-aws-credentials
- exit code: 1

AWS secret found in Makefile: ff**************************

**Comment by asottile** [comment]
this is not the repository you're looking for -- this is the framework

I'd suggest reporting it to whatever repository houses the `detect-aws-secrets` tool
