### ISSUE TITLE
link checker for Markdown?

### ISSUE THREAD

**Issue by vielmetti** [pre-commit/pre-commit#1861]
There is a Github action for checking links in Markdown files, at

https://github.com/marketplace/actions/markdown-link-check

It uses https://github.com/tcort/markdown-link-check to do its work.

This looks like would be a nice addition as a pre-commit hook.
I'm uncertain as to how to proceed to add it, though - so this
is more of a request for interest (is this the sort of plugin that
makes sense?) and for help (what would it take to make it work?)

**Comment by asottile** [comment]
yeah!  this sort of tool would work fine with pre-commit (assuming you don't have an intentionally restricted network such as with https://pre-commit.ci) -- though checking links is likely going to be kinda slow

since it's written in js it'll work with the native js support in pre-commit
