### ISSUE TITLE
pre-commit cached virtual environments break on system Python upgrade

### ISSUE THREAD

**Issue by EliRibble** [pre-commit/pre-commit#1869]
To reproduce:

 1. Configure a repository with a pre-commit hook that uses the `python` language.
 2. Run your hook with a system install of Python at version A.
 3. `pre-commit` will create a Python virtual environment at `~/.cache/pre-commit/repoXXXXXXXX/py_env-python3` with symlinks to Python version A at `~/.cache/pre-commit/repoXXXXXXXX/py_env-python3/bin/python` and libraries installed to `~/.cache/pre-commit/repoXXXXXXXX/py_env-python3/lib/python-A/`
 4. Upgrade the system python version to version B.

At this point the virtual environment will now use the new system version of Python, bit it will *not* use the libraries that were installed at `~/.cache/pre-commit/repoXXXXXXXX/py_env-python3/lib/python-A/` because of the version number mismatch. This can break the behavior of the hook in exotic ways. Generally it just looks like a large stack trace on running the hook entrypoint.

**Comment by EliRibble** [comment]
I'm not certain on the right way to fix this, but I assert that since `pre-commit` creates these virtual environments it should at least inform the user that the environment is broken because the system Python was updated. It seems like this should be fairly easy to do since `~/.cache/pre-commit/repoXXXXXXXX/py_env-python3/pyvenv.cfg` contains specific version information for the virtual environment that can be compared against the system python version.

It'd be really nice if pre-commit could detect the situation and invalidate the cache and attempt to create a fresh virtualenv. Whether or not that should be pre-commit's responsibility seems worthy of discussion.

**Comment by asottile** [comment]
there's code inside pre-commit to handle this case and invalidate the environments? can you share what version of `pre-commit` you're using and what error outputs you are seeing?

**Comment by EliRibble** [comment]
I'm on version 2.12.0, but we have systems that may be on earlier versions that are affected - do you know what version it was released in, or where in the code I would find it, or any documentation on the behavior?

**Comment by asottile** [comment]
early versions are not supported -- check the changelog for more information.  the scenario you described is impossible in the latest versions

**Comment by EliRibble** [comment]
I'll work on answering my own questions for the benefit of others who may find this issue in the future.

You can find the logic for detecting the "health" of a cached Python virtual environment at `pre_commit/languages/python.py` in a function called [healthy](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py#L166). This function was originally added in [commit cff98a64](https://github.com/pre-commit/pre-commit/commit/cff98a) which corresponds roughly to [version 0.15.3](https://github.com/pre-commit/pre-commit/releases/tag/v0.15.3).

There is no documentation on how the feature works and the Changelog merely says ["Recover from invalid python virtualenvs"](https://github.com/pre-commit/pre-commit/blob/master/CHANGELOG.md#0153---2017-07-20).

**Comment by EliRibble** [comment]
It appears that the logic currently checks if the virtual environment is healthy as part of [install_hook_envs](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/repository.py#L209) (via `_need_installed()` -> `_hook_installed()`). If the environment is unhealthy due to the version in `pyvenv.cfg` not matching the version of the running Python then the [cached virtualenv is removed](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/repository.py#L80) using `rmtree()`
