### ISSUE TITLE
Support pre-push

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#187]
(Maybe generically support more hooks as well)

This seems pretty straightforward to implement. Should be able to read the spec on pre-push and use the revision information to run the pre-commit hooks.

We'll need to extend run, install, and uninstall to support this as well.

**Comment by guykisel** [comment]
You're going to have to rename the entire project now.

**Comment by asottile** [comment]
lol

**Comment by asottile** [comment]
#189

**Comment by shihoonhootsuite** [comment]
Was there documentation on how to enable pre-push or is this just enabled by default?

**Comment by asottile** [comment]
Docs for pre-push are http://pre-commit.com/#advanced  section "pre-commit
during push"

You'll need a sufficiently new version of git (I believe >1.8) which
supports pre-push as a hook

**Comment by mechastorm** [comment]
Thanks!
