### ISSUE TITLE
`pre-commit/action` does not support the `--config` flag

### ISSUE THREAD

**Issue by puqeko** [pre-commit/pre-commit#1871]
[pre-commit/action](https://github.com/pre-commit/action) assumes the config file is at `.pre-commit-config.yaml` for caching. A possible fix is to check for the argument of the `-c` and `--config` flags in the combined `args` array. A diff of proposed changes to master is given below...

```
diff --git a/index.js b/index.js
index 4fc00db..073dd51 100644
--- a/index.js
+++ b/index.js
@@ -48,9 +48,16 @@ async function main() {
     const pr = github.context.payload.pull_request;
     const push = !!token && !!pr;
 
+    // Get config file location from last config argument for caching
+    var configPath = '.pre-commit-config.yaml'  // Default location
+    const cIndex = Math.max(args.lastIndexOf('-c'), args.lastIndexOf('--config'));
+    if (cIndex > -1 && cIndex + 1 < args.length) {
+        configPath = args[cIndex + 1];
+    }
+
     const cachePaths = [path.join(os.homedir(), '.cache', 'pre-commit')];
     const py = getPythonVersion();
-    const cacheKey = `pre-commit-2-${hashString(py)}-${hashFile('.pre-commit-config.yaml')}`;
+    const cacheKey = `pre-commit-2-${hashString(py)}-${hashFile(configPath)}`;
     const restored = await cache.restoreCache(cachePaths, cacheKey);
     const ret = await exec.exec('pre-commit', args, {ignoreReturnCode: push});
     if (!restored) {
```

I am submitting this here since non-collaborator pull requests and issues seem to be disabled for [pre-commit/action](https://github.com/pre-commit/action)

**Comment by asottile** [comment]
they are disabled to prevent abuse

no new features will be implemented on pre-commit/action at this time -- please follow convention and put it in the conventional place or fork if you need additional behaviour
