### ISSUE TITLE
Clarification on pre-comimt/action#94

### ISSUE THREAD

**Issue by puqeko** [pre-commit/pre-commit#1872]
@asottile Thank you for looking at issue pre-commit/action#94. Could you please clarify why this issue was dismissed as a feature instead of being classified as a bug?

From the [pre-commit/action README](https://github.com/pre-commit/action#using-this-action-with-custom-invocations): "`extra_args` lets users specify a single hook id and/or **options to pass to `pre-commit run`**". However, the action will fail if the `--config` flag (which is a [valid option](https://pre-commit.com/#cli) of `pre-commit run`) takes on a value that is not the conventional config file path. Since the actual behaviour does not appear to fully support the documented behaviour, it appears pre-commit/action#94 is describing a bug not a feature.

Can you please either

1. Implement the fix proposed, or
2. Update the [pre-commit/action README](https://github.com/pre-commit/action#using-this-action-with-custom-invocations) to be explicit about the limitations of `--config` when specified in `extra_args`.

Again, my apologies for having to re-raise this issue under the pre-commit repo

**Comment by asottile** [comment]
you can pass the arg all you want, that works fine, but the feature of supporting non-standard configuration locations is a feature request

**Comment by puqeko** [comment]
Okay, thank you. Are you able to give any indication of if/when the action might become open to feature requests?

**Comment by asottile** [comment]
it will not be receiving future feature development, only bugfixes
