### ISSUE TITLE
Check for pre-commit minimal version before any other validation

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1876]
**Context**
My hooks in https://github.com/lorenzwalthert/precommit are currently using `language: script`. Since with pre-commit 2.11, R is supported as a language, I wanted to leverage that in https://github.com/lorenzwalthert/precommit/pull/233. People who run `pre-commit autoupdate` without updating the pre-commit executable to at least 2.11 are going to run into the following message:

```
An error has occurred: InvalidManifestError: 
==> File ***.cache/pre-commit/repouxtsfstk/.pre-commit-hooks.yaml
==> At Hook(id='roxygenize')
==> At key: language
=====> Expected one of conda, coursier, docker, docker_image, dotnet, fail, golang, node, perl, pygrep, python, python_venv, ruby, rust, script, swift, system but got: 'r'
```

So I thought I can add a minimal version requirement for pre-commit as documented in https://pre-commit.com/#top_level-minimum_pre_commit_version to my `.pre-commit-hooks.yaml`, but I keep getting the same error with pre-commit < 2.11. 

**Suggestion**
For these reasons, I suggest to check the pre-commit minimal version requirement first before validating any other configuration since *all* configurations can be a function of the pre-commit minimal requirement (also breaking API changes in the config structure for example).

**Validating problem**
To make sure nothing is wrong with my example, I did the following to verify pre-commit's behavior:
I bumped the version requirement to 2.12 and installing pre-commit 2.11 (where R is already supported) and then I got the expected error message on `git commit`:
```
[INFO] Initializing environment for https://github.com/lorenzwalthert/precommit.
[ERROR] The hook `style-files` requires pre-commit version 2.12 but version 2.11.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.
```

**Comment by asottile** [comment]
it's unfortunately a chicken-and-egg problem -- we can't read the value until we parse the configuration, and we can't parse the configuration without validating (it could be completely wrong structurally!), and we can't change the behaviour in already-released things
