### ISSUE TITLE
Alternative way to detect root folder 

### ISSUE THREAD

**Issue by tmotyl** [pre-commit/pre-commit#1882]
Right now pre-commit requires the project to have a .git folder to find out  which folder is a root folder.

I would like to run pre-commit in CI context on a folder which doesn't have .git (however the git binary is available).
At this stage of CI, the artifact being tested has .git folder stripped out as the repo is quite heavy.

Now I'm getting an error:
``` 
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```
The working directory i'm executing pre-commit from has a config file (.pre-commit-config.yaml), so It would be great if pre-commit could rely on it and assume we're in the project root directory.
Alternatively I could pass some param or env variable to make the root directory explicit.

**Comment by asottile** [comment]
pre-commit works by running on files checked into git, you can always `git init . && git add .` -- but there isn't really any way otherwise -- **pre-commit only operates on git checked-in files**
