### ISSUE TITLE
Failing build on CI

### ISSUE THREAD

**Issue by Borda** [pre-commit/pre-commit#1889]
hello, first of all, not sure if this is the proper place for reporting/asking issue with running pre-commit.ci
I am trying to get some minimal case checked by this CI, but it fails on the build without any message so not sure what is happening there, any suggestion on how to debug/proceed?

https://results.pre-commit.ci/run/github/330707186/1619429009.yUl3BKyQRjimpxm3IKR17w

**Comment by asottile** [comment]
it is not, you want https://github.com/pre-commit-ci/issues

**Comment by asottile** [comment]
hmmm it seems the error message is not propagating properly, here's the output though:

```console
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[ERROR] The hook `isort` specifies `language_version` but is using language `system` which does not install an environment.  Perhaps you meant to use a specific language?
```

**Comment by asottile** [comment]
=> https://github.com/pre-commit-ci/issues/issues/61

**Comment by Borda** [comment]
> => [pre-commit-ci/issues#61](https://github.com/pre-commit-ci/issues/issues/61)

Thank you for putting it in correct place :rabbit:
