### ISSUE TITLE
pre-commit install --install-hooks does not install other hook types

### ISSUE THREAD

**Issue by josephtate** [pre-commit/pre-commit#1895]
When I run `pre-commit install --install-hooks`, I expect that all relevant hooks would get installed, but only the pre-commit hook actually gets set up in .git/hooks. For example, when I have `commit-msg` hooks set up in `.pre-commit-config.yaml`, I'd expect to be able to use them, but while the environments are set up, the hook isn't actually installed.

```
$ pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/milin/giticket.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```
Note that only the pre-commit script gets set up.

The giticket hook is a commit-msg hook (configured in the remote repo), but that hook does not get installed.

Instead a manual step is required for each used hook `pre-commit install -t <hook-type>` leading to lots of extra steps and different install documentation for each project using alternate hooks.

**Comment by asottile** [comment]
`pre-commit install` takes a `--hook-type` which can be specified multiple times

so if you want to install (for example) `pre-commit` and `commit-msg` you can run `pre-commit install --install-hooks --hook-type pre-commit --hook-type commit-msg`

**Comment by asottile** [comment]
dupes are collected in #1145

**Comment by josephtate** [comment]
But --install-hooks knows what stages are necessary. Why not install the right stages?

**Comment by asottile** [comment]
read the dupes please -- "what stages are necessary" is every single stage which you definitely don't want
