### ISSUE TITLE
Specific shell scripts not identified

### ISSUE THREAD

**Issue by avdv** [pre-commit/pre-commit#1896]
Hi.

Having a hook:
```
         "entry": "shellcheck",
          "exclude": "^$",
          "files": "",
          "id": "shellcheck",
          "language": "system",
          "name": "shellcheck",
          "pass_filenames": true,
          "types": [
            "sh",
            "ash",
            "bash",
            "bats",
            "dash",
            "ksh"
          ]

```
when running `pre-commit run --all-files` this hook is alwyas skipped although there is a bash script which is identified thusly:
```console
$ identify-cli  check-this 
["bash", "executable", "file", "shell", "text"]
```
When I change the `types` to just `["shell"]` it works. 

How does this work?

**Comment by asottile** [comment]
https://pre-commit.com/#filtering-files-with-types

> `types`, `types_or`, and `files` are evaluated together with `AND` when filtering. Tags within `types` are also evaluated using `AND`.

**Comment by avdv** [comment]
Right, forgot about that... :facepalm:
