### ISSUE TITLE
How to change font color of `Passed` for hooks that have passed on pre-commit in iTerm2?

### ISSUE THREAD

**Issue by avatar-lavventura** [pre-commit/pre-commit#1897]
On pre-commit `...Passed` and `...Skipped` colors are as follows (Passed color is white where it is not readable on top of green background) if users are using dark theme:

[![enter image description here][1]][1]

Here https://pre-commit.com/#usage, it's much more readable:

[![enter image description here][2]][2]

How could I change the font and background color of `Passed` and `Skipped` that is located at the end of each check?

Related issue https://github.com/pre-commit/pre-commit/issues/969 has only solutions as disabling colors with `--color=never`

--------

- I am using [`iTerm2`][3] as terminal emulator.
- My shell is `zsh`.
-  Theme is [`dracula`](https://draculatheme.com/iterm).

My color configuration under iTerm2:

[![enter image description here][4]][4]

-----

Afterwards, when I change foreground theme to something else than white, font color of `...Passed` is changed but it effects my overall font configuration.

[![enter image description here][5]][5]

  [1]: https://i.stack.imgur.com/uQPvL.png
  [2]: https://i.stack.imgur.com/VEfns.png
  [3]: https://iterm2.com
  [4]: https://i.stack.imgur.com/4BryRl.png
  [5]: https://i.stack.imgur.com/EzUjz.png

**Comment by asottile** [comment]
the foreground color is going to be the same as your default text color -- I'd recommend you make the green color darker ?

**Comment by avatar-lavventura** [comment]
I am sorry for keep asking questions related to this.

I changed bright green color to dark-red as solution.

**Comment by kdheepak** [comment]
If anyone else is interested in configuring the colors, you can hack it by changing the global variables on the cli entry. Just as an example, you can have `Passed` in italics, `Skipped` in strikethrough and `Failed` in bold and red, illustrated in the screenshot below:

<img width="1680" alt="Screen Shot 2021-07-02 at 2 11 21 PM" src="https://user-images.githubusercontent.com/1813121/124324102-a6099300-db3f-11eb-918a-e93f03d497ea.png">

I'm pretty sure **_the developers will not recommend doing this_**, so if you choose to proceed you are on your own. I'm  sharing in case someone else is looking for something like this:

1) Find where `pre-commit` is installed: `which pre-commit` on UNIX or `where pre-commit` on Windows:

You should see a file that looks something like this:

```python
!#/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys
from pre_commit.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

2) Modify the global variables, `color.RED`, `color.GREEN`, `color.YELLOW` and `color.TURQUOISE` in the `pre_commit` package.

For the above screenshot, I modified the file to below:

```python
!#/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import os
import sys
from pre_commit import color

def hex2rgb(h):
    h = h.lstrip('#')
    return ";".join(list(str(int(h[i:i+2], 16)) for i in (0, 2, 4)))

def true_color(foreground, background):
    return '\x1b[38;2;{foreground}m\x1b[48;2;{background}m'.format(foreground = hex2rgb(foreground), background = hex2rgb(background))

BOLD = "\x1b[1m"
ITALICS = ""\x1b[3m""
STRIKETHROUGH="\x1b[9m"

color.RED = "  {}{}".format(BOLD, true_color(os.environ["PRECOMMIT_COLOR_BLACK"], os.environ["PRECOMMIT_COLOR_RED"]))
color.GREEN = "  {}".format(ITALICS)
color.YELLOW = true_color(os.environ["PRECOMMIT_COLOR_BLACK"], os.environ["PRECOMMIT_COLOR_YELLOW"])
color.TURQUOISE = "  {}{}".format(STRIKETHROUGH, true_color(os.environ["PRECOMMIT_COLOR_FOREGROUND"], os.environ["PRECOMMIT_COLOR_BACKGROUND"]))

from pre_commit.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

In my local environment I have something like this, that is autogenerated from my theme colors.

```
  export PRECOMMIT_BACKGROUND='#061626'
  export PRECOMMIT_FOREGROUND='#acb4c2'
  export PRECOMMIT_BOLD='#eeeeee'
  export PRECOMMIT_CURSOR='#9ca1aa'
  export PRECOMMIT_CURSORTEXT='#080808'
  export PRECOMMIT_SELECTION='#b2ceee'
  export PRECOMMIT_SELECTIONTEXT='#080808'
  export PRECOMMIT_BLACK='#1d3b53'
  export PRECOMMIT_RED='#fc514e'
  export PRECOMMIT_GREEN='#a1cd5e'
  export PRECOMMIT_YELLOW='#e3d18a'
  export PRECOMMIT_BLUE='#82aaff'
  export PRECOMMIT_PURPLE='#c792ea'
  export PRECOMMIT_CYAN='#7fdbca'
  export PRECOMMIT_WHITE='#a1aab8'
  export PRECOMMIT_BRIGHTBLACK='#7c8f8f'
  export PRECOMMIT_BRIGHTRED='#ff5874'
  export PRECOMMIT_BRIGHTGREEN='#21c7a8'
  export PRECOMMIT_BRIGHTYELLOW='#ecc48d'
  export PRECOMMIT_BRIGHTBLUE='#82aaff'
  export PRECOMMIT_BRIGHTPURPLE='#ae81ff'
  export PRECOMMIT_BRIGHTCYAN='#7fdbca'
  export PRECOMMIT_BRIGHTWHITE='#d6deeb'
```

I like using true colors in my terminal, and my dotfiles have environment variables with all these colors anyway so for me it was just a matter of adding a new more environment variables once this entry point was modified. 

Obviously you can change the `true_colors` function to output base16 colors or 256 colors or anything else you wish.
