### ISSUE TITLE
allow passing options to pip

### ISSUE THREAD

**Issue by Finkregh** [pre-commit/pre-commit#1907]
It would be great if I could pass options to `pip` to e.g. force it to compile everything from source (`--no-binary ":*:"`).

Like that I would be able to workaround wrong binary files on arm64/darwin:

```
ImportError: dlopen(/.cache/pre-commit/repotic30zme/py_env-python3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/.cache/pre-commit/repotic30zme/py_env-python3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-darwin.so: mach-o, but wrong architecture

or

ImportError: dlopen(/.cache/pre-commit/repo4yfo038w/py_env-python3/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/.cache/pre-commit/repo4yfo038w/py_env-python3/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
```

When I manually switch to the venv i am able to remove the package and install it via `python3 -m pip install --no-binary ":*:" --no-cache-dir typed_ast`.

Thanks!

**Comment by asottile** [comment]
anything in `additional_dependencies` is passed to pip -- that said this looks like a bug in pip itself -- you might want to upgrade that (you can usually do so by upgrading `virtualenv` next to pip

mucking around inside the private cache implementation details is not supported and you are very likely to break things
