### ISSUE TITLE
Getting the information of what is to be pushed in pre-push hook

### ISSUE THREAD

**Issue by Jonas-Visma** [pre-commit/pre-commit#1908]
As mentioned in #1410, some of the information given to pre-push from git is missing. Unlike #1410 I am wondering whether it is possible to get the information about every single commit about to be pushed?

I suspect that this is currently not possible, based on #693 and the function [_pre_push_ns](https://github.com/pre-commit/pre-commit/blob/2c28197c2a87513a4a3663eb73cc37f41f56f05e/pre_commit/commands/hook_impl.py#L104-L154). Which seems to discard this information.

Is this a feature that would be possible to incorporate in the design of `pre-commit`? Or is there a work around I am not seeing? The work around should preferably still utilize this awesome framework so the pre-push wouldn't have to be manually setup.

**Comment by asottile** [comment]
yeah it's ~generally not possible within the framework which makes some (potentially incorrect) assumptions that you're pushing the checked out commit -- as far as I can tell it has always been this way 🤷

**Comment by Jonas-Visma** [comment]
Thank you for your response. 

For my use case that is too bad, but there is probably a good reason for it. Either way, would you mind me having a look to see if I can add this feature without breaking or altering the design? If you believe it to be possible, of course.

**Comment by asottile** [comment]
I don't think it's possible within the framework, but feel free to have a look

**Comment by Jonas-Visma** [comment]
Alright. I will have a gander and make a comment my findings.

**Comment by kim-groenborg-nielsen** [comment]
The issue that @Jonas-Visma and I are trying to solve, is to get the stdin data passed on to the plugin so we can validate branch and tag names. Either by getting data via stdin or via environment variables.
Currently, it does not matter for us if the pre-push plugin runs in other branches than the current one.

So I have an easy solution to our problem, which only involves modifying hook_impl.py, so the pre-push plugins are called once for each branch to be pushed.
Could that kind of solution be accepted by you?

**Comment by asottile** [comment]
not really, that will trigger hooks on unrelated code (and many times)

you could use a legacy hook which would receive the full stdin, but that'd be outside the framework
