### ISSUE TITLE
Feature Request: I can haz .yml?

### ISSUE THREAD

**Issue by kthy** [pre-commit/pre-commit#1909]
My sense of order has a sad because pre-commit is the only tool in my toolbox that flat out doesn't accept `.yml` as a config file extension. Could it try `.pre-commit-config.yml` if `.pre-commit-config.yaml` is not found?

**Comment by asottile** [comment]
no can haz yml

can haz search issue tracker? #702 #1451

**Comment by kthy** [comment]
Sorry, I had searched and came up empty. 🤷‍♂️ Thanks for indirectly pointing out the `--config` option, though.
