### ISSUE TITLE
pre-commit should probably ignore symlinks?

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#191]
Right now some hooks do the wrong thing with symlinks.  Maybe the hooks should be written such that they ignore symlinks?

**Comment by kentwills** [comment]
+1

**Comment by asottile** [comment]
Also probably should ignore submodules too

**Comment by asottile** [comment]
pre-commit 0.15.0 will not lint symlinks or submodules by default.

To explicitly lint symlinks use:
```yaml
    types: [symlink]
```
To explicitly lint submodules use:
```yaml
    types: [directory]
```
