### ISSUE TITLE
Option to specify `.pre-commit-config.yaml` file to use

### ISSUE THREAD

**Issue by ryanmcnamara** [pre-commit/pre-commit#1921]
Hi, great tool, thanks!

Is there an option to specify the file to use for the pre-commit configuration instead of using `.pre-commit-config.yaml`, 
Perhaps something like `pre-commit run -f .pre-commit-config-other.yaml`. I looked through the docs and `pre-commit --help` for options and didn't find anything.

I think this would be useful in general, so if the option doesn't exist I'd like to see it added. 
The very specific reason I need this is that I want to run `pre-commit` in CI. My pre-commit file references git remotes that can't be pulled from CI (private repo) but can be pulled locally. What I'd like to do is use a different pre-commit-config file that references working remotes

**Comment by asottile** [comment]
I guess you didn't look too hard? it's there in the `--help` and in [the docs](https://pre-commit.com/#command-line-interface)

**Comment by ryanmcnamara** [comment]
> I guess you didn't look too hard?

Yikes!

`pre-commit run --config .pre-commit-config-other.yaml` works just fine already like you allude to.
