### ISSUE TITLE
Question: How does pre-commit fit into dev container workflow?

### ISSUE THREAD

**Issue by noorul** [pre-commit/pre-commit#1923]
We are using dev container with all our developer dependency tools. We have pre-commit installed as part of the image. Most of the developers prefer to use ```git``` binary from host system. Does anyone has a workflow similar to this and succeeded in keeping pre-commit and dependencies inside container and the ```git``` binary on host?

**Comment by asottile** [comment]
I think you're fighting the general way things work -- pre-commit is designed to avoid needing fiddly container setups and works best when it manages your tools

that said, if you're looking for someone to implement this for your company feel free to reach out and perhaps a contracted solution can be built for your usecases
