### ISSUE TITLE
`pre-commit autoupdate` updates rev to `stable`

### ISSUE THREAD

**Issue by jmknoble** [pre-commit/pre-commit#1925]
```
$ pre-commit --version
pre-commit 2.13.0
$ grep -A 4 'repo:.*json-indent' .pre-commit-config.yaml
  - repo: https://github.com/jmknoble/json-indent
    rev: 2.4.1
    hooks:
      - id: json-indent

$ pre-commit autoupdate
...
Updating https://github.com/jmknoble/json-indent ... updating 2.4.1 -> stable.
...
```

Tags on **json-indent**:

```
$ git remote get-url origin
https://github.com/jmknoble/json-indent.git
$ git show -s FETCH_HEAD
commit d6c0785f4000355bb6fc5f788889ba99617d0d96 (HEAD -> main, tag: v2.4.4, tag: stable, origin/main, origin/HEAD)
Author: Jim Knoble <jmknoble@...>
Date:   Thu May 27 09:41:10 2021 -0700

    Update stable version to 2.4.4
$
```

This seems to be related to [commands.autoupdate.RevInfo.update()](https://github.com/pre-commit/pre-commit/blob/488b1999f36cac62b6b0d9bc8eae99418ae5c226/pre_commit/commands/autoupdate.py#L40), where `git describe FETCH_HEAD --tags` is used:

```
$ git --version
git version 2.31.1
$ git describe FETCH_HEAD --tags --abbrev=0
stable
$ git describe FETCH_HEAD --tags --exact
stable
$
```

If I use either `--match` or `--exclude`, I can get the tag we're after:

```
$ git describe FETCH_HEAD --tags --exact --match '*.*'
v2.4.4
$ git describe FETCH_HEAD --tags --exact --exclude stable
v2.4.4
$
```

Using `--match '*.*'` is closer to what is checked in [clientlib.WarnMutableRev()](https://github.com/pre-commit/pre-commit/blob/488b1999f36cac62b6b0d9bc8eae99418ae5c226/pre_commit/clientlib.py#L124), but fails the hex regex check.  That may be ok, since `git describe` is looking for tags.  Thoughts?

**Comment by asottile** [comment]
`stable` is a newer annotated tag than v2.4.4 which is why it is being picked up in that way (moving tags generally should not be annotated tags)
