### ISSUE TITLE
Local Python hook installs dummy package instead of my package

### ISSUE THREAD

**Issue by defrank** [pre-commit/pre-commit#1926]
# Version information

```sh
› python --version
Python 3.9.4

› pip --version
pip 20.2.3 from /Users/dfrank/.pyenv/versions/3.9.4/envs/pre-commit-bug/lib/python3.9/site-packages/pip (python 3.9)

› python -m pip --version
pip 20.2.3 from /Users/dfrank/.pyenv/versions/pre-commit-bug/lib/python3.9/site-packages/pip (python 3.9)

› pre-commit --version
pre-commit 2.12.1
```

# Problem

Local Python hooks are not installing my package or scripts.

I made a reproducible test case at https://github.com/defrank/pre-commit-bug should you like to clone it or view the files.  I duplicated data in `setup.py` and `setup.cfg` to verify neither was the issue.

I first noticed this problem because pre-commit couldn't find a script it should be installing:

```sh
› pre-commit run --all-files test-myscript
[INFO] Initializing environment for local.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Test myscript............................................................Passed

› pre-commit run --all-files test-myscript
Test myscript............................................................Failed
- hook id: test-myscript
- exit code: 1

Executable `myscript` not found
```

However, I am able to both successfully install my local setup and get pre-commit to succeed with my manual install:

```sh
› pip install .
Looking in indexes: https://artifacts.riotgames.com/artifactory/api/pypi/pypi/simple
Processing /Users/dfrank/Code/defrank/pre-commit-bug
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: test-scripts
  Building wheel for test-scripts (PEP 517) ... done
  Created wheel for test-scripts: filename=test_scripts-0.0.1-py3-none-any.whl size=2286 sha256=4c121ca65abeb7712eb288ce0bddc7573e4a48fbea513e358a618d8dd736e87a
  Stored in directory: /Users/dfrank/Library/Caches/pip/wheels/0c/74/36/d0180c878574ffc7f6a1f81e47a06b4f00b8659e2c9d9994c8
Successfully built test-scripts
Installing collected packages: test-scripts
Successfully installed test-scripts-0.0.1
WARNING: You are using pip version 20.2.3; however, version 21.1.2 is available.
You should consider upgrading via the '/Users/dfrank/.pyenv/versions/3.9.4/envs/pre-commit-bug/bin/python3.9 -m pip install --upgrade pip' command.

› pre-commit run --all-files test-myscript
Test myscript............................................................Passed
```

# Theory

I believe that my local files are not being copied to the install directory and so the `pre-commit-dummy-package` is being installed instead.

```sh
› ls ~/.cache/pre-commit/
README  db.db  repo_7iplhap

› ls ~/.cache/pre-commit/repo_7iplhap/
Cargo.toml  Makefile.PL  environment.yml  go.mod  main.go  main.rs  package.json  pre_commit_dummy_package.gemspec  py_env-python3.9  renv.lock  setup.py

› diff ~/.cache/pre-commit/repo_7iplhap/setup.py setup.py
1c1
< from setuptools import setup
---
> import setuptools
3,4c3,13
<
< setup(name='pre-commit-dummy-package', version='0.0.0')
---
> setuptools.setup(
>     name="test-scripts",
>     version="0.0.1",
>     author="Derek M Frank",
>     author_email="derek@frank.sh",
>     description="Test installing with pre-commit",
>     python_requires=">= 3.7",
>     scripts=[
>         "scripts/myscript",
>     ],
> )
```

[`pre_commit/languages/python.py:install_environment()`](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py#L204) calls [`pre_commit/languages/helpers.py:run_setup_cmd()`](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/helpers.py#L52) and sets the current working directory for the subprocess to the directory with the dummy `setup.py`:
```python
def run_setup_cmd(prefix: Prefix, cmd: Tuple[str, ...]) -> None:
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
```

**Comment by asottile** [comment]
pre-commit does not install the repository under test ever.

dupe #730 #880 #1406 #1445 #1752 #1837

**Comment by defrank** [comment]
Makes sense.  Thanks for the quick reply.  I fell for the same as https://github.com/pre-commit/pre-commit/issues/1445 by taking the documentation a little too literally.

https://pre-commit.com/#python

> python 
> The hook repository must be installable via `pip install .` (usually by either `setup.py` or `pyproject.toml`). The installed package will provide an executable that will match the `entry` – usually through `console_scripts` or `scripts` in setup.py.

Perhaps it's worth making this a request to clarify the docs that this use-case is not supported?  I wouldn't want others to spend time on it as well.

**Comment by asottile** [comment]
that's for _remote_ repos -- the `local` repository documentation is later on
