### ISSUE TITLE
`pre-commit install` in pre-commit activated repo only replaces .git/hooks/pre-commit

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1931]
Is that intentional? I.e. if I want to re-install pre-commit, I hoped that by default, `pre-push` and other hook scripts would also be replaced without specifying them explicitly via `-t` in [`pre-commit install`](https://pre-commit.com/#pre-commit-install). If it is intentional, maybe adding a note to docs that `-t pre-commit` is the default?

**Comment by asottile** [comment]
dupes are collected in #1145

**Comment by lorenzwalthert** [comment]
I am not sure this is what I meant. I am aware that I can do 
```
pre-commit install --install-hooks -t pre-commit -t commit-msg
```

But my inquiry was rather in a repo where `pre-commit install` was already ran before (e.g. once for pre-commit, once for pre-push), should re-install only overwrite the pre-commit hooks or all hooks? My pre-commit executable changed location (after upgrading with a different installation method, i.e. pip -> brew) so I had to `pre-commit install`, yet pushing still did not work as `.git/hooks/pre-push` still liked the old executable. It's a minor issue though, my concern was only that it could cause a headache for people who are not very experienced with pre-commit.

**Comment by asottile** [comment]
yeah the commands are all stateless (makes it not only easier to implement but easier to reason about and debug)
