### ISSUE TITLE
Questions about additional_dependencies 

### ISSUE THREAD

**Issue by maxxxxxdlp** [pre-commit/pre-commit#1932]
I have a few questions about the behavior of `additional_dependencies` and was not able to find a sufficiently clear answer in the docs.

Does running `pre-commit autoupdate` update `additional_dependencies` too?
Also, in case of node dependencies, I can specify a dependency with or without a version number. E.x `stylelint@^13.8.0` vs `stylelint`. What effect would specifying/omitting the version number have on `pre-commit autoupdate`?

Thanks!

**Comment by asottile** [comment]
#1351 is a dupe for the first question

and the second isn't answerable given the answer to the first
