### ISSUE TITLE
M1 architecture support for python based images

### ISSUE THREAD

**Issue by elbaulp** [pre-commit/pre-commit#1934]
I have a problem trying to get `pre-commit` with `black`, It seems no suitable image can be found:

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "***.cache/pre-commit/repoee16lhm6/py_env-python3/bin/black", line 5, in <module>
    from black import patched_main
  File "**/.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 10, in <module>
    import regex as re
  File "**/.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "***/.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "**/.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(***/.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/***.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/***/.cache/pre-commit/repoee16lhm6/py_env-python3/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture

```
I took a look at  #1786  and setting `language_version: system` but also did not help.

I'm running `pre-commit 2.13.0`

Although it seems its a problem from black itself trying to use some regex package that's not yet supported on the M1?

However, I can run black normally when installed on the system

**Comment by asottile** [comment]
this isn't a pre-commit problem, sorry

**Comment by elbaulp** [comment]
Why do you think so? I can install and run black perfectly without using `pre-commit`, That's why I thought is a `pre-commit` problem

**Comment by asottile** [comment]
what pre-commit does is roughly:

```bash
git clone https://github.com/psf/black
cd black
virtualenv venv
venv/bin/pip install .
```

if that's giving you broken images, it's not a pre-commit problem -- it's probably an issue with either `regex`'s wheels or `pip` picking distributions that aren't correct, or you have an x86_64 python sitting around

an aside, it's working fine on other M1 machines so I suspect you've got a broken setup in some other way

**Comment by elbaulp** [comment]
I just did:

git clone https://github.com/psf/black
cd black
pyenv virtualenv black 3.9.4
pip install .

And got installed... Interesting, I'd need to investigate further and see what may be happening  

Thanks

**Comment by TheKevJames** [comment]
I just came across this issue with https://github.com/lovesegfault/beautysh and a few other hooks; it seems to be affecting some chunk of `language: python` packages, generally those relying on packages which don't have M1 wheels.

For me, the fix ended up being adding a language specifier:
```
default_language_version:
    python: python3.11
```
It seems as though many packages are only building M1 wheels on newer versions, often in places where they've dropped support for older pythons.

I initially thought I had the same behaviour as @elbaulp (running the pip installation steps manually worked, running via pre-commit didn't), but a bit more digging showed I had mistakenly been using `python3.7` via pre-commit but _thought_ I was using python3.11 for that hook.

Hope this helps anyone who hits this in the future!
