### ISSUE TITLE
Pre-commit hook based on an executable (not git repo)

### ISSUE THREAD

**Issue by ikamensh** [pre-commit/pre-commit#1936]
I'd like to run executable coming from pip that isn't available as a git repository. It seems that documentation assumes anything you'd like to run comes from git repositories: https://pre-commit.com/#plugins. How can I run arbitrary shell commands as pre-commit hooks?

**Comment by asottile** [comment]
[`repo: local`](https://pre-commit.com/#repository-local-hooks)
