### ISSUE TITLE
Pass only new files to a hook

### ISSUE THREAD

**Issue by ekans** [pre-commit/pre-commit#1939]
I think it's not possible now but I would like to run a hook only on new files.
It could be "just" a new hook option (like exclude or types).
For instance: pass_added_files, pass_deleted_files, pass_modified_files
Is it something possible in a future release?

As a workaround I set pass_filenames to false and retrieve the list of added files inside the hook.
The problem is I have to do this inside every hooks.

**Comment by asottile** [comment]
check out the approach that `check-added-large-files` uses: https://github.com/pre-commit/pre-commit-hooks/blob/44effd2842e8c71f01240a112487194ca8891ce4/pre_commit_hooks/check_added_large_files.py#L35

it's not a common enough usecase to warrant the complexity in the framework
