### ISSUE TITLE
Improve error message when attempting to run non-existent hook

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#194]
Hook id in `/.pre-commit-config.yaml` doesn't exist in the included repository

(From https://github.com/pre-commit/pre-commit-hooks/issues/37)

It should probably suggest updating hooks or checking the spelling of the hookid

**Comment by Lucas-C** [comment]
+1 I've been bitten by this :)

**Comment by Lucas-C** [comment]
Thanks !
