### ISSUE TITLE
mypy with `--install-types` as an arg fails to install types because process is interactive

### ISSUE THREAD

**Issue by bastienboutonnet** [pre-commit/pre-commit#1944]
I know this is not a problem with pre-commit per se. But as of `mypy==0.902` warnings that stubs were not installed stared popping up while running pre-commit (see example)

```
dbt_sugar/core/ui/cli_ui.py:6: error: Library stubs not installed for "click" (or incompatible with Python 3.7)
dbt_sugar/core/ui/cli_ui.py:6: note: Hint: "python3 -m pip install types-click"
dbt_sugar/core/ui/cli_ui.py:8: error: Library stubs not installed for "yaml" (or incompatible with Python 3.7)
dbt_sugar/core/clients/yaml_helpers.py:7: error: Library stubs not installed for "yaml" (or incompatible with Python 3.7)
dbt_sugar/core/clients/yaml_helpers.py:7: note: Hint: "python3 -m pip install types-PyYAML"
dbt_sugar/core/clients/yaml_helpers.py:7: note: (or run "mypy --install-types" to install all missing stub packages)
dbt_sugar/core/clients/yaml_helpers.py:7: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

I was thinking that passing the `--install-types` as one of the arguments on my pre-commit config would do the trick but I get a failure which I think is due to the fact that `--install-types` requires a yes/no user input (as discussed here: https://github.com/python/mypy/issues/10600#issuecomment-857351152). Here's the error message:
```
Installing missing stub packages:
/Users/bastienboutonnet/.cache/pre-commit/repochpm25o9/py_env-python3.8/bin/python -m pip install types-PyYAML types-click

Install? [yN] Traceback (most recent call last):
  File "/Users/bastienboutonnet/.cache/pre-commit/repochpm25o9/py_env-python3.8/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/bastienboutonnet/.cache/pre-commit/repochpm25o9/py_env-python3.8/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 133, in main
  File "mypy/main.py", line 1093, in install_types
EOFError: EOF when reading a line
```
(also happens when running pre-commit.ci on my public repo (https://github.com/bitpicky/dbt-sugar/pull/290)

Looks like there is a new flag which will be shipped as part of 910 but I was wondering if in the meantime there was a way to run pre-commit with install-types in a way to fake the yes answer? a bit like the comment above does with pipes.

If not I'll turn off that check from mypy until they fix it but I thought maybe there's a way?

**Comment by bastienboutonnet** [comment]
I'm gonna close this because I should have posted it on https://github.com/pre-commit/mirrors-mypy and there's already an issue which you closed there: https://github.com/pre-commit/mirrors-mypy/issues/50

sorry for the noise

**Comment by asottile** [comment]
> I know this is not a problem with pre-commit per se

lol, you knew this was wrong but did it anyway 🙃 

> Looks like there is a new flag which will be shipped as part of 910

even when `--install-types` is implemented properly **it should not be used with pre-commit**

it mutates the running environment which not only breaks caching invariants but can break in mysterious ways (pip is not multiprocess safe) and can lead to false positives and false negatives.  the only supported way to install stubs (as it always has been) is via `additional_dependencies`

I've made a ~relative easy way to restore old typeshed in a way which is safe: https://github.com/asottile/types-all

**Comment by bastienboutonnet** [comment]
> lol, you knew this was wrong but did it anyway 🙃

I'm sorry I only realised after posting that I should have raised it on mypy mirror and then dove into the issues there and saw you had replied. Padonez moi Anthonk!

That being said, thanks for the https://github.com/asottile/types-all trick, I had not seen that before and I'll be using it.

**Comment by john-bodley** [comment]
Thanks @asottile for adding the `type-all` logic. Is there any reason this isn't added to the [default](https://github.com/pre-commit/mirrors-mypy/blob/master/.pre-commit-hooks.yaml) pre-commit hook?

**Comment by asottile** [comment]
the problem is `types-all` is a hack / workaround and would further differ from vanilla mypy

**Comment by Greedquest** [comment]
Hi @asottile, given [types-all](https://github.com/asottile-archive/types-all) is deprecated/hack/static workaround, do you have any more personal tips on getting the most out of pre-commit + mypy?

 > well, not really deprecated but it represents a point-in-time and won't be changing

What do you do in your projects?

**Comment by asottile** [comment]
they're all public, feel free to answer your own question

**Comment by irusland** [comment]
I have solved such problem with running `mypy --install-types --non-interactive`, the [--non-interactive flag](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-non-interactive) installed types silently

**Comment by asottile** [comment]
you're going to break your cache which is intended to be immutable. don't do that https://github.com/pre-commit/pre-commit/issues/1944#issuecomment-862653460
