### ISSUE TITLE
Minimum version requirement for "identify" to ensure correct types are found

### ISSUE THREAD

**Issue by bdice** [pre-commit/pre-commit#1946]
Hi! I noticed that one of my pre-commit hooks wasn't acting right because it missed some files. I needed to update to a newer version of `identify` that recognized those file extensions (I needed `>=2.2.4`). In my understanding, pre-commit requires `identify>=1.0.0`:

https://github.com/pre-commit/pre-commit/blob/8037b45cb1f1cc624bdb3d1d190a4455ce6d4693/setup.cfg#L27

Is there a way to require a minimum version of `identify` within my pre-commit config, to ensure that the behavior is consistent across different users' systems who may have different versions of `identify` installed? I am guessing that this can't be configured at the hook level, since many hooks don't use the pip ecosystem for installation.

If there isn't a way to do that right now, perhaps that could be added to the config in the same way as `minimum_pre_commit_version`. What do you think?

**Comment by asottile** [comment]
pre-commit already produces an error message telling the user to upgrade if the types are missing so I don't see a reason to add this complexity

**Comment by bdice** [comment]
Hmm. The types existed, so no error was thrown, but the types did not cover all the desired file extensions until a later version of `identify`. This felt like a bug, but I could see the argument that this should fall on the user to keep `identify` up to date, since it is a self-contained tool. Thanks for considering it.

**Comment by asottile** [comment]
updating installed packages is absolutely not something that will be automated. read the error message and do what it says
