### ISSUE TITLE
Run all files ignores the specified config file

### ISSUE THREAD

**Issue by spr0ut** [pre-commit/pre-commit#1948]
`pre-commit install --config .pre-commit-config.yml`
pre-commit file exists in .git directory with the correct file referenced
`ARGS = ['hook-impl', '--config=.pre-commit-config.yml', '--hook-type=pre-commit']`

However, running pre-commit run --all-files results in an error:
```
An error has occurred: InvalidConfigError:
=====> .pre-commit-config.yaml is not a file
Check the log at /home/<user>/.cache/pre-commit/pre-commit.log
```
Side note, install --config doesn't appear to validate if a file exists or not.

Environment: WSL2 / Ubuntu 20.04

**Comment by asottile** [comment]
all of the commands are stateless, you're looking for `pre-commit run --config ... --all-files`
