### ISSUE TITLE
Precomit adds dot at end of repository url, breaking auto-hyperlinking

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1950]
All the urls below will give 404, mainly because they end with a dot.

![ss](https://sbarnea.com/ss/Screen-Shot-2021-06-22-13-54-21.71.png)

This is easy to avoid by not printing a dot after the url, as it will no longer confuse hyperlink detection logic.

**Comment by asottile** [comment]
please report to github, their linkifier is broken not our code

**Comment by ssbarnea** [comment]
You know very well that dot is valid part of URI/URL spec, so they can easily say that is not a bug, is only being compliant with the spec.

**Comment by asottile** [comment]
show me a real url that ends with a `.` -- I'll wait

**Comment by marcjay** [comment]
Thought I'd give this a quick test and iTerm2 and Jenkins both handle the URL correctly - not including the trailing dot:

#### iTerm2
(underlines the dot but doesn't include it in the URL)
![image](https://user-images.githubusercontent.com/580744/122938456-abf6bb80-d36a-11eb-8665-6c11dcb949a3.png)
#### Jenkins
![image](https://user-images.githubusercontent.com/580744/122938464-adc07f00-d36a-11eb-87e4-3316c487f322.png)

**Comment by ssbarnea** [comment]
I reported the issue at https://github.com/github/feedback/discussions/4234 as it is not really clear where GH really wants feedback but I still think we should have tuned our own code to avoid that issue, especially considering the percentage of users using pre-commit inside a GHA.
