### ISSUE TITLE
pre-commit.ci autoupdate PR asks to downgrade revision from commit SHA to older tag

### ISSUE THREAD

**Issue by scottclowe** [pre-commit/pre-commit#1957]
**Setup**

I'm using `rev: some_commit_sha` in .pre-commit-config.yaml.

I can't use a tag because the latest tag doesn't contain a feature I need. I would rather use a stable revision over the unstable pointer to the master/main branch because this is better practice and ensures everyone using the repository is working with the same pre-commit hooks.

**Problem**

The autoupdate feature of [pre-commit.ci] is issuing a PR asking to upgrade the revision to the latest tag. However the latest tag is *older* than the revision I have pinned, so moving to the latest tag would actually be a downgrade not an upgrade.

**Full example**

I'm using [black_nbconvert](https://github.com/dfm/black_nbconvert) to automatically blacken notebooks. It's a great tool, but not seen any updates in the last 2 years. The latest release (v0.2.0, Oct 2019) can't handle notebook cells containing cell magic, whereas the bleeding-edge version can.

Contents of [.pre-commit-config.yaml](https://github.com/rochefort-lab/fissa/blob/master/.pre-commit-config.yaml#L37-L40):
```yaml
repos:
  - repo: https://github.com/dfm/black_nbconvert
    rev: dcd7789
    hooks:
      - id: black_nbconvert
```

PRs issued by pre-commit.ci here https://github.com/rochefort-lab/fissa/pull/196 and https://github.com/rochefort-lab/fissa/pull/216 both want to do [github.com/dfm/black_nbconvert: dcd7789 → v0.2.0](https://github.com/dfm/black_nbconvert/compare/dcd7789...v0.2.0) which is a downgrade.
If you [reverse the comparison](https://github.com/dfm/black_nbconvert/compare/v0.2.0...dcd7789) you can see the two commits which are being dropped by the autoupdate PR.

I've asked the author of black_nbconvert to release a new tag with cell magic support (https://github.com/dfm/black_nbconvert/issues/3), which would solve things for this one pre-commit hook but not the problem in general.

What is the best solution? Maybe autoupdate should never try to change revisions which have been pinned to a tag, but to never change revisions pinned to a commit SHA? I'm not sure if this is best, but what seems clear is that autoupdate should not issue a PR asking for a revision to be changed to one that corresponds to an older revision which loses commits without adding any new ones.

Apologies if this is not the right place for pre-commit.ci autoupdate issues. I couldn't see somewhere else to put this.

**Comment by asottile** [comment]
issues for pre-commit.ci live here: https://github.com/pre-commit-ci/issues

but note that this is the same behaviour as `pre-commit autoupdate` -- I'd encourage you to encourage the upstream to make a release and otherwise close the PRs that you do not want

**Comment by scottclowe** [comment]
Ah, thank you for pointing me in the right place.

P.S. Thanks @asottile for all your hard work across the Python QA space! These tools, such as pre-commit, are really fantastic.
