### ISSUE TITLE
Add ability to recreate cached hook venvs from local repository only

### ISSUE THREAD

**Issue by bristea** [pre-commit/pre-commit#1958]
Instead of being forced to use `pre-commit clean` to clean entire tool cache, which is more of BFG which affects execution on all projects, we should have the option to reset/recreate caches related to current repository only.

That is a very useful feature to have, especially as some hooks do require installing current repository, which produces outdated caches from time to time (mypy and pylint being such examples).

As also tox has a very useful `-r` switch, it should not be a bad idea to match its API and when the `-r` is given the already existing caches would not be trusted and they would be recreated.

**Comment by asottile** [comment]
can you show an example? you should never need to recreate venvs as the caching is deterministic.  `pre-commit clean` isn't really intended to ever be used so adding features to it is not going to happen -- but I'd like to better understand what case you think you need it for
