### ISSUE TITLE
ignore autoupdate for specific hook/s

### ISSUE THREAD

**Issue by digitronik** [pre-commit/pre-commit#1959]
Take it as RFE or question

Recently, `mypi` latest version creating problems for my projects. I want to avoid `mypi` hook in `autoupdate`.

Do we have anything which helps me to ignore just a specific hook and allow auto update for all other hooks as per YAML?

I think we can add one tag in yaml like `autoupdate=false` default pre-commit will consider autoupdate=true for all hooks.

**Comment by digitronik** [comment]
@asottile please help me this ^^

**Comment by asottile** [comment]
if you don't want to auto update then don't run auto update

you can use `--repo` to update individual repositories

**Comment by digitronik** [comment]
I think, I failed to explain importance. @asottile think about bot sending PR/MR to n number of projects and user just don't want update for specific hook/repo.

**Comment by asottile** [comment]
you need to upgrade at some point

**Comment by digitronik** [comment]
Exactly, but sometimes project want to support like in my case py36 and mypi latest version creating problem. We need to take hard decision on this but need some time as ecosystem 😃.

If pre-commit provide option to ignore autoupdate for specific hook just like pinning version then it will give freedom to users.

It's just my opinion/Idea.

**Comment by asottile** [comment]
I'm using latest mypy (you're spelling it wrong) with py36 just fine

**Comment by digitronik** [comment]
My bad. In mypy doc they provided awesome note.
Usera need to fix it but definitely need some time.

```Starting in mypy 0.900, most third-party package stubs must be installed explicitly. This decouples mypy and stub versioning, allowing stubs to updated without updating mypy. This also allows stubs not originally included with mypy to be installed. Earlier mypy versions included a fixed set of stubs for third-party packages.```

**Comment by asottile** [comment]
that has nothing to do with python3.6 and if you want to restore all of typeshed without thinking about it see https://github.com/asottile/types-all

**Comment by digitronik** [comment]
Woot... intresting definitely this will solve problem 🙌. I would like to apply this with TODO note.
Thanks!

**Comment by asottile** [comment]
sorry but as above:

> if you don't want to auto update then don't run auto update
