### ISSUE TITLE
Python2 and Python3 with pre-commit

### ISSUE THREAD

**Issue by Dinoshauer** [pre-commit/pre-commit#197]
Hey!

Some of our developers (including me), have python2.7 as the default interpreter for various reasons, we code for python3.4 though, using virtualenvs this is an easy change.

However, pre-commit seems to only use the default interpreter and that can cause many various problems, such as pylint not knowing what is correct and incorrect syntax etc.

Would it be possible to initialize a pre-commit environment with a specific python version? I was thinking maybe to put it in the `.pre-commit-config.yml` in sort of manner like this:

    ---
    py_versions:
      - python2.7
      - python3.4
    ...

That way you could run the pre-commit hook for several environments (sort of like tox) or just choose a specific version. This would solve a lot of our daily gripes with pre-commit

**Comment by asottile** [comment]
Does http://pre-commit.com/#advanced (Overriding Language Version) satisfy your issue?

**Comment by Dinoshauer** [comment]
Hah, oh wow, I had totally missed that :+1: - Seems to work like a charm! It does however seem to be a bit excessive to have to add `language_version` to all `hook.id`s, no?

**Comment by asottile** [comment]
Yeah, I've also thought about changing the config format however that breaks a bunch of things. Which is really my fault for not thinking about future apis. There's been other things in the past where I've reached for a place to configure repository wide things so I'll probably implement something like this eventually.

**Comment by ssbarnea** [comment]
@asottile I encountered today a case with a linter that works only with python3 and my default python is py27. How can we fix this? Documentation was useless in this aspect because it mentioned something about about python_venv as needing extra prerequisites on the system, something that would be a deal breaker hot using a hook. I think we need a "python3" language or something similar.

**Comment by asottile** [comment]
I believe you're looking for [`language_version`](https://pre-commit.com/#overriding-language-version)
