### ISSUE TITLE
Stdout: file not found error

### ISSUE THREAD

**Issue by ag-monk** [pre-commit/pre-commit#1970]
Python version: 3.8.5
Pre-commit —version: 2.13.0
detect-secrets —version: 1.0.3

pre-commit-config.yaml

repos:
  -repo: https://github.com/Yelp/detect-secrets
   rev: v1.1.0
   hooks:
     - id: detect-secrets
        args: [‘—baseline’, ‘.secrets.baseline’]
        exclude: .*/tests/.*
        
Error:
pre-commit install-hooks
[INFO] Installing environment for https://github.com/Yelp/detect-secrets
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes…
An unexpected error has occurred: CalledProcessError: command: (‘c:\\users\\user\\dir\\python-3.8.5-embed-amd64\\python.exe’, ‘-mvirtualenv’, ‘C:\\Users\\user\\.cache\\pre-commit\\repolfrsus6q\\py_env-default’)
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [WinError 3] The system cannot find the path specified: ‘c:\\users\\user\\dir\\python-3.8.5-embed-amd64\\DLLs’

stderr: (none)
Check the log at C:\\Users\\user\\.cache\\pre-commit\pre-commit.log

Seems like virtual env issue. Current virtual env version : 20.4.7 but downgrading version to 20.0.33 did not help.

**Comment by asottile** [comment]
please report to `virtualenv`: https://github.com/pypa/virtualenv

you should be able to reproduce with `c:\users\user\dir\python-3.8.5-embed-amd64\python.exe -m virtualenv venv`
