### ISSUE TITLE
wrong path in case of workdirs 

### ISSUE THREAD

**Issue by daschuer** [pre-commit/pre-commit#1972]
When working with work dirs the conflict check is using the wrong path. This results in a weird error message during a commit with the base worktree in conflict. 
```
[INFO] Checking merge-conflict files only.
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'diff', '--name-only', '--no-ext-diff', '-z', '-m', 'e8fb6f96dfe86b454ceb6913a3e02f88a9103565', 'HEAD', 'MERGE_HEAD')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: mehrdeutiges Argument 'MERGE_HEAD': unbekannter Commit oder Pfad existiert nicht
    im Arbeitsverzeichnis
    Benutzen Sie '--', um Pfade und Commits zu trennen, ähnlich wie:
    'git <Befehl> [<Commit>...] -- [<Datei>...]'
    
Check the log at /home/sperry/.cache/pre-commit/pre-commit.log
```

**Comment by daschuer** [comment]
It is a possible regression from https://github.com/pre-commit/pre-commit/pull/832 fixing https://github.com/pre-commit/pre-commit/issues/831

It looks like we need tow get_git_dir() functions one for the git dir for the regular usage  and  one for the common git dir used during install.

**Comment by asottile** [comment]
you're missing: a reproduction of your error and a test in the pr demonstrating the change

**Comment by daschuer** [comment]
The issue can reproduced like that: 
* create a second worktee from the default worktree that contains the common .git folder 
* create a conflicting merge in the origin worktee
* don't resolve the conflicts 
* change to the other worktree folder 
* change a file 
* commit 
* the error message posted above appears.

I have no clue how to create a test for that. Can you help out here? Is there an other test that can be taken as a template?

**Comment by asottile** [comment]
there's a handful of relevant similar tests in https://github.com/pre-commit/pre-commit/blob/835f9c65e93cdaa517fb87a4cd42edb4f9b084a3/tests/git_test.py#L27 and https://github.com/pre-commit/pre-commit/blob/835f9c65e93cdaa517fb87a4cd42edb4f9b084a3/tests/staged_files_only_test.py

I believe the latter on is relevant to the error you posted above

**Comment by daschuer** [comment]
The test is in place.

**Comment by daschuer** [comment]
Since https://github.com/pre-commit/pre-commit/pull/1973 has been closed, is this issue solved?

**Comment by asottile** [comment]
the pr was incomplete and stale

**Comment by daschuer** [comment]
Do you have plans to fix the issue yourself?

**Comment by asottile** [comment]
not really -- I don't use the feature

**Comment by daschuer** [comment]
So we are back to the PR right? I think I need your help to fix. What is to do to put it into a merge-able state?

**Comment by asottile** [comment]
well the CI is green without your change so something you changed broke things -- you'll have to do some debugging to figure out why
