### ISSUE TITLE
pre-commit seems to consider changing files to be a failure

### ISSUE THREAD

**Issue by duane** [pre-commit/pre-commit#1975]
I don't subscribe to this philosophy. How can I disable it?

**Comment by duane** [comment]
Looking back through issues, the developers seem incredibly hostile to this functionality, so I'm going to close it. However, you can trivially fix this with a change [like this](https://github.com/pre-commit/pre-commit/commit/1fe184f6a2692ea0894ebf60b7b0a0aab2df2816).

**Comment by asottile** [comment]
please search the issue tracker next time!  you _really_ don't want this -- it allows you to commit things which aren't formatted correctly
