### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by milica-nikolic** [pre-commit/pre-commit#1976]
Hi everyone!

Can someone tell me is pre-commit supported on Windows 10 and if it is what instructions can i follow to implement pre-commit ?

Thanks in advance ! :)

**Comment by MarcoGorelli** [comment]
Hi @milica-nikolic 

> what instructions can i follow to implement pre-commit ?

To implement, or to install? To install: https://pre-commit.com/#installation . To implement your own hook: https://pre-commit.com/#new-hooks

**Comment by asottile** [comment]
the [website](https://pre-commit.com) indicates the support and installation instructions, yes it works on windows for most languages
