### ISSUE TITLE
Re-add/re-commit files changed configuration

### ISSUE THREAD

**Issue by basickarl** [pre-commit/pre-commit#1977]
I'm running the following hook:
```
  - id: style_fix
    name: Style Fix
    description: This hook fixes styling.
    entry: bash -c '(cd format-1; npm run style:fix)' --
    language: system
```
It would be nice if there was a setting such as `update` or `allowChanges` which would re-add and re-commit the file changes. We wish to force file changes on file commits as we check for file changes in the repo (not locally).

**Comment by asottile** [comment]
pre-commit will never ever ever modify the staging area, that's not a safe operation and one of the worst anti-features of related tools

See also #1782 #1706 #1342 #1246 #1188 #1099 #1086 #879 #806 #999 #747 (please search the issue tracker next time!)

**Comment by basickarl** [comment]
@asottile Well that simply is your opinion. I'd prefer a more reasonable answer such as:

> Since I do not believe in that practice I will not spend time on it.

For you to dictate how others are to conduct coding is not for you to decide nor of your concern. Also you have no idea what requirements and/or constraints certain projects have. I'm quite bewildered at such illogical behaviour. The amount of requests for such a feature only demises your argument.

**Comment by asottile** [comment]
I'm sorry that free software doesn't do what you want.  next time be a good citizen and search first and do not lecture me on how to run my project.
