### ISSUE TITLE
exclude is not excluding the files listed by regex on macos for golang

### ISSUE THREAD

**Issue by rakheek** [pre-commit/pre-commit#1980]
Here is my exclude for golangci-lint hook:

    - id: golangci-lint
      exclude: |
        (?x)^(
             cmd/scratch.go
            )
This is not excluding the file from the hook. Any advise is appreciated.

**Comment by asottile** [comment]
can you show more output, I cannot see your screen

**Comment by asottile** [comment]
also "not working" is not a bug report, please describe what you're seeing and what you expect to see

**Comment by rakheek** [comment]
Just updated the bug report. Attaching my .pre-commit-config.yaml. Also, attaching the output of git ls-files for the file listed in exclude
`repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
      exclude: |
        (?x)^(
             cmd/scratch.go
            )
#    - id: go-vet
#    - id: go-lint
#    - id: go-imports
#    - id: go-cyclo
#      args: [-over=15]
#    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
      exclude: |
        (?x)^(
             cmd/scratch.go
            )
#    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy`
  `rakheeks-MacBook-Pro:mando rakheekulkarni$ git ls-files |grep scratch
cmd/scratch.go
docs/mando_scratch.md`

**Comment by rakheek** [comment]
Attaching output of pre-commit run which shows that the file is not excluded
`rakheeks-MacBook-Pro:mando rakheekulkarni$  pre-commit run --all-files
go fmt...................................................................Passed
Check files aren't using go's testing package........(no files to check)Skipped
golangci-lint............................................................Failed
- hook id: golangci-lint
- exit code: 1

cmd/scratch.go:13:5: `pod` is unused (deadcode)
var pod string
    ^
cmd/scratch.go:91:6: `subToChange` is unused (deadcode)
func subToChange() {`

**Comment by asottile** [comment]
so pre-commit will filter out that file from the commandline passed into `golangci-lint` -- however my guess is that `golangci-lint` has some sort of linter that doesn't care if you pass filenames to it and it is still detecting your unused code.  for that you'll need to *also* configure golangci-lint's exclude / ignore / whatever their setting is

by the way, I fixed your markdown formatting in the comments -- I'd recommend you check out this video I made which goes over the basics so you can format things nicely in the future!  https://youtu.be/1UodxuXj5Ao

**Comment by rakheek** [comment]
Thank you so much for fixing my markdown formatting. I will definitely check the youtube. You do see that I am excluding on the golangcli-lint hook. Is there a issue with the exclude syntax? I am not getting a error, but exclude is not working.

**Comment by asottile** [comment]
nope! your exclude syntax is correct and pre-commit is handling that correctly (by not passing that filename to `golangci-lint`) -- but `golangci-lint` is doing additional discovery of the files in your repo (unfortunately)
