### ISSUE TITLE
Use of --dev deprecated for npm

### ISSUE THREAD

**Issue by henryiii** [pre-commit/pre-commit#1983]
I'm seeing this warning sometimes (output seems to be hidden unless the install fails):

```
npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
```

Which seems to be because of this:

https://github.com/pre-commit/pre-commit/blob/fe436f1eb09dfdd67032b4f9f8dfa543fb99cf06/pre_commit/languages/node.py#L104

The problem with this command was that it installed dependencies recursively, rendering them useless (AFAICT, not a node expert). The developers decided it was only a footgun in https://github.com/npm/npm/issues/5554#issuecomment-56121953 and deprecated in https://github.com/npm/npm/issues/6200.

**Comment by asottile** [comment]
it's a break either way to change it -- since old npm doesn't support the new flag

the unfortunate thing is that's the command that was recommended by the npm team so...

**Comment by henryiii** [comment]
What about selecting the flag based on npm version, could that be done here? If so I could look up the version that --include=dev was added.

**Comment by asottile** [comment]
good luck parsing npm's version and doing anything reasonable with it 😆 .  I don't think that's a solution which gives long term stability

**Comment by asottile** [comment]
did some research on this, and it looks like we can't replace the code we have for this until *at least* npm 6.x is no longer supported.  which would be the EOL of node 14 2023-04-30

**Comment by sanmai-NL** [comment]
[@asottile ](https://github.com/pre-commit/pre-commit/issues/1983#issuecomment-908807469) And here we are.
