### ISSUE TITLE
YAML Schemas for `.pre-commit-{config,hooks}.yaml`

### ISSUE THREAD

**Issue by yehoshuadimarsky** [pre-commit/pre-commit#1986]
It'd be helpful if there was a schema spec for the yaml files, that would define exactly what they require, and with comments for each entry. Then, it could be integrated into an IDE workflow, similar to the way ArgoCD (unrelated project) does, see their docs here https://argoproj.github.io/argo-workflows/ide-setup/#vscode.

Do you think this is doable?

Thanks!

**Comment by asottile** [comment]
it is not, because some of the choices are not enumerable and some of the types are not representable

fortunately, `pre-commit-validate-*` are provided validate
