### ISSUE TITLE
pre-commit files collection

### ISSUE THREAD

**Issue by foolioo** [pre-commit/pre-commit#1991]
i would like to implement a hook, so i started with a basic hook.

```yaml
# .pre-commit-config.yaml
minimum_pre_commit_version: 2.13.0
repos:
  - repo: local
    hooks:
      - id: foo
        name: foo
        entry: /bin/bash -c 'echo $@'
        language: script
        types:
          - file
```

following pre-commit execution

```shell
$ pre-commit run --verbose --all-files
foo......................................................................Passed
- hook id: foo
- duration: 0s

$ pre-commit run --verbose --files .pre-commit-config.yaml
foo......................................................................Passed
- hook id: foo
- duration: 0s
```

i would expect that when pre-commit is executed as the above, it will output the files which pre-commit collected. in this case, would expect that at least `.pre-commit-config.yaml` will be printed to the screen.

is this an issue with pre-commit or something else?

**Comment by asottile** [comment]
nope, your bash is just incorrect:

```console
$ bash -c 'echo "$@"' hi

```

you want

```yaml
    entry: bash -c 'echo "$@"' --
```

**Comment by asottile** [comment]
you also want `language: system`, `script` is intended for *scripts* relative to the root of the repository

**Comment by foolioo** [comment]
**thank you** @asottile
