### ISSUE TITLE
Command argument for customizing shebang

### ISSUE THREAD

**Issue by guoquan** [pre-commit/pre-commit#1992]
Since it is difficult to determine the python version string in shebang, would it be nice to have a command-line argument, a configuration entry, or an environment variable, that allows users to configure the shebang by themself (while leaving the current approach for finding a default shebang)?

https://github.com/pre-commit/pre-commit/blob/8037b45cb1f1cc624bdb3d1d190a4455ce6d4693/pre_commit/commands/install_uninstall.py#L56-L73

**Comment by asottile** [comment]
the shebang there doesn't really matter -- it is only used in the bootstrapping script to find the original executable

**Comment by guoquan** [comment]
Actually, it does. I have pre-commit installed in a conda virtual environment with python 3.9 and `pre-commit install` with it, resulting a shebang pointing to `python3.9`, while my system default python is python 3.8.
So I would appreciate if it gave me `python3`, instead of `python3.9`.

**Comment by asottile** [comment]
please describe your actual problem instead of prescribing a solution

**Comment by guoquan** [comment]
Actually, it does. I have pre-commit installed in a conda virtual environment with python 3.9 and `pre-commit install` with it, resulting a shebang pointing to `python3.9`, while my system default python is python 3.8.
So I would appreciate if it gave me `python3`, instead of `python3.9`.

It is not a problem if I commit from command-line in my venv.
But when I work with IDEs like vscode, where git is managed by the IDE without knowing my venv, it yields `python3.9 not found`.

**Comment by asottile** [comment]
the only way the code linked would give python3.9 is if you have a python3.9 in /usr/local/bin /usr/bin or /bin and *not* a python3 in /usr/local/bin /usr/bin or /bin

so I suspect there is something you're not telling

please take a step back and do the following:

1. tell me all the versions you're using
2. tell me the commands you ran and their outputs
3. tell me what you expect to see
4. tell me what you're seeing

**Comment by guoquan** [comment]
I am working with macOS and we all know it has python2.
I did check and `/usr/local/bin/python --version` gave me `Python 2.7.17`.

So,
1. I have
  - python 2 with OS,
  - python 3.8 with conda base environment, which will be activated by default in a local shell, 
  - python 3.9 with a conda virtual environment, which I develop with.
2. with zsh,
```
path/to/my/project mybranch*
base ❯ python --version
Python 3.8.5

path/to/my/project mybranch*
base ❯ conda activate myenv

path/to/my/project mybranch*
myenv ❯ python --version
Python 3.9.5

path/to/my/project mybranch*
myenv ❯ python -m pip install pre-commit
Collecting pre-commit
[... many lines]
Successfully installed pre-commit-2.13.0

path/to/my/project mybranch*
myenv ❯ which pre-commit
/Users/me/opt/anaconda3/envs/myenv/bin/pre-commit

path/to/my/project mybranch*
myenv ❯ pre-commit install
pre-commit installed at .git/hooks/pre-commit

path/to/my/project mybranch*
myenv ❯ head -n1 .git/hooks/pre-commit
#!/usr/bin/env python3.9
``` 

3. The last command shows the shebang that has been installed. Well, I hope it can be something pointing to the default python when I start a shell, which is the python 3.8 one in conda base.

4. So as explained above, the git command in development tools uses python with shell default. I have come to understand why you are looking at system-wise python first. But as in my case (with mac), system-wise python should not work.

So, maybe allow users to customize it? or maybe look at shell default as a fallback?

**Comment by asottile** [comment]
can you `ls -al /usr/bin/python* /usr/local/bin/python* /bin/python*` ?

**Comment by guoquan** [comment]
```
base ❯ ls -al /usr/bin/python* /usr/local/bin/python*
lrwxr-xr-x  1 root     wheel      75 Jan  1  2020 /usr/bin/python -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root     wheel      82 Jan  1  2020 /usr/bin/python-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
lrwxr-xr-x  1 root     wheel      75 Jan  1  2020 /usr/bin/python2 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root     wheel      75 Jan  1  2020 /usr/bin/python2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root     wheel      82 Jan  1  2020 /usr/bin/python2.7-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
-rwxr-xr-x  1 root     wheel  137600 Jan  1  2020 /usr/bin/python3
lrwxr-xr-x  1 root     wheel      76 Jan  1  2020 /usr/bin/pythonw -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x  1 root     wheel      76 Jan  1  2020 /usr/bin/pythonw2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x  1 me  admin      38 Dec 25  2019 /usr/local/bin/python -> ../Cellar/python@2/2.7.17_1/bin/python
lrwxr-xr-x  1 me  admin      45 Dec 25  2019 /usr/local/bin/python-config -> ../Cellar/python@2/2.7.17_1/bin/python-config
lrwxr-xr-x  1 me  admin      39 Dec 25  2019 /usr/local/bin/python2 -> ../Cellar/python@2/2.7.17_1/bin/python2
lrwxr-xr-x  1 me  admin      46 Dec 25  2019 /usr/local/bin/python2-config -> ../Cellar/python@2/2.7.17_1/bin/python2-config
lrwxr-xr-x  1 me  admin      41 Dec 25  2019 /usr/local/bin/python2.7 -> ../Cellar/python@2/2.7.17_1/bin/python2.7
lrwxr-xr-x  1 me  admin      48 Dec 25  2019 /usr/local/bin/python2.7-config -> ../Cellar/python@2/2.7.17_1/bin/python2.7-config
lrwxr-xr-x  1 me  admin      40 Nov 11  2020 /usr/local/bin/python3 -> ../Cellar/python@3.9/3.9.0_1/bin/python3
lrwxr-xr-x  1 me  admin      47 Nov 11  2020 /usr/local/bin/python3-config -> ../Cellar/python@3.9/3.9.0_1/bin/python3-config
lrwxr-xr-x  1 me  admin      42 Nov 11  2020 /usr/local/bin/python3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/python3.9
lrwxr-xr-x  1 me  admin      49 Nov 11  2020 /usr/local/bin/python3.9-config -> ../Cellar/python@3.9/3.9.0_1/bin/python3.9-config
lrwxr-xr-x  1 me  admin      39 Dec 25  2019 /usr/local/bin/pythonw -> ../Cellar/python@2/2.7.17_1/bin/pythonw
lrwxr-xr-x  1 me  admin      40 Dec 25  2019 /usr/local/bin/pythonw2 -> ../Cellar/python@2/2.7.17_1/bin/pythonw2
lrwxr-xr-x  1 me  admin      42 Dec 25  2019 /usr/local/bin/pythonw2.7 -> ../Cellar/python@2/2.7.17_1/bin/pythonw2.7

~
base ❯
```
Oh, I didn't know I had python 3.9 here.

But one strange thing is, when I `pre-commit install` with conda base env, it gave python3.8 shebang, which I currently use as work around.

**Comment by asottile** [comment]
like I suspected, next time please include details when making an issue
