### ISSUE TITLE
Hooks that need the filename list not at the end of their argv

### ISSUE THREAD

**Issue by zackw** [pre-commit/pre-commit#1993]
I'd like to reopen discussion on a generalized version of the problem described in #1000. I think that earlier discussion got tied up in knots because it was focusing on an overly specific scenario, the unusual way `clang-tidy` and related programs use the special `--` argument.  Here's the generalization:

1. Some programs, that it makes sense to run from a pre-commit hook, expect a list of files to examine *not* at the end of their command line.
2. pre-commit hooks that wrap a program with a complicated command-line interface may have trouble telling which of their arguments are actually filenames.

To solve these problems I propose these two new features:

1. If the special argument `${FILES}` (exactly as shown) appears in the `args:` or `entry:` array of a hook configuration, the list of files to examine is inserted in place of it, instead of at the end.
2. When running each hook, pre-commit sets an environment variable `PRE_COMMIT_FILE_INDS` to a comma-separated list of all the indices in that hook's argv array that represent file names.

For example, this local hook configuration

```
-   repo: local
    hooks:
    -   id: clang-tidy
        language: system
        types_or: [c, c++]
        entry: ['clang-tidy', '-checks=clang*,bugprone*', '${FILES}', '--', '-I', 'include']
```

would, when `foo.c` and `bar.cxx` had changed, run the equivalent of the shell command

```
PRE_COMMIT_FILE_INDS=2,3 clang-tidy '-checks=clang*,bugprone*' foo.c bar.cxx -- -I include
```

What do you think? I could probably find the time to implement it if you like it.

/cc @pocc

**Comment by asottile** [comment]
no sorry, my decision there was final -- and substitutions will not be implemented

**Comment by zackw** [comment]
I'm disappointed to hear that.  This is not just a problem for clang-tidy.  In compiled code land it is common to have tools with very complicated, order-dependent command line interfaces, where the list of input files isn't necessarily the last thing that goes on the command line.

Would you at least consider adding the suggested environment variable?  If the files are always at the end, it can be just a single number (the index of the first argument that is a file).  This would make it possible to deal with these tools reasonably easily with a wrapper script.  Right now, such scripts have to have detailed knowledge of how the underlying tool parses its command line to work reliably, and often that's just not practical.

**Comment by asottile** [comment]
I don't think there'd be any value since you already have to write a wrapper.  just use whatever uncommon separator you want and then separate the arguments (as the solution to #1000 did).
