### ISSUE TITLE
autoupdate downdates

### ISSUE THREAD

**Issue by skycaptain** [pre-commit/pre-commit#1994]
Pre-commit 2.13.0 autoupdate downdates in the following case:

`.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.3.51'
    hooks:
      - id: editorconfig-checker
```

```shell
$ pre-commit --version
pre-commit 2.13.0

$ pre-commit autoupdate
Updating https://github.com/editorconfig-checker/editorconfig-checker.python ... updating 2.3.51 -> 2.3.5.
```

The latest version of editorconfig-checker.python is actually 2.3.51.

**Comment by asottile** [comment]
the latest tag on the primary branch is....:

```console
$ git describe --tags --abbrev=0
2.3.5
```

**Comment by skycaptain** [comment]
Hmm, indeed you are right. They must have messed up their release pipeline as there is a 2.3.51 release and Git tag, but not on the main branch. Actually, dependabot suggested 2.3.51, so the issue is on their side. Thanks.
