### ISSUE TITLE
Use content of staged file instead of working-directory content

### ISSUE THREAD

**Issue by DanielSmit** [pre-commit/pre-commit#2013]
# Background
I used a git-attribute-clean-filter to filter the contents of large files. (In particular it was `nbstripout` to remove outputs from `.ibynb-files`).
I ran into an issue with the `check-added-large-files`:

The  `check-added-large-files`-hook reported the .ipynb-file to be to large. This is true for the unfiltered version of the file (as it is in the working directory) but not for the actual content of the staged version of the file (as I verified with `git diff --staged`), which is way smaller and under the size-limit.

# My Understanding
As far as I was able to track, in general arguments to pre-commit-hooks are the paths to staged files in the working directory.

I verified this with the identity-meta-hook.

So my guessing is, that the `check-added-large-files` will check the file-size of the file in my working dir, not the version of the file in the staging area.

# Wanted behaviour
(All) pre-commit-hooks should work with the staged versions of the files, as they might have been altered by filters and possibly differ from the files in the working-directory.

**Comment by DanielSmit** [comment]
Thinking about it, maybe it is better to make the proposed working on staged files an optional setting. (Cause I guess in general modifiying the file based on the working-directory content is preferable)

**Comment by asottile** [comment]
problems with smudge filters are currently collected in #776
