### ISSUE TITLE
pre-commit adds non-optional arguments to local system hook

### ISSUE THREAD

**Issue by trallnag** [pre-commit/pre-commit#2014]
For whatever reason pre-commit seems to add non-optional arguments when using local system hooks. This is no problem for entries that simply ignore additional arguments, but some utilities start to throw around errors.

## Reproduce

Take any project where pre-commit is setup. Add the following to pre-commit config:

```yaml
  - repo: local
    hooks:
      - id: reqs
        name: reqs
        language: system
        entry: echo HALLLO
        args: []
```

Run the hook with `pre-commit run reqs`.

```
❯ git add .pre-commit-config.yaml; pre-commit run --verbose reqs
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/jfn/.cache/pre-commit/patch1629239297-17805.
reqs.....................................................................Passed
- hook id: reqs
- duration: 0s

HALLO .pre-commit-config.yaml

[INFO] Restored changes from /home/jfn/.cache/pre-commit/patch1629239297-17805.
```

Notice the "HALLO .pre-commit-config.yaml". 

As mentioned, tools like Poetry don't like additional arguments.

```
Too many arguments.
```

**Comment by MarcoGorelli** [comment]
Does `pass_filenames: false` not work for this use case?

**Comment by trallnag** [comment]
Indeed @MarcoGorelli, this works. Seems like I've skipped over this knob in the documentation. Thanks a lot
