### ISSUE TITLE
Default stages require commit for manual run

### ISSUE THREAD

**Issue by Matthijsy** [pre-commit/pre-commit#2015]
I am trying to run the pre-commit hooks manual in our CI to check that everything is linted correct. However, when `commit` is not present in the `default_stages` configuration, it seems that `pre-commit run --all-files` does not run anything.

Config file
```
default_stages: [manual, push]
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
```

If I change the config file to include commit it does run. I was using pre-commit version 2.14.0

**Comment by asottile** [comment]
[`pre-commit run`](https://pre-commit.com/#pre-commit-run) has a `--hook-stage` which defaults to `commit`
