### ISSUE TITLE
Ruby hooks require system dependencies even if `language_version` is specified

### ISSUE THREAD

**Issue by Holzhaus** [pre-commit/pre-commit#2016]
Despite the [documentation stating that no system dependencies are needed to run ruby hooks](https://pre-commit.com/#ruby), this currently doesn't seem to be the case.

- Without `language_version`, `pre-commit` doesn't detect if ruby is installed apparently, and fails with the issue mentioned in #1999. (reported here: https://github.com/mixxxdj/mixxx/pull/4222#issuecomment-901157068)
- With `language_version` specified, it fails to compile. A Fedora user reported that it fails with: `The Ruby readline extension was not compiled. ERROR: Ruby install aborted due to missing extensions. Try running 'yum install -y readline-devel' to fetch missing dependencies.` (reported here: https://github.com/mixxxdj/mixxx/pull/4222#issuecomment-901199817)

For now, I worked around this issue by using the nodejs-based markdown linter instead of the ruby-based one :wink: 

PS: Thanks for this great tool btw, I use it in all my projects now!

**Comment by asottile** [comment]
if you select a version with prebuilt binaries you won't need to build from source -- but yes if you don't have prebuilt binaries available for your platform you'll need to build

**Comment by Holzhaus** [comment]
I suppose it's not feasible to fetch build depenencies for all platforms or download statically built ruby versions. However, I think the documentation should be improved, i.e. that ruby hooks *require system dependencies* unless a `language_version` is specified and a prebuilt binary exists for your platform.
