### ISSUE TITLE
`check-useless-excludes` meta hook doesn't seem to work well with broken symlinks

### ISSUE THREAD

**Issue by pkoch** [pre-commit/pre-commit#2019]
Repro steps
1. Add a submodule
2. Add a symlink to somewhere inside this submodule
3. Use `check-symlinks`
4. Deinit submodule (to simulate the case when people clone without `--recursive`)
4. Notice that it now complains about the symlink created on 2
5. Add an exclude entry with the path to that symlink
6. Use `check-useless-excludes`
7. Notice that it complains that the added exclude entry doesn't apply.

For a working example, check out https://github.com/pkoch/test-check-useless-excludes (without `--recursive`, or run `git submodule deinit --all`) and run `pre-commit run --all`.

**Comment by asottile** [comment]
hmm indeed -- the "test" hook gets initialized with `types: [file]` which filters out the symlink -- the fix needs to happen [here](https://github.com/pre-commit/pre-commit/blob/509e4e20e86b5db48bc827753dcdfcdbbd706812/pre_commit/meta_hooks/check_useless_excludes.py#L48) -- notably it should probably have a `hook.setdefault('types', [])` ? something like that?

**Comment by pkoch** [comment]
Unsure, can't really reason about the code. However, I can add that adding `types: []` to `check-useless-excludes` doesn't help.

**Comment by pkoch** [comment]
Interesting! Any clues on why adding `types: []` on my side didn't help?

**Comment by asottile** [comment]
my guess is you added it to the wrong thing, but you don't actually want
that at runtime anyway
