### ISSUE TITLE
The `try-repo` command should add the possibility of specifying hook arguments

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit#2021]

**Comment by asottile** [comment]
dupe #1905 -- `try-repo` is meant as a shortcut, you can always create your own configuration to test hooks

**Comment by revolter** [comment]
I have my own configuration, but I don't know how to test uncommited changes to my hooks repository.

**Comment by asottile** [comment]
you can't, you'll need to commit and `--amend`

**Comment by asottile** [comment]
(another thing you can do is set `args` in your `.pre-commit-hooks.yaml` while testing -- it will work exactly the same as it being set in `.pre-commit-config.yaml`)

**Comment by revolter** [comment]
> (another thing you can do is set `args` in your `.pre-commit-hooks.yaml` while testing -- it will work exactly the same as it being set in `.pre-commit-config.yaml`)

If I do this, then I also need to set the `filenames` argument that I'm already setting under the `--commit-msg-filename` one.

**Comment by revolter** [comment]
> you can't, you'll need to commit and `--amend`

Ok. And then, how do I test it without pushing the commit changes? Because `try-repo` still doesn't use my config file, even if the changes are commited.

**Comment by asottile** [comment]
`pre-commit run --config your-test-config ...`  and your separate configuration can point to a filesystem location (this is what was done before `try-repo` streamlined it) -- I go over this workflow in the issue linked above

**Comment by revolter** [comment]
Thank you very much for your time.

**Comment by revolter** [comment]
> If I do this, then I also need to set the `filenames` argument that I'm already setting under the `--commit-msg-filename` one.

Actually, I think that this is a bug. Since I commited, tagged, and pushed my changes, and it crashes when I try to commit. Meaning, `pre-commit` stops sending the commit message filename to my hook.

**Comment by revolter** [comment]
Oooh, it adds it at the end :(

**Comment by revolter** [comment]
I fixed it by using

```python
parser.add_argument('--allowed-label', action='append')
```

instead of

```python
parser.add_argument('--allowed-labels', nargs='+')
```
