### ISSUE TITLE
How to check if hooks are already installed?

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2032]
Does the pre-commit CLI offer a way to verify that hooks have been installed? Something like `pre-commit isinstalled`? Would be useful for humans as well as for e.g. `package.json` scripts:

```json
{
  "scripts": {
    "prepublishOnly": "pre-commit isinstalled"
  }
}
```

**Comment by asottile** [comment]
`pre-commit install` is idempotent so I don't think there's a need for such a script

**Comment by janosh** [comment]
> I don't think there's a need for such a script

Then how would you fail lifecycle hooks like `prepublishOnly` if `pre-commit` is not installed?

`pre-commit install` gives the same output no matter what. Even in a repo without a config file, it prints

> pre-commit installed at .git/hooks/pre-commit

Wouldn't it be better to issue a warning here?

**Comment by asottile** [comment]
> 
> 
> > I don't think there's a need for such a script
> 
> Then how would you fail lifecycle hooks like `prepublishOnly` if `pre-commit` is not installed?
> 

why would you want that?  it doesn't enforce that they were run

> `pre-commit install` gives the same output no matter what. Even in a repo without a config file, it prints
> 
> > pre-commit installed at .git/hooks/pre-commit
> 
> Wouldn't it be better to issue a warning here?

a warning is useful for a problem scenario -- there is no problem (`mkdir -p` doesn't print a warning for example)

**Comment by janosh** [comment]
> why would you want that? it doesn't enforce that they were run

It does for a benevolent user like myself. The scenario I'm targeting is that I forget to install pre-commit hooks. If I then try to publish and that fails because hooks aren't installed, I know that whatever I just committed still needs to be checked.

> a warning is useful for a problem scenario -- there is no problem (mkdir -p doesn't print a warning for example)

If the user runs a command that makes no sense in the absence of a config file, they're probably working under false assumptions so a warning or at least printing that this was a no-op makes sense.

**Comment by asottile** [comment]
I don't think this warrants the complexity, use `test -x .git/hooks/pre-commit`

**Comment by janosh** [comment]
What's supposed to happen here? I get nothing:
```sh
>>> rm -rf .git/hooks/pre-commit 
>>> test -x .git/hooks/pre-commit
>>>
```

**Comment by asottile** [comment]
`echo $?`

[about test](https://youtu.be/8kFmJGXa1qk)

**Comment by janosh** [comment]
Thanks!
