### ISSUE TITLE
Executing a hook after switching from a branch which edits a rev in .pre-commit.yaml uses wrong version of hook

### ISSUE THREAD

**Issue by quentinelwin** [pre-commit/pre-commit#2034]
Hi,

In my repo, I was working on a branch which had edited the value of a "rev" field in the .pre-commit.yaml file (in this case, the version of mypy). When I go back to my main branch, and execute pre-commit, I noticed that it executes the version of the hook of the other branch.

I thought pre-commit would detect any change in the .pre-commit.yaml file compared to the version of hooks which are installed and update themselves, as it does when I edit a rev and commit it. Then how can I force pre-commit to use the exact versions written in the .pre-commit.yaml file? I did not see anything about this in the documentation.

**Comment by asottile** [comment]
please show a reproduction -- it does not work how you describe
