### ISSUE TITLE
Modify foreground rather than background color to improve readability

### ISSUE THREAD

**Issue by mikepqr** [pre-commit/pre-commit#2038]
Would you take a PR that changed the default colors such that, e.g. PASSED is green text on the user's default background (rather than the user's default foreground on a green background)?

I think this would improve readability for most color schemes (users generally pick these colors with use as foreground text in mind). Light/white on green in particular is very hard to read. It would also be consistent with pytest, which does not modify the background on the happy path.

I've attached a screenshot from my terminal. The top 10ish lines is pytest (looks great to me!), the middle 10ish lines is pre-commit's current behavior, and the bottom 10ish lines is pre-commit patched as described above.

<img width="717" alt="Screen Shot 2021-09-03 at 15 23 48" src="https://user-images.githubusercontent.com/370930/132072665-edd6a457-f2b4-4cc1-9df4-193620f13a8c.png">

**Comment by asottile** [comment]
please search the issue tracker for duplicates

I am not going to change the branding

**Comment by mikepqr** [comment]
I did search (and see several people raise the general issue of poor legibility), but the specific suggestion here is not a duplicate of any issue. If it appears to you to be a duplicate then you might find it useful to read it again.

**Comment by mikepqr** [comment]
For anyone else who finds this issue, you can patch [this line](https://github.com/pre-commit/pre-commit/blob/36b8ad63d2d92e8413146e868910964fbf1e46e4/pre_commit/color.py#L58) to `GREEN = '\033[32m'` (and make similar changes to the other colors, i.e. subtract 10 from the escape code) to get the improved behavior in the screenshot above.
