### ISSUE TITLE
mypy missing types-PyYAML when used by pre-commit but is fine when used solo

### ISSUE THREAD

**Issue by spidermila** [pre-commit/pre-commit#2041]
### describe your issue

Hi Anthony, glad I can test your new bud report form but not happy about the circumstances. I hope this all is not just a problem specific to my server.
I have started using yaml in my small project https://github.com/spidermila/dungeon and pre-commit started complaining at the mypy stage:
```
world.py:9: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
world.py:9: note: Hint: "python3 -m pip install types-PyYAML"
world.py:9: note: (or run "mypy --install-types" to install all missing stub packages)
world.py:9: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
When I run mypy directly, it's fine:
```
 mypy dungeon.py
Success: no issues found in 1 source file
```

I am using Python 3.9.5, mypy and pre-commit installed in virtualenv. 
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

uname -a
Linux nas 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

python -m pip freeze
backports.entry-points-selectable==1.1.0
cfgv==3.3.1
distlib==0.3.2
filelock==3.0.12
identify==2.2.13
mypy==0.910
mypy-extensions==0.4.3
nodeenv==1.6.0
platformdirs==2.3.0
pre-commit==2.15.0
PyYAML==5.4.1
six==1.16.0
toml==0.10.2
types-PyYAML==5.4.10
typing-extensions==3.10.0.2
virtualenv==20.7.2

```

Steps to reproduce:
1. create new virtual environment + clone the project from github
2. activate the virtualenv
3. python -m pip install mypy
4. python -m pip install types-PyYAML
5. python -m pip install pre-commit
6. mypy dungeon.py # will work fine
7. modify dungeon.py, git add -u
8. pre-commit # mypy will end with error

I used to have mypy installed by apt, but I have removed it and now it's the one from the virtual environment that is being used. Is there maybe a way how to check which mypy is used by pre-commit, or how to install the missing stub package there?

Thanks!

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
```

### ~/.cache/pre-commit/pre-commit.log (if present)

log file not present

**Comment by MarcoGorelli** [comment]
> or how to install the missing stub package there

You just need to add in to `additional_dependencies`, like in example from the mirrors-mypy README https://github.com/pre-commit/mirrors-mypy

**Comment by spidermila** [comment]
> 
> 
> > or how to install the missing stub package there
> 
> You just need to add it to `additional_dependencies`, like in example from the mirrors-mypy README https://github.com/pre-commit/mirrors-mypy

So it was just my poor understanding how pre-commit works.
The solution worked like a charm. Thank you very much!

**Comment by anhtuank7c** [comment]
I have `additional_dependencies` but it still shows an issue regarding missing types-PyYAML.
Please help.

![CleanShot 2024-10-25 at 15 50 27@2x](https://github.com/user-attachments/assets/3c8e5664-6390-4337-9a59-3e9e02c9b74d)
![CleanShot 2024-10-25 at 15 53 49@2x](https://github.com/user-attachments/assets/2fd769e5-7eb0-41b4-9e48-81b9d87f39dd)

**Comment by asottile** [comment]
why would you think that installing tokenize-rt would help you with types-pyyaml?

**Comment by anhtuank7c** [comment]
@asottile my bad. I install types-PyYAML to the `additional_dependencies`. it works. Thank you so much.
