### ISSUE TITLE
add warning for regular expression with `[/\]`

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#2043]
pre-commit normalizes slashes to forward slashes since 2.5.0 (and further back to 1.19.0 for per-hook configuration)

there's already a [similar warning for `/*`](https://github.com/pre-commit/pre-commit/blob/2ef29b7f95384f899ede86a370bf2a1c766095b4/pre_commit/clientlib.py#L140-L145) so this should be a fairly beginner-friendly changeset

**Comment by dogukanteber** [comment]
Can you open up the issue a little more, please? I do not understand the problem exactly.

**Comment by asottile** [comment]
right now, one may write something like:

```yaml
    files: ^somedir[/\].*\.py$
    # or
    exclude: ^somedir[\/]otherdir[\/].*\.py$
```

expecting that they need to match both posix paths `somedir/foo/bar.py` and windows paths `somedir\foo\bar.py` -- however this is unnecessary because pre-commit normalizes all slashes to forward slashes

there's a similar regular expression warning for doing something like `files: whatever/*.py` where someone assumes that it is a glob and not a regex

**Comment by asottile** [comment]
via #2053
