### ISSUE TITLE
Windows: Large number of files causes `xargs: ... Bad file number`

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#205]
Originally here: https://github.com/pre-commit/pre-commit-hooks/issues/41

**Comment by asottile** [comment]
I think I might be able to solve this with xargs -s perhaps

**Comment by guykisel** [comment]
Based on my googling that does sound like a good way to handle this issue. It's actually surprisingly difficult to find much information about this.

**Comment by asottile** [comment]
The other idea I have is it is hitting the file descriptor limit which seems to be surprisingly low on windows.

**Comment by guykisel** [comment]
Is pre-commit actually opening all of those files at once, though? It doesn't seem like these hooks would actually be hanging on to file descriptors.

**Comment by asottile** [comment]
pre-commit shouldn't be grabbing file descriptors.  I did see the same problem with just `git add` which makes me think it might be some git internal that's misbehaving.  At the moment I'm trying to reproduce this under test (and not just interactively) and failing :/

**Comment by guykisel** [comment]
> On computers running Microsoft Windows XP or later, the maximum length of the string that you can use at the command prompt is 8191 characters. On computers running Microsoft Windows 2000 or Windows NT 4.0, the maximum length of the string that you can use at the command prompt is 2047 characters.

In Linux it's more like a few megabytes worth of text I think.

**Comment by asottile** [comment]
Linux depends on the implementation. POSIX says 4096 is the lowest minimum so I'm going to choose `-s 4000` to be pretty safe.

**Comment by guykisel** [comment]
Cool, sounds good.

**Comment by asottile** [comment]
@guykisel Please check v0.4.2 (just released)!

**Comment by guykisel** [comment]
Just tested it. Confirmed as fixed. Thank you!
