### ISSUE TITLE
Feature request: run separate hooks in parallel

### ISSUE THREAD

**Issue by ajgrover** [pre-commit/pre-commit#2050]
From my brief reading of how `pre-commit` is working, it looks like each hook can be run in parallel with itself and is partitioned with each thread being sent groups of files. I'd like to be able to run entire hooks in parallel with each other.

Concrete use case: my team has the following hooks:
- a couple of linters/formatters (rewrites files)
- check that the project's dependencies are up to date with what's installed locally (does not rewrite any files)
- check that the Django migrations are in sync with what's in our application (does not rewrite any files)

The final hook takes longer than the rest of the hooks combined because it requires booting our app. Because it doesn't actually modify any code, it could feasibly be kicked off at the beginning of the pre-commit run and run while the linters and other hooks are running. This would reduce the amount of time it takes to commit by around 1/2 and would be very welcome.

Not all hooks can be parallelized (our linters rewrite files so they'd conflict unless run serially) so I'd imagine there will need to be an option for this at the hook level.

**Comment by asottile** [comment]
there's a duplicate somewhere

there isn't a way to do this safely -- and generally it doesn't lead to any performance improvements (tools are already run in parallel)

**Comment by asottile** [comment]
also you should generally not run slow hooks as part of pre-commit -- those sorts of tasks are better done in a CI task

**Comment by ajgrover** [comment]
i see https://github.com/pre-commit/pre-commit/issues/510 which looks like it resulted in the current per-hook parallel behavior, but beyond it being complicated it doesn't seem like the consensus was that it's impossible to de safely, especially if individual hooks can opt in.

my hooks are nowhere near as slow as the 105 second one in that issue but even a couple hooks that take 5-10 seconds each run serially can add up

**Comment by dudicoco** [comment]
As @alex-grover wrote [#510](https://github.com/pre-commit/pre-commit/issues/510) only touched per-hook parallel behavior.

We are also in need of parallel execution for all hooks, the use case here is when running several local hooks with `language: docker_image`, the execution takes 10-20 seconds when running locally on mac (docker desktop performance is terrible), and it takes even longer on the CI because github actions cannot cache docker images and pulls them each time.

@asottile what is the blocker for implementing such a feature?

**Comment by asottile** [comment]
as above the blocker is it's complex, not safe in the general case, and won't help in the general case
