### ISSUE TITLE
Manually caching a hook repository without a configuration file

### ISSUE THREAD

**Issue by robhanlon22** [pre-commit/pre-commit#2054]
Hello! I'm wondering if it's possible to issue a pre-commit command that will clone and cache a particular hook repository and revision. The use case here is that I'm building a generic Docker image to run some tests on CI that doesn't rely on a particular local repository, but will at some point have a repository volume mapped into it to run tests, and I'd like to avoid having each test run clone the configured hook repositories before checking issues with `pre-commit run`. Thanks.

**Comment by asottile** [comment]
an installed hook is two parts: the base repository and the configuration overlayed on top of it -- you can't build an installed hook with only one of those two parts

check out https://pre-commit.ci by the way
