### ISSUE TITLE
Question: Support a pre-commit hook without git clone (i.e. because the tool is already installed)

### ISSUE THREAD

**Issue by adamcunnington** [pre-commit/pre-commit#2055]
I find that certain pre-commit hooks that I want to run are actually already installed (e.g. black, isort, prospector). I have two issues with specifying the repo in the config file:
1) It's wasted time in CI because the tools are already installed.
2) Having to maintain the exact version of the repo that should be cloned in addition to the version that should be maintained in requirements-dev.txt (or whatever) is not ideal.

I assume the answer to my question of whether this can be achieved is no as I think it would come with lots of complications. The pre-commit-hooks aren't likely to be installed so perhaps this could just be an alternative option. I.e. rather than prodiving `repo: ...`, i could provide `local: prospector` where `prospector` is an actual local command that can be ran directly.

**Comment by asottile** [comment]
you're kind of missing the point of pre-commit which is to install and maintain your tools.  that said, you can continue in unsupported territory with `repo: local` and `language: system` / `language: script` as documented
