### ISSUE TITLE
Support pyproject.toml for configuration

### ISSUE THREAD

**Issue by adamcunnington** [pre-commit/pre-commit#2056]
I am aware that this has been asked multiple times, upvoted multiples times, and closed multiple times but please can I emplore the maintainer to consider this afresh again.

pyproject.toml is increasingly becoming the standard for storing tool configuration. This is a really great thing because projects can otherwise, easily have tens of configuration files which is just crazy. We use about 10 tools during the dev workflow of our projects and pre-commit is now the only one that does not support pyproject.toml. I appreciate migrating the config is not straight forward but that doesn't mean it shouldn't be properly considered. Thus far, the topics that were closed were closed quite bluntly with no invitation for discussion. I would like to open an issue where there can be a productive discussion about this ask and what it would entail. Perhaps there are some community members that would be willing to contribute all of part of the implementation.

**Comment by asottile** [comment]
> I am aware that this has been asked multiple times, upvoted multiples times, and closed multiple times but please can I emplore the maintainer to consider this afresh again.

are you serious?
