### ISSUE TITLE
Pre-commit Proxy Feature

### ISSUE THREAD

**Issue by theoricien** [pre-commit/pre-commit#2059]
### describe your issue

When installing depedencies, the user may trigger errors by _pip_ because pip don't go through a proxy.
The user should setup a proxy (env variable, configuration file, CLI argument) to solve this issue.

**Hot Local Fix**: In the pre-commit package, put your proxy in https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py#L200

Example:
```Py
def install_environment(
        prefix: Prefix,
        version: str,
        additional_dependencies: Sequence[str],
) -> None:
    # SNIP
    install_cmd = ('python', '-mpip', '--proxy', MY PROXY, 'install', '.', *additional_dependencies)
    # SNIP
```

### pre-commit --version

N/A

### .pre-commit-config.yaml

```yaml
N/A
```

**Comment by asottile** [comment]
you can put pip options in `additional_dependencies`

please don't recommend people hot edit the code
