### ISSUE TITLE
Support for installing Python packages already specified in the project under test

### ISSUE THREAD

**Issue by altendky** [pre-commit/pre-commit#2061]
I would like to be able to install the dependencies of the project under test, including an extra, into the environment created for running mypy.  mypy is of fairly limited use if you don't have your project's dependencies and it is a hassle to maintain another copy of that dependency list in the pre-commit configuration file.

This is somewhat similar to https://github.com/pre-commit/pre-commit/issues/1526 and it took me awhile to realize the difference.  There, they wanted to install an extra of the hook's project.  `.` seems to refer to the local clone of the hook repository and so it works.  I want to be able to install something from the project under test, not the hook.

https://github.com/pre-commit/pre-commit/blob/66c51a3d568ee36f16cd0127059501daefbc0560/pre_commit/languages/python.py#L190-L205

Given that `.` seems to refer to the hook repository, I don't expect there's any way to specify a path portably to refer to the project under test.

Am I missing something and this is a support request, or is this a feature request?

**Comment by asottile** [comment]
there are many duplicates collected in https://github.com/pre-commit/pre-commit/issues/730#issuecomment-835856309
