### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application Error

### ISSUE THREAD

**Issue by SAG786** [pre-commit/pre-commit#2067]
I have .pre-commit-config.yaml as -
`repos:
-   repo: local
    hooks:
    -   id: commit-msg
        name: commit-msg
        entry: ./src/scripts/commit-msg.sh
        language: script`

While commiting this on windows getting WinError 193. 

content of commit-msg.sh
`echo "inside commit-msg shell file`

**Comment by asottile** [comment]
you're missing a shebang -- `#!/usr/bin/env bash` for example
