### ISSUE TITLE
Failures when hook ids are non-ascii

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#207]
```
$ pre-commit run ☃
An unexpected error has occurred: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Check the log at ~/.pre-commit/pre-commit.log
$ cat ~/.pre-commit/pre-commit.log 
An unexpected error has occurred: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/asottile/workspace/pre-commit/pre_commit/error_handler.py", line 34, in error_handler
    yield
  File "/home/asottile/workspace/pre-commit/pre_commit/main.py", line 129, in main
    return run(runner, args)
  File "/home/asottile/workspace/pre-commit/pre_commit/commands/run.py", line 163, in run
    return _run_hook(runner, args, write=write)
  File "/home/asottile/workspace/pre-commit/pre_commit/commands/run.py", line 133, in _run_hook
    write('No hook with id `{0}`\n'.format(hook_id))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by Lucas-C** [comment]
Same error here, after running a `mvn test` invoking JUnit tests.
I don't have time to write a minimal test case right now sadly.

**Comment by asottile** [comment]
I have a fix for the issue reported, I imagine your fix is a UnicodeDecodeError somewhere else though (or why are are you using unknown non-ascii hook ids?), I'd love to see that stacktrace :)

**Comment by Lucas-C** [comment]
My bad, sorry, my issue is not due to hook ids:

    $ file .pre-commit-config.yaml
    .pre-commit-config.yaml: ASCII text

But I still have a similar encoding error:

    Run JUnit tests in mvn-test...............................................An unexpected error has occurred: UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 330146: invalid start byte

I use the following hook definition:
```
- repo: local
  hooks:
  - id: mvn-test
    name: Run JUnit tests in my-java-project
    language: system
    entry: sh -c 'cd my-java-project && mvn test -Drun-integ-tests=true'
    files: ^my-java-project
```

**Comment by asottile** [comment]
@Lucas-C Could you open a new ticket for this?  I imagine the work I'm doing for this issue wrt output will actually resolve that issue as well, but it's hard to say.  Could you also attach the following (if possible):

`~/.pre-commit/pre-commit.log`
The output of `sh -c 'cd my-java-project && mvn test -Drun-integ-tests=true'`

It'd greatly help me reproducing this error. I imagine the cause is mvn outputting some non-utf-8 character in the output stream.
