### ISSUE TITLE
Feature/all-files per hook

### ISSUE THREAD

**Issue by Niccolum** [pre-commit/pre-commit#2070]
I, as a developer, want to run some hooks every commit and pass files not only from commits file. For example - check for security issues (safety) in dependencies not only when I change requirements, update dependencies (pip-compile-multi) not only when I change my requirements.

I want something like `run --all-files`, but per hook inside hook settings like `always_run: true`, but with needed files.

**Comment by asottile** [comment]
this has been proposed before (there's a rejected duplicate somewhere) and there isn't a valid use case -- that would be slow for no reason

**Comment by Niccolum** [comment]
Why my two use cases are not valid?

**Comment by Niccolum** [comment]
If it can be slow to scan - i can set file/files strict inside hook. Why not.
