### ISSUE TITLE
"run --files" should normalize paths to repository root before matching with "files" or "exclude"

### ISSUE THREAD

**Issue by wavexx** [pre-commit/pre-commit#2072]
### describe your issue

Let's assume you want to exclude a directory from a hook. Using the: ``exclude: ^dir/`` rule seems like the obvious choice, but it can fail to work if calling pre-commit interactively:

```
cd subdir
pre-commit run --files ../dir/file.cpp
```

This is because the path is not canonicalized in respect to the repository root before matching. I consider this behavior to be broken.

- If I'm able to use ``pre-commit run`` anywhere within a git repository, I expect no differences in behavior according the CWD.
- Without canonicalization we cannot build robust rules that match the path prefix in any way.

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
-
```

### ~/.cache/pre-commit/pre-commit.log (if present)

-

**Comment by asottile** [comment]
cannot reproduce -- they are normalized first -- please fill out the issue template next time
