### ISSUE TITLE
Strange behavior with modified config file

### ISSUE THREAD

**Issue by a666** [pre-commit/pre-commit#2080]
### describe your issue

In one of our new python projects we are evaluating pre-commit, unfortunately this strange behavior happens.

In a new project add and commit a `.pre-commit-config.yaml`

```shell
git init
pre-commit sample-config > .pre-commit-config.yaml
pre-commit install
git add .pre-commit-config.yaml
git commit -m 'Test'
```

Now modify your `.pre-commit-config.yaml` (just add anything, like `check-toml`)
```shell
$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .pre-commit-config.yaml
```

Now try to add a new file and commit it.
```shell
touch manage.py
git add manage.py
git status
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   manage.py

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .pre-commit-config.yaml

$ git commit
[ERROR] Your pre-commit configuration is unstaged.
`git add .pre-commit-config.yaml` to fix this.

$ git commit manage.py
[ERROR] Your pre-commit configuration is unstaged.
`git add .pre-commit-config.yaml` to fix this.
```

Well, I'm not sure why that is required but ok. We `git add the .pre-commit-config.yaml`.

```shell
git add .pre-commit-config.yaml
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .pre-commit-config.yaml
        new file:   manage.py
```

But then doing a commit with files is blocked too.

```shell
$ git commit manage.py
[ERROR] Your pre-commit configuration is unstaged.
`git add .pre-commit-config.yaml` to fix this. # this message is wrong, the file is staged
```

But commit with all staged files are not.

```shell
$ git commit  # NOTE, this is not what we want, it would result in a commit with two modified files
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check Toml...........................................(no files to check)Skipped
Check for added large files..............................................Passed
```

If the behavior is wanted (i.e. if `.pre-commit-config.yaml` is modified you MUST commit it before doing anything) probably the error message should be modified to say so.

But perhaps this behavior could be relaxed if doing a commit with files (like `git commit manage.py`)?

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
```

**Comment by asottile** [comment]
`git commit manage.py` doesn't commit the `.pre-commit-config.yaml` -- it temporarily unstages the changes which is why you see the error message

the pre-commit configuration is required to be in a not-partially-staged state because it was confusing users when pre-commit would discard the changes to it

the output you show above seems correct to me (the behaviour I expect at least)

for example, if you stick a `__import__('subprocess').call(('git', 'status'))` into `.git/hooks/pre-commit` at the top, this is what pre-commit sees:

```console
$ git commit manage.py 
On branch master
Changes to be committed:
	new file:   manage.py

Changes not staged for commit:
	modified:   .pre-commit-config.yaml

[ERROR] Your pre-commit configuration is unstaged.
`git add .pre-commit-config.yaml` to fix this.

```

**Comment by asottile** [comment]
the unfortunate thing is `pre-commit` can't actually differentiate the two cases because `git` hides that away from us :(
