### ISSUE TITLE
Add support for PHP hooks

### ISSUE THREAD

**Issue by struys** [pre-commit/pre-commit#209]
hootsuite is already using pre-commit with PHP hooks but they're using PHP from the system level (https://github.com/hootsuite/pre-commit-php). We should add support for PHP in pre-commit.

**Comment by struys** [comment]
We need a system similar to pip for pear packages or whatever is most common in PHP. I don't know enough about it to say how we should be doing it.

It should look something like what we have for python/node/ruby, for example - https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py

**Comment by asottile** [comment]
I looked a bit at these two projects: https://github.com/phpenv/phpenv and https://github.com/CHH/phpenv

They both seem kind of deadish unfortunately (the first has a completely dead `dev` branch, and a partially (?) working master branch).   They both seem like I could use a similar approach to our ruby support to get a virtualenv-like thing working

**Comment by struys** [comment]
@shihoonhootsuite have any experience with these?

**Comment by asottile** [comment]
This seems more promising: https://github.com/virtphp/virtphp

**Comment by shihoonhootsuite** [comment]
Thanks for this feature suggestion! Sorry I haven't had much experience with running these local php envs - it has been still a relative new thing in PHP. But the last link from @asottile at https://github.com/virtphp/virtphp does look promising. I assume the aim of doing this is so that users can write hooks in PHP right?

**Comment by asottile** [comment]
Indeed, that's the goal :)

**Comment by awebdeveloper** [comment]
would  composer help

https://getcomposer.org/

**Comment by asottile** [comment]
This was initially looked into in #458 but it was decided it was too fragile and difficult to support properly.

The suggested route for php-based hooks is to use the new (in 0.10.0 docker support).  http://pre-commit.com/#supported-languages talks about how to approach implementing hooks using docker.
