### ISSUE TITLE
Hardcoded path makes Python upgrades on Windows difficult

### ISSUE THREAD

**Issue by Vynce** [pre-commit/pre-commit#2092]
### describe your issue

`pre-commit install` writes `sys.executable` to the hook scripts: https://github.com/pre-commit/pre-commit/blob/v2.12.1/pre_commit/commands/install_uninstall.py#L103

That works well on Linux:
```python
# start templated
INSTALL_PYTHON='/usr/bin/python3'
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=commit-msg', '--skip-on-missing-config']
# end templated
```
but causes problems on Windows because different versions of Python get installed in different folders.
```python
# start templated
INSTALL_PYTHON = 'C:\\Python36\\python.exe'
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=commit-msg', '--skip-on-missing-config']
# end templated
```

If we install Python 3.8 in `C:\Python38` and keep Python 3.6 around for a while, projects will continue using the 3.6 version of pre-commit.

If the hardcoded Python executable doesn't exist, it'll fall back to finding the `pre-commit` binary in the `$PATH`, which would work if we were to uninstall Python 3.6, but still not idea.
https://github.com/pre-commit/pre-commit/blob/v2.12.1/pre_commit/resources/hook-tmpl#L28

I see that you recently refactored the hook template: https://github.com/pre-commit/pre-commit/commit/e622f793c3de2276d6975358c7e35e9b890fbdfd. I haven't tried that version yet, but it looks like it'll have the same issue.

What do you think about providing an install argument to override `INSTALL_PYTHON` so we could just set it to `python` instead of an absolute path? Or could you just set `INSTALL_PYTHON=python` on Windows and `INSTALL_PYTHON=python3` on Linux (unfortunately, the Python installer for Windows only provides `python.exe`, not `python3.exe` or `python3.8.exe`). Any other ideas?

### pre-commit --version

pre-commit 2.12.1

### .pre-commit-config.yaml

```yaml
N/A
```

**Comment by asottile** [comment]
the point of `INSTALL_PYTHON` is to make a best effort to recover the original executable which `pre-commit install` was run with, you can always rerun `pre-commit install` to update it
