### ISSUE TITLE
Ref range parameters pass incorrect argument to git

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [pre-commit/pre-commit#2116]
### describe your issue

**I ran:**

pre-commit run --from-ref origin/HEAD --to-ref HEAD

**I expected:**

pre-commit to execute on files that changed since the branch was created

**I received:**

Git error:

> An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'diff', '--name-only', '--no-ext-diff', '-z', 'origin/HEAD..HEAD')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: **ambiguous argument 'origin/HEAD..HEAD'**: unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

**Comments**

It seems that the following command line was executed:

git diff --name-only --no-ext-diff -z 'origin/HEAD..HEAD'

While the correct command line would be (note the absence of single quotes around ref range):

git diff --name-only --no-ext-diff -z origin/HEAD..HEAD

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

_Irrelevant to replicating the issue_

**Comment by asottile** [comment]
please fill out the issue template correctly
