### ISSUE TITLE
Question: Why did you go for YAML?

### ISSUE THREAD

**Issue by Greedquest** [pre-commit/pre-commit#2121]
Hi, bit random question if you have a moment. I'm building a package manager written in python but for another language. I'm deciding on a file format for specifying a project's references and dependencies and it's a similar thing to what pre-commit does; where on client side you have an environment config file to specify what to download, and on the vendor side you have a package config file to specify what to supply and what dependencies are required (as well as name, description, build options etc. - although I'm keeping it very simple for now).

Anyway I had a look at [pep-0518](https://www.python.org/dev/peps/pep-0518/#other-file-formats) for pyproj.toml as well as this discussion on [TOML vs YAML vs StrictYAML](https://stackoverflow.com/q/65283208/6609896) and from what I understand the key benefit of YAML over TOML is that it can have cyclic references and therefore express much more complex objects whereas TOML is limited to tables and arrays (i.e. sequences and nests). Have you found a need for the more complex structures because of your multilanguage approach perhaps some tools need exotic declarations? If not then was your motivation for yaml?

**Comment by asottile** [comment]
toml / ini aren't appropriate for describing nested structures.  additionally toml didn't exist in 2014 when the tool was created and despite pre-commit being written in python it is not a python tool so `pyproject.toml` would not be an appropriate format

back then the choices were basically yaml or json

admittedly, I don't really like yaml and given a perfect universe would use something like json5 -- ideally I'd want a fast roundtrip parser -- of which there don't seem to be any in any configuration language (even yaml so we have terrible hacks for autoupdate)

I even tried [inventing my own configuration language](https://github.com/asottile/dumbconf) but never really finished it
