### ISSUE TITLE
Warn About or Forbid Duplicate IDs

### ISSUE THREAD

**Issue by Kurt-von-Laven** [pre-commit/pre-commit#2128]
No indication is given if a `.pre-commit-config.yaml` contains more than one entry with the same ID. This scenario likely indicates a user configuration error (e.g., same hook run twice or two different hooks that happen to have the same ID). In the latter scenario, the lack of uniqueness can lead to unintended consequences (e.g., when skipping hooks by ID).

**Comment by asottile** [comment]
this is intentional, duplicate ids are often useful for running different options for the same thing.  the configuration was intentionally designed as a list to enable this

**Comment by Kurt-von-Laven** [comment]
Ah, I see your point.
