### ISSUE TITLE
Does not work within submodules

### ISSUE THREAD

**Issue by quentindemetz** [pre-commit/pre-commit#213]
I'm getting: 
```
An unexpected error has occurred: NotADirectoryError: [Errno 20] Not a directory: '/home/quentin/chef-repo/cookbooks/ssmtp-cookbook/.git/hooks/pre-commit'
```
chef-repo is my primary repository and ssmtp-cookbook a git submodule of that. 

**ssmtp-cookbook/.git file contents:**
```
gitdir: ../../.git/modules/cookbooks/ssmtp-cookbook
```

**Comment by asottile** [comment]
What is your pwd?

**Comment by quentindemetz** [comment]
app-cookbook

**Comment by asottile** [comment]
Well you're not really supposed to develop inside of submodules (they aren't quite full git repos) but I guess we can support this workflow. The fix is a regression test and to mkdirp the hooks directory I'd imagine. A workaround is to manually make the hooks directory yourself.

**Comment by asottile** [comment]
Ah I think I'm wrong here,  in newer git submodules have an entirely separate git directory from the repository.  This means our trick of searching upwards for the git dope won't work.  Apparently there is `git rev-parse --git-dir` which will get us what we want maybe?

**Comment by quentindemetz** [comment]
I concur, `git rev-parse --git-dir` does yield the correct path to the git directory, including in my current submodule configuration:
```
$ git rev-parse --git-dir
/home/quentin/chef-repo/.git/modules/cookbooks/ssmtp-cookbook
```

Good find !

**Comment by quentindemetz** [comment]
(oops)

**Comment by asottile** [comment]
So I took an initial look into this, it's slightly more difficult than I initially thought since we (erroneously) depend on the git directory existing at the top level of the repository for several things (such as where to chdir right before running hooks).  Therefore this needs to be split into two concepts: git-dir and git-root.
