### ISSUE TITLE
[Question] pre-commit running pip-compile across multiple operating systems

### ISSUE THREAD

**Issue by BTOdell** [pre-commit/pre-commit#2132]
I posted this question on the pip-tools repo [here](https://github.com/jazzband/pip-tools/issues/1534), but after a week it hasn't received a response. So I'm posting this here as well for visibility:

---

I have `pre-commit` set up using GitHub Actions to run on Linux and Windows. `pre-commit` is configured to run `pip-compile`:
```
- repo: https://github.com/jazzband/pip-tools
  rev: 6.4.0
  hooks:
    - id: pip-compile
```

The pip-compile documentation suggests running `pip-compile` for each environment combination (OS+Python):
https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile
*"As the resulting `requirements.txt` can differ for each environment, users must execute `pip-compile` on each Python environment separately to generate a `requirements.txt` valid for each said environment."*

On Linux, I currently manually run `pip-compile` and output to `requirements.txt` and on Windows I have `pip-compile` output to `requirements.win.txt`.

How do I get `pip-compile` to output to the correct requirements file depending on the operating system that pre-commit runs on?

---

I want to be able to run `pre-commit run --all-files` and have it run `pip-compile` with the correct output file depending on the operating system (Windows vs Linux).

**Comment by asottile** [comment]
sorry we do not provide support for behaviours for specific tools -- the pip-tools tracker was the correct place to ask
