### ISSUE TITLE
[NEW FEATURE] python-local-venv language to run hooks in the same venv as pre-commit is running

### ISSUE THREAD

**Issue by KRunchPL** [pre-commit/pre-commit#2133]
If you would have actually read my comment in other issue you would know that I agree with you that the `system` language should NOT be changed and I have proposed different solution for the issue a lot of your users encounter (based on multiple issues reported) and that you have tried to solve with `system` language (based on documentation).

Please read carefully what I have wrote (especially the solution proposal).

I feel that it is a strange move on your side to have multiple issues regarding the same thing. My comment was not off-topic to the previous issue, but it was a proposal of solution (that was taking all your comments into consideration) for the issue original reporter had with just more details and explanation.

### Problem

It relates to Python virtualenvs, especially when the user does not fully control whether the virtualenv is activated when running `git commit` command. It can happen when the command is being run by some other tool.  For example VS Code SCM is running git commands as [its own subprocess](https://github.com/microsoft/vscode/blob/6fc33324aff616a2be2b5b2658ca4100927538b0/extensions/git/src/git.ts#L524) which usually does not have venv activated (the venv is activated by extension in integrated terminal).

Currently hooks can be run either in `pre-commit` managed virtual environment or in environment provided by system, but they cannot be run in user defined virtualenv (even though `pre-commit` application is being run in venv choosen by user, because of [this line](https://github.com/pre-commit/pre-commit/blob/cb40e9682e2a941644347e3bea620875c8ed0ad5/pre_commit/commands/install_uninstall.py#L111)). It causes local hooks to fail if they depend on whole project environment.

### Reproduction

```
## Pre-test configuration
# create new poetry project
poetry new temp_repo; cd temp_repo
# initialize its git repository
git init
# add flake8 as dependency
poetry add -D flake8
# commit what you have
git add .; git commit -m "initial commit"

## Test steps
# (step 1) add pre-commit as developer dependency and install it to venv
poetry add -D pre-commit
# (step 2) create got hooks
poetry run pre-commit install
# (step 3) configure the hook
# The example is simplified and runs flake8, but is actually important when running things that requires
# all project dependencies, which as documentation states is one of the reasons to use local hooks with system language
Set-Content .\.pre-commit-config.yaml -Value "repos: `
-   repo: https://github.com/pre-commit/pre-commit-hooks `
    rev: v4.0.1 `
    hooks: `
    -   id: trailing-whitespace  `
-   repo: local `
    hooks: `
    -   id: flake8 `
        name: flake8 `
        entry: python -mflake8 `
        language: system `
        types: [python] `
        require_serial: true `
"
# (step 4) introduce flake error to the code
Set-Content .\temp_repo\__init__.py -Value "__version__='0.1.0'"
# (step 5) stage the changes
git add .
# (step 6) commit changes
git commit
```

### Result description

The `git commit` (step 6) runs `pre-commit` application properly, using project virtualenv, but the local hook itself fails, because of non-existing module. Non-local hooks, are running properly.

### Cause

The `.git/hooks/pre-commit` script runs the `pre-commit` application in hardcoded python virtualenv (which is great), but the application itself is executing `system` hooks outside of it, in global environment. This behavior is expected for `system` language, but does not fulfill Python needs.

### Additional explanation

I understand that the question is "Why the hell are you running commands outside of virtualenv if you need it?". As described above, the answer is that it happens, because a lot of tools is doing it for me. For example VS Code SCM is running git commands as [its own subprocess](https://github.com/microsoft/vscode/blob/6fc33324aff616a2be2b5b2658ca4100927538b0/extensions/git/src/git.ts#L524) which usually does not have venv activated (the venv is activated by extension in integrated terminal). Git is having a lot of GUIs that are running command for the user and they are not run in specific venv, especially that they support multiple repos at the same time.

### Proposed solution

We can implement another language called for example `python-local-venv` that would behave like system environment, but would prepend the PATH env var with the absolute path to a folder holding python interpreter that is executing `pre-commit` code.

```
os.environ['PATH'] = os.path.dirname(sys.executable) + os.pathsep + os.getenv('PATH', '')
```

Of course we need to consider reverting the change made to PATH env var after the hook finishes.

This will cause hooks using this language to run in the same venv that `pre-commit` is installed, which is the development environment for a lot of projects (I would even wonder if not majority of projects, but am not sure about it).

The `system` language is great, but when it comes to Python, the code is hardly ever run in system environment, but usually some development venv that `pre-commit` code is also run in.

### Workarounds

I know that a lot of people encountered the issue

Those workarounds can be applied locally, but are not good solutions to the problem, so should NOT be introduced to the package code.

[See here](https://github.com/pre-commit/pre-commit/issues/1465#issuecomment-974629717) for some workarounds.

The other way is to use some venv managers. If you have poetry installed globally, you can have a hook with entry `poetry run flake8`.

**Comment by asottile** [comment]
pre-commit is not going to manage environments outside of its environment directory -- as stated many times in the tracker

so this will not be implemented

cache invalidation of such environments is intractable

**Comment by KRunchPL** [comment]
I fully understand and agree. I have never suggested that pre-commit should manage this environment. But you state in the [documentation](https://pre-commit.com/#repository-local-hooks) yourself, that there are some hooks that you just cannot manage the environment for and that is one of the reasons that `system` language is introduced.

> Repository-local hooks are useful when: Hooks require state that is only present in a built artifact of your repository (such as your app's virtualenv for pylint).

But the `system` language is not good enough for Python environments in some situations. That is why I suggest that genre of `system` language that would be a little bit better crafted for Python itself. It would be unmanaged environment, the same as in `system` language, but the user will say "use the same venv that I am running pre-commit in, instead of the one git command execution environment provides".

Would you at least consider looking at implemented solution and merging it (because I will probably implement it either way in my fork) or should I not bother you with the PR?

**Comment by asottile** [comment]
please do not bother with a PR

you can always use `entry: venv/bin/whatever` if you don't want to depend on being "activated"

**Comment by KRunchPL** [comment]
This is not the solution, because would require all the developers to keep the venv in the same place, or create some symlinks, because the hook declaration is common for all developers (as it is kept on the repo), but the `pre-commit` git hook script is usually different for each of the developers (the script `pre-commit` provide is having the path we are looking for).

**Comment by asottile** [comment]
ok
