### ISSUE TITLE
pre-commit.ci — run manual tasks?

### ISSUE THREAD

**Issue by max-sixty** [pre-commit/pre-commit#2140]
### describe your issue

I'm not sure whether this is the correct place for this — please feel free to close if not.

We're recent users of pre-commit.ci — it's really good — thank you!

We're considering moving one of our tasks to a `manual` stage, because it's fairly slow (https://github.com/pydata/xarray/pull/6024). Is there a way of running that task in pre-commit.ci?

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
https://github.com/pydata/xarray/blob/f82140ea8db7d8c1b03d631491dac7586af76fb1/.pre-commit-config.yaml
```

**Comment by asottile** [comment]
there isn't -- pre-commit.ci runs things which interesect with `stages: [pre-commit]` -- `manual` is more designed for things which aren't meant to be run automatically

**Comment by max-sixty** [comment]
That makes sense. Let me know if we're missing anything re dealing with slower tests — i.e. 5 seconds is a long time on the commit path — but we really like the encapsulation of pre-commit. 

Feel free to close this one.

**Comment by asottile** [comment]
indeed -- the current recommended approach is to utilize [SKIP=](https://pre-commit.com/#temporarily-disabling-hooks)

**Comment by max-sixty** [comment]
> indeed -- the current recommended approach is to utilize [SKIP=](https://pre-commit.com/#temporarily-disabling-hooks)

Right — though tbc, we want the default behavior to skip — rather than the exception. Thanks all the same
