### ISSUE TITLE
InvalidManifestError .pre-commit-hooks.yaml is not a file

### ISSUE THREAD

**Issue by Animatea** [pre-commit/pre-commit#2141]
### describe your issue

I'm trying to run a pre-commit run, but nothing happens because of this error, I can't figure out what the problem is. 

![Screenshot_23](https://user-images.githubusercontent.com/70884964/143732000-5fc46c6e-a657-4b98-ba6e-308b0bb39ed3.png)

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        log_file: logs/pre-commit.log

    -   id: end-of-file-fixer
        log_file: logs/pre-commit.log

    -   id: trailing-whitespace
        log_file: logs/pre-commit.log

    -  id: check-json
       log_file: logs/pre-commit.log

-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
        log_file: logs/pre-commit.log
        args: [--include=\.pyi?$, --verbose, --line-length=110, --target-version=py39]

-   repo: https://github.com/Animatea/AnimateaBot
    rev: 1.0.0
    hooks:
    -    id: run_coverage
         include: run_coverage.py
         always_run: true
         args: [python, -m, src, coverage]
```

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\den25\AppData\Local\Programs\Python\Python310\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

```
Traceback (most recent call last):
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\main.py", line 396, in main
    return run(args.config, store, args)
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\run.py", line 401, in run
    config = load_config(config_file)
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 394, in load_from_filename
    with reraise_as(exc_tp):
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

**Comment by asottile** [comment]
you've added `https://github.com/Animatea/AnimateaBot` as a hook repo, but it does not provide (`.pre-commit-hooks.yaml`) any hooks

**Comment by Animatea** [comment]
> you've added `https://github.com/Animatea/AnimateaBot` as a hook repo, but it does not provide (`.pre-commit-hooks.yaml`) any hooks

got it, thanks. How can I run a single file using a hook? I thought it would work this way

**Comment by asottile** [comment]
you're probably looking for [`repo: local`](https://pre-commit.com/#repository-local-hooks) hooks but I have no idea because you haven't explained what you're trying to do -- maybe take a watch of [this](https://youtu.be/ritp4gAqNMI)

**Comment by apidwalinsubport** [comment]
> ### describe your issue
> I'm trying to run a pre-commit run, but nothing happens because of this error, I can't figure out what the problem is.
> 
> ![Screenshot_23](https://user-images.githubusercontent.com/70884964/143732000-5fc46c6e-a657-4b98-ba6e-308b0bb39ed3.png)
> 
> ### pre-commit --version
> pre-commit 2.15.0
> 
> ### .pre-commit-config.yaml
> ```yaml
> default_language_version:
>     python: python3.10
> 
> repos:
> -   repo: https://github.com/pre-commit/pre-commit-hooks
>     rev: v4.0.1
>     hooks:
>     -   id: check-yaml
>         log_file: logs/pre-commit.log
> 
>     -   id: end-of-file-fixer
>         log_file: logs/pre-commit.log
> 
>     -   id: trailing-whitespace
>         log_file: logs/pre-commit.log
> 
>     -  id: check-json
>        log_file: logs/pre-commit.log
> 
> -   repo: https://github.com/psf/black
>     rev: 21.11b1
>     hooks:
>     -   id: black
>         log_file: logs/pre-commit.log
>         args: [--include=\.pyi?$, --verbose, --line-length=110, --target-version=py39]
> 
> -   repo: https://github.com/Animatea/AnimateaBot
>     rev: 1.0.0
>     hooks:
>     -    id: run_coverage
>          include: run_coverage.py
>          always_run: true
>          args: [python, -m, src, coverage]
> ```
> 
> ### ~/.cache/pre-commit/pre-commit.log (if present)
> ### version information
> ```
> pre-commit version: 2.15.0
> sys.version:
>     3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
> sys.executable: C:\Users\den25\AppData\Local\Programs\Python\Python310\python.exe
> os.name: nt
> sys.platform: win32
> ```
> 
> ### error information
> ```
> An error has occurred: InvalidConfigError: 
> =====> .pre-commit-config.yaml is not a file
> ```
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
>     yield
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\main.py", line 396, in main
>     return run(args.config, store, args)
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\run.py", line 401, in run
>     config = load_config(config_file)
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 394, in load_from_filename
>     with reraise_as(exc_tp):
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 43, in reraise_as
>     raise tp(e).with_traceback(tb) from None
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 40, in reraise_as
>     yield
>   File "C:\Users\den25\AppData\Local\Programs\Python\Python310\lib\site-packages\cfgv.py", line 396, in load_from_filename
>     raise ValidationError(f'{filename} is not a file')
> pre_commit.clientlib.InvalidConfigError: 
> =====> .pre-commit-config.yaml is not a file
> ```
