### ISSUE TITLE
[Feature Request] : Allow to mark (tag) actions and execute them selectively according to their markers (tags).

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [pre-commit/pre-commit#2143]
Hi!

The (custom) _markers (tags)_ would allow defining _"which"_ (groups of) actions to execute.
Just as the _stages_ allow to define _"when/where"_ the actions are executed (in relation to `git`)

I personally prefer to separate some actions in different categories or according to certain modalities.

- Examples:

    - `[check]`:  actions that check things.
    
    - `[fix]`: actions that modify things (and that could break things)

    - `[stable]`: less likely to break things - more stable or robust actions - such as some formatters.
     
    - `[experimental]`: more likely to break things - less stable, less robust or a bit more experimental actions - such as some autofixers.
    
    - `[strict]`: more restrictive modalities or configurations, like some linters, type checkers or tools that remove things. 

- Example:

```bash
pre-commit run --all-files --markers=strict,stable,check
```

Thanks!
.

**Comment by asottile** [comment]
I don't really think this complexity is worth it -- you can already do `pre-commit run $hookid --all-files` and write scripts which compose those

this also wouldn't be useful for hook execution either where you'd want to run everything anyway

**Comment by diegovalenzuelaiturra** [comment]
Oh, I see ...

- Do you think it would be useful to enable (or disable) certain hooks under different contexts? 
    (without having to maintain different scripts or configuration files)

Thanks!

**Comment by asottile** [comment]
I don't think so, separate configuration files are already supported and accomplish that as well as the `manual` stage

I'd rather not maintain multiple ways to accomplish the same thing

**Comment by diegovalenzuelaiturra** [comment]
Ok, I understand ...

One last question (I'm not totally sure if this is a way to accomplish the same thing)

- Do you think it would be useful to allow overwriting and/or extending configuration files?
    I think this can avoid duplication of configurations, in cases where multiple configurations are already being used.

Currently, tools such as `docker-compose` [^docker-compose-extends] [^docker-compose-cli] or `hydra-core` [^hydra-core] (through `omegaconf` [^omegaconf]) allow defining base configuration files (also allowing the use of _variable interpolation_ [^omegaconf-variable-interpolation])

- which can be overwritten or extended by additional configuration files
- or populated for example using environment variables or other
- and whose values can be overwritten by arguments provided through the command line 

Thanks!

[^docker-compose-extends]:  https://docs.docker.com/compose/extends/
[^docker-compose-cli]: https://docs.docker.com/compose/reference/
[^hydra-core]: https://hydra.cc/
[^omegaconf]: https://omegaconf.readthedocs.io
[^omegaconf-variable-interpolation]: https://omegaconf.readthedocs.io/en/latest/usage.html#variable-interpolation

**Comment by asottile** [comment]
I am intentionally not implementing that because extension is a hard problem that you really don't need and makes caching difficult / intractable

there are many other issues which mention this

I am well aware of other tools which do this and it does not improve the argument
