### ISSUE TITLE
Question: how to handle partial commits?

### ISSUE THREAD

**Issue by jenstroeger** [pre-commit/pre-commit#2147]
So, I’m a little befuddled at the moment because I’m trying to understand what exactly is going on with pre-commit.

In my playground repo I’ve added Python [type stubs](https://mypy.readthedocs.io/en/stable/stubs.html) and these new `.pyi` files are staged together with the occasional related `.py` file. I also have pre-commit hooks for `pylint` and `mypy` configured.

When I run `git commit` then the hooks run on the _staged_ files, in which case `pylint` flags two files with
```
src/orm/meta.py:1:0: R0801: Similar lines in 2 files
==orm.meta:[6:72]
==orm.meta:[6:72]
```
which are the two that have both `.py` and `.pyi` staged! And `mypy` flags
```
src/orm/meta.py: error: Duplicate module named "orm.meta" (also at "src/orm/meta.pyi")
```
which is one of the these two. That same behavior is reproducible when I run `pre-commit run`.

However, when I run `pre-commit run --all-files` (i.e. not only staged files) then the `pylint` error disappears and the `mypy` error changes to a different file (same complaint, though) which has _only_ the `.pyi` file staged.

Finally, when I run `pylint` and `mypy` manually, none of the issues are flagged and the code is clean. In that case I think (🤞🏼) I have used the same command-line args but I realize that the context environment is different compared to running pre-commit (which runs [hooks in their own environment](https://pre-commit.com/#pre-commit-install-hooks)).

What’s the recommended way forward, here:
 - `git --no-verify commit` feels a bit naughty and I worry that subsequent commits may break because this one wasn’t actually clean; or
 - `SKIP=mypy,pylint git commit` and [temporarily disabling](https://pre-commit.com/#temporarily-disabling-hooks) also feels hackish but given the staged files may be the correct way of going about this?

**Comment by asottile** [comment]
don't skip the issue template, it's there for a reason

**Comment by jenstroeger** [comment]
@asottile are you asking me to ask this question using the issue template?

**Comment by jenstroeger** [comment]
Opened a new issue https://github.com/pre-commit/pre-commit/issues/2148.
