### ISSUE TITLE
pre-commit run allow multiple hook ids as positional args

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2149]
What's the reason `pre-commit run` only allows specifying a single hook at a time?

```sh
$ pre-commit run check-case-conflict check-symlinks -a
pre-commit: error: unrecognized arguments: check-symlinks
```

**Comment by asottile** [comment]
because:
- it's ambiguous when used with `--files`
- you can just as easily use `&&`
- it's not intended to be used beyond simple debugging locally

**Comment by janosh** [comment]
> it's ambiguous when used with `--files`

Can you explain? Expected behavior would be `--files` are passed to all hooks?

**Comment by asottile** [comment]
run foo --files bar baz

which of those are hook IDs and which are files

**Comment by janosh** [comment]
Everything following `--files` are files of course...
