### ISSUE TITLE
Please consider renaming this project to avoid confusion with pre-commit (the hook)

### ISSUE THREAD

**Issue by DanielPower** [pre-commit/pre-commit#2155]
### describe your issue

My company is in the process of transitioning from an in-house githook management system to pre-commit (the tool, not the hook). And because of the name of this tool, I have to preface every single message on the topic with a blurb about how the tool is not the same as the the hook, but the tool supports the hook, but also other hooks. I then have to re-iterate this multiple times throughout the message to indicate whether I'm referring to the tool or the hook any time I mention the words `pre-commit`.

It would be a little more understandable if the project still only supported pre-commit (the hook), but it now supports other hooks as well. As-is, the name of this project makes communication around the topic a mess.

### pre-commit --version

All

### .pre-commit-config.yaml

```yaml
Irrelevant
```

**Comment by asottile** [comment]
considered and no
