### ISSUE TITLE
Question: Migration from lint-staged

### ISSUE THREAD

**Issue by anishmittal2020** [pre-commit/pre-commit#2157]
Since, lint-staged do not support ignoring files since v8. I want to migrate to `pre-commit`. I have following config file for lint-staged (v8)

```json
{
  "linters": {
    "*.md": [
      "cross-env qPreProcess=\"/home/nikhil/opt/bin/qPreProcess\" qPreProcess",
      "git add"
    ],
    "*.{yaml,yml}": [
      "prettier --write",
      "git add"
    ],
    "*.{js,json}": [
      "prettier --write",
      "git add"
    ]
  },
  "ignore": [
    "README.md",
    "CHANGELOG.md"
  ]
}
```

Can anybody suggest if I can do the above intended task with pre-commit? Basically, In want to run particular tools for files with particular extension and I want to ignore certain paths.

**Comment by asottile** [comment]
yes, all of that is possible with pre-commit -- for more on ignoring files check out [the documentation]{https://pre-commit.com)
