### ISSUE TITLE
`pre-commit` disregards `--git-dir` flag

### ISSUE THREAD

**Issue by uriva** [pre-commit/pre-commit#2168]
### describe your issue

I'm using a script to run some commands for a certain repo, when the working directory is something else. This is using the `--git-dir` flag. When I'm using this script on a repo with pre-commit hook, I get:

> "No .pre-commit-config.yaml file was found".

I think pre-commit ignores that flag.

### pre-commit --version

pre-commit --version

### .pre-commit-config.yaml

```yaml
Irrelevant
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Irrelevant

**Comment by asottile** [comment]
I can't reproduce

please actually fill out the issue template and make sure to include the full commands and outputs

**Comment by uriva** [comment]
I think I might have the wrong flag, trying with `git -C` and will reopen if needed. Thanks!

**Comment by asottile** [comment]
@uriva in the future do not skip the template. it would have been obvious what was wrong if you had supplied sufficient information
