### ISSUE TITLE
How I can know the pre-commit arguments inside a hook

### ISSUE THREAD

**Issue by carlosbustillordguez** [pre-commit/pre-commit#2172]
I am looking for a way to get the provided arguments to the `pre-commit run | try-repo`, mainly if the `--all | -a` was provided as an argument.

That could be good because, in our hook, we need to check for that option to improve the performance during some tests and take some required actions.

**Comment by asottile** [comment]
there isn't a way to do that, somewhat intentionally -- the hook shouldn't care about how it is called, just that it receives a list of filenames

for example, `pre-commit run --all-files` is basically just a shortcut for `pre-commit run --files $(git ls-files)` and even with that your hook executable may be called multiple times with a subsequence of the file list.
