### ISSUE TITLE
ci: PR description not updated when a PR is updated

### ISSUE THREAD

**Issue by WhyNotHugo** [pre-commit/pre-commit#2176]
### describe your issue

When an auto-update PR is updated after a week, its description is not updated to reflect the new changes.

See https://github.com/jazzband/django-payments/pull/284 as an example

Do let me know if this should actually be reported elsewhere.

### pre-commit --version

ci

### .pre-commit-config.yaml

```yaml
n/a
```

### ~/.cache/pre-commit/pre-commit.log (if present)

n/a

**Comment by asottile** [comment]
from the template:

> this is for issues for `pre-commit` (the framework).
> if you are reporting an issue for [pre-commit.ci] please report it at [pre-commit-ci/issues]
>
> [pre-commit.ci]: https://pre-commit.ci
> [pre-commit-ci/issues]: https://github.com/pre-commit-ci/issues

the duplicate issue is here: https://github.com/pre-commit-ci/issues/issues/78

**Comment by WhyNotHugo** [comment]
:facepalm:
