### ISSUE TITLE
Inspecting the index using GitPython

### ISSUE THREAD

**Issue by robin-moss** [pre-commit/pre-commit#2184]
### describe your issue

I am trying to write a new hook that checks that a `.meta` file exists for every file under the Assets folder (Unity specific check), I have working code that uses `GitPython==3.1.24` to inspect the Git index. When I run this code directly it works as expected, however when I run it via pre-commit (as a hook or try repo) the `index` check fails (`meta_file_in_index`).

It looks like although it's finding the correct git repo, the index is empty, I've tried several things to figure out what is happening but I've not had any luck. Any advice would be apprecaited

Hook Code

```python
import os
import sys

from git import Repo, IndexFile, DiffIndex


def filter_assets(path: str):
    lower_case = path.lower()
    return lower_case.startswith("assets")


def path_to_meta_file(path: str):
    return path + ".meta"

def meta_file_exists(meta_file: str):
    return os.path.isfile(meta_file)

def meta_file_in_index(meta_file: str, index: IndexFile):
    return any(x for x in index.entries.keys() if x[0] == meta_file)

def meta_file_in_diff(meta_file: str, diff: DiffIndex):
    return any(x for x in diff if x.a_path == meta_file)


def run():
    files = [path for path in sys.argv[1:] if filter_assets(path)]
    repo = Repo(os.getcwd())
    index = repo.index
    modified = index.diff(None)
    errors = []
    for file in files:
        meta_file = path_to_meta_file(file)
        if not meta_file_exists(meta_file):
            errors.append(f"{file} does not have a matching meta file {meta_file}")
            continue

        if not meta_file_in_index(meta_file, index):
            errors.append(f"{meta_file} is not in the git index")
            continue

        if meta_file_in_diff(meta_file, modified):
            errors.append(f"{meta_file} has been changed but is not staged")

    if len(errors) > 0:
        print("At least one file has an issue with it's meta file:")
        print("  * " + "\n  * ".join(errors))
        sys.exit(1)


if __name__ == "__main__":
    run()
```

### pre-commit --version

pre-commit 2.13.0

### .pre-commit-config.yaml

```yaml
---
- id: meta_check
  name: Check meta files are in the Git index
  entry: meta_check
  exclude: ".meta$"
  language: python
```

**Comment by robin-moss** [comment]
The project is built using poetry and has a scripts entry point called `meta_check` that calls directly into `run`, I'm testing it locally using `try-repo`

`pre-commit try-repo /path/to/unity-pre-commit meta_check --verbose --all-files`

**Comment by asottile** [comment]
this doesn't look like a framework issue but some trouble you're running into with gitpython or your own code -- maybe try their tracker instead for assistance?

**Comment by robin-moss** [comment]
thanks. I did wonder if the framework was doing something to the current state of git that I was not aware of. I know it can stash changes but not sure what else it does

**Comment by robin-moss** [comment]
@asottile to help me understand this, could you let me know if pre-commit does anything to git beyond stashing the changes?

**Comment by asottile** [comment]
nothing, it should be identical to you running `yourthing filename filename filename` -- in fact you could stick that in `.git/hooks/pre-commit` if you want to be in exactly the same state as git would call you

**Comment by asottile** [comment]
`--all-files` also doesn't even stash

**Comment by guykisel** [comment]
oh i would be really interested in an "official" or at least pre-commit-friendly set of unity hooks. i currently have a custom hook (also using GitPython) for this same exact purpose but it would be nice to have something public and shareable for collaboration. i have seen a few other hooks out there people have published for this, such as https://github.com/doitian/unity-git-hooks/blob/master/scripts/pre-commit but none of them are set up for easy integration with pre-commit (the tool, not the git hook, i mean)

**Comment by guykisel** [comment]
also in case it helps, there are four cases we check for currently: 

1. meta file added, but asset file is not in the git index
2. asset file added, but corresponding meta file is not in the git index
3. meta file is staged to be removed, but the corresponding asset file is still in the git index
4. asset file is staged to be removed, but corresponding meta file is still in the git index

**Comment by robin-moss** [comment]
@guykisel sadly this is being hosted internally at my company, a new version of GitPython has been released that fixed the issue :tada: and based on your comment I've added the 4th check too. 

The new code is below (post pylint, pydocstyle, mypy, isort, etc):
```python
"""
Unity meta file checker.

checks is the meta file exists, is in the git index and is committed, vice versa it also checks that a meta file as a
associated asset file/folder.
"""
import os
import sys
from typing import Any

from git.diff import DiffIndex
from git.index.base import IndexFile
from git.repo.base import Repo


def filter_assets(path: str) -> bool:
    """
    Check if the path an asset and not a meta file.

    :param path: Path to check.
    """
    lower_case = path.lower()
    return lower_case.startswith("assets") and not lower_case.endswith("meta")


def filter_meta(path: str) -> bool:
    """
    Check if the path to a meta file.

    :param path: Path to check.
    """
    lower_case = path.lower()
    return lower_case.startswith("assets") and lower_case.endswith("meta")


def path_to_meta_file(path: str) -> str:
    """
    Covert the given asset path to a meta file path.

    :param path: Path to change.
    """
    return path + ".meta"


def meta_file_exists(meta_file: str) -> bool:
    """
    Check the meta file exist on the filesystem.

    :param meta_file: Meta file to check for.
    """
    return os.path.isfile(meta_file)


def meta_file_in_index(meta_file: str, index: IndexFile) -> bool:
    """
    Is the meta file in the Git index.

    :param meta_file: Meta file to check for.
    :param index: Git index to check.
    """
    return any(x for x in index.entries.keys() if x[0] == meta_file)


def meta_file_in_diff(meta_file: str, diff: DiffIndex[Any]) -> bool:
    """
    Check if there has been an un committed change to the meta file.

    :param meta_file: Meta file to check for.
    :param diff: Git diff to check.
    """
    return any(x for x in diff if x.a_path == meta_file)


def file_or_folder_exists(path: str) -> bool:
    """
    Check a file or folder exist at the given path.

    :param path: Path to check.
    """
    return os.path.exists(path)


def run() -> None:
    """Run the Unity meta check."""
    asset_files = [path for path in sys.argv[1:] if filter_assets(path)]
    meta_files = [path for path in sys.argv[1:] if filter_meta(path)]
    repo = Repo(os.getcwd())
    index = repo.index
    modified = index.diff(None)
    errors = []
    for file in asset_files:
        meta_file = path_to_meta_file(file)
        if not meta_file_exists(meta_file):
            errors.append(f"{file} does not have a matching meta file {meta_file}")
            continue

        if not meta_file_in_index(meta_file, index):
            errors.append(f"{meta_file} is not in the git index")
            continue

        if meta_file_in_diff(meta_file, modified):
            errors.append(f"{meta_file} has been changed but is not staged")

    for file in meta_files:
        asset_file = file.removesuffix(".meta")
        if not file_or_folder_exists(asset_file):
            errors.append(f"{file} exists but no asset file exists for it")

    if len(errors) > 0:
        print("  * " + "\n  * ".join(errors))
        sys.exit(1)


if __name__ == "__main__":
    run()
```
