### ISSUE TITLE
Add ability to skip hook based on platform

### ISSUE THREAD

**Issue by aesopius** [pre-commit/pre-commit#2192]
### describe your issue

There is a number of hooks that may not work on all platforms (win/linux/macos) or produce undesirable results when not run on specific platform.

It would be very useful to be able to skip these hooks when current platform is not the expected one, something similar with how python conditional dependencies work.

While a hook writer can add the extra logic in its own hook that does not work for 3rd party hooks and sadly that is exactly why I would be awesome to add a feature like this to pre-commit itself, so we can made hooks conditional.

I am aware of manual hooks but sadly that is not sorting the issue of calling them as you would need a wrapper that decides when to add manual ones or not, basically reducing the usability considerably.

Would you accept a PR that add such a feature to pre-commit?

### pre-commit --version

main

### .pre-commit-config.yaml

```yaml
n/a
```

**Comment by asottile** [comment]
pre-commit already has a mechanism for skipping via the `SKIP` environment variable as well as `stages` to select specific hooks

in the future please fill out the issue template and have a concrete usecase
