### ISSUE TITLE
[Question] tags for run hooks

### ISSUE THREAD

**Issue by Niccolum** [pre-commit/pre-commit#2195]
Thanks for your big and very good work!

I use pre-commit with local development and run all hooks on stage `[commit]`

In near future I want to use CI, and run couple of hooks on different stage, for example:
linters, formatters, dependency-check, security-check.

Is is possible to run multiple hooks (with alias hook attribute) with one `pre-commit run` command, or, maybe, you can add "tags", for running `pre-commit run --tag linters`?

Or maybe it's possible, but I don't know how?
Thanks!

**Comment by asottile** [comment]
dupe #2143
