### ISSUE TITLE
Idea: pre-commit lockfile

### ISSUE THREAD

**Issue by gitpushdashf** [pre-commit/pre-commit#2201]
It'd be nice if pre-commit had a way to generate lockfiles with hashes of the hook sources that it's downloading. Git tags can easily be changed and put over malicious code.

This would be similar to Poetry and Pipenv lockfiles.

**Comment by asottile** [comment]
[`pre-commit autoupdate --freeze`](https://pre-commit.com/#pre-commit-autoupdate)
