### ISSUE TITLE
Allow to `mamba install` environments

### ISSUE THREAD

**Issue by janjagusch** [pre-commit/pre-commit#2204]
Thanks for maintaining pre-commit, we really enjoying working with it!

When installing conda environments, [mamba](https://github.com/mamba-org/mamba) is often the preferred option, as it is faster and [requires less memory](https://github.com/conda/conda/issues/5003) when solving an environment.

As of today, pre-commit uses conda for creating environments, as this is hard-coded into the source code:

https://github.com/pre-commit/pre-commit/blob/b944395d6638629a93756ed7279b4368473177af/pre_commit/languages/conda.py#L62-L66

We have a use case, where we want to install pre-commit hooks in CI, but the installation fails because of out-of-memory errors. Installing the same environment with mamba however, succeeds.

It would be nice if one could define whether pre-commit uses conda or mamba for installing environments. This could for example be accomplished by introducing an environment variable `PRE_COMMIT_USE_MAMBA`. If there is a better way to pass such configuration to pre-commit, please let me know.

I'd be glad to work on this feature, if this is something you'd like to see added to pre-commit.

**Comment by asottile** [comment]
if it's drop in presumably you could `ln -s $(which mamba) ~/bin/conda` or something of the sort?

**Comment by xhochy** [comment]
Thanks @janjagusch for opening this issue. I also thought already about opening one here. There are some open points why I didn't yet make one here:

- `mamba` is a 90% drop-in for the end user, you still want to disable it in some rare but regular situations.
- You cannot do `ln -s $(which mamba) ~/bin/conda` as this will also break a lot of other things, e.g. conda's shell activation which is slightly different from `mamba`'s. This might converge in the near future but has not and might never do.
- You cannot only select nowadays between `mamba` and `conda` but there is also `micromamba` available. This is a statically linked binary compatible with the `install` and `env` commands of `mamba`/`conda` but differing on some other aspects. If `mamba` is supported, one should also add support for `micromamba`.

Normally, I have implemented this via the pseudocode in other tools:

```
conda_exe = shutil.which("mamba")
if not conda_exe or os.environ.get("PRE_COMMIT_USE_MAMBA", "1") == "0":
  mamba_exe = "conda"
```

An alternative in pre-commit could also be to implement it as another language, e.g. if you want to use `mamba`, use `language: mamba`. Additionally, this also could open up the possibility to use `micromamba` as a third alternative without the need for another environment variable.

**Comment by xhochy** [comment]
After sleeping a night over this, I think we should not implement a new language as this will be confusing to the end-user. All three tools are package managers for the same distribution technique and only differ in speed and how they handle things like environment activation. There is no behavioural difference for pre-commit hooks, thus there also shouldn't be a difference in how things are configured.

I opted for the ordering of first checking for `micromamba`, then `mamba` and then a default fallback for `conda`. This is in increasing order of "popularity". If you have one of the former tools installed, you have it installed because you explicited opted for using it.

**Comment by jezdez** [comment]
If it is any consolation, the conda project has been working in the past months on porting the mamba solver to conda which should help with the most memory and cpu consuming parts of the installation. We'll do [an opt-in release in a month or so](https://github.com/conda/conda/milestone/53).

**Comment by lautjy** [comment]
Thanks for the info @jezdez !  Would be great if that solves the enormous memory consumption of conda.
For reference. 1GB AWS box runs out of MEM : https://github.com/conda/conda/issues/5003#issuecomment-747973829
