### ISSUE TITLE
end-of-file-fixer add always a new line for .gitignore files

### ISSUE THREAD

**Issue by edgarriba** [pre-commit/pre-commit#2206]
### describe your issue

After running `pre-commit` hook `end-of-file-fixer` it always add a new line for every `.gitignore` file in our private repo. Subsequently, our job checker always fails after `run --all-files` trying to fixes those files.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', '-c', 'submodule.recurse=0', 'checkout', '--', '.')
return code: 2
expected return code: 0
stdout: (none)
stderr:
    
    This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.
    
    
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/commands/run.py", line 399, in run
    exit_stack.enter_context(staged_files_only(store.directory))
  File "/usr/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/staged_files_only.py", line 98, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/staged_files_only.py", line 67, in _unstaged_changes_cleared
    cmd_output_b(*_CHECKOUT_CMD, env=no_checkout_env)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'submodule.recurse=0', 'checkout', '--', '.')
return code: 2
expected return code: 0
stdout: (none)
stderr:
    
    This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this

**Comment by asottile** [comment]
you're going to have to provide more information than that -- perhaps the byte contents of the files before and after?  maybe you're not understanding the intention of that hook?

as for the other error message -- the output seems very clear, perhaps follow what it suggests?

**Comment by edgarriba** [comment]
in my local machine the file before `'*'` / after `'*\n'`. So it seems okay, but later in the PR commit is the file appears as follows as expected.

![image](https://user-images.githubusercontent.com/5157099/149590888-c3a6f787-dc22-496b-9d00-315d6e318689.png)

However, after running `pre-commit run --all-files` in the ci, the job fails with the following error:
```bash
[INFO] This may take a few minutes...
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1

Fixing .devel_home/.gitignore

```

**Comment by asottile** [comment]
can you show the actual contents?  perhaps add `--show-diff-on-failure` ?

**Comment by edgarriba** [comment]
<img width="663" alt="add debug flag · farm-ngworkspace@e6740fd" src="https://user-images.githubusercontent.com/5157099/149592707-6048c526-aff1-4888-a9eb-441a97f6dd56.png">

**Comment by asottile** [comment]
that doesn't look like the output that pre-commit 2.16.0 would produce, notably it is missing a "files were changed by this hook" output

also you haven't shown the full log file above, redacting important platform information

I really want to give you the benefit of the doubt but there's a lot you're not telling me

**Comment by edgarriba** [comment]
I have verified and we  have `pre-commit 2.16.0` and neither local nor ci appears shows that message.
We use a docker container configuration in an internal repository that for security reason I cannot fully disclose about the whole platform. In short, we use a LTS ubuntu with latest version of pip.

The pre-commit in local seems to do the right thing but later in GH (which in principle uses the same docker container) doesn't recognize well the end of line character ?

**Comment by asottile** [comment]
without a reproducible case I cannot help you -- please make a minimal reproducible case that I can clone and verify

**Comment by asottile** [comment]
(and consider sponsoring the project if your company is receiving value from it)

**Comment by asottile** [comment]
closing for now -- please make an open source reproduction of this that I can look at

**Comment by edgarriba** [comment]
I’ll do — thanks in case for the help.
