### ISSUE TITLE
tag stage

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2226]
[`git` doesn't seem to offer a `tag` / `pre-tag` hook](https://git-scm.com/docs/githooks#_hooks) even thought it seems like a useful thing to have. I assume `pre-commit` won't/can't offer hooks not already in `git`'s hook API? Is there a way to trigger hooks at the `push` stage only if the commit is annotated with a version tag?

**Comment by asottile** [comment]
correct it is not possible to hook into something which git does not provide a hook for

**Comment by janosh** [comment]
> Is there a way to trigger hooks at the push stage only if the commit is annotated with a version tag?

But it could offer an option to only trigger `push` hooks when there's a version tag, right?

**Comment by asottile** [comment]
you can already do that -- here's the variables you'd check: https://github.com/pre-commit/pre-commit/blob/f1d2e6c289774cc5258d10e6f275560c02c2525b/pre_commit/commands/run.py#L373-L380
