### ISSUE TITLE
Overriding hook arguments

### ISSUE THREAD

**Issue by MarkKoz** [pre-commit/pre-commit#2228]
Sometimes, I'd like hooks to use different arguments under certain conditions, such as in CI. For example, in CI I may want to specify `--format` to flake8 so that GitHub can annotate my commits. However, in a local development environment I'd instead want the default format.

What's the recommended way of dealing with this in a DRY way? By DRY, I mean only specifying the version of a dependency/hook one time in one place. The current workarounds I can think of aren't DRY: I can manually install flake8 with pip in CI, or I can duplicate the hook in the config and set its stage to manual.

**Comment by asottile** [comment]
you can add additional [`stage: [manual]` hook](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages)

**Comment by MarkKoz** [comment]
@asottile I mentioned that. Am I missing something about how to make this DRY? If I already have a flake8 hook that has a specific version and a bunch of additional dependencies with specific versions, it's not ideal to have to duplicate all of that. I'd have to manually ensure that all the versions are kept in sync, which is error-prone.

**Comment by asottile** [comment]
well you haven't shown me what you have and DRY is often a foolish goal -- you can probably use some wacky yaml refs or merges or ...
