### ISSUE TITLE
Skipping all hooks (without using --no-verify)

### ISSUE THREAD

**Issue by hterik** [pre-commit/pre-commit#2231]
Hi
We are using Gerrit to host our git repos. Gerrit requires all commit messages to have a `Change-Id` footer in the commit message, otherwise it rejects even pushing an "open change" (the equivalent of a PR). This Change-Id is auto generated using a `commit-msg` hook, which you install as you clone the repo[1]. See https://gerrit-review.googlesource.com/Documentation/user-changeid.html for the gritty details.
[1] In practice this is done by copying a short "_Clone with commit message hook_" script, like here: https://android-review.googlesource.com/admin/repos/platform/manifest,general 

Now imagine you have worked on a commit for some time but you are not fully done. At this point, the commit might not pass the pre-commit hook, or the hooks are broken for some other reason, but you are still in a rush to push it as open change, just to ensure it is backed up. Or maybe you want architectural review or handing it over to someone else.

Since the pre-commit fails, normally you could pass `--no-verify`, **but this also disables the Gerrit Change-Id generation**, leaving you unable to push even the incomplete commit.
I've seen [the SKIP-environment variable](https://pre-commit.com/#temporarily-disabling-hooks) but this requires listing every hook id. Would it be possible to add an "all" option to SKIP, or another envvar like SKIP_PRE_COMMIT? Preferably this should be evaluated as early as possible, even in the hook shell script before python starts at all, to provide an escape hatch for _any_ potential failures, like incorrect python versions etc.
Maybe git already has something with finer granularity than `--no-verify`?

Temporary uninstalling the pre-commit is of course another option but not super convenient and easy to forget to add it back, especially in the case of errors caused by a partially done commit where skipping really is a one time temporary operation.

**Comment by asottile** [comment]
yeah I'd recommend your current situations

**Comment by nitrocode** [comment]
I'm not sure what the recommendation is here. Is it to set `SKIP` for each pre-commit hook ? If so, this is kind of a pain to do especially because there is no way to natively list installed hooks.

This seems to work. You can build the SKIP env var by grepping the `.pre-commit-config.yaml` file and then comma delimiting the results

```bash
SKIP=$(grep -oP '(?<=- id: )[\w\d_-]+' $(git rev-parse --show-toplevel)/.pre-commit-config.yaml | tr '\n' ',' | sed 's/,$//g')
```

Example

```bash
✗ echo $SKIP
terraform_fmt,check-added-large-files,forbid-new-submodules,no-commit-to-branch,trailing-whitespace,end-of-file-fixer,check-merge-conflict,check-executables-have-shebangs,check-case-conflict,mixed-line-ending,check-yaml,check-json,pretty-format-json
```

I based the grep based on this comment

- https://github.com/pre-commit/pre-commit/issues/2562#issuecomment-2329121559 

Another way to do it is to just remove the

**Comment by asottile** [comment]
the recommendation is that your workflow is bad and you should adjust it
