### ISSUE TITLE
Global hook to detect pre-commit config per repo and run if present

### ISSUE THREAD

**Issue by jcogilvie** [pre-commit/pre-commit#2233]
I know the team has opted not to provide for a global pre-commit config file in #450, but I have a variation of that request which might be more palatable.

Is it possible to, instead of having to `pre-commit install` in every repo, have a global hook which on commit checks the present repo for a config file, and, if present, runs pre-commit with that config?

It'd save me (and my team) the overhead of remembering to `pre-commit install` with every new checkout.

**Comment by asottile** [comment]
I believe you're looking for [`pre-commit init-templatedir`](https://pre-commit.com/#pre-commit-init-templatedir)

**Comment by jcogilvie** [comment]
That's close, but not quite right.  This works for new repositories, but I (and my team) also have a couple dozen existing repositories checked out for which this does not take effect.

I'm thinking about something like `pre-commit install --global` that would set up pre-commit using the `core.hooksPath` git config.  Or if not an actual feature, then at least some quick documentation on how to do this myself.

**Comment by asottile** [comment]
sorry no, `core.hooksPath` will not be implemented -- search the issue tracker for that if you're looking for why.
