### ISSUE TITLE
git commit fails to install environment in a git repo

### ISSUE THREAD

**Issue by baggiponte** [pre-commit/pre-commit#2239]
### describe your issue

I added a `.pre-commit-config.yml` to an existing repo and committed it. Then I added some more files to the staging area and when I commit I get the prompt that pre-commit is creating an environment, but fails to install.

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.35.1
sys.version:
    3.10.2 (main, Feb  2 2022, 06:19:27) [Clang 13.0.0 (clang-1300.0.29.3)]
sys.executable: /Users/luca/.local/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/Users/luca/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/Users/luca/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "/Users/luca/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/luca/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/Users/luca/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/Users/luca/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/repository.py", line 86, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

**Comment by asottile** [comment]
can you describe your setup as the error message asks you to do?  it sounds like your python executable is broken but I have nothing to go on (where does it come from? how did you install it?)

**Comment by baggiponte** [comment]
Thank you for the prompt reply - I am afraid I did not completely get the "describe your environment". I have installed pre-commit via pipx, which installs it using python 3.10.2 (in the meantime, I tried to reinstall it, but the error persists). What other info do you need? Glad to help!

**Comment by asottile** [comment]
mostly: from where did you get python 3.10, what platform are you on, what architecture, how did you install pipx, etc. etc. -- help me understand so I can reproduce your setup

**Comment by baggiponte** [comment]
Oh sure, sorry.

# OS and `pipx`

I am on macOS 12.1 and I installed `pipx` with `homebrew`. `pipx` has an environmental variable `$PIPX_HOME` set to `$HOM/.local/pipx` and a `$PIPX_BIN_DIR` set to `$HOME/.local/bin`. `pipx` installs the packages you install in a dedicated venv and uses by default the latest python version compatible with the package. For example, here are some of the packages I have installed with `pipx`:

```
❯ pipx list
venvs are in /Users/luca/.local/pipx/venvs
apps are exposed on your $PATH at /Users/luca/.local/bin
...
   package jupytext 1.13.6, installed using Python 3.9.6
    - jupytext
   package pdm 1.12.8, installed using Python 3.10.1
    - pdm
   package pre-commit 2.17.0, installed using Python 3.10.2
    - pre-commit
    - pre-commit-validate-config
    - pre-commit-validate-manifest
   package thefuck 3.32, installed using Python 3.10.0
    - fuck
    - thefuck
```

## `pipx` and Python installations

### `$PIPX_DIR/shared` library

At first, I thought  `pipx` installed its own versions of Python, but from what I understood by looking at the `$PIPX_HOME` dir, it uses Python versions it finds on your machine. I have multiple Python versions on my machine: either installed with homebrew (to make formulae work) and `pyenv`, but also miniconda for my data science projects.

I had a look at `$PIPX_DIR/shared`, as I believe it contains the libraries that are shared among the installed python libraries, and it looks like this:

```
❯ tree -L 2
.
├── bin
│   ├── Activate.ps1
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── pip
│   ├── pip3
│   ├── pip3.9
│   ├── python -> python3.9
│   ├── python3 -> python3.9
│   ├── python3.9 -> /usr/local/opt/python@3.9/bin/python3.9
│   └── wheel
├── include
├── lib
│   └── python3.9
└── pyvenv.cfg

4 directories, 12 files
```

As a starter, `python3.9` points to the homebrew python (I have both python@3.9 and python@3.10). The `pyvenv.cfg` file still points to homebrew python:

```
❯ < pyvenv.cfg
home = /usr/local/opt/python@3.9/bin
include-system-site-packages = false
version = 3.9.6
```

### `PIPX_DIR/venvs/pre-commit`

Then, there are files and symlinks also under `PIPX_DIR/venvs/pre-commit`, i.e. where `pre-commit` is installed.

```
❯ tree -L 2
.
├── bin
│   ├── Activate.ps1
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── identify-cli
│   ├── nodeenv
│   ├── pre-commit
│   ├── pre-commit-validate-config
│   ├── pre-commit-validate-manifest
│   ├── python -> python3.10
│   ├── python3 -> python3.10
│   ├── python3.10 -> /usr/local/Cellar/pipx/1.0.0/libexec/bin/python3.10
│   └── virtualenv
├── include
├── lib
│   └── python3.10
├── pipx_metadata.json
└── pyvenv.cfg

4 directories, 15 files
```

And the `pyvenv.cfg` points to: 

```
❯ < pyvenv.cfg
home = /usr/local/Cellar/pipx/1.0.0/libexec/bin
include-system-site-packages = false
version = 3.10.2
```

`usr/local/Cellar/pipx/1.0.0/libexec/bin` is another dir that looks like the other above and the python version symlinked is the same as above, i.e. python@3.10 from homebrew:

```
❯ tree -L 2 /usr/local/Cellar/pipx/1.0.0/libexec
/usr/local/Cellar/pipx/1.0.0/libexec
├── bin
│   ├── Activate.ps1
│   ├── activate
│   ├── activate-global-python-argcomplete
│   ├── activate.csh
│   ├── activate.fish
│   ├── pip
│   ├── pip3
│   ├── pip3.10
│   ├── pipx
│   ├── python -> ../../../../../opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/python3.10
│   ├── python-argcomplete-check-easy-install-script
│   ├── python-argcomplete-tcsh
│   ├── python3 -> ../../../../../opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/python3.10
│   ├── python3.10 -> ../../../../../opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/python3.10
│   ├── register-python-argcomplete
│   └── userpath
├── include
├── lib
│   └── python3.10
└── pyvenv.cfg

4 directories, 17 files
```

**Comment by asottile** [comment]
ah yep that would do it

you have a mix of 3.10.0, 3.10.1, and 3.10.2 -- so when pre-commit creates a "python3.10" environment from 3.10.2 and gets an unrelated version it complains

you'll want to clean up your python setup so you only reference one of those three versions and it should resolve itself -- admittedly `pipx` should probably be detecting this case and healing for you but that would be a request towards pipx and not here

**Comment by baggiponte** [comment]
thanks for the reply! i tried to follow the suggestions in [this pipx issue](https://github.com/pypa/pipx/issues/791) and "nuked the `$PIPX_DIR/shared`". This did not help, but re-installing all pipx libraries did bump the python version to the latest one.

i noticed the problem was solely with the pre-commit hook of isort, which by default installs itself using the first pip in your `$PATH`: I noticed my `pyenv` (not `pyvenv`!) active (global) python was 3.9.9 and then I switched to 3.10.2, but this did not change anything.

in the end, i just removed the isort hook and everything worked out. i do not know why with black this problem does not arise. the thing is: i have already installed isort using pipx (as well as many other tools like black, bandid, autopep8...) so i was wondering if there was a way to tell pre-commit to use them. or shall i ping the folks at isort?

**Comment by baggiponte** [comment]
as a reference, i opened a new issue [here](https://github.com/pypa/pipx/issues/818). i am inclined to think it's `pipx`, as i tried to install a fresh `pre-commit` via homebrew (instead of `pipx`) and i have not encountered the problem (yet).
