### ISSUE TITLE
Why tests/commands/run_test.py:test_multiple_hooks_same_id ?

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#224]
What is the rationale behind this test ?
Why allowing multiple hooks with identical ids in the config instead of raising an error ?
Doesn't it break the ability to `pre-commit run $hook_id` ?

**Comment by asottile** [comment]
We have several (closed source,  sorry!) hooks at yelp that do wildly different things based on the arguments that are passed to them.  This allows them to reuse the backing repo but have several calls to that hook.  And you're right, running by a single hook id is a bit awkward in this case.  This however is a feature we depend on so I added this test.

**Comment by Lucas-C** [comment]
OK, thanks for the answer.
