### ISSUE TITLE
How can I use MonkeyType with pre-commit?

### ISSUE THREAD

**Issue by Mockapapella** [pre-commit/pre-commit#2241]
For the uninitiated: https://github.com/Instagram/MonkeyType

> MonkeyType collects runtime types of function arguments and return values, and can automatically generate stub files or even add draft type annotations directly to your Python code based on the types collected at runtime.

It would be really nice to be able to apply this kind of static typing automatically with pre-commit. Looking at [the pre-commit website](https://pre-commit.com/) it looks like this should be possible, but I'm not familiar enough with how pre-commit works under the hood to tell either way

**Comment by asottile** [comment]
since you haven't really tried anything yet here's [the docs for creating new hooks](https://pre-commit.com/#new-hooks).  if you get stuck on something then ask your question :)
