### ISSUE TITLE
Feature Implmentation: Summary info optionally output in JSON format

### ISSUE THREAD

**Issue by andrew-glenn** [pre-commit/pre-commit#2256]
please discuss the implementation first in an issue that way we can design it instead of going straight to a PR

_Originally posted by @asottile in https://github.com/pre-commit/pre-commit/issues/2255#issuecomment-1048037857_

As requested, I'm moving this discussion into an issue. 

See PR: #2255

The idea there is to output the 'summary' information in JSON format. External tools / processes can then parse the data and perform further actions. (For example, sending the data to an internal reporting mechanism, etc).

The proposed implementation in the PR is pretty straight-forward. Only passing the optional argument (with a path to a filename) enables this feature. Otherwise, the status quo is observed.

I welcome any thoughts on this feature / implementation.

_Side note: If discussing feature implementations in an issue (as opposed to a PR) is the requested interaction method, it's not stated anywhere in the contribution guide that I'm finding. While I understand it's probably easier to manage from an administrative point of view, I feel setting  a PR to draft and discussing in-line is a better contributor experience_

**Comment by asottile** [comment]
there's a handful of duplicates that you'll want to read through and understand before we revisit the decisions made there -- I would start with #1332 and click through the duplicates linked there

**Comment by andrew-glenn** [comment]
OK. I've read through the linked duplicate (and the nested one from there).

I agree that parsing the output of individual toolsets is way out of scope. It's not a rabbit hole that I want to go down either. I also understand that you don't want to really get in the business of parsing output.

The comment that strikes me about previous conversations is this: 

https://github.com/pre-commit/pre-commit/issues/1332#issuecomment-679215923
> > Here, I'd been thinking outcome in terms of ...
> 
> you can get all this from the current output except changed paths
> 
> > if it's possible to slurp the changed path(s) into the output, that'd be great, since that's mainly what a person will be interested in
> 
> it's not possible to get changed paths, pre-commit doesn't even know that on a per-hook basis (diffs are treated opaquely)

You're correct that it's available in the stdout output. it's not in a machine readable format. The onus is on the end-user to write a parsing utility (which would be fragile, and totally dependent on you not changing the current output format) 

Is this something that you're willing to reconsider? If not, understood - I'll spend my time writing a very fragile output parser. However, it's really not deal, speaking honestly.
