### ISSUE TITLE
Can't find git in WSL2

### ISSUE THREAD

**Issue by davidkopp** [pre-commit/pre-commit#2258]
### describe your issue

Command `pre-commit install` fails with the following error:

> An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
> Check the log at /home/david/.cache/pre-commit/pre-commit.log

I'm executing the command inside of Windows Subsystem for Linux (WSL2) in a git repository that's inside the linux filesystem. Commands like `git --version` and `git status` are working.

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
- repo: git://github.com/jcchavezs/pre-commit-kotlin
  rev: HEAD
  hooks:
    - id: ktlint
      args:
      - --color --disabled_rules=no-wildcard-imports
```

### version information

```
pre-commit version: 2.17.0
git --version: [Errno 8] Exec format error: '/usr/local/bin/git'
sys.version:
    3.8.10 (default, Nov 26 2021, 20:14:08)
    [GCC 9.3.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

```
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/git.py", line 59, in get_root
    cmd_output('git', 'rev-parse', '--show-cdup')[1].strip(),
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/util.py", line 160, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/bin/git', 'rev-parse', '--show-cdup')
return code: 1
expected return code: 0
stdout:
    [Errno 8] Exec format error: '/usr/local/bin/git'

stderr: (none)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/main.py", line 351, in main
    _adjust_args_and_chdir(args)
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/main.py", line 168, in _adjust_args_and_chdir
    toplevel = git.get_root()
  File "/home/david/.local/lib/python3.8/site-packages/pre_commit/git.py", line 63, in get_root
    raise FatalError(
pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

**Comment by asottile** [comment]
what does `file /usr/local/bin/git` give you? and what does `type git` and `which -a git` give you?

it *sounds* like you've subtly broken your git installation given the error message which wouldn't be a pre-commit problem

**Comment by davidkopp** [comment]
`file /usr/local/bin/git`:
> /usr/local/bin/git: ASCII text

`type git`:
> git is /usr/local/bin/git

`which -a git`:
> /usr/local/bin/git
> /usr/bin/git
> /bin/git

By the way, I have installed git in the Windows file system and in the Linux file system. But inside WSL only git from the Linux file system is used.

**Comment by asottile** [comment]
what does `head -1 $(which git)` give you?  it seems very weird that you have `/usr/local/bin/git` in the first place -- did you do that?

**Comment by davidkopp** [comment]
Thank you for that hint!
Indeed I had placed `/usr/local/bin/git` there in the first placed with a [script](https://gist.github.com/jasonboukheir/3fdab92ece236744528447a4f7f5de00). Unfortunately I had forgot about that script. When I remove this script from there the `pre-commit install` command works. So sorry for the unnecessary interruption.

**Comment by asottile** [comment]
you *probably* forgot `#!/bin/sh` on that script
