### ISSUE TITLE
Trying to use repository local hook, but the executable is not being found

### ISSUE THREAD

**Issue by Wargazm** [pre-commit/pre-commit#2259]
Hello,
My team's workflow includes running a setup script that adds a bunch of directories to the user's path.  There is a utility package in one of these paths that contains a script (let's call it repo_check) that I want to use as a pre-commit "local repository" hook

The project I am working on is checked out here:

`/path/to/my/workspace/project_repo`

And the utility is located here:

`/utility/paths/are/different/ver_1.0.0/bin/repo_check`

After sourcing my team's setup script, I can run `which repo_check` and it finds it just fine.

However, pre-commit can't find it because it appends my workspace path to the `entry`.  This is my `.pre-commit-config.yaml` file:

    repos:
    -   repo: local
        hooks:
        -   id: repo_check
            entry: repo_check
            name: My Special Repo Checker
            language: script
            pass_filenames: false

Here's my shell output

    $ pre-commit run

    My Special Repo Checker..................................................Failed
    - hook id: repo_check
    - exit code: 1

    Executable `/path/to/my/workspace/project_repo/repo_check` not found    

As you can see, my _workspace_ path was prepended to the entry.  I don't want that to happen.  I just want it to run `repo_check` bare, because the user's environment has been configured to find that utility in it's path.

I can work around this limitation by hardcoding the path in the entry:

    repos:
    -   repo: local
        hooks:
        -   id: repo_check
            entry: /utility/paths/are/different/ver_1.0.0/bin/repo_check
            name: My Special Repo Checker
            language: script
            pass_filenames: false

But this is not optimal because, as you can see, there is a version in that path.  In the future, we may move to version 2.0.0 of the utilities package by updating the version number in the setup script I mentioned earlier.  I don't want to have to edit this YAML file in addition to editing the setup script just to keep the utility package versions in sync with each other, as this could be error prone.

Is there a way to configured pre-commit to not prepend the workspace path when running a script as a hook, and instead just look for it in the user's path?

**Comment by asottile** [comment]
then you don't want `language: script` you want [`language: system`](https://pre-commit.com/#system)

**Comment by Wargazm** [comment]
Perfect!  That is exactly the problem.  Thank you very much!
