### ISSUE TITLE
pre-commit Passed badge has very poor contrast (gray on green)

### ISSUE THREAD

**Issue by bristea** [pre-commit/pre-commit#2268]
### describe your issue

It seems that the ANSI colors combination used by pre-commit tool to displayed the result of a hook run is using an unfortunate color combination: light-gray on green, something that is hard to read on almost any terminal color theme.

I do suspect a reason for this is that it does only decides to change the default (transparent) background to green. Those few that are using a white background terminal as less likely to be impacted by the constrast issue, but those on dark backgrounds are high likely to be affected.

There are many way this can be avoided, even with avoiding use of background color and sticking just to coloring the text foreground or forcing use of either pure bold-white or black for text color, instead of defaulting to default text.

Default text color is usually a non bold/highlighted color, a shade of gray, which is exactly the kind of color that has a bad contrast with green in particular. To a lesser extent the same applies to red background.

Please note that I am not suffering from any colour vision deficiency, so we could expect others to find the contrast issue even more than me:

<img width="158" alt="pre-commit-contrast-issue" src="https://user-images.githubusercontent.com/17796449/156756637-d05e5167-fd2a-41df-b2fc-79f171e17e5d.png">
.

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
N/A
```

**Comment by asottile** [comment]
these are your terminal color choices -- so change them

**Comment by bristea** [comment]
Initial example was from vscode and looks almost identically bad with 5 themes (Abyss, One Dark Pro(s) and Tomorrow Night Blue). I will also include an example with the default theme, which is a little bit better but the underlining issue is still present. 
<img width="231" alt="precommit-badges-vscode-default-theme" src="https://user-images.githubusercontent.com/17796449/156774553-27f3ec3d-1972-4b93-a114-36e9b761ed0b.png">

The failure text can be read by anyone but I am not so sure about the Passed text. Keep in mind that the image appears already 2x the real size due to being captured from a retina/hidpi display.

While a terminal theme can influence the outcome it cannot really undo the damage caused by a default lacking contrast.   

Putting even the pure (unthemed) RGB values on an accessibility tool like https://webaim.org/resources/contrastchecker/ will produce some warning signs.
