### ISSUE TITLE
Add GIT_HTTP_PROXY_AUTHMETHOD to kept environment variables

### ISSUE THREAD

**Issue by VincentBerthier** [pre-commit/pre-commit#2271]
### describe your issue

On the cluster I work on, there’s a proxy. It’s… Let’s just say that proxy is being a pain, and to make it work we have to set the environment variable GIT_HTTP_PROXY_AUTHMETHOD.

In pre_commit/git.py however, only a small subset of variables are kept, and that one is not among them. So, sure, I can (and did) edit the script to keep that one too (and it works now) but it’s not ideal.

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
Not relevant
```

**Comment by asottile** [comment]
sounds fine! would you like to send a PR?

**Comment by VincentBerthier** [comment]
Sure, it’s done.
