### ISSUE TITLE
Inserting flags before each file when passing file list to a hook?

### ISSUE THREAD

**Issue by Wargazm** [pre-commit/pre-commit#2273]
Hello,
if I define a hook with pass_filenames set to true, I understand I will get the following command:

`path/to/script-or-system-exe dir/file1 dir/file2 file3`

Some of our scripts that I'd like to use as hooks are written such that they need a flag passed before each file.  For example:

`path/to/script-or-system-exe --file dir/file1 --file dir/file2 --file file3`

Is it possible to do this with pre-commit?  Or am I stuck having to rewrite the script?

**Comment by asottile** [comment]
it is not, [pre-commit passes files as positional arguments after `args`](https://pre-commit.com/#arguments-pattern-in-hooks)

**Comment by Wargazm** [comment]
Thanks for the quick response, asottile.  It's what I expected.  

Would you be open to adding this as a feature request?

**Comment by asottile** [comment]
no
