### ISSUE TITLE
Run hooks on files in specific directory

### ISSUE THREAD

**Issue by ericus20** [pre-commit/pre-commit#2275]
### describe your issue

I have a project structure

/todo-list
     .pre-commit-config.yaml
     /api

where there are some files in the /api that I want to target and run.

I have tried several matching techniques following this thread
https://github.com/pre-commit/pre-commit/issues/1173

/api is a spring boot project with gradle which comes with gradlew included. 

Output

```
$ git commit -m "asdf"
trim trailing whitespace.............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
don't commit to branch...................................................Passed
check for merge conflicts............................(no files to check)Skipped
gradle check.........................................(no files to check)Skipped
On branch test
nothing to commit, working tree clean
```

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, develop]
    -   id: check-merge-conflict
-   repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.2.1  # Use the ref you want to point at
    hooks:
    -   id: gradle-check
        args: ['-w', --wrapper]
        files: ^api/
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Not present

**Comment by asottile** [comment]
try these documentation sections to answer your question:

 - [pre-commit during commits](https://pre-commit.com/#pre-commit-during-commits)
 - [quick start: run against all the files](https://pre-commit.com/#4-optional-run-against-all-the-files)

**Comment by kenanmasri** [comment]
Would this be possible with `pre-commit run`?

I want to manually run `pre-commit run my/sub/folder/`
Because specifying files manually (e.g. `/my/sub/folder/**/*.*`) would not see the .rc configs for different hooks...

For example I have configured pylint to ignore: `migrations`
I wonder if there's a better way so that specifying a directory is possible and each hook can check by its own.

Thanks

**Comment by asottile** [comment]
@kenanmasri please make a new issue describing your situation -- this comment here is off topic and unrelated to OP's issue (though I suspect if you search "subdirectory" or "monorepo" instead you'll find the ~10 or so issues with answers to your question)
