### ISSUE TITLE
feat discussion/req: customizable 'skipped' exit code for hook

### ISSUE THREAD

**Issue by andrew-glenn** [pre-commit/pre-commit#2279]
I'm running into a use case where the `identity` library doesn't fully recognize CloudFormation templates (a superset of YAML/JSON). Rather than clutter the library with relatively niche use-case, I'd rather pass my custom hook all JSON/YAML files and have middleware determine which files to act on.

To that end, I'd like to signal back to pre-commit that the check should be flagged as `SKIPPED` (rather than passed). I'm proposing a `skipped_exit_code` parameter to each hook. The idea is that if the hook returns said exit code, it's marked as skipped.

Alternatively - I'm happy to submit a PR to the `identity` library adding CloudFormation support but I'm not sure it's a good fit and would require a fair amount of work (would need to further parse all JSON/YAML files to determine if they're CFN or not)

Thoughts?

**Comment by asottile** [comment]
no thanks -- this was discussed here: https://stackoverflow.com/a/71253727/812183

**Comment by andrew-glenn** [comment]
You didn't answer the second half of my question - which is - do you feel that CloudFormation support in the identity project is a good fit? Would you support a PR to add it?

**Comment by asottile** [comment]
and here -- I'd recommend you do the same as the official `cfn-lint`: https://github.com/pre-commit/identify/issues/281
