### ISSUE TITLE
How to handle dynamic configuration

### ISSUE THREAD

**Issue by tetienne** [pre-commit/pre-commit#2280]
Hi,

I’ve already read several times all the issues related to [monorepo](https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+monorepo) topic.

My company starts to have multiple (micro-)services located in the same git repository. These services can use different language versions and linter configurations. We would like to set a pre-commit configuration at the root folder of each service to avoid having a big `.pre-commit-config.yaml` file and give more freedom to the service owner.

I tried the following solution. 

```yaml
repos:
  - repo: local
    hooks:
      - id: dedicated-hook
        name: Run dedicated hook
        entry: ./hooks/pre-commit.py
        language: script
        types: [file]
```

```python
#!/usr/bin/env python3
import os
import subprocess
import sys

import pathlib

ROOT_PATH = pathlib.Path().absolute()
PACKAGES_HOME = ROOT_PATH / "packages"


def main():
    packages = []
    # Find all pre-commit specific configurations
    for root, dirs, files in os.walk(PACKAGES_HOME, topdown=True):
        if ".pkg" in files: #.pkg identify a service root folder
            dirs[:] = []
            if ".pre-commit-config.yaml" in files:
                packages.append(root)

    packages_files = {package: [] for package in packages}

    files = sys.argv[1:]
    
    # Filter modified files sent by pre-commit and dispatch them to the matching service.
    for file in files:
        for package in packages:
            if pathlib.Path(file).is_relative_to(package):
                packages_files[package].append(file)

    
    for package, files in packages_files.items():
        subprocess.call(["pre-commit", "run", "--config", pathlib.Path(package) / ".pre-commit-config.yaml", "--files", *files])

    return 0 # TODO


if __name__ == "__main__":
    exit(main())

```

So I use pre-commit to run again pre-commit with a specific configuration. But when testing the solution, I got:

```
/Users/tetienne/git/entropy/packages/backend 0
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/git', 'write-tree')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: Unable to create '/Users/tetienne/git/entropy/.git/index.lock' : File exists.
```

So I guess I’m doing something wrong, and probably the use case I implemented is not supported. 

A potential solution, would be that pre-commit, if no .pre-commit-config.yaml presents, use the output of a script (e.g .pre-commit-config.py) that generate a configuration.

**Comment by asottile** [comment]
what you're trying to do is intentionally not supported, you're on your own sorry
