### ISSUE TITLE
Add hook id to the console output of hooks

### ISSUE THREAD

**Issue by elagil** [pre-commit/pre-commit#2282]
I use pre-commit for checking files after saving them, by triggering a task in VSCode that looks like this:

```json
    "tasks": [
        {
            // Run pre-commit on the current file.
            "label": "pre-commit: current",
            "type": "shell",
            "command": "pre-commit run --file ${file}",
        }
    ]
```

Doing this, I want to see issues that the hooks find (especially linters), in the 'Problems' panel of VSCode. For that, I use a collection of different problem matchers, which each target the output of a particular hook and try to match it.

For example, a `flake8` matcher looks like this:

```json
    "problemMatcher": [
        {
            "owner": "flake8",
            "source": "flake8",
            "severity": "warning",
            "fileLocation": [
                "relative",
                "${workspaceFolder}"
            ],
            "pattern": {
                // Example: path/to/file:73:9: F841 local variable 'input' is assigned to but never used
                "regexp": "^(.*):(\\d+):(\\d+):\\s+(F\\d+)\\s(.*)$",
                "file": 1,
                "line": 2,
                "column": 3,
                "code": 4,
                "message": 5
            }
        },
    ]
```

The problem is that matchers for different hooks may be so similar that I get a match from the wrong matcher. Then, the `source` of the problem in my 'Problems' panel is incorrect, or the problem is incorrectly formatted.

**Proposed solution**
Matching would be unambiguous, if each line of the hook output would be prepended by the id of the hook. For example:

```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

flake8: path/to/file:125:9: E999 SyntaxError: EOL while scanning string literal
```

I envision an optional global pre-commit settings `prepend_hook_id`. It could also be a per-hook setting, if you prefer.

Would you consider such an output formatting option, if I made a pull request?

**Comment by elagil** [comment]
I made a PR, since this is very simple to implement. I decided to make it a per-hook setting `prepend_name`, as this is less invasive than a new global setting.

**Comment by asottile** [comment]
sorry I don't want to carry this complexity

you can accomplish this directly with `--format` in flake8

**Comment by elagil** [comment]
I guess, flake8 was not the best example, but other tools do not offer such formatting capabilities. I will try to find another way, possibly have to write a VSCode extension.

**Comment by elagil** [comment]
I found no other way to solve my problem, so I made a [VSCode extension](https://marketplace.visualstudio.com/items?itemName=elagil.pre-commit-helper) that runs pre-commit on saving a file, or via the command panel. Maybe you find this useful.
