### ISSUE TITLE
Checking commit ranges with `commit-msg` hooks

### ISSUE THREAD

**Issue by Holzhaus** [pre-commit/pre-commit#2290]
Pre-commit can be used on CI to automatically check Pull Requests. From the pre-commit documentation:

> pre-commit can also be used as a tool for continuous integration. For instance, adding `pre-commit run --all-files` as a CI step will ensure everything stays in tip-top shape. To check only files which have changed, which may be faster, use something like `pre-commit run --from-ref origin/HEAD --to-ref HEAD`.

However, this only runs hooks from the `commit` hook stage.

I'm using `gitlint` to ensure that commits follow the conventional commit style during the `commit-msg` stage. It would be nice if it was possible to automatically check if all commits in a PR conform to that style on CI. Unfortunately that does not work:

    $ pre-commit run --hook-stage commit-msg --from-ref  origin/HEAD --to-ref HEAD
    [ERROR] `--commit-msg-filename` is required for `--hook-stage commit-msg`

It would great if pre-commit support for this.

**Comment by nickbroon** [comment]
Could 'pre-commit run' implement the loop over each of the commits in from-ref to-ref range and run the commit-msg hook on each of commit msg? (Is it already implementing some form of loop to determine the files that have changed in the run on range?)
Being able to run the pre-commit msg-commit hook on range would be an extremely useful feature for use in CI automation.

**Comment by martin-eder-zeiss** [comment]
The current behavior is surprising. If one can explicitly specify a hook-stage and a range, then you would assume that all hooks from that stage are actually run against that range, which is not the case for "commit-msg".

@asottile is there really no way to do this? This would be a great enhancement and very helpful.
