### ISSUE TITLE
"pre-commit install" should install all necessary hooks

### ISSUE THREAD

**Issue by igh-fp** [pre-commit/pre-commit#2292]
Hi!

I think one of pre-commit's advantages is that someone who clones a repository does not have to know, which hooks shall be installed. Only one command is needed: `pre-commit install`. Then everything should be working as expected...

... as long, as only pre-commit hooks are required. If using other hooks like post-commit or post-checkout, `pre-commit install --hook-type post-commit` must be entered manually. Otherwise the defined hooks are simply not executed.

Should not `pre-commit install` identify, which hooks are needed (after cloning the repos and analyzing the stages of the hooks) and install all of them?

**Comment by asottile** [comment]
please search the issue tracker there are many duplicates

it's not possible to know the hooks with the information available at `pre-commit install` time
