### ISSUE TITLE
override `language` in `.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#2294]
In contrast to many other configuration options, `language` set in `.pre-commit-hooks.yaml` can't be overridden by `.pre-commit-config.yaml` (or at least it's not documented to be possible). On first sight, overriding does not seem to be something useful. However, I think it can be very useful iff `entry_point` is identical, in particular to avoid maintaining separate hooks for `language: docker`. Let me explain:

Assume I have a bunch of hooks with - say `language: xyz` that some people want to use `language: docker` with. The reason being that they [don't have `language: xzy` available on that system](https://github.com/lorenzwalthert/precommit/issues/387#issuecomment-1071414226), but they have docker. If `entry_point` is the same whether or not the hook is used with `language: docker` or some other language, creating a separate hook enty in `.pre-commit-hooks.yaml` sounds like redundant, plus they need separate ids, documentation, unit tests, although they host the same functionality.

For that reason, I think it makes sense to allow overriding `language` in `.pre-commit-hooks.yaml` with a language set in `.pre-commit-config.yaml`, in particular in the context of `language: docker`.

**Comment by asottile** [comment]
it works just fine, it's strongly not recommended however
