### ISSUE TITLE
pre-commit causes `git rev-parse --show-toplevel` to return $PWD in worktrees

### ISSUE THREAD

**Issue by sbienkow-ninja** [pre-commit/pre-commit#2295]
### describe your issue

I know this makes zero sense, expecially since all other things seem to work.
This seems to only happen during `commit` phase, and running manually with `pre-commit run` does not trigger it.

#### Folder structure
```
.
├── .git
├── hooks
│   └── pre_commit_bug.sh
└── .pre-commit-config.yaml
```

#### Reproduction script
```sh
#!/usr/bin/env bash
set -euo pipefail

orig="$(git rev-parse --show-toplevel)"
echo "ORIG: ${orig}"

cd hooks

new="$(git rev-parse --show-toplevel)"
echo "NEW: ${new}"

[ "${orig}" = "${new}" ]
```

#### Steps

1. Create new repo (`mkdir /tmp/pre-commit-bug && cd /tmp/pre-commit-bug && git init`)
2. Install pre-commit (`pre-commit install`)
3. Add attached `.pre-commit-config.yaml` as well as `pre_commit_bug.sh` script file (placing it in `hooks/` dir, as in the folder structure)
4. Commit those files, noticing that the PR was successful
5. Create new worktree `git worktree add ../pre-commit-bug2 && ../pre-commit-bug2`
6. Try creating a commit in this worktree `git commit --allow-empty` - notice that the hook failed

### Notes

I've tried to debug it for a while. As mentioned previously, this does not happen outside of commiting with precommit. I did diff the environment and noticed:
1. There are some env vars added. The `GIT_EXEC_PATH` contains `/usr/lib/git-core` (potentially important later). The `GIT_DIR` and `GIT_INDEX_FILE` are set to values I'd expect.
```python
>>> pprint(DeepDiff(working, faulty))
{'dictionary_item_added': [root['GIT_AUTHOR_DATE'], root['GIT_AUTHOR_EMAIL'], root['GIT_AUTHOR_NAME'], root['GIT_DIR'], root['GIT_EXEC_PATH'], root['GIT_INDEX_FILE'], root['GIT_PREFIX']],
# ...
}
```
2. The `PATH` is modified, and it's 13th value (out of 48) is inserted to equal `/usr/lib/git-core`
3. In the "not working" case, `which git` returns `/usr/lib/git-core/git` instead of `/usr/bin/git`, but it's just a symlink to the later.

When enabling git tracing logs with `git config --global trace2.normalTarget ~/trace.txt` and running pre-commit, you can see line suggesting that for git the `pre-commit-bug/hooks` is a worktree. I'm running git `2.35.1` which seems to be latest as of this writing.

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: bug-repro
        name: "Reproduce pre-commit bug"
        language: script
        entry: ./hooks/pre_commit_bug.sh
        always_run: true
```

**Comment by asottile** [comment]
dupe #1972

**Comment by sbienkow-ninja** [comment]
Related: https://www.spinics.net/lists/git/msg374184.html

From https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

> `GIT_DIR` is the location of the `.git` folder. If this isn’t specified, Git walks up the directory tree until it gets to `~` or `/`, looking for a `.git` directory at every step.
> 
> `GIT_WORK_TREE` is the location of the root of the working directory for a non-bare repository. **If `--git-dir` or `GIT_DIR` is specified but none of `--work-tree`, `GIT_WORK_TREE` or `core.worktree` is specified, the current working directory is regarded as the top level of your working tree.**

It looks like the solution would be to either:
1. Not set `GIT_DIR` env var
2. Also set `GIT_WORK_TREE` env var

**Comment by sbienkow-ninja** [comment]
Gotta love GH UI not updating. @asottile I saw that issue but it seemed related, not the same. But it's your call :)
I looked at the proposed PR and the fix is potentially easier. But I also haven't touched pre-commit source to know exactly how it works.
