### ISSUE TITLE
How can you run against a specific commit?

### ISSUE THREAD

**Issue by sogartar** [pre-commit/pre-commit#2296]
I want to run the hooks against the changes in a specific commit. The idea is to test if the commit is OK.
I tried to use `--from-ref` and `--to-ref` like that
```
pre-commit run --from-ref my-commit~1 --to-ref my-commit
```
This seems to only take the the files that have changed between the to commits and then runs the hooks against the current contents of the working tree. I want instead the hooks to run against `my-commit`.

**Comment by asottile** [comment]
you would need to run `git checkout my-commit` and then you have the right command
