### ISSUE TITLE
RScript location not always correct

### ISSUE THREAD

**Issue by jeff-m-sullivan** [pre-commit/pre-commit#2300]
This rarely comes up, because most people (in my experience) don't explicitly set R_HOME in regular terminals, but do have `RScript` in the path. If you use the RStudio-supplied Terminal, however, they do explicitly set R_HOME, which then causes the hook installs to break on some platforms (e.g., AWS Ubuntu is where I encountered the problem).

While some distributions add symlinks, the default install location for `RScript` is `$R_HOME/bin/Rscript`:
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installation

I believe it can be fixed in just one spot:

https://github.com/pre-commit/pre-commit/blob/354b900f15e88a06ce8493e0316c288c44777017/pre_commit/languages/r.py#L62

Just adding `bin` to that path join should solve the issue.

**Comment by asottile** [comment]
@lorenzwalthert ^

**Comment by asottile** [comment]
via #2301
