### ISSUE TITLE
question: implementing a pre-commit hook configuration with an extras requirement

### ISSUE THREAD

**Issue by wwuck** [pre-commit/pre-commit#2303]
I'm planning to submit a pre-commit hook to https://pypi.org/project/validate-pyproject/ but I'm not sure how to proceed with the project dependencies.  The regular way to run the tool is to install `validate-pyproject[all]` but I'm not sure what is the recommended way to get the hook config to install the extras requirements.

Should I add `.[all]` to `addtional_dependencies` or should I add in the individual extras requirements `tomli>=1.2.1`, `packaging>=20.4`, and `trove-classifiers>=2021.10.20` instead which would mean duplicating the version specifiers and require more maintenance from the project developer?

**Comment by asottile** [comment]
sounds to me like they're using extras incorrectly given some of their dependencies are hard requirements but listed as optional -- smells a bit over-engineered

the default configuration should probably not deviate from what one would install from pypi and should only document `additional_dependencies: ['.[all]']` as an option
