### ISSUE TITLE
Command `run` should allow external `diff` drivers on `--show-diff-on-failure`

### ISSUE THREAD

**Issue by ljmf00** [pre-commit/pre-commit#2307]
Currently, `pre-commit` doesn't allow external diff drivers to be used when `--show-diff-on-failure`. This is a convenient feature to have since default diff drivers are not so human readable, especially on trailing whitespace changes.

With default driver:
![image](https://user-images.githubusercontent.com/5050669/160429974-03c23d09-0bed-42ed-9084-beac88d89aba.png)

With a custom (`diff-so-fancy`) driver specified in the `.gitconfig` of the user:
![image](https://user-images.githubusercontent.com/5050669/160430038-e9034d03-2e11-4c2d-9b2e-7dbe2dd5c928.png)

In practice, `--no-ext-diff` shouldn't be enforced. See https://github.com/pre-commit/pre-commit/blob/main/pre_commit/commands/run.py#L306 .

**Comment by asottile** [comment]
ext diff drivers can take control of the terminal so they are intentionally not allowed

**Comment by ljmf00** [comment]
> ext diff drivers can take control of the terminal so they are intentionally not allowed

Can you clarify? Any hook can do that too and this is an explicit user choice. Currently, it overrides the user's intention of displaying the diffs.

If you are willing to be sceptical about this threatening the end-user, `pre-commit` can at least allow using the official `diff-highlight` script provided by `git`. See https://github.com/git/git/tree/master/contrib/diff-highlight .

**Comment by asottile** [comment]
if you want custom behaviour use `|| (your custom behaviour here && exit 1)`

invoking a custom diff tool can hang the program indefinitely while waiting for interaction so it is intentionally avoided

**Comment by ljmf00** [comment]
> if you want custom behaviour use `|| (your custom behaviour here && exit 1)`

Piping the output is an option, but if we consider that hooks could output a unified diff format in the middle of the output, this is not ideal.

> invoking a custom diff tool can hang the program indefinitely while waiting for interaction so it is intentionally avoided

External drivers can even open UI tools, but that's the user option to do so. What about just allowing custom pagers then? In contrast to external diff drivers, pagers are intended to output on the TTY and check for TTY interactiveness.
