### ISSUE TITLE
pre-commit doesn't lock dependencies

### ISSUE THREAD

**Issue by nbren12** [pre-commit/pre-commit#2310]
Wow, I've never had an issue closed so quickly without any opportunity to respond to your question. Sorry if I rubbed the wrong way @asottile. If you had left the issue open for longer than 2 minutes, I could have provided some justification for why I think it's a general issue with the tool.

Yes the issue was in  a downstream tool, but I expect users will want deterministic builds in general. This code suggest that pre-commit is in the business of managing python dependencies:
https://github.com/pre-commit/pre-commit/blob/354b900f15e88a06ce8493e0316c288c44777017/pre_commit/languages/python.py#L199

Also, the pre-commit docs explicitly mention  the`additional_dependencies` field.

A key tool for managing dependencies is locking transitive deps so that users can have deterministic builds.

_Originally posted by @asottile in https://github.com/pre-commit/pre-commit/issues/2309#issuecomment-1081155784_

**Comment by asottile** [comment]
right, well, if you searched the issue tracker you'd have either found `frozen` or `additional_dependencies` -- but you decided to raise an alarmist bug report without filling out the template

**Comment by nbren12** [comment]
Ok...so it is in scope.

Ya know, I did search the issue tracker, and spent a while reading issues and following the conversation. Maybe 30 minutes-1hr of thought before I decided to open the issue. It was an honest question based on an issue that will probably consume some of my time today...sorry that you read it as alarmist. Sorry I didn't know the magic keywords to search. I saw additional_dependencies mentioned in the docs/issues but not frozen.

This is the most negative interaction I've had on github ever btw...and it didn't have to be. Have a good one...I think I'll steer well clear of this issue tracker in the future.

**Comment by nbren12** [comment]
FWIW, here's a fix if anyone else runs into the problem:
https://github.com/ai2cm/fv3net/pull/1738/commits/67178f2d60f9d44044bbc7072211c0ec243b853c
```
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
```

Referencing #2309 so that the link trail leads here.
