### ISSUE TITLE
[FR] - command to install all defined hooks at once

### ISSUE THREAD

**Issue by jnoortheen** [pre-commit/pre-commit#2313]
`pre-commit install` will install only pre-commit stage . It will be useful to have an option to install all defined hooks at once based on the stages defined in pre-commit-config file. So after adding a pre-push/msg-style hooks, one can simply run `pre-commit install-all` instead of `pre-commit install --install-hooks -t stage -t st2 ...`

**Comment by asottile** [comment]
there's a bunch of duplicates in the tracker, please search

it's not possible given the information available at the command time and installing every git hook is not desirable

**Comment by jnoortheen** [comment]
sorry I wasn't able to find one.

When the command is ran, it can read the config file, and the stage field. Also , the command is to explicitly state all configured stages to be installed

**Comment by jnoortheen** [comment]
Thanks
