### ISSUE TITLE
Remove / deprecate expected_return_code

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#232]
Since we rely heavily on xargs, this feature doesn't really work as expected.

**Comment by Lucas-C** [comment]
Damn, that was useful.
To revert the logic of a `grep` for  example.
I don't of a specific use case though, so I won't miss it personally.

**Comment by asottile** [comment]
Yeah it was actually in the v-1 of the project, but is horribly broken for a nontrivial number of files: https://github.com/pre-commit/pre-commit/commit/7bb7f4a4838dbd5d52873187cc9b1b51b83cf0ba

I also ran into this while implementing pcre hooks, and you can see the "correct" way here (pcre are basically just special system hooks): https://github.com/pre-commit/pre-commit/blob/2ec7a34035e3072b2a4d118131fbf3b64c12b2f6/pre_commit/languages/pcre.py#L19-L23

The problem is with the way that xargs works (we'll use -n 1 to simplify the problem, but the same occurs with generalized larger n):

```sh
# test.sh
# Trivial shell file which executes whatever command is given to it
$1
```

```
$ ./test.sh true; echo $?
0
$ ./test.sh false; echo $?
1
$ echo true false | xargs -n 1 ./test.sh; echo $?
123
$ echo false false | xargs -n 1 ./test.sh; echo $?
123
```

Consider `false` to be like "grep failed to match", it's impossible to distinguish between "grep failing to match" in not all the processes vs "grep failing to match" in all of the processes.

I could reimplement xargs inside of pre-commit, but I don't want to do that and I don't think I'd get it right in all of the edge cases.
