### ISSUE TITLE
Docs Request: --color auto vs always

### ISSUE THREAD

**Issue by jamesbraza** [pre-commit/pre-commit#2320]
A coworker has cargo cult'd `--color=always` from an online `pre-commit` config.  Despite multiple attempts to figure out the difference by just playing around, I can't discern a difference between `--color=always` and `--color=auto`.

https://pre-commit.com/ mentions them, but doesn't document the difference.  Looking at the source code here https://github.com/pre-commit/pre-commit/blob/main/pre_commit/color.py#L81 it's also not immediately popping out.

I think it would be useful to add to the docs the difference between the two.

I would gladly create a PR to add the docs myself, I just need some quick pointers to expedite the process.

**Comment by asottile** [comment]
[it is documented already](https://pre-commit.com/#command-line-interface) ^F color

**Comment by jamesbraza** [comment]
Yes I had come across that, but it wasn't clear when `auto` switches between colored outputs and not colored outputs.
