### ISSUE TITLE
Very poor color contrast with dark themes. Potential fixes included.

### ISSUE THREAD

**Issue by ralgar** [pre-commit/pre-commit#2325]
I recently discovered this project and I love it, it helps me to catch simple issues, keep my commit history cleaner, and avoid wasting time on failed CI runs. Kudos!

The one issue I've had is extremely poor contrast with the color highlighting when using a dark color scheme, very similar to #2268. I've seen the answer given in that issue, and I disagree with the assessment that the terminal color scheme is to blame. I'm using a common color scheme (One Dark) that is widely tested in IDEs, terminals, and editors. I use this color scheme system-wide and I have no problems with the output of any other CLI application, or any elements of my window manager. The issue is 100% down to the implementation of highlighting in pre-commit. I suspect this issue is affecting the users of many common terminal dark themes.

---
### Solutions

I can propose two ways of fixing this problem, both could be easily implemented as options:
1. Highlight the text foreground, rather than the background.
2. When using background highlighting, the text foreground color should become the terminal background color. This option wouldn't change the branding of the application in any significant way.

Either of these solutions could be implemented as simple environment variables, or the latter could possibly be done automatically based on the terminal's foreground and background colors.

---
### Screenshots
 
**Default pre-commit highlighting:**
![pre-commit-default](https://user-images.githubusercontent.com/59636191/161409703-65cc6c66-cf28-48a3-973f-1ca4a86412ce.png)

**Using only foreground highlighting:**
![pre-commit-fg-no-bg](https://user-images.githubusercontent.com/59636191/161409462-f6afd841-cb2e-4ce9-bc53-ade23025fbb0.png)

**Using inverse background highlighting:**
![pre-commit-bg-inverted](https://user-images.githubusercontent.com/59636191/161409461-cd39f897-ad33-484e-bb0f-29a13f447d08.png)

**Full screenshot of my system:**
![vim-screenshot](https://user-images.githubusercontent.com/59636191/161409519-78123747-3aef-40aa-8d55-0fe3b5948573.png)

---

As you can see, it is absolutely nothing to do with my color scheme, and by changing the way pre-commit highlights text it is entirely possible to create a visually pleasing result like you see in the rest of my OS.

I fully understand if you aren't interested in doing the work for this, as it is a fairly trivial issue and it's likely a lot of work to maintain this project already. However, I do hope you would consider having a discussion about the logistics, and accepting a Pull Request to implement some kind of solution for dark theme users.

Thanks for your time.

**Comment by asottile** [comment]
dupe #2268 

please search the issue tracker next time

**Comment by ralgar** [comment]
I actually did search the issue tracker extensively and, not to be rude, but frankly I'm unsatisfied with the past answers given.

You're being rather **non-inclusive** to people with visual impairment issues, such as myself, and you are incorrectly blaming the color scheme for a problem that is caused entirely by the application itself. I'm rather disappointed that you seem unwilling to consider this, as the FOSS community is generally more inclusive and supportive of each other.

Having a soft and dark color scheme is *critical* in keeping my eye strain down, as I spend at least 8 hours in a terminal most days. I've discussed this with my optometrist, and he recommends that I stick with what I'm doing, as there has been a marked improvement since I switched to this configuration. So changing the terminal theme is not an option for me, especially after spending a fair amount of time building a configuration that works well for me. Having the colored output is also important, because it provides separation of information, and keeps me from having to focus as much on the non-critical info.

All I'm asking is that you will allow for a PR, to give users like myself a choice. I'm not asking to change the default behavior of the application, or for any significant work on your part. I do hope you'll consider this.

Thanks again for all your work on this project.

**Comment by asottile** [comment]
I understand you're frustrated but I think you're taking it a bit far to insinuate I'm being "non-inclusive" -- but I'll look past that.

you're asking me to change the established branding of the output of the tool for cosmetics.  the colors you are seeing are your choice and you can pick whichever ones you want.  for instance in my terminal's dark theme they appear quite fine and readable. the colors that are displayed are entirely in your control.  pre-commit just says "show this green" and "show this red" and your terminal emulator is applying your configured colors.  if the text were more significant I could mayyyybe see justifying the complexity of adding such a feature -- however they are a simple indicator of success / failure and the actual text is not meaningful (it doesn't need to be read).

additionally, suggesting that "just a PR fixes this" isn't really a sustainable approach to open source.  writing the code is a small fraction of the actual maintenance work required to support a feature.  there's always going to be ongoing cost for each incremental feature added not to mention the tests, documentation, explaining the behaviours, and debugging any quirks etc. to "solve a feature"

"I'm unsatisfied with the past answers given." I'm sorry but this isn't a sustainable or charitable approach to open source.  there are exact duplicates of your idea here with the same message.  this is a waste of everyone's time.  and none of what I'm saying is new or different from the previous exact duplicate issue.

and at the end of the day, it's open source and permissively licensed.  you're free to tweak it in whatever way you want to your exact liking!  and if you're not satisfied  you can even fork and maintain your own version of it!
