### ISSUE TITLE
[pre-commit.ci] Provide a way to opt-out the autoupdate PR

### ISSUE THREAD

**Issue by frostming** [pre-commit/pre-commit#2331]
First, apologize if it isn't the right place for this FR about pre-commit.ci.

I wonder if it is possible to add a `never` option to the `autoupdate_schedule` to disable the periodic autoupdate of the hooks. Some people in our projects are using the old toolchain and we want to keep the styles and lining rules consistent. We can anyway update the hooks manually if necessary.

**Comment by asottile** [comment]
you're looking for https://github.com/pre-commit-ci/issues (it's linked at the bottom of every pre-commit.ci page) -- also you'll want to check out this duplicate as to why it's intentionally not supported: https://github.com/pre-commit-ci/issues/issues/83

**Comment by frostming** [comment]
Yeah, thanks for the help.
