### ISSUE TITLE
allow yaml !include to have a distributed config file

### ISSUE THREAD

**Issue by christian-steinmeyer** [pre-commit/pre-commit#2335]
Hi!
Perhaps I am missing something, but I would like to be able to import content from another config file in my `.pre-commit-config.yaml`. Something like

```yaml
!include some-shared-pre-commit-config.yaml

repos:
  - # ...
```

Right now, the behavior when trying this is
```bash
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
=====> mapping values are not allowed in this context
  in "<unicode string>", line 3, column 6
Check the log at <CACHE_DIR>/pre-commit/pre-commit.log

```

Note, I am not looking for any logic on the level of pre-commit, but rather the support of an (almost) standard feature of yaml files, something like [pyyaml-include](https://github.com/tanbro/pyyaml-include).

I understand, that you are hesitant against the distribution of the config file (#554, #548), but in our case this would be actually really helpful. In contrast to the referenced issues, I also don't think, this would come with a lot of effort. What do you think? I'd be happy to support with docs or similar.

**Comment by asottile** [comment]
inclusion is intentionally not supported and will not be supported -- please search the issue tracker next time there are many duplicates

**Comment by christian-steinmeyer** [comment]
I did (see issue references above) and couldn't find any duplicates for a plain yaml include. Would you mind sharing one of them that contains the rational of why it's not supported?
