### ISSUE TITLE
Apparently similar to issue 1458 but without conda-forge (ref: pre-commit repeatedly installs environments when nothing has changed #1458)

### ISSUE THREAD

**Issue by MartinVedani** [pre-commit/pre-commit#2354]
### describe your issue

Good day @asottile / @nicoddemus, I am currently having the following issue (similar to ref: pre-commit repeatedly installs environments when nothing has changed #1458)  when trying to use pre-commit and ansible-lint hooks but without conda-forge.

Pre-commit seems to be trying to install ALL of ansible in a venv.

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
[INFO] Installing environment for https://github.com/ansible-community/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/martin.vedani/.cache/pre-commit/repo8pq_k3vn/py_env-python3/bin/python', '-mpip', 'install', '.', '.[community,yamllint]')
return code: 1
expected return code: 0
stdout:
    Processing /home/martin.vedani/.cache/pre-commit/repo8pq_k3vn
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting pyyaml
      Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
    Collecting rich>=9.5.1
      Using cached rich-12.2.0-py3-none-any.whl (229 kB)
    Collecting packaging
      Using cached packaging-21.3-py3-none-any.whl (40 kB)
    Collecting enrich>=1.2.6
      Using cached enrich-1.2.7-py3-none-any.whl (8.7 kB)
    Collecting ruamel.yaml<1,>=0.15.37
      Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
    Collecting tenacity
      Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
    Collecting wcmatch>=7.0
      Using cached wcmatch-8.3-py3-none-any.whl (42 kB)
    Collecting ansible>=2.10
      Using cached ansible-5.6.0.tar.gz (35.5 MB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting yamllint>=1.25.0
      Using cached yamllint-1.26.3-py2.py3-none-any.whl
    Collecting ansible-core~=2.12.4
      Using cached ansible_core-2.12.4-py3-none-any.whl
    Collecting pygments<3.0.0,>=2.6.0
      Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
    Collecting commonmark<0.10.0,>=0.9.0
      Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
    Collecting typing-extensions<5.0,>=4.0.0
      Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
    Collecting ruamel.yaml.clib>=0.2.6
      Using cached ruamel.yaml.clib-0.2.6-cp38-cp38-manylinux1_x86_64.whl (570 kB)
    Collecting bracex>=2.1.1
      Using cached bracex-2.2.1-py3-none-any.whl (12 kB)
    Requirement already satisfied: setuptools in ./py_env-python3/lib/python3.8/site-packages (from yamllint>=1.25.0->ansible-lint==0.1.dev1) (62.1.0)
    Collecting pathspec>=0.5.3
      Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
    Collecting pyparsing!=3.0.5,>=2.0.2
      Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
    Collecting resolvelib<0.6.0,>=0.5.3
      Using cached resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)
    Collecting jinja2
      Using cached Jinja2-3.1.1-py3-none-any.whl (132 kB)
    Collecting cryptography
      Using cached cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
    Collecting cffi>=1.12
      Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
    Collecting MarkupSafe>=2.0
      Using cached MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
    Collecting pycparser
      Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
    Building wheels for collected packages: ansible-lint, ansible
      Building wheel for ansible-lint (pyproject.toml): started
      Building wheel for ansible-lint (pyproject.toml): finished with status 'done'
      Created wheel for ansible-lint: filename=ansible_lint-0.1.dev1-py3-none-any.whl size=115203 sha256=6c13f1aa4c5ae6e0b72557c36af3d232436ab9acf27954a75c5c5cf11dbe88c8
      Stored in directory: /tmp/pip-ephem-wheel-cache-6imf6mys/wheels/8f/53/bd/4dccc2681a8dfe6206f8234504bd3f8170b4e5b02a9f884453
      Building wheel for ansible (setup.py): started
      Building wheel for ansible (setup.py): finished with status 'error'
      Running setup.py clean for ansible
    Successfully built ansible-lint
    Failed to build ansible
    Installing collected packages: resolvelib, commonmark, typing-extensions, tenacity, ruamel.yaml.clib, pyyaml, pyparsing, pygments, pycparser, pathspec, MarkupSafe, bracex, yamllint, wcmatch, ruamel.yaml, rich, packaging, jinja2, cffi, enrich, cryptography, ansible-lint, ansible-core, ansible
      Running setup.py install for ansible: started
      Running setup.py install for ansible: finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [19354 lines of output]
```

When I add "additional_dependencies" to my current .pre-commit-config.yaml like this:

```
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.3.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        types: [file]
        additional_dependencies: ['ansible-base:2.10.17']
```
I am getting this error:

```
 $ git commit -m 'lint test 2' .pre-commit-config.yaml
[INFO] Installing environment for https://github.com/ansible-community/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/martin.vedani/.cache/pre-commit/repow8vq8qf0/py_env-python3/bin/python', '-mpip', 'install', '.', 'ansible-base:2.10.17')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Invalid requirement: 'ansible-base:2.10.17'
```

Should I install conda-forge or change any of the versions used below? I am tied to ansible-base 2.10.17

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

```
$ pip show pre-commit
Name: pre-commit
Version: 2.18.1
Summary: A framework for managing and maintaining multi-language pre-commit hooks.
Home-page: https://github.com/pre-commit/pre-commit
Author: Anthony Sottile
Author-email: asottile@umich.edu
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ pip show virtualenv
Name: virtualenv
Version: 20.14.1
Summary: Virtual Python Environment builder
Home-page: https://virtualenv.pypa.io/
Author: Bernat Gabor
Author-email: gaborjbernat@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ pip show ansible-base
Name: ansible-base
Version: 2.10.17
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ pip show ansible-lint
Name: ansible-lint
Version: 5.3.2
Summary: Checks playbooks for practices and behaviour that could potentially be improved
Home-page: https://github.com/ansible-community/ansible-lint
Author: Will Thames
Author-email: will@thames.id.au
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ /usr/bin/python3 --version --version
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
```

```
$ head -1 $(which pre-commit)
#!/usr/bin/python3
```
```

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.3.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        types: [file]
        # additional_dependencies: ['ansible-base:2.10.17']
```

### ~/.cache/pre-commit/pre-commit.log (if present)

> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
[INFO] Installing environment for https://github.com/ansible-community/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/martin.vedani/.cache/pre-commit/repo8pq_k3vn/py_env-python3/bin/python', '-mpip', 'install', '.', '.[community,yamllint]')
return code: 1
expected return code: 0
stdout:
    Processing /home/martin.vedani/.cache/pre-commit/repo8pq_k3vn
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting pyyaml
      Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
    Collecting rich>=9.5.1
      Using cached rich-12.2.0-py3-none-any.whl (229 kB)
    Collecting packaging
      Using cached packaging-21.3-py3-none-any.whl (40 kB)
    Collecting enrich>=1.2.6
      Using cached enrich-1.2.7-py3-none-any.whl (8.7 kB)
    Collecting ruamel.yaml<1,>=0.15.37
      Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
    Collecting tenacity
      Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
    Collecting wcmatch>=7.0
      Using cached wcmatch-8.3-py3-none-any.whl (42 kB)
    Collecting ansible>=2.10
      Using cached ansible-5.6.0.tar.gz (35.5 MB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting yamllint>=1.25.0
      Using cached yamllint-1.26.3-py2.py3-none-any.whl
    Collecting ansible-core~=2.12.4
      Using cached ansible_core-2.12.4-py3-none-any.whl
    Collecting pygments<3.0.0,>=2.6.0
      Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
    Collecting commonmark<0.10.0,>=0.9.0
      Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
    Collecting typing-extensions<5.0,>=4.0.0
      Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
    Collecting ruamel.yaml.clib>=0.2.6
      Using cached ruamel.yaml.clib-0.2.6-cp38-cp38-manylinux1_x86_64.whl (570 kB)
    Collecting bracex>=2.1.1
      Using cached bracex-2.2.1-py3-none-any.whl (12 kB)
    Requirement already satisfied: setuptools in ./py_env-python3/lib/python3.8/site-packages (from yamllint>=1.25.0->ansible-lint==0.1.dev1) (62.1.0)
    Collecting pathspec>=0.5.3
      Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
    Collecting pyparsing!=3.0.5,>=2.0.2
      Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
    Collecting resolvelib<0.6.0,>=0.5.3
      Using cached resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)
    Collecting jinja2
      Using cached Jinja2-3.1.1-py3-none-any.whl (132 kB)
    Collecting cryptography
      Using cached cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
    Collecting cffi>=1.12
      Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
    Collecting MarkupSafe>=2.0
      Using cached MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
    Collecting pycparser
      Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
    Building wheels for collected packages: ansible-lint, ansible
      Building wheel for ansible-lint (pyproject.toml): started
      Building wheel for ansible-lint (pyproject.toml): finished with status 'done'
      Created wheel for ansible-lint: filename=ansible_lint-0.1.dev1-py3-none-any.whl size=115203 sha256=6c13f1aa4c5ae6e0b72557c36af3d232436ab9acf27954a75c5c5cf11dbe88c8
      Stored in directory: /tmp/pip-ephem-wheel-cache-6imf6mys/wheels/8f/53/bd/4dccc2681a8dfe6206f8234504bd3f8170b4e5b02a9f884453
      Building wheel for ansible (setup.py): started
      Building wheel for ansible (setup.py): finished with status 'error'
      Running setup.py clean for ansible
    Successfully built ansible-lint
    Failed to build ansible
    Installing collected packages: resolvelib, commonmark, typing-extensions, tenacity, ruamel.yaml.clib, pyyaml, pyparsing, pygments, pycparser, pathspec, MarkupSafe, bracex, yamllint, wcmatch, ruamel.yaml, rich, packaging, jinja2, cffi, enrich, cryptography, ansible-lint, ansible-core, ansible
      Running setup.py install for ansible: started
      Running setup.py install for ansible: finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [19354 lines of output]

**Comment by asottile** [comment]
this isn't the same as the other issue which was a continual reinstall

your issue here is Ansible can't install -- please report that to Ansible

this is not an issue with the framework

**Comment by MartinVedani** [comment]
Thanks @asottile - we will indeed. In the meanwhile however, since we are using ansible-base, the question is will it work with it? I have studied all the documentation and pointers I could find online for the last 4 days. Any pointers you may be able to share since you are my last resort?

 (btw, sorry for writting on the 2 year old issue, my sincere appologies, overloaded with reading I am afraid)

**Comment by asottile** [comment]
I don't know, I have no affiliation with ansible or ansible-lint -- you would have to ask your ansible-specific question to their tracker.  this tracker is for pre-commit, the framework

**Comment by MartinVedani** [comment]
OK, will do. I have not been able to keep the venv from trying to install ALL of ansible, tried additional_dependencies: ['ansible-base:2.10.17'], then [core], and finally [community] as well.

Thanks for the quick responses, have a great weekend.

**Comment by ssbarnea** [comment]
In fact that is the same bug as https://github.com/pre-commit/pre-commit/issues/1593 and is likely caused by a shallow git-clone instead of a full clone. Just an hour ago I got someone reporting a bug on https://github.com/ansible/ansible-lint/issues/2713

If setuptools-scm fails to find the last `tag`, it would use the implicit `0.1.dev1` as a version. Some tools can report a little bit different versions if they detect a missing version inside their archives, like `unknown`.

AFAIK, there is no option to tell pre-commit to perform full cloning and I do not know if there is something we can to to improve the outcome in that case. If anyone knows what we could to do to improve let me know.
