### ISSUE TITLE
Multi-language additional_dependencies

### ISSUE THREAD

**Issue by priv-kweihmann** [pre-commit/pre-commit#2357]
This is more like a general question (haven't found any other ticket in this regards, so if this has been answered already, please bare with me)
For now it seems like additional_dependencies need to be using the same package manager as the hook entry itself - which works really well for most of the use cases.
Looking at #1453 I can think of projects requiring sources from different package managers (mainly something + download inside the same environment) - for now docker_image seems to be the only way out, which feels quite the opposite of lightweight - and if I had the chance I wouldn't want to go that way.

I guess that would require some code changes at various place, but I got the impression that due to the good structure it's not impossible.

Would that be something that *could* be supported in the long run - or are there reasons for not doing so that I'm missing here?

**Comment by asottile** [comment]
do you have a concrete usecase?   I don't think this'll be supported -- each individual hook has a single language (a repo can provide hooks of several languages, but an individual hook must have exactly one)

**Comment by priv-kweihmann** [comment]
semgrep is one of the examples I was thinking about - that contains of a python lib, so the main entry point/language would be python, but it requires a binary blob written in ocaml to fully run the tool (they offer a pre-build blob via github release, so a simple http fetch would do it).
I know they offer a pre-made wrapper package to include this, but to me that looks iffy.
Additionally this tool relies on "rule files", which can be side-loaded - so plenty of ways something non-python might be required even though the main entry point is installable via pip.

This issue is not limited to semgrep - I just wanted to highlight that there are scenarios out there that unfortunately don't follow this one package manager at a time approach.

If you don't think this is worth the trouble, I'd okay with sticking to these wrapper libraries, although some of them coming from 3rd parties and are not that "trustworthy" or "reliable" as the actual upstream.

Basically I was just looking for a way to avoid using docker_image, esp when one keeps in mind that one might have limited control over the user's setup (so system or script might be off the table) and the docker being the most expensive option of them all.

I can think of plenty of ways how that could be implemented, but I'm not sure if I see all the implications on the overall architecture, or even on the project's scope - therefore my initial question.

one option would be an extension of "additional_dependencies" to a language specific dictionary and then cross referencing them at one point of the computing chain - not entirely sure if that would be a good idea, or (second option) using a limited support for language specific prefixes like "download:https://foo.org/bar.zip".

As I said this is more like a general question on how to tackle this, while avoiding docker, so (again) if you don't want to support this at any point (for understandable reasons), just close this issue and keep the issue for others to find (that might come up with the same idea as I had)

**Comment by asottile** [comment]
semgrep is pip installable so this doesn't see, needed

**Comment by priv-kweihmann** [comment]
That is correct for all but on case - when running on py 3.10 there's no pre-build wheel available that contains the needed binary.
In my understanding pip would fall back on the source distribution (please correct me if I'm wrong) - leading to a failing installation.

But your first comment made it clear that such scenarios might be not worth all the implementation trouble.
Thanks for the clarification.

**Comment by asottile** [comment]
ok you've wasted my time on an XY problem then -- state your actual issue up front in the future and don't waste my time with hypothetical "solutions" -- a multi language wouldn't have even helped you
