### ISSUE TITLE
Secret handling / loading / passing to hooks

### ISSUE THREAD

**Issue by w4tsn** [pre-commit/pre-commit#2358]
I'm wondering how you'd best approach loading and passing secrets like API tokens to hooks. E.g. the gitlab-ci-linter hook I'm trying to use wants a token passed as environment variable. It'd be nice if I wouldn't have to load the token manually into the env each time I want to commit. So it got me thinking: wouldn't it be nice if I could provide a file in the root-level configuration file (which is e.g. ignored by git) that loads secrets into environment variables that are then passed to hooks?

It could either be just a plain env file, but then the secrets would lay as plain text on the drive. Even better would then be e.g. adding a little `pass` (or similar) script to the repo alongside the pre-commit-config file which is then called to populate secrets which at best are only available in pre-commits context and pre-commit then hands over secrets from those vars explicitly to hooks that want those env vars.

Or is there a much better way I'm just not aware of?

WDYT?

As an example I'm trying to use the  following gitlab-ci-linter hook:

```
repos:
- repo: https://gitlab.com/devopshq/gitlab-ci-linter
  rev: v1.0.2
  hooks:
    - id: gitlab-ci-linter
```

**Comment by asottile** [comment]
I have no interest in making pre-commit a security-sensitive secret manager -- you're best to handle that in whatever way your tools manage them

**Comment by asottile** [comment]
(that said, pre-commit can run any thing yo uwant so you could always do something like `entry: ./my-secret-loader other-exe` or whatever)
