### ISSUE TITLE
Limit hook runtime

### ISSUE THREAD

**Issue by priv-kweihmann** [pre-commit/pre-commit#2360]
I'm occasionally encountering a weird issue with a certain hook which just get stuck forever) in a github CI pipeline, as well as locally.
- While this is an upstream bug (the used tool is detectsecrets) and will be addressed separately with upstream - I was kind of wondering if it would make sense to limit the maximum runtime of a hook/or the overall runtime of the pre-commit call to a certain time span (like for instance an hour or something way beyond the normal expected runtime)?

What I actually seen is that no logs were visible in the github pipeline, because of a timeout (6hrs runtime limit) - that makes it even harder to debug the underlying issue for me with this 1 out of a 100 runs appearing bug.

While if the pre-commit instance would terminate the call after, let's say 1 hour, by itself, I'm pretty sure I'd get proper logs that help investigating this issue better.

Looking at the code it seems like easy to be integrated, as popen communicate already offers such a parameter, but I'm not sure if that should be configurable or not and to what extent.

Or should such an issue be handled exclusively by the calling context? (If so it might be helpful for users to provide a hint in the advanced section of the pretty good documentation of the tool)

**Comment by asottile** [comment]
you can use [`timeout`](https://youtu.be/QRywzsBftfc) to debug -- no need for pre-commit to implement `timeout` poorly for you

override `entry` with `timeout`

**Comment by priv-kweihmann** [comment]
Thank you that makes indeed sense - will give it a try
