### ISSUE TITLE
Suggestion: Make pre-commit output easier to parse by problem matchers

### ISSUE THREAD

**Issue by elagil** [pre-commit/pre-commit#2369]
Hello!

We use `pre-commit` a lot for checking code during development, not only on commits or pushes, but also while saving a file. Development happens in VSCode, which is why I previously opened [this issue](https://github.com/pre-commit/pre-commit/issues/2282) and wrote a VSCode extension for handling hook execution. The extension can run hook individually, so that I know in advance, which problem matcher to use for which hook.

I separate hooks into fixes (these change files, like formatters) and checks (which don't), but I know that this is currently [not a good way to do it, and can be dangerous](https://github.com/pre-commit/pre-commit/issues/1564). Thus, I would like to return to running pre-commit just once, including all of its hooks.

However, matching against the pre-commit output in CI or locally is not easy, because individual hook outputs don't include the hook name. The hook's id is only provided once in the beginning, but not at the end.

### Suggestion

Provide the hook id also at the end of the hook output.

```bash
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1

Files were modified by this hook. Additional output:

Fixing sample.py

- end hook id: trailing-whitespace # Add something like this
black....................................................................Passed
```

This would be similar to how watch tasks notify the user (or parser) of new output, for example like `ts-lint`:
```
12:32:35 PM - File change detected. Starting incremental compilation...
src/messages.ts(276,9): error TS2304: Cannot find name 'candidate'.
12:32:35 PM - Compilation complete. Watching for file changes.
```

`pre-commit` could then be called with something like a `--parseable` option.

This way of doing it is supported by IDEs that know how to parse watcher outputs, including VSCode. They require an opening match (e.g. `- hook id: trailing-whitespace`) as well as a closing match (then, `- end hook id: trailing-whitespace`).

Would you be willing to include such a change?

**Comment by asottile** [comment]
there are several duplicates -- the intended mechanism is via [`log_file`](https://pre-commit.com/#config-log_file)

**Comment by elagil** [comment]
I see, thanks!
