### ISSUE TITLE
using pre-commit install from WSL

### ISSUE THREAD

**Issue by qci-amos** [pre-commit/pre-commit#2371]
### describe your issue

I'm wanting to `pre-commit install` from my WSL.

Normally, I use `conda`, but I seem to be hitting some issue with https://github.com/pre-commit/pre-commit/issues/1329 . The solution seems to be to upgrade to py 3.9, but I'm stuck on 3.8 for the near term.

So then I tried to make a `virtualenv`, which all seems fine, from my terminal:
```
$ which python
/mnt/c/Users/me/Documents/venv/bin/python
```

If I run the hook in isolation it seems ok::
```
$ .git/hooks/pre-commit
Trim Trailing Whitespace.............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
autoflake............................................(no files to check)Skipped
isort................................................(no files to check)Skipped
black................................................(no files to check)Skipped
black-jupyter........................................(no files to check)Skipped
```

however, when I run from `git`, it isn't:
```
$ git commit -m "removed old files" .
`pre-commit` not found.  Did you forget to activate your virtualenv?
```

The `pre-commit` script was initialized to have this:
```
INSTALL_PYTHON=/mnt/c/Users/me/Documents/venv/bin/python
```
however, `-x` evaluates to false for that when I run from `git`.

If I `ls` the directory, I see:
```
ls -lrt c:/Users/me/Documents/venv/bin
```

```
total 37
lrwxrwxrwx 1 me 1049089   15 May  3 12:18 python -> /usr/bin/python
lrwxrwxrwx 1 me 1049089    6 May  3 12:18 python3 -> python
-rwxr-xr-x 1 me 1049089  262 May  3 12:18 easy_install
-rwxr-xr-x 1 me 1049089  262 May  3 12:18 easy_install-3.8
-rwxr-xr-x 1 me 1049089  253 May  3 12:18 pip
-rwxr-xr-x 1 me 1049089  253 May  3 12:18 pip3
-rwxr-xr-x 1 me 1049089  253 May  3 12:18 pip3.8
-rw-r--r-- 1 me 1049089 8834 May  3 12:18 Activate.ps1
-rw-r--r-- 1 me 1049089 2196 May  3 12:18 activate
-rw-r--r-- 1 me 1049089 1248 May  3 12:18 activate.csh
-rw-r--r-- 1 me 1049089 2400 May  3 12:18 activate.fish
-rwxr-xr-x 1 me 1049089  270 May  3 12:20 virtualenv
-rwxr-xr-x 1 me 1049089  238 May  3 12:20 nodeenv
-rwxr-xr-x 1 me 1049089  243 May  3 12:20 identify-cli
-rwxr-xr-x 1 me 1049089  246 May  3 12:20 pre-commit
-rwxr-xr-x 1 me 1049089  283 May  3 12:20 pre-commit-validate-config
-rwxr-xr-x 1 me 1049089  287 May  3 12:20 pre-commit-validate-manifest
-rwxr-xr-x 1 me 1049089  252 May  3 12:21 black
-rwxr-xr-x 1 me 1049089  253 May  3 12:21 blackd
```

I tried some different path styles, but none seemed to work:
```
#INSTALL_PYTHON=/mnt/c/Users/me/Documents/venv/bin/python
#INSTALL_PYTHON=C:/Users/me/Documents/venv/bin/python
#INSTALL_PYTHON=C:\\Users\\me\\Documents\\venv\\bin\\python
INSTALL_PYTHON=/c/Users/me/Documents/venv/bin/python
```

so then I thought I'd try this:
```
export PATH=/c/Users/me/Documents/venv/bin:$PATH
INSTALL_PYTHON=python
which python
```
but then it's not finding the right python.

... and now I'm running into the limits of how well I understand scripting in Windows...

So I'm not sure what the problem is (other than my ignorance about Windows!), but it seems possible that `pre-commit install` could detect whatever variant I'm running into and create an appropriate `pre-commit` file in my git.

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
    -   id: black-jupyter
```

**Comment by asottile** [comment]
can you show the output of `pre-commit install`?  there's supposed to be a warning which says that this configuration is unsupported (you're mixing the host python and the VM python and/or you're mixing cygwin python and windows git)

you basically need to be using (windows git + windows python) or (WSL git + WSL python) or (cygwin git + cygwin python) but you've got a mismatch mix of the three

**Comment by qci-amos** [comment]
```
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
$ cat .git/hooks/pre-commit
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/mnt/c/Users/me/Documents/venv/bin/python
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
$ git commit
`pre-commit` not found.  Did you forget to activate your virtualenv?
```

**Comment by asottile** [comment]
ok that looks like a linux python at the least (a windows python would use a `#!/bin/sh` shebang for "annoying" reasons) -- are you calling `git` from your host machine?

**Comment by qci-amos** [comment]
lol, I have this in my `.bash_aliases`:

```
# https://markentier.tech/posts/2020/10/faster-git-under-wsl2/#solution
# use Windows' git when working under C:\ drive
function git() {
  if $(pwd -P | grep -q "^\/mnt\/c\/*"); then
    git.exe "$@"
  else
    command git "$@"
  fi
}
```
I'm guessing that's getting in the way!

**Comment by asottile** [comment]
that would certainly be the problem!

**Comment by qci-amos** [comment]
ok, thanks for talking me through this! the solution is pretty simple: run `pre-commit install` from my git bash shell (i.e., windows bash), and then that `pre-commit` file works in both WSL and git bash.

**Comment by qci-amos** [comment]
(and I don't seem to need my venv...)

**Comment by tuxerrante** [comment]
unlickily it didn't work for me.
I'm on Win11 and I use Git Bash and WSL from VSCode.

Installing pre-commit through pip as the docs suggest in GitBash result in a PATH error, which I've fixed adding `/c/Users/USER/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/Scripts` to the .bashrc PATH.

After this I get 
```pre-commit install
[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
 ```

So I've run `git config --global --unset-all core.hooksPath` since I had set them globally, and re-run it.
Now I'm able to run it from Docker and from GitBash but not from WSL.

So to make it work from both sides I've replaced the `elif` branch exec command with the docker run:
```bash
if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    TAG=latest
    exec docker run -e "USERID=$(id -u):$(id -g)" -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run 
else
    echo '`pre-commit` not found.' 1>&2
    exit 1
fi
```

Instead this is what I get from WSL:
```
[13:12:24] ➜ pre-commit run --all-files
trim trailing whitespace.................................................Passed
check yaml...............................................................Passed
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 2

: invalid option name/pre-commit/repozjxdpqro/hooks/terraform_fmt.sh: line 2: set: pipefail
```

Environment:
- Python 3.10.12
- Linux 5.15.133.1-microsoft-standard-WSL2 x86_64
- Terraform v1.7.5 on linux_amd64
- pre-commit 3.7.0
- Microsoft Windows 11 Enterprise

**Comment by asottile** [comment]
wsl is not magic for running windows executables on Linux.  if you're in a Linux environment you'll need a Linux install of pre-commit and conversely if you're on Windows you need a Windows install of pre-commit

the install from Windows can't be used inside wsl and the install inside wsl will not work on Windows

**Comment by tuxerrante** [comment]
> wsl is not magic for running windows executables on Linux. if you're in a Linux environment you'll need a Linux install of pre-commit and conversely if you're on Windows you need a Windows install of pre-commit
> 
> the install from Windows can't be used inside wsl and the install inside wsl will not work on Windows

indeed I've installed it from WSL2 pip command and run it from `~/.local/bin/pre-commit`
