### ISSUE TITLE
Create a Docker image for this application

### ISSUE THREAD

**Issue by aanzolaavila** [pre-commit/pre-commit#2377]
Hi y'all,

I'm interested in including this as part of our git hooks, but as for the general process, I prefer to leave everything without any hard dependencies on packages installed on the machine and in the general case leave it as a container execution that just shares volumes to apply those changes.

**Comment by asottile** [comment]
please search the issue tracker

**Comment by aanzolaavila** [comment]
I just have, but I don't see anything related to creating a docker image (in DockerHub) for example to execute this, is there?

**Comment by asottile** [comment]
ok I'll link the duplicates then, -- I searched for "docker image" and "official docker image" -- #1798 #1323
