### ISSUE TITLE
pre-commit install-hooks should run without git tree

### ISSUE THREAD

**Issue by cdleonard** [pre-commit/pre-commit#2378]
### search tried in the issue tracker

install-hooks

### describe your issue

I want to build a docker container in which pre-commit hooks are already installed but running `pre-commit install-hooks -c .pre-commit-config.yaml` fails: `An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?`

There are various workarounds such as copying the .git directory inside the container or creating a temporary git repo but I think it's useful to just allow `install-hooks` to work with just a config file

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
```

### ~/.cache/pre-commit/pre-commit.log (if present)
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /root/.cache/pre-commit/pre-commit.log
### version information

```
pre-commit version: 2.19.0
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/git.py", line 58, in get_root
    cmd_output('git', 'rev-parse', '--show-cdup')[1].strip(),
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/util.py", line 152, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'rev-parse', '--show-cdup')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: not a git repository (or any of the parent directories): .git


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 344, in main
    _adjust_args_and_chdir(args)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 147, in _adjust_args_and_chdir
    toplevel = git.get_root()
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/git.py", line 64, in get_root
    raise FatalError(
pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

**Comment by cdleonard** [comment]
You closed the PR claiming "pre-commit needs git to locate the tools:" but all it really needs is a `.pre-commit-config.yaml` file, it does not need a git working directory.

Issue #1722 is about running pre-commit without a git working directory but all I want is to install the tools and cache them inside a docker layer because they very rarely change. The run step will happen with a real working directory.

As far as I understand the directories inside `~/.cache/pre-commit` can already be shared between projects (if using the same version of a hook) so hook installation can't depend on anything inside the git working directory other than the `.pre-commit-config.yaml` file.

The patch as written actually solves the problem for me. What am I missing?

**Comment by asottile** [comment]
your patch breaks functionality and `pre-commit` is not intended to be used that way.  you need to have a git repo to have a consistent discovery of the configuration file.  for your case you can use a trivial `git init`

**Comment by cdleonard** [comment]
What functionality does it break? As far as I can tell the git working directory is not used by the `install-hooks` step. If it was used then it would likely misbehave when hooks are shared between projects so should be considered a bug.

The configuration file can be discovered consistently with the -c argument but "current directory" is also fine. I tried to run `pre-commit install-hooks` from a subdirectory and it did not find the config file in the parent so it doesn't appear to base it this on the git working directory.

Several subcommands like `validate-config` are already supported without a git working directory and I think it's useful to also support `install-hooks`.

I only tried very simple hooks, is there some way for installation to depend on stuff outside `.pre-commit-config.yaml`?

**Comment by asottile** [comment]
I showed you exactly what it breaks in your PR -- try that before and after your patch

**Comment by cdleonard** [comment]
Sorry I missed that.

What if I made a new PR which only makes `pre-commit install-hooks -c` work without a git working directory, would that be acceptable?

**Comment by asottile** [comment]
no thanks, I have no intention to carry such complexity

**Comment by cdleonard** [comment]
Fair enough, I'll use temporary git repos.

**Comment by kovaacs** [comment]
It's quite unfortunate. Ideally, I'd like to run all the hooks on all files without needing Git at all. Since it's not even installed in the Docker image, I'd have to install it just to meet this dependency.

**Comment by asottile** [comment]
scroll up and read
