### ISSUE TITLE
No colors output text

### ISSUE THREAD

**Issue by Pirols** [pre-commit/pre-commit#2380]
### search tried in the issue tracker

alacritty, color

### describe your issue

I have just found out this amazing project and was testing it out on my system.

The issue I encountered concerns coloring in that, as explained [here](https://github.com/pre-commit/pre-commit/issues/2325#issuecomment-1086977606), I would've expected the output to be highlighted as defined in my [terminal](https://github.com/alacritty/alacritty) configuration and got just black and white text instead.

I tried running pre-commit install --color always and setting PRE_COMMIT_COLOR=always to no avail.

As you can see in the following image other commands follow my colorscheme.

![image](https://user-images.githubusercontent.com/36996537/167178828-e67dffb0-7676-4fde-b67a-565d74d48e4e.png)

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
```

**Comment by asottile** [comment]
dupe #2356
