### ISSUE TITLE
Idea: support a way to execute a command in a repo environment

### ISSUE THREAD

**Issue by uSpike** [pre-commit/pre-commit#2382]
I'd find it very useful to have a way to run an arbitrary command in the environment created for a repo.  For example, I use https://github.com/flakeheaven/flakeheaven in my pre-commit configuration.  This package has a number of command-line tools that can be necessary when adding plugins or understanding error codes.  But, when I use flakeheaven as a pre-commit repo I cannot (easily) run the `flakeheaven` command.  I've resorted to installing `flakeheaven` as a `requirements-dev.txt` dependency and using flakeheaven as a local pre-commit hook.

My suggestion would be to add a pre-commit command such as `pre-commit env <env_name> <command>`.  In my example, this could be `pre-commit env <env_name> flakeheaven codes` which translates to executing `~/.cache/pre-commit/repo880l2mpz/py_env-python3.9/bin/flakeheaven codes`

I think a tricky bit might be determining what `<env_name>` is since these aren't easily discoverable.

**Comment by asottile** [comment]
the envs are intentionally not exposed. when they were in the past people messed with the internals and wasted a lot of my time

the intended mechanism for what you're describing is `manual`

but note that pre-commit is intentionally not a generic execution engine

also note that flakeheaven is misusing private interfaces of flake8 and will break -- I'm sure you're also aware that it's forked from a hostile maintainer that ripped off my code and violated my license

though that is neither here nor there

**Comment by asottile** [comment]
there's a bunch of duplicates in the tracker, in the future please use the issue template which prompts you to search first

**Comment by uSpike** [comment]
Thanks, I did not use the issue template because it was labeled for bugs, and this is not a bug. I did search and could not find a related issue.

I wasn't aware of this other malpractice around the afformentioned project, I only brought it up as an example use case.
