### ISSUE TITLE
Add support for TypeScript check (tsc)

### ISSUE THREAD

**Issue by mohsentaleb** [pre-commit/pre-commit#2396]
I needed to add `tsc` to my project's pre commit hook but realized you don't support it at the moment.
I [made one myself](https://github.com/mohsentaleb/precommit-tsc) according to your [https://pre-commit.com/#new-hooks](guides).

Was wondering if I should keep it as my own private repo or should I send a PR?

**Comment by asottile** [comment]
tsc is far too slow to fit nicely  your contributors will likely be frustrated with such a hook and turn it off entirely.  also please don't use "pre-commit" in your naming as you are not associated with the project

there's a few dupes in pre-commit/pre-commit.com
