### ISSUE TITLE
Exclude option feature requests/changes

### ISSUE THREAD

**Issue by AceofSpades5757** [pre-commit/pre-commit#2400]
When making adjustments to the `exclude` option, I intuitively thought this matched on a glob pattern. Also, when trying to create more than one I thought to use an array rather than a lengthy Python regex pattern.

For the glob, I think most tools in similar situations would use this. These types of patterns are also more accepted compared to specifically Python's regex.

For the array, I think it would be a lot more flexible and intuitive if it could also support an array of patterns, or just an array to begin with.

**Comment by asottile** [comment]
https://pre-commit.com/#regular-expressions

**Comment by asottile** [comment]
please also search the issue tracker, at least one dupe: #149
