### ISSUE TITLE
Error message: .pre-commit-config.yaml is not a file

### ISSUE THREAD

**Issue by andreas-vester** [pre-commit/pre-commit#2401]
### search tried in the issue tracker

Couldn't find a solution

### describe your issue

I installed pre-commit and auto-generated the example config file like this:

`pre-commit sample-config > .pre.commit-config.yaml`

I then subsequently wanted to check all files via

`pre-commit run --all-files`

This resulted in the following error:
```
An error has occurred: InvalidConfigError:
=====> .pre-commit-config.yaml is not a file
Check the log at C:\Users\andre\.cache\pre-commit\pre-commit.log
```

I am using Windows, by the way.

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.34.1.windows.1
sys.version:
    3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\andre\SynologyDrive\coding\df2img\.venv\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

```
Traceback (most recent call last):
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\pre_commit\main.py", line 389, in main
    return run(args.config, store, args)
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\pre_commit\commands\run.py", line 398, in run
    config = load_config(config_file)
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\cfgv.py", line 394, in load_from_filename
    with reraise_as(exc_tp):
  File "C:\Users\andre\.pyenv\pyenv-win\versions\3.10.4\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "C:\Users\andre\SynologyDrive\coding\df2img\.venv\lib\site-packages\cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

**Comment by asottile** [comment]
the error message is not wrong, you have a typo

**Comment by Murtagy** [comment]
This is not informative error message and not informative answer.

**Comment by asottile** [comment]
@Murtagy could you explain what's different to you between:

```
{path} is not a file
```

and

```
the file does not exist at {path}
```

**Comment by asottile** [comment]
and in case it's not clear, OP made a typo, compare:

```
pre-commit sample-config > .pre.commit-config.yaml
pre-commit sample-config > .pre-commit-config.yaml
```

**Comment by Murtagy** [comment]
> @Murtagy could you explain what's different to you between:
> 
> ```
> {path} is not a file
> ```
> 
> and
> 
> ```
> the file does not exist at {path}
> ```

My error:
I copied a config from my existing project, but accidentally placed it into a subfolder.
As far as I was pretty sure that the file indeed exists, I understood the error message as a "Config file validation error", in other words I suspected that the file is there, but there is an error in file content. 

 It is very  error.

**Comment by Murtagy** [comment]
It is clearly a rare error and has some hints for what went wrong. 
I just was too angry on myself that I spent 20+ minutes trying to figure our what went wrong, so I am mentally more comfortable to blame the error message 😄 .

**Comment by asottile** [comment]
sounds like you just didn't read the error message and assumed you were smarter than the tool

the error message already contains the path so you should have checked there
