### ISSUE TITLE
Relationship between `stages` and `hook-type`

### ISSUE THREAD

**Issue by Andreagit97** [pre-commit/pre-commit#2418]
### search tried in the issue tracker

-

### describe your issue

Hi folks! First of all thanks for the amazing project! I just want to ask a simple question to check If I understood correctly :) 
If I run `pre-commit install --hook-type pre-commit` I will install all hooks with `stages: [commit]` (and obviously `stages: [all]`), is this correct? 
I ask it because looking at possible `stages` values, i found: 
* `commit`
* `merge-commit`
* `push`
* `prepare-commit-msg`
*  `commit-msg` 
*  `post-checkout` 
* `post-commit` 
* `post-merge`
* `post-rewrite`
* `manual`

Since the `--hook-type` search for `pre-commit` I would expect a `pre-commit` stage however I found only the `commit` one. Same thing for `merge-commit` stage instead of `pre-merge-commit` and `push` stage instead of `pre-push`. Maybe this has been done to avoid collisions with the project name `pre-commit`, this is just my guess. Anyway, I would only be sure that when I call `pre-commit install --hook-type pre-commit` only hooks with `stages: [commit]` will be installed (and obviously all hooks with `stages:[all]` if I have not overridden the default behavior). 

Thank you very much for your time.

### pre-commit --version

-

### .pre-commit-config.yaml

```yaml
-
```

### ~/.cache/pre-commit/pre-commit.log (if present)

-

**Comment by asottile** [comment]
yes they unfortunately mismatch for pre-commit and pre-push because those were the first ones

there's no such stage all

this is all in the docs https://pre-commit.com

**Comment by Andreagit97** [comment]
> yes they unfortunately mismatch for pre-commit and pre-push because those were the first ones
> 
> there's no such stage all
> 
> this is all in the docs https://pre-commit.com

Thank you very much for the quick answer!
