### ISSUE TITLE
Private hook repo authentication issue

### ISSUE THREAD

**Issue by nbjohnson** [pre-commit/pre-commit#2420]
What is the expected method to be able to properly pass git authentication to pull hooks from a private repository? I have my git token stored in the env var GIT_API_KEY which works fine to pull all of my other repos through git, however when pre-commit tries to pull the hook it doesn't seem to recognize this env var and just asks for a user password.

What is the expected way/setting to allow me to use my GIT_API_KEY env var for private repo authentication in the hook pull step?

**Comment by asottile** [comment]
variables (minus a few allowlisted) starting with `GIT_` are purged from the environment because `git` does not handle its own internal state well during `git` hooks: https://github.com/pre-commit/pre-commit/blob/4738d06e71edecb2e07ad8d8ea5fd1ea2e44cd3a/pre_commit/git.py#L27-L48

**Comment by nbjohnson** [comment]
@asottile Thanks for the quick response. I would very much like to be able to authenticate with private git repositories, so could a change be implemented? Either:

1. Adding `GIT_API_KEY` to the allowlist of git env vars as I do see other env vars have been added in the past (ex GIT_HTTP_PROXY_AUTHMETHOD)
OR
2. A config option that would append to the allowlist for users to manually override what env vars get purged so in the future users don't have to request env vars being added to the allowlist while also not impacting other user implementations
OR
Other potential solutions
