### ISSUE TITLE
Loss of changes.

### ISSUE THREAD

**Issue by paul-english** [pre-commit/pre-commit#2425]
### search tried in the issue tracker

yes

### describe your issue

https://github.com/pre-commit/pre-commit/issues/176
https://github.com/pre-commit/pre-commit/issues/397

I think I just experienced a case of lost work due to this program. I think I'll be uninstalling it unless I can be directed to some test case that attempts to ensure or verify that issues like these reported cannot occur. It might be good to allow these issues to be merged or reopened so that tracking the regression here is easier.

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
n/a
```

### ~/.cache/pre-commit/pre-commit.log (if present)

...
    error: ... patch does not apply
...

**Comment by paul-english** [comment]
No, it's the same issue, I'm saying that your program should verify that no loss of data can occur. Regardless of the code path that caused it.

**Comment by asottile** [comment]
I can assure you it is not -- there are tests in place which ensure the behaviours experienced are not happening: https://github.com/pre-commit/pre-commit/commit/0479f78b4dd4ae9ad9a402818ff53034aa6cf52e https://github.com/pre-commit/pre-commit/commit/b05cc4077e621cec637b22d6ad2b80ee84749f97

please provide more information, thanks!

**Comment by paul-english** [comment]
Thanks, do you have a formal verification of that? https://en.wikipedia.org/wiki/Formal_methods Something that ensures your execution model can't use git in a way that causes data loss?

**Comment by asottile** [comment]
yes

**Comment by paul-english** [comment]
For what versions of pre-commit?

**Comment by asottile** [comment]
yes

**Comment by paul-english** [comment]
Like I said, I just experienced data loss under normal use of pre-commit 2.18.1

**Comment by asottile** [comment]
show me some information so I can help you

**Comment by asottile** [comment]
start with the template, but also the output and any other relevant information

**Comment by paul-english** [comment]
It looks like it's the same issue as #176 and at least #397. Has _anyone_ else experienced data loss and reported it too you? There may have been differing execution contexts that led to the end behavior, however if you say that these are "different" then maybe there's a higher level architecture or execution model to blame. Which is why I'd recommend a formal method for verifying behavior here. The key here is that if there's at least two previous instances of data loss, then the approach of solving it as a contextual based situation maybe isn't correct. You shouldn't need much more information than that, this should be a fundamental property of your software that it's use, can't misplace data. If you're 100% certain of that, then maybe it's a bug in git itself, but I suspect git is relatively well tested.

**Comment by asottile** [comment]
show me your output and your log file or I'm going to ban you.  I don't have the patience for your disrespect.

**Comment by paul-english** [comment]
Thanks, I will always recommend people uninstall this tool.
