### ISSUE TITLE
[question] How to pass login/password to git hook?

### ISSUE THREAD

**Issue by Niccolum** [pre-commit/pre-commit#2431]
### search tried in the issue tracker

Not found

### describe your issue

I search in the docs of pre-commit tool and can't find any answers.
For example, I have private repo with my hooks, which I want to include to another private repo. (Gerrit, in my case). Is it possible?

### pre-commit --version

Any

### .pre-commit-config.yaml

```yaml
Any
```

**Comment by asottile** [comment]
what have you tried so far? I can't really help if you haven't shown what isn't working

pre-commit runs code so anything is possible

**Comment by Niccolum** [comment]
Hm, okay. I'm not trying yet, I'll create new issue after that.
If it possible, before closing issue, can you answer - how to pass login/password to git hooks, but not passed it manually in url or config (https://user:password@remote.git).

**Comment by asottile** [comment]
I recommend trying things first and then when you're stuck only then ask for help, especially because you're doing it for work and your work is not sponsoring the project and you're essentially asking me to spend my free time for free to solve your problems
