### ISSUE TITLE
No way to tell pre-commit to run isolated on commit

### ISSUE THREAD

**Issue by nextstate** [pre-commit/pre-commit#2432]
# Description
My team uses a pip.ini that points to internal feeds, which requires authentication. We have packages that handle the authentication automatically whenever we do a `pip install`. The authentication packages are on `pypi.org` and we have to install them with `pip install --isolated ...`. Once installed and authenticated we don't have to deal with that again.

We create the `.pre-commit-config.yaml`, run `pre-commit install`, then run `git commit ...`

The issue comes when `pre-commit` installs the packages in the `.pre-commit-config.yaml`. It installs them into a separate env. When it tries to install the packages, it uses our `pip.ini` and fails because the authentication packages have not been installed in the environment.

# Proposed Solution
If `pre-commit` could be told to `pip install --isolated`, this would solve the issue. A flag could be set in `.pre-commit-config.yaml` that would tell `pre-commit` to run `pip` isolated.

# Workarounds
Right now, each developer has their own set of hoops to jump through to workaround this issue. Some developers just bypass the problem by not using `pre-commit` locally and letting the build pipeline fail if `pre-commit` reports any violations.

**Comment by asottile** [comment]
you can also pass `additional_dependencies: [--isolated]` to influence pip's flags if you want to do it that way instead
