### ISSUE TITLE
Changing default config location for pre-commit run

### ISSUE THREAD

**Issue by aalbaali** [pre-commit/pre-commit#2449]
I'm storing a `.pre-commit-config.yaml` file in a subdirectory, which can be passed to `pre-commit install` by using the `--config` option (i.e.,  `pre-commit install --config path_to_config.yaml`). However, after installing pre-commit, I still need to add the `--config` (or `-c`) option whenever I *run* pre-commit on some files (i.e., `pre-commit run ...` would *not* work, but `pre-commit run -c path_to_config.yaml` works).

Would it be possible to use the config file passed when installing/configuring pre-commit (i.e., `pre-commit install -c path_to_config.yaml` )whenever running `pre-commit run` within the same repo?

**Comment by asottile** [comment]
the only supported location is at the root of the repository (where git hooks always run from) -- otherwise you need to use the `--config` option
