### ISSUE TITLE
pre-commit base directory is git root instead of directory contains .pre-commit-config.yaml

### ISSUE THREAD

**Issue by alonbl** [pre-commit/pre-commit#2452]
### search tried in the issue tracker

is:issue git directory base 

### describe your issue

Hello,

I have a git repo which is structured as:

 * java/...
 * python/...

I would like to use the pre-commit on the python directory and not the java.
I put `.pre-commit-config.yaml` at the python directory.
I go to the python directory and run tox which runs `pre-commit run --all-files`

The pre-commit hook reads the`.pre-commit-config.yaml` file within the python directory, however, the tests are made relative to the git root instead of my expectation of being relative to the `.pre-commit-config.yaml` configuration file (and the directory that it is invoked).

Can you please consider supporting nested directories? I am unsure why the git root plays a part. If you would like to have this as default, please consider a configuration setting or a parameter to the run command to override and run relative to the execution working directory.

Thanks!

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
Not relevant.
```

**Comment by asottile** [comment]
git hooks always run from the root of the repository

**Comment by alonbl** [comment]
Hello @asottile

git hooks can run scripts from any other directory, including the pre-commit, not sure why is how git-hooks run relates to how I ran validations from the git-hooks.

I also unsure why the pre-commit is tightly coupled with git (unless explicit tests require) I see there were several discussions of this in the past.

pre-commit != git-hooks
git-hooks MAY USE pre-commit in a customized configuration (cwd, environment, parameters)

If we assume that pre-commit == git-hooks, it should read the configuration out of the git root and not current directory.

Either way there is probably a bug of inconsistency.

Thanks,

**Comment by asottile** [comment]
pre-commit only operates on git -- there's a ton of dupes if you want to search the tracker -- most of them either mention "directory" or "monorepo" but this is not changing

git only has one set of git hooks per repository, and they always run from the root of the repository.  there's not really any meaning to having multiple pre-commit configurations per repository because you can only have one set of hooks
