### ISSUE TITLE
ansible-lint python package gets installed incorrectly

### ISSUE THREAD

**Issue by GarrisonD** [pre-commit/pre-commit#2458]
### search tried in the issue tracker

python

### describe your issue

I use `pre-commit` to run `ansible-lint` hook but the incorrect version is being installed.

Start a sandbox:

```sh
docker run --rm -it -v $(pwd)/.pre-commit-config.yaml:/.pre-commit-config.yaml mcr.microsoft.com/vscode/devcontainers/python:3.10 bash
```

Inside the sandbox:

```sh
git init
pip install pre-commit
pre-commit run -a -v
```

Actual result:

`pre-commit` installs **0.1.dev1** of `ansible-lint`

```
[INFO] Initializing environment for https://github.com/ansible/ansible-lint.
[INFO] Initializing environment for https://github.com/ansible/ansible-lint:.[community].
[INFO] Installing environment for https://github.com/ansible/ansible-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Ansible-lint.............................................................Passed
- hook id: ansible-lint
- duration: 0.8s

ansible-lint 0.1.dev1 using ansible 2.13.1
```

Expected result:

`pre-commit` installs **v6.3.0** of `ansible-lint`

---

In docs, it's said that `pre-commit` runs `pip install .` in the cloned repo.

When I do this manually, `ansible-lint` is **v6.x.x**:

```sh
git clone -b v6.3.0 https://github.com/ansible/ansible-lint
cd ansible-lint
pip install .
ansible-lint --version # ansible-lint 6.3.0 using ansible 2.13.1
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.3.0
    hooks:
      - id: ansible-lint
        args: [--version]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

cat: /root/.cache/pre-commit/pre-commit.log: No such file or directory

**Comment by asottile** [comment]
that version is the setuptools-scm fallback version so you probably want to report there instead

**Comment by asottile** [comment]
a better search term for the future would be "0.1.dev1" rather than "python" (did you actually expect to find something with that?) -- there's several exact duplicates

**Comment by GarrisonD** [comment]
I didn't know that `0.1.dev1` is so special that can be a search keyword 🙂

**Comment by GarrisonD** [comment]
Do all the Python hooks have this dumb version?

Can't up-/downgrading the version of `setuptools-scm` help with that?

**Comment by asottile** [comment]
I don't know, I don't maintain setuptools-scm and it isn't part of pre-commit so I cannot help you sorry
