### ISSUE TITLE
post-merge doesn't seem to find files to check

### ISSUE THREAD

**Issue by jangroth** [pre-commit/pre-commit#2461]
### search tried in the issue tracker

yes. a lot.

### describe your issue

I want to trigger a custom commit hook on post merge, ideally with a list of of incoming file changes.

Custom hook config:

```
-   id: run-pbi-tools-post-merge
    name: pbi-tools compile (post merge)
    description: invoke pbi-tools to compile powerbi proj-folders into reports
    entry: run-pbi-tools-post-merge
    language: python
    files: ''                   # all files
    require_serial: true        # no parallel invocation
    verbose: true
    stages: [post-merge]
```
Client-side repo config:

```
repos:
- [...]
-   repo: https://github.com/myorg/precommit_hooks
    rev: 0.1.3
    hooks:
    -   id: run-pbi-tools-post-merge
```
I've installed pre-commit for post-merge (`pre-commit install -t post-merge`), however pre-commit isn't invoking the hook:

```
git pull
Updating 87c6d50..f51cb2a
Fast-forward
 trigger.txt | Bin 0 -> 82 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 trigger.txt
pbi-tools compile (post merge).......................(no files to check)Skipped
- hook id: run-pbi-tools-post-merge
```
I would expect the hook to be invoked for `trigger.txt`.

I'm getting  similar output when manually invoking the hook for trigger.txt:
```
pre-commit run --verbose --hook-stage post-merge --files trigger.txt
pbi-tools compile (post merge).......................(no files to check)Skipped
- hook id: run-pbi-tools-post-merge
```
... or for all files:
```
pre-commit run --verbose --all-files --hook-stage post-merge
pbi-tools compile (post merge).......................(no files to check)Skipped
- hook id: run-pbi-tools-post-merge
```

Is this a misconception on my end? My use case is running a script _on pull_ to restore meta-data that was split up _on commit_. Maybe someone could point me towards an example that does something similar? So far I haven't been able to find any.

### pre-commit --version

2.20.0 (running on Windows)

### .pre-commit-config.yaml

```yaml
repos:
- [...]
-   repo: https://github.com/myorg/precommit_hooks
    rev: 0.1.3
    hooks:
    -   id: run-pbi-tools-post-merge
```

### ~/.cache/pre-commit/pre-commit.log (if present)

./.

**Comment by asottile** [comment]
did you read the section on post-merge in the docs?

**Comment by asottile** [comment]
ah nope I was referring to [this section](https://pre-commit.com/index.html#pre-commit-during-merges) about `post-merge` -- seems it is missing the same disclaimer that's present on other hooks which do not operate on files [such as this one](https://pre-commit.com/index.html#pre-commit-for-switching-branches)

> Which brings me to the point of my comment - why are you being so arrogant and rude in your answer?

I don't know where you're deriving arrogance or rudeness -- perhaps you're misinterpreting brevity for tone?

>  I have spent days on the documentation, and have used plenty of my own trying to make this work.

and now you're insulting me and demanding my free time -- maybe have your company consider sponsoring the work instead of demanding free support.

and maybe my first inkling was wrong -- that you didn't read the docs (because you also didn't read which repository you were reporting it to and reported it in the wrong place twice) -- and I'm sorry for assuming that.  but you also need to have some realistic expectations about open source -- you get what you pay for and if you're going to throw a tantrum because you didn't fill out the issue template and I pointed you at the docs then idk what to tell you.

**Comment by jangroth** [comment]
Hi @asottile - thanks for getting back to me. 

Let me make myself clear: I think pre-commit is great and I very much appreciate your work. Also, I understand that you are running this in your own time and I have zero expectation for you to sacrifice your time beyond what you are willing to spend on this project.

Maybe in turn you can understand that I spend days working with & learning the framework already. Only last week I moved to the `post-merge` bit of my work and yes, I misunderstood the relevance of the paragraph you pointed me to. I also made an honest effort to solve the problem without having to post an issue here, including spending hours here and on SoF. So yes, 'RTFM' wasn't the answer I was hoping for. There might also be a little bit of cultural differences in the mix, what you consider 'brevity' is a  solid 8/10 'rudeness' in German :-) 

However, all good from my end, and as I said, I really appreciate your work here.

---

> My use case is running a script on pull to restore meta-data that was split up on commit.

Just confirming my understanding: This is _not_ possible with `pre-commit`, as we cannot invoke a hook on _every_ pull, correct?

**Comment by jangroth** [comment]
Update for future readers that might search for issues with `post_merge`:

This hook can be invoked _without_ file names being submitted by configuring `always_run: true` in `.pre-commit-config.yaml`

```
git pull
Updating 25d7641..629438c
Fast-forward
 trigger.txt | Bin 0 -> 82 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 trigger.txt
pbi-tools compile (post merge)...........................................Passed
- hook id: run-pbi-tools-post-merge
- duration: 0.62s

2022-07-19 09:20:43,820 run_pbi_tools DEBUG Invoking post_merge_handler with Namespace(filenames=[])
```

**Comment by hugochinchilla** [comment]
The docs still have missing a note about this, the ticket should not be closed until the docs are updated.
