### ISSUE TITLE
stuck in [INFO] Initializing environment for git@github.com:realm/SwiftLint.git.

### ISSUE THREAD

**Issue by suddenly1990** [pre-commit/pre-commit#2463]
### search tried in the issue tracker

no find

### describe your issue

I use pre-commit in iOS project。
when I use git commit -m 'test' in terminal。
it's hold on：
in [INFO] Initializing environment for git@github.com:realm/SwiftLint.git. 
and no response.
```
➜  precommit git:(main) ✗ git commit -m 'test'
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/baisheng/.cache/pre-commit/patch1658393187-5306.
[INFO] Initializing environment for git@github.com:realm/SwiftLint.git.
```

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: git@github.com:realm/SwiftLint.git
    rev: v0.47.0
    hooks:
    -   id: swiftlint
-   repo: git@github.com:pocc/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
    -   id: oclint
```

**Comment by suddenly1990** [comment]
I use pre-commit pre-commit autoupdate.
it's ok for stuck.but I have other error:
`[INFO] Installing environment for git@github.com:realm/SwiftLint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /Users/baisheng/.cache/pre-commit/patch1658395992-27817.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/swift', 'build', '-C', '/Users/***/.cache/pre-commit/repo3d4eiei0', '-c', 'release', '--build-path', '/Users/***/.cache/pre-commit/repo3d4eiei0/swift_env-default/.build')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    warning: '--chdir/-C' option is deprecated; use '--package-path' instead
    error: terminated(72): xcrun --sdk macosx --find xctest output:
        xcrun: error: unable to find utility "xctest", not a developer tool or in PATH`

**Comment by asottile** [comment]
swiftlint legitimately takes a long time to build, it's not stuck afaik. the other error isn't a pre-commit problem
