### ISSUE TITLE
Is there any way to have a global, default config?

### ISSUE THREAD

**Issue by bplaxco** [pre-commit/pre-commit#2470]
Hello :wave: 

I picked through the docs and the code and I didn't see the option, so I just wanted to ask:

Is there a way to have a global, default config that can be merged with the repo's config if it exists?

My use case for context:

I have a pre-commit check that requires api credentials to be set up and a lot of folks that will be using it will also be contributing to OpenSource projects where the check shouldn't be enabled for other contributors in a .pre-commit-config.yaml in the project.

It would be really nifty if:

1. The tool checks for a `~/.config/pre-commit/config.yaml` (or managed by some config opt in your git config)
2. If it exists load it
3. Checks for a `.pre-commit-config.yaml` in the root of the repo like it already does
4. Merges the set of configs, deduping things with the same id. (Last config to be added wins when there's an id collision)

Then I could set up a global config with the internal only hook and set up the git's `init.templateDir` to install the pre-commit by default, and then every new project we set up gets this scanner enabled by default but we don't end up forcing it on folks. 

Thoughts?

If a workflow like that doesn't exist, is that something you'd want me to try to put together and submit as a PR?

**Comment by asottile** [comment]
please fill out the issue template next time -- it encourages you to search the tracker for which there are a few duplicates -- this has my most up-to-date answer on this topic though https://stackoverflow.com/a/73054627/812183

**Comment by asottile** [comment]
also be concrete about your usecase.  show what you've tried and what isn't working -- you're jumping to solutions which often clouds the actual problem

**Comment by bplaxco** [comment]
Thanks for the quick response. 

> please fill out the issue template next time

Gotcha, sorry about that. The only one I saw available was "bug report" and this seemed like a more general question rather than a bug.

> my most up-to-date answer on this topic though

Thanks! I'll check it out.

> also be concrete about your usecase. show what you've tried and what isn't working -- you're jumping to solutions which often clouds the actual problem

Ack. Thanks for the advice :)
