### ISSUE TITLE
[proposed python, question] Should I exclude venv

### ISSUE THREAD

**Issue by thedmdim** [pre-commit/pre-commit#2472]
Hello everyone, I'm wandering if I should exclude venv globally?

I haven't found an explicit answer, either should I add `exclude: ^venv/` in _.pre-commit-config.yaml_ if I don't want any of pre-commit hooks go test dependencies.

**Comment by MarcoGorelli** [comment]
The tool only runs on staged files, so no need

**Comment by asottile** [comment]
it's trivial to **just try it** or consult [the docs](https://pre-commit.com/#pre-commit-during-commits)
