### ISSUE TITLE
Feature request: Ability to suppress warning message when config is missing and --skip-on-missing-config is used

### ISSUE THREAD

**Issue by Psychobobb** [pre-commit/pre-commit#2476]
### search tried in the issue tracker

`.pre-commit-config.yaml` config file not found. Skipping `pre-commit`, warning, missing config, quiet

### describe your issue

First of all, great project!

I am looking to use the `pre-commit init-templatedir` option to so that common hooks are added to all repos automatically when they are cloned down.

Not all repos would use/have a pre-commit config, but the above caters for that as it sets the hooks up with `--skip-on-missing-config`.

If a config is not present (but the hooks are because of the above), I see the following warning message per hook every time I trigger that hook event (so in my case this appears 2x for every commit as I am using both the pre-commit and commit-msg hooks - but this could be more depending on how many hooks have been installed).

```
`.pre-commit-config.yaml` config file not found. Skipping `pre-commit`
```

I would like to avoid seeing these warning messages any time a config is not present and anytime one of the git events is triggered

As the idea of init-templatedir is to set hooks up so they auto install into repos but the repo can opt-in or out, I can see the warnings becoming an annoyance.  Some devs might end up deleting the git hooks out their local repos to stop them, and that could mean if pre-commit configs are added at a later date, those devs will not run them as they got rid of their local hooks.

1. Is there any option I am currently overlooking that will allow us to suppress this warning completely when a config is not present?

 
2. If not, would is be possible to request a new argument be added to the hooks that when present alongside `--skip-on-missing-config` it completely suppresses this warning?

    - The default behaviour can warn still (so no difference to now), but anyone who is only opting in some of their repos by choice, then doesn't need to see potentially multiple warnings on every commit

Thanks!

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
---
```

**Comment by asottile** [comment]
the intention is to encourage pre-commit so I don't think this is going to change -- you're free to edit the file to do whatever custom unsupported behavior that you want though!
