### ISSUE TITLE
Strip basic auth from cache database repo URL

### ISSUE THREAD

**Issue by jonashaag** [pre-commit/pre-commit#2502]
### search tried in the issue tracker

basic auth

### describe your issue

We have a pre-commit config with basic auth repo urls, with frequently changing (token-based) credentials:

```yml
- repo: https://user:token@...
```

If `token` changes, the environment cache will be invalidated because the auth information is kept in the database, eg. here https://github.com/pre-commit/pre-commit/blob/354b900f15e88a06ce8493e0316c288c44777017/pre_commit/store.py#L121-L128

I think it should be safe to strip auth info because what you get from `git clone ...` does not depend on the specific credentials used (either auth is incorrect, then you don't get anything, or you get the same checkout as any other credentials).

Happy to submit a patch if this is accepted.

### pre-commit --version

latest

### .pre-commit-config.yaml

```yaml
- repo: https://user:token@...
```

**Comment by asottile** [comment]
I am not getting into the business of attempting to parse the clone url, that's going to be a big ball of complexity

plus it's possible to route via auth so it wouldn't even be correct to strip it
