### ISSUE TITLE
Let user define branch to update from

### ISSUE THREAD

**Issue by finswimmer** [pre-commit/pre-commit#2512]
_This is a follow up of https://github.com/pre-commit/pre-commit/issues/2508, whose conversation was locked before any discussion could start._

Whenever there is a need for a project to support multiple versions, it is necessary to provide multiple branches e.g. `1.1`, `1.2` which receives backports of fixes from the main development branch and also receive there own tags with each release. (Other examples beside Poetry, which uses this branching strategy: [pandas](https://github.com/pandas-dev/pandas), [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy), [jupyter-notebook](https://github.com/jupyter/notebook))

At the moment `pre-commit autoupdate` can only fetch the latest tag from the default branch. This is all good for the simple case, where the user always want to really get the latest version and the default branch always is the stable branch and not the main development branch. If users want to stay at a specific e.g minor version, there's currently no way to update to new tags in those branches.

This is why I suggest a new option for the `.pre-commit-config.yaml`, where users can define a branch they want to receive new tags from, for each repo.

_Disclaimer: Every feature request is created due to a need for it by its author. In this case Poetry likes to see such an option._

**Comment by asottile** [comment]
yes it was locked -- this is not happening -- the lock was a firm "no" -- please respect boundaries

you can merge your tags into your primary branch and then they'll be detected -- you can even do a history-only merge (though I suspect you probably want your changelogs in your primary branch anyway)
