### ISSUE TITLE
Autoupdate attempts to update to pre-release tags

### ISSUE THREAD

**Issue by christianbundy** [pre-commit/pre-commit#2513]
### search tried in the issue tracker

autoupdate alpha beta pre-release

## Problem

When I run `pre-commit autoupdate`, I am surprised to see what my dependencies are updated to pre-release versions (alpha, beta, release candidate, etc).

Concrete example: https://github.com/pre-commit/mirrors-prettier/releases/tag/v3.0.0-alpha.0

I understand that 'latest tag in a repo' is a simple heuristic that usually works well, but in this case it's back-firing.

First of all: Is this a problem that pre-commit should aim to solve?

## Solution

If it _is_ a problem we'd like for pre-commit to solve, one option would be to add 'autoupdate version' regex or similar, which would allow customization about which tags to update to. This would also provide the ability to add arbitrary version constraints (e.g. patch/minor versions only) without requiring that every dependency uses the same versioning scheme (i.e. semver).

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1 '
    hooks:
    -   id: prettier
```

**Comment by asottile** [comment]
there's a bunch of dupes -- https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+autoupdate+pre-release+is%3Aclosed
