### ISSUE TITLE
 poetry add pre-commit fails to resolve dependencies

### ISSUE THREAD

**Issue by JasonF-BJSS** [pre-commit/pre-commit#2536]
### search you tried in the issue tracker

poetry

### describe your issue

poetry add pre-commit --group dev 
Using version ^2.20.0 for pre-commit

Updating dependencies
Resolving dependencies...

Did not resolve (left running for one hour)

Could be problem with Meta data according to poetry:
Poetry (version 1.2.1)
not sure if the issue is with pre-commit or poetry.

I have had to stop using pre-commit until a resolution is found.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
N/A as it will not install
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A as it will not install

**Comment by JasonF-BJSS** [comment]
linked to:
https://github.com/python-poetry/poetry/issues/6697
raised in poetry as not sure where bug sits

**Comment by asottile** [comment]
works fine for me, sounds like a poetry problem

**Comment by JasonF-BJSS** [comment]
This may be a red herring, it may in-fact be a dependency 'filelock' that is the issue:
running in verbose mode it stop at filelock:

poetry add pre-commit -vvv
...
Source (PyPI): No release information found for setuptools-13.0, skipping
Source (PyPI): 493 packages found for setuptools *
1: fact: virtualenv (20.16.5) depends on distlib (>=0.3.5,<1)
1: fact: virtualenv (20.16.5) depends on filelock (>=3.4.1,<4)
1: fact: virtualenv (20.16.5) depends on platformdirs (>=2.4,<3)
1: selecting virtualenv (20.16.5)
1: derived: filelock (>=3.4.1,<4)
1: derived: distlib (>=0.3.5,<1)
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] [https://pypi.org:443](https://pypi.org/) "GET /pypi/filelock/json HTTP/1.1" 304 0

adding filelock on its own has same output:

poetry add filelock -vvv
Loading configuration file /Users/jason.francis/Library/Preferences/pypoetry/config.toml
Using virtualenv: /Users/jason.francis/Library/Caches/pypoetry/virtualenvs/jml-automation-scripts-deYEdmxQ-py3.10
Project environment contains an empty path in sys_path, ignoring.
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] [https://pypi.org:443](https://pypi.org/) "GET /pypi/filelock/json HTTP/1.1" 304 0

**Comment by asottile** [comment]
yeah I can't help -- I don't use and actively avoid poetry, please talk to the poetry people
