### ISSUE TITLE
Hooks which don't cause pre-commit to fail

### ISSUE THREAD

**Issue by antonag32** [pre-commit/pre-commit#2542]
Is this something the community is interested in? Declaring hooks which won't make pre-commit fail if they fail?. Sort of optional checks. I have a use case for it and am wondering if this feature is something that could get merged if I made the MR for it.

**Comment by asottile** [comment]
please search the issue tracker as the issue template recommends -- #2413

hooks that don't fail when they fail (aka warning noise) are already possible with `|| true` and `verbose: true` -- but they are discouraged and outside official support
