### ISSUE TITLE
[autoupdate] Please consider using this command to get the latest tag in a repository

### ISSUE THREAD

**Issue by DeadNews** [pre-commit/pre-commit#2543]
### search you tried in the issue tracker

autoupdate

### describe your issue

https://github.com/pre-commit/pre-commit/blob/b97bb1809fa11323f7d0879293b791b62a92025c/pre_commit/commands/autoupdate.py#L41-L42

        no the latest is 1.2.0rc1:

```console
$ git clone --quiet git@github.com:python-poetry/poetry 
$ cd poetry
$ git describe --tags --abbrev=0
1.2.0rc1
```

_Originally posted by @asottile in https://github.com/pre-commit/pre-commit/issues/2507#issuecomment-1240659989_

-----

Please consider using this command to get the latest tag in a repository:

```sh
$ git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1
1.2.1
```

<details> 
  <summary>count=10</summary>

  ```sh
  $ git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=10
  1.2.1
  1.2.0
  1.2.0rc2
  1.2.0rc1
  1.1.15
  1.2.0b3
  1.1.14
  1.2.0b2
  1.2.0b1
  1.1.13
  ```
</details>

<details> 
  <summary>exclude pre-releases</summary>

  ```sh
  $ git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' | grep -v '[a,b,rc]' | head -n10 
  1.2.1
  1.2.0
  1.1.15
  1.1.14
  1.1.13
  1.1.12
  1.1.11
  1.1.10
  1.1.9
  1.1.8
  ```
</details>

ref: https://github.com/pre-commit/pre-commit/issues/2518, https://github.com/pre-commit/pre-commit/issues/2507, https://github.com/pre-commit/pre-commit/issues/1555

      

### pre-commit --version

any

### .pre-commit-config.yaml

```yaml
any
```

**Comment by asottile** [comment]
that will do the wrong thing for backports on old branches

I am not changing this please stop
