### ISSUE TITLE
Win11: Codespell doesn't use Python interpreter from INSTALL_PYTHON

### ISSUE THREAD

**Issue by JoergAtGithub** [pre-commit/pre-commit#2545]
### describe your issue

My `.git\hooks\pre-commit` contains

`INSTALL_PYTHON='C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe'`

which is the path of the Python v3 interpreter on my system.

But it seems that codespell doesn't use this path, instead it tries to execute
`%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\python3.exe`
Which is just a alias for the Microsoft Store, which comes with every Windows 11 installation by default.

### pre-commit --version

2.2.0

### .pre-commit-config.yaml

```yaml
Doesn't exist
```

### ~/.cache/pre-commit/pre-commit.log (if present)

not present

**Comment by asottile** [comment]
please report to codespell then

if you don't have a pre-commit config then you must not be using pre-commit

**Comment by JoergAtGithub** [comment]
> please report to codespell then
> 
> if you don't have a pre-commit config then you must not be using pre-commit

@asottile This assumption is not true, all other checks are executed. If I SKIP=codespell, it even passes.

**Comment by asottile** [comment]
then why didn't you fill out the template

**Comment by asottile** [comment]
the bug is in your tools/codespell.py
