### ISSUE TITLE
add some explanation docs for `types: [direcrory]` usage

### ISSUE THREAD

**Issue by tandav** [pre-commit/pre-commit#2546]
the [docs says](https://pre-commit.com/#filtering-files-with-types)
> directory - in the context of pre-commit this will be a submodule

I have following hook:
```
.
├──.git 
│  ...
├── .pre-commit-hooks.yaml
├── print_hook.py
├── setup.cfg
└── setup.py
```

#### `.pre-commit-hooks.yaml`
```yaml
- id: print_hook
  name: print_hook
  entry: print_hook
  language: python
  types: [directory]
```

#### `print_hook.py`
```py
import sys

def main():
    print('hello from print_hook', sys.argv)
```

#### `setup.cfg`
```
[metadata]
name = print-hook
version = 0.2.0

[options]
py_modules = print_hook

[options.entry_points]
console_scripts =
    print_hook = print_hook:main
```

#### `setup.py`
```py
from setuptools import setup
setup()
```

I have a repo where I want to run above hook:
```
.
├── mymod
│ ├── __init__.py
│ ├── f0.py
│ ├── f1.py
│ └── sub1
│     └── __init__.py
```

```sh
$ pre-commit try-repo /Users/tandav/Desktop/print-hook/ print_hook --verbose --all-files
[WARNING] Creating temporary repo with uncommitted changes...
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpqzgbxnva/shadow-repo
    rev: b2c7e5afe0254393acbda84877d9e97fe65bf5d8
    hooks:
    -   id: print_hook
===============================================================================
[INFO] Initializing environment for /var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpqzgbxnva/shadow-repo.
[INFO] Installing environment for /var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpqzgbxnva/shadow-repo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
print_hook...........................................(no files to check)Skipped
```

it prints `Skipped`. If I change filtering to `types: [python]` or `types: [file]` I get:
```sh
$ pre-commit try-repo /Users/tandav/Desktop/print-hook/ print_hook --verbose --all-files
[WARNING] Creating temporary repo with uncommitted changes...
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpmvo2bw8i/shadow-repo
    rev: 385260bc459a79df3e2a9a433eeb9f0f8ae4d612
    hooks:
    -   id: print_hook
===============================================================================
[INFO] Initializing environment for /var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpmvo2bw8i/shadow-repo.
[INFO] Installing environment for /var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpmvo2bw8i/shadow-repo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
print_hook...............................................................Passed
- hook id: print_hook
- duration: 0.03s

hello from print_hook ['/var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpmvo2bw8i/repoi8o7t4pp/py_env-python3.10/bin/print_hook', 'mymod/__init__.py', 'mymod/f0.py', 'mymod/f1.py']
```

I can see that hook is running and files are triggered. But I can't see `mymod/sub1/__init__.py`.  

### I have 2 questions:

1. Is `type: [python]` scans only top level python files [in a module] and not does recursive search?
2. My expected behavior for `types: [directory]`: script should be called with all directories found in repo (recursively?) (expected output listed bellow). Am I misuse `types: [directory]`? If so can you explain how to use it?
```
$ pre-commit try-repo /Users/tandav/Desktop/print-hook/ print_hook --verbose --all-files
hello from print_hook ['/var/folders/55/qy0t9p014pz23w43l2zyd70r0000gn/T/tmpmvo2bw8i/repoi8o7t4pp/py_env-python3.10/bin/print_hook', 'mymod', 'mymod/sub1']
```

**Comment by asottile** [comment]
a "submodule" is a thing in git, that is the only thing that will be matched.  git does not track directories, only files

**Comment by sblask** [comment]
The question doesn't exactly match my problem, but the title of this issue does. I've got this in my config:

      - id: trivy
        name: trivy
        entry: trivy config --debug --exit-code 1 .
        language: system
        types_or:
          - directory
          - dockerfile
          - terraform
        pass_filenames: false

I also have a git submodule in my repository, but when I update it pre-commit still skips my trivy hook. I can understand if pre-commit doesn't look into submodules for file changes, but if it does not recognise this kind of change:

```
diff --git a/infrastructure/shared-terraform-modules b/infrastructure/shared-terraform-modules
index e930e82..7192685 160000
--- a/infrastructure/shared-terraform-modules
+++ b/infrastructure/shared-terraform-modules
@@ -1 +1 @@
-Subproject commit e930e82c6cf9994ce9a4555ba2c657f0ecce944c
+Subproject commit 71926859ccb6c847d9389fd47d3105f4c8e8d6bc
```

I have no idea what `types: [directory]` is for? The documentation also says `symlinks / submodules can be easily ignored` As far as I can tell `types` is only for including, so how can I ignore something with it?

**Comment by asottile** [comment]
> The question doesn't exactly match my problem

**then don't post a new off topic question on an unrelated issue**

[the default is `types: [file]`](https://pre-commit.com/#hooks-types) -- so you need to reset that to `types: []`
