### ISSUE TITLE
Idea: selectively enable / disable specific hooks

### ISSUE THREAD

**Issue by bmwant** [pre-commit/pre-commit#2551]
### Description
Allow to enable / disable specific hooks by id. Might be useful when working on a big monorepo, so infrastructure team uses only terraform hooks, f/e uses js-related and backend team invokes python ones.
Will probably require maintaining a separate user-specific configuration file or file in the repo directory which should be added to `.gitignore`.

### CLI UX overview

* `pre-commit list` (or `status`)
```
isort................................................(5.10.1)Enabled
black................................................(22.0.1)Enabled
flake8...............................................(4.0.1)Enabled
poetry-check.........................................(1.2.1)Disabled
```

* `pre-commit disable isort` - disable specific check by id / `pre-commit disable` - disable all the hooks. Another advantage is to be able temporary skip checks using these commands.

* `pre-commit enable flake8` - enable specific check by id / `pre-commit enable` - enable all the hooks

@asottile let me know whether this is the feature that can be added to the package and I will be glad to create a PR for the change

**Comment by asottile** [comment]
no thanks. you can already accomplish this with multiple configs and the point of the pre-commit config is every contributor runs the exact same set of tools

there's already a mechanism for temporarily disabling hooks as well (SKIP) and we don't need two of them
