### ISSUE TITLE
Feature-request: pre-commit without changed files

### ISSUE THREAD

**Issue by ymilki** [pre-commit/pre-commit#256]
I have lots of pre-receive hooks that I would like to convert to pre-commit. But lots of them run against the git history rather than changed files. Support for hooks that will run without changed files, but changed history would be useful.

**Comment by asottile** [comment]
I'm not sure what this would look like?  Currently pre-commit is designed entirely around feeding a list of files to hooks.

**Comment by ymilki** [comment]
A git commit always have access to the original HEAD and information to generate a new commit (e.g. committer, author, message body, blobs). A hook at this stage would generally examine the information for the new commit.

A git push would always have the current ref tip to push and the remote's original ref tip. A hook at this stage would examine the commits that differ between the remote and the pushed refs.

**Comment by asottile** [comment]
So it sounds like the already-existing `pre-commit run --origin {remoteref} --source {currentref}` would solve your problem?

**Comment by ymilki** [comment]
That sounds like it would work for pre-push, but not for pre-commit as at pre-commit time, there is no new commit yet.

**Comment by asottile** [comment]
Right, at pre-commit time there is no commit so you cannot compare commits.  The above command is already what is used for pre-push.

To support what you want at pre-commit time I'd suggest invoking git commands inside your hook (similar to how [this one works](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_added_large_files.py#L17)).

**Comment by ymilki** [comment]
Ok. So we can write pre-commit hooks that are triggered without file changes?

https://github.com/pre-commit/pre-commit/blob/5f5947d1c8e7e0fd9d25d5032dc6a286e31dbceb/pre_commit/commands/run.py#L79 will skip hooks if no files were changed.

**Comment by asottile** [comment]
You'll need to respond to some file change.  Otherwise there's nothing to lint?

The hook in question responds to *all* files: https://github.com/pre-commit/pre-commit-hooks/blob/master/hooks.yaml#L13-L14

**Comment by ymilki** [comment]
Hm, that would seem to work in the general case.

Does this also apply to `git commit --amend` without changed files?

**Comment by asottile** [comment]
`--amend` without changed files will also have nothing to lint.

**Comment by ymilki** [comment]
Ok, so hook that only looks at changed history wouldn't be able to run in that case. If that is required, it would only work as a pre-push hook and not a pre-commit hook. I think that caveat is fine.

Matching all files with `files: ''` in the hook config appears to be sufficient for hooks that examine commit history. I'll try that out.

**Comment by asottile** [comment]
Yeah sounds about right.  Everything is currently based on files and I don't see that changing any time soon.

**Comment by JulianVolodia** [comment]
Hey, could I ask about it again? :) @asottile @ymilki :)

I know 2 situation that this not working.
Both apply to problem that pre-commit skipping files already commited, not staged. You could apply changes or cherry-pick some commit where will not be any conflicts needing solve. But will increase the smaller entropy of the repo.

First situation.
In example, isort is in pre-commit hooks. You add any class or function import from same module.
Imagine, that you rebasing. Then, your commit was tested, passed and OK. It is not ok after rebase, because someone added import too. Which is changing the sort after your rebase. Your rebase COMMITS have skipped ~~pre-file-change~~ pre-commit hooks. On CI there is the fail. Bang bang.

Second situation.
One commit with --no-verify. ~~pre-file-change~~ pre-commit not care about it. So, you need to craft other tool to do it, because this is not configurable to check *all* files *always* **auto-magically** don't repeting ourselfs.

What You think about that problems? Thanks.

**Comment by asottile** [comment]
checking all files always is slow with no escape hatch.  this will not happen in the framework but you can always adjust the `entry` to do what you want (it's strongly not suggested, but you can make it happen with `entry` and / or `args` and / or `always_run`

my suggestion is to run with `--all-files` periodically -- and if you need gating use that in CI (sounds like you especially need this if your devs are skipping checks) and look out for https://pre-commit.ci in the future which'll autofix for you

**Comment by JulianVolodia** [comment]
Thanks for advices @asottile . Regards.

**Comment by JulianVolodia** [comment]
Still, I talk only about checking files from commit and staged for when pre-commit (if could) know about amending in progress, or about checking file commit when commit is "cherry-picked".

If You want, I could read more and understand more about it, 1st case.

Second, indeed - goes to culture if some use `--no-verify`.

**Comment by JulianVolodia** [comment]
Maybe I miss some basic understanding about hooks here, so that is pity and need to progress that.

**Comment by asottile** [comment]
I'm not sure what you want, I told you how you can accomplish it but it is not a good idea to do so.

git doesn't tell us whether an amend happened or a no-verify occurred so "detecting" it is impossible.  also pre-commit works fine for amends (it runs against the files being amended)

I'd suggest you try my suggestion above, but also this is off topic from the original post (which is also 5 years old!)
