### ISSUE TITLE
Feature Request: `list` subcommand to show all installed pre-commit hooks

### ISSUE THREAD

**Issue by fabianegli** [pre-commit/pre-commit#2562]
I am looking for an easy and reliable way to list all installed pre-commit hooks and couldn't find one.

Hence the proposal to have a `list` or `list-installed-hooks` or similar subcommand for `pre-commit` that lists all installed hooks.

**Comment by asottile** [comment]
why?

does `cat` on your config not do what you want?

**Comment by asottile** [comment]
that doesn't matter, pre-commit will always install exactly what's needed in the config on demand

**Comment by fabianegli** [comment]
True, but what if I want to make the execution of the hooks dependent on what's installed?

**Comment by asottile** [comment]
why would you want to do that

**Comment by fabianegli** [comment]
I would like to use one of the pre-commit hooks in a repo as a utility for the code in the repo without installing the hooks in the repo. And I thought listing installed hooks was one step on the way get there, but maybe not.

This convolution mostly derives from the desire to make use of npm in a python tool and there might be better ways to handle the integration (of Prettier).

**Comment by asottile** [comment]
just use `pre-commit run whatevertool`?

**Comment by fabianegli** [comment]
Thank you :-)

**Comment by asottile** [comment]
this is what's called an XY problem.  you didn't state what you wanted to do up front and instead prescribed a completely unrelated solution that wouldn't have even helped your problem. in the future just state what you're actually trying to do

**Comment by trallnag** [comment]
Here is how to do it with `grep`:

```sh
grep -oP '(?<=- id: ).*' .pre-commit-config.yaml
```

**Comment by bluefing** [comment]
I bit late but another example building on  @trallnag 

`yq -r '.repos[].hooks[].id' .pre-commit-config.yaml`

I'm using the list in a `just` recipe, piping the list into `fzf` to allow me to selectively pick and execute hooks locally to test changes.
