### ISSUE TITLE
Question: is possible to skip analysis files if only run command via pre-commit

### ISSUE THREAD

**Issue by shenxianpeng** [pre-commit/pre-commit#2572]
Hello @asottile

I would like to create a pre-commit hook that just runs a command and no need to analyze files. 

The current situation is that running the command via `pre-commit` takes many times as long as running the command alone.

I tried to use `files: ^$` to skip analysis files in  `.pre-commit-hooks.yaml`, but it seems `pre-commit` still analyzes files.

Is there any way to skip the analysis files? 

I looked at pre-commit.com documentation but I didn't find the relevant option, if I missed something, I'm very sorry for taking up your time.

Thank you in advance.

**Comment by MarcoGorelli** [comment]
If I understand correctly, do you just need `pass_filenames: false`?

**Comment by asottile** [comment]
don't skip the template, there's lots of dupes including the most recent issue https://github.com/pre-commit/pre-commit/issues/2567
