### ISSUE TITLE
Support for `pre-rebase` Hook

### ISSUE THREAD

**Issue by BrutalSimplicity** [pre-commit/pre-commit#2582]
Is there a pre-commit hook that can prevent rebase operations? It looks like git does support a `pre-rebase` hook, but I didn't see it in the docs.

I checked [here](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages).

Example `pre-rebase` hook:

https://gist.github.com/uasi/9384329

**Comment by asottile** [comment]
here's some PRs you can draw inspiration from -- #2036 #1800

**Comment by BrutalSimplicity** [comment]
Never mind, I think I'm actually looking for the standard `commit` hook functionality. I want to be able to prevent certain commits from being rewritten, which I _think_ that hook can do. Apologies. 😅 

I'll still leave this open, since it is functionality that doesn't exist.

**Comment by BrutalSimplicity** [comment]
@asottile I appreciate the quick response. Thank you! Not sure if I'll have time soon to add this, but when I have more time, I'll try to take a look if this is still open.

**Comment by asottile** [comment]
if you're trying to hook into individual "commits" that (for example) an interactive rebase makes unfortunately I don't think there's a way to do that (`git rebase --continue` skips hooks in my experience)

**Comment by asottile** [comment]
(that is, unless you manually call `git commit` with no arguments before continuing)

**Comment by BrutalSimplicity** [comment]
Ahh, thanks for letting me know that. I guess server-side hooks are the way here. Any ideas on how you can implement a server-side hook that will reject a push if a "protected" commit message is modified?

I don't think there is support in `git` for this concept, but some tools like to use git as a more traditional datastore, and if a certain commit is altered, the tools end up in an odd state.

As I was typing this it dawned on me that this could possibly be handled by a tagging strategy.

**Comment by adamchainz** [comment]
I just [blogged about](https://adamj.eu/tech/2022/11/07/pre-commit-run-hooks-rebase/) a solution to run hooks during rebase:

```
$ git rebase -x 'pre-commit run --from-ref HEAD~ --to-ref HEAD' main
```

**Comment by jawomg** [comment]
เพิ่มการรองรับ hook แบบ pre-rebase #2725
