### ISSUE TITLE
Hook execution order

### ISSUE THREAD

**Issue by adam-moss** [pre-commit/pre-commit#2588]
Hi,

Is there a way to set a hook to execute at a certain point when multiple hooks are present for a given stage?

I know I can set `require_serial: true` on all of the hooks in the stage to force them to run sequentially but it isn't clear if that ordering would be per the `.pre-commit-yaml.config` or something else.

And the ordering isn't really important except for one hook which I want to run _after_ all the others have completed successfully but can't move into a preceding stage as you still have the same challenge and I'd also get a timing issue occur.

Thanks

**Comment by adam-moss** [comment]
Oh they work, don't get me wrong.

I've got a particular hook in `commit-msg` that pulls a signing key into the agent I've got git configured to use and then removes it again in the `post-commit`.

I'm simply trying to minimise the time that key is "exposed" (for want of a better word) to the agent.

**Comment by asottile** [comment]
I don't think I understand, are you seeing things happen out of order?

**Comment by adam-moss** [comment]
Yes, I don't have `require_serial` on the hooks at the moment, as there is only this particular one I'd like to optimise. The rest are fine in parallel.  At the moment I see a varying number completing after the key one (which is defined last in the `.pre-commit-config.yaml`).

**Comment by asottile** [comment]
you're going to have to provide more information since that's not how it works

**Comment by asottile** [comment]
actually let's just start over -- don't skip the template and fill it out completely
