### ISSUE TITLE
Raise error if `--files` don't exist

### ISSUE THREAD

**Issue by dannysepler** [pre-commit/pre-commit#2589]
### search you tried in the issue tracker

is:issue files

### describe your issue

When running `--files` against paths that don't exist, pre-commit silently continues with the rest of the execution. This hides potential user mistakes when calling pre-commit. Would it be reasonable to instead raise an error here?

To reproduce:

```bash
echo "print('hi')" > f.py

pre-commit run --files f.py nope.py
# fix end of files.........................................................Passed
# exits successfully

pre-commit run --files nope.py
# fix end of files.....................................(no files to check)Skipped
# exits successfully
```

In both these cases I would expect pre-commit to exit with an error code. I don't really have an opinion about if the hooks should run on other files (if given) that do exist.

---

Side note: this recently contributed to a similar confusion I had to https://github.com/pre-commit/pre-commit/issues/2511. I had run `pre-commit run --files setup.py my_dir/*.py` and had mistakenly thought it was passing since `setup.py` did exist

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.37.0 (Apple Git-136)
sys.version:
    3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
sys.executable: /opt/homebrew/opt/python@3.10/bin/python3.10
os.name: posix
sys.platform: darwin
```

**Comment by asottile** [comment]
this is, unfortunately, intentional -- due to `git diff --staged --name-only` reporting deleted files.  a change here would be a break

**Comment by dannysepler** [comment]
ah i see, we remove non-existent files [in the Classifier object](https://github.com/pre-commit/pre-commit/blob/4399c2dbc6b7571489a524eedecfba9cd53d93a8/pre_commit/commands/run.py#L74) which is shared between different ways to get the files. that also makes sense that if something's coming from a git command we have pretty good faith the file exists (or existed)!

could we instead do the check in a place specific to the `.files` arg ([here](https://github.com/pre-commit/pre-commit/blob/4399c2dbc6b7571489a524eedecfba9cd53d93a8/pre_commit/main.py#L152) for example), since it's mainly when `--files` are given that a typo could occur?

**Comment by asottile** [comment]
as above, people currently call `git diff --staged --name-only | xargs pre-commit --files` (or other various versions of this) which would break that
