### ISSUE TITLE
Allow `pre-commit run`'s `--to-ref` flag to support specifying the current index

### ISSUE THREAD

**Issue by jtamagnan-delphix** [pre-commit/pre-commit#2600]
### Search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/2058

### Describe your issue

Even outside of the scope of "diff-based pre-commit checks", there are occasions where one may want to a pre-commit check from some reference to the current git index. An example of this is that one might want to run pre-commit on all of the files in all of the commits between the current index and the upstream branch.

I think that the trickiest part of this change is the interface. 
 1. One idea would be to pass in some sentinel value to `--to-ref`, possible values would be, `"INDEX"`, `"NONE"`, `""`. The problem here though is that it breaks the convention that `--to-ref` takes in an actual git ref
  2. Another option would be to add a new flag `--to-index`. This would do the trick but further increases the surface area of the tool.
  3. A third option would be to make `--to-ref` optional . This adds more functionality to this flag without changing the interface in a backwards incompatible way. We would be adding functionality in the cracks where an error used to be raised. The issue here is that this behavior would not be as explicit as passing in `--to-index`.

I think my personal favorite implementation of this would be #3.

---

I'd be willing to open a pull request to implement this but wanted to bring up the idea and talk about the interface before getting started on any work. 

---

### pre-commit --version

pre-commit 2.15.0

**Comment by asottile** [comment]
> there are occasions where one may want to a pre-commit check from some reference to the current git index. An example of this is that one might want to run pre-commit on all of the files in all of the commits between the current index and the upstream branch.

you can do that already -- `pre-commit run --from-ref ... --to-ref ... && pre-commit run`

I see no reason to add complexity when there's already a simple way to do what you want and when I think what you want is dubious / rare at best

**Comment by asottile** [comment]
I think you can also use `--to-ref $(git write-tree)`

**Comment by jtamagnan-delphix** [comment]
Ahhh `git write-tree` was the missing link that I was looking for. Thanks for super quick response and the helpful direction. If you ever do change your mind about adding the ability to omit `--to-ref` let me know, I'd be happy to help out. Cheers.
