### ISSUE TITLE
The sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [pre-commit/pre-commit#2609]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+tox.ini+sdist

### describe your issue

The sdist at PyPI is missing both `tox.ini` and `requirements-dev.txt` files.  Please add them to sdist to make the downstream testing easier.  Thanks.

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
NA
```

**Comment by asottile** [comment]
no thanks, use the tgz from pypi

**Comment by mtelka** [comment]
> no thanks, use the tgz from pypi

What exactly you mean by "tgz from pypi"?  Could you provide an url please?  Thank you.

**Comment by asottile** [comment]
sorry I mean github
