### ISSUE TITLE
option to share virtualenv and avoid duplicate files?

### ISSUE THREAD

**Issue by juju4** [pre-commit/pre-commit#2615]
Thanks a lot for your work. pre-commit is great!

While reviewing my disk space, I found that ~/.cache/pre-commit is taking about 3GB.
There is one repoXXX directory ranging from 3 to 500MB.

Is there away to share virtualenv fully or partially and avoid duplicate files?

I know that it is hard if want to keep each repo separated but it would be a nice option.

**Comment by asottile** [comment]
they are shared already

**Comment by juju4** [comment]
That's great but How does it explain disk usage?
On my side, it seems mostly in py_env-python3/lib*/python3.*/site-packages (pip, ansible...). another less common is semgrep-core.

**Comment by asottile** [comment]
try `pre-commit gc` but also it's 2022 so disk is functionally free

**Comment by juju4** [comment]
Thanks. down to 1.6GB after gc.
