### ISSUE TITLE
Ability to run hooks in incremental-only mode

### ISSUE THREAD

**Issue by mdering** [pre-commit/pre-commit#2625]
We maintain a large sql repository, and would like to start adding sqlfluff linting but only for updated scripts. The problem is, many of our users are in the habit of running `pre-commit run --all-files` which can take an hour to run, and would in all likelihood modify all 1500 of these sql files. I would like to propose adding a feature so that certain hooks can be configured to not run when we run `pre-commit run --all-files` and instead only run on the new or modified files.

**Comment by asottile** [comment]
give them a script with SKIP

**Comment by asottile** [comment]
or better yet, start by formatting everything instead of ending up with noisy unrelated changes in every pr

**Comment by mdering** [comment]
and if they don't run it or don't read it? and it still takes an hour to run, even if all the formatting is fine

**Comment by mdering** [comment]
sorry, i don't think this addressed my issue. can you reopen the ticket?

**Comment by asottile** [comment]
surely your developers will get impatient and cancel it

**Comment by mdering** [comment]
is my developers getting impatient and cancelling it the best use case for this tool?

**Comment by asottile** [comment]
yes. I am not adding the complexity you are suggesting when there is already a designed way to do what you want. you're suggesting we maintain a bunch of complexity for a .0001% use case and a dubious feature.

feel free to fork if you really want such a thing

**Comment by mdering** [comment]
ok thank you very much

**Comment by asottile** [comment]
> sorry and so what is the designed way? because so far you've suggested telling people to use SKIP, and relying on impatience. and the added complexity you're referring to is 5 lines across 3 files?

don't do this.  I already said no.  please respect my time and decisions
