### ISSUE TITLE
Add feature to warn quoted quotation for literal block via `validate-config`

### ISSUE THREAD

**Issue by micttyl** [pre-commit/pre-commit#2627]
When an yaml config file contains a literal block that is a multi-line string with an extra outer-most quote, it can lead to the undesirable result(not working and hard to figure out why). We can check like [this](https://github.com/carbon-language/carbon-lang/pull/2438). Thinking of treatment, someone in extreme may want to do quote twice, so it shouldn't be an error. I wonder if this can be at least warned via, for example, `validate-config`.

**Comment by asottile** [comment]
please fill out the template -- it prompts you for your configuration and some examples -- as it is I don't know what you're talking about

**Comment by asottile** [comment]
I'm guess you're talking about [a feature that already exists](https://pre-commit.com/#meta-check_hooks_apply) -- if not please reopen with more information

**Comment by micttyl** [comment]
> I'm guess you're talking about [a feature that already exists](https://pre-commit.com/#meta-check_hooks_apply) -- if not please reopen with more information

I agree. It can be debugged like so and below the doc, the usage of block was given clearly. I will follow the template next time. My apology.
