### ISSUE TITLE
Specify the working directories in which a hook is executed

### ISSUE THREAD

**Issue by f1rstlady** [pre-commit/pre-commit#2639]
I have some cases where I would like to specify the working directories in which a hook is executed. For example, I use StyLua to format my Lua code; the code itself and some config files reside in some subdirectory:
```
lua
├── module.lua
├── .styluaignore
└── stylua.toml
```
StyLua recognizes config files only in the working directory (or by passing an additional argument), thus these config files are not recognized by the corresponding pre-commit hook. This may be fixed by moving the config files to the top-level directory which I want to avoid. Hence it would be great if one could specify for each hook a list of working directories in which the hook is executed, e.g.:
```
hooks:
-   id: stylua
    working-directories: [ lua/ ]
```

What do you think about this idea?

**Comment by asottile** [comment]
please search the issue tracker, there are many duplicates, workarounds, and reasons this wil no be implemented

**Comment by f1rstlady** [comment]
I had searched the issue tracker before -- apparently not thourougly. For others reading this issue, here is the link to the explanation: https://github.com/pre-commit/pre-commit/issues/1110#issuecomment-518939116
