### ISSUE TITLE
Missing functools32 as dependency

### ISSUE THREAD

**Issue by ericklaus-wf** [pre-commit/pre-commit#264]
When running `pip install pre-commit` in a fresh Python environment, the install completes but `pre-commit` throws an error when attempting to run it. 

I haven't investigated enough to understand whether `pre-commit` simply omits this requirement or whether a dependency is not correctly installing it.

The problem is solved by additionally installing `functools32`. For example, `pip install functools32 pre-commit`.

### Error message:
```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/68fd35975e3f7495/bin/pre-commit", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/user/.virtualenvs/68fd35975e3f7495/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/Users/user/.virtualenvs/68fd35975e3f7495/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/user/.virtualenvs/68fd35975e3f7495/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
```

**Comment by chriskuehl** [comment]
What version of pip are you using? There's a comment from some guy named @dnephin [here](https://github.com/Julian/jsonschema/issues/233#issuecomment-110944344) that suggests there may be an issue with older versions of pip not understanding environment markers.

Indeed it is jsonschema that pulls in that dependency for pre-commit as well.

Not sure if this is a full solution to the problem, but maybe a start. If you upgrade pip in a clean Python environment are you then able to install and run pre-commit?

**Comment by chriskuehl** [comment]
(maybe we just want to add it to our setup.py anyway, dunno)

**Comment by ericklaus-wf** [comment]
Ug--I should have found that when I was searching for the problem.

I do indeed have an old version of pip by default in my virtual environments. I was using version 1.4.1. In a fresh environment, installing the latest version of pip, installing pre-commit, and then running pre-commit does work.

I'm not sure how common old versions of pip actually are, so I can't say how important this is to work around generally. In my case, it's pretty easy to just remember to upgrade pip.

**Comment by asottile** [comment]
Seems this is broken in pip<=1.4, upgrading to at least 1.5 solves this.  pip 1.5 was released on 2014-01-02 and at least in trusty, python-pip is old enough: http://packages.ubuntu.com/trusty/python-pip (though not in precise :/)

Since there's an upstream issue here: https://github.com/Julian/jsonschema/issues/233 I'm tempted to close this as wontfix on our end.

If you want your virtualenv to create a newer pip by default, I'd suggest upgrading virtualenv.  The version we use at work is kinda old (1.11.x) but it'll still installs pip1.5 by default.

@ericklaus-wf  what do you think?

**Comment by ericklaus-wf** [comment]
That's fine by me.
