### ISSUE TITLE
Omit [WARNING] Unstaged files detected.

### ISSUE THREAD

**Issue by KUGA2** [pre-commit/pre-commit#2648]
### search you tried in the issue tracker

yes

### describe your issue

When i have unstages changes it shows:

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/kuka/.cache/pre-commit/patch1671728912-3677.
Check Yaml...........................................(no files to check)Skipped
...
[INFO] Restored changes from /home/kuka/.cache/pre-commit/patch1671728912-3677.
```

Why is the first warning printed? Is this dangerous?

Can we remove this? Or add a config flag to remove it?

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: .clang-format
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
```

**Comment by asottile** [comment]
"yes" is not a search

it's a warning because it's an exceptional case

**Comment by KUGA2** [comment]
Updated my search.

Nevertheless, I do not think this is an exceptional case. This heavyly depends on ones workflow.
I regular do this (develop something, then add separate commits for different steps).

git supports this and does not warn, if something is unchanged. I do not think pre-commit should either.

**Comment by asottile** [comment]
correct, but `git` also takes no action -- whereas `pre-commit` tries very hard to ensure that when tools check your commit that there are no remaining unstaged changes -- and then tries very hard to put everything back the way it was before.  the warning is out of caution because that part is quite complicated (it's also the reason pre-commit tells you its implementation detail of the patch file in case things go horribly wrong and you need to recover)

**Comment by KUGA2** [comment]
I agree with what pre-commit is doing here. We surely do not want to check anything that will not be commited. This would is especially important when you commit only parts of a file (that file has other unstaged lines).

I see why you are extra cautious here. I just think the info message would be enough. But nevermind, my real [issue ](https://github.com/microsoft/vscode/issues/169871) is elsewhere...
