### ISSUE TITLE
Add new hook-level configuration 

### ISSUE THREAD

**Issue by Niccolum** [pre-commit/pre-commit#2652]
Hello, 

Thanks for your work and your awesome tool.

I have situation, when I need run latest hook only if other passed successfully. I can solve this with global fail_fast=true option. But it means, what if I have 10 formatters - I'll run pre-commit as many times as formatters fail. Sometimes, this not very good solution. So, if you share my opinion, maybe add this setting for hook-level?

**Comment by asottile** [comment]
https://pre-commit.com/#hooks-fail_fast

**Comment by Niccolum** [comment]
@asottile but this option means, that if current hook fail - all lre-commit stops. This is not the same, which i mean.

**Comment by asottile** [comment]
describe your actual situation then

**Comment by Niccolum** [comment]
Thanks, @asottile 

I have a lot of formatters and linters.
My latest local hook - change version file and add it to current commit changes.
So, with fail_fast=false, if any hooks fail - pre-commit fail. But version will rise anyway. If it will be possible to skip this - this solve my problem.

**Comment by asottile** [comment]
changing version as part of a commit is a bad idea

**Comment by Niccolum** [comment]
This is the best I could come up with to remember to upvote
