### ISSUE TITLE
Another proposal for allowing use of files from the repository

### ISSUE THREAD

**Issue by bmerry** [pre-commit/pre-commit#2653]
### search you tried in the issue tracker

Issues #730/#880/#945

### describe your issue

I'm still hoping to find a way to get pre-commit to get versions from my standalone requirements files rather than duplicating information into `additional_dependencies`. I've looked through previous issues (#730, #880, #945) and while #945 seems to be pointing people in the direction of writing tools to synchronise information (despite the issues with machine-rewriting YAML), I'm going to make another proposal. I'm prepared to work on a PR for it, but wanted to check that I'm going in the right direction and that a PR won't be rejected for design reasons.

### Interface

The problem with #880 is it tried to be very Python-specific and do magical things. My suggestion is to require the user to explicitly indicate the files from the repository that affect the installation of the hook. So for example, a mypy hook might look like this:

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
      - additional_dependencies: ['-r', '${srcdir}/requirements.txt']
      - additional_files: ['requirements.txt']
```

The important part is the `additional_files`: when the hook repo is checked out, files listed there will get copied to a special-purpose directory under the repo dir (preserving the directory structure), and `${srcdir}` in additional_dependencies will get rewritten to point to that directory. That keeps the user honest and ensures that they don't forget to list any files that will affect cache invalidation. For example, if `requirements.txt` contains `-r requirements2.txt`, then the user ought to list `requirements2.txt` in `additional_files`, and if they don't, it will lead to an error during `installation_environment` because it won't have been copied.

### Implementation

The caching mechanism will obviously need to be extended so that changing one of the `additional_files` produces a new cache key. I haven't spent enough time looking at the code yet to figure out the best way to do this, but my rough thinking is that methods like Store.clone and its callees will take an additional parameter containing either
- `additional_files` as is; or
- A dictionary mapping additional_files keys to file contents (if it's desirable to read the files earlier to fail fast)

Then Store.db_repo_name will compute a hash of the files (SHA2 for example), and combine it into the returned repo name. A bit of care will probably be needed to avoid reading the files twice, both for efficiency and to avoid race conditions if the file changes in between. My guess is that Store._new_repo should probably handle the writing, under the `exclusive_lock` and `clean_path_on_failure` context managers.

Once a repo that uses this feature is installed once, future runs of `pre-commit` will pay the cost of reading the `additional_files` and hashing their content as part of computing the cache key. For the typical use cases people are asking for, there are only a handful of files and they're small (kilobytes rather than gigabytes) so I expect this cost to be unnoticeable.

There are still a few issues I haven't mentally sorted out yet - I'll probably have a better idea once I've dug into the code more:
- [ ] What happens if one of the `additional_files` is dirty in the repo, or is modified by another pre-commit hook? I imagine this is similar to `.pre-commit-config.yaml` itself being dirty and can be handled similarly.
- [ ] Should `${srcdir}` correspond to the root of the repo, or the directory where `.pre-commit-config.yaml` sits? Or is it worth having two different tokens to refers to these two paths?
- [ ] Which file and directory attributes is it important to copy? I imagine that at least the execute bit is important. I'd suggest following symlinks (rather than copying the symlink itself)
- [ ] Does the directory holding a copy of the files need to be kept around? For lockfiles (requirements.txt, Cargo.lock etc) probably not, but this is a generic mechanism and users might find other use cases where the files that are copied are then used by the hook. Keeping the files around also makes sense for debugging.

There are also a couple of features that could possibly be added in later versions but are probably a bit complicated for a first pass:
- Allow `additional_files` to support globs/directories/extended globs (with `**` to match multiple levels). To allow that future support, we should probably reserve use of `*` and `?` in filenames so that their meaning can change in future.
- Allow `..` in `additional_files`, to refer to files above `.pre-commit-config.yaml` in the repo.

### Security

I'm assuming that there are no security concerns, because when running pre-commit you're already trusting the person who wrote `.pre-commit-config.yaml` and the people who wrote the hooks to run arbitrary code on your computer.

### pre-commit --version

N/A - feature proposal

### .pre-commit-config.yaml

```yaml
N/A - feature proposal
```

**Comment by asottile** [comment]
please don't do this. the answer was you've already found is a very firm and consistent no
