### ISSUE TITLE
Specifying additional_dependencies to work on Apple M1 silicon chip

### ISSUE THREAD

**Issue by filipchristiansen** [pre-commit/pre-commit#2659]
Using (e.g.) [PyLint](https://github.com/PyCQA/pylint) as pre-commit hook, one might want to specify `additional_dependencies`.

For (e.g.) TensorFlow, on an intel chip one would specify `tensorflow`, while on a silicon chip one would specify `tensorflow-macos`. Is there a way to write this dependency in  the `.pre-commit-config.yaml` file in a way that it works for both intel and silicon chips?

**Comment by asottile** [comment]
please fill out the issue template it's there for a reason. there's also a duplicate with an answer (use environment specifiers) if you search which it prompts you to do
