### ISSUE TITLE
pre-commit run --all-files was working on uncommitted files

### ISSUE THREAD

**Issue by the-bort-the** [pre-commit/pre-commit#2660]
### search you tried in the issue tracker

uncommitted

### describe your issue

After installing pre-commit for a local repo, I was able to run `pre-commit run --all-files` on uncommitted files and it would show me `shellcheck` warnings, errors, etc. as I was making changes. Before installing `pre-commit` I had several scripts and the `pre-commit run --all-files` worked; these changes remained uncommitted in VSCode until all warnings, errors had been fixed.

After a successful commit to remote, I made several new scripts and now these files are being skipped, despite having the same errors within `shellcheck`. These are uncommitted changes. Now If I update a script which existed before installing `pre-commit`, and make a bad change knowingly, `pre-commit run --all-files` will pick up on that; that change is also uncommitted. 

I'm curious how I can continue on with getting `pre-commit` feedback with uncommitted changes. It seems as the pre-commit existing scripts are "pre-committable" and any script added after `pre-commit` was installed just gets skipped until I actually commit. 

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
```

### ~/.cache/pre-commit/pre-commit.log (if present)

No logs

**Comment by asottile** [comment]
in the future please include specific reproduction steps.  I can guess at what you mean but it's not helpful to waste my time guessing. i think you're misunderstanding "uncommitted" and lumping together both "untracked" (has never been in the repo, is not among the repo file list) and "unstaged" (a not-staged modification to a repo file). pre-commit will only ever send files to tools that are part of the repository
