### ISSUE TITLE
First tutorail in docs throws an error

### ISSUE THREAD

**Issue by sizhky** [pre-commit/pre-commit#2663]
### search you tried in the issue tracker

ImportError: cannot import name '_unicodefun' from 'click'

### describe your issue

I followed the following tutorial for running black on all python files in a repo

https://pre-commit.com/#install

and got 

`ImportError: cannot import name '_unicodefun' from 'click'`

### pre-commit --version

pre-commit 2.21.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
```

**Comment by sizhky** [comment]
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

```

Update black's `rev`

**Comment by asottile** [comment]
it's just a sample to show the structure and is not meant to be kept up to date. you can use `pre-commit autoupdate` to get an up to date config

**Comment by MarcoGorelli** [comment]
Newcomers tend to copy-and-paste from documentation to try things out, if they get an error they'll tend to assume that something went wrong with their installation

I understand not wanting to always keep it pinned to the latest versions, but at least not pinning to a broken rev seems like a reasonable ask
