### ISSUE TITLE
Question: Is there a way to reference a config file when defining a hook

### ISSUE THREAD

**Issue by mh-trimble** [pre-commit/pre-commit#2679]
I want to create a hook for scalafmt for my team and use that hook to include the scalafmt.conf file, so we can specify that in one place and not have to copy that file to each of our multi repo setup.

**Comment by asottile** [comment]
what have you tried so far so I can help you get there?

**Comment by mh-trimble** [comment]
I have this `.pre-commit-hooks.yaml`
```
- id: scalafmt
  name: ScalaFMT
  description: "Format scala files with scalafmt"
  entry: scalafmt -c .scalafmt.conf
  language: system
  types: [scala]
  exclude_types: [sbt]
```
and I tried also using a script but I seem to only be able to reference a script in the directory where the hook is run nothing from where the hook is written

**Comment by asottile** [comment]
can you show your `script` attempt?

**Comment by mh-trimble** [comment]
```
- id: scalafmt
  name: ScalaFMT
  description: "Format scala files with scalafmt"
  entry: test.sh
  language: script
  types: [scala]
  exclude_types: [sbt]
```

where `test.sh` is
```
#!/usr/bin/env bash

scalafmt -c .scalafmt.conf $@
```

**Comment by mh-trimble** [comment]
yes the quoting was just due to me cobbling something together (I usually run shellcheck over my scripts, as I am not a bash wizard) - what do you mean by the `exec` bit (see the not bash wizard)?

**Comment by asottile** [comment]
```
foo bar
```

creates a process tree like:

```
(caller)
  \
    bash
       \
         foo bar
```

````
exec foo bar
```

gives you

```
(caller)
  \
    foo bar
```

as it replaces the process
