### ISSUE TITLE
Feature Request: more options for specifying file list to run against

### ISSUE THREAD

**Issue by dnephin** [pre-commit/pre-commit#268]
Currently `run` supports either a list of files, `--all-files` or stagged file.

I was hoping to either pass in a list of files on stdin (`--files -`, which would handle most cases) or by specifying a sha (or maybe even range of sha's) to generate the file list.

Does this support already exist and I missed it?

**Comment by chriskuehl** [comment]
What would you want specifying a (commit?) SHA to do?

**Comment by dnephin** [comment]
Oh right, I would want it to run against all files changed in that sha. Similar to staged but post commit.

**Comment by asottile** [comment]
Would it be sufficient to document these?  There's too-many-to-count ways to grab a list of filenames that can be satisfied in other ways:

- A sha: `git diff 857fd4 857fd4^ --name-only | xargs pre-commit run --files`
- A range of shas: `git diff 3d90b0 857fd4 --name-only | xargs pre-commit run --files`
- Stdin: `... | xargs pre-commit run --files`
- etc.

**Comment by dnephin** [comment]
Oh ya, I didn't realize `xargs ... --files` would work. That's all I needed!
