### ISSUE TITLE
Caching in docker

### ISSUE THREAD

**Issue by rusmux** [pre-commit/pre-commit#2680]
I'm trying to install pre-commit inside a docker image. In the latest versions of Docker there is an option to [cache](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mounttypecache) dependencies using [BuildKit](https://docs.docker.com/build/buildkit/).

Example from the [documentation](https://docs.docker.com/build/cache/#use-the-dedicated-run-cache) of how to cache apt packages:

```Dockerfile
RUN \
    --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y git
```
This way, even if the layers have changed, apt packages will not be re-downloaded, but will be extracted from the cache.

However, when I try to mount the pre-commit directory `/root/.cache/pre-commit`, it doesn't work as expected. Here is a minimal example:

```Dockerfile
FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    pip install -U pip && \
    pip install pre-commit

RUN --mount=type=cache,target=/root/.cache \
    git init && \
    pre-commit sample-config > .pre-commit-config.yaml && \
    pre-commit install --install-hooks

CMD ["bash"]
```

Despite the `--install-hooks` option, pre-commit does not create environments:

```
...
#6 0.224 Initialized empty Git repository in /.git/
#6 0.424 pre-commit installed at .git/hooks/pre-commit
#6 DONE 0.5s
...
```

If I don't use caching, everything works fine.

Is there a way to achieve caching environments in Docker?

**Comment by asottile** [comment]
the docs on the website address this, have you followed them?
