### ISSUE TITLE
Question: hook override file or similar personal configuration

### ISSUE THREAD

**Issue by simonrw** [pre-commit/pre-commit#2688]
Hi, thanks for creating and maintaining this tool. I'm a big fan!

We use pre-commit to define our repository hooks, but I may want to add additional hooks that are not shared with the team. Currently (I believe) pre-commit looks in `.pre-commit-config.yaml` for its configuration, and only this place. Is it possible for the tool to look in additional places for per-user configuration that either overrides or augments the configuration stored in `.pre-commit-config.yaml`?

I realise there may be issues when pre-commit stashes untracked changes to test just the staged changes (a feature I _love_ :heart: ) - I'm just curious.

Thanks

**Comment by asottile** [comment]
please search the issue tracker, there are several duplicates

**Comment by Clindbergh** [comment]
@simonrw #1887 might be helpful.
