### ISSUE TITLE
2nd-class support Julia

### ISSUE THREAD

**Issue by jmuchovej** [pre-commit/pre-commit#2689]
Would `pre-commit` be open to supporting Julia as a first-class language? There's at least one project that Julia seem keen to have `pre-commit` support ([`JuliaFormatter.jl`][jlfmt-support]). I realized in attempting to provide `pre-commit` support that there's no first-class support for Julia.

I believe I'd be open to making a PR to provide said support, but wanted to ask if it's something `pre-commit` would be open to supporting, in the first place. 🙂 

[jlfmt-support]: https://github.com/domluna/JuliaFormatter.jl/issues/498

**Comment by asottile** [comment]
yep!  new languages are always welcome -- there's certain "classes" of languages defined -- 2nd class is the easiest to get started with ~usually -- https://github.com/pre-commit/pre-commit/blob/main/CONTRIBUTING.md#adding-support-for-a-new-hook-language

**Comment by jmuchovej** [comment]
OOH. I see. I totally missed the varying classes of support. Thanks for the pointer! 🙂 I'll definitely start-off with 2nd class support and go from there. 😄
