### ISSUE TITLE
What is the best practice regarding tool version management.

### ISSUE THREAD

**Issue by ldng** [pre-commit/pre-commit#2692]
Hello,

not really an issue, I just wondered if there was a best practice regarding tool version management.

My concrete case is that my python project install a version of black which is configured within pyproject.toml.
How do I make sure the version match between pyproject.toml and pre-commit ?

More broadly, how do I make sure that my package manager (pyproject.toml, Cargo.tom, whatever ...) installs a tool version (linter, formater, whatever) that matches the version configured in .pre-commit-config.yaml ?

I doubt it, but could a hook dynamically reconfigure required version ?

Thanks.

**Comment by asottile** [comment]
please search the issue tracker, there are several duplicates

**Comment by ldng** [comment]
I did search and did not find anything relevant.
If it is so recurrent, maybe it should be in the documentation (and maybe I missed it, sorry then)
Anyway, your project, your rules. I will not bother you further.
