### ISSUE TITLE
[Q] Passing of initial git-hook arguments to the plugin

### ISSUE THREAD

**Issue by vic123** [pre-commit/pre-commit#2711]
I've debugged the code a little bit and did not find a way how to pass original git-hook arguments along with the 
`retcode, out = language.run_hook(hook, filenames, use_color)` in run.py _run_single_hook()
I'm evaluating your solution for server-side bare repository usability. And expect that will need all possible info.
Am I missing something or such behavior is out of the concept?
Thank you!

**Comment by asottile** [comment]
_usually_ they are not needed, however pre-commit exposes those as environment variables under the `PRE_COMMIT_*` namespace
