### ISSUE TITLE
pre-commit image in their own Github package

### ISSUE THREAD

**Issue by christopherekfeldt** [pre-commit/pre-commit#2716]
Hi, I have a feature request for pre-commit. I would love to get is that pre-commit have their own package (image) which is viable on their Github. This way we don't need to have our own Docker image for pre-commit , but can instead use yours and always have the latest version released. 

A good example can be seen here in : https://github.com/elementary-data/elementary/pkgs/container/elementary
Is this something you guys have looked into? Or think can be done. We love simplifying our workflows by accessing really slimmed images maintained by the creators of the tool we use.

**Comment by christopherekfeldt** [comment]
> please search the issue tracker, there are several duplicates

Can you reference me to one? I can't seem to find it.

**Comment by asottile** [comment]
if you're not going to put the effort in why should I be your low latency search engine?
