### ISSUE TITLE
pre-commit CI force push of updates will remove subsequent commits on Pull Requests

### ISSUE THREAD

**Issue by Zeitsperre** [pre-commit/pre-commit#2719]
### search you tried in the issue tracker

force push commits

### describe your issue

With precommit.ci configured to make automatic pull requests in my repositories, if the PR is modified by a user and is not merged before the next scheduled update, the pre-commit CI bot will force push updates to the commit that opened the PR and remove all subsequent commits made.

I was unaware of this behaviour (it did not set me back very long, thankfully), so I was thinking it would be helpful to make a mention of this behaviour somewhere? Another option would be to simply add another commit to the PR when it seems that the branch is unmerged and modified by users.

Thanks!

### pre-commit --version

pre-commit.ci

### .pre-commit-config.yaml

```yaml
<irrelevant>
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A

**Comment by asottile** [comment]
please read the first line of the issue template -- this is not the place to report issues

**Comment by Zeitsperre** [comment]
Sorry about that. My bad!
