### ISSUE TITLE
New flag to run only against changed files in branch

### ISSUE THREAD

**Issue by ysawa0** [pre-commit/pre-commit#2721]
When running pre-commit as part of CI such as Github Actions it's necessary to run `pre-commit run --all-files` as the changes have already been committed and there's no native functionality to run the hooks only against files changed in a branch.

Suggestion is to implement a new flag such as `pre-commit run --changed-files` (open to other suggestions on the naming) that will

* compare current branch vs main branch and get a list of files that were changed
* run pre-commit hooks only against those files

while running `pre-commit run --all-files` in CI is fine for small repos as you add more hooks and more files the CI tends to run too long. if maintainers are open to this idea I can take a stab at implementing this.

**Comment by asottile** [comment]
[that's what `--from-ref` and `--to-ref` are for](https://pre-commit.com/#pre-commit-run)
