### ISSUE TITLE
CI: Error in build process for GitHub Actions

### ISSUE THREAD

**Issue by jakob-bagterp** [pre-commit/pre-commit#2750]
### search you tried in the issue tracker

is:issue is:open ci build process

### describe your issue

I'm using the CI version of pre-commit via GitHub Actions on several repositories, and since version 3.0.2 until now 3.0.4 the build process fails. It worked fine in version 3.0.1, and little has been changed in my code that would justify the errors.

### pre-commit --version

pre-commit 3.0.2, 3.0.3, 3.0.4

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        exclude: test/_mock_data
        args:
        -   --expand-star-imports
        -   --ignore-init-module-imports
        -   --in-place
        -   --remove-all-unused-imports
        -   --remove-duplicate-keys
        -   --remove-unused-variables

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args:
        -   --py310-plus

ci:
    autofix_prs: true
    autoupdate_schedule: quarterly
    submodules: false
    # TODO: Temporarily ignored hooks since the CI checker doesn't use Python 3.8 and not 3.10, which gives syntax errors.
    skip: [check-ast, check-docstring-first, debug-statements, flake8]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Relevant repositories with examples of error messages:

- https://github.com/jakob-bagterp/browserist
-- https://results.pre-commit.ci/run/github/446597664/1675657197._3ym76UUQMatbYxSRe8KDw
- https://github.com/jakob-bagterp/timer-for-python
-- https://results.pre-commit.ci/run/github/381935468/1675667507.L4auhw61Tm2Ab1ni0mv4kg
- https://github.com/jakob-bagterp/colorist-for-python
-- https://results.pre-commit.ci/run/github/453327826/1675678663.AWtudmz1QhConscFfDGbTw

<img width="747" alt="Screenshot 2023-02-07 at 20 51 37" src="https://user-images.githubusercontent.com/25110864/217351389-eaad3ff7-a34e-405e-8640-4e3e04626d01.png">

<img width="1301" alt="Screenshot 2023-02-07 at 21 00 31" src="https://user-images.githubusercontent.com/25110864/217352357-f4fd015e-a9a3-4309-ac5f-124e5962e88c.png">

**Comment by asottile** [comment]
have you tried googling your error message?
