### ISSUE TITLE
Feature Request (and offer to help): multiple configuration files

### ISSUE THREAD

**Issue by thisfred** [pre-commit/pre-commit#2754]
A situation I've encountered more than once is that pre-commit is used to enforce a minimal coding standard on a project, but that there are addtional hooks individual developers find helpful that they would like to add for themselves, without forcing them on everyone working on the project. (Hooks that take a long time to run, for instance, may present different trade-offs to different people.)

It would be fantastic if there was a way to have a way to allow additional configuration files that add hooks.

I realize that this is probably not a super simple feature to add (what happens when the configurations specify the same hooks with conflicting configuration values), and it may be too rare of a use case to be worth the cost of maintenance, but if others feel this is worthwhile, and there's a chance a version of it would be approved, I'd be happy to take an initial stab at implementing.

**Comment by asottile** [comment]
please search the issue tracker -- there are many duplicates
