### ISSUE TITLE
Groovy-lint hook

### ISSUE THREAD

**Issue by Pymann** [pre-commit/pre-commit#2757]
### search you tried in the issue tracker

groovy

### describe your actual problem

Actually writing in groovy is quite important, because of jenkins needs.
Jenkins Libraries are in use for several things: foss-scanning, testing, release, daily-builds, code-analyzation

Therefore the effort becomes big and linting groovy code would be of great help.
I saw a linter project for groovy: npm-groovy-lint that maybe is working under Linux only?

Maybe you can add this hook and anyhow make it xplatform (Linux/Windows).

### pre-commit --version

2.20.0

**Comment by asottile** [comment]
pre-commit is just a framework. it does not implement linters
