### ISSUE TITLE
Remove cached installed by current repository

### ISSUE THREAD

**Issue by yasirroni** [pre-commit/pre-commit#2758]
### search you tried in the issue tracker

is:issue remove cache current repository 

### describe your actual problem

Based on the doc about [pre-commit gc](https://pre-commit.com/#pre-commit-gc) and running `pre-commit gc -h`, no information about remove environment installed using `pre-commit install` on current repo.

Also, no doc that clearly state running `pre-commit uninstall` + `pre-commit gc` will remove environment on `~/.cache/pre-commit` that is related to current repository.
___
So, I request a feature to remove cache of current repository, but not others. If it is already supported, an updated doc will be appreciated.

### pre-commit --version

pre-commit --version

**Comment by asottile** [comment]
`pre-commit gc` removes unused repostories

there is intentionally no way to interact with the cache besides completely clearing it -- you should instead figure out why your cache is incorrect (perhaps you are not selecting versions correctly or specifically)

the framework intentionally does not give you a cargo cult way to clear the cache -- you should instead fix your configuration.  there's a few duplicates about this specific idea (clearing based on a repository name) but this is not going to be implemented

**Comment by LecrisUT** [comment]
One example of this issue that I've encountered is with 
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - "ruamel.yaml>=0.16.6"
```
At some point I got a broken version which errored with
```
error: Skipping analyzing "ruamel": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```
If I change the text of `additional_dependencies` I am able to get a more recent version.

The issue would be that there is no clear way how to refresh that specific pre-commit, and since I am using a system installed `pre-commit` with multiple projects it is hard to track down which cache has this issue

**Comment by asottile** [comment]
yeah and you shouldn't do that -- and there's not going to be additional features to enable and encourage doing it wrong.  use == and then there's a clear way to adjust your versions
