### ISSUE TITLE
Cache does not work correctly when mounted as different users

### ISSUE THREAD

**Issue by jgopel** [pre-commit/pre-commit#2762]
### search you tried in the issue tracker

cache user

### describe your issue

Reproduction steps:
1. Delete the pre-commit cache, if there is already one (by default, `~/.cache/pre-commit/`)
2. Start a docker container with username1 (as far as I can tell, this doesn't matter, but for me this is `jonathan`) with the cache directory mounted
3. `pre-commit run -a` to generate the cache
4. Exit the docker container
5. Start a docker container with username2 (for me, `dev`) with the cache directory mounted
6. `pre-commit run -a` to try to reuse the cache.

Expected outcome:
`pre-commit` runs as normal, preferably reusing the cache (if relevant), but generating a new one for the different user would also be acceptable.

Actual outcome:
```
pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
An error has occurred: InvalidManifestError:
=====> /home/jonathan/.cache/pre-commit/repolj54wa4t/.pre-commit-hooks.yaml is not a file
Check the log at /home/dev/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 3.0.4

### .pre-commit-config.yaml

```yaml
Applies to many
```

**Comment by asottile** [comment]
the cache is not relocatable. please search for duplicates better next time
