### ISSUE TITLE
print warning when cannot find pre-commit command

### ISSUE THREAD

**Issue by gzm55** [pre-commit/pre-commit#2777]
### search you tried in the issue tracker

warning

### describe your actual problem

The hook [template](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/resources/hook-tmpl#L18) now always fail the hook when cannot execute pre-commit module. Can we add an switch (env or git config) to override this behaivor by just print a warning log then skipping thee python hooks?

### pre-commit --version

pre-commit 3.0.4

**Comment by asottile** [comment]
no? how did it get installed if `pre-commit` wasn't available in the first place?

**Comment by gzm55** [comment]
> no? how did it get installed if `pre-commit` wasn't available in the first place?

the virtual env may be removed
