### ISSUE TITLE
Podman support by using docker api instead of the executable

### ISSUE THREAD

**Issue by komima** [pre-commit/pre-commit#2779]
### search you tried in the issue tracker

podman

### describe your actual problem

To support `docker_image` / `docker` hooks with podman as backend and without any wrapper scripts, [Docker python library](https://docker-py.readthedocs.io/en/stable/containers.html) (which uses the api) could be used instead of running the executables with subprocess.

This would simplify the workflow with podman, since currently these hooks require either actual docker binaries present (which are connecting to the podman api) or wrapping the podman executable with a `docker` alias/shell wrapper/etc.

This could also help with the error messages, since errors thrown from the api when launching the container are separate from the return code of the container.

### pre-commit --version

pre-commit 3.1.0

**Comment by asottile** [comment]
can't take on that dependency -- it's been a constant thorn in my side in the past
