### ISSUE TITLE
pass files conditionally on changed files

### ISSUE THREAD

**Issue by taozhou-glean** [pre-commit/pre-commit#2781]
### search you tried in the issue tracker

"pass_filenames", "conditionally", "all_files" etc

### describe your actual problem

We have eslint hook enabled and it runs on staged files during precommit just fine. But sometimes when people modified the eslint config file, we actually want to make sure the hook run on all files instead, otherwise, some errors may not be captured by the hook as affected files not included in the change and leave the main branch in an error/warning state.

As the underneath tool like `eslint` seems work as expected (lint on passed in files if has), so I am wondering if this should be supported by the pre-commit instead. The idea here is that if we can set `pass_filenames` to false under some conditions based on the changed files, then we can let it run on all files. Or maybe new option like `run_all_if_changed` etc

I thought about some alternatives like creating a custom eslint hook plugin tailored to this use case, or run a local hook with shell script including the custom logic, but it would be great if it can be supported out of box. Also let me know if there is any other workaround.

### pre-commit --version

pre-commit 2.21.0

**Comment by asottile** [comment]
if you're changing the configuration you should manually run with `--all-files` (this is the conclusion that came up last time as this issue is a duplicate)
