### ISSUE TITLE
Allow unstaged config

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2784]
### search you tried in the issue tracker

n/a (found dupe)

### describe your actual problem

Came here wanting to ask for #848 and read through that thread. Could you explain why it's not possible (or not worth it) to load the config first, then stash and continue the commit with the already loaded config?

Current behavior forces you to commit changes to config first even if you don't know if they're final, requiring rebase surgery afterwards or preventing commits until all work is done.

### pre-commit --version

3.0.0

**Comment by asottile** [comment]
because then it will use a config that's not committed which is wrong

**Comment by janosh** [comment]
What about adding a config option to say that's right.

**Comment by asottile** [comment]
no means no
