### ISSUE TITLE
Custom path `environment.yml`

### ISSUE THREAD

**Issue by tdegeus** [pre-commit/pre-commit#2792]
### search you tried in the issue tracker

environment.yml

### describe your actual problem

In my repo I already have a `environment.yml` that I use for CI. For the pre-commit hook I would like to have a file with path `.pre-commit-environment.yml`

### pre-commit --version

pre-commit 3.0.4

**Comment by asottile** [comment]
pre-commit does not install from the repository under test

**Comment by tdegeus** [comment]
Thanks for replying. However, I understand nothing of your reply ;)

**Comment by asottile** [comment]
there are several duplicates please search
