### ISSUE TITLE
Show hook output while it's executing

### ISSUE THREAD

**Issue by claudiu-wg2** [pre-commit/pre-commit#2794]
### search you tried in the issue tracker

log output; print output while executing; real time output

### describe your actual problem

Hi, I noticed that when running with `--verbose` the hook output is printed only after the hook finishes executing.
Is there a way to print the hook output while it's executing to get a sense of the progress?

### pre-commit --version

pre-commit 3.0.4

**Comment by asottile** [comment]
please search more next time as there are duplicates but also think about the current output and how what you're suggesting is impossible

**Comment by claudiu-wg2** [comment]
How is it impossible to print logs from the hook? I don't get it...
