### ISSUE TITLE
Pre-commit causing the index to report deleted files when core.fsmonitor enabled

### ISSUE THREAD

**Issue by jarshwah** [pre-commit/pre-commit#2795]
### search you tried in the issue tracker

fsmonitor stashed

### describe your issue

After committing a file, when pre-commit runs, it reports thousands of files as deleted and then stashes and unstashes them.

This has happened to several members of our team in the last 24 hours.

It only happens when git is configured to run with fsmonitor:

```
git config core.fsmonitor true
```

Git version: git version 2.39.2 (also reproducible with 2.39.1)

This isn't caused by pre-commit, but is a PSA for others using pre-commit and can't figure out why this might be happening.

When the issue is presenting you can get git to show that thousands of files are being deleted by running:

```
git diff-index --ignore-submodules --exit-code --no-color --no-ext-diff $(git write-tree) --
```

Which is what pre-commit effectively runs when checking for unstaged files: https://github.com/pre-commit/pre-commit/blob/2822de9aa6284f2de1c5ff8d0884b38bc553afa5/pre_commit/staged_files_only.py#L52-L56

I'm unsure if  running `git update-index` before `git write-tree` helps, [but the docs seem to suggest](https://git-scm.com/docs/git-write-tree) that the index should always be updated before using write-tree:

> In order to have that match what is actually in your directory right now, you need to have done a git update-index phase before you did the git write-tree

Disabling fsmonitor resolves the issue. Passing `--no-fsmonitor` also seems to help but I haven't re-confirmed this step.

## Reproducing the issue

```
$ git config core.fsmonitor true
$ git checkout -b test-branch
Switched to a new branch 'test-branch'

$ echo "test 3" >> newfile.txt 
$ git add . 
$ git status
On branch test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   newfile.txt

$ git commit -a -m "will it fail?"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/josh/.cache/pre-commit/patch1677888420-10129.
trim trailing whitespace.................................................Passed
check python ast.....................................(no files to check)Skipped
check for case conflicts.................................................Passed
[INFO] Restored changes from /Users/josh/.cache/pre-commit/patch1677888420-10129.
[test-branch 7c899582c19] will it fail?
 1 file changed, 1 insertion(+)
 create mode 100644 newfile.txt

$ git status
On branch test-branch
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    src/tests/__init__.py
	deleted:    src/tests/site/__init__.py
	deleted:    src/tests/site/test_models.py
        ... lots more files ...

no changes added to commit (use "git add" and/or "git commit -a")

$ git status | wc -l
   15298

$ git restore .

$ git status 

On branch test-branch
nothing to commit, working tree clean
```

Reproducing with just git commands (no pre-commit):

```
$ git diff-index --ignore-submodules --exit-code --no-color --no-ext-diff $(git write-tree) --

:100644 000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0000000000000000000000000000000000000000 D	src/tests/__init__.py
:100644 000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0000000000000000000000000000000000000000 D	src/tests/site/__init__.py
:100644 000000 d8edaad92120781998e811277f966551b12fc823 0000000000000000000000000000000000000000 D	src/tests/site/test_models.py

... thousands more files ...

# but the files *are* on disk

$ ls src/tests/__init__.py
src/tests/__init__.py
```

Git seems to do the right thing when using `update-index` with `--no-fsmonitor`:

```
$ git update-index --really-refresh --no-fsmonitor
warning: core.fsmonitor is set; remove it if you really want to disable fsmonitor

$ git diff-index --ignore-submodules --exit-code --no-color --no-ext-diff $(git write-tree) --
> no output
```

### pre-commit --version

pre-commit 3.1.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast      
      - id: check-case-conflict
```

### ~/.cache/pre-commit/pre-commit.log (if present)

not present

**Comment by asottile** [comment]
you'll need to provide more information like commands run and output (like the template prompts you to)

**Comment by jarshwah** [comment]
@asottile I've added steps to reproduce after re-enabling fsmonitor, please let me know if there's anything else needed. To be clear, I think this is a problem with `git` rather than `pre-commit`, but the issue presents itself when using pre-commit and I suspect you'll have a few folks running into this issue with no idea why it's happening.

**Comment by asottile** [comment]
oh then you probably want to report it to git -- their mailing list is `git@vger.kernel.org`

**Comment by jarshwah** [comment]
Reported upstream - [link to the mailing list mirror](https://lore.kernel.org/git/CAPbDM0d5Xe=KTLECDCJYtpzmBt2wqzZrMWVcbiisM+abopenig@mail.gmail.com/)

**Comment by jarshwah** [comment]
Coming back to this, the response on the mailing list suggests this may be an issue with how pre-commit is running `diff-index` without running `update-index`: https://lore.kernel.org/git/8afb1988-df49-d759-ead8-1bd384f09c82@gmx.de/

> I suspect that the issue is a missing `git update-index --refresh`. While
`git diff` refreshes the index automatically, `git diff-index` does not
(when you use low-level commands like `diff-index` you need to do such
things explicitly).

However, https://github.com/pre-commit/pre-commit/pull/2890 suggests that `update-index --refresh` did not help. Since I'm unable to reproduce (recloned/disabled fsmonitor) I'm not able to repro for the git folks.
