### ISSUE TITLE
Add an option to test staged files without stashing unstaged changes

### ISSUE THREAD

**Issue by JulienGrv** [pre-commit/pre-commit#2803]
### search you tried in the issue tracker

stash, disable stash, no stash

### describe your actual problem

Hi @asottile,

When running a build in the background, performing a commit triggers pre-commit and a stash of the unstaged changes, which in turn will cause the background build to compile files without the wanted working tree changes.

Also, if I take a hook like the Python code formatter Black, Black only checks the files passed to it as input, which makes a stash a costly operation where I think a `git diff --cached --name-only` could be enough. Speed is from a user perspective important for Git hooks even though I understand that stashing unstaged changes can be safer in some situations.

For the 2 issues mentioned above, I am asking if it is possible to offer a different behaviour which would not stash and simply pass the list of staged files. This could be an option at the top-level and/or repo level in the `.pre-commit-config.yaml` file, maybe something like: `stash_unstaged_changes: false`. I am still completely open to suggestions regarding how this option should be best implemented.

As a side note: in the case you validate this feature request, I could do the implementation except if you prefer to do it yourself of course.

Best, Julien

### pre-commit --version

pre-commit 3.1.1

**Comment by asottile** [comment]
this would break a fundamental part of the tool and has been proposed before and rejected. please search harder next time
