### ISSUE TITLE
Allow local dependency in additional_dependencies

### ISSUE THREAD

**Issue by taozhou-glean** [pre-commit/pre-commit#2804]
### search you tried in the issue tracker

additional_dependencies, local dependency

### describe your actual problem

We have a local eslint plugin that we have not published yet and likely stay that way as it's very tight with our codebase, wondering if there is any way to add that to the `additional_dependencies` so it can be installed in the pre-commit env ?

I tried change it to `file:path_to_our_plugin`, but relative path does not work there as the root is different under pre-commit install: `/Users/xxx/.cache/pre-commit/repokg41wiin`, wondering if there is any workaround for this ? thanks

### pre-commit --version

pre-commit 2.21.0

**Comment by asottile** [comment]
there are many duplicates -- pre-commit will never install from the repository under test -- please do some more due diligence next time
