### ISSUE TITLE
Global configuration of files / exclude

### ISSUE THREAD

**Issue by asieira** [pre-commit/pre-commit#281]
A top-level entry of `files` and `exclude` that was used as the default by all hooks where those options are not defined would be really useful.

**Comment by asottile** [comment]
Unfortunately,  this suffers from the same problem as #240 in that the top level is currently a list and not a dictionary

**Comment by asottile** [comment]
Only took two years 😆 but I'm finally able to implement this, PR #617 adds a `global_exclude`.

**Comment by asottile** [comment]
This is now available in [v1.1.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.1.0)!  Thanks again for the issue!

**Comment by asottile** [comment]
@Gby56 don't bump 5 year old issues with off topic questions
