### ISSUE TITLE
additional_dependencies fails to install prettytable 

### ISSUE THREAD

**Issue by jmtatsch** [pre-commit/pre-commit#2816]
### search you tried in the issue tracker

additional_dependencies fail

### describe your issue

I was trying to write a hook to run pip-licenses to autogenerate a file with license notices

 https://github.com/raimon49/pip-licenses/issues/107

I was expecting that with `language: python` it would pip install the pip-licenses package in the repo with the necessary dependencies. Which it doesn't. Then I tried to force it with `additional_dependencies: [prettytable]` to install the missing lib which also didn't work.

Am I missing something? Doing something wrong?

### pre-commit --version

3.1.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/jmtatsch/pip-licenses
    rev: 0b6176619a8314c88e7817e3b51c59b1ffd4943a
    hooks:
    -   id: update-pip-licenses
        additional_dependencies: [prettytable]
        verbose: true
```

### ~/.cache/pre-commit/pre-commit.log (if present)

pre-commit run --all-files                                                                                                                          tatsch@knecht3
[INFO] Installing environment for https://github.com/jmtatsch/pip-licenses.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/tatsch/.cache/pre-commit/repoijlcclt_/py_env-python3.10/bin/python', '-mpip', 'install', '.', 'prettytable')
return code: 1
stdout:
    Processing /home/tatsch/.cache/pre-commit/repoijlcclt_
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [8 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/home/tatsch/.cache/pre-commit/repoijlcclt_/setup.py", line 34, in <module>
              from piplicenses import __author__ as AUTHOR
            File "/home/tatsch/.cache/pre-commit/repoijlcclt_/piplicenses.py", line 43, in <module>
              from prettytable import ALL as RULE_ALL
          ModuleNotFoundError: No module named 'prettytable'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /home/tatsch/.cache/pre-commit/pre-commit.log

**Comment by asottile** [comment]
this isn't a pre-commit problem. the tool you're using does not build from source. it should specify that dependency in it's build deps in project.toml
