### ISSUE TITLE
A way to report (on-disk) sizes of hooks

### ISSUE THREAD

**Issue by kratsg** [pre-commit/pre-commit#2817]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+size+is%3Aclosed

### describe your actual problem

pre-commit.ci has maximum tier sizes (understandable) however there's no straightforward way to determine the size of various hooks we pull in (as far as I can tell) besides digging out all the cloned repos locally and run `df` on each.

For example, I get a message like this:

```
build of https://github.com/jonasbb/pre-commit-latex-hooks@v1.4.0 for rust@system exceeds tier max size 250MiB: 255.9MiB
```

which is fine, but how do I know which hooks are bloating it up, or if it's an entire repo?

### pre-commit --version

pre-commit 2.20.0

**Comment by asottile** [comment]
you can utilize `du -hs` to determine the on disk size. you'll have to like around the cache a bit but I don't really want to expose a first class way to inspect this
