### ISSUE TITLE
Bro, the first line of the issue indicates why I'm trying to bring this up again, and why it's not helpful to flat out refuse to discuss something

### ISSUE THREAD

**Issue by wlritchi** [pre-commit/pre-commit#2819]
### search you tried in the issue tracker

I read through 30 pages of issues trying to cover the bases

### describe your actual problem

Please feel free to close this one as spam, but it's pretty rude to ignore the last one entirely

### pre-commit --version

pre-commit 3.1.1

**Comment by asottile** [comment]
bro it's not productive to try and continually re-litigate decisions that have already been decided
