### ISSUE TITLE
Documentation for python language is misleading

### ISSUE THREAD

**Issue by kasium** [pre-commit/pre-commit#2821]
### search you tried in the issue tracker

`RuntimeError: failed to find interpreter for Builtin discover`

### describe your issue

I just stubbled across an issue in the documentation.
According to the [docs](https://pre-commit.com/#python): 

> python hooks work without any system-level dependencies. It has been tested on linux, macOS, windows, and cygwin.

However when you e.g. set the `language_version` field to a python version which is not installed, it fails. According to the issue tracker this is expected, which is fine. 
Therefore, it would be nice if the documentation could reflect, that a fitting python executable must exist on the system. E.g. the [docker documentation](https://pre-commit.com/#docker) states that:

> Support: docker hooks are known to work on any system which has a working docker executable.

Also (just for completeness): a pyenv integration would be great but I guess this is just for linux so it seems not to fit for pre-commit...

### pre-commit --version

latest

### .pre-commit-config.yaml

```yaml
n/a
```

### ~/.cache/pre-commit/pre-commit.log (if present)

n/a

**Comment by pbhuss** [comment]
Under https://pre-commit.com/#overriding-language-version, it clearly states:
> Valid values for specific languages are listed below:
> - python: Whatever system installed python interpreters you have.

**Comment by kasium** [comment]
I might got that wrong but still the docs say no system dependency but there is one. The language_version was just an example

**Comment by asottile** [comment]
correct, `python` must be available already because you're running `pre-commit` which is written in python
