### ISSUE TITLE
List outdated hooks with autoupdate

### ISSUE THREAD

**Issue by kasium** [pre-commit/pre-commit#2822]
### search you tried in the issue tracker

autoupdate

### describe your actual problem

I would like to request a feature for autoupdate. Instead of doing the changes right away, print out the changes in e.g. YAML, plain text or JSON. I would think it similar to `pip list --outdated --format X`.

I think that such a feature could be used by dependency update bots which might want to create JIRA/GitHub issues first before making a code change. Also it could help to just locally check if any update are there w/o changing any file.

I see that this won't be the main used feature but I see it as a nice addition. However, open source is (mostly) unpayed, therefore I understand if this won't be accepted, since you can workaround it with `autoupdate` itself.

_Note: I guess that pre-commit.ci also does a check beforehand or checks the changed files afterwards to create the changelog in the PR message_

### pre-commit --version

pre-commit 3.1.1

**Comment by asottile** [comment]
your config should be version controlled. you can simply run `pre-commit autoupdate` and then look at `git diff ` 

there are a few duplicates already
