### ISSUE TITLE
Hook for running pre-commit on 'git add' rather than on 'git commit'

### ISSUE THREAD

**Issue by why-not-try-calmer** [pre-commit/pre-commit#2825]
_This is a feature request._

### search you tried in the issue tracker

git add

### describe your actual problem

When using pre-commit hooks in a repo the current workflow goes typically like this:
```
git add -A
git commit -m "I hope this is OK"
... pre-commit finds and fixes a formating issue ...
git add -A
git commit -m "Thanks pre-commit!"
```
Would it be possible to let the user opt-in to a `git add` pre-commit hook? Instead of the above we'd have:
```
git add -A
... pre-commit finds and fixes a formating issue ...
git add -A
git commit -m "Thanks pre-commit!"
```
? That's one less step. Even better if in addition to this there's an option for re-adding the files edited by pre-commit, turning the previous into:
```
git add -A
... pre-commit finds and fixes a formating issue, and also re-adds the edited files ...
git commit -m "Thanks, pre-commit!"
```
The lazy programmer will enjoy the two steps spared!

### pre-commit --version

pre-commit 3.1.1

**Comment by asottile** [comment]
there's no such git hook

**Comment by mortenfc** [comment]
This should be reopened, it's not completed. It's a feature request. It could be rejected if you give good reason why the community is wrong., but it's not completed.

**Comment by asottile** [comment]
it's literally impossible. git does not provide such a hook as stated above
