### ISSUE TITLE
pathspec error while initializing environment

### ISSUE THREAD

**Issue by pums974** [pre-commit/pre-commit#2829]
### search you tried in the issue tracker

yes

### describe your issue

On my gitlab-ci workflow, I have this issue that appeared recently:
```
[INFO] Initializing environment for https://github.com/myint/docformatter.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', 'v1.6.0.rc1')
return code: 1
stdout: (none)
stderr:
    error: pathspec 'v1.6.0.rc1' did not match any file(s) known to git
```

Which is partitularly surprising since I'm not even using this version of docformatter

### pre-commit --version

pre-commit-2.21.0

### .pre-commit-config.yaml

```yaml
repos:
    - repo: https://github.com/myint/docformatter
      rev: v1.5.1
      hooks:
          - id: docformatter
            args: [--in-place]

# other linters and checks removed for consiveness
```

**Comment by asottile** [comment]
you've selected a tag that does not exist

also your configuration does not match. please when reporting bugs actually use your exact config

**Comment by pums974** [comment]
Sorry I got confused between my different branches
You are absolutely right
sorry for wasting your time
