### ISSUE TITLE
run all hooks against all files regardless of the hook stages argument

### ISSUE THREAD

**Issue by JaGarRod** [pre-commit/pre-commit#2848]
### search you tried in the issue tracker

pre-commit run all files all stages; all stages all files

### describe your actual problem

I want to run all hooks in all files with `pre-commit run --all-files`. However all hooks with a stages argument "push" are not run. I would like to run all hooks against all files regardless of the hook stages argument. 
Is this possible?

### pre-commit --version

2.20.0

**Comment by asottile** [comment]
each stage works differently so what you're suggesting is not possible.  you could add the `manual` stage and use that perhaps

**Comment by JaGarRod** [comment]
Could explain what the role of the flag --hook-stage in pre-commit run command is? if I execute pre-commit run --all-files --hook-stage push, all hooks with stages: [push] argument plus all hooks with no stages argument specified are executed (this is precisely what I am looking for), is this intended behaviour? I was expecting only hooks with "push" stage would be run

**Comment by asottile** [comment]
the default stage for unspecified stages is all stages (as the documentation states)
