### ISSUE TITLE
Make pre-commit consider a hook as "failed" if it modifies files and still (incorrectly?) exits 0

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#285]
This would allow us to ditch autopep8-wrapper and support a bunch of hooks which refused to be scriptable (yapf, etc.)

**Comment by David2011Hernandez** [comment]
It is possible to "disable" this behavior for a specific hook?

**Comment by asottile** [comment]
no, there's no reason that would be a desirable behavior
