### ISSUE TITLE
Mac OS Ruby issues using cfn_nag fook

### ISSUE THREAD

**Issue by txynidakis** [pre-commit/pre-commit#2855]
### search you tried in the issue tracker

seached for 'missing psych' & 'ruby mac'

### describe your issue

I was running a git commit using VSCode and the commit fails when using cfn_nag_scan.

I can run cfn_nag_scan successfully via cmd

The error is 
`stelligent CFN_NAG.......................................................Failed
- hook id: cfn-nag
- exit code: 1

/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/psych-3.3.2/lib/psych.bundle, 0x0009): Library not loaded: /usr/local/opt/ruby/lib/libruby.3.1.dylib (LoadError)
  Referenced from: <1DA33A18-D9C8-3FC1-BCE5-5F59E99F7D8B> /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/psych-3.3.2/lib/psych.bundle
  Reason: tried: '/usr/local/opt/ruby/lib/libruby.3.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ruby/lib/libruby.3.1.dylib' (no such file), '/usr/local/opt/ruby/lib/libruby.3.1.dylib' (no such file), '/usr/local/lib/libruby.3.1.dylib' (no such file), '/usr/lib/libruby.3.1.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/ruby/3.2.2/lib/libruby.3.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/ruby/3.2.2/lib/libruby.3.1.dylib' (no such file), '/usr/local/Cellar/ruby/3.2.2/lib/libruby.3.1.dylib' (no such file), '/usr/local/lib/libruby.3.1.dylib' (no such file), '/usr/lib/libruby.3.1.dylib' (no such file, not in dyld cache) - /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/psych-3.3.2/lib/psych.bundle
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/psych-3.3.2/lib/psych.rb:13:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/yaml.rb:4:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-model-0.6.6/lib/cfn-model/parser/cfn_parser.rb:3:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-model-0.6.6/lib/cfn-model.rb:3:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-nag-0.0.0/lib/cfn-nag/custom_rule_loader.rb:3:in `<top (required)>'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-nag-0.0.0/lib/cfn-nag/cfn_nag.rb:3:in `require_relative'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-nag-0.0.0/lib/cfn-nag/cfn_nag.rb:3:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-nag-0.0.0/lib/cfn-nag.rb:3:in `<top (required)>'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/gems/cfn-nag-0.0.0/bin/cfn_nag_scan:4:in `<top (required)>'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/bin/cfn_nag_scan:25:in `load'
	from /Users/?????/.cache/pre-commit/repo6sqonemt/rbenv-system/gems/bin/cfn_nag_scan:25:in `<main>'`

### pre-commit --version

pre-commit 3.2.2

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/stelligent/cfn_nag
    rev: v0.8.10
    hooks:
      - id: cfn-nag
        name: stelligent CFN_NAG
        description: Looks for patterns in CloudFormation templates that may indicate insecure infrastructure.
        entry: cfn_nag_scan --input-path
        language: ruby
        files: AWS\/CloudFormation.*?\/.*(json|yaml|yml|template)
```

### version information

```
pre-commit version: 3.2.1
git --version: git version 2.40.0
sys.version:
    3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /usr/local/Cellar/pre-commit/3.2.1/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: FatalError: git toplevel unexpectedly empty! make sure you are not inside the `.git` directory of your repository.
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/3.2.1/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/3.2.1/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 366, in main
    _adjust_args_and_chdir(args)
  File "/usr/local/Cellar/pre-commit/3.2.1/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 180, in _adjust_args_and_chdir
    toplevel = git.get_root()
               ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.2.1/libexec/lib/python3.11/site-packages/pre_commit/git.py", line 69, in get_root
    raise FatalError(
pre_commit.errors.FatalError: git toplevel unexpectedly empty! make sure you are not inside the `.git` directory of your repository.
```

**Comment by asottile** [comment]
this isn't a pre-commit problem but a problem with your ruby installation

**Comment by txynidakis** [comment]
@asottile , I have other hooks in the pre-commit.yaml file and pre-commit works if I comment out the cfn-nag setting.

I'm sorry for my ignorance, but would I see the ruby issue if the other hooks are working as expected?

**Comment by asottile** [comment]
it is impossible to know because you have not shared your configuration file -- but entirely likely since hooks can be implemented in many different languages which are not ruby

**Comment by hofbi** [comment]
@asottile I also ran into the issue reported here because of a missing libyaml. My issue is caused by https://github.com/mattlqx/pre-commit-search-and-replace. While browsing through a few issues, I found [this comment](https://github.com/pre-commit/pre-commit/issues/369#issuecomment-219751345) you made on https://github.com/pre-commit/pre-commit/issues/369. In there, you are reproducing another issue with `rbenv`:

```
# some more code
   29  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
   33  apt-get install libyaml-dev
   36  rbenv install 2.2.4
# more code
```

I noticed that you explicitly install `libyaml-dev`. Is this a relevant dependency for ruby or rbenv? I if yes, I would expect this to be shipped as part of their installation. Else, the statement in https://pre-commit.com/#ruby "Support: ruby hooks work without any system-level dependencies. It has been tested on linux and macOS and may work under cygwin." wobbly.

I am not too much into ruby, hence not sure who has to take care of this dependency. Should we raise an issue in the rbenv repo or ruby-build? What would you suggest?
