### ISSUE TITLE
Environment Setup Performance Improvements

### ISSUE THREAD

**Issue by jlindquist-godaddy** [pre-commit/pre-commit#2857]
### search you tried in the issue tracker

is:issue environment install parallel

### describe your issue

I've not been able to find an open issue (or a closed issued that addressed this), so I apologize in advance if I've simply missed an existing one, but is there any way to speed up the environment setup, or setup using a shared environment, when multiple hooks are enabled?

For example, we're running several Puppet pre-commit hooks which require Ruby, and an environment is setup for each of these which in various scenarios took 20+ mins during an initial setup which seems excessive since it has to download and compile ruby for each environment, and install any required gems. 

In this particular case, would it be possible to:

- Install and compile a Ruby version once (if needed), and setup individual / isolated gemsets (something like [rbenv-gemset](https://github.com/jf/rbenv-gemset), or even RVMs built-in gemset functions) which would save time compiling the same Ruby version over and over
- Do these installs in parallel in some way?
- Specify an externally managed Ruby env to use, or alternate provider?

Obviously open to any suggestion or idea on improving performance.  Thanks!

```
time pre-commit run --all-files -v
[INFO] Initializing environment for https://github.com/godaddy/tartufo.
[INFO] Initializing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Initializing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git:puppet:<8.
[INFO] Initializing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git:puppet-lint:<4,voxpupuli-puppet-lint-plugins:<5.
[INFO] Initializing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git:r10k.
[INFO] Initializing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git:ruby.
[INFO] Installing environment for https://github.com/godaddy/tartufo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tartufo..................................................................Passed
- hook id: tartufo
- duration: 1.49s

Time: 2023-04-28T18:52:07.792893
All clear. No secrets detected.

Validate EPP templates...............................(no files to check)Skipped
- hook id: epp-validate
Validate ERB templates...................................................Passed
- hook id: erb-validate
- duration: 2.65s
puppet-lint..............................................................Passed
- hook id: puppet-lint
- duration: 1.79s
Validate Puppet manifests................................................Passed
- hook id: puppet-validate
- duration: 26.07s
Validate r10k Puppetfile.................................................Passed
- hook id: r10k-validate
- duration: 4.43s
Validate ruby syntax.....................................................Passed
- hook id: ruby-validate
- duration: 0.7s

real	20m31.715s
user	18m41.883s
sys	11m52.517s
```

### pre-commit --version

pre-commit 3.2.2

### .pre-commit-config.yaml

```yaml
default_language_version:
  ruby: 2.7.7
repos:
  - repo: https://github.com/godaddy/tartufo
    rev: v4.1.0
    hooks:
    - id: tartufo
  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.2.0
    hooks:
      - id: epp-validate
        additional_dependencies:
          - puppet:<8
      - id: erb-validate
      - id: puppet-lint
        additional_dependencies:
          - puppet-lint:<4
          - voxpupuli-puppet-lint-plugins:<5
        args:
          - --fail-on-warnings
      - id: puppet-validate
        additional_dependencies:
          - puppet:<8
      - id: r10k-validate
      - id: ruby-validate
```

**Comment by asottile** [comment]
your `default_language_version` setting is causing all those builds

parallel install isn't safe in general and wouldn't make things faster anyway if your cores are all building

**Comment by asottile** [comment]
but also initial setup shouldn't matter much, it's cached after that

**Comment by jlindquist-godaddy** [comment]
The cache is great once its setup, but it's a deterrent for new committers to have to wait for so long for an initial setup.  Is there a way to ensure all the hooks are installed in the same version without using `default_language_version`

**Comment by asottile** [comment]
does the specific ruby version actually matter?

**Comment by jlindquist-godaddy** [comment]
Yes, by default it seems like it tries to use the systems Ruby version (which on MacOS Ventura is 2.6.x), and the gems we need to pin to require a newer version.  The latest version(s) of the gems require an even newer version of Ruby that we're not quite to yet either, so there are very real needs to be able to specify the Ruby version for specific installs

```
### version information

```
pre-commit version: 3.2.2
git --version: git version 2.40.1
sys.version:
    3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.2.2/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby', '/usr/bin/gem', 'install', '--no-document', '--no-format-executable', '--no-user-install', 'pre_commit_fake_gem-0.gem', 'puppet:<8')
return code: 1
stdout:
    Successfully installed pre_commit_fake_gem-0
    Successfully installed hocon-1.4.0
    Successfully installed thor-1.2.1
    Successfully installed facter-4.4.0
    Successfully installed hiera-3.12.0
    1 gem installed
stderr:
    ERROR:  Error installing puppet:
    	The last version of semantic_puppet (~> 1.0) to support your Ruby & RubyGems was 1.0.4. Try installing it with `gem install semantic_puppet -v 1.0.4` and then running the current command again
    	semantic_puppet requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 409, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/languages/ruby.py", line 132, in install_environment
    lang_base.setup_cmd(
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/opt/homebrew/Cellar/pre-commit/3.2.2/libexec/lib/python3.11/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby', '/usr/bin/gem', 'install', '--no-document', '--no-format-executable', '--no-user-install', 'pre_commit_fake_gem-0.gem', 'puppet:<8')
return code: 1
stdout:
    Successfully installed pre_commit_fake_gem-0
    Successfully installed hocon-1.4.0
    Successfully installed thor-1.2.1
    Successfully installed facter-4.4.0
    Successfully installed hiera-3.12.0
    1 gem installed
stderr:
    ERROR:  Error installing puppet:
    	The last version of semantic_puppet (~> 1.0) to support your Ruby & RubyGems was 1.0.4. Try installing it with `gem install semantic_puppet -v 1.0.4` and then running the current command again
    	semantic_puppet requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
```
