### ISSUE TITLE
Syntax error while installing

### ISSUE THREAD

**Issue by lomefin** [pre-commit/pre-commit#2869]
### search you tried in the issue tracker

syntax error

### describe your issue

I was trying to install pre-commit

As of the documentation
`curl https://pre-commit.com/install-local.py | python -`

Shows the following error

```
 File "<stdin>", line 25
    def clean(dirname: str) -> None:
                     ^
SyntaxError: invalid syntax
```

This has been tested on several machines, Linux and MacOS. All have the basic default Python install.

### pre-commit --version

3.3.1

### .pre-commit-config.yaml

```yaml
Never reached
```

**Comment by asottile** [comment]
you're using python 2 which has been end of lifed for years

also that script is deprecated as well so don't use that either
