### ISSUE TITLE
Could we have to possibility to write pre-commit.log to the stderr stream?

### ISSUE THREAD

**Issue by b-enoit-be** [pre-commit/pre-commit#2871]
### search you tried in the issue tracker

stderr; pre-commit.log

### describe your actual problem

Today, I was using a (Docker) container via a Jenkins pipeline to run a pre-commit check on one of my team's repository.
Because some files where bind-mounts, I ended up with a user permission issue on the files in the _.git_ folder, causing pre-commit to fail with the message [`Check the log at .../pre-commit.log`](https://github.com/pre-commit/pre-commit/blob/51104fa94a6c3cdf603de2e187284289ea5abcf5/pre_commit/error_handler.py#LL35C33-L35C49), and because this is a container and that Jenkins does a proper clean up after itself, the file _pre-commit.log_ vanished with the container, making it really hard for me to debug the issue easily.

So, **long story short**, I would love to have the content of the _pre-commit.log_ written to the standard error stream rather than to a file. But, a quick look at the way [it is implemented](https://github.com/pre-commit/pre-commit/blob/51104fa94a6c3cdf603de2e187284289ea5abcf5/pre_commit/error_handler.py#L32) makes me to think this is not possible at the moment, and will need a new feature.

### pre-commit --version

3.3.1

**Comment by asottile** [comment]
you're free to `|| (cat ... && exit 1)` without me needing to carry additional complexity

**Comment by b-enoit-be** [comment]
Right. Out of curiosity, then, why was [`log_file`](https://pre-commit.com/#config-log_file) implemented when `| tee output.log` could have be instructed there too?

**Comment by asottile** [comment]
you're free to read the history and free to do that if you want

but also there's no shells involved

also idk if you meant it that way but it feels kind you're "but this exists so my feature should too" which I don't appreciate

**Comment by b-enoit-be** [comment]
Sorry, that was not the intend at all, I realised it hence me edit.
