### ISSUE TITLE
Testing fails when run from source tarball

### ISSUE THREAD

**Issue by mtelka** [pre-commit/pre-commit#2872]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+source+testing+

### describe your issue

I tried to run tests from source tarball as suggested in #2609 but I found that they simply do not work correctly because they expect they are run directly from git repo, not a tarball.

My testing scenario:

I do have a directory that is a part of some git repo (not related to pre-commit).  Let say the directory is `/opt/src` and so there is `/opt/src/.git` subdirectroy.  In this directory I unpack https://github.com/pre-commit/pre-commit/archive/refs/tags/v3.3.1.tar.gz so I have `/opt/src/pre-commit-3.3.1` now.  In `/opt/src/pre-commit-3.3.1` there is no `.git` subdir.  I run tests in `/opt/src/pre-commit-3.3.1`.

Observations:

The first failure is this:
```
____________________ test_local_resources_reflects_reality _____________________

    def test_local_resources_reflects_reality():
        on_disk = {
            res[len('empty_template_'):]
>           for res in os.listdir('pre_commit/resources')
            if res.startswith('empty_template_')
        }
E       FileNotFoundError: [Errno 2] No such file or directory: 'pre_commit/resources'

/opt/src/pre-commit-3.3.1/tests/store_test.py:189: FileNotFoundError
```
This is because the current working directory when the `test_local_resources_reflects_reality` test is run is `/opt/src`, not `/opt/src/pre-commit-3.3.1`.  This sounds roughly similar to [this poetry-core issue](https://github.com/python-poetry/poetry/issues/5547).  To workaround the problem I just set `GIT_DIR=/opt/src/pre-commit-3.3.1`.  This allowed the `test_local_resources_reflects_reality` test to pass, but other (many more) tests started to fail complaining they are not run in git repo.  For example:
```
    def cmd_output_b(
            *cmd: str,
            check: bool = True,
            **kwargs: Any,
    ) -> tuple[int, bytes, bytes | None]:
        _setdefault_kwargs(kwargs)

        try:
            cmd = parse_shebang.normalize_cmd(cmd, env=kwargs.get('env'))
        except parse_shebang.ExecutableNotFoundError as e:
            returncode, stdout_b, stderr_b = e.to_output()
        else:
            try:
                proc = subprocess.Popen(cmd, **kwargs)
            except OSError as e:
                returncode, stdout_b, stderr_b = _oserror_to_output(e)
            else:
                stdout_b, stderr_b = proc.communicate()
                returncode = proc.returncode

        if check and returncode:
>           raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
E           pre_commit.util.CalledProcessError: command: ('git', 'add', '.')
E           return code: 128
E           stdout: (none)
E           stderr:
E               fatal: this operation must be run in a work tree

pre_commit/util.py:110: CalledProcessError
```

### pre-commit --version

3.3.1

### .pre-commit-config.yaml

```yaml
NA
```

**Comment by asottile** [comment]
I'd rather you not package pre-commit and instead suggest your users install from pypi, especially if you're going to waste my time like this.

there are many duplicates and solutions in them if you search
