### ISSUE TITLE
Install or update system dependencies in commit

### ISSUE THREAD

**Issue by DavidSlayback** [pre-commit/pre-commit#2888]
### search you tried in the issue tracker

install system dependency

### describe your actual problem

On commit, I want to write a hook that updates the system's poetry version `poetry self update <version>` and installs the local environment `poetry install` so that all developers are running the desired Poetry version. Because the pre-commit is using its own cached poetry version, it only updates that one, so the action will appear to run, but it won't have the desired effect.

Is there already an easy way to update system dependencies? I could probably do a hack to find the local poetry and pass it as an environment variable, but ideally, I'd like to just flag that I want the local version instead of the result of `pre-commit install`

### pre-commit --version

pre-commit 3.3.0

**Comment by asottile** [comment]
there's a whole section in the docs on this, have your read through them?

**Comment by asottile** [comment]
yeah `export` isn't ever going to persist from subprocesses -- https://youtu.be/YE6ZDpRcdQU might help understand that one

> not exactly appreciated

skipping the issue template and opening low quality issues without any context or what you've tried is also not appreciated
