### ISSUE TITLE
Possible to accept STDIN from hooks?

### ISSUE THREAD

**Issue by fantapop** [pre-commit/pre-commit#289]
I'd like to have commit hooks that prompt for user input and then continue.  It looks like STDIN is not currently being passed back and forth and in my tests this doesn't work.

Is this a reasonable feature request?

**Comment by asottile** [comment]
Unfortunately the hooks are executed with `xargs` and the filenames are fed as stdin to `xargs`

Without writing our own xargs in python I'm not sure this is possible.  Even if it was, we bundle up all the stdout / stderr to hide it if the hook passes.

So.... probably no :(

**Comment by social-anthrax** [comment]
Apologies to post in a 5 year old thread but in case anyone ends up here from google: There's a really hacky bypass to show output and accept input. Instead of executing your hook normally make a bash script containing the following.

```bash
#! /usr/bin/env bash -e

exec < /dev/tty > /dev/tty

# Whatever you wanted to have in the entry field.
python3 ./main.py $@
```
