### ISSUE TITLE
Use pre-commit even without Git

### ISSUE THREAD

**Issue by defineapex** [pre-commit/pre-commit#2893]
### search you tried in the issue tracker

without git 

### describe your issue

I have some django/python projects where I no longer need Git. I then removed all .git folders. I was now working on a project and wanted to start pre-commit manually, unfortunately I got the following error message:

$ pre-commit run -a
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?

How can I still use pre-commit?

### pre-commit --version

3.2.2

### .pre-commit-config.yaml

```yaml
-
```

**Comment by asottile** [comment]
search better, there are duplicates. one idea would be to search the actual message you get
