### ISSUE TITLE
Add ability to customise color output

### ISSUE THREAD

**Issue by kiran94** [pre-commit/pre-commit#2895]
### search you tried in the issue tracker

color / accessibility

### describe your actual problem

Add the ability to customise the foreground / background of the status text

It's a **minor** quality of life accessibility feature which is low priority. But below you can see that it's quite difficult to see the status text: 

![image](https://github.com/pre-commit/pre-commit/assets/7103956/e4874926-e24a-4717-a5b3-4b229fb117eb)

It would be lovely if I could customize the color of the text to black for example and set that configuration into my `.bashrc` / `.zshrc`.  

For this kind of feature, I don't think it should live inside `.pre-commit-config.yaml`  as different engineers on a team might be using different terminal color themes. I see we already have `PRE_COMMIT_COLOR` to control if color should be used or not so maybe something like `PRE_COMMIT_STATUS_COLOR_FG` and `PRE_COMMIT_STATUS_COLOR_BG` to control this output. 

### pre-commit --version

3.3.2

**Comment by asottile** [comment]
did you read the search results?
