### ISSUE TITLE
autoupdate in pre-commit.yaml with a `git commit --all` fails since 3.3.0

### ISSUE THREAD

**Issue by grimm26** [pre-commit/pre-commit#2900]
### search you tried in the issue tracker

autoupdate error: invalid object

### describe your issue

Ever since v3.3.0, running autoupdate in .pre-commit.yaml fails when I run a `git commit --all`. If I `git add` first and then just `git commit` it works fine. If I downgrade to precommit `3.2.2` autoupdate works fine with `git commit --all`.

```
❯ git commit --all --verbose
fix end of files.........................................................Passed
pre-commit autoupdate....................................................Passed
error: invalid object 100644 f8523d4a677b2904df1ebf50c826323b2555edeb for '.pre-commit-hooks.yaml'
error: Error building trees
```

### pre-commit --version

3.3.2

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: autoupdate
        name: pre-commit autoupdate
        language: system
        exclude: '.*'
        always_run: true
        entry: pre-commit
        args: [autoupdate]
```

**Comment by asottile** [comment]
you should not run autoupdate in git hooks.  you're free to try and debug this and send a patch but you're in unsupported territory
