### ISSUE TITLE
Allow disabling some hooks on specific branches

### ISSUE THREAD

**Issue by caprest** [pre-commit/pre-commit#2902]
### search you tried in the issue tracker

I searched for `branch` keyword.  I found a similar closed PR but not found no issues to discuss on the feature.

### describe your actual problem

# Feature Request: Enhanced Branch-Specific Control in Pre-commit

Dear Pre-commit Team, thank you for creating an awesome library that greatly simplifies code maintenance ! 

The suggested enhancement is for `pre-commit-config.yaml` to support an additional set of configuration items as shown below:

```yaml
skip_branch:
  - branchA : [flake8, ]
  - branchB: [flake8, isort, black]
```

The intended behavior would be that when committing on 'branchA', pre-commit would behave as if `SKIP=flake8 pre-commit` has been executed, thereby skipping the `flake8` check.

## Rationale

During development, certain hooks can sometimes feel rather strict. For instance, there are times when I prefer to ignore the `flake8` requirement such as `F401` because I believe that such refactoring can be performed after completing the whole process. Another situation is when there's a sandbox branch in use for experimentation, without the necessity of strict code quality considerations.

At present, I can utilize the `SKIP` environment variable to achieve the desired behavior. However, it would be even more convenient if I could toggle these settings directly in the `.pre-commit-config.yaml` file.

## Evidence of Demand

I noticed a previously closed PR, linked below, which suggests there may be similar demands for this feature:

https://github.com/pre-commit/pre-commit/pull/2858

While the pull request has been closed, I believe the feature could still prove useful to a variety of users.

I hope you will consider this feature request. I believe it could add more flexibility to pre-commit. Thank you in advance for your consideration and for the great work you've done on pre-commit.

Best regards,

### pre-commit --version

pre-commit v3.3.2

**Comment by asottile** [comment]
sorry but I'm going to decline this -- same as the PR

this seems like a bad idea.  if you want to enforce things enforce them -- if you don't then well don't

you can of course accomplish whatever you want in custom scripting -- and pre-commit doesn't need to be involved in that.

for instance:

```bash
entry: ./flake8-wrapper.sh
```

and some shell if statements checking the branch name

but I strongly would not recommend it (everything should be up to lint standards, no exceptions for random branches) and I wouldn't build a feature into pre-commit for it
