### ISSUE TITLE
autoupdate drops all my commented out code in the config file

### ISSUE THREAD

**Issue by zoidbergwill** [pre-commit/pre-commit#291]
While experimenting with pre-commit, a couple times I've temporarily commented out some code and then autoupdated and been surprised that all my commented out code has been dropped.

I know it's hard to re-format the file and keep comments in the same place, but it'd be neat if it at least printed the old file or commented out code to stdout or there was a warning or something, or at least an extra argument to not re-format the file and just update the hashes.

I'm sorry if this is a duplicate issue, I tried to find any similar issues before filing it.

**Comment by asottile** [comment]
Yeah this is covered by #210. I have a mostly working (but needs rebase) pr to solve this with #211 but I haven't had time to complete it. 

A workaround is `git checkout -p .pre-commit-config.yaml `

**Comment by zoidbergwill** [comment]
Awesome, thanks.

Yeah, unfortunately I haven't convinced my team to use it yet, so I'm using a git ignored config for now. Though I'll remember `git checkout --patch` for next time it happens. Thanks.
