### ISSUE TITLE
Add new `-W treat warning as errors` option for `pre-commit run`

### ISSUE THREAD

**Issue by vlotorev** [pre-commit/pre-commit#2911]
### search you tried in the issue tracker

warning as error

### describe your actual problem

'pre-commit run' command can print warnings starting with `[WARNING]`. Warning examples I came across:
```
[WARNING] Unexpected key(s) present on <some-repo> => <some-hook>: additional_dependecies
[WARNING] The top-level 'exclude' field is a regex, not a glob -- matching '/*' probably isn't what you want here
```
It would be useful to detect such warnings on CI automatically with a new option 'treat warnings as errors'. Examples for option from other software:
* Sphinx `sphinx-build -W` (turn warnings into errors)
* GCC `gcc -Werror` (treat warnings as errors).

### pre-commit --version

3.3.3

**Comment by asottile** [comment]
you can `| grep WARNING` just as easily -- I don't really want to add such a feature since I don't think it'll really get used

**Comment by lalten** [comment]
Hi @asottile, I'd like to achieve this as well to prevent commits that add warnings from being checked in -- can you explain what you mean with the grep? I'm using https://github.com/pre-commit/action.
