### ISSUE TITLE
ModuleNotFoundError when `repo: meta` (a request for guidance in nixpkgs)

### ISSUE THREAD

**Issue by MatrixManAtYrService** [pre-commit/pre-commit#2915]
### search you tried in the issue tracker

nixpkgs, modulenotfounderror meta, 

### describe your actual problem

Hello.  I'm in a bit of a pickle.  I'm neither a pre-commit expert nor a nixpkgs expert.  Perhaps foolishly, [I noticed a problem in the nixpkgs pre-commit package and fixed it](https://github.com/NixOS/nixpkgs/pull/235123).  Later I learned that [this broke pre-commit's ability to run `repo: meta` hooks](https://github.com/NixOS/nixpkgs/issues/238345)--which I hadn't been using.

I feel some responsibility to address this because I broke it.  Maybe reverting my fix is the way to go, but that would bring back the PYTHONPATH bug that I was addressing in the first place.  Better would be to find a way forward that addresses both concerns--I'm hoping you can help me do that.

I recognize that maintaining nixpkgs is not your responsibility, but if you're willing to take a peak at the above issues and give me some guidance, I'll do my best to leave things in a better state than I found them.  Otherwise feel free to close this issue with no hard feelings.  Thanks.

### pre-commit --version

pre-commit 3.2.2

**Comment by asottile** [comment]
nope sorry -- I don't recommend using nix
