### ISSUE TITLE
Support `FORCE_COLOR` env var

### ISSUE THREAD

**Issue by MicaelJarniac** [pre-commit/pre-commit#2918]
### search you tried in the issue tracker

FORCE_COLOR, color

### describe your actual problem

Add support for the `FORCE_COLOR` environment variable. When set, regardless of value, all output should have colors enabled, as if the terminal supported them.

pre-commit seems to support a similar env var, `PRE_COMMIT_COLOR`, that should have a similar effect when set to `always`.

`FORCE_COLOR`, however, seems to be basically a universal approach to this, and is being used by many other projects.

Supporting it means that one only has to set a single env var to enable colors on all tools at once automatically.

If every tool were to create its own unique env var, CI configuration would easily get too crowded and messy.

I'm not saying that `PRE_COMMIT_COLOR` should be deprecated, just that `FORCE_COLOR` should also be supported.

Some projects that use this:
- [Pytest](https://docs.pytest.org/en/7.0.x/reference/reference.html#envvar-FORCE_COLOR)
- [Nox](https://nox.thea.codes/en/stable/usage.html#controlling-color-output)
- [Tox](https://tox.wiki/en/4.0.6/changelog.html#features-4-0-0a2)
- [Rich](https://rich.readthedocs.io/en/latest/console.html?highlight=FORCE_COLOR#environment-variables)
- [Mypy](https://github.com/python/mypy/blob/781dc8f82adacce730293479517fd0fb5944c255/mypy/util.py#L523)
- [build](https://pypa-build.readthedocs.io/en/stable/changelog.html?highlight=FORCE_COLOR#id13)

Related:
- https://github.com/Textualize/rich/issues/2425
- https://github.com/wntrblm/nox/issues/502
- https://github.com/pypa/pip/issues/10909
- https://github.com/astral-sh/ruff/issues/5499
- https://github.com/python-poetry/cleo/issues/341

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
dupe #1073
