### ISSUE TITLE
Podman support by allowing defining the docker executable name

### ISSUE THREAD

**Issue by komima** [pre-commit/pre-commit#2920]
### search you tried in the issue tracker

podman

### describe your actual problem

I'd like to use podman (on Windows WSL2) as the docker-compatible backend, and use pre-commit `docker/docker_image` hooks against that.

Since the current implementation requires `docker` commands to be available those binaries need to be downloaded separately. There are also some very hard to debug inconsitensies in this setup (like `docker run --rm ...` run againsts the podman socket returns 0 instead of the actual code and causes hooks to pass, fixed lately https://github.com/containers/podman/issues/18889).

Related issue (https://github.com/pre-commit/pre-commit/issues/2779) about pre-commit using the API instead of the executable was closed, so this would be an alternative way to use podman-based containers and not needing extra work to provide the docker cli for pre-commit.

Maybe this could be implemented via some kind of environment variable like `PRE_COMMIT_DOCKER_EXECUTABLE=podman` and populated to the commands from that, defaulting to `docker`?

### pre-commit --version

pre-commit 3.3.0

**Comment by asottile** [comment]
please continue the discussion in #1243

**Comment by asottile** [comment]
fwiw `ln -s podman docker` works pretty well for me

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit/issues/2920#issuecomment-1621640634
