### ISSUE TITLE
Support for custom git hooks

### ISSUE THREAD

**Issue by CarterWilde** [pre-commit/pre-commit#2925]
### search you tried in the issue tracker

"custom git hook" searched "custom stage"  as well

### describe your actual problem

I'm looking to use pre-commit at work, and we have our own git hook named `pre-cr`.

I tried setting my `default_stages` to `[pre-cr]` 

but it gives an error of:
```
==> File .pre-commit-config.yaml
==> At Config()
==> At index 0
=====> Expected one of commit-msg, manual, post-checkout, post-commit, post-merge, post-rewrite, pre-commit, pre-merge-commit, pre-push, pre-rebase, prepare-commit-msg but got: 'pre-cr'
```

This seems like an intentional error/limitation. I was wondering if it would be possible to add support for any git hook?

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
if you're forking `git` to add custom hooks you'll probably also want to maintain your own fork of `pre-commit` -- we can't really support random patched `git` versions

**Comment by asottile** [comment]
alternatively you can (ab)use the [`manual` stage](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages)

**Comment by CarterWilde** [comment]
That's what I was thinking of doing... However, may look into making a fork. Thanks for the responses.
