### ISSUE TITLE
Write mode for log_file in hook config

### ISSUE THREAD

**Issue by yesemsanthoshkumar** [pre-commit/pre-commit#2928]
### search you tried in the issue tracker

log_file

### describe your actual problem

log_file when added to hook config does append only to an existing file. While this is preferrable for systems say jenkins (and you'd need the entire build logs), this causes the file to grow if used in a local environment for development. The version I currently use is 2.x. When I looked at the master branch, it seems file mode is harcoded as append in https://github.com/pre-commit/pre-commit/blob/main/pre_commit/output.py#L22

Is there a way to work around the problem of log file growing large? Or Is it possible to add a feature to the hook as `log_write_mode` with append as the default?

I'd be happy to make a PR for this if this is worth adding as a feature :)

### pre-commit --version

pre-commit 2.16.0

**Comment by asottile** [comment]
no thanks.  if you want log rotation use a tool for log rotation
