### ISSUE TITLE
repo in config should respect (local) gitconfig for repo url

### ISSUE THREAD

**Issue by adrian-goe** [pre-commit/pre-commit#2930]
### search you tried in the issue tracker

is:issue repo is:closed gitconfig

### describe your actual problem

The repo url should respect the local .gitconfig and redirect the git url to access private repos.

I have multiple git accounts with different ssh keys. I have vor each customer a directory with a local git config.

```
~./gitconfig
~/customerA/.gitconfig
~/customerB/.gitconfig
...
```
Some of those use the managed gitlab with their own Active Directory. So in this cases, I have an account for each customer, as the accounts cant be linked.

This also means, for each separate SSH key/config. For git itself, this is not a problem with the local `.gitconfig`. Using a url redirect solves this problem.

```
[user]
  name = My Name
  email = test@email.com
  signingkey = /Users/my/.ssh/custumerKey
[commit]
  gpgsign = true
[gpg]
  format = ssh
[url "git@customer.gitlab.com:"]
  insteadOf = git@gitlab.com:
```
This config ensures, that every git command uses the correct host config form ssh, without changing the url manualy.
For example for clone  i can use this:`git clone git@gitlab.com:organisation/team/project.git` instead of manually writing `git clone git@customer.gitlab.com:organisation/team/project.git`.

pre-commit not. The repo url is used as it is configured. For users with just one gitlab account, this is not a big deal. For someone like me, it means to change the config and not committing the file.

But this also breaks for example intelij git because the pre commit hook cant run, as it is dirty and not marked als `include for commit`.

So in the end, if the pre-commit would lookup the git config, it would find the correct repo and access rights.

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
this works for me. pre-commit just calls git and git reads the config

**Comment by adrian-goe** [comment]
@asottile not in sub directory.
pre-commit executes per default in home directory. So it uses the default git config, not the one of my sub directory.
As a workaround I found now is, I can run `export PRE_COMMIT_HOME=./temp` in my subdirectory and then it uses the git config of my sub directory. But always setting the `PRE_COMMIT_HOME` is better but still not the best solution.

**Comment by asottile** [comment]
that's not how gitconfig works -- you must have some forked git or some other extension.  git only reads `~/.gitconfig` -- it doesn't read your other configurations

**Comment by asottile** [comment]
but either way -- you've got a hack and you're getting bit by it -- I'd recommend not doing that.  be explicit about what you're cloning instead of being lazy / clever.  `pre-commit` just calls git -- so it's just going to do what `git` does -- there's no magic there and nothing that `pre-commit` can "fix" for you

**Comment by adrian-goe** [comment]
Its based of conditional includes.
https://stackoverflow.com/a/60344116

**Comment by asottile** [comment]
separate ssh keys is not a problem -- git will negotiate the connection with each key and only the one that works will be used.  you can even use hints in your ssh configuration to give it the url.

either way this is not a pre-commit problem, and it sounds like you already have a solution for your hack
