### ISSUE TITLE
allow Rust language hooks to install binaries from a workspace

### ISSUE THREAD

**Issue by jcreekmore** [pre-commit/pre-commit#2931]
### search you tried in the issue tracker

is:issue rust 

### describe your actual problem

I have a repository that contains a Rust workspace at the root of the repository and several of the crates in the workspace have utilities that I want to use as pre-commit hooks. My `Cargo.toml` looks like this:

```toml
[workspace]
members = ["crates/*"]
```

and I want to be able to use the `do-checks` binary located in the `checks` package in the `crates` directory:

```yaml
- id: do-checks
  name: do fancy checks
  types: [text]
  language: rust
  entry: do-checks
```

There is currently nothing available that would allow me to specify that I want to use a binary from a package located in a workspace. When I try using the `try-repo` command, I run into the following error:

```
❯ pre-commit try-repo ../checks-repo do-checks
[WARNING] Creating temporary repo with uncommitted changes...
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /tmp/tmpvwk81di4/shadow-repo
    rev: 2b784c6bd1c1e41bd7e3c039d97c3cfa9130568b
    hooks:
    -   id: do-checks
===============================================================================
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /tmp/tmpvwk81di4/patch1689695368-289924.
[INFO] Initializing environment for /tmp/tmpvwk81di4/shadow-repo.
[INFO] Installing environment for /tmp/tmpvwk81di4/shadow-repo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /tmp/tmpvwk81di4/patch1689695368-289924.
An unexpected error has occurred: CalledProcessError: command: ('/home/jonathan/.cargo/bin/cargo', 'install', '--bins', '--root', '/tmp/tmpvwk81di4/repo01nrjjfk/rustenv-default', '--path', '.')
return code: 101
expected return code: 0
stdout: (none)
stderr:
    error: found a virtual manifest at `/tmp/tmpvwk81di4/repo01nrjjfk/Cargo.toml` instead of a package manifest

Check the log at /home/jonathan/.cache/pre-commit/pre-commit.log
```

The reason _why_ I see that is because pre-commit defaults to passing `--path .` as mentioned in issue #1112 and merged in with PR #1113. In this case, what I really want to do is be able to specify `--path crates/checks` for this hook, because that is where the package is located inside the workspace.

Looking at the code, I don't think that passing anything for `additional_dependencies` will do what I am trying to do, because it will unconditionally pass `--path .` which will never work with a workspace. It would be helpful if we could specify an override for the path component there instead of having to use `.` (that is, allow `.` as the default, but let us override it when defining the hook?)

### pre-commit --version

v3.3.3

**Comment by asottile** [comment]
hooks are conventionally always at the root.  there are several duplicates and I'm not changing this

**Comment by jcreekmore** [comment]
Well, for the sake of any people in the future who are trying to figure out how to use Rust binaries in a workspace as a pre-commit hook, this is the workaround I am implementing in my repo. Using the [`docker` language](https://pre-commit.com/#docker), I dropped a minimal `Dockerfile` into the root of my repository with the following contents:

```dockerfile
FROM rust

COPY . /app
WORKDIR /app
RUN cargo install --path crates/checks  
# you could do multiple RUN cargo install --path {crate} here if necessary if you need multiple crate binaries built
```

Changing my `.pre-commit-hooks.yaml` in the root of the repository to:

```yaml
- id: do-checks
  name: do fancy checks
  types: [text]
  language: docker
  entry: do-checks
```

This all seems to work out ok if 1) you don't mind consuming the default name of the `Dockerfile` for building a container to run the hooks and 2) don't have an issue using Docker as part of your pre-commit process. You can further work around 1) if you are already using the default `Dockerfile` for other purposes and have a CI loop: use the [`docker_image` language](https://pre-commit.com/#docker_image) to reference your already built containers.

**Comment by Matthieu-LAURENT39** [comment]
Man, that's one hell of a messy workaround...
I get wanting the `.pre-commit-hooks.yaml` to be at the root, but forcing the Cargo.toml to be at the root as well just feels unnecessarily restrictive...

**Comment by asottile** [comment]
your comment is not productive
