### ISSUE TITLE
Gathering metrics on hook performance

### ISSUE THREAD

**Issue by atoader** [pre-commit/pre-commit#2933]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+metrics+

### describe your actual problem

Hi,

I am setting up pre-commit for my team as part of a broader push for improving developer productivity. As this is a long-term project, I would like to be able to keep track how much time is spent on different parts of the development flow, including running pre-commit hooks or pre-push hooks. 

Is there any way to get metrics or structured logs with information such as:
Per-hook
- Hook ID
- Duration
- Input arguments length

Per-stage:
- Total duration

One option that I see is to use the local configuration and invoke a script that emits the metrics before invoking the executable that performs the action, but that would mean that I would need to manually manage tool installation which is less than ideal.

If this sounds like a feature that is worth doing, I can try to propose a design that modifies pre-commit to emit metrics.

### pre-commit --version

pre-commit v3.3.3

**Comment by sfc-gh-tszerszen** [comment]
👍 I need this as well

**Comment by asottile** [comment]
@sfc-gh-tszerszen use the react button instead of sending more notifications

@atoader please look at the third result in your search

**Comment by sfc-gh-atoader** [comment]
Thanks, @asottile! Are you referring to https://github.com/pre-commit/pre-commit/issues/2202#issuecomment-1010436372 ? I'll give it a try. Sorry for the spam, but it was not immediately clear from the comment how that would work. I also saw some ideas on https://github.com/pre-commit/pre-commit/issues/696 when reading about verbose logs and metrics.
