### ISSUE TITLE
Make `--to-ref` default to `HEAD`, when only `--from-ref` is used

### ISSUE THREAD

**Issue by kaidokert** [pre-commit/pre-commit#2939]
### search you tried in the issue tracker

`to-ref` 

### describe your actual problem

I don't have an actual problem :) but i often run `pre-commit run --from-ref=origin/main --to-ref=HEAD` to verify stuff that i have committed and bypassed checks on, but obviously don't want to push as-is.

Currently:
```
pre-commit run --from-ref=origin/main
[ERROR] Specify both --from-ref and --to-ref.
```

I would suggest making this tiny ERROR go away and simply default to `HEAD` in this case, to save a bit of typing. Perhaps this isn't everyones preference though, and there could be other reasonable defaults for this ?

I did search issue tracker for anything mentioning `--to-ref` and didn't find a similar issue. Happy to make a PR if this sounds like worthwhile thing.

### pre-commit --version

pre-commit 2.21.0

**Comment by asottile** [comment]
no thanks -- both are required to be specified explicitly

**Comment by kaidokert** [comment]
Understood - but is there a bit of rationale as to why a default would be bad or dangerous here ?
