### ISSUE TITLE
To increase the number of characters from 80 to 100, sometimes it becomes too tough to convey the message in 80 characters 

### ISSUE THREAD

**Issue by balianurag** [pre-commit/pre-commit#2954]
### search you tried in the issue tracker

On my local

### describe your actual problem

utils.py:391:81: E501 line too long (100 > 80 characters)

### pre-commit --version

pre-commit 2.6.0

In this, 
https://github.com/pre-commit/pre-commit/blob/main/pre_commit/commands/run.py#L249-L251

set from `return max(cols, 80)` to `return max(cols, 100)`

**Comment by asottile** [comment]
no thanks
