### ISSUE TITLE
Does `pre-commit run my_manual_hook` really need `--hook-stage manual`?

### ISSUE THREAD

**Issue by randolf-scholz** [pre-commit/pre-commit#2959]
### search you tried in the issue tracker

hook-stage manual

### describe your actual problem

It seems kind of verbose to require `--hook-state manual`, when a single hook is specifically chosen. Why not simply:

```bash
pre-commit run my_manual_hook -a
```

The intention seems unambiguous: execute the hook `my_manual_hook` on all files.

When `pre-commit run my_hook` is called, it seems intuitive that the stage shouldn't matter, as the intention is to execute the specific hook `my_hook` right now.

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
yes, `pre-commit run` is what is run in the git hook so you must match the appropriate stage

it may seem unambiguous in your particular case but imagine if there were two hooks with the same id with different stages -- then what

rather than guessing: be explicit
