### ISSUE TITLE
Add configuration (or documentation if already possible) to use other container runtimes than `docker`

### ISSUE THREAD

**Issue by macwinnie** [pre-commit/pre-commit#2964]
### search you tried in the issue tracker

`containerd`, `rancher` and finally `nerdctl` (without any open / closed filters)

### describe your actual problem

On my working machine (Mac M1, Ventura 13.5), I'm not relying on Docker but used `Rancher Desktop` to set up a local single node k8s instance with simple `containerd`. For being able to work as near to the prod environment as possible, I don't want to change back to Docker – especially not only for the use of `pre-commit` hooks.

It would be great to configure `pre-commit` to use an alternative command like `nerdctl` on languages `docker` and `docker_image`, which (almost) have the same command usage like the `docker` command.

I've also added an alias to my `.bashrc` as well as the `.zschrc` which keeps ignored by `pre-commit` execution … probably the solution just is to give me a hint on how the command will be executed so I can place the `alias docker=nerdctl` correctly?

Thanks a lot!

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
dupe #1243
