### ISSUE TITLE
`--no-verify` is ignored if configuration is unstaged

### ISSUE THREAD

**Issue by nfantone** [pre-commit/pre-commit#2966]
### search you tried in the issue tracker

--no-verify

### describe your issue

If your `.pre-commit-config.yaml` has active changes, `git commit --no-verify` fails.

```sh
$ git commit --no-verify

[ERROR] Your pre-commit configuration is unstaged.
`git add .pre-commit-config.yaml` to fix this.
```

I don't need or want to stage `.pre-commit-config.yaml` in this particular set of changes. IMHO, `--no-verify` should be honoured and this check should not occur.

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
N/A.
```

**Comment by asottile** [comment]
--no-verify skips the hooks entirely.  it is not passed on to pre-commit.  you're encountering some non shippable hook (such as prepare-commit-msg)

there's nothing pre-commit can do in this scenario

**Comment by nfantone** [comment]
The call is clearly being trapped by `pre-commit` as it runs validations, prints a message and aborts the `git` call.

Anyway, why are you closing this without waiting for a response?

**Comment by asottile** [comment]
because there's nothing pre-commit can do.  did you read my response?

**Comment by nfantone** [comment]
I did. But perhaps you didn't read my reply in which I addressed yours.
