### ISSUE TITLE
Mypy run in pre-commit ignores configuration excludes

### ISSUE THREAD

**Issue by simonezamboniembark** [pre-commit/pre-commit#2967]
### search you tried in the issue tracker

mypy

### describe your issue

Running mypy on its own and running it using pre-commits have a different output, even though the configuration is the same. More specifically, running with pre-commit ignores the exclude of mypy.
It is possible to reproduce the issues, these are the steps:

- create a new repository with `git init mypy_test`
  - `cd mypy_test/`
- created a virtualenvironment with conda and python 3.10: `conda create --name mypy python=3.10` then `conda activate mypy`
- Install mypy and pre-commits: 
  - `pip install pre-commit` (installed version 3.3.3)
  - `pip install mypy` (installed version 1.5.1)
- Create the following folder structure:

main.py
```
def main() -> None:
    print('main')

if __name__ == "__main__":
    main()
```

pyproject.toml
```
[project]
requires-python = ">=3.10"
dependencies = [
]
[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
no_implicit_optional = true
exclude = [
    "^to_ignore/.*\\.py$"
]
```

.pre-commit-config.yaml
```
repos:
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: python
    types_or: [python, pyi]
    entry: mypy -v
```

to_ignore/myfunct.py
```
my_function("test")
```

The idea is to have two python files, `main.py` which is correct and `to_ignore/myfunct.py` which contains wrong code. Then in `pyproject.toml` we configure mypy to ignore everything in the `to_ignore/` folder. We add mypy to the `.pre-commit hooks.yaml` .

When running `python mypy -v .`:

```
LOG:  Mypy Version:           1.5.1
LOG:  Config File:            pyproject.toml
LOG:  Configured Executable:  /home/user/anaconda3/envs/mypy/bin/python
LOG:  Current Executable:     /home/user/anaconda3/envs/mypy/bin/python
LOG:  Cache Dir:              .mypy_cache
LOG:  Compiled:               True
LOG:  Exclude:                ['^to_ignore/.*\\.py$']
LOG:  Found source:           BuildSource(path='./main.py', module='main', has_text=False, base_dir='/home/user/tmp/mypy_test', followed=False)
...
Success: no issues found in 1 source file
```

When adding all the files with `git add *` and then `git commit -m "test"`:
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

LOG:  Mypy Version:           1.5.1
LOG:  Config File:            pyproject.toml
LOG:  Configured Executable:  /home/user/anaconda3/envs/mypy/bin/python
LOG:  Current Executable:     /home/user/anaconda3/envs/mypy/bin/python
LOG:  Cache Dir:              .mypy_cache
LOG:  Compiled:               True
LOG:  Exclude:                ['^to_ignore/.*\\.py$']
LOG:  Found source:           BuildSource(path='to_ignore/my_funct.py', module='my_funct', has_text=False, base_dir='/home/user/tmp/mypy_test/to_ignore', followed=False)
...
LOG:  Processing SCC singleton (my_funct) as inherently stale
to_ignore/my_funct.py:1: error: Name "my_function" is not defined  [name-defined]
LOG:  Deleting my_funct to_ignore/my_funct.py my_funct.meta.json my_funct.data.json
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.156 seconds with 40 modules, and 1 errors
Found 1 error in 1 file (checked 1 source file)
```

So `python mypy -v .` correctly ignores the file in the `/to_ignore` folder, while when running it from the pre-commits it does not ignore the folder, even though the configuration and exclude are exactly the same.
Why is this?

P.S. in the .yaml in the entry for mypy I tried `mypy`, `mypy -v`, `mypy -v .`, `mypy --config-file pyproject.toml` but nothing worked.

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: python
    types_or: [python, pyi]
    entry: mypy -v
```

**Comment by asottile** [comment]
there are many many duplicates. pre-commit passes filenames to hooks. not `.`

to compare apples to apples use `mypy $(git ls-files -- '*.py')` and then use `exclude` to fix it

**Comment by sigma67** [comment]
Set `pass_filenames: false` to fix this issue (at least it did for me)
