### ISSUE TITLE
Please support MacOS 14 Sonoma

### ISSUE THREAD

**Issue by crazysteeaam** [pre-commit/pre-commit#2974]
### search you tried in the issue tracker

None

### describe your actual problem

I'm trying to install pre-commit by `brew install pre-commit` on my device running MacOS 14 Sonoma.Please support this pre-release new system as it will be formally released in a month.

The following content is the warning after i run in the bash.

You are using macOS 14.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

### pre-commit --version

pre commit 3.3.3

**Comment by asottile** [comment]
maybe report to homebrew? we don't maintain homebrew
