### ISSUE TITLE
Allow empty `stages` entry or additional stage to never run hook as part of a stage

### ISSUE THREAD

**Issue by seamuswn** [pre-commit/pre-commit#2985]
### search you tried in the issue tracker

multiple searches

### describe your actual problem

I want to have three sets of pre-commit hooks for an existing project:
1. Hooks that are triggered automatically as part of Git hooks (i.e. pre-commit or pre-push). I would like use these for 'checks' (i.e. 'dry-run' validations) and never edit the un-committed files as a side effect of trying to commit / push.
2. Hooks that are triggered manually using the 'manual' hook stage in pre-commit. I would like for this hook stage to try to apply any 'autofix' / formatting when expressly opted in. For this reason I want to be able to run `pre-commit run --hook-stage=manual --file=...` for developers to manually apply formatting when desired instead.
3. Hooks that are triggered manually by name/hook ID, but not as part of any hook stage. I would like to use this as a way to run specific checks (e.g. we have a custom script to check all imports in our project to detect unused packages in `requirements.txt` - but this takes a long time to run and not something we want to trigger automatically).

For more context:

The way we currently have our project configured is to set default stages in config to everything but `manual` (for point 1 above), and developers are free to choose which Git hooks they want to install the checks on that suit their workflow (but we do have `default_install_hook_types` set to `[pre-push]` to nudge them towards that workflow). 
 
Depending on their workflow devs will either:
1. Configure their IDE to run the manual stage for all files in project on save to apply any automatic fixes to the checks installed in Githooks as they edit files.
2. Run the manual stage for all edited files in their branch before pushing using `pre-commit run --hook-stage manual --from-ref origin/HEAD --to-ref HEAD`.

We would like to introduce new checks that are only intended to be run in an ad-hoc manner - essentially using pre-commit as a script runner for some more expensive checks / validations that we don't want to be triggered by Githooks.

While we could just use the manual stage for the 'autofix' hooks + fully manual checks, but then when running the 'autofix' step developers would need to know the names/IDs of all formatting hooks.

What I have considered:

1. Allowing setting `stages: []` and having this match no pre-commit stage when running hooks. However this would be a breaking change as right now explicitly empty stages is treated the same as a null value (and default stages apply).
2. Introduce a `none` stage that can be explicitly set, in config but cannot be targeted by CLI. This means that `pre-commit run --hook-stage=none` would fail, but we could explicitly set `stages: [none]` to avoid having a hook picked up as part of any triggerable hook stage.
3. Introduce some other 'new' stage to represent what we currently use 'manual' stage for (e.g. 'format' / 'autofix' or simialar name).

I'm happy to contribute a PR with the necessary changes if this kind of use case is something you're happy to support.

### pre-commit --version

3.3.3

**Comment by asottile** [comment]
`stages: [manual]` is intended for this purpose.  or use `--config` and sequester your special hooks there

**Comment by asottile** [comment]
also "multiple searches" does not help me understand what you tried to find. in the future please fill out the field
