### ISSUE TITLE
precommit hook script not using nixos compatible stuff

### ISSUE THREAD

**Issue by LDprg** [pre-commit/pre-commit#3001]
### search you tried in the issue tracker

Well nothinf similar found

### describe your issue

Well I used precommit on nixos when .git/hook/pre-commit file reported that it couldnt find bash as a interpreter!

As a workaround I changed the reference to the nixos-store path of bash the `#!/usr/bin/env bash` command and everything worked!

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
not needed
```

**Comment by asottile** [comment]
there are many duplicates if you search for nixos
