### ISSUE TITLE
pre-commit-validate-config and pre-commit-validate-manifest: ImportError: cannot import name 'validate_manifest_main'

### ISSUE THREAD

**Issue by skwde** [pre-commit/pre-commit#3002]
### search you tried in the issue tracker

is:issue is:open pre-commit-validate / is:issue is:open ImportError 

### describe your issue

```sh
$ pre-commit-validate-config --version
Traceback (most recent call last):
  File "~/.conda/envs/pre-commit/bin/pre-commit-validate-config", line 6, in <module>
    from pre_commit.clientlib import validate_config_main
ImportError: cannot import name 'validate_config_main' from 'pre_commit.clientlib' (~/.conda/envs/pre-commit/lib/python3.11/site-packages/pre_commit/clientlib.py)

$ pre-commit-validate-manifest --help
Traceback (most recent call last):
  File "~/.conda/envs/pre-commit/bin/pre-commit-validate-manifest", line 6, in <module>
    from pre_commit.clientlib import validate_manifest_main
ImportError: cannot import name 'validate_manifest_main' from 'pre_commit.clientlib' (~/.conda/envs/pre-commit/lib/python3.11/site-packages/pre_commit/clientlib.py)
```

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
---
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.5.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
        args: ["--config","commitlint.config.js"]
```

**Comment by asottile** [comment]
those were removed in 3.0.  I suspect your packager has messed those up

**Comment by skwde** [comment]
@asottile that's weird, even after a fresh install the commands 

```sh
pre-commit                    pre-commit-validate-config    pre-commit-validate-manifest 
```

are available.

If I deactivate the environments, none of the above is available.

The `pre-commit` sub-commands `validate-config` and `validate-manifest` are available.

I tested

```sh
pre-commit validate-config
```

which works.

So the problems seems to be in bash-completions?!
Any idea?

The install is done via pip in a conda environment.

Since <https://github.com/pre-commit/pre-commit/issues/1986> mentions `pre-commit-validate-*` I link it here.

**Comment by asottile** [comment]
yeah -- figure out why your distributor has messed up the package -- those are not present in the `pre-commit` I send to pypi but some mistake in someone else's packaging (conda?)
