### ISSUE TITLE
Option to return exit code 0 when files were changed

### ISSUE THREAD

**Issue by Feuermurmel** [pre-commit/pre-commit#3007]
### search you tried in the issue tracker

`failed modified`, `"exit code" modified`, `modified success`

### describe your actual problem

_I'm kind of surprised this hasn't been suggested before. If it was, I'm sorry for opening a duplicate issue._ There's this StackOverflow post which kind of describes my issue: https://stackoverflow.com/questions/75272028/pre-commit-differentiating-between-files-modified-and-actual-failure

Context: I'm a member of a team working on a large-ish Python project. I'm investigating introducing automated formatting, currently looking at black and isort.

My use case: I'm using `pre-commit` to run the auto-formatters (black, isort) in the pre-commit stage, to prevent people from committing code that would be changed by these tools. The default behavior of `pre-commit` works well in this case. Now I'm looking at providing a suggested configuration that people can use in their IDEs that would run those tools automatically on save.

We're already doing that for some other tooling where we've found that a shorter round-trip between editing and applying fixes (instead of waiting until commit) makes suboptimal fixes more likely to be caught.

Now in this case, the default behavior of `pre-commit` is not helpful. I could of course do something equivalent to adding a `|| true` to the command line to ignore all errors running `pre-commit`, but I think that's a suboptimal solution. What I'd like to have is an option that tells `pre-commit` to not treat files modified by the tools as a kind of failure.

I know that when files were modified by any of the tools, running `pre-commit` again could lead to another tool either modifying a file again and/or failing because a linter is now detecting some violation. But I think these cases are rare. In our case, we take care to run the tools in an order where a later tool would not undo a formatting change made by an earlier tool (which would be a problem `pre-commit` can't fix anyway) and to run linters _after_ code formatters.

### pre-commit --version

pre-commit 3.4.0

**Comment by asottile** [comment]
plus you already found [my answer](https://stackoverflow.com/a/75272269/812183) so I'm not sure what else you want to hear :)

**Comment by Feuermurmel** [comment]
> plus you already found [my answer](https://stackoverflow.com/a/75272269/812183) so I'm not sure what else you want to hear :)

I read your answer on SO as "this is currently not support", so I proposed to add that feature. I understand that you are not interested in it.

What do you propose as a workaround for my use case? Would you suggest doing what [odigity](https://stackoverflow.com/users/210867/odigity) proposed in the comments to your answer?

> For my purpose, I'm considering running it twice, and if it succeeds the second time, treating that as an "autorepair" event instead of a "blocker".

**Comment by asottile** [comment]
I'm not sure how you could interpret "no but also it also would be impossible to know" as "this is possible to support"

**Comment by chriskuehl** [comment]
Keep in mind that a modification introduced by one hook can cause a hook that was previously passing to fail the next time you run pre-commit. There can also be hooks that are able to auto-fix some errors but fail on other unfixable errors.

So if you're going to do this, you should probably follow the idea to run pre-commit a second time to see if it succeeds, rather than assume all hooks pass after modifications.

**Comment by Feuermurmel** [comment]
> So if you're going to do this, you should probably follow the idea to run pre-commit a second time to see if it succeeds, rather than assume all hooks pass after modifications.

I see that point, and I briefly discussed it in the description of this issue. But IMHO it doesn't apply to my use case because the final check runs at commit time, not when the file is saved. My use case is not to replace the Git pre-commit hook with the `pre-commit` being run on save in an IDE (I wrote that in the description in more detail). I'm also not intending to use the feature I'm proposing here when `pre-commit` runs from the Git pre-commit hook, but only when used by the IDE on save. To summarize the two cases:

- User saves file: IDE runs `pre-commit --no-treat-file-modifications-as-failure`.
- User runs `git commit`: Git hook runs `pre-commit`.

> I'm not sure how you could interpret "no but also it also would be impossible to know" as "this is possible to support"

I think I answered your question? Your answer assumes that I'd want to run "linting" tools on save.

Also, I'm only intending to run tools that automatically fix stuff (e.g. auto-formatters) in the first case. Running anything that only reports errors is useless in that case, that's what IDE integrations for those tools are for. They can show the errors in the editor.

**Comment by asottile** [comment]
feel free to do whatever you want -- but I'm not going to attempt to solve an impossible problem

**Comment by Feuermurmel** [comment]
Wow, you're resorting to sarcasm, basically telling me I'm stupid, instead of explaining how you intend `pre-commit` to be used in this scenario. I know that what I am proposing would work and have the intended effect for me and my co-workers, because the even stupider solution of running `pre-commit || true` also has the desired effect, with some drawbacks.

Even the simpler approach of providing different exit codes for the different scenarios would cater for this use case, without violating any of the principles you're following.

Peace out.
