### ISSUE TITLE
[3.4.0] pre-commit autoupgrade downgrads yapf v0.40.1 to v0.40.0?

### ISSUE THREAD

**Issue by hartwork** [pre-commit/pre-commit#3010]
### search you tried in the issue tracker

"autoupdate", "yapf", "downgrade"

### describe your issue

Hi!

I'm having trouble understanding why pre-commit autoupdate is downgrading v0.40.1 to v0.40.0 while…
- both versions are non-prereleases of yapf (https://pypi.org/project/yapf/#history)
- `pip3 install yapf` would get me v0.40.1 not v0.40.0
- Python is at 3.11 and yapf does not even require this recent (https://github.com/google/yapf/blob/main/pyproject.toml)

From what I found in existing issues:
- #2811 and #2364 are different
- #2831 looks similar but provides no hints or help, and I did search

Any chance you could help me understand why this is happening?
For a minimal reproducer in a Bash Linux terminal:

```console
# cd "$(mktemp -d)"

# cat <<EOF > .pre-commit-config.yaml
repos:
- repo: https://github.com/google/yapf
  rev: v0.40.1
  hooks:
    - id: yapf
EOF

# python3.11 -m venv venv

# source venv/bin/activate

# pip3 install pre-commit

# hash pre-commit

# pre-commit --version
pre-commit 3.4.0

# git init

# rm ~/.cache/pre-commit/pre-commit.log

# pre-commit autoupdate
[https://github.com/google/yapf] updating v0.40.1 -> v0.40.0   # why?!

# cat ~/.cache/pre-commit/pre-commit.log
cat: /home/sping/.cache/pre-commit/pre-commit.log: No such file or directory
```

Thanks in advance!

### pre-commit --version

3.4.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/google/yapf
  rev: v0.40.1
  hooks:
    - id: yapf
```

**Comment by asottile** [comment]
#2507 and #1555 are exact duplicates I found using your search terms

**Comment by hartwork** [comment]
> from https://pre-commit.com/#updating-hooks-automatically
> 
> > this will bring the hooks to the latest tag on the default branch.
> 
> ```
> $ git clone git@github.com:google/yapf >& /dev/null
> $ cd yapf
> $ git describe --abbrev=0 --tags
> v0.40.0
> ```
> 
> github also gives a hint that someone mistagged a non-mainline commit https://github.com/google/yapf/tree/v0.40.1

@asottile the tag is not on `main` there indeed. That's not critical to my projects though, is there a way to still include that tag despite not being a predecessor of `main`?
PS: I will open a wish for re-tagging and a new release with yapf upstream.

> #2507 and #1555 are exact duplicates I found using your search terms

If you look at e.g. https://github.com/pre-commit/pre-commit/issues?page=1&q=is%3Aissue+downgrade there are many tickets of little relation to look past manually and I just missed/overlooked it. It sure is easier to find issues when you've all seen them before like I would have on my own projects.

**Comment by asottile** [comment]
> is there a way to still include that tag

there's nothing stopping you from using that non-mainline tag.  autoupdate is merely a convenience and you are not required to use it

btw I took `autoupdate downgrade` and found those issues in about 15 seconds

**Comment by hartwork** [comment]
> there's nothing stopping you from using that non-mainline tag. autoupdate is merely a convenience and you are not required to use it

@asottile come on, that's not an argument. pre-commit autoupdate is working great for me most of the time.

> btw I took `autoupdate downgrade` and found those issues in about 15 seconds

Are you saying that you having seen all the tickets before and the need to look past irrelevant tickets is irrelevant to you?

**Comment by asottile** [comment]
I'm saying you should have spent a few more minutes scrolling through issues and spared me this wasted time
