### ISSUE TITLE
Latest versions of node/npm used to set up environment for node-based hooks?

### ISSUE THREAD

**Issue by hoffch** [pre-commit/pre-commit#3013]
### search you tried in the issue tracker

node npm latest

### describe your actual problem

This is rather a question than a fully-fletches feature request (yet).

If I got it correctly, pre-commit sets up an isolated environment for each `node.js`-based hook (using nodeenv). The question is: *which `node` and `npm` releases are used to populate this environment?* Could it be that the *latest* version is used by default? If not, could you sketch the underlying process, particularly the involved tools and the call chain? That would be extremely helpful for further debuggin.

If case that actually the lastest version are used: that would introduce some non-reproducibulity (and possibly upstream errors, as in our case) into projects, even if they pin the version of pre-commit and it's hooks. From the point of view of a CI engineer (and likely others), it would then be desirable to have the possibility to pin the underlying `node` and `npm` versions in pre-commit, to ensure reproducible builds.

Background of this question: on 2023-09-28, we observed that `pre-commit install-hooks` suddenly failed in different projects and on different machines, yet with varying error messages (most related to networking issues). In all cases, the underlying code or the environment had not changed. The problem occurred (and still occurrs) with pre-commit `2.21.0` and `3.4.0`, and various Python versions from `3.8.0` to `3.11.5`. Intensive debugging eventually lead us to the new [node version 20.8.0](https://nodejs.org/dist/v20.8.0/), *which was released on exactly that date*. Seems that the server providing [the relevant archive](https://nodejs.org/dist/v20.8.0/node-v20.8.0-win-x86.zip) it overloaded with the mass of downloads right now: directly downloading that archive from the browser fails or gets stuck in 9 of 10 cases at the moment. We assume that this behavior also causes the observed issues with `pre-commit install-hooks`.

### pre-commit --version

3.4.0

**Comment by asottile** [comment]
the docs show how the version is picked and what versions are available

**Comment by hoffch** [comment]
@asottile Thanks for the quick response. May I humbly ask to point me to that part of the documentation? The only roughly related part that I found [is this](https://pre-commit.com/#node). Yet that does not explain how the version is picked.  May I have overlooked something obvious? In that case I'll apologize.

**Comment by asottile** [comment]
^F node and you'll find it eventually
