### ISSUE TITLE
Pass directories instead of file paths

### ISSUE THREAD

**Issue by mmlb** [pre-commit/pre-commit#3014]
### search you tried in the issue tracker

sort files and other things related to one-file-per-invocation

### describe your actual problem

I've come to this feature request from a go developer stand point. Many of the go dev tooling works on a package path, aka directories. It would be really nice if pre-commit supported that instead of per-file. I use pre-commit via https://github.com/cachix/pre-commit-hooks.nix/ which does the for-loop-in-bash workaround for those that want one-file-per-path. This ends up working fine but wasteful. Since the files are shuffled its possible to see files from the same directory be over different partitions/calls to the `entry`. I'd really like directories instead of files, but otherwise the ability to sort instead of shuffle.

I'd be happy to do the PR if deemed acceptable and would appreciate a pointer into the code to start looking into.

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
pre-commit only operates on files and that's not changing

**Comment by mmlb** [comment]
@asottile gotcha, how about sorting of files instead of shuffling?

**Comment by asottile** [comment]
I'll invite you to read the history about why they are shuffled instead of me reiterating it

**Comment by mmlb** [comment]
I did see https://github.com/pre-commit/pre-commit/issues/861 earlier. You mention that deterministic shuffling might be the best that can be done https://github.com/pre-commit/pre-commit/issues/861#issuecomment-440079479 but in many go projects thats not the case. If we could opt-in to sorting instead of shuffling that would work really well for many go tools.

**Comment by asottile** [comment]
no means no.  please stop replying when I've already said it's not changing
