### ISSUE TITLE
Can some project be hosted on this organization?

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit/pre-commit#3015]
### search you tried in the issue tracker

host on organization

### describe your actual problem

I notice a pre-commit hook for clang-format are hosted on this github organization <https://github.com/pre-commit/mirrors-clang-format>.

Can some similar projects be hosted on this organization for visibility?

- [astyle-wheel](https://github.com/Freed-Wu/astyle-wheel/): needed by mirrors-astyle
- [mirrors-astyle](https://github.com/Freed-Wu/mirrors-astyle): A pre-commit hook for astyle (another formatter for C)

IMO:

- It should make people easier to find them
- And let maintainer get more bug reports to improve it
- Increase [bus factor](https://en.wikipedia.org/wiki/Bus_factor)

TIA!

### pre-commit --version

/

**Comment by asottile** [comment]
no thanks I already have enough on my plate
