### ISSUE TITLE
Add a file_additional type and a corresponding files_additonal pattern to extend types_or with new file extensions

### ISSUE THREAD

**Issue by jevinskie** [pre-commit/pre-commit#3018]
### search you tried in the issue tracker

types_or files

### describe your actual problem

I want write a hook that uses clang-format behind a wrapper to [parse Logos files](https://github.com/pre-commit/identify/pull/418). The PR was rejected because the file extensions were considered too ambiguous but it leaves me in a spot where I have to not only extend the wrapper-clang-format hook's `types_or` declaration but abandon `identify` types for `c++, c, c#, cuda, java, javascript, json, objective-c, objective-c++, proto, textproto` entirely and reimplement them using a `files` pattern.

From the documentation:

> If you want to match a file path that isn't included in a type when using an existing hook you'll need to revert back to files only matching by overriding the types setting.

I want to be able to use `identify` types in `types_or` with an additional means of specifying more files based on filename pattern matching.

I humbly suggest some sort of new `file_additional` type tag that matches filenames against a `files_additonal` pattern. You can bike shed the `file_addional` naming all you want. It would probably be bad form to have `file_additional` use the existing `files` pattern because that may be a breaking change for some folks - thus it should probably have a new, dedicated extension pattern (also open to bike shedding on the name).

Do you have any other suggestion about how to cleanly achieve what I'm working towards here? Having to give up on `identify` types entirely and fall back to only using `files` patterns is a big bummer.

### pre-commit --version

pre-commit 3.4.0

**Comment by asottile** [comment]
you don't need that because you can specify a hook as many times as you want:

```
    -  id: clang-format
    -  id: clang-format
       alias: clang-format-logos
       types: [file]  # reset to default
       files: ... # whatever you need
```

if you searched a little more in the issue tracker you would have found a similar recipe
