### ISSUE TITLE
Support ESLint new-style configuration

### ISSUE THREAD

**Issue by jklaiho** [pre-commit/pre-commit#3022]
### searches you tried in the issue tracker

eslint, eslint.config.js

### describe your actual problem

It seems like the ESLint hook doesn't support the new "flat" style config of ESLint, which will be the default from version 9.0.0 onwards, and is already working in the 8.x series, too, if you place a config file called `eslint.config.js` in the project root folder instead of an old-style config file.

I'm categorizing this as a feature request rather than a bug report, but that's just a hunch on my part—if this is supposed to already work, then I'm clearly missing something.

The relevant section of my `.pre-commit-config.yaml` is this:

```yaml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
    - id: eslint
      types: [javascript]
      additional_dependencies: [
        'globals@13.21.0',
        'eslint@8.51.0',
        '@eslint/js',
        'eslint-config-prettier@9.0.0'
      ]
```

If I use a classic-style configuration file called `.eslintrc.json` like this, everything works:

```
{
    "env": {
      "es2022": true,
      "browser": true
    },
    "extends": [
      "eslint:recommended",
      "prettier"
    ],
    "ignorePatterns": [
      "project/static/htmx/**"
    ],
    "parserOptions": {
      "sourceType": "module"
    },
    "rules": {}
}
```

However, things break when I replace that with this new `eslint.config.js`:

```
import globals from "globals";
import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  eslintConfigPrettier,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
      },
      sourceType: "module",
      ecmaVersion: 2022,
    },
  },
  {
    ignores: ["project/static/htmx/**"],
  },
];
```

This is the error that gets produced by `pre-commit run --all-files`:

```
eslint...................................................................Failed
- hook id: eslint
- exit code: 2

Oops! Something went wrong! :(

ESLint: 8.51.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'globals' imported from /Users/jkl/Development/foobar/eslint.config.js
Did you mean to import globals/index.js?
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```

The same type of error happens if I place the imports for `eslintConfigPrettier` or `js` first in the file, so this is not about the `globals` package as such. The syntax of the imports is the same as in [the ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#using-predefined-configurations) so I'd assume that the "Did you mean..." section of the error is misleading.

Both the old and new style configs that I tested were in the same dir as the pre-commit config YAML, under `/Users/jkl/Development/foobar`. I do not have ESLint installed globally, so this should not be a case of the hook using that instead of its own ESLint instance.

Is there some extra configuration I need to do to make this work, or is this just something that's not yet implemented at the pre-commit (possibly, `mirror-eslint`) level?

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
pre-commit just calls eslint there's no magic happening
