### ISSUE TITLE
Auto-update with `--config` option should run everywhere

### ISSUE THREAD

**Issue by 5ouma** [pre-commit/pre-commit#3025]
### search you tried in the issue tracker

autoupdate config

### describe your actual problem

I set a global `pre-commit.yml` file by `pre-commit init-templatedir "$XDG_CONFIG_HOME/git" --config='/path/to/pre-commit.yml'` to use that config file for all repositories, and it loads it by `git config --global core.hooksPath ~/.config/git/hooks`.
If I'm in a git repository, it successfully runs `pre-commit autoupdate --config='/path/to/pre-commit.yml'` and updates **the same** global file. However, when I'm in a non-git repository, it doesn't run `An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?`, even if it has a file to update.

I want it to update when a `--config` option is added.

### pre-commit --version

pre-commit 3.4.0

**Comment by asottile** [comment]
you are in unsupported territory -- you're on your own
