### ISSUE TITLE
Environment Variable for `--config`

### ISSUE THREAD

**Issue by 5ouma** [pre-commit/pre-commit#3026]
### search you tried in the issue tracker

environment variable config

### describe your actual problem

I use an override function to set `--config` by default, but some commands like `clean` or `gc` can't run with this option.
So I want to use an environment variable like `PRE_COMMIT_CONFIG` to load a config file as needed as `PRE_COMMIT_COLOR` or `PRE_COMMIT_HOME`.

### pre-commit --version

pre-commit 3.4.0

**Comment by asottile** [comment]
no thanks, this option is intentionally verbose to discourage the hacks that need it
