### ISSUE TITLE
run multiple hook stages 

### ISSUE THREAD

**Issue by tekumara** [pre-commit/pre-commit#3037]
### search you tried in the issue tracker

run multiple hook stages 

### describe your actual problem

I'd like to use `pre-commit run` to run hooks from multiple hook stages, eg:

```
pre-commit run --all-files --hook-stage pre-commit --hook-stage pre-push --hook-stage manual
```

This would be super useful in CI (eg: Github actions) for making sure all hooks are run.

### pre-commit --version

pre-commit 3.5.0

**Comment by tekumara** [comment]
NB: whilst its possible to do this with multiple `pre-commit run` commands, its not as easy to mimic the behaviour of pre-commit eg: don't fail-fast when a hook fails, but still report a non-zero exit status.

**Comment by asottile** [comment]
use &&

**Comment by tekumara** [comment]
Thank you for your response @asottile 🙏 

So when I use `&&` I find that hooks in the second `pre-commit run` command aren't run if any hooks in the first `pre-commit run` command fail.

I'd love the failure handling behaviour of pre-commit, ie: run all the hooks, regardless of whether previous ones fail, but still report a non-zero exit status when any fail. It's not immediately obvious to me what the equivalent shell incantation for this behaviour might be (and I imagine differs between Windows and Linux). So running multiple hook stages from pre-commit itself would be helpful!

**Comment by asottile** [comment]
while we are not a code debugging service here's what you want
```bash
fail=0
x || fail=1
x || fail=1
```

what you're asking for is not really possible without breaking pre-commit and making its checks unsafe
