### ISSUE TITLE
Is there a way to add a custom language?

### ISSUE THREAD

**Issue by mlisovyi** [pre-commit/pre-commit#3040]
### search you tried in the issue tracker

add new language

### describe your actual problem

I would want to add a new language to the [languages defined by the tool](https://pre-commit.com/#supported-languages) in an application repository or in a thin wrapper around `pre-commit` package.

Is there a mechanism to do it other than making a full fork and making changes there?

Thanks in advance for any feedback

### pre-commit --version

3.4.0

**Comment by asottile** [comment]
there is not, nor is there any guarantee on the API of languages so I would not recommend doing that and instead try and contribute it here

**Comment by asottile** [comment]
there is advice in the contributing docs on adding a new one though and the support level
