### ISSUE TITLE
Python library is being installed without its git version tag

### ISSUE THREAD

**Issue by johentsch** [pre-commit/pre-commit#3047]
### search you tried in the issue tracker

is:issue git version tag 

### describe your issue

We've started using my library `ms3` as a pre-commit hook to generate additional files before committing. These include metadata files which routinely state the version of `ms3` used to generate them.

**Expected behaviour**

The library should output the same version that is stated in the `.pre-commit-config.yaml` file calling it (currently `v2.4.0`).

**Observed behaviour**

Instead, the version information is something like `0.0.post1.dev1+gc24101c`. Needless to say that under all other circumstances the version output is correctly based on the latest git tag.

**Possible explanation**

The version output looks like a version tag for a git repo that does not come with any tags. Could it be that `pre-commit` clones the repository without the relevant version tag?

**Useful information**

`ms3` infers its own version using the `importlib.metadata` module, which happens [here in the top-level __init__.py](https://github.com/johentsch/ms3/blob/main/src/ms3/__init__.py#L14). It is written to the file `__version__.py` from where it can be imported by any other module.

**How to reproduce**

1. `git clone https://github.com/johentsch/ms3 --depth 1`
2. Replace the contents of `.pre-commit-hooks.yaml` with the content below
3. In the repo, execute `pre-commit try-repo . --all-files --verbose`

<details><summary>Output</summary>
<p>

```bash
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
0.0.post1.dev1+gc587578
```

</p>
</details> 

To convince yourself that under normal circumstances it works correctly, you could `pip install .` and then execute `ms3 --version`.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-hooks.yaml

```yaml
-   id: version
    name: Show ms3 version
    entry: ms3 --version
    language: python
```

**Comment by asottile** [comment]
this is setuptools-scm bamboozling you.  the revision that's checked out is exactly the one requested

there are a bunch of duplicates if you search around for the version strings or setuptools-scm

**Comment by johentsch** [comment]
I'm sorry @asottile but I need to kindly ask your support for debugging this. I've left the bug there for 15 months to sort it out later: today. I've spent 3+ hours to no avail. Based on the existing tickets I've played around with my [pyproject.toml](https://github.com/johentsch/ms3/blob/main/pyproject.toml) quite a lot (including solutions mentioned here: https://stackoverflow.com/a/79271095).
My biggest hope that was that updating the file to what they show in their [README](https://github.com/pypa/setuptools-scm) would solve the issue:

```
[build-system]
requires = ["setuptools>=64", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "ms3"
dynamic = ["version"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
```

No. The result is always the same: The library builds perfectly fine with some correct (dirty) version number (e.g. `'ms3-2.6.0.post1.dev2+g210aebad.d20250320'`, depending on the current setting) which can be verified with `ms3 --version` but when `pre-commit` installs `ms3`, it consistently outputs some incorrect version number which looks like a "guessed" next version string based on some dummy/fallback `0.0.0` (such as `0.0.post1.dev1+gabcdfac`). It seems pretty obvious that the problem is related to the absence of git tags.

#2610 seems to be very much about the same issue. My impression is -- and I'll be more than happy to be corrected -- that although the user indicates the version tag to tell `pre-commit` which commit to checkout, the resulting clone comes without any tags, not even with the only one that would be the needed, the one pointing at the commit that was checked out. After you closed that ticket, you commented

>  it's pretty easy to use importlib.metadata.version at runtime rather than needing to tie your distributions to your VCS

I have to say I'm not expert enough to understand how exactly things are supposed to work for pre-commit to do this correctly, all I know is that `ms3` _does_ use `importlib.metadata.version` at runtime and the output _is_ tied to the VCS (output of `ms3 --version` corresponds to the output of `git describe --tags`). If you could point me to the code where the cloning & install is happening, I would gladly try to set up a minimal (non-)working example.

**Comment by johentsch** [comment]
I would be willing to do this but I've set up the library using [PyScaffold](https://pyscaffold.org/) and rely on it to update the library's infrastructure. I could not find a guide on how to "ditch" setuptools-scm and it seems to be fairly standard to use. Independently of that, versioning software based on Git tags (and derivates) nowadays is a wide-spread standard, too. When pre-commit installs `ms3 @ v2.6.0` why is it not possible that the clone comes with the tag `v2.6.0`?

**Comment by asottile** [comment]
it does, setuptools-scm just doesn't detect it

**Comment by johentsch** [comment]
I see. Could you please indicate how I need to restructure `ms3` so that `importlib.metadata.version` will return the correct string after `pre-commit` installs it?

**Comment by asottile** [comment]
for instance specify the version in pyproject.toml

**Comment by johentsch** [comment]
You mean filling in the value manually for each version? Sounds like step back to me...
