### ISSUE TITLE
Allow install into alternate location

### ISSUE THREAD

**Issue by innermatrix** [pre-commit/pre-commit#3049]
### search you tried in the issue tracker

install

### describe your actual problem

I want to use a tool that automates sharing of git hooks (for example `git config core.hooksPath` or https://github.com/kilianc/shared-git-hooks), which require hooks to be installed in an alternate location — but there is no way to ask `pre-commit` to install itself into a place other than `.git/hooks`. 

I would like to be able to `pre-commit install --hooks-dir foo` or something similar

### pre-commit --version

pre-commit 3.4.0

**Comment by asottile** [comment]
please put in more than zero effort to find duplicate issues.  "install" is obviously not going to get you anything actually relevant

this is intentional -- if you search your actual error message you will find many alternate solutions if you want to continue in unsupported territory
