### ISSUE TITLE
How to pull the remote script so it can be run in my local repository?

### ISSUE THREAD

**Issue by isaacporras** [pre-commit/pre-commit#3051]
### search you tried in the issue tracker

How to pull remote script.

### describe your issue

Hi,

I want to create a custom hook to run checkpatch.pl script. To do that I have:

1. A remote repository with the `.pre-commit-hooks.yaml` file. The contents are:

```shell
- id: checkpatch
  name: checkpatch
  description: "Check-Patch: perl script which checks for trivial style violations in patches and optionally corrects them."
  entry: checkpatch.pl
  language: system
  types: [c]
``` 

The remote repository tree is:
```shell
.
├── .pre-commit-hooks.yaml
└── checkpatch.pl
``` 

On my local repo, I want to pull that checpatch.pl script and run it. So my `.pre-commit-config.yaml`

```shell
repos:
-   repo: /home/my_username/path_to_the_repo
    rev: commit_id
    hooks:
    -   id: checkpatch
        args: [-f , '--no-tree']
``` 

However when I try to run `pre-commit run --all-files`, it gives me the following error:

```
Executable `checkpatch.pl` not found
``` 

It seems like it is not pulling the script so I it cant be runned in the local repository. I can successfully run the checkpatch.pl if i place the file in the local repo. However, the hole point of having the remote repository is to store the script there and not locally (also to multiple repositories can use the script and not having to add it to each single one of them).

Things that I have tried:

Run:

```
pre-commit install
``` 

However it doesnt seem to install the script.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: /home/my_username/path_to_the_repo
    rev: commit_id
    hooks:
    -   id: checkpatch
        args: [-f , '--no-tree']
```

**Comment by asottile** [comment]
you want `language: script`

**Comment by isaacporras** [comment]
Thanks, that worked.
Also, is there a way to include needed files by the script? Such as `spelling.txt` that is needed by checkpatch?

**Comment by asottile** [comment]
you can reference them relative to your script (in python it's `__file__` -- no idea in perl)
