### ISSUE TITLE
When running `pre-commit autoupdate` choose which type of update you want

### ISSUE THREAD

**Issue by paddyroddy** [pre-commit/pre-commit#3052]
### search you tried in the issue tracker

autoupdate major

### describe your actual problem

I have a package that is a GitHub Action as well as a `pre-commit` hook. So it updates in minor version `v0.1.0` and has a major version tracking it `v0` which will update automatically on tag. For the purpose of GitHub actions this is what I want as I can do `paddyroddy/my-action@v0`. But for the `pre-commit` hook I want to point to `v0.1.0` and when I run `pre-commit autoupdate` it should go to `v0.2.0`, not `v0` (as mutable reference error will happen). But this is what occurs when I run `pre-commit autoupdate`.

I tried the minor versions to be without `v`, i.e. `0.1.0` & `v0`. As well as `v0.1.0` & `0` and that approach worked the same as if both had the `v` in front.

### pre-commit --version

3.5.0

**Comment by asottile** [comment]
there are many duplicates. please search better

**Comment by paddyroddy** [comment]
> there are many duplicates. please search better

Could you please point me to some? I searched a fair few

**Comment by paddyroddy** [comment]
My bad I found #2311. When I run `git describe FETCH_HEAD --tags --abbrev=0` on https://github.com/paddyroddy/.github I get `v0.34.0`. So why does it go to `v0` when running `pre-commit autoupdate`?

**Comment by paddyroddy** [comment]
I have fixed my issue by manually creating a non-annotated tag https://github.com/paddyroddy/.github/blob/3ddbe9b8e3d71099c363c70b2c4f4eb1aa8a2748/.github/workflows/tags.yml#L41-L49. Found remark here https://github.com/pre-commit/pre-commit/issues/1925#issuecomment-849888460.
