### ISSUE TITLE
[pre-commit]: Spellcheck hook for source code and gitlab/github for commit messages and MR/PR descriptions

### ISSUE THREAD

**Issue by honey-speaks-tech** [pre-commit/pre-commit#3055]
### Search you tried in the issue tracker

spelling

### Describe your actual problem

Hi all,

I wonder if there is a pre-commit hooks that could be used for spell-check. It should support one or all of the following.

Spell-check required in source code lines including comments.
Spell-check required in documents integrated in source code repository - For eg: markdown files for detailed design etc those are close to code, README etc.
Spell-check required in Gitlab/Github (eg: commit messages, MR/PR descriptions etc).
On a quick skim, I haven't found anything mentioned in pre-commit website, but found one github project: [git-spell-check](https://github.com/mprpic/git-spell-check). Seems like the last change happened 6 years ago, so not sure if it is the standard one to be used.

Any advice / pre-commit package suggestions would be greatly appreciated.

Thank you in advance,
Honey

Honey Sukesan (She / her)

### pre-commit --version

pre-commit (any)

**Comment by asottile** [comment]
try searching the Internet or looking on pre-commit.com/hooks
