### ISSUE TITLE
Issue installing pre-commit

### ISSUE THREAD

**Issue by JessenWilliam88** [pre-commit/pre-commit#3057]
### search you tried in the issue tracker

AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

### describe your issue

Get error when installing pre-commit

[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...

An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/jessen11/.cache/pre-commit/repohc_o_j7k/py_env-python3/bin/python>>
- expected version: 3.10.12.final.0

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-json
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [Flake8-pyproject]
```

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.34.1
sys.version:
    3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/jessen11/.cache/pre-commit/repohc_o_j7k/py_env-python3/bin/python>>
- expected version: 3.10.12.final.0

```

```
Traceback (most recent call last):
  File "/home/jessen11/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/jessen11/.local/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return hook_impl(
  File "/home/jessen11/.local/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
  File "/home/jessen11/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/jessen11/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/jessen11/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 100, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/jessen11/.cache/pre-commit/repohc_o_j7k/py_env-python3/bin/python>>
- expected version: 3.10.12.final.0
```

**Comment by asottile** [comment]
so... describe your environment

**Comment by swills1** [comment]
What steps did you follow to install and what OS?

**Comment by JessenWilliam88** [comment]
I am using WSL in my VS Code Terminal. I get the pre-commit by downloading via pip install and run pre-commit install, where the error appears.

**Comment by asottile** [comment]
what os in WSL?

**Comment by swills1** [comment]
> what os in WSL?

https://learn.microsoft.com/en-us/windows/wsl/install
It would help to know what steps you've gone through, @JessenWilliam88. This is most likely an issue with your setup.

**Comment by JessenWilliam88** [comment]
Let me update later, thanks for the link

**Comment by JessenWilliam88** [comment]
Closing this
