### ISSUE TITLE
Add option exclude_file_path to allow passing a file path with a list of excludes.

### ISSUE THREAD

**Issue by cesan3** [pre-commit/pre-commit#3059]
### search you tried in the issue tracker

provide option to pass external file with excludes files or patterns

### describe your actual problem

I need to exclude a huge list of paths from several hooks.  I'd like the ability to provide an option with a file containing the files/patterns.

I'll provide PR

### pre-commit --version

pre-commit 3.5.0

**Comment by asottile** [comment]
no thank you -- pre-commit only reads from its configuration file and I'm not changing that

**Comment by asottile** [comment]
fwiw you probably want https://pre-commit.com/#top_level-exclude or to use yaml anchors of some sort
