### ISSUE TITLE
Missing files when running pre-commit run -a

### ISSUE THREAD

**Issue by tetienne-zenchef** [pre-commit/pre-commit#3061]
### search you tried in the issue tracker

missing, all files

### describe your issue

Hi, 

Here my git status (sorry in French)

```
❯ git status
...
Modifications qui seront validées :
  (utilisez "git restore --staged <fichier>..." pour désindexer)
        modifié :         app/Providers/AuthServiceProvider.php
```

As you can see, when running manually php -l, I well get an error

```
❯ php -l app/Providers/AuthServiceProvider.php                                       
PHP Parse error:  Unclosed '[' on line 15 does not match '}' in app/Providers/AuthServiceProvider.php on line 30

Parse error: Unclosed '[' on line 15 does not match '}' in app/Providers/AuthServiceProvider.php on line 30
Errors parsing app/Providers/AuthServiceProvider.php
```

if I launch`pre-commit run`, the same error is well returned

```
❯ pre-commit run                              
Check PHP syntax.........................................................Failed
- hook id: php-l
- exit code: 255

PHP Parse error:  Unclosed '[' on line 15 does not match '}' in app/Providers/AuthServiceProvider.php on line 30

Parse error: Unclosed '[' on line 15 does not match '}' in app/Providers/AuthServiceProvider.php on line 30
Errors parsing app/Providers/AuthServiceProvider.php

identity.................................................................Passed
- hook id: identity
- duration: 0.02s

app/Providers/AuthServiceProvider.php
```

When I launch `pre-commit run -a`, there is no error returned.

```
❯ pre-commit run -a                    
Check PHP syntax.........................................................Passed
identity.................................................................Passed
- hook id: identity
- duration: 0.04s
```

If I grep the output (identity list all the impacted files),  my php file with the error is not returned. Some other php files are also not returned.

I cannot guess where I’m wrong in my configuration. My use case seems quit simple. Have you any idea on what happening here? Thx.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: php-lint
        language: system
        name: Check PHP syntax
        entry: php -l
        files: \.php$

  - repo: meta
    hooks:
      - id: identity
        files: \.php$
```

### ~/.cache/pre-commit/pre-commit.log (if present)

No log generated.

**Comment by asottile** [comment]
try adding `verbose: true` to your `php-lint` to see if something fishy is happening there?

what does `git ls-files` give you as well? (that's what pre-commit is looking at for `--all-files`)

**Comment by asottile** [comment]
can you show the hexdump of `git ls-files -z | hd -c` ?

**Comment by asottile** [comment]
it also looks like `php -l` only takes a single file at a time -- so it is ignoring every other argument on your commandline list.  you'll need to call it once per file probably (there are recipes if you search around for this in the issue tracker using either `xargs` or `bash` with a for loop)
