### ISSUE TITLE
Document what pre-commit considers a mutable reference to be, or tweak the definition

### ISSUE THREAD

**Issue by alexpdp7** [pre-commit/pre-commit#3073]
### search you tried in the issue tracker

"mutable"; I reviewed all matching issue subjects updated after #1715

### describe your actual problem

We had some unexpected warnings running pre-commit, because one of our hooks repository uses the following tagging scheme for versions; `yyyymmdd`, but `yyyymmdd.n` if we make multiple releases on the same day.

Tags with `.n` work well, but tags without `.n` generate a warning- which we discovered when we found #1715 , and I just read the discussion on #1794.

IMHO, at least it would be good to document this behavior outside the source code. Either the message error can be expanded to describe the regex used, or the docs.

I am not sure the regex approach is ideal. So maybe "we may revisit if this comes up more frequently"...?

### pre-commit --version

3.0.4

**Comment by asottile** [comment]
you found the answer without help so it's probably good enough as is
