### ISSUE TITLE
Custom hook last call is sometimes invoked with no arguments

### ISSUE THREAD

**Issue by bcdickinson** [pre-commit/pre-commit#3074]
### search you tried in the issue tracker

no arguments, xargs

### describe your issue

I have some custom hooks that call npm scripts. Sometimes, some combination of the number of files and the number of CPU cores is causing the last batch of arguments to the hook entry script to be empty, so it fails erroneously.

Example output from `pre-commit run -a fix:css`, the npm script that the `fix:css` hook calls runs `stylelint --report-needless-disables --fix`:

```
... <snip>
> project@0.0.0 fix:css
> stylelint --report-needless-disables --fix project/static_src/sass/govuk-components/_govuk-related-navigation.scss project/static_src/sass/components/_carousel.scss project/static_src/sass/govuk-components/_govuk-blockquote.scss
> project@0.0.0 fix:css
> stylelint --report-needless-disables --fix project/static_src/sass/config/_mixins.scss project/static_src/sass/govuk-components/_govuk-responsive-object.scss project/static_src/sass/components/_video-modal.scss
> project@0.0.0 fix:css
> stylelint --report-needless-disables --fix project/static_src/sass/components/_rich-text.scss project/static_src/sass/govuk-components/_govuk-pagination.scss project/static_src/sass/config/_gov_uk_variables.scss
> project@0.0.0 fix:css
> stylelint --report-needless-disables --fix
  A mighty, modern CSS linter.
  Usage: stylelint [input] [options]
  Input: Files(s), glob(s), or nothing to use stdin.
    If an input argument is wrapped in quotation marks, it will be passed to
    globby for cross-platform glob support. node_modules are always ignored.
    You can also pass no input and use stdin, instead.
  Options:
... <snip>
```
As you can see, it looks like the last partition of the filename args is empty, so stylelint prints its help message and exits with code 2, causing the hook to fail. 

I can work around this for now by setting `require_serial: true` in the hook config, but if I understand correctly, that's not guaranteed to prevent this for all CPU count/arg number/arg length/max command line length combinations.

### pre-commit --version

3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: fix:css
        name: fix:css
        language: system
        entry: >
          bash -c '
          cd ./src/ &&
          shopt -s extglob &&
          npm run fix:css ${*##*(./)src/}
          '
        types_or:
          - css
          - scss
```

**Comment by asottile** [comment]
this isn't a pre-commit problem.  try your command in your shell with positional arguments

**Comment by bcdickinson** [comment]
If it's not a pre-commit problem, then why would `require_serial: true` and having all of the files passed to one invocation of the script work fine? 

I guess it's not taken as read that I had tried to debug the bash command on its before raising this issue and maybe I should have been more explicit, so here you go:

```
$ css_files=$(git ls-files -- "**/*.?css"); cd src; shopt -s extglob; npm run fix:css ${css_files##*(./)src/} && echo success || echo failure

> project@0.0.0 fix:css
> stylelint --report-needless-disables project/static_src/sass/base/_base.scss src/project/static_src/sass/base/_fonts.scss src/project/static_src/sass/base/_typography.scss #  ... long list of every .[s]css file in my project

success
```

It seems _very_ likely to me that there's just a bug in the xargs code that results in an empty final partition sometimes. If I get time, I'll see if i can create a reproducible case (this only fails on a CI machine with a different number of cores to my laptop, which is inconvenient).

I get that reviewing issues out of the blue can be annoying, but I'd rather have no response than just get slapped down. There are real people on the other end of these things, you know! :sweat:

**Comment by asottile** [comment]
what's annoying is your attitude -- today is your [lucky day](https://xkcd.com/1053/)

```console
$ bash -c 'echo $*' file1 file2
file2
```
