### ISSUE TITLE
Improve error message if repo not set up for pre-commit

### ISSUE THREAD

**Issue by jkerhin** [pre-commit/pre-commit#3094]
### search you tried in the issue tracker

InvalidManifestError

### describe your actual problem

When building a project's `.pre-commit-config.yaml`, the error message you get when attempting to use a project that _is not_ configured for pre-commit takes a bit of work to debug. The only repo information printed to the screen is the path to the cached repository, e.g. `repoa8swhg2r`. There's no trivial way for the user to tell what repository `repoa8swhg2r` was created from, even when looking at `pre-commit.log`.

This particular issue bit me when I was moving from `flake8` to `ruff`. The `flake8` project _is_ configured with a `.pre-commit-hooks.yaml` file, but `ruff` has a separate `ruff-pre-commit` repo that needs to be used instead. 

In attempting to add some friendly error handling, I see that `pre-commit` is making heavy use of context managers to capture errors and process them. I've taken a first pass at updating `pre_commit/repository.py` to log the error message I'd like to have seen, but it's very likely that this is not the ideal solution. I'm especially leery of the way that I used a string comparison on `err.args[0].err_msg` to check for the condition to handle. I think the _correct_ way to handle this may involve a modification to the `cfgv` project so that missing files are treated differently than invalid files (e.g. [right here](https://github.com/asottile/cfgv/blob/0b2c646a82b9b4d5bdc9625e108656919fabd986/cfgv.py#L401)), but I'm not familiar enough with `cfgv` to make an informed suggestion there.

It's likely that I've missed some other areas where this should be handled, and I wasn't able to figure out the best way to add a test for this. So I would say that my PR (to come) is not ready for merge yet, but does implement the desired behavior in a simple case.

Before this change:  
```
> pre-commit
An error has occurred: InvalidManifestError:
=====> C:\Users\Joe\.cache\pre-commit\repoa8swhg2r\.pre-commit-hooks.yaml is not a file
Check the log at C:\Users\Joe\.cache\pre-commit\pre-commit.log
```

After this change:  
```
> pre-commit
[ERROR] Could not find .pre-commit-hooks.yaml in https://github.com/astral-sh/ruff - Is https://github.com/astral-sh/ruff configured to be used with pre-config?
An error has occurred: InvalidManifestError:
=====> C:\Users\Joe\.cache\pre-commit\repoa8swhg2r\.pre-commit-hooks.yaml is not a file
Check the log at C:\Users\Joe\.cache\pre-commit\pre-commit.log
```

### pre-commit --version

pre-commit 3.5.0

**Comment by asottile** [comment]
there's already an error message

**Comment by asottile** [comment]
you've cut the important part of the output which already shows the repo name right before the error

**Comment by jkerhin** [comment]
Ah, in working to reproduce, yes - the problem I attempted (and failed to) fix only occurs _after_ the registry has been created. 

The first time you run `pre-commit`, you do indeed get the helpful error message:
```
# from a 'clean' environment
$ pre-commit
[INFO] Initializing environment for https://github.com/astral-sh/ruff.
An error has occurred: InvalidManifestError:
=====> /home/joe/.cache/pre-commit/repo831vyfpk/.pre-commit-hooks.yaml is not a file
Check the log at /home/joe/.cache/pre-commit/pre-commit.log
```

However, if you don't fix the problem (and don't run `pre-commit clean`), each subsequent run will only show the `InvalidManifestError`

Second and all subsequent runs:
```
# from a 'dirty' environment
$ pre-commit
An error has occurred: InvalidManifestError:
=====> /home/joe/.cache/pre-commit/repo831vyfpk/.pre-commit-hooks.yaml is not a file
Check the log at /home/joe/.cache/pre-commit/pre-commit.log
```
