### ISSUE TITLE
Run hooks only on conflicting files in a merge conflict situation

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#31]
Most gripes I have with pre-commit hooks are "someone else doesn't have them enabled and I had to do their resolution during a merge conflict"

**Comment by vinayinvicible** [comment]
@asottile 
I recently faced an issue with pre-commits during merge conflict.

git's STDOUT during merge conflict looks like this

> From github.com:`REPO`
>  \* branch            master     -> FETCH_HEAD
> Auto-merging `M_file1`
> Auto-merging `C_file1`
> CONFLICT (content): Merge conflict in `C_file1`
> Removing `R_file1`
> Auto-merging `M_file2`
> Auto-merging `C_file2`
> CONFLICT (content): Merge conflict in `C_file2`
> Auto-merging `M_file3`
> Auto-merging `M_file4`
> Automatic merge failed; fix conflicts and then commit the result.
> 

I haven't modified any other file than the conflict files.
I would expect pre-commits to run only on `C_file*` files.
But it was running on both `C_file*` and `M_file*` files.

I am not sure if this was intended behavior.

**Comment by asottile** [comment]
Do you have a reproducible test case?

**Comment by vinayinvicible** [comment]
@asottile I've raised a PR #388

**Comment by vinayinvicible** [comment]
@asottile any updates on this

**Comment by asottile** [comment]
Just commented on the PR, sorry it took me so long to get back to this -- been pretty busy :D
