### ISSUE TITLE
require_serial: true splitting files into multiple lists

### ISSUE THREAD

**Issue by pasqualesalza** [pre-commit/pre-commit#3104]
### search you tried in the issue tracker

require_serial split

### describe your actual problem

Hello everybody. I'm trying to write a hook supporting also a long list of arguments, in particular when using `--all-files`.

As expected, if I simply omit the `require_serial` option, the list of files is split into multiple commands. However, I would have expected the list of files to be passed as a single item when using `require_serial: true`, but what happens is just that I reduce the number of splits, apart from executing the commands sequentially.

I thought it was because I was using `language: system`, but also with a custom hook in python I still get the same splits. Is it something that could be managed? Well, I suppose this is intended, but I wonder whether there is a way to manage the entire list of files as a single one, instead of having pre-commit calling the command multiple times.

### pre-commit --version

3.6.0

**Comment by asottile** [comment]
commands have a length limit.  you cannot expect to get all files in a single call ever
