### ISSUE TITLE
Mark official releases for mirrors-prettier

### ISSUE THREAD

**Issue by jarrodmillman** [pre-commit/pre-commit#3108]
### search you tried in the issue tracker

mirrors-prettier

### describe your actual problem

We are using pre-commit.ci for several projects and I use it to autoupdate the repos. We keep getting autoupdate PRs to update mirrors-prettier to alpha releases. We would rather only autoupdate to stable releases.

Would marking https://github.com/pre-commit/mirrors-prettier/releases/tag/v3.1.0 as a Release on GitHub fix this?
https://github.com/pre-commit/mirrors-prettier/releases

Sorry if this is the wrong place to ask, but the mirrors-prettier repo didn't have a place for opening issues.

### pre-commit --version

pre-commit 3.6.0

**Comment by asottile** [comment]
it would not, you can find many duplicates here and in pre-commit-mirror-maker about why there's no good solution
