### ISSUE TITLE
Compose multiple .pre-commit.yaml files

### ISSUE THREAD

**Issue by drewoldag** [pre-commit/pre-commit#3115]
### search you tried in the issue tracker

"compose" "multiple yaml files"

### describe your actual problem

I would like to be able to compose multiple pre-commit yaml files. We use templates to quickly generate projects, and each template has an associated set of pre-commit hooks. Currently we have to manually copy/paste the hooks into a single file. 

Is there an existing way to compose a set of pre-commit yaml files into one? 

### pre-commit --version

latest

**Comment by asottile** [comment]
there are many duplicates, please search for them
