### ISSUE TITLE
Question: Remove logger from whole repo?

### ISSUE THREAD

**Issue by berthin** [pre-commit/pre-commit#3134]
### search you tried in the issue tracker

yes

### describe your actual problem

Hi, I was looking at the source code, especially how logger is used, and I think it's not used at all. Like, few files have something like this:

logger = logging.getLogger('pre_commit')

but the `out.write` function prints to `sys.stdout` directly as none of the out.write calls pass the logger. Hence my question: Should logger be removed from the project? Should an option be added to like support logger in pre-commit? Or am I missing something?

Personally, I'd like to have an option to use logger since it provides many mechanisms for log collection.

Thanks!

### pre-commit --version

3.6.2

**Comment by asottile** [comment]
there's no public programmatic interface

**Comment by berthin** [comment]
Hi,

I don't quite understand your answer. If you are talking about logging, on the documentation they provide ways to interact with config files (https://docs.python.org/3/library/logging.config.html) but I understand that you don't want to support that.

What about my question of removing logging from pre-commit since it's not used at all?

Thanks!

**Comment by asottile** [comment]
what is your actual goal?

**Comment by berthin** [comment]
I was just thinking that it should be possible to write my own custom adapters for capturing and reporting logs. Like if I want to use pre-commit in my CI pipeline, I'd like to have an xml report for instance sort of embedded in pre-commit and I think that is sort of possible if logging is used.
