### ISSUE TITLE
Prefer to fail on invalid argument list

### ISSUE THREAD

**Issue by AFulgens** [pre-commit/pre-commit#3136]
### search you tried in the issue tracker

args list

### describe your actual problem

I know that this is a typical [PICNIC](https://en.wikipedia.org/wiki/User_error#PEBKAC/PEBCAK/PICNIC) problem, but I just lost a good half hour of my life to this.

In case you make the mistake not to comma-separate the args list, i.e., you write
```
- id: no-commit-to-branch
  args: [ --branch=develop --branch=main ]
```
and miss the `,` between the two, the commit hook will happily display "Passed", always. I've debugged this and the hook is not even invoked (of course, because there is a grave error when calling it), but I couldn't dig out any kind of error message for this case.

A hard fail in case any configured hook could not be invoked would be preferred, I think. Or even a new state ("Error" or similar?)

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
arguments can contain spaces and dashes so there's nothing that can be done here

**Comment by AFulgens** [comment]
I don't agree that nothing can be done. The arg-list is just an example for "the hook could not be invoked because X". In case the hook has not been executed (for whatever reason), I think it's wrong to display "Passed".

**Comment by asottile** [comment]
where do you see that the hook was invoked unsuccessfully?

the hook was executed and exited 0 according to your output (if it said Passed)

**Comment by AFulgens** [comment]
I've prepared an MWE and you are absolutely right, the script is being invoked and with the whitespaces/dashes in the argument. Rightly closed, as it was (as written at the beginning) my fault. Sorry for the extra rounds, have a nice day!

Just leaving this here for posterity.

Having a hook something like this:
```python
....
def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('filenames', nargs='*', help='Filenames to check')
    parser.add_argument('-a', '--argument', action='append', help='Argument for MWE')
    ....
```

Then the argument lists will be interpreted as follows:

When no arguments given to the hook:
```
Namespace(filenames=[...], argument=None)
```

When `args: [ -a=1 ]` given to the hook:
```
Namespace(filenames=[...], argument=['1'])
```

When `args: [ -a=1, -a=2 ]` given to the hook:
```
Namespace(filenames=[...], argument=['1', '2'])
```

When `args: [ -a=1 -a=2 ]` given to the hook:
```
Namespace(filenames=[...], argument=['1 -a=2'])
```
