### ISSUE TITLE
Add a `no-todo` hook that warns or fails if there's any TODOs in your code

### ISSUE THREAD

**Issue by b-** [pre-commit/pre-commit#3142]
### search you tried in the issue tracker

todo

### describe your actual problem

I just want pre-commit to shout at me (and optionally fail or not) if detects TODO comments in my code.

This seems like something simple that someone would have requested first, but I really couldn't find it… 

Nevertheless I might do the needed work to implement something myself, at least because a simple local-hook that fails if a TODO is present is already in this repo [buried in the tests, uncommented and undocumented.](https://github.com/pre-commit/pre-commit/blob/7b868c3508dd3a4c1f1930dc25f5433f2dac7950/tests/commands/run_test.py#L950C1-L976C1)

A fully fleshed out `no-todo` hook might have a configurable list of strings to issue warnings or failures upon encountering. For example, issuing a warning (but still returning `0`) upon detecting `TODO:`, but issuing a failure upon detecting `FIXME:`

### pre-commit --version

pre-commit 3.6.1

**Comment by asottile** [comment]
[language: pygrep](https://pre-commit.com/#pygrep) provides a nocode way to do this

**Comment by b-** [comment]
> [language: pygrep](https://pre-commit.com/#pygrep) provides a nocode way to do this

Oh, well I suppose I didn’t know what to search for then. Thanks so much for linking me so I didn’t start reinventing the wheel!
