### ISSUE TITLE
Using 'pre-commit install -c'  with an invalid path still succeeds, even though the '--allow-missing-config' flag is not provided

### ISSUE THREAD

**Issue by funkyfisch** [pre-commit/pre-commit#3144]
### search you tried in the issue tracker

is:issue allow-missing

### describe your issue

I was running `pre-commit install -c SOME_INVALID_PATH` inside git repositories.

What happened:
```bash
> pre-commit install -c SOME_INVALID_PATH
pre-commit installed at .git/hooks/pre-commit
> echo $?
0
```
What is the meaning of the --allow-missing-flag if it still behaves the same when not provided?
I expected the above to fail instead, or at least provide a warning.

### pre-commit --version

3.5.0

### .pre-commit-config.yaml

```yaml
not sure what to provide here
```

**Comment by asottile** [comment]
as [the docs indicate](https://pre-commit.com/#pre-commit-install):

> Hook scripts will permit a missing configuration file.

`--allow-missing` is for runtime *after* installation -- it permits a configuration to be missing when someone goes to run `git commit`

a missing path is allowed, and has a few valid usecases -- the biggest one being to initialize a template directory (where a configuration may not exist at all!)

**Comment by funkyfisch** [comment]
In that case it would be greatly appreciate if it was a bit better communicated that the flag is for being applied as an attribute to how the hook will run

I would expect `pre-commit install` to work obviously with templating with no issues, but if you seek to manually specify which file you want to use as your config with the `-c` option, I would expect it to at least verify the input somehow.

**Comment by asottile** [comment]
yes however your expectations are wrong given what I've said above
