### ISSUE TITLE
`prettier` hook unable to find plugins in presence of `node_modules` folder in subtree

### ISSUE THREAD

**Issue by rezib** [pre-commit/pre-commit#3148]
### search you tried in the issue tracker

node_modules, prettier, plugin

### describe your issue

A error is thrown when I run the prettier hook on my project:

```console
$ pre-commit 
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

[error] Cannot find package 'prettier-plugin-tailwindcss' imported from $CWD/noop.js
```

This git repository contains a VueJS application in `frontend/` subfolder with its own `node_modules` folder. FWIW, I noticed when I move this `node_modules` folder in Git repository topfolder or even it parent folder, the hook works:

```console
$ mv frontend/node_modules .
$ pre-commit 
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

frontend/src/components/LoadingSpinner.vue 235ms


$ mv node_modules ..
$ pre-commit 
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

frontend/src/components/LoadingSpinner.vue 235ms
```

Note that this `node_modules` tree also contains _prettier_ and the _tailwindcss_ plugin.

However, when I remove it, it breaks again:

```console
$ rm -rf ../node_modules
$ pre-commit 
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

[error] Cannot find package 'prettier-plugin-tailwindcss' imported from $CWD/noop.js
```

It seems there is some sort of conflict between `pre-commit` environment for this hook and the npm package in this subtree. I suspect this is due to the way prettier/nodejs loads plugins and resolve packages. Could `pre-commit` handle this case?

### pre-commit --version

pre-commit 3.6.2

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
  - id: prettier
    types_or: [vue, ts, javascript]
    additional_dependencies:
    - prettier@3.2.5
    - prettier-plugin-tailwindcss@0.5.12
```

**Comment by asottile** [comment]
this isn't a pre-commit problem and you didn't read the search results of your search
