### ISSUE TITLE
Add option to configure the path of where to install the hook

### ISSUE THREAD

**Issue by SimonSegerblomRex** [pre-commit/pre-commit#3151]
### search you tried in the issue tracker

init-templatedir

### describe your actual problem

Hi! Thank you for creating and maintaining `pre-commit`!

**Scenario**
In the Linux environment I work in `.git/hooks` is automatically set up as a symlink to a directory with a set of hooks that the user is not supposed to touch. All repo unique hooks should instead be installed in another directory, `.githooks.d`.

**Problem**
There's no way of configuring where `pre-commit install` installs the hook.

**Workaround**
My first thought was to configure `core.hooksPath`, but that's not supported by pre-commit (see https://github.com/pre-commit/pre-commit/issues/1198).

Instead I came up with this workaround using `pre-commit init-templatedir`:
```shell
HOOKS_DIR=$(git rev-parse --show-toplevel)/.githooks.d
TMP_DIR=/tmp
# git config --local init.templateDir $TMP_DIR  # optional: to get rid of warnings from pre-commit
pre-commit init-templatedir $TMP_DIR >/dev/null
# git config --unset init.templateDir
mv $TMP_DIR/hooks/pre-commit $HOOKS_DIR/pre-commit.50
```

**Proposed solution**
Add an option to specify the installation path of the hook:
```shell
pre-commit install --output-path=.githooks.d/pre-commit.50
```

I realize that you will probably find this use-case odd, and it's ok if you want to label this issue as a question just discussing improvements to the workaround solution.

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
seems like you already have a solution that works without me needing to maintain something I don't agree with

**Comment by SimonSegerblomRex** [comment]
> seems like you already have a solution that works without me needing to maintain something I don't agree with

Sure, I appreciate your standpoint! I just hope that the workaround won't break with some future update to `pre-commit` (but of course I understand that we are using `pre-commit init-templatedir` in an unsupported way without any guarantees).

I know that this use-case is far from unique, so hopefully more users will find the workaround helpful.

**Comment by asottile** [comment]
I mean you're already doing a not-recommended thing in unsupported territory so there's no guarantees on whether it will continue to work or not

**Comment by SimonSegerblomRex** [comment]
I just realized that there is a much simpler solution to my problem.

The only thing I need to do is to create a custom version controlled pre-commit hook that calls `pre-commit run`:
```sh
#!/bin/sh
command -v pre-commit >/dev/null 2>&1 || { echo >&2 "\n'pre-commit' was not found, please install 'pre-commit' using pip.\n"; exit 2; }
pre-commit run
```

There's simply no need to bother with the hook created by `pre-commit install` or `pre-commit init-templatedir` in this situation. Sorry for not realizing this earlier.

**Comment by asottile** [comment]
there's quite a few downsides to that but I'm sure you understand then and are willing to accept those
