### ISSUE TITLE
Download raw .pre-commit-hooks.yaml file instead of whole repository

### ISSUE THREAD

**Issue by almahdi404** [pre-commit/pre-commit#3153]
### search you tried in the issue tracker

raw .pre-commit-hooks.yaml

### describe your actual problem

I am not sure if the `.pre-commit-hooks.yaml` file is what pre-commit only requires.

But if so, then why doesn't pre-commit just download the raw `.pre-commit-hooks.yaml` file like this,

https://raw.githubusercontent.com/psf/black/24.3.0/.pre-commit-hooks.yaml

So, we won't need a mirror repository.

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
that's a github-specific and rate limited extension
