### ISSUE TITLE
The exclude option should support lists as well as strings

### ISSUE THREAD

**Issue by sffortytwo** [pre-commit/pre-commit#3154]
### search you tried in the issue tracker

exclude

### describe your actual problem

I wanted to exclude two specific files from the yaml check. Instead of being able to list them, I had to write a regex of the two files. As I add more files, this expression is going to get longer and I have no way of breaking it up. I think both strings and arrays should be supported.

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
you clearly didn't search very well.  there are several duplicates and if you read the docs they also show you how to nicely split this up
