### ISSUE TITLE
Allow to pass files args through file to avoid MAX_ARGS size limit

### ISSUE THREAD

**Issue by iwanb** [pre-commit/pre-commit#3157]
### search you tried in the issue tracker

pass files through args, MAX_ARGS, args limit

### describe your actual problem

On a big repository, a hook might need to execute multiple times because the arguments passed to the hook exceed the system limit on the size of arguments that can be passed to the command.
As implemented here: https://github.com/pre-commit/pre-commit/blob/3bdf9fb91bd661c667131dd3f73581a4ce9368c3/pre_commit/xargs.py#L76

pre-commit could allow to pass the list of files to test via a temporary file to bypass this limit. E.g. a NULL-delimited list of paths, or newline delimited.

It is a problem mainly for hooks which have [require_serial](https://pre-commit.com/#hooks-require_serial) set, as otherwise the hook will anyway be executed multiple times but in parallel.

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
a hook which needs every file is poorly designed and not a good fit for the framework.  extra hacks will not be built and maintained to support things like this.  if you searched the issue tracker you would have found several duplicates including one for the same proposal as here.  please search harder next time
