### ISSUE TITLE
documentation request / guidance needed: how to add pre-commit to the build in an existing large codebase

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#3160]
### search you tried in the issue tracker

incremental, partial, only files changed

### describe your actual problem

So let's say we're adding pre-commit a large existing codebase.

We can't add pre-commit run --all-files to make test because we have a lot of code that would fail, and we can't fix it all up immediately - we need to incrementally migrate the code to satisfy linters etc.

We could just not run pre-commit in make test / ci, and rely on the default behaviour of pre-commit to only run on files that you actually committed, but there's no guarantee that developers are actually installing a venv (or what if someone edits a file from the github ui).

It would be nice to somehow get the best of both worlds. An off the top of my head solution looks something like this:

```make
test: venv
    ./venv/bin/pre-commit run --files $(git diff origin/main --name-only)
```

but idk if that's sketchy or not. (one obvious thing is that the code in origin's main could change at any point, so that introduces some flakeyness, but it's rare that the build is totally isolated from the outside world anyway soooo seems like an ok tradeoff to me)

ty!

### pre-commit --version

n/a

**Comment by asottile** [comment]
https://github.com/readme/guides/code-review
