### ISSUE TITLE
Unable to commit if repo with hooks is unavailable

### ISSUE THREAD

**Issue by mcheremisinov** [pre-commit/pre-commit#3161]
### search you tried in the issue tracker

"unable to commit", "repo unavailable "

### describe your actual problem

I've cloned pre-commit repo into my privately hosted server and installed hooks using URL to that server.

Suppose the server is unavailable for a particular reason and pre-commit hooks are used in a local repository. In that case, I can't do any commits locally, because pre-commit hangs in some internal response await from that server.

It would be nice to have the ability to make a commit if the remote server is unavailable.
For example, use some command-line flag a.k.a `git commit --ignore-pre-commit` to disable pre-commit for particular commits (which may be ideologically incorrect).
Or pre-commit should report an error after some timeout and do a commit anyway without running any hooks.

### pre-commit --version

pre-commit 3.6.0

**Comment by rkm** [comment]
Does `git commit --no-verify` not allow this already? https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify

**Comment by rkm** [comment]
Individual hooks can also be skipped. This is clear from reading the documentation: https://pre-commit.com/index.html#temporarily-disabling-hooks

**Comment by mcheremisinov** [comment]
Yeah, this works, thx.
