### ISSUE TITLE
File selection criteria based on contents?

### ISSUE THREAD

**Issue by mxr** [pre-commit/pre-commit#3164]
### search you tried in the issue tracker

file selection, exclude

### describe your actual problem

I want to use a formatter which is known to fail on certain language constructs, so I want to exclude those files from the hook. I know I can select the files that a hook runs on using `files` or `types`. But that alone doesn't tell me if a file has the offending language construct.

Would it be reasonable to add a way to select files based on a regex applied to the file contents? I realize regex processing on code is error-prone but it would probably be good enough in this case.

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
I don't think this would work, it would either be broken if regex based or pre-commit would have to understand every language and feature (including ones which don't exist) which would be intractable

it's fairly easy to generate the `exclude` manually so I see no reason to complicate the framework to support this as a feature

**Comment by mxr** [comment]
OK. For my usecase, do you think I could have a hook which generates the exclusion list and then updates `.pre-commit-config.yaml` directly?

**Comment by asottile** [comment]
yeah probably!
