### ISSUE TITLE
Expose diff-filter options to pre-commit api

### ISSUE THREAD

**Issue by harmstyler** [pre-commit/pre-commit#3165]
### search you tried in the issue tracker

pre-commit diff-filter options

### describe your actual problem

It would be great to selectively run hooks against files that are checked against the type of commit being made. Ideally, I want to treat files that are new differently than files that are modified, so running a different hook on each is the ideal outcome.

Alternatively, if I were to write a custom hook, having these options exposed in the custom hook would suffice so as to not clutter the primary config options.

### pre-commit --version

pre-commit 3.6.2

**Comment by asottile** [comment]
this isn't a common enough use case to warrant an option and has been rejected before.  it's easy enough to query this information yourself such as what `check-added-large-files` does

**Comment by harmstyler** [comment]
I didn't realize check-added-large-files does that. I'll look into that. Thanks!
