### ISSUE TITLE
How should this project be named to distinguish it from the identically-named Git hook?

### ISSUE THREAD

**Issue by arcanemachine** [pre-commit/pre-commit#3178]
### search you tried in the issue tracker

confusing name

### describe your actual problem

I am aware of the incident a few years back where some person was spamming the issue tracker over and over again. I have no intent to harass you the same way, I am just looking for an answer to the question in the title.

The other person suggested the name "pre-commit.com" which isn't very good IMO.

If you have any suggestions, I would be glad to hear them. Communication is very important, but it makes it harder to advocate the use of this project.

In case this thread is just going to be closed without remark, I'm going to offer `pre-commit.py` for the historical record, because I need a name for the project that disambiguates it from the Git hook.

Thank you for the wonderful tool, by the way. Again, I have no intention of coming in here just to bother you.

### pre-commit --version

3.7.0

**Comment by asottile** [comment]
you found the duplicate though? and the answer?

**Comment by arcanemachine** [comment]
I found several duplicates (#1765, #1766, #2155) and _an_ answer, although I wouldn't call it a very good one. I'm going with `pre-commit.py` since it explains what the project is and how it distinguishes the project from the Git hook.

I understand that there is no desire on the part of the developers to address the issue, but am genuinely perplexed at the refusal to acknowledge the naming issue.

But yes, you can consider the issue closed, if you like.

**Comment by asottile** [comment]
the original thing you found (pre-commit.com) is what we recommend and what we use for SO posts

**Comment by asottile** [comment]
python is an implementation detail that is unlikely to last

**Comment by arcanemachine** [comment]
Oh, my mistake. I thought that "pre-commit.com" was just the suggestion by the person who was spamming the issue tracker. I did not realize that name was officially recognized as an alternative.

Well, you can definitely consider the issue closed then. Sorry.
