### ISSUE TITLE
Show additional information when a hook fails

### ISSUE THREAD

**Issue by helly25** [pre-commit/pre-commit#3189]
### search you tried in the issue tracker

manual

### describe your actual problem

When developers run the pre-commit, they don't always understand what to or where to find more information. The hook description field is already present and often used to provide more descriptive information. For brevity this is not shown in normal cases, but this PR changes the tool behavior to show the description in verbose mode (`-v`). So most users won't see any difference but this can easily be enabled for people who want it.

Alternatives considered:
* Always show the description: Some people may not like this though as it can be spammy.
* Provide a new field: Possible but seems to be just more work with description already present and not otherwise used.
* Show the `repo` link. This is at the wrong level and has a slightly different purpose. Though description can just be set to the same url where that is correct.

### pre-commit --version

pre-commit 3.7.0

**Comment by asottile** [comment]
no thanks -- I'd rather keep it the way it is
