### ISSUE TITLE
Github token not propagated

### ISSUE THREAD

**Issue by adminy** [pre-commit/pre-commit#3196]
### search you tried in the issue tracker

2532

### describe your issue

I tried cloning a repo that is private with:

repo: https://oath2:${token}@github.com/owner/repo

and that does not work, similar to #2532
fails a step below cloning.

also doing a `git clone https://oath2:${token}@github.com/owner/repo` works!

### pre-commit --version

pre-commit 3.7.0

### .pre-commit-config.yaml

```yaml
repos: private ones
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A

**Comment by asottile** [comment]
pre-commit is not a shell nor does the configuration support any substitutions (intentionally)

your "comparison" is wrong -- the equivalent is: `git clone 'https://oath2:${token}@github.com/owner/repo'` which you'll find fails in the same way

**Comment by adminy** [comment]
okay, so is pre-commit just not interested in supporting private/authenticated repos? is there nobody that can take a look at this? Its not on the roadmap? Would you accept a PR with support?

Because locally it works with github ssh keys but inside github actions you don't have ssh keys, you have tokens, and they are the only form that you can safely have.

**Comment by asottile** [comment]
no, you've just not read the docs nor searched for duplicates

nor are you paying for enterprise support

**Comment by asottile** [comment]
why aren't you interested in ssh?

actually, I don't think I want to help you given your attitude.
