### ISSUE TITLE
Warn when archived

### ISSUE THREAD

**Issue by adam-moss** [pre-commit/pre-commit#3211]
### search you tried in the issue tracker

archive; warning; autoupdate

### describe your actual problem

It would be useful if `pre-commit` exposed a configuration option to warn (default) or fail (opt-in) in certain scenarios.

E.g. if running `pre-commit autoupdate`:

```console
pre-commit autoupdate --repo https://github.com/pre-commit/mirrors-prettier
[https://github.com/pre-commit/mirrors-prettier] already up to date!
```

However the source repo has been archived so will likely never see another update.

Having this visibility as part of the `autoupdate` workflow will allow for more timely discovery of potential issues with hooks being consumed.

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
archived is a feature of github of which there's no information exported via git

this is basically the same as the renamed repo feature request that's been asked about before, you can search the tracker to find the conclusion about that as well

**Comment by adam-moss** [comment]
Would you consider this a viable meta hook?  Hitting the relevant github/lab/tea api's to get archived status is pretty straight forward.

**Comment by asottile** [comment]
no it is not.  you need credentials at worst and that is not happening here
