### ISSUE TITLE
Restrict a hook to run exclusively in prepare-commit-msg

### ISSUE THREAD

**Issue by chain710** [pre-commit/pre-commit#3212]
### search you tried in the issue tracker

run a hook only in prepare-commit-msg

### describe your issue

I'd like to create a hook that runs exclusively in prepare-commit-msg, without requiring the user to specify the hook type during installation.

Is the only way to do this through `pre-commit install -t prepare-commit-msg`?

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
- repo: xxx
  hooks:
  - id: xx
```

**Comment by asottile** [comment]
what have you tried? what isn't working? you haven't even shown your configuration

**Comment by asottile** [comment]
nothing is implicit since you are opting into code execution.  you must install the stages specifically

**Comment by asottile** [comment]
nah you're confused -- it just won't run at all if they haven't installed the specific hook and you've properly set `stages`
