### ISSUE TITLE
A way for defining Top level config variables to reuse

### ISSUE THREAD

**Issue by Architrixs** [pre-commit/pre-commit#3214]
### search you tried in the issue tracker

varaibles in config

### describe your actual problem

I want to define a varaible at top level in my` pre-commit-config.yaml`, so it could be used in multiple hooks.
Per my current use case I am creating config where I need to define a different working directory than my root for some hooks.

I need something similar 
```
   set VARIABLE: some_value
   set ANOTHER_VARIABLE: another_value
   
    ...
    repo: https://github.com/pre-commit/mirrors-eslint
    hooks:
        ...
        working_dir: {{VARIABLE}}
```

This way variable could be reused in same file, as well i can make a config template which can be used in different projects.

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
this has been rejected several times already
