### ISSUE TITLE
Python language: add option to use uv instead of pip for venv creation & dependency installs

### ISSUE THREAD

**Issue by rsyring** [pre-commit/pre-commit#3222]
### search you tried in the issue tracker

"uv" "uv pip" "pip" "astral"

### describe your actual problem

I've been using [uv](https://github.com/astral-sh/uv) instead of pip and virtualenv and the speed difference is staggering.

Can pre-commit add support for using `uv venv` and `uv pip` when using the python language?  So far in my usage they have been drop in replacements.  I'm not sure the best way to suggest enabling UV.  IMO, a global setting at the pre-commit level, environment variable, etc. would be better than having to remember to specify it every time in a python language hook.  

As an example, Tox gives the ability to set the install command with:

`install_command = uv pip install {opts} {packages}`

### pre-commit --version

pre-commit 3.7.0

**Comment by asottile** [comment]
make sure even you search for duplicates to also search closed issues so you don't waste both of our time
