### ISSUE TITLE
Allow passing the filenames absolute paths, to support chdir in command

### ISSUE THREAD

**Issue by noamraph** [pre-commit/pre-commit#3228]
### search you tried in the issue tracker

absolute path, abspath

### describe your actual problem

I want to run a check command that requires the working directory to be in a subdirectory.

It is currently quite hard, since filenames are passed as paths relative to the base directory. I found https://github.com/pre-commit/pre-commit/issues/1110#issuecomment-525953824, which suggests writing a script just for fixing the paths.

How about passing absolute paths to the command? Since changing the behavior for all commands can cause some backwards-incompatibility, perhaps add an option, say `abspath: true`, which will cause pre-commit to pass absolute paths instead of relative paths?

BTW, my current solution is this:

```bash
bash -c 'rpaths=(); for arg in "$@"; do rpaths+=($(realpath $arg)); done; cd subpath && cargo fmt -- ${rpaths[@]}' dummyarg
```

which is better IMHO than creating a new script, but is still pretty involved and error-prone.

### pre-commit --version

pre-commit 2.21.0

**Comment by asottile** [comment]
you found the duplicate and still decided to make an issue
