### ISSUE TITLE
[Question] enforce script to run once (and only once) for each commit

### ISSUE THREAD

**Issue by laurentsigal** [pre-commit/pre-commit#323]
I was going through the documentation but I could not find a way to use a pre-commit hook in the "normal way" i.e. have the script run once on every commit (instead of being triggered once for each modified file corresponding to the pattern).

Is there an option that I can pass to the .yaml config to fulfill that purpose?

Thanks a lot guys, and awesome framework!

**Comment by asottile** [comment]
Unless there's a large number of files being touched, the individual hook executables will usually only be called either 0 or 1 times (receiving the filenames as positional arguments) -- it uses xargs so if there's a ton of filenames it'll end up calling your executable multiple times.  This is documented here: http://pre-commit.com/#passing-arguments-to-hooks

As for enforcing a hook that always runs exactly once, you could probably use the "migration mode" approach documented here: http://pre-commit.com/#running-in-migration-mode .  In migration mode, pre-commit will run whatever existing script was sitting at .git/hooks/pre-commit when `pre-commit install` was executed *before* running all the other hooks.

The migration mode is a bit clunky (doesn't have nice printing, doesn't do the stash behaviour, doesn't honor merge conflicts, etc.) so when we've reached for something similar to what you're asking, we've instead written hooks that simply ignore the passed arguments and are less concerned about them running more than once (or better, make them idempotent!).  For this we've essentially made the argparser ignore positional arguments when executing.

**Comment by laurentsigal** [comment]
Anthony, thanks a lot for the quick answer!

I have looked into that migration mode, but the problem is that then the script is no longer centralized (which is the huge value of pre-commit in the first place).

Here is my use case:
I generate files on each commit (out of all the files in a specific folder in my repo). This build is global which means it only needs to run once. Running it several times is fine though, it's just extra work but not the real problem.
The real issue actually is that it needs to run on deletion of files as well, but they currently do not trigger the script, because of this line https://github.com/pre-commit/pre-commit/blob/master/pre_commit/git.py#L92

For my case, it would be super neat if either:
- deletion of files would still trigger the script (which does not make sense in the normal use of pre-commit where you validate the integrity of a file)
OR
- we could specify a config into yaml to run the script everytime there is a commit, no matter what files are changed

But again, I'd love to still run the script within the pre-commit framework, because it is awesome to centralize and maintain scripts out of one github repo!

Let me know if you think there is a workaround for this.

**Comment by asottile** [comment]
Can't think of any other workarounds at the moment.  Though I think the second option sounds good and is doable.

Something like an `always_run: true` setting that'd run the hook regardless of the filename list, might be a bit of work to get pre_commit/commands/run.py to handle that but I think it's definitely doable.

Want to start a feature branch?

**Comment by laurentsigal** [comment]
Yes I have looked at the code and I think it is very doable

**Comment by laurentsigal** [comment]
How does the push process works? Github does not let me create a new branch onto your repo..

**Comment by asottile** [comment]
You'll fork to your own repo and then create a pull request from there.

Click the fork button in the top right and then you can push to that by doing:

```
git remote add mine git@github.com:laurentsigal/pre-commit  # If you're using ssh, otherwise https://github.com/laurentsigal/pre-commit
git fetch mine
git push mine HEAD
```

**Comment by laurentsigal** [comment]
https://github.com/pre-commit/pre-commit/pull/324

**Comment by laurentsigal** [comment]
That ends up being  a really tiny change :smile:

**Comment by laurentsigal** [comment]
covered by #324
