### ISSUE TITLE
disable loading Gemfiles in the enclosing project in ruby applications

### ISSUE THREAD

**Issue by Roguelazer** [pre-commit/pre-commit#3231]
### search you tried in the issue tracker

is:issue bundler

### describe your actual problem

I want to use `rubocop` with pre-commit. Internally, rubocop's extension mechanism first uses `Bundler.load` to try to load extensions from the current project (this recurses up through the parent directories of the `cwd` to find the first file named `Gemfile` and then eagerly loads everything in it); this isn't really desirable when it's running through pre-commit, because the rbenv used by pre-commit doesn't have all of the local dependencies installed, so it ends up failing pretty miserably. We pass any extensions as `additional_dependencies` in the `pre-commit-config.yml`; these are also discovered by rubocop through another mechanism.

This isn't a rubocop-specific issue; any Ruby program which calls `Bundle.load` at some point will end up trying to eagerly install all of the dependencies in the current project.

I think in an ideal world, when installing ruby dependencies into an rbenv, pre-commit would create a new `Gemfile` and actually install them with bundler rather than by running `gem install`, but that seems like a larger project.

A change that does work is to simply make an //empty// Gemfile in the rbenv root and point `BUNDLER_GEMFILE` to that. I'll send over a PR which does so.

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
are you on the latest rubocop? I had the same problem and they considered it a bug and fixed it

**Comment by Roguelazer** [comment]
Yes, this is on 1.64.1. It looks like https://github.com/rubocop/rubocop/commit/094239599b582c1303eb264246b5c3f911b0abef changed it so that if there's no Gemfile at all, it won't die, but if there is a Gemfile it still loads it.

**Comment by asottile** [comment]
I'd recommend trying that route first, I don't think pre-commit should mess with bundler like you're recommending

**Comment by Roguelazer** [comment]
> I'd recommend trying that route first, I don't think pre-commit should mess with bundler like you're recommending

Just to clarify: your position is that it should be user error for any pre-commit plugin to ever call `Bundler.load`?

**Comment by asottile** [comment]
not user error -- a linter blindly trying to access an unrelated environment is a poorly behaving linter.  rubocop has fixed this behaviour before thrice at least
