### ISSUE TITLE
[Question]: How to maintain previous workflow? (`global hooks`)

### ISSUE THREAD

**Issue by bukowa** [pre-commit/pre-commit#3236]
### search you tried in the issue tracker

in:title global hooks

### describe your actual problem

Hey I just tried installing `pre-commit` in my repository.
````shell
$ pre-commit install
[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
hint: `git config --unset-all core.hooksPath`
````

This is my only hook I always remember using:
````shell
#!/bin/sh

NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
````

How do I use `pre-commit` without breaking my previous workflow?

### pre-commit --version

3.7.1

**Comment by asottile** [comment]
well the first two checks do nothing since git also enforces that and the later you can do with gitconfig

**Comment by bukowa** [comment]
Use git commit templates or or `git commit --sign-off`
