### ISSUE TITLE
Apply patches to hooks before execution

### ISSUE THREAD

**Issue by hofbi** [pre-commit/pre-commit#3239]
### search you tried in the issue tracker

"apply patch", "patch hooks", "patch"

### describe your actual problem

Assume you are using a hook which has a bug/missing feature. You implement the fix and even create a PR for the upstream repository. Now you have to wait until the PR is accepted (and even for a new release if you want to rely on pre-commit autoupdate). However, you want to use you fix immediately. To do so, I see 2 options:

1. Change you pre-commit config to your fork that already contains this feature (this can be done already as is)
2. Apply your fix as a patch to the actual hook repo before pre-commit executes the hook (this is why I am creating this issue)

While option 1 is always possible, the patch approach is quite common in [bazel](https://bazel.build/rules/lib/repo/http#http_archive-patches), [conan](https://docs.conan.io/2/examples/tools/files/patches/patch_sources.html), or many other tools used for consuming remote dependencies if you cannot open source your changes.

What do you think about adding a `patch` or `patches` key to the [hooks](https://pre-commit.com/#pre-commit-configyaml---hooks) where you can specify a patch file or list of patch files that are applied to the hook before it gets executed?

### pre-commit --version

3.5.0 and 3.7.1

**Comment by asottile** [comment]
absolutely not. the system is specifically designed to support option 1
