### ISSUE TITLE
Support prec-ommit for unmake

### ISSUE THREAD

**Issue by ccoVeille** [pre-commit/pre-commit#3241]
### search you tried in the issue tracker

unmake

### describe your actual problem

[Unmake](https://github.com/mcandre/unmake) is a linter that helped me a lot to validate `Makefile` files

I like the tool, I opened an [issue](https://github.com/mcandre/unmake/issues/242), then a [PR](https://github.com/mcandre/unmake/pull/244) on the repository.

The owner refused to consider adding pre-commit support...

So I created https://github.com/ccoVeille/pre-commit-unmake to provide it

I'm opening this issue here to see if you are likely to accept it such linter.

Before I'm doing the work to import the file and add a decent README :smile: 

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
pre-commit is just a framework -- it doesn't implement lint checks

**Comment by ccoVeille** [comment]
Of course, it doesn't.

I didn't look at the hooks page for while. And the page was totally different.

I think this message explain it well.

>  adding to this page ¶
> the previous iteration of this page was a laundry list of hooks and maintaining quality of the listed tools was cumbersome.

> this page is not intended to be exhaustive

So indeed, my small idea won't fit the new rules https://pre-commit.com/hooks.html#adding-to-this-page

I'm sorry if I didn't look at contribution instructions.

My bad, so I will create the project anyway as it's a norm to be independent and not listed in a maintained list
