### ISSUE TITLE
html checker which plays nice with Jinja2

### ISSUE THREAD

**Issue by bernardpaulus** [pre-commit/pre-commit#3249]
### search you tried in the issue tracker

is:issue html

### describe your actual problem

I'm looking for an HTML validator which plays nice with Jinja2 templates. I had [prettier](https://github.com/pre-commit/mirrors-prettier
) in my project but it doesn't play nice with templates, transforming stuff like:

```jinja
{% extends "base.html" %}

{% block content %}
<h1 class="title">{{ page.title }}</h1>
{% endblock content %}
```

in 
```jinja
{% extends "base.html" %} {% block content %}
<h1 class="title">{{ page.title }}</h1>
{% endblock content %}
```

I tried [adding a basic one myself](https://github.com/pre-commit/pre-commit-hooks/pull/1072), but it was closed, mentioning [w3c](https://validator.w3.org/). Using the w3c tool [v.Nu](https://validator.github.io/validator/) is not working for me because it assumes entire html documents.

Looking deeper I could find [html-validate](https://html-validate.org/) which, tested manually, works well for my purpose.

Before moving forward and making a [node hook](https://pre-commit.com/#node) for html-validate, I'd like to take a step back and get your feedback about this approach.

What do you think about this approach?

---

*edit*: I realize that I was mixing [formatters and linters](https://prettier.io/docs/en/comparison) (e.g. prettier vs v.Nu). I'm looking for a linter. 

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
that would probably work, if html-validate exposes a cli you may be able to use it directly via `additional_dependencies` (at least to try it) 

your other hook could probably work too, just it wouldn't be the best for for pre-commit/pre-commiy-hooks (but that's an important part of pre-commit's design: you can plug in whatever repo or fork you want!) -- so even that approach would work if you built your own hook repository

**Comment by bernardpaulus** [comment]
hello  @asottile ,
It took a while due to a misconfiguration of html-validate on my side, but it works :smiley:

I made a [mirror for html-validate](https://github.com/bernardpaulus/pre-commit-mirror-html-validate) thanks to [pre-commit-mirror-maker](https://github.com/pre-commit/pre-commit-mirror-maker/).

Thank you for your quality work!

**Comment by asottile** [comment]
check out the github actions in the ones in github.com/pre-commit -- I need to poke them once in a while but they mostly just work
