### ISSUE TITLE
syntax error near unexpected token `(' when runnin git commit -m

### ISSUE THREAD

**Issue by hallya** [pre-commit/pre-commit#3267]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/1483

### describe your issue

- I was trying to commit 
- I ran `git commit -m "..."`
- I expected to commit successfully
- I got this error I don't understand. 

I have upgraded the version of node through nvm I use to v20.14.0, but then I revert to v18
I use now v20.16.0.

I don't know if this could be related.

When I run `gcmsg 'chore: ugrade nvm version'` (`gcmsg='git commit -m'`), I get
```
.git/hooks/_detect_package_hooks.cjs: line 2: syntax error near unexpected token `('
.git/hooks/_detect_package_hooks.cjs: line 2: `const fs = require('fs');'
```

which correspond to `const fs = require('fs');`

2 more think to know:
- I already commit once
- `--no-verify` does not work either

### pre-commit --version

no pre-commit package installed in dependencies

### .pre-commit-config.yaml

```yaml
/
```

**Comment by asottile** [comment]
that file is not us
