### ISSUE TITLE
Customizing 'pre-commit not found' message

### ISSUE THREAD

**Issue by ArtemSokolov** [pre-commit/pre-commit#3271]
### search you tried in the issue tracker

virtualenv

### describe your actual problem

Dear developers,

Thanks very much for this amazing tool. I was wondering if it's possible to customize the "pre-commit not found" message, which is currently automatically generated by `pre-commit install` as:
``` bash
echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
```

I looked through the docs but didn't see a configuration setting for it. Apologies if I'm missing something obvious.

### pre-commit --version

3.8.0

**Comment by asottile** [comment]
it is not, no

you're free to fork though
