### ISSUE TITLE
pre-commit importing python code from the current directory

### ISSUE THREAD

**Issue by bplaxco** [pre-commit/pre-commit#3273]
### search you tried in the issue tracker

sys.path current directory import

### describe your issue

I noticed pre-commit importing code from the current directory during runs. Could cause issues if the repo collides with libs used in pre-commit or be used to exec malicious code (probably not likely but still possible).

To reproduce:

```sh
cd "$(mktemp -d)"
mkdir -p logging
echo 'print("Evil Code")' > logging/__init__.py
git init
pre-commit install -f
touch .pre-commit-config.yaml
git add -A
git commit -m "Will explode"
```

Output:

```
Initialized empty Git repository in /tmp/tmp.5K3OIfpWae/.git/
pre-commit installed at .git/hooks/pre-commit
Evil Code
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  ...snip...
    LOGGER = logging.getLogger("concurrent.futures")
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger'
```

Note "Evil Code" showing up in the output when commit is ran.

This is how pip gets around the same issue:

```python
import os
import sys

# Remove '' and current working directory from the first entry
# of sys.path, if present to avoid using current directory
# in pip commands check, freeze, install, list and show,
# when invoked as python -m pip <command>
if sys.path[0] in ("", os.getcwd()):
    sys.path.pop(0)
```

I have a tool that wraps pre-commit and the above change seems to solve it for me as well. 

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
Empty in the example above. Doesn't really matter what's in here since it's an error during the inital import.
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Not present.

**Comment by asottile** [comment]
you'd have to attack your own system for it to be "relevant".  this is just how `python -m` works

**Comment by bplaxco** [comment]
Understandable from the attack perspective. I agree it's a pretty low chance. 

I did see at least one person run into a problem where they had a package name in their python project conflict and it caused pre-commit to raise an exception, but there are workarounds.

Anywho, just wanted to let you know about the behavior :+1: 

> this is just how python -m works

An aside, if you add the `-P` flag for more recent versions of Python, it also resolves the issue. So `python -Pm` would work, but sadly 3.9 doesn't support that from what I've seen :upside_down_face:

**Comment by asottile** [comment]
yeah we'll drop 3.9 (or python) soon enough and then it won't be an issue
