### ISSUE TITLE
`run --all-files` ignores files from `git commit --no-verify` 

### ISSUE THREAD

**Issue by filipre** [pre-commit/pre-commit#3280]
### search you tried in the issue tracker

is:issue is:open no-verify all-files 

### describe your issue

Hi,

I noticed that once you add a file using `git commit --no-verify`, any change to the file will be ignored by `pre-commit run --all-files` and makes checks pass. I find this a bit unexpected because we run this command in our CI pipeline and we would like to detect problematic files even if they were added by a `no-verify` commit before. I found https://github.com/pre-commit/pre-commit/issues/179 but it seems like there the issue did not exist.

I created a repository that reproduced this behavior: https://github.com/filipre/pre-commit-no-verify The readme describes the steps to reproduce the issue. In short:

```
$ pre-commit install

# 20kb has not been staged yet
$ pre-commit run --all-files
check for added large files..............................................Passed

# 20kb has been staged
$ pre-commit run --all-files
check for added large files..............................................Failed

# Commit using --no-verify
$ git commit -m "Add 20kb file" --no-verify

# --all-files ignores 20kb.txt now
$ pre-commit run --all-files
check for added large files..............................................Passed

# Change 20kb.txt and commit
$ git add 20kb.txt
$ git commit -m "Change 20kb file"
check for added large files..............................................Passed
$ pre-commit run --all-files
check for added large files..............................................Passed
```

I am on `3.3.3` but the issue still exists after upgrading to `3.8.0`

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10']
```

### ~/.cache/pre-commit/pre-commit.log (if present)

No such file or directory

**Comment by asottile** [comment]
your assumption about how it works isn't correct.  check added large files does just what it says: checks "added" files.  once it has been committed then it is no longer added 

there are options to make it work differently if you read the docs for that hook
