### ISSUE TITLE
Execute hook when another hook failed

### ISSUE THREAD

**Issue by mdeweerd** [pre-commit/pre-commit#3282]
### search you tried in the issue tracker

is:issue execute hook failed 

### describe your actual problem

I would like to have a hook run if another hook failed and avoid having pre-commit run 3 times in total (rather than 2).

# uncrustify needs a second run after modifcations

After formatting code a first time it regularly occurs that running it again applies new style changes (alignment of comments for instance).
Running a second time uncrustify in another hook when the first run fails cleans up the code in a single run.

# insert-license needs a second run.

insert-license needs (or needed/not checked) two runs to update the licence because it updates(-ed?) only one year at a time.
So as a workaround I have insert-license and insert-license2.

There are other cases where I could use it, for instance:
- Run php-cs to verify that the code is ok and if that fails, run php-cbf to apply the style formats.  Otherwise, skip php-cbf.

### pre-commit --version

pre-commit 3.8.0

**Comment by asottile** [comment]
sounds like problems with specific tools that you should take up with them
