### ISSUE TITLE
Enable pass through of exit code

### ISSUE THREAD

**Issue by liiight** [pre-commit/pre-commit#3287]
### search you tried in the issue tracker

exit,codes,pass

### describe your actual problem

I want to enable passing the original exit code of the hook in case of failure.
There are instances (like in my case, [Gitlab CI](https://docs.gitlab.com/ee/ci/yaml/#retryexit_codes)) that a retry can be set to a specific exit code. 
According to the docs, pre-commit has its own exit codes:

> new in 2.8.0: pre-commit now exits with more specific codes:
> 
> 1: a detected / expected error
> 3: an unexpected error
> 130: the process was interrupted by ^C

It would be very beneficial to be able to pass the original exit code on occasion.
Thanks in advance 🙏

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
think about why this wouldn't be possible

what if there are many different exit codes?

**Comment by liiight** [comment]
I think this could be handled as well in an expected manner.
Let's say that the exit status is a per-hook configuration.
You can use the exit code of a hook that set to that, if there's exactly one hook that failed AND configured to pass the exit code.
If more than 1 hook fail, you can have a specific exit code for that as well.

Another idea I had is having this be a CLI option when running a specific hook.
Something like
```
pre-commit run hookname --all-files --exit-code
```
Then i can split the pre-commit invocation to more than 1 instance, skipping the hook I want in the other instance:
```
SKIP=hookname pre-commit run --all-files
```
I agree it's a bit murky and I totally understand if you consider this out of scope.
Thank you very much for this amazing tool and the time you put into it 🙏

**Comment by asottile** [comment]
that's an absolute ton of complexity and edge cases for dubious (imo) value

you can still implement what you want by having a script touch a file to indicate a retry but this won't be implemented in the framework

**Comment by liiight** [comment]
Fair enough.

Thank you for your response!
