### ISSUE TITLE
Accepting standard git merge commit messages as valid commit message.

### ISSUE THREAD

**Issue by lstanc** [pre-commit/pre-commit#3289]
### search you tried in the issue tracker

git merge, main, standard, merge message

### describe your actual problem

Hi,

I don't know how to treat this request as a bug or as a feature, but maybe it would be nice to have such functionality that standard git merge commit messages are accepted by pre commit as they are. By that I mean that they don't need to have "feat: " or the other prefixes. I think that would be good to add them as an exception to the validation rule.
commit message "Merge branch 'main' into feature/name-of-a-feature-branch".

### pre-commit --version

pre-commit 3.8.0

**Comment by asottile** [comment]
I have no idea what you're talking about.  pre-commit does not implement any validation
