### ISSUE TITLE
Add debug output to GitHub issues

### ISSUE THREAD

**Issue by adamtheturtle** [pre-commit/pre-commit#3290]
### search you tried in the issue tracker

action

### describe your actual problem

I am using the GitHub Action as so:

```yaml
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
```

on one PR, the action errors with:

```
Traceback (most recent call last):
15
  File "/home/runner/work/_actions/pre-commit-ci/lite-action/v1.0.2/bin/main", line 298, in <module>
16
    raise SystemExit(main())
17
                     ^^^^^^
18
  File "/home/runner/work/_actions/pre-commit-ci/lite-action/v1.0.2/bin/main", line 270, in main
19
    commit = _make_commit(src_repo=args.src_repo, head=head, clone=clone)
20
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21
  File "/home/runner/work/_actions/pre-commit-ci/lite-action/v1.0.2/bin/main", line 57, in _make_commit
22
    subprocess.check_call(
23
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/subprocess.py", line 413, in check_call
24
    raise CalledProcessError(retcode, cmd)
25
subprocess.CalledProcessError: Command '('git', '-c', 'user.name=does-not-matter', '-c', 'user.email=does-not-matter@example.com', '-c', 'protocol.version=2', '-C', '.', 'commit', '--all', '--quiet', '--no-edit', '--no-verify', '--message=hi')' returned non-zero exit status 1.
```

I do not understand why. My guess is that the `CalledProcessError` includes some data which could be useful, but that isn't shown in the action. My request is for the action to be changed to make debugging easier.

### pre-commit --version

pre-commit-ci/lite-action@v1.0.2

**Comment by asottile** [comment]
this is the wrong repo, and feel free to debug it yourself! actions are public repos so you can do whatever you need to figure it out

**Comment by adamtheturtle** [comment]
@asottille I chose this issue because https://github.com/pre-commit-ci/lite-action does not allow new issues.

I am in the process of running my own fork of the action and adding debugging helpers. However, I still think it is a valid request - show the error details.

**Comment by adamtheturtle** [comment]
@asottile I chose this issue because https://github.com/pre-commit-ci/lite-action does not allow new issues.

I am in the process of running my own fork of the action and adding debugging helpers. However, I still think it is a valid request - show the error details.

**Comment by asottile** [comment]
pre-commit-ci/issues is where

it can't really know what is the best output for everyone so please debug your issue in your own!
