### ISSUE TITLE
Support Github Actions notices

### ISSUE THREAD

**Issue by NickLarsenNZ** [pre-commit/pre-commit#3294]
### search you tried in the issue tracker

combinations of: github actions notice warning output

### describe your actual problem

When running in Github Actions (ie: `GITHUB_ACTIONS=true`), we would like warnings/errors to appear for the lines they relate to.

This can be achieved by printing output (per docs for [notice], [warning], and [error]) such as:

```
::warning file=example.yaml,line=8,col=3,title=yamllint::comment not indented like content  (comments-indentation)
```

A preview of a [warning] and [error]:

![preview](https://user-images.githubusercontent.com/46307996/181099304-a6ab1d98-a6a8-4d09-ac15-cd1532e09d53.png)

[notice]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-notice-message
[warning]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-warning-message
[error]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-error-message

### pre-commit --version

pre-commit 3.7.1

**Comment by NickLarsenNZ** [comment]
The icing on the cake would would be a [job summary]

[job summary]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary

![preview](https://docs.github.com/assets/cb-24677/mw-1440/images/help/actions/actions-job-summary-simple-example.webp)

**Comment by asottile** [comment]
the framework has no control over the output of individual tools
