### ISSUE TITLE
A means of dealing with unstaged files 

### ISSUE THREAD

**Issue by ernieIzde8ski** [pre-commit/pre-commit#3295]
### search you tried in the issue tracker

`is:issue is:open unstaged hook`, `is:issue unstaged`

### describe your actual problem

I have a local directory named `target/`, which I intentionally include in my working tree. I ensure that the files in this directory are always generated with a pre-commit hook, but I do not have a means of ensuring that they are always tracked. Would it be possible to write a `fail` rule that operates on untracked or unstaged files, or is there a better way?

### pre-commit --version

pre-commit 3.8.0

**Comment by asottile** [comment]
it makes no sense to lint on things which aren't being committed
