### ISSUE TITLE
language 'coursier' with 'local' repo fails

### ISSUE THREAD

**Issue by pettermahlen** [pre-commit/pre-commit#3308]
### search you tried in the issue tracker

coursier - showing only 3 closed tickets

### describe your issue

Using the following hook configuration: 
```
  - repo: local
    hooks:
      - id: ktfmt
        name: ktfmt
        language: coursier
        entry: ktfmt --google-style
        files: \.kt$
        require_serial: true
```

And a repo in the root of the git repo, named `.pre-commit-channel`, with the following file: 
```
{
  "mainClass": "com.facebook.ktfmt.cli.Main?",
  "launcherType": "assembly",
  "repositories": [
    "central"
  ],
  "dependencies": [
    "com.facebook:ktfmt:0.52"
  ]
}
```

When I do `pre-commit run`, I get the following output: 

```
An error has occurred: FatalError: expected .pre-commit-channel dir or additional_dependencies
Check the log at /Users/petter/.cache/pre-commit/pre-commit.log
```

I have verified that coursier itself seems to work through this command:

```
coursier  bootstrap --default-channels=false --channel=.pre-commit-channel com.facebook:ktfmt:0.51 -M com.facebook.ktfmt.cli.Main -o kkk
```

I have a feeling that pre-commit uses some prefix; it would have been great to report the full directory [here](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/languages/coursier.py#L58), so that it would be easier to understand how to fix the error. 

Does maybe .pre-commit-channel need to be added to the [LOCAL_RESOURCES](https://github.com/pre-commit/pre-commit/blob/de8590064e181c0ad45d318a0c80db605bf62a60/pre_commit/store.py#L39) or something? Or am I doing something wrong? 

### pre-commit --version

3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.11.0
    hooks:
      - id: google-java-formatter-jdk11
        args: [--replace, --set-exit-if-changed]
  - repo: local
    hooks:
      - id: ktfmt
        name: ktfmt
        language: coursier
        entry: ktfmt --google-style
        files: \.kt$
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.45.1
sys.version:
    3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.7.1/libexec/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: FatalError: expected .pre-commit-channel dir or additional_dependencies
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/languages/coursier.py", line 57, in install_environment
    raise FatalError(
pre_commit.errors.FatalError: expected .pre-commit-channel dir or additional_dependencies
```

**Comment by pettermahlen** [comment]
These docs state differently: https://pre-commit.com/index.html#coursier

> new in 3.0.0: language: coursier hooks now support repo: local and additional_dependencies.

Should that be '... support repo:local with additional_dependencies but not with .pre-commit-channel'?

**Comment by asottile** [comment]
as stated before, pre-commit never installs from the repo under test -- independent of language

**Comment by pettermahlen** [comment]
I don't understand that statement, I'm afraid. To me, the docs seem to say that I should be able to do what I tried to do, but it's not working, and the error message is not understandable.

For clarity, this report was an attempt at helping improve the product in that regard, either by fixing the code or the docs.

**Comment by asottile** [comment]
`local` only installs from the configuration always.  anything else is intractable
