### ISSUE TITLE
improve parallel documentation/execution

### ISSUE THREAD

**Issue by andrewgazelka** [pre-commit/pre-commit#3317]
### search you tried in the issue tracker

pre-commit parallel

### describe your actual problem

https://github.com/Eventual-Inc/Daft/blob/main/.pre-commit-config.yaml

seems to run sequentially. However, from what I understand it should be running in parallel unless [require_serial](https://pre-commit.com/#hooks-require_serial) is set to true.

### pre-commit --version

3.8.0

**Comment by asottile** [comment]
what does the text say in the link in the docs?

**Comment by andrewgazelka** [comment]
> what does the text say in the link in the docs?

> (optional: default false) if true this hook will execute using a single process instead of in parallel.
 
=>

should be executing in parallel since we do not have require_serial, correct?

**Comment by asottile** [comment]
what does "this hook" mean?
