### ISSUE TITLE
Node hooks using ECMAScript module imports will not properly work

### ISSUE THREAD

**Issue by Alexerson** [pre-commit/pre-commit#3321]
### search you tried in the issue tracker

eslint, node, esm

### describe your issue

When a `node` hook depends on a ESM JS config file (for instance the new eslint config, it seems tailwind as well, but I haven’t used it), then the imports cannot be resolved, even if you properly specified the additional dependencies.

This is happening (I think) because with ESM, node is not supporting `NODE_PATH` anymore: see the note here - https://nodejs.org/api/esm.html#esm_no_node_path

You can reproduce the issue with https://github.com/alexerson/pre-commit-3321

The workaround solution for now is to keep those configuration file as commonJS, rather than ESM, but it seems the general movement for the node ecosystem is to go to ESM, so it would probably be good to support this somehow (which I agree might be tricky cause the only solution seems to be symlinks).

The error will be a "missing dependency" error from node, for instance:
```
eslint...................................................................Failed
- hook id: eslint
- exit code: 2


Oops! Something went wrong! :(

ESLint: 9.12.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'globals' imported from /home/alex/Projects/pre-commit-3321/eslint.config.js
Did you mean to import "globals/index.js"?
    at packageResolve (node:internal/modules/esm/resolve:839:9)
    at moduleResolve (node:internal/modules/esm/resolve:908:18)
    at defaultResolve (node:internal/modules/esm/resolve:1038:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:557:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:525:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:246:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49)
```

### pre-commit --version

3.8.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.12.0
    hooks:
      - id: eslint
        files: \.[jt]s$ # *.js, *.ts
        types: [file]
        additional_dependencies:
          - eslint@9.12.0
          - globals@15.10.0
```

**Comment by asottile** [comment]
please include a minimal example and error message otherwise this issue is useless to most

**Comment by Alexerson** [comment]
Hello, thanks for looking into it. 
Here is a git repo with a minimal reproduction: https://github.com/alexerson/pre-commit-3321
I’ve added the steps in the README.md.

**Comment by asottile** [comment]
please include that in this issue including error message such that others having the issue can find it and I can understand what you're even talking about

**Comment by Alexerson** [comment]
I can add the error message, but it won’t give more information, because it is specific to the used hook and the additional dependencies used.

**Comment by asottile** [comment]
I still don't think I understand, this just seems like standard expectations (the local dependencies aren't supposed to be available)

**Comment by Alexerson** [comment]
My assumptions are as follow:
- when you use pre-commit, you don’t need to install anything locally, because pre-commit will use it’s own folder to install the needed libraries (the venv for python, or the node_modules for node for instance)
- the `bin` folder in the pre-commit repo contains the tool binary file, and that’s the file that is run directly by pre-commit
- when running the bin (in my case eslint), pre-commit is setting `NODE_PATH` to make sure the additional dependencies are found by node.

Except, with ESM, the `NODE_PATH` is ignored, because apparently that’s what the node project decided makes more sense. So now, the binary is found (because pre-commit is running it with the full path), but the import for the additional dependencies (that are needed by the config file via an import) are not found, because the `pwd` for pre-commit is still the current project, and `node` is only looking in `$(pwd)/node_modules/` for ESM imports, ignoring `NODE_PATH`.

**Comment by asottile** [comment]
how does `npm i -g` normally work in that case?

**Comment by Alexerson** [comment]
It fails as well (even more than `pre-commit` it seems, as even the CJS version doesn’t work). Same for `npx`.

Maybe there is no easy solution for it [^1] and the only good way is to do `npm install` in the project before running pre-commit (which I feel would break the expectations of what additional_dependencies does) and that’s it. In that case, maybe it’s simply worth documenting?

[^1]: my research only triggers symlinks solutions. Because I have a workaround in my case, I didn’t try to look into how much of a solution it would be for pre-commit.

**Comment by asottile** [comment]
if it doesn't work for `npx` or `-g` then I don't think this is a pre-commit problem

**Comment by Alexerson** [comment]
Sounds fair. Thanks for looking into this.

**Comment by RayBB** [comment]
@Alexerson did you ever find a better solution for this? I'm facing this with eslint as well.
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'eslint' imported from ./eslint.config.mjs
```

**Comment by RayBB** [comment]
As I dug around more, weirdly the fix locally seems to be running `npm i`. This is confusing to me because I thought pre-commit runs in an isolated way.
Unfortunately, in CI the issue persists. So I think I'll open a bug report.

**Comment by Alexerson** [comment]
It works locally because the `pwd` for npm (or npx) will be the current working repository (and therefore, the fact that `NODE_PATH` is ignored won't be an issue), and that's where it will look for the `node_modules`.

I feel sticking with CommonJS is cleaner.

**Comment by Alexerson** [comment]
Nothing specific, you just convert your ESM file to commonJS.

Something like this:
```
const eslint = require("@eslint/js");
const compat = require("eslint-plugin-compat");
const globals = require("globals");

/** @type { import("eslint").Linter.Config[] } */
module.exports = [
  {
    ignores: ["eslint.config.cjs"],
  },

  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  eslint.configs.recommended,
  compat.configs["flat/recommended"],
];

```

**Comment by wosc** [comment]
I did manage to make pre-commit `language: node` work for using ESM modules, but it is somewhat kludgy.

```yaml
# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        # You have to reverse-engineer how to call the respective program
        # without using its ready-made script (`prettier` in this example),
        # since we have to inject the `node --loader` commandline parameter
        entry: ./node.sh prettier/bin/prettier.cjs --write --ignore-unknown
        types: [text]
        language: node
        additional_dependencies:
          - prettier
```

```js
// .prettierrc.mjs
// You have to specify the filename here, even though normal ESM imports do not;
// I don't know enough about JS to figure out why, or if/how I could fix that
import shared_config from 'example-config-module/index.js';

export default {
  ...shared_config
}
```

```bash
# node.sh
#!/bin/bash
program=$1
shift
exec node --loader esm-loader.js $NODE_PATH/$program "$@"
```

```js
// esm-loader.js
import { pathToFileURL } from 'node:url';

export async function resolve(specifier, context, nextResolve) {
	try {
		return await nextResolve(specifier, context);
	} catch (err) {
		if (!isBareSpecifier(specifier)) throw err;
		// pre-commit points NODE_PATH to the `node_modules` directory itself.
		const url = pathToFileURL(process.env.NODE_PATH + '/' + specifier).href;
		return await nextResolve(url, context);
	}
}

function isBareSpecifier(specifier) {
	return (
		!specifier.startsWith('./') &&
		!specifier.startsWith('../') &&
		!specifier.startsWith('/') &&
		!/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(specifier) // node:, file:, https:, etc.
	);
}
```
