### ISSUE TITLE
publicly document the rationale behind #730 (where the local repository is not installed for tests)

### ISSUE THREAD

**Issue by ernieIzde8ski** [pre-commit/pre-commit#3325]
### search you tried in the issue tracker

python local repo

### describe your actual problem

The referenced issue is a popular one. You have a repository with some Python, you incorporate some type checker, and you want pre-commit to find your repository's dependencies for you. Desirable, which explains the many duplicates:

- #157
- #730
- #880
- #1406
- #1445
- #1626
- #1752
- #1837
- #1926
- #2133

The fact that you can't do this is not obvious. It seems reasonable from the website that you might be able to do this for a local repo:

> The hook repository must be installable via `pip install .`.
> ...
> Repository-local hooks are useful when: Hooks require state that is only present in a built artifact of your repository

After a little digging, the first issue I found to provide real clarity as to *why* was a comment on #1445:

> implementation detail: it still runs pip install ., but it's on the empty template
> ... this is intentional, installing from things outside of .pre-commit-config.yaml leads to intractable caching problems

(...and [a comment on #880](https://github.com/pre-commit/pre-commit/pull/880#issuecomment-446286115) talks about this in the most depth)

This explains why a naïve solution like `additional_dependencies: ["."]` would create a valid pre-commit hook, but not install dependencies like the user might hope. It also explains why `additional_dependencies: ["-r", "-requirements.txt"]` does *not* create a valid pre-commit hook.

None of this is obvious. I looked through issues, PRs, and their comments for maybe half an hour today before I found one which explained that this can't be done with pre-commit, which had a rationale, and whose rationale made sense to me.

The request: add documentation on [the website's `python` language](https://pre-commit.com/#python) or on [its local hook section](https://pre-commit.com/#repository-local-hooks) to explicitly state the exception of "a local repo need not be installable", that it cannot be used to supply values to `additional_dependencies`, and maybe a "here's a link to why".

### pre-commit --version

pre-commit 4.0.0

**Comment by asottile** [comment]
the issues are public already
