### ISSUE TITLE
Allow opening issues in `pre-commit/action` or document where to open issues

### ISSUE THREAD

**Issue by jamesbraza** [pre-commit/pre-commit#3332]
### search you tried in the issue tracker

n/a

### describe your actual problem

https://github.com/pre-commit/pre-commit/issues/3331 was closed because "wrong repo" and immediately locked as off topic. I opened that issue here because https://github.com/pre-commit/action as of 10/14/2024 does not allow issues being opened there.

Since `pre-commit` only lets issues be opened in a few places, where should one open requests or bug reports for https://github.com/pre-commit/action? Can you at least document that in this repo, `pre-commit.com`, or https://github.com/pre-commit/action?

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
it is temporarily disabled.  please respect boundaries
