### ISSUE TITLE
Expose repo path

### ISSUE THREAD

**Issue by petrprikryl** [pre-commit/pre-commit#3334]
### search you tried in the issue tracker

expose repo path

### describe your actual problem

Hi, I would like to propose some new command to get useful metadata about repo and hooks. In my case the installation path which is in DB: https://github.com/pre-commit/pre-commit/blob/cc4a52241565440ce200666799eef70626457488/pre_commit/store.py#L95

It could look something like:
```
~ pre-commit inspect ruff
/home/user/.cache/pre-commit/repo86lnsa5q
```

I think it is useful for debugging/verifying hooks.

### pre-commit --version

pre-commit 4.0.0

**Comment by asottile** [comment]
this has been proposed many times and is intentionally not exposed because of testing showed that people messed with the private implementation details

please search better next time
