### ISSUE TITLE
freeze commit sha in rev field

### ISSUE THREAD

**Issue by mcbemlogic** [pre-commit/pre-commit#3335]
### search you tried in the issue tracker

freeze rev; freeze revision; block autoupdate; revision freeze; manual rev update 

### describe your actual problem

I want to be able to freeze the rev field to a specific commit SHA e.g. `rev: 75b98813cfb7e663870a28c74366a1e99d7bfe79 # corresponds to v0.6.9` or tag

My problem is that when I then run `pre-commit autoupdate` the rev field will be updated again to the latest tag: e.g. `rev: v0.6.9` (or sha with `--freeze`)

I want to be able to make the rev field so it is not possible at all to update it with `autoupdate` (also with the `--freeze` option), but only manually update the rev field. This is for security reasons, I don't ever want the hook to run on a third party repo that has not been checked (since the last rev sha). To stop this, I would like that the `rev` field can only be manually updated, so I can leave a comment regarding the security risk associated with updating the `rev`, so that users can evaluate for themselves before updating.

I have thought of two solutions for this: 

1. Some kind of global config in the `.pre-commit-config.yaml` file that blocks `autoupdate`
2. An optional field next to `rev` that specifies if the rev can be automatically updated or not:

```yaml
rev: 75b98813cfb7e663870a28c74366a1e99d7bfe79
rev_freeze: true
``` 

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
you're asking for `pre-commit autoupdate --no-auto` which is nonsense as such has been rejected many times.  if you don't want the automatic behavior don't use the automatic tool
