### ISSUE TITLE
freeze pre-commit revision

### ISSUE THREAD

**Issue by mcbemlogic** [pre-commit/pre-commit#3338]
### search you tried in the issue tracker

freeze rev; freeze revision; block autoupdate; revision freeze; manual rev update 

### describe your actual problem

I just wanted to respond to some comments left on my previous open issue, since it is now closed I cannot respond: https://github.com/pre-commit/pre-commit/issues/3335

I just want to clear some things up that I perhaps didn't explain so well:

- "if you don't want the automatic behavior don't use the automatic tool": This is exactly the point. However, anyone in the team could use the automatic tool without knowing the consequences. This is why I wanted something that would be more forceful in stopping automated updates.

- "don't run autoupdate if you don't want to autoupdate": again this is similar to the point above. I know that for my usecase I don't want to run autoupdate, but anyone else in the team using the same repo could use autoupdate without knowing the consequences. Of course you can try and notify everyone in the team not to use it, or you could have some mechanism for not allowing it for your project.

### pre-commit --version

pre-commit 4.0.1

**Comment by mcbemlogic** [comment]
Also when I ask for a global config I am not asking for a command line option like: `pre-commit autoupdate --no-auto``
I am more looking for some flag I can place in the `.pre-commit-config.yaml`

**Comment by asottile** [comment]
the answer is no. I'm not relitigating this.  please respect boundaries
