### ISSUE TITLE
Consider defaulting node version to "lts" rather than using nodeenv default (latest)

### ISSUE THREAD

**Issue by jasonwashburn** [pre-commit/pre-commit#3340]
### search you tried in the issue tracker

["lts", "node lts", "node version"]

### describe your actual problem

In light of the Node 23 release yesterday that broke pre-commit hooks requiring node without an explicitly defined `language_version`, I was curious on your thoughts on setting the default version of node used to "lts" instead of defaulting to the nodeenv default (which appears to be latest)

Looking at the history of both projects, it looks like the option to select "lts" was added as a nodeenv feature (https://github.com/ekalinin/nodeenv/pull/281) about a year _after_ the current version selection logic in [pre_commit/languages/node.py](https://github.com/pre-commit/pre-commit/commit/0f528544b5a5d74744a2f9271a215098c12982f1#diff-511cea45e7094a2bb5988a8e2c7b8e0110a0550bbdca7baeedda93a2525e840a) .

The change appears like it would be pretty straightforward (a changed lines and updating some test expectations), but understand that there might be some resistance since it would technically be a breaking change. 

Happy to do the work if it's something you're interested in changing, but understand if you want to leave it as-is as it's completely solvable with the language_version option.

also, big thank you for the work you're doing, it makes a lot of our jobs easier!

-Jason

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
I think it would be a more convincing argument in the nodeenv repository (and deviating from their behavior would be more surprising than not).  I can't remember where but this is the conclusion we came to last time and I think I'm going to stick to that today

note also that latest is the fallback when no suitable node is available
