### ISSUE TITLE
Verify dependencies from `additional_dependencies` are installed

### ISSUE THREAD

**Issue by stoney95** [pre-commit/pre-commit#3342]
### search you tried in the issue tracker

"Executable not found", "additional_dependencies", "local Executable not found"

### describe your issue

I was trying to use `repo: local` in combination with  `additional_dependencies` and `language: python`. I know this is the escape hatch. I also searched for 2 hrs to find a coresponding issue. There are some that look similar, but I couldn't find any about the installation of  `additional_dependencies`. [This](https://github.com/pre-commit/pre-commit/issues/3243) is the closest I could find. But could not find the duplicates mentioned in the comments. 

I am working behind a proxy which does not allow `git clone ...` of public repositories. The installation of packages via `pip` is allowed via a private pypi mirror. 
In my understanding deps defined by `additional_dependencies` are installed into the pre-commit environment. 

I expected that running `pre-commit run -a` would run the specified pre-commit hooks (currently only `pydocstyle`). 

The output I got was:

```bash
$ pre-commit run -a
[INFO] Initializing environment for local:--index-url=https://company.com/pypi/simple pydocstyle.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Check doc strings are in place...........................................Failed
- hook id: pydocstyle
- exit code: 1

Executable `pydocstyle` not found
```

So, I am wondering how I can check if the dependencies (here `pydocstyle`) have been installed correctly. It also seems that pre-commit setup commands run inside the pre-commit home, which can be set via `PRE_COMMIT_HOME`, but is looking for the dependencies in the currently activated environment. At least, when I install the dependency (`pydocstyle`) manually into the currently active environment the hook gets executed properly.  

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks: 
      - id: pydocstyle
        name: Check doc strings are in place
        entry: pydocstyle
        args: ["--add-ignore=D100,D101,D104,D107"]
        types: [python]
        language: python
        additional_dependencies: [
          --index-url=https://company.com/pypi/simple pydocstyle
        ]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
#Only present for using `additional_dependencies` without `--index-url`
#pre-commit tries to install `pydocstyle` from public pypi. This fails as its blocked by the company proxy
#I ran this to check if something happens when using `additional_dependencies`

stderr:
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000000059BDD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pydocstyle/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000000059BE750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pydocstyle/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000000059BF050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pydocstyle/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000000059BF990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pydocstyle/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000000059B83D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pydocstyle/
    ERROR: Could not find a version that satisfies the requirement pydocstyle (from versions: none)
    ERROR: No matching distribution found for pydocstyle
```

**Comment by asottile** [comment]
your config is missing a `,`.  as written it is using an index URL with a space in it and not a package

not really much pre-commit can do when you can't yaml properly
