### ISSUE TITLE
Question: Update pre-commit sample-config to avoid deprecated stage names?

### ISSUE THREAD

**Issue by ido123net** [pre-commit/pre-commit#3351]
### search you tried in the issue tracker

sample-config

### describe your actual problem

When using `pre-commit sample-config`, I noticed that the generated `.pre-commit-config.yaml` file includes:
```sh
$ pre-commit sample-config
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      ...
```
This setup causes the following warning:
```sh
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[WARNING] repo `https://github.com/pre-commit/pre-commit-hooks` uses deprecated stage names (commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks` will fix this.  if it does not -- consider reporting an issue to that repo.
...
```

I wanted to check if this configuration is intentional to inform users of the deprecation, or if the goal is to update the sample file to avoid the warning. If an update is desired, I’d be happy to help with PR.

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
search prs too next time!
