### ISSUE TITLE
Any way we can mark a specific hook so it doesn't get cached?

### ISSUE THREAD

**Issue by OmarJaroudi** [pre-commit/pre-commit#3353]
### search you tried in the issue tracker

cache, bypass cache

### describe your actual problem

I want to be able to bypass the cache for certain hooks in my pre-commit-config file, ideally by passing a flag to that hook perhaps? The idea is that I have a node hook, which I pass additional_dependencies to, like so
```
- additional_dependencies: ["myDependency@^1"]
```
(I basically want consumers to always pick up the most recent minor version of that dependency)
So assume the hook runs the first time, installs version v1.0.0 of that dependency, if I release a new version of it (say v1.1.0), I'm having to manually clear the pre-commit cache before running again, to pick up the new version.
This is not too bad locally, but I am also invoking pre-commit in a Github Actions workflow, where I am saving the pre-commit cache based on a hashkey of the pre-commit-config file, to cut down on running time by reusing that cache if the pre-commit-config is unchanged. But that means that if a new version of `myDependency` was released, I would have to flush that cache for the CI workflow to do a fresh run of pre-commit and setup the hooks again.
Any ideas if this is already possible with the current logic? Or if adding a flag to bypass the cache/not save a cache entry for certain hooks seems feasible?
Thank you!

### pre-commit --version

pre-commit 4.0.1

**Comment by OmarJaroudi** [comment]
I don't think I'm missing the point, no. Using a floating major is a valid way to version npm dependencies, and using it comes with the understanding that users might end up with a newer minor version without them performing any manual action. I understand pre-commit's position on intentionally not accommodating _"unpinned latest version" of hook repositories_, but I believe this isn't exactly the same thing; I don't see the point in that applying for additional_dependencies.
Would you care to elaborate why this doesn't make sense to you?

**Comment by asottile** [comment]
you're missing the point of pre-commit which is to ensure all of your developers utilize exactly the same tools to validate their changes
