### ISSUE TITLE
Support combining hooks into groups that can be run together

### ISSUE THREAD

**Issue by jalaziz** [pre-commit/pre-commit#3359]
### search you tried in the issue tracker

hook groups

### describe your actual problem

This is a revisit of #554 which was closed by the author, but I would like to present a use case which I believe could benefit from this feature.

Through multiple other issues, it has been made clear that using `files` or `types` as a "trigger" for when a hook runs is an abuse of pre-commit. Instead, it appears that the recommended use case is to generally always run "all" hooks.

While this works for smaller repos, in large polygot monorepos running all hooks on every change can waste a large amount of time, resources, and money. It's becoming increasingly common to speed up builds, tests, and even linting by selectively running tools based on the changes being committed.

It's also become increasingly common for hooks to be somewhat granular. For example, for Rust you may have a `cargo fmt` and a `clippy` hook and for protobuf you may have multiple `buf` hooks.

pre-commit already allows running specific hooks by passing a hook ID to `pre-commit run`. This is great, but only supports a single hook. Alternatively, you can exclude running multiple hooks by using `SKIP`.

However, managing individual hooks in an increasingly complex pre-commit configuration in a large repo with many contributors is not very scalable. To accomplish selective triggering of hooks based on changes, it would be great if we could label hooks with a set of groups and then ask `pre-commit` to run all hooks that are labeled with that group.

An example use case using GitHub Actions may look like:
* PR triggers a workflow
* The workflow runs a step to determine which files have changed, assigning a set of groups
* The workflow then calls `pre-commit` passing the set of groups for which hooks should be run
* Success!

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
this was previously declined. please respect the last decision
