### ISSUE TITLE
Allow selective pass-on-change behavior for specific files

### ISSUE THREAD

**Issue by bisrat-otterai** [pre-commit/pre-commit#3364]
### search you tried in the issue tracker

modified, pass selected, 

### describe your actual problem

Hi,

I'm trying to achieve a workflow where the pre-commit framework allows certain files to be modified by hooks without causing a failure, while still failing if other files are modified. 

Currently, if a hook modifies any files (e.g., Ruff's `--fix` option), the pre-commit framework fails the commit. While this is generally desirable behavior, there are cases where we want to allow automatic fixes for certain files while still preventing modifications.

Example use case:
- A [system](https://pre-commit.com/#system) hook that updates a cache directory that exists within the same directory where the hook itself runs. In this case, even on a successful run, when the hook updates the cache, it's considered a failed run.

I've tried using `exclude` patterns and file-specific args, but these either skip the files entirely or still fail when modifications are made. If there are existing workarounds to this, I would love to know.

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
this has been rejected many times.  silently modifying what is to be committed is a bad idea for many reasons
