### ISSUE TITLE
Unit tests fail when only one env is used

### ISSUE THREAD

**Issue by shaleh** [pre-commit/pre-commit#337]
If I run ``tox -e py27`` the unit tests fail because they still try to call python3.

```
>               returncode, cmd, retcode, output=(stdout, stderr),
            )
E           CalledProcessError: Command: ['/home/perryse/repos/pre-commit/.tox/py27/bin/python2.7', '-m', 'virtualenv', '/tmp/pytest-of-perryse/pytest-3/test_arbitrary_bytes_hook0/0/repoxUiuHu/py_env-python3.3', '-p', 'python3.3']
E           Return code: 3
E           Expected return code: 0
E           Output:
E               The executable python3.3 (from --python=python3.3) does not exist
E
E           Errors: (none)
```

**Comment by shaleh** [comment]
My system only has 2.7 and 3.4 installed so I was trying to limit the tests. Still no dice )-:

**Comment by asottile** [comment]
Documented here: https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#local-development

**Comment by shaleh** [comment]
I missed that. Sorry.

Would you be opposed to the tests being moved into a "multi-version" env so that if the user invokes ``tox -e py??`` the tests only validate that version? A full run will still run all of them. This would also allow running just the explicitly multi-version tests too.
