### ISSUE TITLE
Follow-up to #3369

### ISSUE THREAD

**Issue by nickvigilante** [pre-commit/pre-commit#3370]
### search you tried in the issue tracker

conda environment.yml

### describe your actual problem

Following up on this, the docs had suggested to me that so long as the hook repository (which I assumed applied to the local reposotiry) has an `environment.yml` file, that it would try to install it. Here's the exact sentence from which I gathered that:

> The hook repository must contain an environment.yml file which will be used via conda env create --file environment.yml ... to create the environment.

It would be nice to see more explicit wording here stating what @asottile shared in #3369.

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
a `repo: local` has no repository as indicated in the docs
