### ISSUE TITLE
Maybe replace xargs with a python implementation

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#345]
There's quite a few bugs we've run into by relying on a valid implementation of xargs being installed.  Perhaps we should instead implement our own in python and call that. 

This would also allow us to do clever things with multi processing if we wanted to.

**Comment by chriskuehl** [comment]
you probably just aren't using the right permutation of xargs' 40 command-line flags

**Comment by asottile** [comment]
via #355
