### ISSUE TITLE
"Not a git repository" error in Cygwin

### ISSUE THREAD

**Issue by sverhagen** [pre-commit/pre-commit#352]
`pre-commit install` seems to have worked fine, but when executing `pre-commit run` I run into the following problem:

	$ pre-commit run
	[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
	An unexpected error has occurred: CalledProcessError: Command: ['git', 'reset', 'v0.4.2', '--hard']
	Return code: 128
	Expected return code: 0
	Output: (none)
	Errors:
	    fatal: Not a git repository (or any of the parent directories): .git
	
	
	Check the log at ~/.pre-commit/pre-commit.log

This is a Windows machine, inside a Cygwin shell, with 1.9.4.msysgit.2 and Python 2.7.10.

Obviously this is working just fine on my colleagues' computers who are on Macs :cry:

**Comment by asottile** [comment]
This error message looks familiar at least! 

Could you provide the following as well:
- pre-commit --version
- cat ~/.pre-commit/pre-commit.log

**Comment by sverhagen** [comment]
> This error message looks familiar at least!

Thanks, that looks promising. We googled for it, but to no avail.

Here's the additional info:

	$ pre-commit --version
	pre-commit 0.7.6

	$ cat ~/.pre-commit/pre-commit.log
	An unexpected error has occurred: CalledProcessError: Command: ['git', 'reset', 'v0.4.2', '--hard']
	Return code: 128
	Expected return code: 0
	Output: (none)
	Errors:
	    fatal: Not a git repository (or any of the parent directories): .git
	
	
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
	    yield
	  File "/usr/lib/python2.7/site-packages/pre_commit/main.py", line 147, in main
	    return run(runner, args)
	  File "/usr/lib/python2.7/site-packages/pre_commit/commands/run.py", line 195, in run
	    repo_hooks = list(get_repo_hooks(runner))
	  File "/usr/lib/python2.7/site-packages/pre_commit/commands/run.py", line 141, in get_repo_hooks
	    for repo in runner.repositories:
	  File "/usr/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
	    value = obj.__dict__[self.func.__name__] = self.func(obj)
	  File "/usr/lib/python2.7/site-packages/pre_commit/runner.py", line 47, in repositories
	    repository.require_installed()
	  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 115, in require_installed
	    self.install()
	  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 163, in install
	    for language_name, language_version in self.languages
	  File "/usr/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
	    value = obj.__dict__[self.func.__name__] = self.func(obj)
	  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 62, in languages
	    for _, hook in self.hooks
	  File "/usr/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
	    value = obj.__dict__[self.func.__name__] = self.func(obj)
	  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 77, in hooks
	    if hook['id'] not in self.manifest.hooks:
	  File "/usr/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
	    value = obj.__dict__[self.func.__name__] = self.func(obj)
	  File "/usr/lib/python2.7/site-packages/pre_commit/manifest.py", line 24, in hooks
	    return dict((hook['id'], hook) for hook in self.manifest_contents)
	  File "/usr/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
	    value = obj.__dict__[self.func.__name__] = self.func(obj)
	  File "/usr/lib/python2.7/site-packages/pre_commit/manifest.py", line 18, in manifest_contents
	    self.repo_path_getter.repo_path, C.MANIFEST_FILE,
	  File "/usr/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
	    value = obj.__dict__[self.func.__name__] = self.func(obj)
	  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 47, in repo_path
	    return self._store.clone(self._repo, self._sha)
	  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 122, in clone
	    cmd_output('git', 'reset', sha, '--hard', env=no_git_env())
	  File "/usr/lib/python2.7/site-packages/pre_commit/util.py", line 194, in cmd_output
	    returncode, cmd, retcode, output=(stdout, stderr),
	CalledProcessError: Command: ['git', 'reset', 'v0.4.2', '--hard']
	Return code: 128
	Expected return code: 0
	Output: (none)
	Errors:
	    fatal: Not a git repository (or any of the parent directories): .git

**Comment by asottile** [comment]
Awesome, so here's what I've tried so far (haven't been able to reproduce it yet, but I'm trying to eliminate possibilities!):

- git2.6.3 on windows -> works
- git1.9.4 on ubuntu -> works

I'll try and use 1.9.4 on windows next, do you know where I can find the exact installer you're using?

**Comment by asottile** [comment]
Just as a test (and potential workaround), can you try using pre-commit 0.7.0 (via `pip install pre-commit==0.7.0`) -- this was the version before I added special support for submodules (which complicated the way I have to call the git command that's triggering the error above)

**Comment by sverhagen** [comment]
> I'll try and use 1.9.4 on windows next

You know, don't do that. I didn't realize that it is _that_ outdated, and I'll upgrade. I'm installing 2.7.4 now. I'll update the thread with the results.

**Comment by sverhagen** [comment]
The results with Git 2.7.4 (`git version 2.7.4.windows.1`) are exactly the same. Did you notice this is all in Cygwin? I don't even have my Python setup to work anywhere else, so I can't (yet) test it from a normal Command Prompt.

**Comment by sverhagen** [comment]
I'm also wondering if there's an issue with paths, and I was wondering if it'd make sense to pass `cwd` to `subprocess.Popen` to make sure that it's in the right folder. Cygwin has these funny folders, like `/cygdrive/e/my_repo` instead of `E:\my_repo`. We would expect me to execute `pre-commit run`, and for `Popen` to execute in the root of my local working copy, right?

**Comment by asottile** [comment]
Ah strange, things are all sorts of broken under cygwin :(

I usually use MINGW64, powershell, or cmd which seem to work better

I'll look into getting cygwin working but for now I'd suggest the others :)

**Comment by asottile** [comment]
Ah so my problem is I'm using non-cygwin python in a cygwin space and so the paths that git is returning don't match up with the paths python expects

**Comment by asottile** [comment]
Hrmm, now I'm stumped again:

```
Anthony@AnthonysDesktop /tmp/foo
$ pip install pre-commit
Collecting pre-commit
  Downloading pre_commit-0.7.6-py2.py3-none-any.whl (100kB)
    100% |████████████████████████████████| 102kB 2.7MB/s
Collecting aspy.yaml (from pre-commit)
  Downloading aspy.yaml-0.2.1.tar.gz
Collecting argparse (from pre-commit)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting virtualenv (from pre-commit)
  Using cached virtualenv-15.0.1-py2.py3-none-any.whl
Collecting jsonschema (from pre-commit)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Collecting cached-property (from pre-commit)
  Downloading cached_property-1.3.0-py2.py3-none-any.whl
Collecting pyyaml (from pre-commit)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 256kB 2.2MB/s
Collecting nodeenv>=0.11.1 (from pre-commit)
  Downloading nodeenv-0.13.6.tar.gz
Collecting ordereddict (from pre-commit)
  Downloading ordereddict-1.1.tar.gz
Collecting functools32 (from jsonschema->pre-commit)
  Downloading functools32-3.2.3-2.tar.gz
Building wheels for collected packages: aspy.yaml, pyyaml, nodeenv, ordereddict, functools32
  Running setup.py bdist_wheel for aspy.yaml ... -done
  Stored in directory: /home/Anthony/.cache/pip/wheels/de/99/d7/5b333af6ba8ec93d6ecd8b4f61471125a841b25564e1d404de
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /home/Anthony/.cache/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
  Running setup.py bdist_wheel for nodeenv ... done
  Stored in directory: /home/Anthony/.cache/pip/wheels/b1/59/d6/d7e2be1c56d2fc8d02fcf567fa270b828a17a18012b2a62bf1
  Running setup.py bdist_wheel for ordereddict ... done
  Stored in directory: /home/Anthony/.cache/pip/wheels/4e/23/88/f33a8c7c622e6f5244c408306805de7c56dd5d36cff4346fb6
  Running setup.py bdist_wheel for functools32 ... done
  Stored in directory: /home/Anthony/.cache/pip/wheels/38/c6/c7/ee17acd621120c302e25c2fa8b3a8b235d5d1137c6ab4c9728
Successfully built aspy.yaml pyyaml nodeenv ordereddict functools32
Installing collected packages: ordereddict, pyyaml, aspy.yaml, argparse, virtualenv, functools32, jsonschema, cached-property, nodeenv, pre-commit
Successfully installed argparse-1.4.0 aspy.yaml-0.2.1 cached-property-1.3.0 functools32-3.2.3.post2 jsonschema-2.5.1 nodeenv-0.13.6 ordereddict-1.1 pre-commit-0.7.6 pyyaml-3.11 virtualenv-15.0.1
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ pre-commit --version
pre-commit 0.7.6
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ nano .pre-commit-config.yaml
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ pre-commit run --all-files
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Check Yaml...............................................................Passed
(venv)
Anthony@AnthonysDesktop /tmp/foo
```

What does `which git` give you?

**Comment by asottile** [comment]
Ahah, I can now reproduce your error:

```
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ ln -s /cygdrive/c/Users/Anthony/AppData/Local/Programs/Git/mingw64/bin/git.exe  venv/bin/git.exe
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ ls venv/bin/ -al
total 51
drwxr-xr-x+ 1 Anthony Anthony    0 Mar 19 20:29 .
drwxr-xr-x+ 1 Anthony Anthony    0 Mar 19 20:22 ..
-rw-r--r--  1 Anthony Anthony 2072 Mar 19 20:22 activate
-rw-r--r--  1 Anthony Anthony 1014 Mar 19 20:22 activate.csh
-rw-r--r--  1 Anthony Anthony 2212 Mar 19 20:22 activate.fish
-rw-r--r--  1 Anthony Anthony 1137 Mar 19 20:22 activate_this.py
-rwxr-xr-x  1 Anthony Anthony  241 Mar 19 20:22 easy_install
-rwxr-xr-x  1 Anthony Anthony  241 Mar 19 20:22 easy_install-2.7
lrwxrwxrwx  1 Anthony Anthony   72 Mar 19 20:29 git.exe -> /cygdrive/c/Users/Anthony/AppData/Local/Programs/Git/mingw64/bin/git.exe
-rwxr-xr-x  1 Anthony Anthony  224 Mar 19 20:22 jsonschema
-rwxr-xr-x  1 Anthony Anthony  217 Mar 19 20:22 nodeenv
-rwxr-xr-x  1 Anthony Anthony  213 Mar 19 20:22 pip
-rwxr-xr-x  1 Anthony Anthony  213 Mar 19 20:22 pip2
-rwxr-xr-x  1 Anthony Anthony  213 Mar 19 20:22 pip2.7
-rwxr-xr-x  1 Anthony Anthony  225 Mar 19 20:22 pre-commit
-rwxr-xr-x  1 Anthony Anthony  244 Mar 19 20:22 pre-commit-validate-config
-rwxr-xr-x  1 Anthony Anthony  246 Mar 19 20:22 pre-commit-validate-manifest
-rwxr-xr-x  1 Anthony Anthony 9235 Mar 19 20:22 python
lrwxrwxrwx  1 Anthony Anthony    6 Mar 19 20:22 python2 -> python
lrwxrwxrwx  1 Anthony Anthony    6 Mar 19 20:22 python2.7 -> python
-rwxr-xr-x  1 Anthony Anthony 2331 Mar 19 20:22 python-config
-rwxr-xr-x  1 Anthony Anthony  220 Mar 19 20:22 virtualenv
-rwxr-xr-x  1 Anthony Anthony  220 Mar 19 20:22 wheel
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ which git
/tmp/foo/venv/bin/git
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ git --version
git version 2.6.3.windows.1
(venv)
Anthony@AnthonysDesktop /tmp/foo
$ pre-commit run --all-files
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: Command: ['git', 'reset', 'v0.4.2', '--hard']
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: Not a git repository (or any of the parent directories): .git


Check the log at ~/.pre-commit/pre-commit.log
(venv)
Anthony@AnthonysDesktop /tmp/foo
```

I'm not sure I should support this? (But perhaps I should make it error loudly :D)  This is cygwin python + non-cygwin git -- I'd suggest installing git from the cygwin installer to fix :)

**Comment by sverhagen** [comment]
Thanks for looking into this, I'm very fond of my Cygwin (most of the time).

    $ which git
    /cygdrive/c/Program Files/Git/cmd/git

    $ /cygdrive/c/Program\ Files/Git/cmd/git --version
    git version 2.7.4.windows.1

**Comment by asottile** [comment]
If you install git for cygwin, it should show /usr/bin/git -- You can do this through the cygwin installer

**Comment by sverhagen** [comment]
I can take another look at present day, but when I originally started using Git in Cygwin, I ran in so many problems, performance being one of them, that prompted me to use a proper standalone installation of Git. The Cygwin Git at that time was also considerably out of step with official releases. I would love for it to be supported, but I can see how it would lead to exceptional handling of Cygwin from within `pre-commit`, like I have (unfortunately) seen in more pieces of code, in the past.

**Comment by asottile** [comment]
It seems relatively up-to-date:
```
$ git --version
git version 2.7.4
```

I can't comment on the performance though :)

**Comment by sverhagen** [comment]
I installed that and will try using that for now, and cross other bridges if I were to run into further Git problems. It's a while ago I had these problems, they've had some time to improve :wink: Thanks for you quick support throughout this process. My company is starting to use `pre-commit` as the outcome of a hackathon, and we're excited about it, but it's good to know there's some "community support" when needed :smile:

**Comment by asottile** [comment]
Sounds great! Glad to help :)

I've opened #354 to at least make this error case more obvious -- I'll see if I can't make it easy to "just work" in these cases, barring that I'll at least add an error message in the short term.

Thanks again for the great bug report and useful debugging information!
