### ISSUE TITLE
Warn when mismatching cygwin git/python

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#354]
See #352 and #353 for how this can manifest itself

**Comment by asottile** [comment]
- cygwin python can be detected using `sys.platform == 'cygwin'`
- cygwin git can be detected using `check_output(('git', 'rev-parse', '--show-toplevel')).decode('UTF-8').startswith('/')` (maybe there's a better way?)

I think the code that would need to be added to verify this is:

```python
if sys.platform in ('win32', 'cygwin'):  # pragma no cover (windows only)
    is_cygwin_python = sys.platform == 'cygwin'
    is_cygwin_git = cmd_output('git', 'rev-parse', '--show-toplevel')[1].startswith('/')

    if is_cygwin_python ^ is_cygwin_git:
        logger.warn(...)
```

**Comment by Lucas-C** [comment]
Thanks for adding the warning !
