### ISSUE TITLE
Ability to denote version requirements in hooks.yaml for Ruby dependencies

### ISSUE THREAD

**Issue by ThatGerber** [pre-commit/pre-commit#361]
Right now it's not possible to note which version of a gem should be installed in the additional dependencies because of the way that inputs into the gem install command are shellescaped.

https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/ruby.py#L102

Ex: Trying to install version 5.0.0 of the foodcritic gem results in this `gem install --no-ri --no-rdoc 'foodcritic --version 5.0.0'`

It would be great to be able to mark a gem and a version to be installed in the hooks.yaml rather than having to create an empty gemspec and manage them that way.

**Comment by asottile** [comment]
This configuration seems to work fine for me:

```
-   id: scss-lint
    name: scss-lint
    additional_dependencies: ['scss_lint:0.47.1']
    entry: 'scss-lint'
    files: '\.scss'
    language: ruby
    language_version: 1.9.3-p547
```

Does this satisfy your requirements?

**Comment by ThatGerber** [comment]
Yes it does! Thanks!
