### ISSUE TITLE
`pre-commit uninstall` does not remove pre-push hooks

### ISSUE THREAD

**Issue by insasho** [pre-commit/pre-commit#364]
Steps to repeat:

1. run `pre-commit install -t pre-push`
2. run `pre-commit uninstall`

Expected results:

- pre-commit not invoked for pushes

Actual results:

- .git/hooks/pre-push is still calling pre-commit

**Comment by asottile** [comment]
Indeed, I'll build a fix for this!

**Comment by asottile** [comment]
Actually, you want `pre-commit uninstall -t pre-push`

**Comment by revolter** [comment]
Isn't there an uninstall all? Stumbled upon this too for the `commit-msg` hook.

**Comment by asottile** [comment]
there currently isn't an install all or uninstall all.  patches welcome though :)
