### ISSUE TITLE
How to run pre commit on diff only?

### ISSUE THREAD

**Issue by salomao-rodrigues** [pre-commit/pre-commit#380]
Is there a way to run hooks on the diff changes?
Use case would be when you're working on a big project that doesn't follow any code standards and you just want to impose linting on new code instead of refactoring the whole app in one go.

I'm only being able to run linting throughout whole files, couldn't find any documentation to achieve what I've asked.

Thanks in advance.

**Comment by asottile** [comment]
If the underlying tool supports it than yes.  In the general case though, things like flake8 and eslint operate on files. 

pre-commit is a simple proxy which determines the files to send and then calls the underlying tool with those arguments. 

I still think this is good enough for a large legacy codebase as you'll progressively improve the quality as you make commits.  Auto fixers such as autopep8 help this process a ton.  As an example, we used this tool internally to successfully enforce linting in a several million line codebase.
