### ISSUE TITLE
Support global git hooks in git v2.9

### ISSUE THREAD

**Issue by wting** [pre-commit/pre-commit#381]
From the [release notes](https://github.com/blog/2188-git-2-9-has-been-released):

>You can now specify a custom path for hooks. Git calls hook scripts to allow you to implement custom policy or actions when certain events occur. These hook scripts are found inside the .git directory of each repository, making them a pain to manage if you have a standard set of hooks for all of your repositories. Now you can store the hooks in one place and point all of the repositories at them with the new core.hooksPath config.

I'm thinking global config with repo local overrides, which solves the pain of manual syncing and updating hooks for every individual repo.

**Comment by asottile** [comment]
"solves the pain" but makes it impossible to have a reproducible state in a repository.  I don't think we'll be changing our strategy or using this feature.
