### ISSUE TITLE
recommend `pip install --user pre-commit` for Non Administrative Installation:

### ISSUE THREAD

**Issue by matkoniecz** [pre-commit/pre-commit#383]
`pip install --user pre-commit` is (AFAIK) standard way to do Non Administrative Installation, so I propose to recommed this method in http://pre-commit.com/#install (or explicitly mention that this standard method is broken by this project)

**Comment by asottile** [comment]
We much prefer virtualenv installation over user installation.  There's lots of problems with eggs and they often interfere in bizarre and strage ways that I'd rather not suggest.
