### ISSUE TITLE
add info why it is better than https://github.com/brigade/overcommit

### ISSUE THREAD

**Issue by matkoniecz** [pre-commit/pre-commit#384]
It seems a very similar project and it is no obvious whetever one is better/for different purposes.

It would be nice to mention documentaton for what purposes this project is better

**Comment by asottile** [comment]
It was mentioned explicitly at some point but perhaps that has been removed from the docs.

For example:
- http://pre-commit.com/#advanced
- Doesn't require you to install a bunch of stuff to your system (zero setup other than having pre-commit installed)
- Easy to integrate any tool (for example, you *could* run overcommit as a `pre-commit` hook)

**Comment by asottile** [comment]
I'm going to complete this in our documentation at some point, for now we'll track that progress there: https://github.com/pre-commit/pre-commit.github.io/issues/128
