### ISSUE TITLE
http://pre-commit.com/hooks.html contains entries that are not working

### ISSUE THREAD

**Issue by matkoniecz** [pre-commit/pre-commit#385]
To reproduce:

`sudo pip install pre-commit`

in repository `pre-commit install`

create file `.pre-commit-config.yaml` with

```
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: detect-aws-credentials
```

run `pre-commit run --all-files`

what results in 
````
[ERROR] `detect-aws-credentials` is not present in repository git://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

run recommended `pre-commit autoupdate` mresultin in

```
Updating git://github.com/pre-commit/pre-commit-hooks...[ERROR] `detect-aws-credentials` is not present in repository git://github.com/pre-commit/pre-commit-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

**Comment by asottile** [comment]
Ah, it really should suggest you remove the entry, run `pre-commit autoupdate`, and then add the entry back.  I guess that's not entirely clear.

The title of this ticket is false however.  If  you use a newer version (such as v0.5.1) it definitely contains that hook.

The metadata on http://pre-commit.com/hooks.html is scraped directly from the repository so it can't be wrong :P
