### ISSUE TITLE
do not recommend `pre-commit autoupdate` on failure of `pre-commit autoupdate` 

### ISSUE THREAD

**Issue by matkoniecz** [pre-commit/pre-commit#386]
It would be preferable to recommend something that has chance of fixing the problem

instruction to reproduce in #385

**Comment by asottile** [comment]
So `autoupdate` is  useful to get you into a working state, however the directions should be:

- Remove the hook, run autoupdate, and add the hook back.

**Comment by asottile** [comment]
See also: https://github.com/pre-commit/pre-commit/pull/368#issue-153987791

**Comment by asottile** [comment]
This has been released in 0.9.0
