### ISSUE TITLE
Support for commit-msg

### ISSUE THREAD

**Issue by zaps** [pre-commit/pre-commit#389]
Totally not trying to be snarky here-- the project is called _pre-commit_, after all-- but is there a reason commit-msg hooks are not supported? 

Being able to validate commit messages for appropriate issue-tracking ids, length, etc is important for a lot of us and having to put together another mechanism to deal with it or utilize another framework alongside pre-commit seems non-DRY-y.

I would put this as a "pro" for overcommit (see #384) but I'd really like to see it in pre-commit, as overcommit's performance in Windows is... subpar. (More of a ruby issue than overcommit.)

**Comment by asottile** [comment]
We're already supporting other hooks (`pre-push`) and would accept a PR if one were to make one :)

There's already a way to configure hooks to only run in specific stages (currently just `commit` or `push`: http://pre-commit.com/#confining-hooks-to-run-at-certain-stages).  There's also a way to configure hooks to always run independent of files changed `always_run`: http://pre-commit.com/#plugins

I imagine to implement `commit-msg` you'd simply need to teach pre-commit about how to make the file for it and how to call a hook with the right stuff.

**Comment by zaps** [comment]
Ok cool yeah I saw the `pre-push` option and figured there would be a similar way to "hook" into the other stages. 

If I get some time in the next few days I'll do some spelunking :microscope:

**Comment by zaps** [comment]
Ok I started a fork for these changes making some [initial progress](https://github.com/zaps/pre-commit/commit/159e04290dbff2a0d3b3af37186a60477ebeeb33) getting `commit-msg`  in on the fun. (It's totally not optimal atm because TDD 🌴 )

One question I had was, in terms of testing the additional hook stage (ie adding something like `stages: [commit-msg,push]` in `.pre-commit-config.yaml`), how is that done?

I see a dictionary-type concoction in [run_test.py](https://github.com/pre-commit/pre-commit/blob/master/tests/commands/run_test.py#L434-L452) but I'm not quite sure of what the format of it is. Can you give a quick rundown and maybe thrown in a sample line for my purposes?

Thanks!

**Comment by asottile** [comment]
You know, I'm not actually too sure about the test you linked!  It actually seems to be doing a lot of useless work and I'll probably go about factoring it out.

The tests that check the integration of the different hook types (strangely) live in tests/commands/install_uninstall_test.py (well not that strange actually, the reason they're there is in order to test that the installation is successful you kind of have to do a full integration run).  I'd probably try from that angle first?  Let me know if you need additional direction :)

**Comment by zaps** [comment]
Ok I think I'm with you now -- I'll start sticking tests for commit-msg in `install_uninstall_test.py`, do a full integration run each time and see what blows up. 

Thanks again

**Comment by peay** [comment]
@zaps have you made more progress on this? I'd be interested in `commit-msg` hooks.

**Comment by seocam** [comment]
I'm also interested in `commit-msg` hooks!

**Comment by k1-hedayati** [comment]
Looking for this too, may be switch to overcommit or other tools that support this feature
pre-commit/pre-commit-hooks/issues/193

**Comment by asottile** [comment]
I have a branch which adds `commit-msg` support: #566

**Comment by asottile** [comment]
This has been added in (just released) 0.15.4!

You can read more about it in [the documentation](http://pre-commit.com/#pre-commit-for-commit-messages).

Thanks for your patience on this :)  I've finally got some freetime to fix some of these older issues :D
