### ISSUE TITLE
Executable normalization breaks custom entry points

### ISSUE THREAD

**Issue by justinmayer** [pre-commit/pre-commit#390]
The executable normalization methods introduced in 82369fd appear to have broken our custom entry point, resulting in unexpected "Executable not found" errors.

Contents of our `.pre-commit-config.yaml` file:

    - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    - id: trailing-whitespace
    - id: debug-statements
    - id: flake8
        name: Flake8 on commit diff
        description: This hook limits Flake8 checks to changed lines of code.
        entry: git diff HEAD^ | flake8 --diff

When using version 0.7.6, the latter custom hook does precisely what we want: only changed lines of code are checked for PyCodeStyle violations.

But subsequent 0.8.x versions produce the following error:

    Executable `git diff HEAD^ | flake8 --diff` not found

Is there another way we should be handling things in `.pre-commit-config.yaml` to account for the aforementioned executable parsing changes made in 0.8.x? Or something else we should be doing to achieve the desired result?

If not, could perhaps the entry point / executable parsing logic be modified such that only the first "word" is analyzed, with the rest ignored? (In this case, `git` would be found in $PATH, so no error would result.)

Or perhaps a configuration setting that skips the executable parsing logic would be the best solution?

**Comment by asottile** [comment]
You'll want to instead use bash -c '...' if you need a shell

**Comment by justinmayer** [comment]
Thanks for the quick response, Anthony. I'm not sure I understand, however. I changed the entry point above to:

    entry: bash -c 'git diff HEAD^ | flake8 --diff'

... and then ran `pre-commit run --allow-unstaged-config --no-stash` using version 0.8.2 with the following result:

    Flake8 on commit diff............................................................................................Failed
    hookid: flake8
    
    Executable `bash -c 'git diff HEAD^ | flake8 --diff'` not found

If I revert via `pip uninstall -y pre-commit; pip install pre-commit==0.7.6` and run the same command again, I get no errors:

    Flake8 on commit diff............................................................................................Passed

What am I missing?

**Comment by asottile** [comment]
Ah, try the edited suggestion: ^^^

**Comment by justinmayer** [comment]
That did the trick. With that revised configuration, version 0.8.2 produces the same result as 0.7.6.

Once again, thank you for the very quick responses!

**Comment by asottile** [comment]
No problem! Thanks for the report @justinmayer!
