### ISSUE TITLE
Idea: Allow searching of hook directory rather than cwd

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#393]
I don't seem to be able to reference the hook directory when passing in arguments, which makes things like passing in config files stored in the hook repo hard.

It would be nice to be able to do so

similar to `{toxinidir}`

```
arguments: ['-c', '{hookdir}/my-config.js']
```

(would be happy to take this ticket if sounds ok)

**Comment by asottile** [comment]
The hooks are guaranteed to run in the root of the repository, `{hookdir}` would always be substituted as `.`.  I don't really want to invent or maintain a substitution metalanguage either so I'm -1.  We'll see what others say.

**Comment by chriskuehl** [comment]
Hooks run in the root of the repo you're testing, but he wants to refer to files in the hook repo.

**Comment by asottile** [comment]
Well then.  hookdir definitely isn't a workable name.  In python you can figure this out by using `__file__` or `sys.executable` or such,  I'm sure there's an equivalent for node.

Can you provide a concrete usecase?

**Comment by magicmark** [comment]
There is yes, but it means having to wrap executables in a script to do so and be able to pass args

I'm currently trying to pass in a config file for stylelint that is stored in the hook repo. stylelint is searching the consuming project dir but it doesn't exist there. I can't provide an absolute path because that will obviously change.

wrapping stylelint in a script just to be able to pass args seems kinda hacky?

**Comment by asottile** [comment]
I think what you actually want is to write a wrapping script if you want to guarantee your config gets loaded.  If you do it via `args:` and a consumer sets `args:` and forgets to add back your config then you are back to the vanilla thing (probably confusingly!).

**Comment by magicmark** [comment]
I mean I guess you could say the same about any arbitrary args which could currently be set in `hooks.yaml` that could be accidentally overridden.

If you're not comfortable with this behavior, then shouldn't we remove the ability to set hooks in `hooks.yaml` altogether?

**Comment by asottile** [comment]
No, I think your situation is different. 

Usually these are used for "default" arguments, bit you want to use this configuration for "always" arguments

**Comment by magicmark** [comment]
Well kinda; a consumer might want to override the config file with their own rules for whatever reason, making being able to set it in `args` desirable.

(This would probably be the biggest reason a consumer would want to overwrite `args` anyway)

That said, I certainly see your argument as to why we wouldn't want to do this, due to the possibility of accidentally losing the config loading. Still, I don't know if the cons outweigh the pros here, so I'm happy to go with however you and others feel :)
