### ISSUE TITLE
Supported CPython versions, installation methods?

### ISSUE THREAD

**Issue by sanmai-NL** [pre-commit/pre-commit#395]
First of all, what versions of Python are supported?
`pre-commit` is being tested against a bunch of Python versions [here](https://github.com/pre-commit/pre-commit/blob/ea05189c28084e42014b20eae3a1130ea14c9d93/.travis.yml#L4-L11). Assuming that declares the supported Python versions, any reason to keep supporting Python 2.6?

In current Python 2.7.z and 3.y, `pip` should be available. This brings me to my main question.
[The ‘Non-Administrative Installation’ and ‘System Level Install’ sections in the manual](http://pre-commit.com/#install) are not conventional as they stand. Why not these instructions instead:

```sh
python -m 'ensurepip' --user
python -m 'pip' --user 'pre-commit'
```

The current instructions could be construed as a security risk (`http://` scheme, fetch of a script from your website instead of from a curated package index) and the extra customer installer script `install.local` requires maintenance.

**Comment by asottile** [comment]
This as well as the list you've found show the supported versions: https://github.com/pre-commit/pre-commit/blob/ea05189c28084e42014b20eae3a1130ea14c9d93/setup.py#L20

As for installation instructions there's several reasons:
- `--user` installations are very often buggy
- pip is not always present on debian (which chooses intentionally and compliantly to not bundle pip)
- `--user` is not a system wide installation
- our strongest suggestion is to install it in a virtualenv
- it supports non-python use cases and shops so dealing with virtualenv is not always an option
- the script maintenance is a valid point but it already works and requires nothing to update for newer versions.  The script is a simple virtualenv bootstrap that uses secure pypi installation 
- the point about http is valid (and brought up somewhere but I'm on a phone so difficult to find)
- as for 2.6, please contribute to the discussion in #263

**Comment by asottile** [comment]
Here's the issue to watch for http : https://github.com/isaacs/github/issues/156

**Comment by sanmai-NL** [comment]
* Can you share some information? How are Python user bases buggy?
* Okay, if `pip` isn't accessible at all even when using `ensurepip`, then good point. But in that case the unconventional  instructions should be clearly reserved for Debian-based Linux OS'es.
* True, for system-wide installations you would of course drop the `--user`.
* Could you explain your comment on non-Python use-cases and shops? How is that related to virtualenv? 

If Debian sabotages `pip`, why wouldn't they sabotage virtualenv? What about standard Python venvs? Are you sure using `pip install --user` is impossible on Debian?

**Comment by asottile** [comment]
Python will put user installs on the python path even in virtual environments.  You can imagine the hundred or so failure modes this invites  

Say I'm a node shop. I don't know things about the python ecosystem or pip or virtualenv.  If there's an option which doesn't require us to understand these things in going to pick it (the fewer moving parts the better).

Debian provides python-pip and python-virtualenv packages but requiring them to be installed makes instalation more difficult.

As it stands,  the only dependency that the install local script has is python itself.  It creates a virtualenv in the home directory and doesn't interfere with other python environments.

**Comment by sanmai-NL** [comment]
Okay, interesting note about the user site-packages dir conflicting with the Python path. I hope you're fine with discussing this further to at least achieve a common understanding.

Based on my current knowledge, I think adding the user site-packages dir to the Python path is a fine design choice for non-isolated virtual environments. Why would it be a problem? Virtualenvs are a hack actually. But most importantly, I could not reproduce this issue in an isolated venv, didn't test it in a non-isolated one.

```sh
python -m venv /tmp/myvenv
. /tmp/myvenv/bin/activate
(myvenv) python -c 'from sys import path; print(path)'
```
```python
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '/usr/lib/python3.5/lib-dynload', '/tmp/myvenv/lib/python3.5/site-packages']
```

Really, I think the Node.js shop argument is not very good. I do not see why it would be more difficult or unattractive to issue one or two very plain command line statements vs. one (slightly more complex). Also, the `curl` dependency of the current instructions won't be available on Windows by default and needs to be installed on the CI host.

It's still okay if you think asking to install one or two OS packages on Debian makes things too difficult, but didn't I propose to reserve the special instructions (meaning, even if just the current ones) for Debian? At least, that would not suggest to users that `pre-commit` should always be installed in the unconventional (in my view, unattractive for the reasons stated) way. Also, `npm` as known by the Node.js peeps works in the same way, also installing deps under the user home directory. The same is true for many other language impl dep managers. And on a final note, I'd say `pip`  itself is fairly well-known by anyone who ever did anything with CPython, even for some end-user use cases.

I agree that it's attractive to just fire off a script and that sorts out everything for installation. The problem is, this fails in a bare Alpine Linux Docker container, i.e. a common CI host, with cryptic error messages. That's related to #396, and not a problem per se. What I am getting at is that the benefits of keeping your script/custom installation commands that you feel do not bear out in practice for me.
