### ISSUE TITLE
Stashed changes lost if hook fails with non-UTF-8 diff containing trailing whitespace

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#397]
Hi,

A colleague almost lost all the changes she was working on after launching a `git commit` (with zero file added) and `pre-commit` crashing without restoring its [patch](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/staged_files_only.py#L15).

Here is the terminal message she got:

```
[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
An unexpected error has occurred: CalledProcessError: Command: ['git', 'apply', 'C:\\Users\\toto\\.pre-commit\\patch1471341002']
```

This seems very similar to a past solved issue:
https://github.com/pre-commit/pre-commit/issues/176

I think it had to do with CRLF conversion.
I'm going to try to reproduce this.

**Comment by asottile** [comment]
Strange!  In the worst case the patch files remain around. Looking forward to the reproduction. Going to tag windows for now

**Comment by Lucas-C** [comment]
Follow-up in https://github.com/pre-commit/pre-commit-hooks/issues/134

**Comment by asottile** [comment]
There's actually two bugs here it seems, I'm going to reopen this.

I think this is the actual actionable one, though it's not entirely clear why it's happening yet!
