### ISSUE TITLE
Warn on useless `exclude:`s during `--all-files`

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#405]
Some of our repositories have some copy-paste pre-commit configs which end up with problems like https://github.com/Yelp/undebt/pull/12#discussion-diff-76108499

It'd be nice to surface these issues to the end-user in a nice way

**Comment by chriskuehl** [comment]
+1 this would be great, though I imagine we can only alert if the regex doesn't match anything at all.

Meaning a common thing like:

```yaml
exclude: ^(file_that_exists|file_that_does_not_exist)\.py$
```

wouldn't really benefit from this. Unless you have some magic way to interpret regexes.

**Comment by asottile** [comment]
I've always wanted to implement a "regex coverage" routine, but I don't think this is the time :) (especially since python regexes are complicated).  I was mainly aiming for the terribly-wrong-doesn't-cover-anything case

**Comment by chriskuehl** [comment]
We'd likely also want to differentiate between `exclude` being defined in the hook repo and in the project repo (as an override). For example, the `replace-tabs` hook does something like `exclude: (Makefile|\.mk)$` which is useful, but we wouldn't want that to error in every project.

**Comment by asottile** [comment]
via https://github.com/pre-commit/pre-commit/pull/643
