### ISSUE TITLE
Could not find valid gem __fake_gem

### ISSUE THREAD

**Issue by rayward** [pre-commit/pre-commit#418]
I'm having trouble getting the hooks installed on OSX:

```
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: (u'/bin/bash', u'/Users/ray.ward/.rbenv/shims/gem', 'install', '--no-ri', '--no-rdoc', '__fake_gem-0.gem')
Return code: 2
Expected return code: 0
Output: (none)
Errors:
    ERROR:  Could not find a valid gem '__fake_gem-0.gem' (>= 0) in any repository
    ERROR:  Possible alternatives: fake_gem, fake-gem, fake_gem_push


Check the log at ~/.pre-commit/pre-commit.log
$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
$ gem -v
2.2.3
$ pre-commit -V
pre-commit 0.9.1
$ uname -a
Darwin SYD-MBP-WARD 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

any ideas?

**Comment by asottile** [comment]
Interesting.  Could you provide `env | grep -Ei '(ruby|rvm|rbenv|gem)'` as well as the `.pre-commit-config.yaml`

**Comment by rayward** [comment]
```
$ env | grep -Ei '(ruby|rvm|rbenv|gem)'
PATH=/Users/ray.ward/.pyenv/shims:/Users/ray.ward/google-cloud-sdk/bin:/Projects/go/bin:/usr/local/sbin:/Users/ray.ward/.rbenv/shims:/Users/ray.ward/.rbenv/bin:/usr/local/bin:/Users/ray.ward/.nvm/versions/node/v4.5.0/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/share/npm/bin
RBENV_SHELL=bash
```

```
-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: 4e9937d4d0ccbea37ae2a9a414a2b0cee58657fa
    hooks:
    -   id: puppet-lint
    -   id: puppet-validate
    -   id: erb-validate
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 09d1747840bfb1457e9b8876b4c1f577d00a2a37
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: trailing-whitespace
```

**Comment by asottile** [comment]
It seems to be escaping the environment we set up in ~/.pre-commit which is a bit strange.  I'm trying to reproduce it locally and having some trouble :S

I think as a workaround you can set `language_version: 2.2.3` for each of the hooks (http://pre-commit.com for some examples) which may force it to do the right thing?  Still looking into how to reproduce this :)

**Comment by asottile** [comment]
Can you also provide `rbenv --version`?

**Comment by rayward** [comment]
```
$ rbenv --version
rbenv 1.0.0
```

installed via brew

**Comment by asottile** [comment]
Alright, this is probably an osx / brew specific bug since I can't reproduce in linux (with similar versions and same `PATH` setup).  I'll see if I can reproduce this when I have my mac in front of me.

**Comment by rayward** [comment]
Cheers!

**Comment by asottile** [comment]
Still can't seem to reproduce it from my end but I think I can write a patch that'll make this _just work_, let me create a branch, would you be able to try out a dev branch for me?

I can't seem to get openssl and gems to cooperate in osx so it's very difficult to reproduce :)

**Comment by rayward** [comment]
Yeh I'm happy to try out a dev branch.

Btw see this if you have certificate issues with rubygems - http://guides.rubygems.org/ssl-certificate-update/

**Comment by asottile** [comment]
alright, the branch is [gem_full_path](https://github.com/pre-commit/pre-commit/compare/gem_full_path?expand=1), I believe you should be able to install it with `pip install git+git://github.com/pre-commit/pre-commit@gem_full_path`

**Comment by asottile** [comment]
Any luck with that? ^

**Comment by rayward** [comment]
No luck unfortunately:

```
[INFO] Installing environment for https://github.com/chriskuehl/puppet-pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: (u'/bin/bash', u'/Users/ray.ward/.rbenv/shims/gem', 'install', '--no-ri', '--no-rdoc', '/Users/ray.ward/.pre-commit/repod4B22P/__fake_gem-0.gem')
Return code: 2
Expected return code: 0
Output: (none)
Errors:
    ERROR:  Could not find a valid gem '/Users/ray.ward/.pre-commit/repod4B22P/__fake_gem-0.gem' (>= 0) in any repository
```

**Comment by asottile** [comment]
I'm perplexed!  Do you have a .gemrc maybe?  Could you post that?

**Comment by asottile** [comment]
@rayward do you have a .gemrc? ^

**Comment by rayward** [comment]
@asottile 

```
$ cat ~/.gemrc
gem: --no-ri --no-rdoc --remote
```

**Comment by asottile** [comment]
ooh that's very helpful! I bet that `--remote` is what's throwing this off.  Let me see if I can figure out a way to avoid gemrc

**Comment by rayward** [comment]
I'm not sure why I have `--remote` in the gemrc...

I removed it and everything is working perfectly now! Woo!

**Comment by asottile** [comment]
Leaving this as documentation, I don't think there's terribly much I can do about this since `gem` only added `--norc` in a relatively recent release (it's not available for instance in the version that ships with xenial).

Thanks for the debugging information!

**Comment by rayward** [comment]
No worries, thanks for all your help!
