### ISSUE TITLE
Do not run hooks on unstaged files when commiting

### ISSUE THREAD

**Issue by psafont** [pre-commit/pre-commit#424]
In the documentation it says:
>pre-commit only runs on the staged contents of files by temporarily saving the contents of your files at commit time and stashing the unstaged changes while running hooks.

This is true when I use the command `pre-commit run` unstaged files do not get processed.

However it is not the case when I commit to repos (`git commit`): the unstaged files get processed, leading failed the tests when the staged files pass the tests.

This is because an completely different bash script is generated for hooks/pre-commit, instead of just executing `pre-commit run` with some parameters to match the configuration. (which is what I'm manually replacing the hook with, for commodity)

Are there any reasons as to why it's done this way? To me it seems unintuitive to do it both ways, creating a difference of functionality

**Comment by asottile** [comment]
<3 If there's anything that can be clarified in the documentation let me know!

**Comment by psafont** [comment]
Nope, I was just being a bug dummy, thanks!
