### ISSUE TITLE
Support for Go hooks

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#430]
Hi,

I'd love to make a pre-commit hook to check Makefiles using https://github.com/mrtazz/checkmake.

Do you think we could add support for Go hooks ?

**Comment by asottile** [comment]
I started work on this at one point but didn't understand the ecosystem well enough. I definitely  think it is doable (via go get or whatever the cool new way to install dependencies is now).

**Comment by asottile** [comment]
via #473

**Comment by Lucas-C** [comment]
Great ! Thanks :)
Would you be Ok to add support for additionnal deps, in order to `go get github.com/mrtazz/checkmake` for example ?

**Comment by asottile** [comment]
Yep, I didn't quite know how to implement them but it should be as easy as `for dep in additional_deps: cmd_output('go', 'get', dep, GOPATH=...)`

**Comment by Lucas-C** [comment]
For info : https://github.com/Lucas-C/pre-commit-hooks-go
