### ISSUE TITLE
Feature request: pre-commit run --sha

### ISSUE THREAD

**Issue by snakescott** [pre-commit/pre-commit#431]
I'd like to be able to run pre-commit on a past commit. My use case is two stage CI which I think is fairly common (CircleCI, Gerrit, Travis etc):

1) user pushes commit to code host
2) CI system is monitoring code host, sees new commit, checks out commit, runs tests, leaves comment on code host
3) User can submit commit to master once CI has left a message that tests pass
4) After user submits, full integration build starts

In step (2), all that I want to run is```pre-commit run --sha $SHA```, which is substantially faster than ```pre-commit run --all-files```. ```pre-commit run --all-files``` is still run in step (4).

**Comment by asottile** [comment]
This can be done with: `git diff --name-only "$SHA" "$SHA^" | xargs pre-commit run --files`

(there's probably a more clever way than `$SHA` `$SHA^` but I'm forgetting my git fu at the moment :D)

**Comment by snakescott** [comment]
Ah, I think that seems right, thanks!

Maybe ```git diff-tree --no-commit-id --name-only -r $SHA``` is better?
http://stackoverflow.com/questions/424071/how-to-list-all-the-files-in-a-commit

Would it make sense to add this to the "Usage in Continuous Integration"  docs?

If so, should I submit a PR to https://github.com/pre-commit/pre-commit.github.io ?

**Comment by asottile** [comment]
Yeah I'm actually surprised there's nothing in the docs which mentions `--files`!  It might make sense in that section or perhaps another section for ad-hoc usage.  Either way works, and we're definitely open to new PRs :) (and yes that is the correct repository)

**Comment by snakescott** [comment]
Thanks for the speedy response, @asottile! pre-commit is amazing, I only wish I had found it earlier :)

**Comment by asottile** [comment]
<3
