### ISSUE TITLE
Run when submodule changes

### ISSUE THREAD

**Issue by samskiter** [pre-commit/pre-commit#440]
I've seen some previous issues about submodules, but I can't work our how they were resolved or find any docs related to submodules.

Could you clarify how I can run a hook when a submodule has changed please?

**Comment by asottile** [comment]
They have yet to be resolved, currently if the submodule path matches the `files:` pattern that path will be passed to hooks.

The plan is to make tags which allow more broad filtering of files passed to hooks.  This is still a work in progress: https://github.com/pre-commit/pre-commit/pull/329

For now, the easiest way to accomplish what you want is something like this:

```yaml
# ...
-   id: ...
    # match all files
    files: ''
```

And then inside the hook, filter that list down to the ones you actually want (through either a check that it is a git directory, or by inspecting `git diff --raw` such as is done here: https://github.com/pre-commit/pre-commit-hooks/blob/77a7bba2f93cfe1205fc7167ef8379cbc6fcbb37/pre_commit_hooks/forbid_new_submodules.py#L11-L20

**Comment by asottile** [comment]
I think the other issue is https://github.com/pre-commit/pre-commit/issues/191#issuecomment-113249998

**Comment by samskiter** [comment]
Thanks! I just got it working, I actually had another issue 👍
