### ISSUE TITLE
Question: python hook versions and install_requires

### ISSUE THREAD

**Issue by snakescott** [pre-commit/pre-commit#445]
I see in the docs that individual hooks can be configured to have entry points, language and language_version. install_requires is global, though. Does pre-commit create a virtualenv for each python hook (pointing to the appropriate python binary)? Is the repo setup.py `pip install -e` ed into each one?

If so this would mean that a mypy hook probably could not co-exist with a python2 only hook, because mypy-lang is python 3 only.

**Comment by asottile** [comment]
Each (repository, language, language_version) gets its own environment.

They are stored per repository, and the environments are named after their language + language_version.

- https://github.com/pre-commit/pre-commit/blob/da3458cd25392679094911d9d8a3862e1a4bf884/pre_commit/languages/python.py#L16
- https://github.com/pre-commit/pre-commit/blob/da3458cd25392679094911d9d8a3862e1a4bf884/pre_commit/languages/helpers.py#L10-L14
- https://github.com/pre-commit/pre-commit/blob/da3458cd25392679094911d9d8a3862e1a4bf884/pre_commit/languages/python.py#L35-L38

**Comment by asottile** [comment]
So you could have a python2 hook and a python3 hook in the same repository and they would not clash with each other

**Comment by snakescott** [comment]
Does this assume/require that dependencies listed in install_requires are compatible with all (language, language_version) pairs in all hooks in the repository?

**Comment by snakescott** [comment]
for example if I have a python2.7 hook (e.g., say it contains `print x`) and my install_requires for some reason includes mypy_lang in install_requires (`pip install mypy_lang` on a 2.7 virtualenv will fail), what happens?

**Comment by asottile** [comment]
It would probably fail to set up the python2.7 virtualenv due to the dependency on `mypy_lang`, you could however make that a conditional requirement:

```python
extras_require={':python_version!="2.7"': ['mypy_lang']},
```

(or split it into multiple repositories)

Note that you can try it out and see what happens without actually publishing a repository: http://pre-commit.com/#developing-hooks-interactively

**Comment by snakescott** [comment]
extras_require seems like just the thing! Today I learned, thanks!

Googling based on that keyword turned up the following which might be good context for anyone else who has this question.
https://hynek.me/articles/conditional-python-dependencies/
