### ISSUE TITLE
question: global/indivisible hooks?

### ISSUE THREAD

**Issue by snakescott** [pre-commit/pre-commit#446]
Many pre-commit hooks are appropriate to run per file -- flake8 and autopep8 are great examples.

Others, for example mypy and cyclic import detection, need to be run on an entire repository to work. In these cases

* Changes to one file can affect other files
* splitting a check into independent subchecks with xargs is inappropriate

Any thoughts on how to work with these in pre-commit? Pre-commit features that are helpful when working with these hooks include:
* environment management
* common configuration / configuration centralization
* include/exclude configuration

Thanks!

**Comment by asottile** [comment]
There's the `always_run` option which'll always invoke the hook and not pass filenames.  You can then configure the arguments that you want to run this hook with.  Does this satisfy that? http://pre-commit.com/#new-hooks

**Comment by snakescott** [comment]
yeah, think so. I'm interested in streamlining exclude/include but I'll dig in on that separately (and don't think it is really a pre-commit issue).
