### ISSUE TITLE
PCRE passes even if ggrep is not installed on OS X

### ISSUE THREAD

**Issue by cmer** [pre-commit/pre-commit#447]
I was scratching my head because some hooks were passing even though they should clearly have failed.

When running `run --all-files` with the `--verbose` flag, I noticed why this was happening:

````
[do_not_commit] Block if "DO NOT COMMIT" is found..................................................................Passed
hookid: do_not_commit

Executable `ggrep` not found
````

It seems like the correct behaviour would be to fail and warn user to install `ggrep`?

For the record, I installed `ggrep` as follow: `brew install homebrew/dupes/grep`, and the hooks now fail as expected.

**Comment by asottile** [comment]
Thanks for the report!  I've confirmed the root cause :)

**Comment by asottile** [comment]
This fix is in the (just released) 0.9.4 release.

**Comment by cmer** [comment]
It seems like this fix no longer works on a brand new Sierra install. `egrep` should be used instead of `ggrep` and comes installed with the OS.

**Comment by asottile** [comment]
@cmer  can you elaborate?  `egrep` is usually an alias for `grep -E` (which is different from `grep -P`)

**Comment by cmer** [comment]
My bad. You’re right. `egrep` is actually NOT the same as `ggrep`. Now that ggrep is no longer available in Homebrew, what should we use on macOS?

**Comment by cmer** [comment]
And I'm wrong again. Installing ggrep now worked. Sorry about this. I need a nap.

**Comment by asottile** [comment]
:D cheers!
