### ISSUE TITLE
[Question] How can I configure pre-commit globally for all projects?

### ISSUE THREAD

**Issue by lavish205** [pre-commit/pre-commit#450]

**Comment by asottile** [comment]
There's a feature added in git 2.9 to have "global" hooks: https://git-scm.com/docs/githooks

But it doesn't quite fit the design pattern that we have: https://github.com/pre-commit/pre-commit/issues/381

Each repository should configure the hooks it needs through .pre-commit-config.yaml, you *could* copy the file pre-commit creates into a directory and configure it via `core.hooksPath` as above, but you'll still need to place a file per repository (and then pre-commit will likely know less about your repository).  It might not even work, it hasn't been attempted.

The supported path for setting up pre-commit in a repository is: create and check in a `.pre-commit-config.yaml` and run `pre-commit install`

**Comment by ssbarnea** [comment]
@asottile I think we should reconsider this question as I have a serious use-case: I want to enforce a checking of all git commit messages to assure that: summary is <50 chars, each line is <72 and that it does not have spelling mistakes. 

I have hundreds of git repos and most of them do not have pre-commit but I would like to benefit from having my user-level hooks regardless what extra hooks are inside the repository.

Do you know a way to make this work?

**Comment by lavish205** [comment]
@ssbarnea I've the same use case, in our organization we have multiple python based projects and its very hard to maintain `yaml` file in each repo as each file is doing the same thing.
And for a single change I have to update all the repos.

**Comment by ssbarnea** [comment]
@lavish205 Maybe not exactly the same use case because I do contribute to various repositories managed by various organisations and I just want to have my own additional set of check made on my commits (just to assure I am consistent in following my self imposed rules).

A centralised pre-commit repository for a specific organisation address maintenance of the hooks for this group, still my use case is different. This is not to say that one use case is more important than another, there are just two aspects similar but different. 

I hope we will be able to find and document a solution for both cases.

**Comment by asottile** [comment]
(going to try and address both things above, some of the things I say apply to both, some to one, and some to the other (some to neither! oops!) 😆)

ok, here's a few ways you _could_ do this...

Note again that client side hooks are intended as a developer tool and not as a stopgap, you really need some other tool to actually _enforce_ your checks (whether that's CI, a server-side `pre-receive`, or however else you actually want to do it).

But first, a comment about micro vs. macro repositories.  If you find yourself with hundreds of repositories (in theory to avoid a monorepo / monolith / etc.) you're really doing yourself a disservice if you don't have a way of applying a mass change in an automated way.  This was incredibly frustrating for myself when I as a young padawan worked at a company that switched from a single monolith repository to a heavily service oriented pattern.  My thought process went something like: "yay! freedom! agility!.... wait, everything is bitrot and version skew now".  Fortunately, there's usually good solutions to these types of things -- in my case I decided to build a tool which acted as a distributed automated changeset applier which (again) made sweeping changes painless.  (_an aside_: personally I'm _pro_ micro-repos and _anti_ monorepos, but your mileage may vary).  This tool for the longest time lived entirely in closed source and was site specific -- but fear not, I've rewritten it from scratch and it works great for my use-cases: [asottile/all-repos](https://github.com/asottile/all-repos).  all-repos actually comes out-of-the-box with tools to [help manage `pre-commit`](https://github.com/asottile/all-repos#example-autofixer) as samples for autofixers.  I also have a running curation of rewrites I've done on my public repositories here: [asottile/all-repos-incantations](https://github.com/asottile/all-repos-incantations).

ok, advertising over -- let's get down to business :)

A few things to get out of the way first though, these are mostly design decisions taken by pre-commit that I'm not willing to change (you can find similar texts in the rest of the issue tracker but I'll rewrite them here).
- `pre-commit` _must_ have a configuration to run.  pre-commit itself is a framework and will not grow opinions about what hooks you should use or how you should use them.  If you want to run it, you need to have some sort of configuration :)
- `pre-commit` will not directly support mutability in configuration (this includes referencing a centralized repository).  This causes lots of issues with repeatability and maintenance in general.  This was an early design decision after seeing the pain caused at scale when a linter changes behaviour and suddenly every repository's _master_ branch is broken.
- One of `pre-commit`'s goals is to make local development _better_ by providing feedback _as early as possible_.  If you're able to run a tool locally before pushing it off to CI or a `pre-receive` hook and easily verify / validate the changes (even automatically!) you're going to be much happier.  Again, this was an early design decision around the frustrations of server-side hooks that were confusing, slow, and sometimes difficult to reproduce locally.  This is why pre-commit (and the current `git` hooks it targets) are aimed at _client_ hooks.

And now let's get on to the ways you can hack this behaviour on (disclaimer: while I may disagree with some of these ideas, they do currently work) :)

- [nested pre-commit configurations](https://github.com/pre-commit/pre-commit/issues/731#issuecomment-376945745)
- nothing is stopping `.pre-commit-config.yaml` from being a symlink! (if you control all the host machines you could presumably "puppet out" a configuration to a well known location and check in a symlink to it
- on the topic of symlinks,  I've seen some repositories maintain their shared configuration in a centralized repository added as a submodule and then symlinks into that (you'd still have the problem of _updating_ that submodule, but that's easy to automate).
- specifically for _user_ specific hooks, you could take advantage of the ["migration mode"](https://pre-commit.com/#running-in-migration-mode) for pre-commit (the docs don't discuss the implementation details but they're not changing any time soon: `pre-commit` will [invoke a hook by the name of `$HOOK_TYPE.legacy`](https://github.com/pre-commit/pre-commit/blob/259ef9e53041b43e746da5b2b1fe5ca9020d70fe/pre_commit/resources/hook-tmpl#L54-L59) if it exists.  With this you could set up a shell script that invokes `pre-commit run --config ~/my-config.yaml` or some sort.
- You could install your own shell script period and not use `pre-commit install` and use the same idea.
- If you control the server and can install server-side hooks, pre-commit supports [`--origin` and `--source`](https://pre-commit.com/#pre-commit-run) for running against commit ranges

These are just a few ideas, sorry if this is rambly and incomplete (have to run now!)

**Comment by varac** [comment]
Ftr, this is how I use a global pre-commit hook:

I configured git to use a centralized git hooks dir:

    git config --global core.hooksPath ~/.config/git/hooks/

there, I use the following file as pre-commit-hook (`~/.config/git/hooks/pre-commit`), which iterates through most of the hooks provided by `/pre-commit`:

```
#!/bin/bash

set -euo pipefail

PLUGINS_BLACKLIST=(__init__.py autopep8_wrapper.py detect_aws_credentials.py forbid_new_submodules.py. no_commit_to_branch.py util.py)
stdin=$(cat /dev/stdin)

echo "${stdin}"

function call_hook () {
  echo "Executing $i".
  echo "${stdin}" | python3 "$1"
}

cd /home/varac/projects/git/pre-commit-hooks/pre_commit_hooks/

for i in *; do
  if ! [[ "${PLUGINS_BLACKLIST[*]}" =~ $i ]]; then
    call_hook "$i"
  fi
done
```

I know this is not how `pre-commit` is meant to get used, and it's kind of quick an dirty, but it works for me, and it might give an idea how to do this for @lavish205 and @ssbarnea.

**Comment by richard-senior** [comment]
is this the latest on the situation as of May 2020?
There is no way of having a single central .pre-commit-config.yaml file that will be used for all
repositories without the need to copy it into the root of the repository?

I understand the ideology behind it, but it might be nice to have a totally non-invasive solution?

**Comment by ssbarnea** [comment]
I think is still a valid question with no easy answers but I would love to see an option like:
```
inherit-from: http://...
```

An option like this would allow those wanting to use a centralized file and still allow them to override any entry from the parent, something that sooner or later may be needed as is not possible to migrate all repos at the same speed, some may need a temporary ignore.

**Comment by richard-senior** [comment]
I had a quick look in the code at where the error message is thrown if the yaml config file doesn't exist.
It would be pretty easy to add an 'else' in there to allow for a global config file to be specified?

**Comment by asottile** [comment]
the message above still stands, a feature implementing inclusion or central management will not be accepted
