### ISSUE TITLE
Support for SwiftPM packages

### ISSUE THREAD

**Issue by benasher44** [pre-commit/pre-commit#451]
[SwiftLint](/Realm/SwiftLint) is a great example of a Swift-based linter that has support for [SwiftPM](/apple/swift-package-manager). It'd be great if pre-commit had support to pull down a repo that has a Package.swift, run `swift build`, and install the specified targets to be used as hooks.

**Comment by asottile** [comment]
This would be great, should be as easy as implementing one of these for swift: https://github.com/pre-commit/pre-commit/blob/8837cfa7ffcc419216d4e01392cee0f1ceee9c88/pre_commit/languages/python.py

The interface is here: https://github.com/pre-commit/pre-commit/blob/8837cfa7ffcc419216d4e01392cee0f1ceee9c88/pre_commit/languages/all.py

Want to take a first stab at it?

**Comment by benasher44** [comment]
Maybe! I was hoping to just get it filed and labeled for now. I'm pretty swamped atm, so anyone else is welcome to pick it up.

**Comment by benasher44** [comment]
@asottile I've started work on this. I have SwiftPM packages building locally, but there's more work to be done to fully test with SwiftLint before I get a PR up. I'll keep ya posted!

**Comment by asottile** [comment]
Via #467 -- available in 0.11.0
