### ISSUE TITLE
force use of https instead of git

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#453]
is there anyway you ppl can force use of https://xxxxx.git instead of git://xxxxx.git

On my system it complained something about unable to download via git://. I managed to workaround it by forcing git config to replace to git:// to https but i guess its better if you ppl use https

**Comment by asottile** [comment]
Ah yes, the git url in the configuration can be anything that git understands and can clone from.  This includes https:// urls, git:// urls, ssh urls (`git@...`), even local paths.  It's really up to whatever consuming repository to pick the url -- the framework doesn't actually care or enforce what url scheme you use (it just runs git clone).
