### ISSUE TITLE
How to create two roules for exclude

### ISSUE THREAD

**Issue by istommao** [pre-commit/pre-commit#454]

**Comment by asottile** [comment]
Exclude takes a regex.  Simply combine the two things you want to exclude with a |:

```yaml 
    exclude: '^(path/1|other/path2)$'
```

**Comment by istommao** [comment]
exclude: '^(path/1|other/path2)$' can't match my roules

exclude: '[migrations/|fabfile.py]' i found this work for me

**Comment by asottile** [comment]
square brackets are character classes (probably not what you want).  You're excluding for instance anything which contains the character m

**Comment by istommao** [comment]
I see! i want exlucde all migrations folder and fabfile.py, how can i do it?

**Comment by asottile** [comment]
I believe this'll do that:

```yaml
    exclude: '(^migrations/|fabfile.py$)'
```

(note that I assumed migrations is in the root, if that's not the case, remove the `^`)

**Comment by istommao** [comment]
I see thinks a lot
