### ISSUE TITLE
Guidance on symlinking to linter configs

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#506]
Hooks can be used to distribute shared linter configs

It would also be nice to have the linter config in the repo directory though so that editors can pick it up

Given that pre-commit installs hooks to a non-deterministic directory, there's not a good way of checking in a symlink to do this

Any thoughts on how to achieve this?

**Comment by asottile** [comment]
See https://github.com/pre-commit/pre-commit/issues/393#issuecomment-239503737
