### ISSUE TITLE
Allow better pre-push interaction with git-lfs

### ISSUE THREAD

**Issue by chbndrhnns** [pre-commit/pre-commit#509]
If I have `pre-push` checks in place and install git-lfs before precommit, I receive the message

```
Running in migration mode with existing hooks at /Users/****/.git/hooks/pre-push.legacy
Use -f to use only pre-commit.
```

If I do git lfs update after precommit is installed, i receive

```
Hook already exists: pre-push

#!/usr/bin/env bash
# This is a randomish md5 to identify this script
# 138fd403232d2ddd5efb44317e38bf03

pushd `dirname $0` > /dev/null
HERE=`pwd`
popd > /dev/null

retv=0
args=""

ENV_PYTHON='/Users/****in/python2.7'
SKIP_ON_MISSING_CONF=false

which pre-commit >& /dev/null
WHICH_RETV=$?
"$ENV_PYTHON" -c 'import pre_commit.main' >& /dev/null
ENV_PYTHON_RETV=$?
python -c 'import pre_commit.main' >& /dev/null
PYTHON_RETV=$?


if ((
        (WHICH_RETV != 0) &&
        (ENV_PYTHON_RETV != 0) &&
        (PYTHON_RETV != 0)
)); then
    echo '`pre-push` not found.  Did you forget to activate your virtualenv?'
    exit 1
fi


# Run the legacy pre-commit if it exists
if [ -x "$HERE"/pre-push.legacy ]; then
    "$HERE"/pre-push.legacy
    if [ $? -ne 0 ]; then
        retv=1
    fi
fi

CONF_FILE=$(git rev-parse --show-toplevel)"/.pre-commit-config.yaml"
if [ ! -f $CONF_FILE  ]; then
    if [ $SKIP_ON_MISSING_CONF = true ] || [ ! -z $PRE_COMMIT_ALLOW_NO_CONFIG ]; then
        echo '

To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
```

Is there any solution to this behavior? Or is it up to git-lfs to fix this?

**Comment by asottile** [comment]
Copying my comment from the other ticket:

> git-lfs functions by (ab)using the pre-push hook. I don't think there's a way to resolve this conflict and use pre-commit's pre-push hook without modifications from the git-lfs side. I believe the problem is on git-lfs's side as pre-commit will still run git-lfs's pre-push hook (as pre-push.legacy) and the pre-push hook will still function.

**Comment by asottile** [comment]
@chbndrhnns I'm not sure there's much that can be done from the pre-commit side.  pre-commit _does_ play nice with other tools in that it will set aside their script and continue to call it (in the so-called legacy mode).

Unless you have other thoughts, I'm inclined to close this as wontfix

**Comment by chbndrhnns** [comment]
That's fine with me for now. 
My understanding now is that a `git lfs update --force` would disable precommit.

**Comment by asottile** [comment]
Yep, that is true.  Thanks for the issue :)
