### ISSUE TITLE
How to uninstall or upgrade?

### ISSUE THREAD

**Issue by sanmai-NL** [pre-commit/pre-commit#512]
I couldn't find info about that on http://pre-commit.com/#install . Could this be clarified in the docs?
Because of the non-standard local installation script I had a bit of a hard time figuring out how and where `pre-commit` is installed and how to upgrade it.

**Comment by asottile** [comment]
Let me know what you think of the wording in https://github.com/pre-commit/pre-commit.github.io/pull/102

(I'll push it now, we can update / iterate afterwards!)
