### ISSUE TITLE
Add option to generate a sample configuration file

### ISSUE THREAD

**Issue by elaichi** [pre-commit/pre-commit#514]
Similar to how `pylint` offers `--generate-rcfile`, `pre-commit` could have an option to generate a sample `.pre-commit-config.yaml`.
Note that this is related to https://github.com/pre-commit/pre-commit.github.io/issues/29.

**Comment by asottile** [comment]
I guess the question becomes what set of hooks would it configure?

**Comment by elaichi** [comment]
How about a fairly generic subset of these?
https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml#L4-L14
e.g. 
```
trailing-whitespace
end-of-file-fixer
check-added-large-files
check-yaml
```

**Comment by asottile** [comment]
Seems easy enough!

**Comment by asottile** [comment]
Via #515

**Comment by asottile** [comment]
This feature is in 0.14.0
