### ISSUE TITLE
limit run to staged changes

### ISSUE THREAD

**Issue by elaichi** [pre-commit/pre-commit#516]
From the documentation:

> pre-commit only runs on the staged contents of files [...]

which is what I expected, since I'll be mostly dealing with legacy code. But just noticed `flake8` failing with warnings for lines (66, 93, 140) nowhere near my change (~15):

```
(.venv) ❯ git --no-pager diff --staged --minimal weberror/pdbcapture.py
diff --git a/weberror/pdbcapture.py b/weberror/pdbcapture.py
index 9c1996e..6fa3ed6 100644
--- a/weberror/pdbcapture.py
+++ b/weberror/pdbcapture.py
@@ -15,10 +15,6 @@ except ImportError:  # pragma: no cover

 here = os.path.dirname(os.path.abspath(__file__))

-#def debug(msg, *args):
-#    args = '%s %s' % (msg, ' '.join(map(repr, args)))
-#    print >> sys.stderr, args
-

 class PdbCapture(object):


(.venv) ❯ pre-commit run
Validate Pre-Commit Config...............................................Passed
Validate Pre-Commit Manifest.........................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check docstring is first.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check Yaml...............................................................Passed
Flake8...................................................................Failed
hookid: flake8

weberror/pdbcapture.py:26:80: E501 line too long (82 > 79 characters)
weberror/pdbcapture.py:66:80: E501 line too long (82 > 79 characters)
weberror/pdbcapture.py:93:80: E501 line too long (118 > 79 characters)
weberror/pdbcapture.py:140:1: E305 expected 2 blank lines after class or function definition, found 1
```

Is there some config I'm missing here? Thanks!

**Comment by asottile** [comment]
pre-commit deals only in passing filenames to hooks.  By staged contents, it means the contents of the file that would exist if the commit would succeed (and not unstaged changes).

**Comment by elaichi** [comment]
Thanks @asottile! I see, I guess this is what I had in mind:
https://github.com/sk-/git-lint

> By default git lint only reports problems with the modified lines (with the exception of some linters that check that the whole file is sound).

**Comment by asottile** [comment]
neat, you _could_ call git-lint from pre-commit (if you wanted to). pre-commit doesn't really aim to be a parser of other tools, but more of a package manager.   thanks for the issue :)
