### ISSUE TITLE
stop running push after fail

### ISSUE THREAD

**Issue by sfahlberg** [pre-commit/pre-commit#518]
Hi there,
I'm just curious whether there is a way for my push to fail after the first failure instead of running my other hooks afterwards. That'll save me some time. Currently, it continues running all of the hooks until they finish for it to fail.

**Comment by asottile** [comment]
This is planned: https://github.com/pre-commit/pre-commit/issues/240

**Comment by sfahlberg** [comment]
excellent!

**Comment by asottile** [comment]
This is now available in [v1.1.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.1.0)!  Thanks again for the issue!
