### ISSUE TITLE
 Unknown Encoding error

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#519]
I get the following error on commit

```
An unexpected error has occurred: LookupError: unknown encoding:
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/main.py", line 195, in main
    return run(runner, args)
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 210, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 159, in get_repo_hooks
    for repo in runner.repositories:
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/runner.py", line 46, in repositories
    repository.require_installed()
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 174, in require_installed
    _install_all(self._venvs, self.repo_config['repo'])
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 68, in _install_all
    for cmd_runner, language_name, version, deps in venvs
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 69, in <genexpr>
    if not _installed(cmd_runner, language_name, version, deps)
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 60, in _installed
    _read_installed_state(cmd_runner, venv) == _state(additional_deps)
  File "/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 43, in _read_installed_state
    return json.loads(io.open(filename).read())
LookupError: unknown encoding: 

```

**Comment by asottile** [comment]
That's strange!  I'll add an encoding to that call but I really expect your operating system to default to C or _something_.

Can you paste: `env | grep -Ei '(LANG|LC)'`

**Comment by asottile** [comment]
I suspect something else is broken with your environment?  Do you have reproduction steps that I can use to get to the bottom of this bug?

**Comment by awebdeveloper** [comment]
here is the output

SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.2LCGqNauoG/Listeners
LC_CTYPE=UTF-8

I got some other error which asked me to do auto update, since then i get this error

**Comment by asottile** [comment]
I expect `LANG=en_US.UTF-8` in your environment as well -- even without that, python _should_ be defaulting to US-ASCII if the LANG variable is missing.  What version of python are you using (and what is your system installed python?)

You can often figure out what one pre-commit is using by `$(head -n 1 $(which pre-commit) | cut -d'!' -f2) --version`

**Comment by awebdeveloper** [comment]
I reinstalled and it's gone. Thanks for help

**Comment by awebdeveloper** [comment]
```
$  $(head -n 1 $(which pre-commit) | cut -d'!' -f2) --version
Python 2.7.10
```

**Comment by asottile** [comment]
Sweet! Yeah I imagine something strange happened if /when brew updated python.

**Comment by awebdeveloper** [comment]
Hi ,

Looks like the issue is still there. Just that I only face this issue whenever I try to commit from VS Code. 

Precommit is using Python 2.7

**Comment by asottile** [comment]
Is there any way to convince vs code to pass along a `LANG` environment variable?

**Comment by awebdeveloper** [comment]
let me check. According to you, it looks like a LANG issue,  is it ??

**Comment by asottile** [comment]
That is my guess -- even though python _should_ still fall back to an appropriate encoding when `LANG` is not present (why I can't even reproduce this issue even with a blank environment on OSX)

**Comment by tlvenn** [comment]
I have the same issue with VS Code.

**Comment by asottile** [comment]
I'll try and reproduce this when I'm at a mac.

Could you help me with the following:
- version and how you installed vscode
- version and how you installed python
- version and how you installed pre-commit

**Comment by tlvenn** [comment]
Hi @asottile, thanks for looking into it, for now I got around by editing the source files and forcing the encoding to `utf8` on open...

As far as my env:

- Latest version of OS X (10.12.3)
- Latest version of VS Code (1.11.2), installed with dmg file downloaded from website
- Latest version of Python (2.7.10), bundled with OS X ?
- Latest version of pre-commit (0.13.6) installed with brew

**Comment by awebdeveloper** [comment]
@tiveen what did you do

**Comment by tlvenn** [comment]
@awebdeveloper you need to edit pre-commit source code in 2 places where it uses io.open so that instead of having `io.open(filename)` it will do: `io.open(filename, encoding:'utf8')`.

The stacktrace from above points to the file you need to edit, so in your case, you will have to edit first `/usr/local/Cellar/pre-commit/0.13.2/libexec/lib/python2.7/site-packages/pre_commit/repository.py` line 43

**Comment by asottile** [comment]
here's a branch which does this while I try and figure out what's up: https://github.com/pre-commit/pre-commit/pull/524

**Comment by awebdeveloper** [comment]
I have raised a issue in vs code too lets see what they have to say. If either of you have any thing else to share plz post in the above ticket.

**Comment by asottile** [comment]
[I fixed this upstream](https://github.com/Microsoft/vscode/pull/26412)

Either grab the nightly VS code or wait for the next release :D

**Comment by awebdeveloper** [comment]
awesome will wait for next version

**Comment by awebdeveloper** [comment]
Next release is out. It's fixed thanks @asottile

**Comment by asottile** [comment]
\o/
