### ISSUE TITLE
looking for pre-commit sanctioned stylelint hook

### ISSUE THREAD

**Issue by elaichi** [pre-commit/pre-commit#520]
`stylelint` seems to be the CSS linter that cool kids are using these days:
https://stylelint.io/
since I didn't find any reference to it here:
http://pre-commit.com/hooks.html
I searched GitHub and found two that have been added by the community:
https://github.com/alanmc/pre-commit-stylelint
https://github.com/awebdeveloper/pre-commit-stylelint

is there one that you would recommend? the second one seems more up-to-date.

**Comment by asottile** [comment]
The main problem we've had (internally) with stylelint is the cli doesn't allow multiple filenames (I don't think either of those two mirrors handle this either).

@magicmark has worked on our internal wrapper (and I believe is adding a PR to make it fit better into the pre-commit ecosystem?) which (if I recall correctly) is a simple shell wrapper that invokes stylelint one file at a time?

Of the two linked, they're set up nearly identically -- @webdeveloper's does include some additional file extensions which may be useful.  You'd probably need to use `args` and tweak either the `entry` or play with `always_run` to get around the single-file issue.  Some entry similar to `bash -c 'echo -n $@ | xargs -d' ' -n1 stylelint' --` might work (note: untested, non-portable, fails for filenames with spaces, mileage may vary)

**Comment by awebdeveloper** [comment]
here is one i have created 

https://github.com/awebdeveloper/pre-commit-stylelint

**Comment by elaichi** [comment]
> The main problem we've had (internally) with stylelint is the cli doesn't allow multiple filenames (I don't think either of those two mirrors handle this either).

@asottile seems like it's fixed now (?), for example, these calls work fine for me:
```
stylelint --config=.stylelintrc.js src/styles/PageLayout.scss src/styles/constants.scss
```
```
stylelint --config=.stylelintrc.js src/styles/*.scss
```
with
```
❯ stylelint --version
7.10.1
```
also, this local hook seems well behaved:
```
-   repo: local
    hooks:
    -   id: stylelint
        name: stylelint
        entry: stylelint
        args:
        - '--config=.stylelintrc.js'
        language: system
        files: \.(css|scss|sass)$
```

**Comment by asottile** [comment]
Sweeeeeeeeet

**Comment by awebdeveloper** [comment]
yes. as I said my hook works fine for me

**Comment by elaichi** [comment]
When I started looking for a `stylelint` hook I first noticed that there was none in the [supported hooks](http://pre-commit.com/hooks.html). I thought that was a bit weird given how popular `stylelint` is, so I searched on GitHub and found the two I mentioned before.
@awebdeveloper when I tried yours, it broke on `pre-commit autoupdate`:
```
❯ pre-commit autoupdate
Updating https://github.com/awebdeveloper/pre-commit-stylelint...[INFO] Initializing environment for https://github.com/awebdeveloper/pre-commit-stylelint.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'reset', '', '--hard')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: ambiguous argument '': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

Check the log at ~/.pre-commit/pre-commit.log
```
and that's when I decided to ask here about it. @asottile why do you think it fails to autoupdate?

**Comment by awebdeveloper** [comment]
i don't know but you may be missing the sha attribute 


```
 -   repo: https://github.com/awebdeveloper/pre-commit-stylelint
       sha: '' # Use the sha or tag you want to point at like 0.0.1
       hooks:
```

**Comment by asottile** [comment]
Yeah probably missing `sha`, I'll go ahead and add @awebdeveloper's mirror to https://github.com/pre-commit/pre-commit.github.io so it shows up on http://pre-commit.com

**Comment by elaichi** [comment]
oh, weird... I was certain that an empty `sha` had never been an issue for other repos 🤔 
anyway, thanks guys!
