### ISSUE TITLE
New hook for tslint

### ISSUE THREAD

**Issue by alexjurkiewicz** [pre-commit/pre-commit#521]
I've created https://github.com/alexjurkiewicz/pre-commit-tslint
Does something like this even need to exist, or should every project just specify the hook themselves? If it should exist, should the pre-commit project own the repo?

Anyway, let me know how you'd best like me to contribute this hook to the wider ecosystem :)

**Comment by asottile** [comment]
Looks cool!

This might be better supported as a `node` hook or used as a `local` hook: http://pre-commit.com/#repository-local-hooks

**Comment by alexjurkiewicz** [comment]
Great. I'll try to get the hook config added to the official linter project, but otherwise teams can create the config themselves

**Comment by awebdeveloper** [comment]
@alexjurkiewicz   probably we should collaborate. I have been working on a similar plugin 

https://github.com/awebdeveloper/pre-commit-tslint

**Comment by alexjurkiewicz** [comment]
@awebdeveloper great minds think alike...

If either PR is not accepted, I am planning to investigate how the https://github.com/pre-commit/mirrors-jshint repo is created and create similar ones for each that the pre-commit project can own.

**Comment by awebdeveloper** [comment]
@alexjurkiewicz looks like my PR is accepted

**Comment by asottile** [comment]
@alexjurkiewicz we use https://github.com/pre-commit/pre-commit-mirror-maker to generate and keep these up to date
