### ISSUE TITLE
Feature request: Allow files to take a glob pattern

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#523]
globs are nice for specifying file groups, and you can still do regexy stuff in it

could we make it try parse a glob if `check_regex` fails?

caveats:
- `foo/**/*.js` or whatever with `glob` only works in py35+ (with the `recursive` flag), but I think since pre-commit takes already in a list of files, `fnmatch.fnmatch` can be used instead and works in 2.7?
- not sure how you validate a glob string or if this is even needed

**Comment by chriskuehl** [comment]
I'm not sure this is a good idea. Globs work okay if you only want to include one directory, but what happens as soon as you need to include another directory? Now you need two globs, so you've either got to convert it back into a regex, or go open another issue on pre-commit to ask it to support a list of globs or something.

I'm not sure what the benefit of globs over regexes is?

**Comment by chriskuehl** [comment]
Also, how do you determine whether to apply regex matching or glob matching? Is `some/example/path/to/file*` a regex or a glob (it's both)?

**Comment by magicmark** [comment]
To answer your first question:

for the simple case, globs like `foo/**/*.js` works and imo is nicer than something like `^foo.+\.js$`

if you wanted something more complicated, you *could* as you say do something like `(foo|bar)/**/*.js`, or go back to regex

in answering your second point, maybe this works better as an additional `filesglob` param and pre-commit only lets you specify one or something? idk, i'm easy as to how it's implemented, I just think it would be neat to be able to use globs :)

**Comment by asottile** [comment]
regexes are already much more powerful than globs.  I'm with @chriskuehl, I don't think this complexity is worth it and is more likely to confuse than help.

**Comment by lamuertepeluda** [comment]
it would have a wise choice to allow globs together with regex: there are many hooks which different option conventions, some use regex, some globs and it's confusing.
The best use case for globs is the exclude (which works as expected with roughly a half of the hooks). A glob expression is much more immediate than having a regex, IMHO.

I wish this tool was a neat husky replacement for python but it feels much more difficult to master and to setup (and maybe buggier).
