### ISSUE TITLE
[RFC] Make the default of `pre-commit autoupdate` use `--tags-only`?

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#525]
I find that `--tags-only` to be much better than the default.

My proposal:

- Make the `--tags-only` behaviour the default behaviour
- Make `--tags-only` a noop argument which produces a warning and does the default
- Add a `--bleeding-edge` which does the current default behaviour

@chriskuehl  thoughts?

**Comment by chriskuehl** [comment]
+1, I've been using `--tags-only` pretty exclusively lately.

**Comment by asottile** [comment]
This feature is in 0.14.0
