### ISSUE TITLE
Add hook option to not pass matching files as arguments to the program

### ISSUE THREAD

**Issue by absassi** [pre-commit/pre-commit#527]
It would be useful to add some hook option to _**not**_ pass matching files as arguments to the program, something like `- filenames-as-args: false`.

This would enable, for instance, easier integration of pre-commit into a repository using Makefiles or similar tools that find the required files to check by themselves and do not accept them in command line.

Currently, I'm using the following workaround to call `make check` to build and test C/C++ code:

- Defining the hook to call a wrapper script that forwards to `make`only the arguments before some delimiter, such as `--`.
- Adding a delimiter at the end of hook args.

However, forcing the user to add this delimiter whenever she wants to customize `make` arguments is confusing and error-prone. I'd like to write `args: [check]` instead of `args: [check, --]` and get rid of the wrapper script.

**Comment by asottile** [comment]
I believe you're looking for `always_run`? something like this:

```yaml
-   id: foo
    entry: make check
    always_run: true
    # The rest of the metadata
```

**Comment by absassi** [comment]
Well, `always_run` would work with a `files` filter that matches nothing (otherwise the filenames are passed anyway) and I did forget to mention this option.

I wasn't considering it because `make` would get called more often than needed. The problem is that the hook usually gets somewhat inefficient for simple operations (such as amending the commit message) because the system `make` uses (comparing file modification timestamps) is not aware of `git` and could trigger entire rebuilds just because the developer switched to another branch. On the other hand, `pre-commit` does know when files have actually changed (if the file filters are properly set, of course).

In one particular case, which motivated this suggestion, I have a mixed-language repository where `make` builds only for a small portion of the code that is not often changed, and building it is a bit slow when compared to other hooks we use.

**Comment by asottile** [comment]
Ah interesting!  I didn't think about things that would only _sometimes_ need to run.

Perhaps a `pass_filenames: ...` (default `true` of course) could be added?  Do you want to attempt a PR?

**Comment by asottile** [comment]
Heh, also found a bug while investigating this -- #533

**Comment by ulope** [comment]
I would also very much like this option. My use-case is the [`readme-renderer`](https://pypi.python.org/pypi/readme_renderer) package which checks if a setup.py's `long_description` is valid ReST and compliant with PyPI. It also takes no filename arguments but I'd still like it to only run when there was an actual change to the README.

**Comment by absassi** [comment]
Hi @asottile, OK, I'll try to make the PR. Thanks.

**Comment by asottile** [comment]
via #538

**Comment by asottile** [comment]
This feature is in 0.14.0
