### ISSUE TITLE
Anyway to run pre-commit on staged

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#528]
Is there anyway to run it on when file is staged

**Comment by asottile** [comment]
Seems not, here's a list of all possible hooks: https://git-scm.com/docs/githooks

**Comment by awebdeveloper** [comment]
look at this https://github.com/okonet/lint-staged

**Comment by asottile** [comment]
Ah I misinterpreted what you were asking, I thought you meant that pre-commit was triggered immediately when running `git add`. If you run just `pre-commit` this will run all hooks on just the staged files.
