### ISSUE TITLE
Feature request - Add support for other types of hooks aside from pre-commit

### ISSUE THREAD

**Issue by techjacker** [pre-commit/pre-commit#531]
It would be great to be able to run post-update hooks for example. Overcommit offers this but I'd prefer to use pre-commit.

**Comment by asottile** [comment]
pre-commit already supports `pre-push` as well (and it's pretty easy to add others).  If you'd like to add support for `post-update` it mostly means adding it to `pre-commit install`, adding a template for it (see `pre-push-tmpl` for example) and then making `stages` understand it.  I'd accept PRs for that :)

**Comment by techjacker** [comment]
Ok thanks for the info, not sure when I'll get time to do that PR but will try to fit it in if I can.

**Comment by asottile** [comment]
`commit-msg` as added [here](https://github.com/pre-commit/pre-commit/pull/566) you might find some inspiration from that :)

**Comment by Sykomaniac** [comment]
@asottile thanks for your work! Updated my commit message structure hook to use your commit-msg hook functionality. Anyone interested in seeing a basic use case of this new hook type take a look at: https://github.com/Sykomaniac/commit-hooks

**Comment by asottile** [comment]
going to close this -- there's now precedent for pre-commit to support other types of hooks (`commit-msg` / `pre-push` are implemented) and all it takes is a champion to add other hook types :)

PRs definitely welcome!

**Comment by fruch** [comment]
@asottile is there an example on how to use 'commit-msg' hook i.e. in the configuration yaml ?

**Comment by fruch** [comment]
@asottile never mind, I've found it
https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
