### ISSUE TITLE
Hook that updates files

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#532]
I have created the following hook called prettier which formats js files.
https://github.com/awebdeveloper/pre-commit-prettier/blob/master/.pre-commit-hooks.yaml

When i try to commit a file (say my-oncogene.js in this case) i get file modified error. What Should i do. 

```
hookid: prettier

Files were modified by this hook. Additional output:

asset/js/my-oncogene.js 41ms
```

looks like the pre-commit only passes if no file is modified. 

I am on newer version of pre-commit 0.13

**Comment by asottile** [comment]
This is intentional.  If a hook modifies files then the commit itself was not ready.  You can inspect whether the modifications were correct, re-add, and commit as usual.

**Comment by awebdeveloper** [comment]
Then Plz update the docs to reflect it esp creating new hooks section

**Comment by asottile** [comment]
I hope I can convince you this is a _reasonable_ behaviour :)

Consider the three possible choices pre-commit could make in this situation:

1. Don't look at modifications as a failure and continue the commit as normal:
    - This will cause commits of unvetted changes (and incorrect contents)
2. `git add` after changes and continue committing
    - What if the committer has unstaged changes on that file?  Attempting to restore them would break.
    - What if the git hook is incorrect? You've now committed broken things.
    - What if the git hook depends on the behaviour of others (for example, a rewriter that expects autopep8 to fix up some indentation)? Again, you've now committed "broken" things.
    - What if two rewriting hooks disagree on how a file should be formatted?  Suddenly you're switching formatting back and forth on every commit :)
3. Treat modifications as a "failure" and leave the intelligent end user to perform the correct actions of the above whether it's:
    - Accept the automatic modifications and `git add`
    - Adjust pre-commit hook settings and re-commit
    - Modify the changes made
    - etc.

**Comment by asottile** [comment]
pre-commit in fact used to take the first approach (1.) and caused many headaches with tools that didn't properly communicate their side-effects by exit codes.  It was considered a bug  (#285) and fixed (#287 #305).

**Comment by awebdeveloper** [comment]
I am completely ok with your approach. And i think it's the right one but it's not communicated any where.

Could a line be added in docs to inform of this behaviour

**Comment by brandon-leapyear** [comment]
I understand why route 3 was chosen as the default, but I think it would be nice to offer route 2 as an option. For example, we have a file in our repo that should be auto-generated from other files. We basically have a pre-commit script that runs `cat ... > generated-file`. This would also be applicable for black (python) and prettier (javascript).

As a user, I would want the following to occur if modifications happen in a pre-commit plugin:

1. If the `modifiable` option is `false` (the default value), fail
2. Add the modifications to the commit
3. When adding back stashed changes, if a conflict occurs, overwrite the file with the stashed changes

e.g. if i had the changes
```diff
-foo = 1
+bar=2
```
and did `git add --patch` to get the two following diffs:
```diff
@@ staged @@
-foo = 1
+bar=1

@@ unstaged @@
-bar=1
+bar=2
```
then running the pre-commit hook should commit the following:
```diff
-foo = 1
+bar = 1
```
and then (since there's a conflict) the unstaged changes should overwrite the file so that `git diff` returns:
```diff
-bar = 1
+bar=2
```

Thoughts?

**Comment by asottile** [comment]
No, I've stated my reasons. pre-commit will never touch the staging area

**Comment by aklajnert** [comment]
> This is intentional. If a hook modifies files then the commit itself was not ready. You can inspect whether the modifications were correct, re-add, and commit as usual.

@asottile how about marking some hooks as "trusted"? If the trusted hook will perform any changes, do not block the commit. The CI's responsibility is to block the faulty changes from going into master, that's the place where changes should be reviewed. 
If you have a lot of hooks, it takes time to run them, so having to run them again is pretty annoying.

**Comment by asottile** [comment]
you cannot, trust nothing -- I've stated my reasons.  pre-commit will never touch the staging area

**Comment by aklajnert** [comment]
OK, I did some experiments, and now I understand what you mean. Just not-failing the hook is not enough, as the changes made during hook run won't be added within the same commit automatically.  
I completely agree now, that the current behavior is the most reasonable. Thanks.

**Comment by plammens** [comment]
> you cannot, trust nothing

Practicality beats purity :)

**Comment by MarcoGorelli** [comment]
> > you cannot, trust nothing
> 
> Practicality beats purity :)

Please, this kind of comment is not helpful and will likely accomplish nothing other than getting this issue locked.

Anthony has been extremely clear on his stance here - pre-commit will never touch the staging area.

**Comment by asottile** [comment]
I am locking this thread, all new comments have been off topic

@plammens this is a warning, please be considerate
