### ISSUE TITLE
Somebody can create new hook from PgSanity - checks the syntax of Postgresql SQL files?

### ISSUE THREAD

**Issue by patsevanton** [pre-commit/pre-commit#541]
PgSanity checks the syntax of Postgresql SQL files.

It does this by leveraging the ecpg command which is traditionally used for preparing C files with embedded sql for compilation. However, as part of that preparation, ecpg checks the embedded SQL statements for syntax errors using the exact same parser that is in PostgreSQL.

So the approach that PgSanity takes is to take a file that has a list of bare SQL in it, make that file look like a C file with embedded SQL, run it through ecpg and let ecpg report on the syntax errors of the SQL.

https://github.com/markdrago/pgsanity

**Comment by chriskuehl** [comment]
Looks cool! pre-commit is designed around anyone being able to create their own hooks (as git repos), there are some instructions on the website: http://pre-commit.com/#new-hooks

This issue probably doesn't belong on the pre-commit project itself (this repo is used for framework-specific questions/bugs/enhancements), but we'd definitely be happy to help you if you have any questions with writing a new hook!

Once you've written the hook, you can submit a PR to https://github.com/pre-commit/pre-commit.github.io to have it listed on [our list of public hook repos](http://pre-commit.com/hooks.html).

**Comment by patsevanton** [comment]
Ок. Thanks.
