### ISSUE TITLE
Feature Request - Allow transformation of found filenames

### ISSUE THREAD

**Issue by dainyl** [pre-commit/pre-commit#544]
When using local repository hooks I often want to run commands in subdirectories.
For example I had a `node` project in a subdirectory and wished to run `eslint` in that subdirectory.`pre-commit` currently supplies the filenames as `subdirectory/file1.js subdirectory/file2.js` where as what I require are the filenames without the subdirectory eg `file1.js file2.js`.

**Comment by asottile** [comment]
I don't think this should happen in the framework -- if the hook needs to transform the filenames it should do that itself.

Our usage of `eslint` works great without mangling the filenames? is there some odd configuration setting you're using?

**Comment by asottile** [comment]
Here's a config that does what you want either way though (not portable: uses bash, also not tested)

```yaml
...
entry: bash -c 'echo "$@" | xargs basename | xargs eslint' --
...
```

**Comment by dainyl** [comment]
I think the odd configuration is that the `package.json` and the rest of the js code is not located in the root directory. Bash should be fine for my use case, so I'll give that config a go. Thanks!

**Comment by asottile** [comment]
@dainyl  did that work for you?
