### ISSUE TITLE
Feature request - pass files to pre-commit hooks separately (i.e. xargs mode)

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#557]
I sometimes come across projects (for example [import-sort](https://github.com/renke/import-sort)) that only take 1 file at a time, and error when pre-commit tries to throw n files at it

in such cases, i've resorted to a wrapper script to call it sequentially

could there a better way to do this?

I'd like to write something like
```
-   id: reorder-es6-imports
    name: Reorder ES6 Imports
    description: This hook reorders ES6 imports.
    entry: import-sort
    language: node
    types: [javascript]
    args: [--overwrite]

    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['import-sort-cli@^3.3.0', 'import-sort-parser-babylon@^3.2.0', 'import-sort-style-eslint@^3.0.0']
    minimum_pre_commit_version: 0.7.0

    # this flag flag does not exist, but it would be neat if it did :)
    pass_files_sequentially: true
```

(I'm thinking the same way there's a `pass_filenames` flag, we could have a `pass_files_sequentially` flag or something)

Fwiw we can achieve the same with xargs:

```
-   id: reorder-es6-imports
    name: Reorder ES6 Imports
    description: This hook reorders ES6 imports.
    entry: bash -c 'echo "$@" | xargs -n1 import-sort --overwrite'
    language: node
    types: [javascript]

    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['import-sort-cli@^3.3.0', 'import-sort-parser-babylon@^3.2.0', 'import-sort-style-eslint@^3.0.0']
    minimum_pre_commit_version: 0.7.0
```

However:
- xargs isn't very portable
- `args` doesn't seem to be respected
- we have to do this wrapping

I think a new flag to solve these things would be nice - @asottile what do you think?

**Comment by asottile** [comment]
Yeah I've hit this once or twice but in every case I've sent a tiny pr and the tool just fixed it. -n1 is also super slow (especially on windows). 

The idea seems fine I guess, I'm not keen on the name chosen (what does sequentially mean? They're already passed in a sequence). 

"xargs mode" also doesn't make too much sense as we're already simulating xargs in a way (see aptly named xargs.py)

**Comment by chriskuehl** [comment]
See also #394 for previous discussion

**Comment by asottile** [comment]
Given the resolution in #394 and the multitude of tools that already allow multiple arguments (precedent) I don't think we should complicate things until there's a stronger usecase

**Comment by asottile** [comment]
slight adjustment, to properly handle spaces you need:

```yaml
    entry: bash -c 'for x in "$@"; do ... "$x"; done' --
```
