### ISSUE TITLE
pre-commit should meet the XDG Base Directory Specification

### ISSUE THREAD

**Issue by nagromc** [pre-commit/pre-commit#562]
XDG Base Directory Specification is quite common now. Just `ls ~/.cache ~/.config ~/.local` to realize it.

I think `~/.pre-commit` should be moved to `$XDG_CACHE_HOME` or `$HOME/.cache`

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by asottile** [comment]
Pull requests welcome, note that this also has to work well for windows which doesn't adhere to XDG.

I've been hesitant to move the directory as it'd be a bit awkward for current users (though perhaps `clean` can just be updated to remove both paths for some amount of time?)

**Comment by nagromc** [comment]
> Pull requests welcome, note that this also has to work well for windows which doesn't adhere to XDG.

Is there any documentation for pre-commit on Windows?

Is it supposed to run on:
- the [official Python release for Windows](https://www.python.org/downloads/release/python-362/);
- Cygwin;
- [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux);
- all of the above?

On which Windows version is it supposed to run?

How do you proceed to test it on Windows? Do you use a VM or something?

> I've been hesitant to move the directory as it'd be a bit awkward for current users (though perhaps `clean` can just be updated to remove both paths for some amount of time?)

I understand. But it won't break anything since it would just re-cache all the needed stuff, right? We can imagine three scenarios if `~/.pre-commit` already exists:
1. Move the existing `~/.pre-commit` in `$XDG_CACHE_HOME` or `$HOME/.cache`, with or without warning (see `2.`);
1. Don't move the existing `~/.pre-commit`, but display a warning before re-caching;
3. Just re-cache the needed parts without displaying any message (and maybe delete the existing `~/.pre-commit`) ¯\\\_(ツ)\_/¯

Well, it has been done already with the transition from `hooks.yaml` to `.pre-commit-hooks.yaml` in some sort.

**Comment by asottile** [comment]
@nagromc If you ^F windows on http://pre-commit.com you can see the current support matrix

It is tested automatically through appveyor -- my home desktop at home also runs windows so I often do more-difficult debugging on that.

As for the three solutions above:

1. Isn't feasible -- virtualenvs are not relocatable (the shebangs contain full paths to the interpreter)
2. A possibility, though...
3. sounds best :)

**Comment by nagromc** [comment]
OK I'll give it a try when I have time. Didn't know about AppVeyor.

And for the third solution, should we delete `~/.pre-commit`?

**Comment by asottile** [comment]
I think just leave it alone for the most part (unless `pre-commit clean` is run, we can include it in there for some amount of time and then after some amount of time pretend like it never existed)
