### ISSUE TITLE
check-docstring-first can't handle unicode

### ISSUE THREAD

**Issue by GhostLyrics** [pre-commit/pre-commit#568]
We have some application where there are Unicode characters (German umlauts, e.g. "ü") in some strings. Strangely I could not reproduce the issue in my dev environment, only in my testing environment.

I tested in a Docker container `buildpack-deps:xenial`.

```
# on the host
docker run -it buildpack-deps:xenial /bin/bash
# in the container
apt update && apt install python3-pip
# here I'd install pre-commit with other things via pip3
pre-commit install
pre-commit autoupdate
pre-commit run --all-files

Check docstring is first.................................................Failed
hookid: check-docstring-first

Traceback (most recent call last):
  File "/root/.pre-commit/repomdnrbb1l/py_env-python3/bin/check-docstring-first", line 11, in <module>
    load_entry_point('pre-commit-hooks==0.9.1', 'console_scripts', 'check-docstring-first')()
  File "/root/.pre-commit/repomdnrbb1l/py_env-python3/lib/python3.5/site-packages/pre_commit_hooks/check_docstring_first.py", line 60, in main
    contents = io.open(filename).read()
  File "/root/.pre-commit/repomdnrbb1l/py_env-python3/lib/python3.5/encodings/ascii.py", line 26, in decode
```

A (not so) quick [search for unicode characters](https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix) resulted in:
```plain
ag -r "[\x80-\xFF]" .

260:        return "Nicht Gen��gend"
309:            return (4, "Gen��gend")
```

I am wondering if this is because `python --version` shows the 2.7 Python (`2.7.12`).

**Comment by asottile** [comment]
It's picking ascii because you don't have locales set up in your docker container. (notable you need to run  locale-gen for en_US.utf-8 and set LANG to the same)

**Comment by GhostLyrics** [comment]
Yes, you were right. Thank you.

For the next person looking at a similar situation:
```
apt install locales
export LANG=en_US.utf-8
# rest of your commands here
```

**Comment by asottile** [comment]
Sweet, yeah wasn't at a computer -- I think the commands I've used in the past are:

```dockerfile
RUN /usr/sbin/locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
