### ISSUE TITLE
pre-commit or pre-add

### ISSUE THREAD

**Issue by LeuisKen** [pre-commit/pre-commit#596]
When I use pre-commit and eslint, I always do things like follows:

```
git add ....
git commit ....
// linter throw error
// fix lint error
git commit ....
// no lint error
git push .....
```

Since I didn't run git add again after I fix lint error, I push the unfixed version to the remote git server.

I wonder how can I get rid of error like this, combine other tools to use or just use a "pre-add" tool.

**Comment by asottile** [comment]
I think you'll find that the workflow as described is impossible with our tool (unless you're using `--no-verify` / `SKIP`).  pre-commit only runs on the *added* contents and not on the unstaged changes.  In your small snippet above you'll get a lint error on both `commit` operations.

If there's a case where that's not happening, I'd be very interested in a more detailed report :)

**Comment by asottile** [comment]
To add a more concrete example:

Here's a `.pre-commit-config.yaml`:

```yaml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: flake8
```

And a shell session in that git repo:

```console
$ echo 'import os' > test.py
$ git add test.py
$ git commit -m "Add test"
Flake8...................................................................Failed
hookid: flake8

test.py:1:1: F401 'os' imported but unused

$ # Fix the problem
$ echo -e 'import os\n\nprint(os.getcwd())' > test.py
$ git commit -m "Add test"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.pre-commit/patch1504397400.
Flake8...................................................................Failed
hookid: flake8

test.py:1:1: F401 'os' imported but unused

[INFO] Restored changes from /home/asottile/.pre-commit/patch1504397400.
$ # Actually adding allows a commit
$ git add test.py
$ git commit -m "Add test"
Flake8...................................................................Passed
[master 25f02e5] Add test
 1 file changed, 3 insertions(+)
 create mode 100644 test.py
```

**Comment by asottile** [comment]
Closing this, if you find that this isn't the case, please attach more information and reopen :)

**Comment by LeuisKen** [comment]
Thank you. :)
