### ISSUE TITLE
Debugging new hook

### ISSUE THREAD

**Issue by hectorv** [pre-commit/pre-commit#613]
Hi!
I'm trying to develop a new `pre-commit` hook for `SVGO`:
https://github.com/svg/svgo
https://github.com/hectorv/mirrors-svgo
I used `pre-commit-mirror-maker` to create it.

My `.pre-commit-config.yaml` currently looks like this:
```
---
-   repo: https://github.com/hectorv/mirrors-svgo.git
    sha: v0.6.6
    hooks:
    -   id: svgo
```

Unfortunately I'm getting this `Unknown argument` messages that I don't know where to start debugging:
```
❯ pre-commit run --all-files svgo
svgo.....................................................................Failed
hookid: svgo

Unknown argument: main/client/static/images/study/android phone + shield copy.svg
Unknown argument: main/client/static/images/score/037.svg
Unknown argument: main/client/static/images/test/click_allow_arrow.svg
Unknown argument: main/client/static/images/cms_splash/globe.svg
Unknown argument: main/client/static/images/splash-sprite3.svg
Unknown argument: main/client/static/images/score/053.svg
```

I'm guessing I haven't properly configured the way `pre-commit` passes arguments to `SVGO`, but I'm not sure how to proceed.
Any ideas? Thanks!

**Comment by asottile** [comment]
Here's [the documentation](http://pre-commit.com/#arguments-pattern-in-hooks) on how pre-commit passes arguments.

My shot-in-the-dark guess is that `svgo` currently doesn't support passing multiple arguments at a time.  It seems there's [already an open issue](https://github.com/svg/svgo/issues/773) for a similar thing!

I'd suggest writing a pull request for `svgo`, if they push back maybe it's finally time for us to implement https://github.com/pre-commit/pre-commit/issues/394

**Comment by asottile** [comment]
@hectorv I took a stab at a PR, maybe it or something like it will get merged? https://github.com/svg/svgo/pull/786

**Comment by asottile** [comment]
Looks like the latest version of `svgo` supports this
