### ISSUE TITLE
dyld: Library not loaded: @rpath/libpython3.6m.dylib -- Error

### ISSUE THREAD

**Issue by mattstrayer** [pre-commit/pre-commit#618]
Hi, 

Getting a strange error when running pre-commit that I can't figure out. Any help would be greatly appreciated! 

- Mac is using anaconda's version of python 3.6 && pre-commit's latest version, 1.1.0

see output from running `pre-commit` below

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/mastra/.cache/pre-commit/patch1505227893.
[INFO] Installing environment for [**REDACTED**]
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /Users/mastra/.cache/pre-commit/patch1505227893.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/local/Cellar/pre-commit/1.1.0/libexec/bin/python3.6', '-m', 'virtualenv', '/Users/mastra/.cache/pre-commit/repou6d5sbti/py_env-python3.6', '-p', 'python3.6')
Return code: 100
Expected return code: 0
Output:
    Using base prefix '/Users/mastra/anaconda'
    New python executable in /Users/mastra/.cache/pre-commit/repou6d5sbti/py_env-python3.6/bin/python3.6
    Also creating executable in /Users/mastra/.cache/pre-commit/repou6d5sbti/py_env-python3.6/bin/python
    ERROR: The executable /Users/mastra/.cache/pre-commit/repou6d5sbti/py_env-python3.6/bin/python3.6 is not functioning
    ERROR: It thinks sys.prefix is '/' (should be '/Users/mastra/.cache/pre-commit/repou6d5sbti/py_env-python3.6')
    ERROR: virtualenv is not compatible with this system or executable
    Running virtualenv with interpreter /Users/mastra/anaconda/bin/python3.6

Errors:
    dyld: Library not loaded: @rpath/libpython3.6m.dylib
      Referenced from: /Users/mastra/.cache/pre-commit/repou6d5sbti/py_env-python3.6/bin/python3.6
      Reason: image not found


Check the log at /Users/mastra/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
This seems like a bad interaction between `virtualenv` and `conda` (which I don't believe are designed to work well together -- *thanks conda*).

You _may_ be able to get this to work with `VIRTUALENV_ALWAYS_COPY=1 pre-commit run ...`?  Unclear.  I'd suggest trying either the official pythons or the `brew` pythons.

I myself don't have access to macos or I'd try and reproduce

**Comment by asottile** [comment]
This seems to be the same issue: https://github.com/ContinuumIO/anaconda-issues/issues/305#issuecomment-285094497

**Comment by mattstrayer** [comment]
Thanks so much, @asottile ! Investigating further now.

**Comment by mattstrayer** [comment]
Update: I removed conda, cleaned pre-commit, and used the regular python3 homebrew setup and we're back in good shape. 

Thanks again @asottile !

**Comment by ghunkins** [comment]
Had the same issue. For anyone who hasn't found an answer, the below worked for me.

```
pip uninstall virtualenv
conda install virtualenv
```

[Source](https://stackoverflow.com/questions/42190984/dyld-library-not-loaded-error-preventing-virtualenv-from-loading)

**Comment by asottile** [comment]
you can also `conda install pre-commit` now thanks to @nicoddemus

**Comment by deichdeich** [comment]
> Had the same issue. For anyone who hasn't found an answer, the below worked for me.
> 
> ```
> pip uninstall virtualenv
> conda install virtualenv
> ```
> 
> [Source](https://stackoverflow.com/questions/42190984/dyld-library-not-loaded-error-preventing-virtualenv-from-loading)

I did this, and the problem persists.  Is there anything else that could be causing the error message?
