### ISSUE TITLE
Throw error if pre-commit isn't installed? Or automatic install pre-commit?

### ISSUE THREAD

**Issue by reywright** [pre-commit/pre-commit#651]
Most of the pip packages I use, I'm able to set up some type of config to get them to work. It seems like with pre-commit, I HAVE to do

`pre-commit install`

The main problem with this, is if I add this to a repo and a user doesn't specifically execute pre-commit install, then they are free to commit code to that repo. So my question is, is how do I make pre-commit a little bit more strict in how it functions? Why do I have to do pre-commit install after I've already pip installed? Is there anyway to make this process more automatic?

Another question, is let's say someone updates the .yaml file. Someone could have updated the repo but it doesn't seem like there are any checks to ensure what you've installed is in sync with any potential updates to the .yaml file.

**Comment by reywright** [comment]
Another question, is let's say someone updates the .yaml file. Someone could have updated the repo but it doesn't seem like there are any checks to ensure what you've installed is in sync with any potential updates to the .yaml file.

**Comment by asottile** [comment]
pip (setuptools / wheels) doesn't provide options for writing files outside of the installation directory, and even with that I think that being explicit is much better.

If you work in an enterprise environment where modifying the default `git` templates is an option, you could include the pre-commit hook template there.

One option that I've used with good success is adding `pre-commit install` to common tasks in the repository such as in `tox`'s tests, in `make test`, etc. (whatever common entry point you have to "setting up a development environment").  Here's [an example](https://github.com/pre-commit/pre-commit-hooks/blob/e718847ccbc65cd72a89fefb4db61c55ec4d430d/tox.ini#L18)

Another option is to include `pre-commit` as part of your continuous integration, here's [our documentation on this](http://pre-commit.com/#usage-in-continuous-integration).

Yet another option is to include `pre-commit` as part of server side hooks (`pre-receive`, etc.) such that it is enforced server side.

**Comment by asottile** [comment]
Could you elaborate on what you mean by "updates to the .yaml file" -- there's two yaml files in question (`.pre-commit-config.yaml` (the local configuration) and `.pre-commit-hooks.yaml` (the remote hooks manifest)).

One of pre-commit's design goals is repeatability, it will run exactly what is configured in `.pre-commit-config.yaml` on disk and is designed to use permanent references to remote repositories.  You can read more about this [in the documentation](http://pre-commit.com/#using-the-latest-sha-for-a-repository).

**Comment by reywright** [comment]
essentially if there's a repo, a user pip installs and then does pre-commit install or whatever, it seems like they'd have to install again if the .pre-commit-config.yaml file updates with a new entry or changes in some way. Maybe what you're saying is there's a way they can run that command (or another command) once and then pre-commit will follow the config.yaml file?

Thanks for the help by the way... I'm not too versed in the git hook space so I'm a bit out of my depth here.

**Comment by asottile** [comment]
`pre-commit install` is only needed once -- the configuration file is free to change after that :).

The hook script is [relatively small](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/resources/hook-tmpl) and is mostly intended to hand off the `git` information to `pre-commit` such that it can do the smart stuff :).  In the end it ends up being a thin wrapper around `pre-commit run` which does all the installation and environment management based on the configuration file.

**Comment by reywright** [comment]
thanks so much @asottile. Makes a ton of sense!

**Comment by asottile** [comment]
Cheers! Thanks for the issue, feel free to reach out if you have more issues or if there's places where the documentation can be improved.
