### ISSUE TITLE
autoupdate just one hook-id

### ISSUE THREAD

**Issue by KevinHock** [pre-commit/pre-commit#656]
Hi Anthony et al.,

I was going to make a PR such that you can run `pre-commit autoupdate just-one-hook-id` and only update that one hook.

Let me know if you think this is a bad idea for some unforeseen reason on my part.

Cheers,
Kevin

**Comment by asottile** [comment]
since revisions are pinned on a repository level, perhaps a repository would be a better level to work against?

You *could* do based on a hook-id, but this would have the side-effect of upgrading all hooks in the same repository

**Comment by asottile** [comment]
But yeah, sounds like a good idea to me, perhaps something like this:

```
pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit
```

**Comment by KevinHock** [comment]
Good point, I'll do it that way, thanks @asottile 👍

**Comment by asottile** [comment]
via #657
