### ISSUE TITLE
Autoupdate, select, multiple repositories

### ISSUE THREAD

**Issue by KevinHock** [pre-commit/pre-commit#658]
Brought up from #657

As noted by @asottile, we can do

`pre-commit autoupdate --repo repo1 --repo repo2 --repo repo3`

to update multiple repositories.

That can be implemented pretty easily with `action='append'` -- and changing the same parts as #657

**Comment by asottile** [comment]
This has been released as part of [v1.7.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.7.0)!
