### ISSUE TITLE
Uh oh, whoops, `pre-commit autoupdate --repo foo` only leaves foo

### ISSUE THREAD

**Issue by KevinHock** [pre-commit/pre-commit#660]
My bad 🤦‍♂️  

So it's supposed to leave everything else 'as is' and just update repo foo.

Whereas now it deletes all the other repos in the `.pre-commit-config.yaml`, and leaves the updated foo.

**Comment by asottile** [comment]
heh, want to fix it?

**Comment by KevinHock** [comment]
Sure, I can do that 👍
