### ISSUE TITLE
Restrict pre-commit checks to a folder

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#662]
How do restrict pre-commit checks to run only on a folder? I have a UI & API folder. I only want pre-commit checks to run on  API folder

**Comment by asottile** [comment]
One way would be to use the new global `exclude` combined with a negative lookahead

```yaml
exclude: '^(?!API/)'
```

**Comment by asottile** [comment]
@awebdeveloper does this solution work for you?

**Comment by awebdeveloper** [comment]
yup

**Comment by awebdeveloper** [comment]
can i have different pre-commit  for different folders

**Comment by asottile** [comment]
Currently not really, there can be multiple configuration files but only one can be hooked up to run on `commit`.  A similar discussion took place here for a reasonable workaround: https://github.com/pre-commit/pre-commit/issues/466

**Comment by yehoshuadimarsky** [comment]
> One way would be to use the new [global `exclude`](http://pre-commit.com/#pre-commit-configyaml---top-level) combined with a negative lookahead
> 
> ```yaml
> exclude: '^(?!API/)'
> ```

Sorry if this is just trivial regex stuff but how can I modify this global exclude to ignore a specific file, i.e. only everything inside `API/` should be included in `pre-commit`, except for this one file called `API/bad_file.py`?

**Comment by asottile** [comment]
There's now a global `files` so you don't even need trickery:

```
files: ^API/
```

**Comment by yehoshuadimarsky** [comment]
Cool! didn't know that, will check it out. Thanks for the super fast reply!!

**Comment by asottile** [comment]
but for your specific regex question, you can "AND" negative lookaheads:

```
^(?!API/)(?!API/bad_file.py)
```

**Comment by yehoshuadimarsky** [comment]
> but for your specific regex question, you can "AND" negative lookaheads:
> 
> ```
> ^(?!API/)(?!API/bad_file.py)
> ```

but won't i run into issues with greedy/non-greedy matching/

**Comment by asottile** [comment]
sorry, re-edited, I misinterpreted
