### ISSUE TITLE
Handle when `core.hooksPath` is set?

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#663]
As we found in https://github.com/pre-commit/pre-commit-hooks/issues/250, pre-commit (despite being installed) will be silently skipped if `code.hooksPath` is set.

A few options:
- during `pre-commit install`, check this variable and warn
- "" but error
- install into the directory at `core.hooksPath` (but it may be outside the working dir? probably not the best idea to write to it)

**Comment by revolter** [comment]
Or a prompt when running `pre-commit install` along the lines of:

> We noticed that you have set a different directory for the git hooks via the `core.hooksPath` config. Do you want us to remove it so `pre-commit` will work or install it in the specified directory?

**Comment by asottile** [comment]
This has been released as part of [v1.7.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.7.0)!

**Comment by revolter** [comment]
Awesome 👍
