### ISSUE TITLE
pre-commit on revert

### ISSUE THREAD

**Issue by hectorv** [pre-commit/pre-commit#665]
This question came up the other day and got me wondering: given that `git revert` creates a commit, wouldn't this also trigger our `pre-commit` hooks? Of course we could take certain assumptions here, e.g. that the commit being reverted got there before running `pre-commit install`, etc. I'm mostly just curious what your take is on this. Thanks!

**Comment by hectorv** [comment]
Could it be because `git revert` is not a supported hook action? 😄 
https://git-scm.com/docs/githooks

**Comment by asottile** [comment]
It seems that despite `git revert` makes a commit, it does not trigger any hooks:

```
(venv) asottile@asottile-VirtualBox:/tmp/pre-commit$ git commit -m "this is a mistake"
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
autopep8 wrapper.....................................(no files to check)Skipped
Check docstring is first.............................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Tests should end in _test.py.........................(no files to check)Skipped
Fix requirements.txt.....................................................Passed
Flake8...............................................(no files to check)Skipped
Validate Pre-Commit Manifest.........................(no files to check)Skipped
Reorder python imports...............................(no files to check)Skipped
Add trailing commas..................................(no files to check)Skipped
Check hooks apply to the repository..................(no files to check)Skipped
Check for useless excludes...........................(no files to check)Skipped
[master 49bd1e0] this is a mistake
 1 file changed, 1 insertion(+)
(venv) asottile@asottile-VirtualBox:/tmp/pre-commit$ git revert HEAD
[master 059efff] Revert "this is a mistake"
 1 file changed, 1 deletion(-)
```

imo, it's not support important to run hooks on a straight revert -- usually the goal of a revert is to get rid of a bad change as quick as possible.

If you wanted to run hooks in a "revert" situation, you could do it like this:

```
$ git revert --no-commit HEAD && git commit --no-edit
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
autopep8 wrapper.....................................(no files to check)Skipped
Check docstring is first.............................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Tests should end in _test.py.........................(no files to check)Skipped
Fix requirements.txt.....................................................Passed
Flake8...............................................(no files to check)Skipped
Validate Pre-Commit Manifest.........................(no files to check)Skipped
Reorder python imports...............................(no files to check)Skipped
Add trailing commas..................................(no files to check)Skipped
Check hooks apply to the repository..................(no files to check)Skipped
Check for useless excludes...........................(no files to check)Skipped
[master 7a2c914] Revert "Revert "this is a mistake""
 1 file changed, 1 insertion(+)
```

Note that `--no-commit` sets the default commit message and then `--no-edit` will use that default message.  It equates to the same thing as `git revert HEAD`, but it runs the hooks.

**Comment by hectorv** [comment]
Makes sense, thanks @asottile !

**Comment by gnustavo** [comment]
Hi. I found this thread while I was trying to know why my pre-commit hook wasn't being invoked by a git-revert. I see now that it isn't. But I'm compelled to offer an example where it would be nice to be.

Reverting normal commits isn't such a big deal. But reverting a merge commit is,  as you can read from the [horse's mouth](https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt) himself.

So, I have a hook to detect commits trying to revert a merge and to deny it. It's mostly important as a pre-receive hook, but I usually make my hooks work the same as a pre-receive and as a pre-commit hook so that I can detect problems at commit time and not only at push time.

So, I think it would be useful for a git-revert to invoke the pre-commit hook too.

Just my two cents.

**Comment by gnustavo** [comment]
Oops. Let me correct myself. Since my hook detects revert commits by the contents of their log messages the pre-commit is of no use. I have to use the commit-msg hook instead, which is also not invoked by git-revert. In fact, git-revert seems to invoke the post-commit hook.

**Comment by asottile** [comment]
It may be useful to suggest this to `git` since that's what is not triggering any hooks :)
