### ISSUE TITLE
Stuck at "Locking pre-commit directory" after add a new hooks

### ISSUE THREAD

**Issue by dwicao** [pre-commit/pre-commit#675]
## Step to reproduce:
in earlier, my team using pre-commit for `prettier`
then we add a hooks for `eslint`
trying to commit a changes:
```
➜  web git:(xyzbranch) ✗ git commit -v -m "test"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/dwicao/.cache/pre-commit/patch1515120727.
[INFO] Locking pre-commit directory
```
just stuck at it

## How to solve:
I deleted `pre-commit` folder at `~/.cache/`
try to commit again, and it just worked flawlessly 🎉

**Comment by asottile** [comment]
Hmm! Do you have steps to reproduce the deadlock?

From the paths I assume you're on macos?

**Comment by dwicao** [comment]
@asottile yeah I'm on macOS, sorry but I really don't know how to reproduce the deadlock

**Comment by asottile** [comment]
That's OK, thanks for the information nonetheless!

**Comment by KevinHock** [comment]
I get this as well, on Linux. I can't give steps to reproduce though.

**Comment by lohith-code** [comment]
> ~/.cache/

Thankyou

**Comment by modamod** [comment]
I know that this has been resolved and closed.
The way to preproduce is killing the pre-commit process before finishing which doesn't delete the lock file in ~/.cache/pre-commit/.lock .

**Comment by asottile** [comment]
@modamod that will still release the file lock as they are associated with processes -- the file there is never deleted, only used as a `flock`

**Comment by modamod** [comment]
@asottile  Okay thank you for explaining how it works.
Still the way I got into the issue mentioned above when I accidently hit ctrl+c while pre-commit was running a local hook.

**Comment by serv-inc** [comment]
> was it maybe during `git commit`? there's a known bug with `git` where it zombies git hook executables on interruption (and so it would have to complete naturally) -- you should be able to find the process still holding the lock with a little `ps` or `lsof`

@asottile : does it make sense to check the age of the lock file and suggest removing if it's older than some threshhold ?

**Comment by neetaBirajdar** [comment]
I had the same issue recently, I fixed it with : 
`pre-commit clean ` 
then: 
`pre-commit run` 
it started working for me.

**Comment by reddytocode** [comment]
I don't see someone new making it work the first time. This should be in the docs 😅

**Comment by asottile** [comment]
the recommendation in the original issue is not the correct fix -- the correct fix is to identify what is actually holding the lock and making it progress. `rm -rf`ing a random directory you don't maintain is not a solution

**Comment by jeremy-feng** [comment]
I have the same problem. My solution is to set the language to `system` as my command is using a system bin file.

As mentioned in https://github.com/huacnlee/autocorrect/issues/23, I changed `language` to `system`. Here is my `.pre-commit-config.yaml` that finally works:

```diff
repos:
  - repo: local
    hooks:
      - id: autocorrect-lint
        name: autocorrect lint
        description: "autocorrect-lint"
        entry: autocorrect --lint
-      language: rust
+      language: system
      - id: autocorrect-fix
        name: autocorrect fix
        description: "autocorrect-fix"
        entry: autocorrect --fix
-      language: rust
+      language: system
```

**Comment by asottile** [comment]
that is a bad solution.  you should find what process is holding the lock and then name a decision based on that.  usually with `lsof` or some such
