### ISSUE TITLE
Selecting Python 2 or 3 in Windows using language_version

### ISSUE THREAD

**Issue by absassi** [pre-commit/pre-commit#697]
Is there a way to specify Python version for a hook portably in Windows (non-machine-specific and ideally portable to other systems as well)?

In the [Overriding Language Version](https://pre-commit.com/#overriding-language-version), it is said that `language_version` is passed on to `-p` of `virtualenv`, which enables using, for instance, `language_version: python3` in systems where there is an executable named `python3`. However, in Windows, all CPython versions are simply called `python.exe`, and there is the `py` launcher to select which Python to launch (with `py -3`, for instance). Of course, one can set the `language_version` to the full path to `python.exe`, but then pre-commit configuration becomes machine-specific.

If not possible yet, would it be possible to accept just the version number in the `language_version` for Python (like it is for Ruby) and internally resolving the path to the Python executable to pass to virtualenv?

**Comment by asottile** [comment]
Ah!  This was actually recently fixed as part of [v1.4.3](https://github.com/pre-commit/pre-commit/releases/tag/v1.4.3) but wasn't documented.

Continue to use [PEP394](https://www.python.org/dev/peps/pep-0394/) names that work on unixlike platforms, [pre-commit will translate those into the appropriate `py` launcher call](https://github.com/pre-commit/pre-commit/blob/17444cdfc9a0673c7a92ea78733a2943c0722546/pre_commit/languages/python.py#L44-L52).

So use

```yaml
        language_version: python2
```

or

```yaml
        language_version: python3
```

in fact, this is how our test validates this: https://github.com/pre-commit/pre-commit/blob/17444cdfc9a0673c7a92ea78733a2943c0722546/testing/resources/python3_hooks_repo/.pre-commit-hooks.yaml#L5

**Comment by asottile** [comment]
I've gone ahead and documented this -- thanks again for the issue :)

**Comment by absassi** [comment]
Thanks!
I had tried that and it didn't work. I was going to write a full report now, but then I discovered a typo I did in `language_version`... sorry I didn't noticed that before opening the issue.

**Comment by asottile** [comment]
No big deal! Happy to help :)
