### ISSUE TITLE
Add flake8 hook.  Deprecate pyflakes

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#70]

**Comment by ssbarnea** [comment]
Do we have any backgroung aroung why pyflakes was deprecated? My impression is that pyflakes is still an active project and that flake8 is not a full replacement for it (quite far from it). 

Am i wrong? Should allow people to use pyflakes if they want?

**Comment by asottile** [comment]
`flake8 --select=F` is pyflakes but with features (noqa, multiprocessing, exclusion, etc.)
