### ISSUE TITLE
windows system use sourcetree Or smartGit commit messy code

### ISSUE THREAD

**Issue by lynshir** [pre-commit/pre-commit#727]
```
git -c diff.mnemonicprefix=false -c core.quotepath=false commit -q -F C:\Users\lynsh\AppData\Local\Temp\2h4osxci.03l
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 

```

**Comment by lynshir** [comment]
There's no problem with the MAC. I don't know how to fix it.

**Comment by asottile** [comment]
Is that the output you get?  This doesn't look like our tool at all :)

Do you have some steps such that I can reproduce this?

**Comment by asottile** [comment]
This is what I get from smartgit (working as intended!)

```
C:\Users\IEUser\workspace\pre-commit> git.exe commit --cleanup=whitespace --file=C:\Users\IEUser\AppData\Local\Temp\smartgit-146556333042806257tmp\commit-6499076887067341743.tmp
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace
Files were modified by this hook. Additional output:
Fixing setup.py
Fix End of Files.........................................................Passed
autopep8 wrapper.........................................................Passed
Check docstring is first.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
Flake8...................................................................Passed
Validate Pre-Commit Manifest.........................(no files to check)Skipped
Reorder python imports...................................................Passed
Add trailing commas......................................................Passed
Check hooks apply to the repository..................(no files to check)Skipped
Check for useless excludes...........................(no files to check)Skipped
```

**Comment by lynshir** [comment]
This is what I get from smartgit(the same as sourcetree ) ,i don't know why
`C:\egenie-frontend> git.exe add --force -- dev\static\js\aftersale\aftersale.js
C:\egenie-frontend> git.exe commit --file=C:\Users\lynsh\AppData\Local\Temp\smartgit-3324286294966613101tmp\commit-5273000383387736776.tmp -o -- dev\static\js\aftersale\aftersale.js
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: `

**Comment by lynshir** [comment]
pacage.json

>   "scripts": {
>     "lint": "./lint.sh"
>   },
>   "pre-commit": [
>     "lint"
>   ]
lint.sh

> #!/bin/bash
> 
> git stash -q --keep-index
> 
> git diff-index --cached HEAD --name-only --diff-filter ACMR | egrep '.js$' | xargs $(npm bin)/eslint
> RESULT=$?
> 
> git stash pop -q
> 
> [ $RESULT -ne 0 ] && exit 1
> exit 0

**Comment by asottile** [comment]
Not our project, heh :)  I think you're looking for husky maybe?

**Comment by asottile** [comment]
(plus with our project you wouldn't need the `git stash` or `diff-index` calls, since `pre-commit` handles that for you).

**Comment by lynshir** [comment]
well , thank you very much

**Comment by asottile** [comment]
Cheers!  Good luck tracking down your issue (I suspect it's due to no shebang (`#!`) support on windows -- pre-commit enables this through some [clever bits](https://github.com/pre-commit/pre-commit/blob/fbebd8449423be6703a2eaf84a950c16a1bc93f9/pre_commit/parse_shebang.py#L57-L73))
