### ISSUE TITLE
wont install nodejs based hooks on arm64

### ISSUE THREAD

**Issue by fczuardi** [pre-commit/pre-commit#732]
due to a bug on nodeenv: https://github.com/ekalinin/nodeenv/issues/209

**Comment by asottile** [comment]
Thanks for the heads up!

**Comment by asottile** [comment]
@fczuardi a possible workaround would be to install `node` at the system (through whatever package manager you're using) and use `language_version: system` -- this'll bypass the `nodeenv` download process
