### ISSUE TITLE
pre-commit just stashed all my uncommited files without any warning

### ISSUE THREAD

**Issue by pydo** [pre-commit/pre-commit#733]
**Problem**
pre-commit just stashed all my uncommited files without any warning. The only place where this seems to be documented is under the [advanced features](https://pre-commit.com/#pre-commit-during-commits).

I had no idea how to use the tool to restore them, so I resorted to restoring an earlier snapshot of the repo...

All this happened after I ran `pre-commit` in my project repo. It's a pretty terrible user experience when a CLI tool doesn't warn you before messing with your files.

**Comment by asottile** [comment]
It's supposed to put them back when completed -- if it didn't that's a bug, sorry about that.

If you could provide a reproduction (including stdout, and the patch file if applicable) that would be very helpful!

In a worst-case, `pre-commit` saves a diff of the unstaged contents (and prints the location of the patch file) which can be used to restore the state if pre-commit doesn't do it itself.

The behaviour is actually desirable though, when committing you want the hooks to test the contents of files _as they're being committed_ and not take into account unstaged changes (this is a rather glaring problem with the usual naive approach).  As such, pre-commit saves off a patch of the unstaged diff, clears the staged area, runs the hooks, and then (if everything is working properly!) restores the patch.  Rest assured, the intention is not to leave your repository in a different state than found :)

**Comment by asottile** [comment]
Note that a successful run usually looks like this (note the unstaged diff before and after is the same):

```diff
$ git diff
diff --git a/test.py b/test.py
index 2521db1..c25b21b 100644
--- a/test.py
+++ b/test.py
@@ -1,2 +1,2 @@
 def hello():
-    return 'world'
+    return 'hello world!'
```
```console
$ git commit -m "wat"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.cache/pre-commit/patch1522637775.
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
[INFO] Restored changes from /home/asottile/.cache/pre-commit/patch1522637775.
[wat a80da68] wat
 1 file changed, 2 insertions(+)
```
```diff
$ git diff
diff --git a/test.py b/test.py
index 2521db1..c25b21b 100644
--- a/test.py
+++ b/test.py
@@ -1,2 +1,2 @@
 def hello():
-    return 'world'
+    return 'hello world!'

```

**Comment by pydo** [comment]
**Repro steps**
1. In project repo
2. `pip install pre-commit`
3. `pre-commit install`
4. `pre-commit`

*step 4*  stdout: 
```
╭─user at user-super in /home/user/coding/stream_donation_service (master ✚7…706)
╰(venv)─λ pre-commit                                                                                              0 < 21:22:12
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/user/.cache/pre-commit/patch1522632201.
[INFO] Restored changes from /home/user/.cache/pre-commit/patch1522632201.
An error has occurred: InvalidConfigError: 
=====> /home/user/coding/stream_donation_service/.pre-commit-config.yaml does not exist
Check the log at /home/user/.cache/pre-commit/pre-commit.log
```

**Expected behavior**
My git repo is restored to it's initial state

**Actual behavior**
pre-commit craps out because it can't find a commit file

Thanks for the quick reply, and I did notice the tool stored a patch of my uncommited files. I just chose the safest route by restoring a filesystem snapshot.

**Comment by asottile** [comment]
Hmm, I'm seeing the error (as it should error) but it's restoring the patch for me.  Could you provide a reproduction with a specific repository I can clone and test against (and maybe your `.gitconfig` minus personal details?):

```diff
$ git diff
diff --git a/test.py b/test.py
index 2521db1..fa89502 100644
--- a/test.py
+++ b/test.py
@@ -1,2 +1,2 @@
 def hello():
-    return 'world'
+    return 'hello world'
```
```console
$ pre-commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.cache/pre-commit/patch1522638298.
[INFO] Restored changes from /home/asottile/.cache/pre-commit/patch1522638298.
An error has occurred: InvalidConfigError: 
=====> /tmp/test/.pre-commit-config.yaml does not exist
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```
```diff
$ git diff
diff --git a/test.py b/test.py
index 2521db1..fa89502 100644
--- a/test.py
+++ b/test.py
@@ -1,2 +1,2 @@
 def hello():
-    return 'world'
+    return 'hello world'
```

**Comment by pydo** [comment]
After checking my logs again I realised that I'm stupid and `pre-commit` did in fact restore the stash after running. I panicked after seeing the error and accidentally stashed my files.

my bad

**Comment by asottile** [comment]
No problem 👍 

Thanks for the issue nonetheless :)
