### ISSUE TITLE
pytest doesn't locate tests

### ISSUE THREAD

**Issue by zmitchell** [pre-commit/pre-commit#737]
Hi, I'm having a problem running a local command. I'm using `pipenv` to manage the environment, and I'm using `pytest` to run my tests. My tests are located in `<project>/tests`, and `pytest` locates/runs my tests when I do `pipenv run pytest` from the `<project>` directory. I tried to set up a pre-commit hook that runs `pytest`, and this is what it looks like:

```yaml
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pipenv run pytest
    language: system
```
Here is the error that is produced:
```
pytest...................................................................Failed
hookid: pytest

============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: <path to project>, inifile:
plugins: hypothesis-3.55.6

========================= no tests ran in 0.00 seconds =========================
ERROR: not found: <path to project>/.pre-commit-config.yaml
(no name '<path to project>/.pre-commit-config.yaml' in any of [])

ERROR: not found: <path to project>/Pipfile
(no name '<path to project>/Pipfile' in any of [])

ERROR: not found: <path to project>/Pipfile.lock
(no name '<path to project>/Pipfile.lock' in any of [])
```

I'm not sure what the last three errors are about (they don't show up when I run `pytest` on my own).

**Comment by asottile** [comment]
You'll want [`pass_filenames: false`](https://pre-commit.com/#new-hooks) I believe. Those errors are coming from the modified files being passed to the command specified.

**Comment by zmitchell** [comment]
That does it, thank you!

**Comment by asottile** [comment]
Thanks for the issue! 🎉
