### ISSUE TITLE
Include LICENSE in sdist

### ISSUE THREAD

**Issue by nicoddemus** [pre-commit/pre-commit#745]
Hi @asottile!

I'm creating a conde package for `pre-commit` and noticed that the `sdist` uploaded to PyPI does not contain the `LICENSE` file. It would be nice to include it so other packagers based on the `sdist` can include the license file as well.

**Comment by asottile** [comment]
Sounds fine to me!  Would you like to submit a patch similar to https://github.com/asottile/cfgv/commit/db4ba935f9b86638b25a566cf387ecd91cba86c4 ?

**Comment by nicoddemus** [comment]
Sure thing, done: #746
