### ISSUE TITLE
Detect deleted files

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit#749]
I am trying to create a hook that should run for all deleted files and I am stuck.

My hook's config contains `files: .+` and I currently have this:

```python
def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('filenames', nargs='*', help='Filenames to check')
    args = parser.parse_args(argv)

    for filename in args.filenames:
        is_deleted = os.path.isfile(filename)

        print("is_deleted: " + ("YES" if is_deleted else "NO"))

    return 1


if __name__ == '__main__':
    sys.exit(main())
```

1. Is it true that if a hook returns `0`, its `print`s are not displayed? If yes, how can I make so all `print`s are displayed?
2. Is there any way to receive separate lists for added, modified and deleted files?

**Comment by asottile** [comment]
There's a couple questions here so I'll address them separately :D

### detecting deleted files

pre-commit currently excludes `deleted` files from the list of files it passes to hooks:

https://github.com/pre-commit/pre-commit/blob/823c5bc8c3a9f713ce22849792be50d4a2a23f42/pre_commit/git.py#L84-L85

That said, you can still get the behavior you want through a couple of ways:

From [the docs](https://pre-commit.com/#new-hooks) some combination of `always_run: true` and `pass_filenames: false` enables a tool to be executed disregarding the staged files.  From that you could call `git diff --staged --diff-filter=D` to get deleted files directly (I forget whether this follows moves or not, you'll want to double check that!).  Note that there's a couple hooks in `pre-commit-hooks` that do [something similar](https://github.com/pre-commit/pre-commit-hooks/blob/904a06196df83e5ba5563d0a839103ade2de16b6/pre_commit_hooks/util.py#L12-L15) (but for newly added only).

### returns zero but prints

There's a newish option for hooks, `verbose: true` -- while it's an option, I personally discourage it as it leads to an increase in "warning noise".

### separate lists for added / modified / deleted

Currently no, I also don't really want to add such a feature, if a hook wants this information it can already compute it (and there's precedence for this approach).


Hope this helps!

**Comment by asottile** [comment]
@revolter just checking in :) does this give you the information you need?

**Comment by revolter** [comment]
Sorry for the delay! Seems like a pretty descriptive answer, but I didn't have time to test it. I'll close this for now and reopen after I manage to try it and something doesn't work.

**Comment by revolter** [comment]
[`R` is for renames](https://stackoverflow.com/a/6879568/865175) for the git diff filter.

**Comment by s0undt3ch** [comment]
Could we add a flag so that a hook gets called for matching deleted paths without requiring `always_run` to be True?
I have an expensive hook that shouldn't really `always_run` but should get called for deleted files....

**Comment by asottile** [comment]
per above, my current answer is "no" -- a hook needing this exceedingly special case can write a small amount of logic to short circuit while using `always_run: true`

**Comment by andrewring** [comment]
@asottile I'd like to push back on this a little. Any pre-commit hook that is generates output based files will have problems with this. For example, the [github-distributed-owners](https://github.com/andrewring/github-distributed-owners) tool includes a pre-commit hook to automatically update the generated CODEOWNERS file from OWNERS files embedded in the file tree. We have some internal tools which also run generative tasks in some cases, as well. I would argue that it's not so niche as to be irrelevant.

**Comment by asottile** [comment]
my answer is above.  you're not bringing anything new to the table
