### ISSUE TITLE
Support custom pip binary for python hooks

### ISSUE THREAD

**Issue by firba1** [pre-commit/pre-commit#757]
Currently, we have a hook repository which relies on using [pip-custom-platform](https://github.com/asottile/pip-custom-platform) in order to be installed properly. However, since pre-commit always uses vanilla pip, we're having issues where wheel builds fail on hook install.

**Comment by asottile** [comment]
Do you have a proposal for how this would work?  Currently there's a single invocation of pip:

https://github.com/pre-commit/pre-commit/blob/cf5f8406a1593aa31dcfa5fb2a3766a9ff3f8a96/pre_commit/languages/python.py#L144-L146

**Comment by firba1** [comment]
Unfortunately, I don't really. The biggest issue is probably the fact that pip-custom-platform has to be bootstrapped into the virtualenv before it can be used for installation. I wonder if it might make sense to have a separate language profile specifically for using that? I'm spitballing here.

**Comment by chriskuehl** [comment]
A little orthogonal to the general issue here (there could still be use-cases for using a different `pip` tool), but if we can get traction on https://github.com/pypa/pip/issues/5453, it could make it a lot easier to avoid needing `pip-custom-platform` with pre-commit.

**Comment by chriskuehl** [comment]
@asottile if we could find a reasonable way to implement this, would you take a patch? Or is this something you think should be solved outside of pre-commit somehow?

This is causing us quite a bit of trouble as we don't have linux_x86_64 wheels anymore on our internal PyPI, requiring us to build packages on every install.

**Comment by asottile** [comment]
Yeah I don't think the idea is completely unreasonable, but there's no proposal here yet :)

**Comment by asottile** [comment]
(an aside: we're tackling this with separate subdirectories on a single pypi server, basically `export PIP_INDEX_URL="https://pypi.example.com/${DISTRIB_CODENAME}/simple"`)

**Comment by asottile** [comment]
I don't think this'll ever be done so I'm going to close this
