### ISSUE TITLE
CI Artifacts

### ISSUE THREAD

**Issue by dcramer** [pre-commit/pre-commit#765]
Apologies if I missed this somewhere.

We'd like to move all of our manual usage of flake8, eslint, etc onto pre-commit. The problem today is we do two different things:

1. Lint on-demand (e.g. VS Code) and pre-commit [solved]
2. Lint in CI with artifact generation

The latter is a serious issue right now as we need various artifacts form different tools.

To give you an example, here's a couple commands we run that are CI-specific:

```
- flake8 > flake8.log
- node_modules/.bin/eslint webapp --format=checkstyle > checkstyle.xml
```

**Comment by asottile** [comment]
Hello! Thanks for the issue, I believe you're looking for [`log_file`](https://pre-commit.com/#pre-commit-configyaml---hooks) perhaps?

**Comment by dcramer** [comment]
@asottile thanks will confirm this + args can solve the problem

it does seem like there might be a better approach though, given configuring log_file I'd have to configure default args, which means these would always dump these files somewhere.

**Comment by dcramer** [comment]
This will work for now though I can see some cases where running pre-commit with different config/args would be useful.

**Comment by asottile** [comment]
There's a few options for doing that today.
- Have a separate config and use `pre-commit run -c {alternate config filename}`
    - downsides: you'd potentially duplicate the common things
    - upsides: keeps things explicitly separate
    - you could even just put ~special things into a separate config and invoke both (once with the default config, once with the custom config)
- Configure specific hooks as [`stages: [manual]`](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) -- these won't run during the _normal_ workflow but you can trigger them by running `pre-commit run --hook-stage manual`

**Comment by asottile** [comment]
Just so it's easier for me to trace, this is for https://github.com/getsentry/responses/pull/199 correct?

**Comment by dcramer** [comment]
@asottile yeah -- to some degree Im using responses and getsentry/zeus as test beds for what we might be able to apply more largely in Sentry's projects

**Comment by asottile** [comment]
Sounds great!  feel free to reach out and I'll help where I can :)

**Comment by dcramer** [comment]
Also related PR for Zeus: https://github.com/getsentry/zeus/pull/116/commits/3df65bb37b7caa8e1472cfd6a29ca841b07f2cea

**Comment by artcyb** [comment]
haha
