### ISSUE TITLE
is there any irc channel for pre-commit?

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#783]
I tried to find an irc channel on freenode, on website and on github and i found only one indication on a comment that you are using irc (but without channel name).

I think it would be very useful to have a pre-commit channel where we can ask simple questions.

**Comment by asottile** [comment]
Indeed, I personally hang out on freenode but haven't set up a channel specifically for pre-commit.  I myself often hang out in `#pylib` (tox / pytest) channel but I'm not sure we'd want to take that one over for their sake 😆.

I've created and joined `#pre-commit` so we can start from that!

**Comment by ssbarnea** [comment]
Thanks! I will remain connected to the channel.

**Comment by ssbarnea** [comment]
Considering that I was the only user on #pre-commit channel for a long time, I do think that it would make sense to re-use `#pylib` channel for pre-commit tool too.

**Comment by asottile** [comment]
I've been planning to move to discord, I've set up a #pre-commit channel in my stream chat: https://discord.gg/HxpQ3px

needs documentation though

**Comment by graingert** [comment]
> I've been planning to move to discord, I've set up a #pre-commit channel in my stream chat: [discord.gg/HxpQ3px](https://discord.gg/HxpQ3px)
> 
> needs documentation though

@asottile looks like this invite link is now invalid

**Comment by ssbarnea** [comment]
@graingert there is also a lot of pre-commit content on Twitch too.

**Comment by asottile** [comment]
oops!  looks like it expired for some reason -- here's the new link: https://discord.gg/xDKGPaW

**Comment by graingert** [comment]
@asottile I think you can create a vanity link with a human readable name

**Comment by asottile** [comment]
I don't have discord premium or whatever it is otherwise I could :(
