### ISSUE TITLE
document way to specify which python interpreter is to be used

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#793]
Currently python language is using default python which is likely python2 and the python_venv language has an extra dependency on python-venv which makes it impossible to use.

As a linter and git-hook, pre-commit should be able to install hooks that use python2 or python3 without requiring any extra preparatory tasks. 

I would advocate for having a `python3` and `python2` language which would use python3 just like python one which has no major version defined. 

My current experience was that is common to find tools that do explicitly work with only one of them. Still, there is also the question about making difference between versions of py3 as we know that user may have multiple python3 interpreters installed at the same time too.

I know that I can install python-venv for myself easily but I cannot expect this to be done by the users, especially for a pre-commit hook which is likely to cause weird issues, especially if they use various git GUIs.

Any idea on how to fix this?

**Comment by asottile** [comment]
[overriding language version](https://pre-commit.com/#overriding-language-version) documents how to do this.

For example:

```yaml
    -   id: my-hook
        language_version: python3
```

**Comment by asottile** [comment]
going to close this given it _is_ documented, let's continue discussion in #794
