### ISSUE TITLE
hook to enforce the 50/72 rule on commit messages

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#802]
Most projects do ask contributors to follow the well known [50/72 rule](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting) for commit message and 
having a hook that checks for this would be extremely useful because is so easy to break the rule
while editing the message.

**Comment by asottile** [comment]
I think [gitlint](https://github.com/jorisroovers/gitlint) has stuff for this (already has pre-commit integration)?

**Comment by ssbarnea** [comment]
I spend the last couple of hours trying to implement gitlint hook but I found some reasons to worry, first I had to run `pre-commit install --hook-type commit-msg` in order to activate this, something I never had to to with other repositories.

Second problem is that I discovered that neither `pre-commit run` nor `pre-commit run --all-files` managed to run this check. They silently skip it.

This is a real issue because the way I introduced pre-commit on various projects was by including execution of "python -m pre_commit --all-files" inside one of the `tox.ini` environments ("lint"). CI jobs would fail this step if something is wrong but apparently this is not enough for testing the commit-message.

I guess that I am missing something here.

**Comment by asottile** [comment]
> first I had to run pre-commit install --hook-type commit-msg in order to activate this, something I never had to to with other repositories.

`commit-msg` is a separate hook from `pre-commit` so it is installed separately (the same is also true for `pre-push` which is supported by `pre-commit`).  That is, they install different hook executables in `.git/hooks`.  All the other repositories you worked with were `commit` hooks and so the default `pre-commit install` set those up for you.

> Second problem is that I discovered that neither pre-commit run nor pre-commit run --all-files managed to run this check. They silently skip it.

`pre-commit run` takes a `--hook-stage` argument (which is usually used during invocation by specific hooks (`commit` / `commit-msg` / `push`).  To run a `commit-msg` hook you'd use `--hook-stage commit-msg`.

As for linting commits that already exist, you'd probably need to invoke `gitlint` in a different way (with `--commits`?) -- I haven't tried it myself but it looks like others https://github.com/jumanjihouse/autostager/commit/f50e61533ceb7d73abe00c2049a4e89f67baf38b#diff-82c3b36709926de3a1b27bea0d8258ccR50

**Comment by rico-chet** [comment]
> `pre-commit run` takes a `--hook-stage` argument

This is seriously under-documented, I've been trying to run my `gitlint` hooks on existing commits and by luck, @ssbarnea had the same problem.

By the way, did you manage to run `gitlint` on a range of commits provided via `--source` and `--origin` parameters via `pre-commit`?

**Comment by asottile** [comment]
> > pre-commit run takes a --hook-stage argument
>
> This is seriously under-documented,

It's listed [here](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) and in `pre-commit run --help` -- if there's somewhere else you'd like to see this in the documentation please make a [PR](https://github.com/pre-commit/pre-commit.github.io)! 😄 

```
$ pre-commit run --help | grep -A2 ' --hook-stage'
  --hook-stage {commit,commit-msg,manual,push}
                        The stage during which the hook is fired. One of
                        commit, commit-msg, manual, push
```

**Comment by rico-chet** [comment]
I've been looking at [pre-commit run [hook-id] [options]](https://pre-commit.com/#pre-commit-run) and it wasn't there. The web page is the primary source of documentation for me currently.
And the place you linked to only mentions `stages: [manual]`, so who would guess that this applies to `commit-msg` too?

Also, `pre-commit run` options' descriptions only make sense in context of certain hooks, so this is also worth improving.

As a `pre-commit` beginner, I don't believe I can make good PRs for the docs ^_^

**Comment by asottile** [comment]
I'm not sure there's anything left here? if there is please comment and I'll reopen -- thanks for the issue :tada:

**Comment by bristea** [comment]
Out of curiosity, is any way to make `pre-commit run` perform any linting of last commit message? I am looking for a way to expand the default linting command without asking users to run additional commands or to install git hooks.
