### ISSUE TITLE
Create `language: fail` for filename-only checks

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#807]
For example, it would be useful here:

https://github.com/pytest-dev/pytest/pull/3765/files

v1 could just print the filenames and exit nonzero, potentially with a `--message` option.

**Comment by chriskuehl** [comment]
+1, here's another case where this could be useful:
https://github.com/ocf/ocfweb/blob/f166a3159da560eb871ebd3a375606ba5a240912/.pre-commit-config.yaml#L67-L71
