### ISSUE TITLE
python3.7: command not found

### ISSUE THREAD

**Issue by cancan101** [pre-commit/pre-commit#810]
If I set  `language_version: python3.7` rather than `language_version: python3`, I get the following error. I am using pyenv-virtualenv:

```
An unexpected error has occurred: CalledProcessError: Command: ('/Users/alex/.pyenv/versions/3.7.0/envs/xxxx/bin/python', '-mvirtualenv', '/Users/alex/.cache/pre-commit/repoxj_919t6/py_env-python3.7', '-p', 'python3.7')
Return code: 127
Expected return code: 0
Output:
repos:
    Running virtualenv with interpreter /Users/alex/.pyenv/shims/python3.7

Errors:
    pyenv: python3.7: command not found

    The `python3.7' command exists in these Python versions:
      3.7.0
```
This may be related to: https://github.com/pyenv/pyenv-virtualenv/issues/206

**Comment by asottile** [comment]
what does `python3.7 -c 'print("hello world")'` say?

**Comment by cancan101** [comment]
```
pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.0
```

**Comment by asottile** [comment]
Looks like your `python3.7` is misconfigured / not installed.

I haven't worked much with `pyenv` myself but I believe you need to do something like `pyenv install 3.7.0` and `pyenv global 3.7.0` (or something of the sort? maybe the second one isn't necessary?)

`pre-commit` itself doesn't have any _direct_ integration with `pyenv`, though it is known to work with it fine as long as you have things set up properly -- notably, pre-commit will call `virtualenv -p $language_version` and if the python referenced by `language_version` isn't functional -- well then you'll see what you're seeing 😆

**Comment by asottile** [comment]
closing this since this is likely an issue with your setup @cancan101 

If it's not, feel free to comment / reopen!

**Comment by thomasfowler** [comment]
Just adding this here for anyone that comes across this issue.

When you create a virtualenv using, for example, `pyenv virtualenv 3.7.0 example_venv`, the command `python3.7` will not work once that virtualenv is activated.

In order to make the command `python3.7` work in an activated virtualenv, you need to tell `pyenv virtualenv` what additional commands too use.

So, to correctly setup the virtualenv to work with pre-commit, run the command as:

`pyenv virtualenv -p python3.7 3.7.0 example_venv`

This should resolve the issue reported.

**Comment by hongfuli** [comment]
Create a symbolic link
```bash
cd /Users/alex/.pyenv/versions/3.7.0/bin/
ln -s python3 python3.7
```

**Comment by mzack5020** [comment]
> Just adding this here for anyone that comes across this issue.
> 
> When you create a virtualenv using, for example, `pyenv virtualenv 3.7.0 example_venv`, the command `python3.7` will not work once that virtualenv is activated.
> 
> In order to make the command `python3.7` work in an activated virtualenv, you need to tell `pyenv virtualenv` what additional commands too use.
> 
> So, to correctly setup the virtualenv to work with pre-commit, run the command as:
> 
> `pyenv virtualenv -p python3.7 3.7.0 example_venv`
> 
> This should resolve the issue reported.

You're awesome. Worked like a charm

**Comment by gvizquel** [comment]
In my case I am working with pipenv and I get this error:

`    python ('/.../.local/share/virtualenvs/guvniOjd/bin/python3.7m', '-mvirtualenv', '/.../.cache/pre-commit/repohfwzvhx1/py_env-python3.7m', '-p', 'python3.7m')`

```
python3.7m -c 'print("hello world")'
hello world
```
I would appreciate any help.

Thanks

**Comment by asottile** [comment]
paste your full error message -- if it doesn't exactly match the output of OP's then it's a different issue

**Comment by gvizquel** [comment]
```
An unexpected error has occurred: CalledProcessError: command: ('/.../.local/share/virtualenvs/guvniOjd/bin/python3.7m', '-mvirtualenv', '/.../.cache/pre-commit/repohfwzvhx1/py_env-python3.7m', '-p', 'python3.7m')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'
```

Thanks

**Comment by asottile** [comment]
yeah that's a completely different error message as I suspected, what does `virtualenv venv -p python3.7m` give you? (if that fails, please create an issue on pypa/virtualenv)

**Comment by gvizquel** [comment]
```
virtualenv venv -p python3.7m
Running virtualenv with interpreter /usr/local/bin/python3.7m
Using base prefix '/usr/local'
/usr/lib/python3/dist-packages/virtualenv.py:1090: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /.../venv/bin/python3.7m
Also creating executable in /.../venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
```

**Comment by asottile** [comment]
use the same version of virtualenv (the error above is from virtualenv 20.x, your output is from virtualenv<20)

**Comment by asottile** [comment]
nevermind I'll do it for you

**Comment by asottile** [comment]
here's the upstream issue @gvizquel  -- you can work around by installing `virtualenv<20` alongside pre-commit

**Comment by gvizquel** [comment]
Thanks very much @asottile a will try it

**Comment by JackTheMico** [comment]
@thomasfowler Thank you very much! I googled this about a hour, finally make it worked with your solution.
This should be recorded somewhere

**Comment by asottile** [comment]
@JackTheMico please don't bump 2 year old issues with a "thanks" message -- that's what the thumbs up button is for
