### ISSUE TITLE
PyCharm support [feature request]

### ISSUE THREAD

**Issue by 1oglop1** [pre-commit/pre-commit#814]
Hi, is there any plan to create some plugin which would support pycharm UI?
Right now it does not look very good in pycharm, because event baloon does not have colours and proper formatting as shell.

![image](https://user-images.githubusercontent.com/7480694/44134337-c53ba8e4-a064-11e8-8a0c-e50aacef129b.png)

And it's not as easy to read the results.

**Comment by asottile** [comment]
There are no current plans (nor boring implemented that I know of) but I'm not opposed to the idea. If you want to hack on something I can add a repo to the org for editor plug-ins!

**Comment by asottile** [comment]
Let's continue the discussion here instead: https://github.com/pre-commit/pre-commit.github.io/issues/185
