### ISSUE TITLE
Execute python tasks as part of pre-commit

### ISSUE THREAD

**Issue by splnanthakumar** [pre-commit/pre-commit#816]
Hi ,
     how to define my local tasks as part of pre-commit ?
    is there a way to define in .pre-commit-config.yaml file to provide path?

I am using tasks.py which is having few tasks (basically UnitTest tasks). I am running this via terminal everytime before commit my code. i wanted to add this as part of pre-commit. please guide me on this

**Comment by asottile** [comment]
I believe you may be looking for [`local`](https://pre-commit.com/#repository-local-hooks) hooks?

In your case you probably also want `always_run: true` and `pass_filenames: false` though you'll know best!

**Comment by asottile** [comment]
@splnanthakumar did this help? anything more I can help you with?

**Comment by splnanthakumar** [comment]
i hope you would be knowing the "tasks" in python. i am executing unittest by calling a task (ie.  $invoke unittest) from command line.
i wanted to execute command line as one of the pre-commit check. 

i have added  in .pre-commit-config.yaml file:
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: invoke unittest
        language: system
        types: [python]


i am getting error as below:
unittest.................................................................Failed
hookid: unittest

No idea what 'com/aruba/test_hook.py' is!

i am not getting what is the error?

**Comment by asottile** [comment]
As I stated above, you probably want `pass_filenames: false` (by default pre-commit will pass the changed filenames as positional arguments)

**Comment by splnanthakumar** [comment]
yeah i got it . i solved it by passing the filename

entry should be pointing the file where file will be containing the 

-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python -m tasks
        language: system
        types: [python]

"tasks.py" is the file and i have added the following condition to invoke a specific task
if__name__=='__main__'
launch_function()

Thankyou for your help.
