### ISSUE TITLE
pygrep to work with commited chunk only

### ISSUE THREAD

**Issue by tmuras** [pre-commit/pre-commit#817]
pygrep is currently searching the entire file. It would be nice to have an option to only check the change/chunk being committed.

**Comment by asottile** [comment]
I'd like to understand your usecase more before considering this.

Currently the framework is intentionally "take filenames, pass them to hooks" and doesn't really concern itself with what the hooks do.

That said, I personally think "linting partial diffs" isn't a reasonable goal and for the most part the current hook implementations agree ([one](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_added_large_files.py) [two](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_merge_conflict.py) exceptions -- but for _good_ reasons).  Most of my resistance comes from the following reasoning:

- Partial linting leads to inconsistency, new code doesn't look like old code which is almost worse
- Move the code? haha sucks to be you now you get to reformat it
- If someone bypasses the hooks (via `SKIP` or (hopefully not) `--no-verify`) then it is easy to sneak in new bad code
- What to do during commit of conflict resolution?  Lint all three places that could be introducing code?

I **do** understand the want to _incrementally_ introduce new linting -- and the framework gives you the ability to do that as long as you're opting in file-by-file (through either `files` or `exclude` (the latter is easier to incrementally apply as new files will be required to adhere by default).  And then you either fix file-by-file or directory-by-directory or however you want to approach it.

Curious to hear your thoughts on this!

Also note that `pygrep` is intended to be _dead simple_ so I'm also hesitant to add complexity there :)

**Comment by asottile** [comment]
Sounds like you should be doing ast-based checks instead and then you can have fewer false positives.

I'm going to reject this feature for now but keep this as a data point for potential future implementation.

Thanks for the issue!
