### ISSUE TITLE
Python executable and/or `libpython` are not running

### ISSUE THREAD

**Issue by slochower** [pre-commit/pre-commit#825]
Hi, I just tried to setup pre-commit with an existing repository and I'm getting a seemingly rare `libpython` error (I can't find any similar reports).

1. I installed pre-commit using `pip install pre-commit`.
2. I edited `.pre-commit-config.yaml` to include:
```python
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
```
3. I then ran `pre-commit install`.
4. Finally, I added and commited `.pre-commit-config.yaml` using `git`.

I get an error saying the Python 3.6 executable is not functioning.

```
An unexpected error has occurred: CalledProcessError: Command: ('/home/XXX/data/applications/anaconda3/bin/python', '-mvirtualenv', '/home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6', '-p', 'python3.6')
Return code: 100
Expected return code: 0
Output:
    Using base prefix '/home/XXX/data/applications/anaconda3'
    New python executable in /home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6/bin/python3.6
    Also creating executable in /home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6/bin/python
    ERROR: The executable /home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6/bin/python3.6 is not functioning
    ERROR: It thinks sys.prefix is '/' (should be '/home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6')
    ERROR: virtualenv is not compatible with this system or executable
    Running virtualenv with interpreter /home/XXX/data/applications/anaconda3/bin/python3.6

Errors:
    /home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6/bin/python3.6: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

````
It seems something is removing the cache directory upon failure, so I can't check if `/home/XXX/.cache/pre-commit/reponv7xlyy1/py_env-python3.6/bin/python` is functioning correctly. I *can* see stuff in `/home/XXX/.cache/pre-commit/reponv7xlyy1/` but not in the `py_env-python3.6` subdirectory.

- CentOS 7.4
- Python 3.6.4
- pre-commit 1.10.1

**Comment by asottile** [comment]
I've seen this many-a-time with macos: #770 #631 #419 but never with centos.

The triage steps in those should help though, particuarly:

```bash
which python3.6
which virtualenv
which pre-commit
head -1 $(which virtualenv)
head -1 $(which pre-commit)
virtualenv venv -ppython3.6
```

I suspect this is a misconfiguration of either your python3.6 installation or your installation of virtualenv but without more information I'm unsure

-----

oh, actually after looking at this I noticed this line:

```
    Running virtualenv with interpreter /home/XXX/data/applications/anaconda3/bin/python3.6
```

if I recall correctly conda does silly things that require its own patched `virtualenv`, I think you might be able to `conda install pre-commit` instead of `pip` and use it that way, that said `conda` integration is neither supported / maintained and so you're mostly on your own.

https://github.com/pypa/virtualenv/issues/1051 for the upstream issue there

**Comment by slochower** [comment]
Thanks for the quick reply.

I first did the installation with `conda`, which pulled in a new copy of `virtualenv`. This seems to have fixed the problem (at least, in combination with running `virtualenv venv -ppython3.6`)!

**Comment by asottile** [comment]
Sweet! good to hear
