### ISSUE TITLE
Ability to define hook based on third party GitHub repo

### ISSUE THREAD

**Issue by petergaultney** [pre-commit/pre-commit#827]
I feel like I'm missing something obvious, but after about 30 minutes of searching and reading documentation I've come up empty, so here goes...

There are various linters and other tools out there that I'd like to be able to run on my repo at pre-commit time, that are either node modules in npm, pip modules in PyPi, or something similar that is supported by pre-commit. All I need to be able to do is require that they be downloaded, installed, and run at pre-commit time. However, many of those tools don't define a .pre-commit-hooks.yaml file in their Github repo.

As an example, https://github.com/cjoudrey/graphql-schema-linter

It seems that pre-commit is only interested in allowing me to use them if they're willing to define that hooks.yaml  (I get an InvalidManifestError because no hooks.yaml file exists). Whereas I feel I should be able to use them by defining the full config in my own end-repo's .pre-commit-config.yaml. 

What am I missing? What does requiring that file to be present in the external repo accomplish that couldn't legitimately be accomplished in my local config? I just need the module installed and then run.

Presumably there are workarounds that involve defining my own repo that 'wraps' the external repo, or making a fork and adding a hooks.yaml. But that's extra work and risks getting me out of sync with the upstream.

**Comment by asottile** [comment]
I _believe_ you're looking for [repository `local` hooks](https://pre-commit.com/#repository-local-hooks).  There's also [`pre-commit-mirror-maker`](https://github.com/pre-commit/pre-commit-mirror-maker) for making wrapping repositories

Ideally though, contributing the pre-commit metadata to upstreams is preferred as others can benefit from the configuration.

**Comment by asottile** [comment]
@petergaultney hope this answered your question! If not please comment below and I'll reopen.

Thanks for the issue 🎉
