### ISSUE TITLE
Does not create .git/hooks/pre-commit file when pre-commit is installed

### ISSUE THREAD

**Issue by anithats** [pre-commit/pre-commit#830]
package.json
"scripts": {
   "checkeslint": "echo \"hi\" && ./pre-commit"
  },
"devDependencies": {
  "pre-commit": "^1.2.2",
  },
  "pre-commit": [
    "checkeslint"
  ]

pre-commit is a script i want to run on git commit 

When i run npm install, no ./git/hooks/pre-commit file gets created. On git commit, the script is not executed. The script runs perfectly fine on npm run checkeslint. Also, on manually creating the pre-commit file, git commit works as expected. 

Please let me know what i am missing.

**Comment by asottile** [comment]
You have the wrong project, that's the node project by the same name

**Comment by anithats** [comment]
Could you please tell me the right project name that i could use?

**Comment by asottile** [comment]
I'd start by searching for that package in the package manager you used to install it.  In this case npm:

- searching google for ["npm pre-commit"](https://www.google.com/search?q=npm+pre-commit)
- leads me to [the npm page](https://www.npmjs.com/package/pre-commit)
- from that clicking on [github](https://github.com/observing/pre-commit)

Note that their package is entirely unrelated to ours, they do not have the same features or functionality.
