### ISSUE TITLE
How to pass a flag as part of the commit ?

### ISSUE THREAD

**Issue by splnanthakumar** [pre-commit/pre-commit#834]
Hi,
   my pre-commit works fine. whenever i try to commit there are 2 hooks.
1.check for python code format
2.run unittest cases

now, i want to run unittest case as part of the flag comes from commit.
(ex: git commit -m "commit messgae" --UT)
is it possible to provide a flag when we do commit?

**Comment by asottile** [comment]
git does not allow passing through of arguments (for instance why SKIP is an environment variable).

If you always want to pass the argument there's [`args: [...] `](https://pre-commit.com/#passing-arguments-to-hooks) in the configuration, though it sounds like you want to ad-hoc send arbitrary arguments?

Another idea if you want to use a fixed command for lint and a different one for commit is to use the [`manual` stage](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) .

**Comment by splnanthakumar** [comment]
thanks for your response @asottile . but args in config is will not yield much efficiency. may i know how "SKIP" works? do you know any document or video tutorials

**Comment by asottile** [comment]
yep! sorry thought I linked it above: [temporarily disabling hooks](https://pre-commit.com/#temporarily-disabling-hooks)

**Comment by asottile** [comment]
If there's more to follow up on, please comment and I can reopen, thanks for the issue!
