### ISSUE TITLE
Hook of type "script" runs multiple times?

### ISSUE THREAD

**Issue by pzelnip** [pre-commit/pre-commit#836]
I have the following `.pre-commit-hooks.yaml`:

```
-   id: test
    name: test
    # description: "test"
    entry: test.sh
    language: script
    types: [text]
```

And in test.sh I have the following:

```
#!/bin/sh

echo "Hello world"
```

When I run it, I see it's run twice:

```
$ pre-commit try-repo ../pre-commit-hooks/ test --verbose --all-files
===============================================================================
Using config:
===============================================================================
repos:
-   repo: ../pre-commit-hooks/
    rev: 61f32d1163a408cd4c867035929ff53670e01e8e
    hooks:
    -   id: test
===============================================================================
[INFO] Initializing environment for ../pre-commit-hooks/.
[test] test..............................................................Passed
hookid: test

Hello world
Hello world
```

Why does the script get executed twice?

**Comment by asottile** [comment]
By default, matching filenames are passed to the hooks as positional arguments.  You can turn this off with `pass_filenames: false`.

pre-commit implements a pure-python [`xargs`](https://en.wikipedia.org/wiki/Xargs) which is [overly timid](https://github.com/pre-commit/pre-commit/issues/691#issuecomment-360172836) to support windows.  There's plans in that linked issue to increase chunk size on posix platforms which can support longer argument strings, though no one has stepped up to implement it.  There's code hints in [this comment](https://github.com/pre-commit/pre-commit/issues/691#issuecomment-360224845) if you wanted to tackle it!

**Comment by pzelnip** [comment]
Perfect, the ```pass_filenames: false``` fixed the issue for me.  Thanks!

**Comment by bsolomon1124** [comment]
For any future readers: an example of where this is useful:

```yaml
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.9.0
  hooks:
  - id: markdownlint
    args: ['-g', '-d', '-u', 'mdl_rules/rules.rb', '.']
    pass_filenames: false
```

In this case, since `mdl` is already passed the positional arg `.`, using `pass_filenames: false` will avoid a duplicate lint.

**Comment by asottile** [comment]
fwiw you probably don't want `pass_filenames: false` in 99% of cases -- it breaks the whole "only run on changed files" guarantees and will make all runs significantly slower

**Comment by bsolomon1124** [comment]
Would the solution in that case be to leave off the positional `.` to `mdl` at @asottile ?

We noticed that when we used just:

```
  - id: markdownlint
    args: ['-g', '-d', '-u', 'mdl_rules/rules.rb', '.']
```

without specifying `pass_filenames`, that `mdl` appeared to be run twice.

**Comment by asottile** [comment]
yes, it's fairly normal to run N times due to the automatic multiprocessing employed -- you can use [`require_serial: true`](https://pre-commit.com/#creating-new-hooks) if you'd like to make it more likely to only run once (though usually, that'll make your execution slower)

**Comment by kevmurray** [comment]
Another example for future readers: Our pre-commit hooks run the unit tests, effectively calling `make test`. Without `pass_filenames: false` we were running the tests once-per-file instead of once-per-commit. So if you are using script-based hooks that treat the project as a whole, you'll really want `pass_filenames: false`
