### ISSUE TITLE
document/set up support tooling for editor integrations

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pre-commit/pre-commit#838]
follow-up to https://github.com/jgirardet/sublack/issues/31

as i conversed with sublack author, it became apparent that its pretty hard/tricky to integrate pre-commit/black for example with editor integrations (in order to fix exact project set-ups)

i wonder if the issue can be elevated/helped in some way

**Comment by asottile** [comment]
I've used `pre-commit run --files $filename` myself w/ editors which works pretty well.  This does require that the file is written out beforehand 🤷‍♂️

**Comment by asottile** [comment]
@RonnyPfannschmidt can you reopen this on the docs repo? https://github.com/pre-commit/pre-commit.github.io

**Comment by RonnyPfannschmidt** [comment]
@asottile i suppose supporting input from streams is not directly sensible=?

**Comment by asottile** [comment]
pre-commit works entirely on filenames today -- it could _probably_ be made to support `/dev/stdin` / `-` (and skip filtering it against the checked in files)?  I'd have to see a pretty good reason for it though :) (and I'm not sure avoiding a disk flush is really going to save _that_ much time)

**Comment by jgirardet** [comment]
hi @asottile .
Indeed using tempfile is not a big performance issue. I tested.
The main  problem. is the pre-commit running time.

@RonnyPfannschmidt asked me for using same version of black (in editor and command line) via pre-commit.
I see 2 ways of doing it keeping run time as slow as possible:
 - pre-commit could have a "skip-pre-commit" ;-) option to directly run the hook, skipping all the precommit stuf. if it accepts arguments we are ultimate.
 - expose the hook path via a "hook info" option or something like this so we could run directly the right executable from pre-commit repo.
