### ISSUE TITLE
port to packaging to avoid pkg_resources import cost

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pre-commit/pre-commit#840]
its expensive to import pkg_resources  if all that's needed is version parsing of packaging

it should be relatively straightforward to simplify and port

**Comment by asottile** [comment]
It's not just that, is there a direct replacement for https://github.com/pre-commit/pre-commit/blob/c0b1f2ff25b53efcfa03098f2b4cb90ded905063/pre_commit/constants.py#L21

**Comment by RonnyPfannschmidt** [comment]
@asottile that part needs a little expansion, personally i'd propose setuptools_scm and writing a version file to the package as importation is so much faster than workingset construction and packageset iteration

**Comment by asottile** [comment]
Nothing personal, but I'm not going to use setuptools-scm, it seems a bit over engineered for what equates to writing a text file.

There's three parts here that need solving:
- self-referential version number
- resource files
- version comparison

The first can reasonably be solved with writing a version number at install time, I _really_ don't want to get `setup_requires` (eggs) involved.

The second is a bit trickier, maybe `importlib_resources`? (backport of 3.7 package) -- that pulls in a lot of dependencies for something that to me seems like it should be simple.  Should I care to support eggs and zipimport as distribution methods for `pre-commit`? Should I require consumers to use pip (or equivalent)?

The third is by far the easiest, pre-commit doesn't have any complicated version numbers (yet, and I don't plan on it) and really it can be replaced with `map(int, s.split('.'))`

**Comment by asottile** [comment]
and hmm, even `setuptools-scm` suggest using `pkg_resources`: https://github.com/pypa/setuptools_scm#setuppy-usage

**Comment by RonnyPfannschmidt** [comment]
@asottile im the maintainer there that wrote the suggestion, its generally more useful for packages that do not have import time constraints - for example pytest uses the entrypoint system excessively anyway
