### ISSUE TITLE
CLI --types option

### ISSUE THREAD

**Issue by dkolepp** [pre-commit/pre-commit#841]
What does the types tag "directory" do?  Git only provides a list of changed files to pre-commit- but what if I am trying to run a pre-commit hook on a sub-directory from which a changed file came from?  Is there a way to do that?  Is there a way to utilize capture groups in the associated regex that defines each hook?

In particular, I am trying to use ansible-lint with pre-commit.  The files that are changed are coming from an ansible role directory, and ansible-lint should be tested on the role as a whole, not the individual file that was changed.

**Comment by dkolepp** [comment]
Your understanding of the scenario is correct.  When `dir2/f.py` is changed, I actually want to process the `dir2` directory.  Ansible-lint can can lint either playbooks, or roles.  A playbook is a single file (this works brilliantly with pre-commit) but roles are grouped by a directory.  The linter, for roles, is expecting a certain directory structure.  The project has both playbooks and projects, and I want to lint both types of artifacts.

This helps a great deal - thanks!

**Comment by asottile** [comment]
Awesome! Let me know what you come up with :) -- I don't think there's anything left here though am I ok to close the issue?

**Comment by dkolepp** [comment]
Yep- free to close. Wanted to tag this as a question but wasn’t sure how to
do that.

**Comment by asottile** [comment]
No problem :) I tagged it for you!

Thanks again for the issue 🎉
