### ISSUE TITLE
Create mirrors for bandit

### ISSUE THREAD

**Issue by KPilnacek** [pre-commit/pre-commit#849]
Dear authors of pre-commit,

I happy user of this package. Thank you for that.

I'd like to have a mirror of the `bandit` package. I created it [myself in my profile](https://github.com/KPilnacek/mirrors-bandit), however, I think it would be more appropriate to have it here.

Would it be possible to transfer under your wings?

With regards
Krystof

**Comment by asottile** [comment]
@KPilnacek this is awesome, thanks for putting in the work for this!

https://github.com/pre-commit/pre-commit.github.io/pull/188 will make it appear on the website :tada:
