### ISSUE TITLE
How to test hook arguments with `try-repo`?

### ISSUE THREAD

**Issue by metmajer** [pre-commit/pre-commit#850]
Hi there!

I am in the process of making a contribution to a pre-commit hooks repo to enable arbitrary arguments to be mixed into the execution of certain processes. In order to test the correct behavior of my contribution, I was looking into `pre-commit try-repo`. However, neither `try-repo` nor `run` allows the configuration of extra arguments for the pre-commit hook.

Any suggestions? Thanks!

**Comment by metmajer** [comment]
@asottile wow, thank you so much for your elaborate answer. I've found a neat way to test the hook and circumvent the need to push code to my repository for changes to take effect by using a `repo: local` directive:

```
 repos:
 - repo: local
   hooks:
   - id: terraform_docs
     name: terraform_docs
     entry: ./terraform_docs.sh
     language: system
     files: (\.tf)$
```

Then, I run `pre-commit run terraform_docs --files ./variables.tf ./outputs.tf`, make local changes and re-run if the results are not as expected. To me, this is the best option for now and this also qualifies for an automated test using [Bats](https://github.com/bats-core/bats-core). Here's a longer description of the approach for your consideration: https://github.com/antonbabenko/pre-commit-terraform/pull/25#issuecomment-431649551. Thoughts?

I would love to see a `--args` option that requires a hook to be provided, but then again, if coupled with `try-repo`, the need to push code before it can be tested would still remain, which in my mind, conflicts with the goal of continuous integration (always keeping the repo in a releasable state).

Anyways, this is such a great project and does an amazing job in building more quality and discipline into our deliverables. Thank you so much!

**Comment by metmajer** [comment]
@asottile as I have found a solution that works for me, feel free to close!

**Comment by asottile** [comment]
Cheers!  Thanks for the issue

**Comment by George-Ogden** [comment]
> If there's a potential feature here, it would have to be limited to the case where pre-commit try-repo is invoked with a particular hook in mind (pre-commit try-repo https://github.com/asottile/pyupgrade pyupgrade --args=...) for instance. Then there's a decision about the ergonomics of the --args command. Would it be --args 1,2,3 and then comma splitting (and escaped commas, bleh) or something like --args 1 2 3 ... (using nargs='+') though this often ends up with parsing ambiguities (especially when the arguments are very likely to be --dashed themselves). Probably gets complicated quickly -- might not be worth implementing for the complexity.

@asottile, I know there hasn't been any activity in this thread for a long time, but this would be an incredibly useful feature (and this issue has a lot of duplicates). While your suggestion is great for manual testing, it doesn't allow for automated testing (automated tools are great) unless you create a pipeline that mimics try-repo (see https://github.com/George-Ogden/pre-commit-hooks/blob/master/tests/mypy/test_mypy_plugin.sh for example)!

I think that parsing a string then using `shlex.split` would be best so that you can escape characters (what if the arg contains a comma)? This has a simple implementation in #3550.

**Comment by asottile** [comment]
why do you need to involve pre-commit at all -- just call your tool directly.  pre-commit works already you don't need to test pre-commit.

please don't revive years old threads.  the message above already is pretty clear that *this will not be implemented*
