### ISSUE TITLE
importlib-resources is not installed for python<3.7

### ISSUE THREAD

**Issue by naeioi** [pre-commit/pre-commit#853]
This line does not install `importlib-resources` for python<3.7.
https://github.com/pre-commit/pre-commit/blob/eecf3472ffa1ce8e8f4638956d319820d80bdf54/setup.py#L50

And this leads to exception `ModuleNotFoundError: No module named 'importlib_resources'` later when pre-commit runs.

**Comment by asottile** [comment]
```
$ virtualenv venv >& /dev/null && venv/bin/pip install pre-commit >& /dev/null && venv/bin/pip freeze | grep importlib
importlib-metadata==0.6
importlib-resources==1.0.1
```

seems to for me -- how are you installing pre-commit?

**Comment by asottile** [comment]
I made sure to test `pip` all the way back to version 1.5.6 and they all succeed in installing `pre-commit` w/ `importlib-resources`.

**Comment by asottile** [comment]
hmm maybe conda?  @nicoddemus I believe handles that <3

**Comment by asottile** [comment]
yeah this seems to be missing `importlib-resources` for python < 3.7, not sure how conda specifies that but that's probably the issue? https://github.com/conda-forge/pre_commit-feedstock/blob/75fa41f37eb75a7738cdbf01134529ede65636aa/recipe/meta.yaml

**Comment by naeioi** [comment]
Yes I am using conda.

**Comment by asottile** [comment]
@naeioi cool, I've created an issue on the feedstock recipe for `pre-commit`, please follow along there (I don't maintain that!): https://github.com/conda-forge/pre_commit-feedstock/issues/16

Thanks again for the issue :tada:

**Comment by naeioi** [comment]
@asottile Oh great. Thanks for your prompt reply!

**Comment by willstott101** [comment]
Hm, this seems to be happening to me with pipenv...

`ubuntu 18.04`
`python 3.6.9`
`pip 20.0.2`
`pipenv 2018.11.26`

might investigate further later but thought I'd at least post it down somewhere.

Hitting this trying to setup a dev environment for Black, but there are some other py 3.6 support problems too, so this isn't a lone blocker.

**Comment by asottile** [comment]
sounds like a bug in pipenv then, it works fine without it using the same version of pip you've listed above:

```console
$ python --version
Python 3.6.9
$ pip --version
pip 20.0.2 from /tmp/venv/lib/python3.6/site-packages/pip (python 3.6)
$ pip install pre-commit
Collecting pre-commit
  Using cached pre_commit-2.0.1-py2.py3-none-any.whl (170 kB)
Collecting identify>=1.0.0
  Using cached identify-1.4.11-py2.py3-none-any.whl (97 kB)
Collecting cfgv>=2.0.0
  Using cached cfgv-2.0.1-py2.py3-none-any.whl (7.4 kB)
Collecting virtualenv>=15.2
  Using cached virtualenv-16.7.9-py2.py3-none-any.whl (3.4 MB)
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-1.5.0-py2.py3-none-any.whl (30 kB)
Collecting nodeenv>=0.11.1
  Using cached nodeenv-1.3.5-py2.py3-none-any.whl (21 kB)
Collecting importlib-resources; python_version < "3.7"
  Using cached importlib_resources-1.0.2-py2.py3-none-any.whl (32 kB)
Collecting toml
  Using cached toml-0.10.0-py2.py3-none-any.whl (25 kB)
Processing /home/asottile/.cache/pip/wheels/e4/76/4d/a95b8dd7b452b69e8ed4f68b69e1b55e12c9c9624dd962b191/PyYAML-5.3-cp36-cp36m-linux_x86_64.whl
Collecting aspy.yaml
  Using cached aspy.yaml-1.3.0-py2.py3-none-any.whl (3.5 kB)
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.5
  Using cached zipp-2.1.0-py3-none-any.whl (4.6 kB)
Installing collected packages: identify, six, cfgv, virtualenv, zipp, importlib-metadata, nodeenv, importlib-resources, toml, pyyaml, aspy.yaml, pre-commit
Successfully installed aspy.yaml-1.3.0 cfgv-2.0.1 identify-1.4.11 importlib-metadata-1.5.0 importlib-resources-1.0.2 nodeenv-1.3.5 pre-commit-2.0.1 pyyaml-5.3 six-1.14.0 toml-0.10.0 virtualenv-16.7.9 zipp-2.1.0
```

**Comment by willstott101** [comment]
Yeah... come to think of it, I don't know how `Pipfile.lock` can be portable in the face of conditional requirements. Perhaps the lockfile is the problem

**Comment by bryant-finney** [comment]
FWIW, I'm also seeing this issue:

```sh
$ python3 --version
Python 3.6.9

$ pip --version
pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

$ pipenv --version
pipenv, version 2018.11.26
```

Explicitly requiring `importlib-resources` in `Pipfile` resolved the issue for me:

```toml
importlib-resources = {version = "*", markers = "python_version < '3.7'"}
```

```sh
$ pipenv install && pipenv shell pre-commit --version
[ ... ]
pre-commit 2.1.0
```

**Comment by asottile** [comment]
what does `$(head -1 $(which pipenv) | cut -d'!' -f2) --version` say? I suspect you're compiling with one version of python and then running with another

either way, it's because pipenv is broken not because of how we specify packages

**Comment by bryant-finney** [comment]
Yup, you're spot on there. `pipenv` in one of my GitLab runners specified `3.8` as the interpreter; because of this, `Pipfile.lock` omitted `importlib-resources` when it was picked up in a later build step by a different runner.

**Comment by revmischa** [comment]
```
❯ poetry run pre-commit install

Traceback (most recent call last):
  File "/Users/cyber/Library/Caches/pypoetry/virtualenvs/testo-PR1kzPxy-py3.8/bin/pre-commit", line 6, in <module>
    from pre_commit.main import main
  File "/Users/cyber/Library/Caches/pypoetry/virtualenvs/testo-PR1kzPxy-py3.8/lib/python3.8/site-packages/pre_commit/main.py", line 8, in <module>
    import pre_commit.constants as C
  File "/Users/cyber/Library/Caches/pypoetry/virtualenvs/testo-PR1kzPxy-py3.8/lib/python3.8/site-packages/pre_commit/constants.py", line 4, in <module>
    import importlib_metadata  # TODO: importlib.metadata py38?
  File "/Users/cyber/Library/Caches/pypoetry/virtualenvs/testo-PR1kzPxy-py3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ModuleNotFoundError: No module named 'zipp'
```

**Comment by asottile** [comment]
@revmischa that's an old version of pre-commit fwiw
