### ISSUE TITLE
Fullpath filename passed to hooks?

### ISSUE THREAD

**Issue by dkolepp** [pre-commit/pre-commit#858]
When you inside a git repo subdirectory, `git status` reports changed files with relative filenames:

For example, In the git repo root:
```
[dan@my-laptop my-project]$ git status
# On branch pc-dev
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   misc/pc-hello-world.sh
#	modified:   misc/pc-sed-patterns.sh
#
```
but in the misc directory:
```
[dank@rhel-laptop misc]$ git status
# On branch pc-dev
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   pc-hello-world.sh
#	modified:   pc-sed-patterns.sh
# 
```
It appears that these filenames get passed to the pre-commit hooks. This has the effect of defeating the `files` parameter of a `.pre-commit-config.yaml` file.  

**QUESTION:** Is there a way (option/flag) to have pre-commit expand filenames to full paths before passing as arguments to hook scripts?  IF not, can this be added?  It means that if working it a repo that I have to return to the repo root to do my commits.

**Comment by asottile** [comment]
If you're having trouble convincing yourself, it's quite easy to demonstrate:

```console
$ tree .
.
├── bar
└── t
    └── foo

1 directory, 2 files
$ cat .pre-commit-config.yaml
-   repo: local
    hooks:
    -   id: echo
        name: echo
        entry: echo
        language: system
$ pre-commit run --verbose
[echo] echo..............................................................Passed
hookid: echo

bar t/foo

$ cd t
$ pre-commit run --verbose
[echo] echo..............................................................Passed
hookid: echo

bar t/foo

```

**Comment by dkolepp** [comment]
Thank you for responding to this.  I was able to verify myself as well.  Now having trouble reproducing my original error.  Will let you know if I do.

Thanks again for your quick reply!

**Comment by asottile** [comment]
cheers 🎉  thanks for the issue!
