### ISSUE TITLE
Different Python Versions

### ISSUE THREAD

**Issue by s0undt3ch** [pre-commit/pre-commit#869]
I have a project which needs both python2 and python3.

I use pyenv + virtualenv.

If I install pre commit under py3 it cannot create a py2 virtualenv, and the other way around too.

What's would be the solution here?

**Comment by asottile** [comment]
I believe you're looking for [`language_version`](https://pre-commit.com/#overriding-language-version)?

**Comment by s0undt3ch** [comment]
I'm setting those.
The issue was that pyenv was being kind of picky but I solved it.
Thanks!
