### ISSUE TITLE
Incorrect shebang in .git/hooks/pre-commit for python3 only installations

### ISSUE THREAD

**Issue by fristedt** [pre-commit/pre-commit#878]
The shebang for `.git/hooks/pre-commit` is `#!/usr/bin/env python`. I work with setups where `python3` is the only python in env.

Could the shebang be the install python instead? I.e. the installation under `INSTALL_PYTHON = '/usr/bin/python3'`

**Comment by asottile** [comment]
hmm! that's a good point I hadn't thought of but presents some issues I can think of:

- windows (official python installs) always use `python` and not `python3`
- `INSTALL_PYTHON` might be ephemeral, it's why there's three options for [detecting `pre-commit` in the script](https://github.com/pre-commit/pre-commit/blob/51659ee606c5207b30ce863086b2a05f572ad245/pre_commit/resources/hook-tmpl#L93-L104)

that said, I think we can get this right, probably by inspecting `sys.executable` and determining what possible values could be used.

**Comment by fristedt** [comment]
> Maybe something like this?
> 
> ```python
> if sys.platform != 'win32' and six.PY3:
>     return '#!/usr/bin/env python3'
> else:
>     return '#!/usr/bin/env python'
> ```

Thanks for the quick reply! I believe that would solve my problem.

**Comment by asottile** [comment]
hmmm I just thought of another case while working on this that might not work.  Some distributions (for instance `arch`) install python 3.x as `/usr/bin/python` and won't (?) necessarily have a `/usr/bin/python3` executable

I'll have to think about this some more -- maybe inspecting `sys.executable` is necessary.  Maybe something like [this](https://github.com/pre-commit/pre-commit/blob/51659ee606c5207b30ce863086b2a05f572ad245/pre_commit/languages/python_venv.py#L21)

**Comment by asottile** [comment]
@fristedt can you try out the branch in #893?

**Comment by fristedt** [comment]
> @fristedt can you try out the branch in #893?

Tested, it works. Thanks @asottile!

**Comment by asottile** [comment]
This has been released as part of [v1.14.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.14.0) 🎉  -- thanks again!
