### ISSUE TITLE
Alternate Referenceable Hook ID

### ISSUE THREAD

**Issue by s0undt3ch** [pre-commit/pre-commit#882]
Would you accept a change that accepts something like `alt` or `altid` in the pre-commit configuration file? `ref`?

The use case is the following.
We run our code through PyLint and while on the project code we're strict, on the tests we're a bit more relaxed.

So, we define 2 repos entries for PyLint. One for the project code, the other for the projects tests.

We already override `name` to make it clear which set of files are being linted, however, there's no way to choose which of the PyLint entries we want to explicitly run on the CLI, `pre-commit run pylint` is all we can do and runs both pylint hook entries.

Here's were the alternative ID comes in. It would allow "overriding" the ID so that we could better target what we want to run.

Should it also be used on the output if defined?

**Comment by asottile** [comment]
This seems kinda reasonable (and has been [asked about before at least once](https://github.com/pre-commit/pre-commit/issues/866#issuecomment-440416952)).

There's a way you can make this work today without needing a new option however, you can define one in one `.pre-commit-config.yaml` and one in another and select the file using `pre-commit run --config ...`.  If this is good enough to fit your usecase I'd rather that than add a new not-often-used feature -- but if it's not good enough let's look into ways to make this happen :)

**Comment by asottile** [comment]
via #886 -- looks like the issue linking didn't work :P

**Comment by asottile** [comment]
This has been released as part of [v1.14.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.14.0) 🎉  -- thanks again!
