### ISSUE TITLE
prepend certain characters to a commit-msg using precommit

### ISSUE THREAD

**Issue by milind-shakya-sp** [pre-commit/pre-commit#884]
Not sure if the new `commit-msg` stage helps, may be we need a new `prepare-commit-msg` stage that can hook into ways people can add to commit messages?

**Comment by asottile** [comment]
`commit-msg` should allow editing of the message, can you share what you've tried so far that hasn't worked?

**Comment by asottile** [comment]
please comment back with more information and I'll reopen.  as I understand, `commit-msg` is sufficient to modify the message that will be committed

**Comment by milin** [comment]
@asottile yes turns out`commit-msg` was sufficient. I've opened a pr on the pre-commit-hooks repo https://github.com/pre-commit/pre-commit-hooks/pull/347 if other people want to use as well.

Thanks for the info!

**Comment by marcjay** [comment]
I do think there would be value in a `prepare-commit-msg` stage to match what's available with git: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

I would like to pre-populate the commit message with some dynamic information such as the Ticket ID and description (so a git template is not suitable). I'd rather not mess with a developer's commit message after they've written it (i.e. use the `commit-msg` stage) but instead just add a useful starting line.

If it's something that is likely to be accepted and is reasonably straightforward I may be able to offer a PR to add this

**Comment by asottile** [comment]
shouldn't be too bad @marcjay -- can basically follow the PR that added `commit-msg` (though some of the internals have moved a bit since then)

https://github.com/pre-commit/pre-commit/pull/566/files

**Comment by milind-shakya-sp** [comment]
@marcjay I went ahead with creating a precommit hook instead. You can checkout https://github.com/milin/giticket to see if its useful.

**Comment by marcjay** [comment]
Thanks for the quick replies both!

Thank you @milind-shakya-sp I did take a look at giticket and tried it out. Nice work! For our use-case I don't really want to quietly change a dev's commit message after they've written it, just provide a relevant template to use. I might use something similar to abort the commit if it's missing the ticket ID as a quick intermediate solution

Cheers @asottile that's really helpful and looks achievable, I plan to have a go over an evening or two.

**Comment by asottile** [comment]
The biggest internal change since that PR is the combination of the hook template and removal of `bash`,  hopefully (?) it's simpler now: https://github.com/pre-commit/pre-commit/blob/b33f2c40d8de0cd2c55a9b637773172198962832/pre_commit/resources/hook-tmpl#L162-L169
