### ISSUE TITLE
gem install failing after release of gem 3.0.0

### ISSUE THREAD

**Issue by sphuber** [pre-commit/pre-commit#890]
Our pre-commit started failing on 19 Dec 2018 because the `--no-ri` option that is being used has been deprecated. I noticed that this already changed in the code base in a [commit](https://github.com/pre-commit/pre-commit/commit/435d9945a34ceedc97d5219b2bbb7cc88c9ac8e8) but wanted to open an issue for reference.

**Comment by asottile** [comment]
This was already fix in #889
