### ISSUE TITLE
Switch from pyyaml -> ruamel.yaml

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#897]
Seems better maintained, I've asked about the "new api" and it seems like there'll be some stability there: https://bitbucket.org/ruamel/yaml/issues/267/id-like-to-use-the-new-api

Should be pretty easy to swap

**Comment by asottile** [comment]
this is maybe more difficult than I thought: https://bitbucket.org/ruamel/yaml/issues/269/ruamelyamlcommentscommentedmap-copy

**Comment by asottile** [comment]
here's a WIP branch: https://github.com/pre-commit/pre-commit/compare/ruamel_yaml?expand=1

**Comment by ssbarnea** [comment]
pyyaml 5.1 was releases yesterday.... ;)

**Comment by asottile** [comment]
this still isn't an error however :(

```pycon
>>> yaml.safe_load('{foo: bar, foo: baz}')
{'foo': 'baz'}
```

**Comment by asottile** [comment]
they also didn't fix "slow by default" :man_facepalming:

**Comment by asottile** [comment]
veto on fallback, if something is not honoring the dependencies in setup.py they're wrong and the complexity to support them is not worth it

**Comment by ssbarnea** [comment]
@asottile I see it as a problem because at this moment ansible is using pyyaml and is very unlikely to change over night. If pre-commit switches to runamel it forces us to rely on both dependencies instead of one. This is why I mentioned the fallback, because it allows you to have an escape net if something goes wrong.

I think that is why python extras were invented for, to allow alternative backends/providers/...

**Comment by asottile** [comment]
The whole reason to move to rumael.yaml would be to *reduce* the support burden -- dragging pyyaml onwards is not on the table.  The code to support pyyaml vs the code to support ruamel.yaml also has very little overlap (it's a rewrite of that machinery) so keeping around the old cruft would be a significantly worse scenario than just staying with pyyaml

> If pre-commit switches to runamel it forces us to rely on both dependencies instead of one.

The two libraries don't conflict, they can both be installed side-by-side.  Who cares if both are installed?  ansible doesn't use `toml` and I don't see a complaint about that dependency :P

> I think that is why python extras were invented for, to allow alternative backends/providers/...

extras *still* aren't properly supported by pip, and they *don't* solve this situation (exclusive or) they only enable add-ons

**Comment by asottile** [comment]
I think this is not going to happen, rumal.yaml doesn't have the facilities I need and is kinda clunky to work with 

that said, I think now that pre-commit is py36+ I can factor out aspy.yaml and use `sort_keys=False` (new in pyyaml 5.1 I believe?)

**Comment by asottile** [comment]
given #1306 I probably won't pursue this

**Comment by ssbarnea** [comment]
The original issue related to lack of maintenance is no longer valid, both appear to be maintained now.

I am curious what is needed form pyyaml that ruamel does not provide? I only want to know as I have other projects using one or another. I know for sure that for linting ruamel is needed as it allows to parse comments and expand anchors, but that is not something you need for loading a config file.

In the end, not doing any change can prove the best move :)

**Comment by asottile** [comment]
dump to string is not supported by ruamel.yaml

**Comment by ssbarnea** [comment]
That ticket also made me discover another dark side of ruamel, https://twitter.com/zhenech/status/1222109994855862272 -- I kinda find ironic the 180 degree turn it went in one year. I personally find very hard to trust anyone still hooked into SF world. I guess that Hg addiction made them pick that direction.

**Comment by asottile** [comment]
hah yeah I saw that too and had a similar reaction
