### ISSUE TITLE
`default_stages` merged w/ `stages` of particular hook ID

### ISSUE THREAD

**Issue by zaufi** [pre-commit/pre-commit#920]
The [docs](https://pre-commit.com/#pre-commit-configyaml---top-level) tell it'll be used only if hook `id` doesn't have it's own `stages` key, but I've got the following error when trying to commit:

    Check for useless excludes...............................................Passed
    Check hooks apply to the repository......................................Passed
    Check for case conflicts.................................................Passed
    Check Yaml...............................................................Passed
    Fix End of Files.........................................................Passed
    Trim Trailing Whitespace.................................................Passed
    hint: Waiting for your editor to close the file...
    Check for useless excludes...........................(no files to check)Skipped
    Check hooks apply to the repository..................(no files to check)Skipped
    Check for case conflicts.................................................Passed
    Check Yaml...........................................(no files to check)Skipped
    Trim Trailing Whitespace.................................................Failed
    hookid: trailing-whitespace

    Fixing .git/COMMIT_EDITMSG

    Commit message check.....................................................Passed

As seen, it tries to check my `.git/COMMIT_EDITMSG` file, which is intended to be checked only by _Commit message check_ plugin.

I've got the following config file:

    default_stages: [commit]
    exclude: '^(build|patches)/.*$'
    fail_fast: false
    repos:
      - repo: meta
        hooks:
          - id: check-useless-excludes
          - id: check-hooks-apply

      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.1.0
        hooks:
          - id: check-case-conflict
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

      - repo: https://github.com/jorisroovers/gitlint
        rev: v0.10.0
        hooks:
          - id: gitlint
            name: Commit message check
            language: python
            entry: gitlint --msg-filename
            stages: [commit-msg]

**Comment by asottile** [comment]
What does `pre-commit --version` say?

**Comment by zaufi** [comment]
Oops, it was the old one (1.13.0)... Upgrade to the latest one works as expected! %)
Case closed %)

**Comment by asottile** [comment]
:tada: thanks for the issue nonetheless!
