### ISSUE TITLE
weird failure to find ansible-lint executable

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#934]
Today I faced an extreamly weird behavior from pre-commit where the ansible-lint hook failed to find ansible-lint executable.

From the [console log](http://logs.openstack.org/13/634113/2/check/openstack-tox-linters/cd6d7c2/job-output.txt.gz#_2019-02-01_12_17_31_402514) it was obvious that it was able to install ansible-lint but still it failed to run.

I was not able to replicate this problem outside CI, the code run locally with `tox -e linters` does work.

The only thing that is different here is that thing change request is made againt a maintenance branch instead of the common master, but this still should not be a problem.

```
Executable `ansible-lint` not found
```

@asottile Any idea? Change that failed is at https://review.openstack.org/#/c/634113/

**Comment by asottile** [comment]
that is quite weird!  is there a git branch I can check out and play with?

**Comment by ssbarnea** [comment]
@asottile Yep, weird. you can always clone that change locally but I doubt you will be able reproduce it. I was not able to.

Still, there is something interesting, I tried to change the `entry: ansible-lint ...` to `entry: pythin 0m ansiblelint ...` and the last build passed.

The only case where I can see this happening is if for some reason pre-commit failed to change the PATH correctly (or if pip failed to create the executable when installing ansible-lint package.).

Now I don't know what caused it but lets keep it open for few days and see if someone else encounters something similar. Feel free to add a label more-info needed or similar as we cannot really do anything about it if we cannot reproduce it.

**Comment by asottile** [comment]
nothing came up, closing -- still interested in digging into this if you can get it isolated or have a machine I can borrow which reproduces that would be great
