### ISSUE TITLE
hardening pre-commit security by avoiding git installation

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#942]
This is a security issue which would require some changes in pre-commit in order to address. Mainly use of git repositories for installing dependencies is not pure because their owners can force-push altered code, code that would endup being run by all users.

Once way to avoid this is to have an installation mode from trusted repositories like pypi or npm ones which do not ever allow someone to override and already published version. People can disable published versions but they cannot replace them with "other" code.

I raised this bug because several people pinged me in the last months about the risks of of using git repos for these hooks. 

Also another issue is that private git repositories are more likely to go offlin, be disabled by their owners or highjacked. Use of package repositories is considered more safe and reliable because they have a team maintaining them able to support in case action is needed. For example in the past I managed to gain ownership of few unmaintained package names and be able to continue maintaining those packages. Shortly, for these reason, I trust a bit more a package-repository than a git url. 

I know that including a checksum in addition to the nice revision number would improve security and I have nothing againt that feature, still this approach does not address the other aspects of the pre-commit maintenance: like disapearing repos.

There are also additional benefits on using pip/npm repos: they can easily be cached and used even in isolated / secured build environments, somethign is almost impossible with git repos pointing to more or less random internet servers.

To be clear: I am not asking to drop current behaviour which could be found more than good enough for most people, but I am asking for considering alternative setup.

**Comment by asottile** [comment]
pre-commit will always always use git as the lowest common denominator and git itself is not a security issue

Please do not try and push your opinions with fear

**Comment by asottile** [comment]
To more accurately address your two concerns:

- republishing
- things disappearing

npm / pypi / most package managers do not address the second so I won't address it for git either.  Same goes for private npm / pypi registries.  This is not a solvable problem and your suggestion of npm / pypi does not solve this.

republishing is also possible on pypi, I've done it before (either through naming trickery or through `.post1` packages) -- I can't say the same for npm as I do not have enough experience with npm

that said, if you somehow think that npm / pypi are more secure you can _already use them today_.  And if you're concerned about the security of git tags, use sha1 hashes.  There are plans to make a ~locklike file in the future which should alleviate all concerns here -- the difficulty is picking a format that works and isn't a merge conflict nightmare

caching works fine with pre-commit, we use it at lyft to run network isolated builds of pre-commit hooks.

1. build time: `pre-commit install-hooks`
2. run time: `pre-commit run`

**Comment by ssbarnea** [comment]
While trying to convince more projects from openstack to adopt pre-commit I faces again some opposition form the infra team which raised valid CI related scalability concerns in addition to security.

For individual developers, doing few additional clones as part of `tox -e lint` is not a real issues, nobody complained so far.

Still, on CI cloning 4-5 additional git repositories for each linting jobs is a serious extra load, especially if these repositories are hosted on github/gitlab -- which do have throttleing based on IP address. You can really end-up having you IPs banned temporary from using their services if you have a big numeber of jobs running.

I know well about caching `~/.cache/pre-commit` folder betwene builds, which is something I use on Travis a lot. Still some CI systems do not support this kind of optimizaiton, for security reasons of practical ones. Think for example about Zuul CI, which is used by OpenStack. We have multiple Zuul instances and each of them is using multiple clouds. Jobs run on various locations which mainly makes the cache-sharing close to impossible.

On the other hand, we already have local pip caches enabled, meaning that pip installs are *very* fast.

They already observed that flake8 can be used as an internal hook from pre-commit-hooks but when doing so you loose the benefit of being able to bump it using `pre-commit auto-update.`.

Do you have any ideas on how we can address these concerns?

**Comment by asottile** [comment]
> Still, on CI cloning 4-5 additional git repositories for each linting jobs is a serious extra load

For repeated clones, one thing that we did at lyft was to prebuild a bunch of pre-commit repos into a docker image and then reuse that in places.  That way they only really get cloned once unless the versions change and then they get re-cloned.

> They already observed that flake8 can be used as an internal hook from pre-commit-hooks but when doing so you loose the benefit of being able to bump it using `pre-commit auto-update`..

I added the pre-commit metadata to `flake8` directly, so you can use that with https://gitlab.com/pycqa/flake8

See also: https://github.com/pre-commit/pre-commit-hooks/issues/344
