### ISSUE TITLE
Easier way to support multiple files or excludes

### ISSUE THREAD

**Issue by firba1** [pre-commit/pre-commit#946]
Several of our hooks have configurations which look like:
```
- id: foo
   exclude: '^(foo/bar|baz/quux)$'
```

It would be nice if we could just specify multiple patterns instead of creating monster regexen, e.g.:
```
- id: foo
   exclude:
       - 'foo/bar'
       - 'baz/quux'
```

**Comment by asottile** [comment]
;) have you read [the docs](https://pre-commit.com/#regular-expressions)

**Comment by firba1** [comment]
Nope, I wasn't aware of that! However, I would argue that that is still a monster regex and this would be easier to understand/maintain.

**Comment by asottile** [comment]
Instead of creating two ways to do things (and an awkward, complex, and strange union-typed schema) we're going to leave this as is.

Thanks for the issue :tada:

**Comment by asottile** [comment]
#591 and #149 are duplicates
