### ISSUE TITLE
Support GIT_SSH_COMMAND

### ISSUE THREAD

**Issue by firba1** [pre-commit/pre-commit#947]
Currently, `GIT_SSH` is supported for overriding the git command, but it is is sightly less ergonomic than `GIT_SSH_COMMAND` since it requires file. Adding support for passing `GIT_SSH_COMMAND` to git commands would obviate the need for creating a new file when you want to change the ssh command.

**Comment by asottile** [comment]
going to be honest, I have no idea what you're talking about -- could you elaborate?

**Comment by firba1** [comment]
Docs for both of these https://git-scm.com/docs/git#git-codeGITSSHcode
Code where pre-commit only allows GIT_SSH: https://github.com/pre-commit/pre-commit/blob/46ae88c1f06b8dc59f3e049c68b2dcea22bb9a54/pre_commit/git.py#L32

**Comment by firba1** [comment]
As for use case, I'm using this to point at a weirdly-placed ssh key.

**Comment by asottile** [comment]
ah ok now I understand.  seems fine, go for it

that said, you can also configure this through `IdentityFile` in `~/.ssh/config` -- but `GIT_SSH_COMMAND` seems harmless to whitelist here

**Comment by firba1** [comment]
There's a lot of complex other reasons I can't really use `~/.ssh/config`. I'll cut a quick branch for this.

**Comment by asottile** [comment]
`dockerbuild`, eh?

**Comment by firba1** [comment]
yep lol
