### ISSUE TITLE
Failed to create venv on missing path

### ISSUE THREAD

**Issue by liiight** [pre-commit/pre-commit#951]
When I try to commit after the initial install of pre-commit, I get this error:
```
13:16	Commit failed with error
			0 files committed, 4 files failed to commit: Added pre-commit hooks
			[INFO] Installing environment for https://github.com/ambv/black.
			[INFO] Once installed this environment will be reused.
			[INFO] This may take a few minutes...
			An unexpected error has occurred: CalledProcessError: Command: ('/Users/orcarmi/PycharmProjects/shield/venv/bin/python3.6', '-mvirtualenv', '/Users/orcarmi/.cache/pre-commit/repod8ugezw0/py_env-python3.6', '-p', 'python3.6')
			Return code: 3
			Expected return code: 0
			Output:
			The path python3.6 (from --python=python3.6) does not exist
			
			Errors: (none)
```
But when I run the same command locally it works just fine:
```console
Ors-MacBook-Pro:shield orcarmi$ python -mvirtualenv /Users/orcarmi/.cache/pre-commit/repod8ugezw0/py_env-python3.6 -p python3.6
Running virtualenv with interpreter /Users/orcarmi/PycharmProjects/shield/venv/bin/python3.6
Using real prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/orcarmi/.cache/pre-commit/repod8ugezw0/py_env-python3.6/bin/python3.6
Also creating executable in /Users/orcarmi/.cache/pre-commit/repod8ugezw0/py_env-python3.6/bin/python
Installing setuptools, pip, wheel...
done.
```
This is my config:
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: check-yaml
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
```

pre-commit 1.14.4

Thanks in advance

**Comment by asottile** [comment]
I've moved the issue as it isn't about `pre-commit-hooks` (just some linting / fixing scripts) and instead is about the framework (`pre-commit`).

I don't have enough information so let's try and get some more :)

Can you provide the following:

```
which python3.6
type python3.6
```

And can you try the command while the current working directory is `/`?  That would be equivalent to how `pre-commit` runs things (to avoid a few common side-effects of the local repository due to `setup.cfg` and such)

**Comment by liiight** [comment]
I originally tried installing pre-commit from within my activated project venv. When I did the same from outside the venv I got it working with no issues.

If this is how it's supposed to work, I apologize.

**Comment by asottile** [comment]
I think either should work -- if you can provide specific reproduction steps that would be super helpful.  Note that you can probably reset pre-commit's state with `pre-commit clean` if that helps your reproduction.

The code I'm thinking of that should make this "just work" is [here](https://github.com/pre-commit/pre-commit/blob/aa4bc9d241d805d67efa29f040b29fe3baba5523/pre_commit/languages/python.py#L108-L110)... though... now that I look at it that seems to only apply on windows for some reason -- maybe it should apply more generically?

**Comment by liiight** [comment]
I'll try to reproduce it, but honestly now that I got it working I'm kinda hesitant to try and reset it just for reproduction purposes. I'll close this for now and reopen if needed.

Thanks for the reply and this amazing tool!

**Comment by asottile** [comment]
Cool, I'll poke around as well
