### ISSUE TITLE
warn on unknown keys at the top level

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#965]
We're now warning on unknown keys at the hook level, this should also happen at the top level

**Comment by yoavcaspi** [comment]
I wish to work on this issue.
I'm pre-commit newbie. 
can you refer me to the warning on unknown keys at the hook level?

**Comment by asottile** [comment]
sure!  @mitzkia started some work on this in #980 and added a [`WarnAdditionalKeys`](https://github.com/asottile/cfgv/pull/17) helper to cfgv to make this easier to do -- but looks like they've been busy with other things :)

the extraneous keys for the hook level is done later in the process [here](https://github.com/pre-commit/pre-commit/blob/8df6b22f4fc93b30be322e62f8bf1e0886729648/pre_commit/repository.py#L105-L110) -- though for the top level and repository level this should probably get done in pre_commit/clientlib.py (on the two mapping types directly) via the new `WarnAdditionalKeys`
