### ISSUE TITLE
Proper way to pass list/array arguments

### ISSUE THREAD

**Issue by homebysix** [pre-commit/pre-commit#971]
Very happy I discovered pre-commit; thank you for a great tool!

I'm trying to pass a list of acceptable values as arguments, which a hook will use to test each file against. The hook is set up to accept the argument as a one-or-more array (`nargs="+"`), but I can't seem to invoke the proper yaml config to pass that array in. Here are the arrangements I've tried unsuccessfully:

- `args: [--values=foo,bar]`
- `args: ['--values=foo,bar']`
- `args: [--values='foo,bar']`
- `args: ['--values', 'foo', 'bar']`

I suspect I've got my quoting wrong. I can envision a fix that involves passing in a string and then splitting it (which looks like what `pretty-format-json` does with the `--top-keys` arg), but that's not as nice as a pure list.

Thanks in advance for any advice!

**Comment by asottile** [comment]
I ~think the last one looks the most correct, you might need to do something like

```yaml
args: ['--values', foo, bar, '--']
```

to tell the argument parsing system there's new stuff to see?

The [docs](https://pre-commit.com/#passing-arguments-to-hooks) show a few examples of how the arguments get splatted but if you need some hands-on debugging you can use the `identity` hook to play with it:

```yaml
-   repo: meta
    hooks:
    -   id: identity
         # can play with args / files / etc. here
```

`identity` will spit out one argument at a time on the commandline

**Comment by asottile** [comment]
If you're designing the hook, another approach you can use is `action='append'` and then one can specify:

```yaml
args: ['--key', 'a', '--key', 'b', '--key', 'c']
```
or some such

I suspect the problem you're hitting is `nargs='+'` and then pre-commit transforming

```yaml
args: ['--foo', 'bar', 'baz']
```
+ filenames a b c

into
```
exe --foo bar baz a b c
```

which can't be distinguished properly

In that case, it looks like (At least with `argparse`) the `--` separator works well:

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--foo', nargs='+')
parser.add_argument('filename', nargs='*')
args = parser.parse_args()
print(args)
```

```console
$ python t2.py --foo a b
Namespace(filename=[], foo=['a', 'b'])
$ python t2.py --foo a -- b
Namespace(filename=['b'], foo=['a'])
```

Hope this helps!

**Comment by homebysix** [comment]
Thank you! I wasn't aware of the trailing `--` trick, but that seems to do exactly what I need. It also appears I can use multi-line arrays to make the config file a bit more readable. The following config is working for me now:

```
-   repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.0.5
    hooks:
    -   id: check-munki-pkgsinfo
        args: [
            '--required-keys', 'description', 'name', 'developer', 'category', 'version',
            '--catalogs', 'testing', 'stable',
            '--categories', 'Communication', 'Design', 'Engineering', 'macOS', 'Printers',
                'Productivity', 'Security',  'Utilities', 'Web Browsers',
            '--']
```

Thank you!

**Comment by asottile** [comment]
Nice!  Glad to help :tada:
