### ISSUE TITLE
Run some hooks only on commit but not on run.

### ISSUE THREAD

**Issue by skorokithakis** [pre-commit/pre-commit#975]
My flow includes running `pre-commit` on commit *and* on CI, to make sure that nobody forgot to run it locally. However, there are some hooks that should run *only* locally, like generating the changelog. Is there any way to tell pre-commit to run a hook only on an actual commit, and not when invoked with `pre-commit run`?

**Comment by asottile** [comment]
I think you're looking for [`stages: [manual] `](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) perhaps?

**Comment by skorokithakis** [comment]
That only runs on `pre-commit run --stage manual`, no? I'm looking for the inverse, pretty much.

**Comment by asottile** [comment]
You'd set `stages: [commit] ` and then that wouldn't be run w/ `--hook-stage: manual` (setting no option defaults to all stages)

**Comment by skorokithakis** [comment]
Ahh, I see what you mean. Yes, that's fantastic. Could the docs perhaps be amended to include this? It'd be nice to have it on the site, it would have saved me a trip here, for one.

**Comment by asottile** [comment]
Sure, feel free to submit a PR :D - - the docs live at https://github.com/pre-commit/pre-commit.github.io
