### ISSUE TITLE
How to install subset of repos

### ISSUE THREAD

**Issue by mattcanty** [pre-commit/pre-commit#976]
I'm looking for ways speeding up CI and trying to parallelise. When I split them out each one initialises all repos.

Is there either:

1. Some information as to what location I could cache, it just `pip`? I checked through the documentation at https://pre-commit.com/#usage.
2. Is there a way of specifying which repos to I want installing? Again checked https://pre-commit.com/#usage.
3. A reason this it isn't already running in parallel, I using `1.14.3` which should include the good work of `1.13.0` - https://github.com/pre-commit/pre-commit/releases/tag/v1.13.0

**Comment by asottile** [comment]
1. `$HOME/.cache/pre-commit` / `%USERPROFILE%/.cache/pre-commit` is cacheable: https://github.com/pre-commit/pre-commit/blob/264161c1824a4938366c588aa44688cd80f0e383/.travis.yml#L32
2. All repos will at the least be *initialized* (this is necessary to load the configuration to determine if they are going to be run or not), though only the hooks being run will be *installed*
3. Install-in-parallel is a slippery slope -- I then have to be responsible for all the install tools being parallel safe.  In the past `pip` has not been at the very least and it wouldn't surprise me if others suffer from the same problems.  The work in 1.13 was parallelism at *runtime*

**Comment by mattcanty** [comment]
1. Thanks, this has reduced some of the faster checks to merely a few seconds!
2. Understood, I think with point 1 this is no longer an issue.
3. Here I should have specified I was referring to the hooks rather than initialisation. They don't appear to be running in parallel...

**Comment by asottile** [comment]
3.  They are internally parallel, crossing the streams isn't at all feasible when rewriters are in play

**Comment by mattcanty** [comment]
Got it. I think that clarifies everything. 

Just based on this thread I've roughly halved the CI time! However I've noticed that it is behaving differently:

`./ci/pre-commit.sh run --all-files`
```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks-safety.
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks:shellcheck.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-pylint.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.
[INFO] Initializing environment for https://github.com/awslabs/cfn-python-lint.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks-safety.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adrienverge/yamllint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/awslabs/cfn-python-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Fix requirements.txt.....................................................Passed
safety...................................................................Passed
Test shell scripts with shellcheck.......................................Passed
pylint...................................................................Passed
yamllint.................................................................Passed
AWSLabs CloudFormation Linter............................................Passed
JSON Linter..............................................................Passed
```

`./ci/pre-commit.sh run python-safety-dependencies-check`
```
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks-safety.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
safety...............................................(no files to check)Skipped
```

Notice how in the `--all-files` the result of `safety` is `Passed`, but when executed alone is `(no files to check)Skipped`.

I haven't changed anything else except the command. It may be something in our CI that I'm not aware but I'm putting down my keyboard until tomorrow. Appreciate any time you may spend looking at it.

**Comment by asottile** [comment]
(on phone, sorry for no link) the docs for pre-commit run cover this, by default `pre-commit run` only runs on the changed staged files

**Comment by mattcanty** [comment]
Got it. I'd misunderstood `--all-files`, makes total sense now. I must have been tired yesterday!

Thanks for your help. We've made significant gains with the changes in place now. :-D

**Comment by asottile** [comment]
No problem!  Happy to help and thank you for the issue :tada:
