### ISSUE TITLE
How to apply pre-commit only to master?

### ISSUE THREAD

**Issue by tamuhey** [pre-commit/pre-commit#984]
Thanks for this cool tool!

I want to apply pre-commit only to master, but I don't know how to configure in .precommit-configure.yaml.

Should I ` git commit --no-verify` in other branches?

**Comment by asottile** [comment]
There's a [`pre-commit install --allow-missing-config`](https://pre-commit.com/#pre-commit-install) option which allows feature branches to bypass until they've been updated with master

Does that satisfy your usecase?

**Comment by tamuhey** [comment]
@asottile very good, thanks!!!

**Comment by asottile** [comment]
perfect! thanks for the issue 🎉
