### ISSUE TITLE
Error when building RPM

### ISSUE THREAD

**Issue by tim77** [pre-commit/pre-commit#985]
When building RPM for Fedora i got this:

`*** ERROR: ambiguous python shebang in /usr/lib/python3.7/site-packages/pre_commit/resources/hook-tmpl: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.`

Would be great if this fixed.

**Comment by asottile** [comment]
The value there doesn't actually matter, it gets replaced out when the file is created on `pre-commit install` [here](https://github.com/pre-commit/pre-commit/blob/da00fa98f9e274e2d3ef8f756566f1946dc79e36/pre_commit/commands/install_uninstall.py#L110) - for now it's purpose is mostly for editor / linter integration

If you'd like to make a PR, changing it to `env python3` will work if you change both references 👍

**Comment by asottile** [comment]
Thanks again for the issue and fix 🎉  -- this should make it into the next release that I plan to put together later today

**Comment by tim77** [comment]
Awesome. Thank you!
