### ISSUE TITLE
Wildcard file globbing matching in subdirectory (2 levels or deeper)

### ISSUE THREAD

**Issue by AnthonyWC** [pre-commit/pre-commit#988]
I looked through the doc but it looks like currently the files wildcard syntax doesn't support any type of file globbing for subdirectory that are 2 level or deeper.

e.g: this matches 1 level of subdirectory down
`files: .*/.*\.json$`

but neither

`files: .*/**/.*\.json$`

or 

`files: .*/*.*/.*\.json$`

would match anything 2 levels or deeper.

**Comment by asottile** [comment]
They are not wildcards or globs, they are [regular expressions](https://pre-commit.com/#regular-expressions)

**Comment by asottile** [comment]
Hope this answers your question!

If you need help with a regex, here's one which requires two levels of directories (two slashes), then any number more:

```yaml
files: .*/.*/.*\.json
```
