### ISSUE TITLE
Question: How to change working directory in `system` language hook

### ISSUE THREAD

**Issue by Ginkooo** [pre-commit/pre-commit#989]
Hello, I want to run `python manage.py` from system hook, but `manage.py` is in another directory. So I tried providing entry like:

`cd RestApi && python manage.py test`, but is says:

`cd` executable not found.

Is there any way to change directory while running `system` hook? I could write python `RestApi/manage.py`, but it fails during relative file lookups in the code.

**Comment by asottile** [comment]
`cd` is a shell builtin, not a program -- if you need a shell you'll need to make one, for example:

```yaml
entry: bash -c 'cd RestApi && python manage.py test'
```

**Comment by Ginkooo** [comment]
Is there any way to make it work under both Windows and Linux?

**Comment by asottile** [comment]
`git` on windows ships with bash so that ~should be reasonably cross platform

If you're concerned about bash, you could also use something more cross platform such as:

```yaml
entry: python -c 'import os; os.chdir("RestApi"); os.execvp("python", ("python", "manage.py", "test"))'
```

**Comment by Ginkooo** [comment]
Thank you! That solves my problem :)

**Comment by asottile** [comment]
awesome!  Thanks for the issue :tada:

**Comment by jmaclean-zaizi** [comment]
- have reviewed all
- fine!
