### ISSUE TITLE
support vendored python

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit#990]
I'm working on a monorepo project that has vendored python (like, the python binaries, all the builtin packages, all the 3rd party packages, etc). I'm trying to get pre-commit working with this repo and I think I'm really close, but there's at least one more issue left.

What I've done so far:

- Installed pre-commit in the vendored packages
- Installed pre-commit-hooks in the vendored packages
- Updated the repo's bootstrap scripts to run `run_python.sh -m pre_commit install --allow-missing-config` (the `--allow-missing-config` is to allow this to gently propagate to all the various branches) (`run_python.sh` is a script in the repo that checks what platform you're running on and runs the appropriate vendored python for you)
- Created a pre-commit config file that runs our custom hooks plus the vendored pre-commit-hooks hooks (see https://gist.github.com/guykisel/4393b32a084796fd38f5adf50ea5687e)

What I think is left:

- The generated `pre-commit` script has a `#!/usr/bin/env python` shebang, but this assumes that the user has python installed on their system, not just vendored in the repo. What I think needs to be done is to modify this shebang in the template to instead use the same path as `INSTALL_PYTHON` in the generated script. Does that make sense? I think I could do this in my own bootstrap scripts as a postprocessing step after installing pre-commit, but it might be better to just fix this upstream in pre-commit itself.

I suspect this is not a common use case, so I'd understand if you'd rather not support this :)

**Comment by asottile** [comment]
:wave: long time no see :D

Makes sense, the shebang in that hook though isn't used for runtime (other than finding `INSTALL_PYTHON`, etc,).  Using `INSTALL_PYTHON` for that shebang also isn't the best as that python can often be ephemeral and then the script would be irreversibly broken (imagine creating from an emphemeral virtualenv).

Your best bet is probably some sort of post-processing of that script, fortunately the python that runs the script doesn't matter _too_ much so long as it's ~some python

**Comment by guykisel** [comment]
👋 wasn't sure if you'd remember me :P

I guess another option would be to have a `--interpreter-path` arg for `pre-commit install` or something along those lines. I can't imagine any other use case for this though.

That sounds good, I'll give the post-processing a shot. Thanks for the quick reply!

**Comment by guykisel** [comment]
Got it working. Post-processing worked fine, but what ended up working even better in this particular use case (since we already had some custom pre-commit hooks installed for this repo) was to actually just vendor the python script that pre-commit generates and have our pre-commit hook call that python script using the vendored python, which means no need to mess with the shebang. 

At this point I'm not really taking advantage of most of the cool features of pre-commit for autoupdating hooks or isolating hooks and such, but it is still a nice source of premade hooks and a hook runner :)

**Comment by asottile** [comment]
Sounds great!  good to hear you got it working :tada:

**Comment by guykisel** [comment]
🎉 Thanks for the help!
