### ISSUE TITLE
improve file modification detection perf for large repos

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit#994]
I'm working on a git repo that's extremely large. I've noticed that pre-commit is a lot slower than it is on smaller repos. Through some basic profiling, it seems that at least one source of slowness is the file modification detection in `pre_commit.commands.run._run_single_hook`:
```
    diff_before = cmd_output(
        'git', 'diff', '--no-ext-diff', retcode=None, encoding=None,
    )
    retcode, stdout, stderr = hook.run(
        tuple(filenames) if hook.pass_filenames else (),
    )
    diff_after = cmd_output(
        'git', 'diff', '--no-ext-diff', retcode=None, encoding=None,
    )

    file_modifications = diff_before != diff_after
```
In a normal git repo, `git diff --no-ext-diff` is fast. Unfortunately, on this repo it averages two seconds per `git diff --no-ext-diff` call. Note this is on Windows 10 in MinGW with git version 2.12.0.windows.1 - other OSes/environments/git versions may not suffer from this regardless of repo size.

Possible improvements:

1. Check the filesize / hash / modified time of each staged file before / after running hooks
2. Run `git diff` specifically on the staged files
3. Cache the `git diff --no-ext-diff` output so that we only have to run it once per hook instead of twice per hook

If any of these (or other potential solutions) sound good I'm happy to work on a PR and test them out.

**Comment by asottile** [comment]
1 and 2 aren't valid as hooks could modify files which aren't staged and that should still trigger a failure -- in some cases this would also make it _slower_ as lots of staged files would need to be split up into multiple calls with `xargs`

3 seems reasonable, I had a branch which implemented this at some point but when I profiled it it didn't seem to make a difference -- if you can demonstrate an improvement here then definitely let's do it :tada:!

**Comment by guykisel** [comment]
> hooks could modify files which aren't staged and that should still trigger a failure
Interesting, I haven't seen tools that do this, but I guess it's a possibility :P

What are your thoughts on doing the file modification check at the start/end of `pre-commit` execution instead of doing it on a per-hook basis? Or maybe making hooks declare that they can modify files in their hook metadata so that we only pay the diff cost if we expect modifications?

**Comment by asottile** [comment]
> What are your thoughts on doing the file modification check at the start/end of pre-commit execution instead of doing it on a per-hook basis?

then you wouldn't know what hooks make the change

> Or maybe making hooks declare that they can modify files in their hook metadata so that we only pay the diff cost if we expect modifications?

that would be a major breaking change and boilerplate for the sake of boilerplate when the framework can already detect it -- I don't want to do that


----

I think this might be a platform-specific `git` bug as well, I'm not seeing the same slowdowns on linux for an extremely large repository

**Comment by asottile** [comment]
> > hooks could modify files which aren't staged and that should still trigger a failure
> 
> Interesting, I haven't seen tools that do this, but I guess it's a possibility :P

One example is https://github.com/asottile/seed-isort-config (for example)

**Comment by guykisel** [comment]
Cool, thanks for all the info and thoughts :)

And yeah, from my research it does seem to be a Windows-specific issue. Unfortunately, in the games industry, working on Windows is a given.

**Comment by asottile** [comment]
totally makes sense :) that's why I run windows at home too :laughing:

**Comment by guykisel** [comment]
After a bunch of testing I've been unable to noticeably improve perf on this. For my own use case I ended up just directly shelling out to run `pre_commit_hooks.trailing_whitespace_fixer` and so on through a custom pre-commit script :( 

@asottile if it's okay with you I think this issue can be reasonably closed as won't-fix since it's a perf issue in git itself (on windows), not in pre-commit.

**Comment by asottile** [comment]
:S bummer!
